import type {ChiefFirstPrepareViewV1} from "./contracts";
import {leadershipDigest,leadershipStableSerialize} from "./determinism";
export type ChiefCommunicationRoleV1="bottom-line"|"material-change"|"current-priority"|"hidden-tension"|"possible-surprise"|"suggested-question"|"uncertainty"|"progressive-reasoning"|"competing-explanation"|"evidence-detail";
export type ChiefCommunicationPlanItemV1={itemId:string;semanticSourceId:string;role:ChiefCommunicationRoleV1;originalContent:string;renderedContent:string;normalizedContent:string;lineage:string[];permissionScope:{organizationId:string;questionId:string};confidencePreserved:true;presentation:"sentence"|"bullet"|"comparison"|"evidence-gap"|"audit"};
export type ChiefCommunicationPlanV1={contractVersion:"1";authority:"non-authoritative-product-communication";organizationId:string;questionId:string;sourceViewDigest:string;items:ChiefCommunicationPlanItemV1[];omitted:Array<{role:ChiefCommunicationRoleV1;reason:"unsupported-empty"|"duplicate"|"role-limit"}>;metrics:{encounteredOntologyTerms:number;translatedOntologyTerms:number;untranslatedOntologyTerms:number;ambiguousTranslations:number}};
export function normalizeChiefCommunication(value:string){return value.normalize("NFKC").toLowerCase().replace(/[“”‘’]/g,"'").replace(/[^\p{L}\p{N}%'-]+/gu," ").trim().replace(/\s+/g," ")}
const ontology:ReadonlyArray<readonly[RegExp,string]>=[[/Governance Friction/gi,"approval friction"],[/Decision Latency/gi,"slow decisions"],[/Accountability Gap/gi,"unclear ownership"],[/Decision Flow/gi,"decision flow"],[/Coordination System/gi,"cross-team coordination"],[/Execution Capacity/gi,"delivery capacity"],[/Leadership Dependency/gi,"dependence on senior leaders"],[/Strategic Alignment/gi,"shared strategic direction"]];
function translate(value:string){let rendered=value,encountered=0,translated=0;for(const[pattern,replacement]of ontology){const count=rendered.match(pattern)?.length??0;if(count){encountered+=count;translated+=count;rendered=rendered.replace(pattern,replacement)}}return{rendered,encountered,translated}}
export function compileChiefCommunicationPlanV1(view:ChiefFirstPrepareViewV1):ChiefCommunicationPlanV1{const lineage=[view.provenance.authorizedProjectionRevision,view.provenance.authorizedProjectionDigest,view.provenance.preparedWorkProductVersionId,...view.provenance.sourceRevisionReferences],candidates:Array<[ChiefCommunicationRoleV1,string[],number]>=[["bottom-line",view.whatMattersNow.slice(0,1),1],["hidden-tension",view.hiddenTension,1],["material-change",view.whatChanged,3],["current-priority",view.whatMattersNow.slice(1),2],["possible-surprise",view.possibleSurprise,1],["suggested-question",view.questions,3],["uncertainty",view.uncertainty,3],["progressive-reasoning",view.reasoning,3],["competing-explanation",view.competingExplanations,3],["evidence-detail",view.sourceBasis.map(item=>item.label),3]],items:ChiefCommunicationPlanItemV1[]=[],omitted:ChiefCommunicationPlanV1["omitted"]=[],seen=new Map<string,string>();let encountered=0,translated=0;for(const[role,values,limit]of candidates){if(!values.length)omitted.push({role,reason:"unsupported-empty"});for(const[index,originalContent]of values.entries()){if(index>=limit){omitted.push({role,reason:"role-limit"});continue}const normalizedContent=normalizeChiefCommunication(originalContent);if(seen.has(normalizedContent)){omitted.push({role,reason:"duplicate"});continue}const result=translate(originalContent);encountered+=result.encountered;translated+=result.translated;const semanticSourceId=`${role}:${leadershipDigest(leadershipStableSerialize({originalContent,lineage}))}`,itemId=`chief-communication-item:${leadershipDigest(leadershipStableSerialize({semanticSourceId,role}))}`;seen.set(normalizedContent,itemId);items.push({itemId,semanticSourceId,role,originalContent,renderedContent:result.rendered,normalizedContent,lineage,permissionScope:{organizationId:view.organizationId,questionId:view.questionId},confidencePreserved:true,presentation:role==="hidden-tension"?"comparison":role==="uncertainty"?"evidence-gap":role==="evidence-detail"?"audit":role==="bottom-line"?"sentence":"bullet"})}}return{contractVersion:"1",authority:"non-authoritative-product-communication",organizationId:view.organizationId,questionId:view.questionId,sourceViewDigest:leadershipDigest(leadershipStableSerialize(view)),items,omitted,metrics:{encounteredOntologyTerms:encountered,translatedOntologyTerms:translated,untranslatedOntologyTerms:encountered-translated,ambiguousTranslations:0}}}

export type ChiefCommunicationSectionB11V1="what-stands-out"|"what-changed"|"the-tension"|"what-could-surprise-you"|"what-to-do-next"|"what-would-help-most"|"question-worth-asking"|"what-i-do-not-know-yet"|"why-this-is-my-view"|"another-explanation"|"evidence-behind-this";
export type ChiefCommunicationPlanItemB11V1=ChiefCommunicationPlanItemV1&{section:ChiefCommunicationSectionB11V1;surface:"first"|"progressive"};
export type ChiefCommunicationPlanB11V1={contractVersion:"1.1";authority:"non-authoritative-product-communication";organizationId:string;questionId:string;sourceViewDigest:string;acceptedB1PlanDigest:string;items:ChiefCommunicationPlanItemB11V1[];omitted:Array<{itemId:string;reason:"generic-audit-label"|"contained-repetition"}>;metrics:ChiefCommunicationPlanV1["metrics"]};

const B11_FIRST_ROLES=new Set<ChiefCommunicationRoleV1>(["bottom-line","material-change","current-priority","hidden-tension","possible-surprise","suggested-question","uncertainty"]);
const GENERIC_AUDIT_LABEL="current authorized cognition projection";
const B11_GLOSSARY:ReadonlyArray<readonly[RegExp,string]>=[[/Weak Knowledge Transfer/gu,"weak knowledge sharing"],[/Knowledge Fragmentation/gu,"scattered knowledge"],[/Knowledge Continuity/gu,"continuity of shared knowledge"],[/Coordination Breakdown/gu,"breakdown in coordination"],[/Unclassified Organizational Mechanism/gu,"unclassified organizational factor"]];
function translateB11(value:string){let rendered=value,encountered=0,translated=0;for(const[pattern,replacement]of B11_GLOSSARY){const count=rendered.match(pattern)?.length??0;if(count){encountered+=count;translated+=count;rendered=rendered.replace(pattern,replacement)}}return{rendered,encountered,translated}}
function sectionForB11(item:ChiefCommunicationPlanItemV1,hasTension:boolean):ChiefCommunicationSectionB11V1{
  if(item.role==="suggested-question")return"question-worth-asking";
  if(item.role==="uncertainty")return item.renderedContent.trim().endsWith("?")?"what-i-do-not-know-yet":"what-would-help-most";
  if(item.role==="progressive-reasoning")return"why-this-is-my-view";
  if(item.role==="competing-explanation")return"another-explanation";
  if(item.role==="evidence-detail")return"evidence-behind-this";
  if(item.role==="current-priority")return"what-to-do-next";
  if(hasTension&&["hidden-tension","material-change","possible-surprise"].includes(item.role))return"the-tension";
  if(item.role==="material-change")return"what-changed";
  if(item.role==="possible-surprise")return"what-could-surprise-you";
  if(item.role==="bottom-line"&&/no material change/iu.test(item.renderedContent))return"what-changed";
  return"what-stands-out";
}

export function compileChiefCommunicationPlanB11V1(view:ChiefFirstPrepareViewV1):ChiefCommunicationPlanB11V1{
  const accepted=compileChiefCommunicationPlanV1(view),hasTension=accepted.items.some(item=>item.role==="hidden-tension"),hiddenText=accepted.items.filter(item=>item.role==="hidden-tension").map(item=>normalizeChiefCommunication(item.renderedContent)),hasFirstConclusion=accepted.items.some(item=>["bottom-line","material-change","current-priority","hidden-tension","possible-surprise"].includes(item.role)),omitted:ChiefCommunicationPlanB11V1["omitted"]=[],items:ChiefCommunicationPlanItemB11V1[]=[];let extraEncountered=0,extraTranslated=0,promotedReason=false;
  for(const item of accepted.items){
    if(item.role==="evidence-detail"&&normalizeChiefCommunication(item.renderedContent)===GENERIC_AUDIT_LABEL){omitted.push({itemId:item.itemId,reason:"generic-audit-label"});continue;}
    if(hasTension&&["material-change","possible-surprise","competing-explanation"].includes(item.role)&&hiddenText.some(value=>value.includes(normalizeChiefCommunication(item.renderedContent)))){omitted.push({itemId:item.itemId,reason:"contained-repetition"});continue;}
    const result=translateB11(item.renderedContent);extraEncountered+=result.encountered;extraTranslated+=result.translated;const promote=!hasFirstConclusion&&!promotedReason&&item.role==="progressive-reasoning";if(promote)promotedReason=true;items.push({...item,renderedContent:result.rendered,section:promote?"what-stands-out":sectionForB11(item,hasTension),surface:B11_FIRST_ROLES.has(item.role)||promote?"first":"progressive"});
  }
  return{contractVersion:"1.1",authority:accepted.authority,organizationId:accepted.organizationId,questionId:accepted.questionId,sourceViewDigest:accepted.sourceViewDigest,acceptedB1PlanDigest:leadershipDigest(leadershipStableSerialize(accepted)),items,omitted,metrics:{encounteredOntologyTerms:accepted.metrics.encounteredOntologyTerms+extraEncountered,translatedOntologyTerms:accepted.metrics.translatedOntologyTerms+extraTranslated,untranslatedOntologyTerms:accepted.metrics.untranslatedOntologyTerms-extraTranslated,ambiguousTranslations:0}};
}
