import type { ProductQuestionWorkspaceV2 } from "../frontendReadinessContracts";
import { productArtifactBodyDigest, type ProductArtifactBodyRefV1 } from "../../persistence/productArtifactBodyContracts";
import type { ProductArtifactMaterialLineageV1 } from "../productArtifactInspectionMetadataContracts";
import type { FuturePreparationItemStateV1, ProductArtifactCurrentAccessResultV1 } from "../productArtifactCurrentAccessContracts";
import type { LeadershipConversationCanonicalChangeFactsV1, LeadershipConversationCanonicalRoutingReceiptV1 } from "./canonicalOwnerReceiptContracts";
import type {
  CanonicalProductMaterializationReceiptV1,
  LeadershipConversationProductMaterializationRecordV1,
} from "./canonicalProductMaterializationContracts";
import { leadershipId } from "./determinism";
import type { HistoricalCheckpointLifecycleLinkReceiptV1, HistoricalCheckpointLifecycleLinkV1 } from "./historicalCheckpointLifecycleLinkContracts";

export const LEADERSHIP_CONVERSATION_CONTRACT_VERSION = "1" as const;
export type DigestAudit = { idempotencyKeyDigest: string; requestFingerprint: string; contentDigest: string };
export type LeadershipConversationContextV1 = DigestAudit & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;contextVersionId:string;contextVersion:number;predecessorContextVersionId:string|null;conversationType:"leadership-conversation";scenarioId:"northstar-recurring-cross-functional-staff-conversation";title:string;purpose:string;intendedOutcome:string;timeframe:string;participants:Array<{participantRef:string;displayName:string;titleLabel:string}>;leaderContext:string|null;recordedAt:string;recordedByUserId:string };
export type PreparedWorkProductContentV1 = { headline:string;situationSummary:string;whatChanged:string[];decisionsRequiringAttention:string[];importantTensions:string[];contradictions:string[];unknowns:string[];priorCommitments:string[];suggestedAgenda:string[];talkingPoints:string[];questionsToResolve:string[];evidenceReferences:string[];uncertaintyAndLimitations:string[];unavailableAreas:string[] };
export type PreparedWorkProductLineageV1 = { questionRevision:number;authorizedProjectionRevision:string;authorizedProjectionDigest:string;productCommunicationRevision:string;productCommunicationDigest:string;sourceRevisionReferences:string[];previousFrozenSnapshotId:string|null;canonicalChangeReceiptReferences:string[];canonicalUnderstandingRevisionId?:string;canonicalUnderstandingRevisionReceiptDigest?:string };
export type PreparedWorkProductV1 = DigestAudit & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;contextVersionId:string;artifactId:string;artifactVersionId:string;artifactVersion:number;predecessorArtifactVersionId:string|null;basedOnFrozenSnapshotId:string|null;content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;createdAt:string;createdBy:"product-communication"|"leader-edit";createdByUserId:string|null;changeSummary:string|null };
export type FrozenPreparedWorkProductSnapshotV1 = DigestAudit & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;contextVersionId:string;snapshotId:string;preparedWorkProductVersionId:string;content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;frozenAt:string;frozenByUserId:string;snapshotDigest:string };
export type ProductArtifactOwnerHeaderV1 = { contractVersion:"1";organizationId:string;semanticOwner:"leadership-conversation";artifactType:"prepared-work"|"frozen-snapshot"|"what-changed";artifactId:string;artifactRevision:string;productQuestionId:string;productWorkflowId:string;creationEnvelopeDigest:string;materialReferencesDigest:string;protectedBody:ProductArtifactBodyRefV1;ownerStageReceiptDigest:string;headerDigest:string };
export type PreparedWorkProductBodyV1 = { contractVersion:"1";content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;createdAt:string;createdBy:"product-communication"|"leader-edit";createdByUserId:string|null;changeSummary:string|null };
export type PreparedWorkProductPublicationV1 = ProductArtifactOwnerHeaderV1 & { artifactType:"prepared-work";contextVersionId:string;artifactVersion:number;predecessorArtifactVersionId:string|null;basedOnFrozenSnapshotId:string|null;materialLineage?:ProductArtifactMaterialLineageV1;publicationProofVersion?:"1";idempotencyKeyDigest:string;requestFingerprint:string };
export type FrozenPreparedWorkProductBodyV1 = { contractVersion:"1";sourcePreparedWorkBodyRef:ProductArtifactBodyRefV1;frozenAt:string;frozenByUserId:string };
export type FrozenPreparedWorkProductPublicationV1 = ProductArtifactOwnerHeaderV1 & { artifactType:"frozen-snapshot";contextVersionId:string;preparedWorkProductVersionId:string;materialLineage?:ProductArtifactMaterialLineageV1;publicationProofVersion?:"1";idempotencyKeyDigest:string;requestFingerprint:string;snapshotDigest:string };
export type LeadershipConversationPublicationReceiptV1 = { contractVersion:"1";receiptKind:"prepared-work-publication"|"frozen-checkpoint-publication";receiptId:string;organizationId:string;productQuestionId:string;productWorkflowId:string;artifactType:"prepared-work"|"frozen-snapshot";artifactId:string;artifactRevision:string;sourceArtifactId:string|null;sourceArtifactRevision:string|null;headerDigest:string;bodyRefDigest:string;materialLineageDigest:string;eventId:string;idempotencyKeyDigest:string;requestFingerprint:string;occurredAt:string;actorRef:string;receiptDigest:string };
export type LeadershipConversationPublicationV1=PreparedWorkProductPublicationV1|FrozenPreparedWorkProductPublicationV1;
export function completeLeadershipConversationPublicationReceiptV1(input:Omit<LeadershipConversationPublicationReceiptV1,"receiptDigest">):LeadershipConversationPublicationReceiptV1{return{...input,receiptDigest:productArtifactBodyDigest(input)}}
export function assertLeadershipConversationPublicationProofV1(input:{publication:LeadershipConversationPublicationV1;event:LeadershipConversationWorkflowEventV1;receipt:LeadershipConversationPublicationReceiptV1;sourcePublication?:PreparedWorkProductPublicationV1}):void{const{publication,event,receipt,sourcePublication}=input,prepared=publication.artifactType==="prepared-work",kind=prepared?"prepared-work-publication":"frozen-checkpoint-publication",eventType=prepared?"prepared-work-product-version-recorded":"prepared-work-product-frozen",sourceId=prepared?null:sourcePublication?.artifactId??null,sourceRevision=prepared?null:sourcePublication?.artifactRevision??null,recordRef=prepared?publication.artifactRevision:publication.artifactId,expectedReceiptId=leadershipId("leadership-publication-receipt",kind,recordRef,event.eventId),{receiptDigest,...unsigned}=receipt;const valid=publication.publicationProofVersion==="1"&&receipt.contractVersion==="1"&&receipt.receiptKind===kind&&receipt.organizationId===publication.organizationId&&receipt.productQuestionId===publication.productQuestionId&&receipt.productWorkflowId===publication.productWorkflowId&&receipt.artifactType===publication.artifactType&&receipt.artifactId===publication.artifactId&&receipt.artifactRevision===publication.artifactRevision&&receipt.sourceArtifactId===sourceId&&receipt.sourceArtifactRevision===sourceRevision&&(!sourcePublication||publication.artifactType==="frozen-snapshot"&&publication.preparedWorkProductVersionId===sourcePublication.artifactRevision)&&receipt.headerDigest===publication.headerDigest&&receipt.bodyRefDigest===publication.protectedBody.refDigest&&receipt.materialLineageDigest===publication.materialLineage?.envelopeDigest&&receipt.eventId===event.eventId&&receipt.idempotencyKeyDigest===publication.idempotencyKeyDigest&&receipt.requestFingerprint===publication.requestFingerprint&&receipt.occurredAt===event.occurredAt&&receipt.actorRef===event.actorRef&&receipt.receiptId===expectedReceiptId&&receiptDigest===productArtifactBodyDigest(unsigned)&&event.contractVersion==="1"&&event.organizationId===publication.organizationId&&event.questionId===publication.productQuestionId&&event.eventType===eventType&&event.recordRef===recordRef&&event.idempotencyKeyDigest===publication.idempotencyKeyDigest&&event.requestFingerprint===publication.requestFingerprint;if(!valid)throw new Error("Leadership Conversation publication proof is invalid.");}
export type ConversationUploadReceiptV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;frozenSnapshotId:string;uploadReceiptId:string;sourceBindingId:string;sourceContentVersionId:string;sourceBindingMutationReceiptDigest:string;mediaType:"text/plain"|"text/markdown";byteLength:number;exactContentDigest:string;normalizedContentDigest:string;sourceContentWriteReceiptDigest:string;displayLabel:string|null;originalFilename:string|null;duplicateClassification:"stored"|"idempotent-replay"|"exact-duplicate"|"normalized-equivalent";uploadedAt:string;uploadedByUserId:string };
export type ProposalKind = "evidence-candidate"|"decision-draft"|"outcome-observation"|"unknown"|"follow-up-question"|"commitment"|"assumption-change"|"correction"|"learning-observation";
export type TakeawayProposalEnvelopeV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;frozenSnapshotId:string;uploadReceiptId:string;sourceBindingId:string;sourceContentVersionId:string;proposalId:string;proposalOrdinal:number;kind:ProposalKind;targetOwner:string;routingPolicy:string;payload:{summary:string;targetRef:string|null};payloadDigest:string;sourceExcerptReferences:Array<{startByte:number;endByte:number}>;proposedAt:string;proposedBy:"northstar-fixture";proposedByUserId:string|null };
export type ProposalDisposition = "approved"|"approved-with-edit"|"rejected"|"deferred"|"duplicate";
export type TakeawayProposalDispositionReceiptV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;dispositionReceiptId:string;proposalId:string;originalPayloadDigest:string;disposition:ProposalDisposition;effectivePayload:TakeawayProposalEnvelopeV1["payload"]|null;effectivePayloadDigest:string|null;duplicateProposalId:string|null;reason:string|null;reviewedAt:string;reviewedByUserId:string;reviewRevision:number };
export type CanonicalOwnerRoutingLinkV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;routingLinkId:string;proposalId:string;dispositionReceiptId:string;targetOwner:string;integrationReceiptId:string;integrationReceiptDigest:string;compatibilityReferences:string[];routedAt:string };
export type LeadershipConversationChangeReceiptLinkV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;changeLinkId:string;routingLinkIds:string[];integrationReceiptId:string;changeFacts:LeadershipConversationCanonicalChangeFactsV1;classification:"changed"|"unchanged"|"undetermined";linkedAt:string };
export type FuturePreparationLinkV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;futurePreparationLinkId:string;sourceFrozenSnapshotId:string;sourceUploadReceiptId:string;approvedProposalIds:string[];canonicalRoutingLinkIds:string[];canonicalChangeReceiptRef:string;canonicalUnderstandingRevisionId?:string;canonicalUnderstandingRevisionReceiptDigest?:string;nextConversationId:string;nextContextVersionId:string;nextPreparedWorkProductVersionId:string;linkedAt:string };
export type LeadershipConversationWorkflowEventType = "context-recorded"|"prepared-work-product-version-recorded"|"prepared-work-product-frozen"|"conversation-upload-received"|"takeaway-proposal-recorded"|"takeaway-disposition-recorded"|"canonical-routing-receipt-recorded"|"canonical-owner-routing-linked"|"change-receipt-linked"|"future-preparation-linked"|"canonical-product-materialization-recorded"|"historical-checkpoint-lifecycle-link-published";
export type LeadershipConversationWorkflowEventV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;eventId:string;eventSequence:number;previousEventId:string|null;eventType:LeadershipConversationWorkflowEventType;recordRef:string;recordDigest:string;occurredAt:string;actorType:"user"|"system";actorRef:string|null };
export type LeadershipConversationArtifactStoreV1 = { contractVersion:"1";organizationId:string;contexts:LeadershipConversationContextV1[];preparedWorkProducts:PreparedWorkProductV1[];frozenSnapshots:FrozenPreparedWorkProductSnapshotV1[];preparedWorkPublications?:PreparedWorkProductPublicationV1[];frozenSnapshotPublications?:FrozenPreparedWorkProductPublicationV1[];publicationReceipts?:LeadershipConversationPublicationReceiptV1[];whatChangedPublications?:ProductArtifactOwnerHeaderV1[];uploadReceipts:ConversationUploadReceiptV1[];proposals:TakeawayProposalEnvelopeV1[];dispositions:TakeawayProposalDispositionReceiptV1[];canonicalRoutingReceipts:LeadershipConversationCanonicalRoutingReceiptV1[];routingLinks:CanonicalOwnerRoutingLinkV1[];changeLinks:LeadershipConversationChangeReceiptLinkV1[];futurePreparationLinks:FuturePreparationLinkV1[];productMaterializations?:LeadershipConversationProductMaterializationRecordV1[];productMaterializationReceipts?:CanonicalProductMaterializationReceiptV1[];historicalCheckpointLifecycleLinks?:HistoricalCheckpointLifecycleLinkV1[];historicalCheckpointLifecycleLinkReceipts?:HistoricalCheckpointLifecycleLinkReceiptV1[];events:LeadershipConversationWorkflowEventV1[];idempotency:Array<{keyDigest:string;requestFingerprint:string;recordRef:string}>;storeDigest:string };
export type LeadershipConversationStepV1 = "set-up"|"prepare"|"freeze"|"capture"|"review"|"what-changed"|"prepare-again";
export type LeadershipConversationActionV1 = { id:"record-context"|"create-preparation"|"edit-preparation"|"freeze-preparation"|"upload-source"|"generate-proposals"|"review-proposal"|"route-approved"|"prepare-again"|"reset-development";enabled:boolean;requiredAuthority:string;blockedReason:string|null };
export type LeadershipConversationWorkspaceV1 = { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;base:ProductQuestionWorkspaceV2;currentStep:LeadershipConversationStepV1;context:LeadershipConversationContextV1|null;currentPreparedWorkProduct:PreparedWorkProductV1|null;frozenSnapshot:FrozenPreparedWorkProductSnapshotV1|null;uploadReceipt:ConversationUploadReceiptV1|null;proposals:TakeawayProposalEnvelopeV1[];dispositions:TakeawayProposalDispositionReceiptV1[];canonicalRoutingReceipts:LeadershipConversationCanonicalRoutingReceiptV1[];routingLinks:CanonicalOwnerRoutingLinkV1[];changeReceiptLink:LeadershipConversationChangeReceiptLinkV1|null;futurePreparationLink:FuturePreparationLinkV1|null;actions:LeadershipConversationActionV1[];unavailableFields:string[];withheldFields:string[];auditReferences:string[] };
export type ChiefFirstPrepareActivationV1={contractVersion:"1";organizationId:string;questionId:string;meetingTitle:string;timeframe:string;role:string;purpose:string;authorizedSourceRefs:string[];idempotencyKey:string};
export type ChiefFirstPrepareViewV1={contractVersion:"1";organizationId:string;questionId:string;seriesId:string;conversationId:string;meeting:{title:string;timeframe:string;role:string;purpose:string};whatChanged:string[];whatMattersNow:string[];hiddenTension:string[];possibleSurprise:string[];questions:string[];priorCycle:{status:"none";message:string};sourceBasis:Array<{sourceRef:string;label:string}>;uncertainty:string[];reasoning:string[];competingExplanations:string[];provenance:{contextVersionId:string;preparedWorkProductVersionId:string;authorizedProjectionRevision:string;authorizedProjectionDigest:string;sourceRevisionReferences:string[]};status:"non-authoritative";currentStep:LeadershipConversationStepV1};
export interface LeadershipConversationClock { now():string }

export type SafeProductArtifactProjectionV1={contractVersion:"1";artifactType:"prepared-work"|"frozen-snapshot"|"what-changed"|"product-decision-draft";artifactId:string;artifactRevision:string;title:string;summary:string;accessResultDigest:string};
export type LeadershipHistoryEntryV1={contractVersion:"1";artifactType:SafeProductArtifactProjectionV1["artifactType"];artifactId:string;artifactRevision:string;label:string;occurredAt:string;accessResultDigest:string};
export type CurrentAuthorizedLeadershipHistoryV1={contractVersion:"1";entries:LeadershipHistoryEntryV1[];historyDigest:string};
export type FuturePreparationItemV1={contractVersion:"1";artifactId:string;artifactRevision:string;state:FuturePreparationItemStateV1;accessResultDigest:string|null;semanticInfluence:boolean;ownerClassificationRef:string|null};
export type CurrentAuthorizedProductQuestionWorkspaceV1={contractVersion:"1";organizationId:string;questionId:string;subjectId:string;purpose:string;scopeDigest:string;sensitivity:"standard"|"restricted"|"private";evaluatedAt:string;artifacts:SafeProductArtifactProjectionV1[];history:CurrentAuthorizedLeadershipHistoryV1;accessResultDigests:string[];workspaceDigest:string};
export type CurrentArtifactDeliveryCandidateV1={access:ProductArtifactCurrentAccessResultV1;safeProjection:SafeProductArtifactProjectionV1|null;occurredAt:string;ownerState:"unchanged"|"changed"|"resolved"|"superseded"|null};
