import type { ProductQuestionWorkspaceV2 } from "../frontendReadinessContracts";
import { productArtifactBodyDigest, type ProductArtifactBodyRefV1 } from "../../persistence/productArtifactBodyContracts";
import type { ProductArtifactMaterialLineageV1 } from "../productArtifactInspectionMetadataContracts";
import type { FuturePreparationItemStateV1, ProductArtifactCurrentAccessResultV1 } from "../productArtifactCurrentAccessContracts";
import type { LeadershipConversationCanonicalChangeFactsV1, LeadershipConversationCanonicalRoutingReceiptV1 } from "./canonicalOwnerReceiptContracts";
import type {
  CanonicalProductMaterializationReceiptV1,
  LeadershipConversationProductMaterializationRecordV1,
} from "./canonicalProductMaterializationContracts";
import { leadershipId } from "./determinism";
import type { HistoricalCheckpointLifecycleLinkReceiptV1, HistoricalCheckpointLifecycleLinkV1 } from "./historicalCheckpointLifecycleLinkContracts";
import type { GovernedScopeRef } from "../../../engine/v3/governance/scopedGovernanceContext";

export const LEADERSHIP_CONVERSATION_CONTRACT_VERSION = "1" as const;
export type DigestAudit = { idempotencyKeyDigest: string; requestFingerprint: string; contentDigest: string };
export type LeadershipConversationContextV1 = DigestAudit & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;contextVersionId:string;contextVersion:number;predecessorContextVersionId:string|null;conversationType:"leadership-conversation";scenarioId:"northstar-recurring-cross-functional-staff-conversation";title:string;purpose:string;intendedOutcome:string;timeframe:string;participants:Array<{participantRef:string;displayName:string;titleLabel:string}>;leaderContext:string|null;recordedAt:string;recordedByUserId:string };
export type PreparedWorkProductContentV1 = { headline:string;situationSummary:string;whatChanged:string[];decisionsRequiringAttention:string[];importantTensions:string[];contradictions:string[];unknowns:string[];priorCommitments:string[];suggestedAgenda:string[];talkingPoints:string[];questionsToResolve:string[];evidenceReferences:string[];uncertaintyAndLimitations:string[];unavailableAreas:string[] };
export type PreparedWorkProductLineageV1 = { questionRevision:number;authorizedProjectionRevision:string;authorizedProjectionDigest:string;productCommunicationRevision:string;productCommunicationDigest:string;sourceRevisionReferences:string[];previousFrozenSnapshotId:string|null;canonicalChangeReceiptReferences:string[];canonicalUnderstandingRevisionId?:string;canonicalUnderstandingRevisionReceiptDigest?:string };
export type PreparedWorkProductV1 = DigestAudit & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;contextVersionId:string;artifactId:string;artifactVersionId:string;artifactVersion:number;predecessorArtifactVersionId:string|null;basedOnFrozenSnapshotId:string|null;content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;createdAt:string;createdBy:"product-communication"|"leader-edit";createdByUserId:string|null;changeSummary:string|null };
export type FrozenPreparedWorkProductSnapshotV1 = DigestAudit & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;contextVersionId:string;snapshotId:string;preparedWorkProductVersionId:string;content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;frozenAt:string;frozenByUserId:string;snapshotDigest:string };
export type ProductArtifactOwnerHeaderV1 = { contractVersion:"1";organizationId:string;semanticOwner:"leadership-conversation";artifactType:"prepared-work"|"frozen-snapshot"|"what-changed";artifactId:string;artifactRevision:string;productQuestionId:string;productWorkflowId:string;creationEnvelopeDigest:string;materialReferencesDigest:string;protectedBody:ProductArtifactBodyRefV1;ownerStageReceiptDigest:string;headerDigest:string };
export type PreparedWorkProductBodyV1 = { contractVersion:"1";content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;createdAt:string;createdBy:"product-communication"|"leader-edit";createdByUserId:string|null;changeSummary:string|null };
export type PreparedWorkProductPublicationV1 = ProductArtifactOwnerHeaderV1 & { artifactType:"prepared-work";contextVersionId:string;artifactVersion:number;predecessorArtifactVersionId:string|null;basedOnFrozenSnapshotId:string|null;materialLineage?:ProductArtifactMaterialLineageV1;publicationProofVersion?:"1";idempotencyKeyDigest:string;requestFingerprint:string };
export type PrivateWorkingContributionBodyV1={contractVersion:"1";organizationId:string;questionId:string;conversationId:string;seriesId:string;occurrenceId:string;contributedByUserId:string;authorizationRevision:string;provenanceDigest:string;contributionArtifactId:string;content:string;contentDigest:string;frozenAt:string};
export type PrivateWorkingContributionArtifactRefV1={contractVersion:"1";artifactId:string;artifactRevision:"1";contributionDigest:string};
export type PrivateWorkingContributionPublicationV1={contractVersion:"1";organizationId:string;questionId:string;conversationId:string;seriesId:string;occurrenceId:string;contributedByUserId:string;authorizationRevision:string;provenanceDigest:string;snapshotId:string;artifactId:string;artifactRevision:"1";protectedBody:ProductArtifactBodyRefV1;ownerStageReceiptDigest:string;contributionDigest:string;publishedAt:string;publicationDigest:string};
export type PrivateWorkingContributionReceiptV1={contractVersion:"1";receiptId:string;organizationId:string;questionId:string;conversationId:string;snapshotId:string;artifactId:string;artifactRevision:"1";bodyRefDigest:string;contributionDigest:string;idempotencyKeyDigest:string;requestFingerprint:string;receiptDigest:string};
export type PrivateWorkingContributionFreezeIntentV1={contractVersion:"1";organizationId:string;questionId:string;conversationId:string;preparedWorkProductVersionId:string;frozenAt:string;idempotencyKeyDigest:string;requestFingerprint:string;contributionRefs:PrivateWorkingContributionArtifactRefV1[];intentDigest:string};
export type PrivateWorkingContributionCaptureV1={contractVersion:"1";organizationId:string;questionId:string;conversationId:string;seriesId:string;occurrenceId:string;snapshotId:string;captureId:string;contributionRefs:PrivateWorkingContributionArtifactRefV1[];provenanceDigests:string[];authorizationRevisions:string[];capturedAt:string;capturedByUserId:string;reviewRequired:true;idempotencyKeyDigest:string;requestFingerprint:string;captureDigest:string};
export type PrivateWorkingContributionCaptureReceiptV1={contractVersion:"1";receiptId:string;organizationId:string;questionId:string;conversationId:string;snapshotId:string;captureId:string;contributionRefsDigest:string;idempotencyKeyDigest:string;requestFingerprint:string;receiptDigest:string};
export type FrozenPreparedWorkProductBodyV1 = { contractVersion:"1";sourcePreparedWorkBodyRef:ProductArtifactBodyRefV1;privateWorkingContributionBodyRefs?:ProductArtifactBodyRefV1[];frozenAt:string;frozenByUserId:string };
export type FrozenPreparedWorkProductPublicationV1 = ProductArtifactOwnerHeaderV1 & { artifactType:"frozen-snapshot";contextVersionId:string;preparedWorkProductVersionId:string;privateWorkingContributionRefs?:PrivateWorkingContributionArtifactRefV1[];materialLineage?:ProductArtifactMaterialLineageV1;publicationProofVersion?:"1";idempotencyKeyDigest:string;requestFingerprint:string;snapshotDigest:string };
export type LeadershipConversationPublicationReceiptV1 = { contractVersion:"1";receiptKind:"prepared-work-publication"|"frozen-checkpoint-publication";receiptId:string;organizationId:string;productQuestionId:string;productWorkflowId:string;artifactType:"prepared-work"|"frozen-snapshot";artifactId:string;artifactRevision:string;sourceArtifactId:string|null;sourceArtifactRevision:string|null;headerDigest:string;bodyRefDigest:string;materialLineageDigest:string;eventId:string;idempotencyKeyDigest:string;requestFingerprint:string;occurredAt:string;actorRef:string;receiptDigest:string };
export type LeadershipConversationPublicationV1=PreparedWorkProductPublicationV1|FrozenPreparedWorkProductPublicationV1;
export function completeLeadershipConversationPublicationReceiptV1(input:Omit<LeadershipConversationPublicationReceiptV1,"receiptDigest">):LeadershipConversationPublicationReceiptV1{return{...input,receiptDigest:productArtifactBodyDigest(input)}}
export function assertLeadershipConversationPublicationProofV1(input:{publication:LeadershipConversationPublicationV1;event:LeadershipConversationWorkflowEventV1;receipt:LeadershipConversationPublicationReceiptV1;sourcePublication?:PreparedWorkProductPublicationV1}):void{const{publication,event,receipt,sourcePublication}=input,prepared=publication.artifactType==="prepared-work",kind=prepared?"prepared-work-publication":"frozen-checkpoint-publication",eventType=prepared?"prepared-work-product-version-recorded":"prepared-work-product-frozen",sourceId=prepared?null:sourcePublication?.artifactId??null,sourceRevision=prepared?null:sourcePublication?.artifactRevision??null,recordRef=prepared?publication.artifactRevision:publication.artifactId,expectedReceiptId=leadershipId("leadership-publication-receipt",kind,recordRef,event.eventId),{receiptDigest,...unsigned}=receipt;const valid=publication.publicationProofVersion==="1"&&receipt.contractVersion==="1"&&receipt.receiptKind===kind&&receipt.organizationId===publication.organizationId&&receipt.productQuestionId===publication.productQuestionId&&receipt.productWorkflowId===publication.productWorkflowId&&receipt.artifactType===publication.artifactType&&receipt.artifactId===publication.artifactId&&receipt.artifactRevision===publication.artifactRevision&&receipt.sourceArtifactId===sourceId&&receipt.sourceArtifactRevision===sourceRevision&&(!sourcePublication||publication.artifactType==="frozen-snapshot"&&publication.preparedWorkProductVersionId===sourcePublication.artifactRevision)&&receipt.headerDigest===publication.headerDigest&&receipt.bodyRefDigest===publication.protectedBody.refDigest&&receipt.materialLineageDigest===publication.materialLineage?.envelopeDigest&&receipt.eventId===event.eventId&&receipt.idempotencyKeyDigest===publication.idempotencyKeyDigest&&receipt.requestFingerprint===publication.requestFingerprint&&receipt.occurredAt===event.occurredAt&&receipt.actorRef===event.actorRef&&receipt.receiptId===expectedReceiptId&&receiptDigest===productArtifactBodyDigest(unsigned)&&event.contractVersion==="1"&&event.organizationId===publication.organizationId&&event.questionId===publication.productQuestionId&&event.eventType===eventType&&event.recordRef===recordRef&&event.idempotencyKeyDigest===publication.idempotencyKeyDigest&&event.requestFingerprint===publication.requestFingerprint;if(!valid)throw new Error("Leadership Conversation publication proof is invalid.");}
export type ConversationUploadReceiptV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;frozenSnapshotId:string;uploadReceiptId:string;sourceBindingId:string;sourceContentVersionId:string;sourceBindingMutationReceiptDigest:string;mediaType:"text/plain"|"text/markdown";byteLength:number;exactContentDigest:string;normalizedContentDigest:string;sourceContentWriteReceiptDigest:string;displayLabel:string|null;originalFilename:string|null;duplicateClassification:"stored"|"idempotent-replay"|"exact-duplicate"|"normalized-equivalent";uploadedAt:string;uploadedByUserId:string };
export type ProposalKind = "evidence-candidate"|"decision-draft"|"outcome-observation"|"unknown"|"follow-up-question"|"commitment"|"assumption-change"|"correction"|"learning-observation";
export type GovernedConsequenceScopeBindingV1={contractVersion:"1";organizationId:string;scope:GovernedScopeRef;scopeOwnerContractVersion:"1";authorityRefs:string[];policyRefs:string[];authorizationContextRef:string;bindingDigest:string};
export function completeGovernedConsequenceScopeBindingV1(input:Omit<GovernedConsequenceScopeBindingV1,"bindingDigest">):GovernedConsequenceScopeBindingV1{const normalized={...input,scope:structuredClone(input.scope),authorityRefs:[...new Set(input.authorityRefs)].sort(),policyRefs:[...new Set(input.policyRefs)].sort()};if(normalized.contractVersion!=="1"||normalized.scopeOwnerContractVersion!=="1"||normalized.organizationId!==normalized.scope.organizationId||!normalized.scope.id||!normalized.authorityRefs.length||!normalized.policyRefs.length||!normalized.authorizationContextRef)throw new Error("Governed consequence scope binding is invalid.");return{...normalized,bindingDigest:productArtifactBodyDigest(normalized)}}
export function assertGovernedConsequenceScopeBindingV1(binding:GovernedConsequenceScopeBindingV1,organizationId?:string):void{if(!binding||typeof binding!=="object")throw new Error("Governed consequence scope binding is invalid.");const{bindingDigest,...unsigned}=binding,partition=organizationId??binding.organizationId;if(binding.contractVersion!=="1"||binding.scopeOwnerContractVersion!=="1"||binding.organizationId!==partition||binding.scope?.organizationId!==partition||!binding.scope.id||!binding.authorityRefs.length||!binding.policyRefs.length||bindingDigest!==productArtifactBodyDigest(unsigned))throw new Error("Governed consequence scope binding is invalid.");}
type TakeawayProposalEnvelopeCommon = Omit<DigestAudit,"contentDigest"> & { organizationId:string;questionId:string;conversationId:string;frozenSnapshotId:string;uploadReceiptId:string;sourceBindingId:string;sourceContentVersionId:string;proposalId:string;proposalOrdinal:number;kind:ProposalKind;targetOwner:string;routingPolicy:string;payload:{summary:string;targetRef:string|null};payloadDigest:string;sourceExcerptReferences:Array<{startByte:number;endByte:number}>;proposedAt:string;proposedBy:"northstar-fixture";proposedByUserId:string|null };
export type LegacyTakeawayProposalEnvelopeV1 = TakeawayProposalEnvelopeCommon & {contractVersion:"1";governedScopeBinding?:never};
export type GovernedTakeawayProposalEnvelopeV2 = TakeawayProposalEnvelopeCommon & {contractVersion:"2";governedScopeBinding:GovernedConsequenceScopeBindingV1};
export type TakeawayProposalEnvelopeV1 = LegacyTakeawayProposalEnvelopeV1|GovernedTakeawayProposalEnvelopeV2;
export type ProposalDisposition = "approved"|"approved-with-edit"|"rejected"|"deferred"|"duplicate";
export type TakeawayProposalDispositionReceiptV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;dispositionReceiptId:string;proposalId:string;originalPayloadDigest:string;sourceProposalContractVersion?:"1"|"2";governedScopeBindingDigest?:string;disposition:ProposalDisposition;effectivePayload:TakeawayProposalEnvelopeV1["payload"]|null;effectivePayloadDigest:string|null;duplicateProposalId:string|null;reason:string|null;reviewedAt:string;reviewedByUserId:string;reviewRevision:number };
export type CanonicalOwnerRoutingLinkV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;routingLinkId:string;proposalId:string;dispositionReceiptId:string;sourceProposalContractVersion?:"1"|"2";governedScopeBindingDigest?:string;targetOwner:string;integrationReceiptId:string;integrationReceiptDigest:string;compatibilityReferences:string[];routedAt:string };
export type LeadershipConversationChangeReceiptLinkV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;changeLinkId:string;routingLinkIds:string[];integrationReceiptId:string;changeFacts:LeadershipConversationCanonicalChangeFactsV1;classification:"changed"|"unchanged"|"undetermined";linkedAt:string };
export type FuturePreparationLinkV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;futurePreparationLinkId:string;sourceFrozenSnapshotId:string;sourceUploadReceiptId:string;approvedProposalIds:string[];canonicalRoutingLinkIds:string[];canonicalChangeReceiptRef:string;canonicalUnderstandingRevisionId?:string;canonicalUnderstandingRevisionReceiptDigest?:string;nextConversationId:string;nextContextVersionId:string;nextPreparedWorkProductVersionId:string;linkedAt:string };
export const CYCLE1_CLOSURE_SECTION_LABELS=["What was decided","What changed","What did not change","What remains unresolved","What should be watched","What the user owes","Checkpoint status"] as const;
export type Cycle1ClosureSectionLabelV1=typeof CYCLE1_CLOSURE_SECTION_LABELS[number];
export type Cycle1ClosureSectionV1={label:Cycle1ClosureSectionLabelV1;items:string[]};
export type Cycle1ClosureCompletionV1=DigestAudit&{contractVersion:"1";authority:"non-authoritative-product-closure";organizationId:string;questionId:string;conversationId:string;seriesId:string;closureId:string;checkpointId:string;checkpointRevision:string;frozenPreparedWorkProductVersionId:string;authorizedProjectionDigest:string;candidateAssessmentDigest:string|null;b11CommunicationDigest:string|null;personalRoomSheetDigest:string|null;reviewedProposalIds:string[];dispositionReceiptIds:string[];canonicalRoutingLinkIds:string[];unresolvedReferences:string[];lifecycleLinkIds:string[];sections:Cycle1ClosureSectionV1[];checkpointStatus:"completed";prepareAgainReadiness:{eligible:true;checkpointId:string;seriesId:string;questionId:string;unresolvedReferenceCount:number};completedAt:string;completedByUserId:string};
export type LeadershipConversationWorkflowEventType = "context-recorded"|"prepared-work-product-version-recorded"|"prepared-work-product-frozen"|"private-working-contribution-captured"|"conversation-upload-received"|"takeaway-proposal-recorded"|"takeaway-disposition-recorded"|"canonical-routing-receipt-recorded"|"canonical-owner-routing-linked"|"change-receipt-linked"|"future-preparation-linked"|"canonical-product-materialization-recorded"|"historical-checkpoint-lifecycle-link-published"|"cycle1-closure-completed";
export type LeadershipConversationWorkflowEventV1 = Omit<DigestAudit,"contentDigest"> & { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;eventId:string;eventSequence:number;previousEventId:string|null;eventType:LeadershipConversationWorkflowEventType;recordRef:string;recordDigest:string;privateWorkingContributionRefs?:PrivateWorkingContributionArtifactRefV1[];occurredAt:string;actorType:"user"|"system";actorRef:string|null };
export type LeadershipConversationArtifactStoreV1 = { contractVersion:"1";organizationId:string;contexts:LeadershipConversationContextV1[];preparedWorkProducts:PreparedWorkProductV1[];frozenSnapshots:FrozenPreparedWorkProductSnapshotV1[];preparedWorkPublications?:PreparedWorkProductPublicationV1[];frozenSnapshotPublications?:FrozenPreparedWorkProductPublicationV1[];privateWorkingContributionFreezeIntents?:PrivateWorkingContributionFreezeIntentV1[];privateWorkingContributionPublications?:PrivateWorkingContributionPublicationV1[];privateWorkingContributionReceipts?:PrivateWorkingContributionReceiptV1[];privateWorkingContributionCaptures?:PrivateWorkingContributionCaptureV1[];privateWorkingContributionCaptureReceipts?:PrivateWorkingContributionCaptureReceiptV1[];publicationReceipts?:LeadershipConversationPublicationReceiptV1[];whatChangedPublications?:ProductArtifactOwnerHeaderV1[];cycle1ClosureCompletions?:Cycle1ClosureCompletionV1[];uploadReceipts:ConversationUploadReceiptV1[];proposals:TakeawayProposalEnvelopeV1[];dispositions:TakeawayProposalDispositionReceiptV1[];canonicalRoutingReceipts:LeadershipConversationCanonicalRoutingReceiptV1[];routingLinks:CanonicalOwnerRoutingLinkV1[];changeLinks:LeadershipConversationChangeReceiptLinkV1[];futurePreparationLinks:FuturePreparationLinkV1[];productMaterializations?:LeadershipConversationProductMaterializationRecordV1[];productMaterializationReceipts?:CanonicalProductMaterializationReceiptV1[];historicalCheckpointLifecycleLinks?:HistoricalCheckpointLifecycleLinkV1[];historicalCheckpointLifecycleLinkReceipts?:HistoricalCheckpointLifecycleLinkReceiptV1[];events:LeadershipConversationWorkflowEventV1[];idempotency:Array<{keyDigest:string;requestFingerprint:string;recordRef:string}>;storeDigest:string };
export type LeadershipConversationStepV1 = "set-up"|"prepare"|"freeze"|"capture"|"review"|"what-changed"|"prepare-again";
export type LeadershipConversationActionV1 = { id:"record-context"|"create-preparation"|"edit-preparation"|"freeze-preparation"|"upload-source"|"generate-proposals"|"review-proposal"|"route-approved"|"complete-closure"|"prepare-again"|"reset-development";enabled:boolean;requiredAuthority:string;blockedReason:string|null };
export type LeadershipConversationWorkspaceV1 = { contractVersion:"1";organizationId:string;questionId:string;conversationId:string;workflowRevision:string|null;base:ProductQuestionWorkspaceV2;currentStep:LeadershipConversationStepV1;context:LeadershipConversationContextV1|null;currentPreparedWorkProduct:PreparedWorkProductV1|null;frozenSnapshot:FrozenPreparedWorkProductSnapshotV1|null;uploadReceipt:ConversationUploadReceiptV1|null;proposals:TakeawayProposalEnvelopeV1[];dispositions:TakeawayProposalDispositionReceiptV1[];canonicalRoutingReceipts:LeadershipConversationCanonicalRoutingReceiptV1[];routingLinks:CanonicalOwnerRoutingLinkV1[];changeReceiptLink:LeadershipConversationChangeReceiptLinkV1|null;closureCompletion:Cycle1ClosureCompletionV1|null;futurePreparationLink:FuturePreparationLinkV1|null;actions:LeadershipConversationActionV1[];unavailableFields:string[];withheldFields:string[];auditReferences:string[] };
export function isLeadershipConversationPrepareAvailable(workspace:LeadershipConversationWorkspaceV1):boolean{return workspace.currentPreparedWorkProduct!==null;}
export function resolveCurrentOccurrenceCheckpointIdentityV1(input:{store:LeadershipConversationArtifactStoreV1;organizationId:string;questionId:string;conversationId:string}):{checkpointId:string;checkpointRevision:string;preparedWorkProductVersionId:string;contributionArtifactIds:string[]}{const productWorkflowId=`leadership-conversation:${input.conversationId}`,matches=(input.store.frozenSnapshotPublications??[]).filter(item=>item.organizationId===input.organizationId&&item.productQuestionId===input.questionId&&item.productWorkflowId===productWorkflowId);if(matches.length!==1)throw new Error("Leadership Conversation checkpoint is unavailable.");const checkpoint=matches[0]!;return{checkpointId:checkpoint.artifactId,checkpointRevision:checkpoint.artifactRevision,preparedWorkProductVersionId:checkpoint.preparedWorkProductVersionId,contributionArtifactIds:(checkpoint.privateWorkingContributionRefs??[]).map(value=>value.artifactId)};}
export type ChiefFirstPrepareActivationV1={contractVersion:"1";organizationId:string;questionId:string;meetingTitle:string;timeframe:string;role:string;purpose:string;authorizedSourceRefs:string[];idempotencyKey:string};
export type ChiefFirstPrepareViewV1={contractVersion:"1";organizationId:string;questionId:string;seriesId:string;conversationId:string;meeting:{title:string;timeframe:string;role:string;purpose:string};whatChanged:string[];whatMattersNow:string[];hiddenTension:string[];possibleSurprise:string[];questions:string[];priorCycle:{status:"none";message:string};sourceBasis:Array<{sourceRef:string;label:string}>;uncertainty:string[];reasoning:string[];competingExplanations:string[];provenance:{contextVersionId:string;preparedWorkProductVersionId:string;authorizedProjectionRevision:string;authorizedProjectionDigest:string;sourceRevisionReferences:string[]};status:"non-authoritative";currentStep:LeadershipConversationStepV1};
export interface LeadershipConversationClock { now():string }

export type SafeProductArtifactProjectionV1={contractVersion:"1";artifactType:"prepared-work"|"frozen-snapshot"|"what-changed"|"product-decision-draft";artifactId:string;artifactRevision:string;title:string;summary:string;accessResultDigest:string};
export type LeadershipHistoryEntryV1={contractVersion:"1";artifactType:SafeProductArtifactProjectionV1["artifactType"];artifactId:string;artifactRevision:string;label:string;occurredAt:string;accessResultDigest:string};
export type CurrentAuthorizedLeadershipHistoryV1={contractVersion:"1";entries:LeadershipHistoryEntryV1[];historyDigest:string};
export type FuturePreparationItemV1={contractVersion:"1";artifactId:string;artifactRevision:string;state:FuturePreparationItemStateV1;accessResultDigest:string|null;semanticInfluence:boolean;ownerClassificationRef:string|null};
export type CurrentAuthorizedProductQuestionWorkspaceV1={contractVersion:"1";organizationId:string;questionId:string;subjectId:string;purpose:string;scopeDigest:string;sensitivity:"standard"|"restricted"|"private";evaluatedAt:string;artifacts:SafeProductArtifactProjectionV1[];history:CurrentAuthorizedLeadershipHistoryV1;accessResultDigests:string[];workspaceDigest:string};
export type CurrentArtifactDeliveryCandidateV1={access:ProductArtifactCurrentAccessResultV1;safeProjection:SafeProductArtifactProjectionV1|null;occurredAt:string;ownerState:"unchanged"|"changed"|"resolved"|"superseded"|null};
