import type { SourceContentWriteReceiptV1 } from "../../../engine/v3/sources";
import type { ProductQuestionWorkspaceV2 } from "../frontendReadinessContracts";
import type { ProductWorkflowArtifactRepository } from "./productWorkflowArtifactRepository";
import type { CanonicalOwnerRoutingLinkV1, ConversationUploadReceiptV1, FrozenPreparedWorkProductSnapshotV1, FuturePreparationLinkV1, LeadershipConversationArtifactStoreV1, LeadershipConversationChangeReceiptLinkV1, LeadershipConversationClock, LeadershipConversationContextV1, LeadershipConversationWorkflowEventType, PreparedWorkProductContentV1, PreparedWorkProductLineageV1, PreparedWorkProductV1, ProposalDisposition, ProposalKind, TakeawayProposalDispositionReceiptV1, TakeawayProposalEnvelopeV1 } from "./contracts";
import { leadershipDigest, leadershipId, leadershipStableSerialize } from "./determinism";
import { buildLeadershipConversationWorkspace } from "./buildLeadershipConversationWorkspace";
import { productArtifactBodyDigest, serializeProductArtifactBodyV1 } from "../../persistence/productArtifactBodyContracts";
import type { ProductArtifactBodyRepository } from "../../persistence/productArtifactBodyRepository";
import {
  assertCanonicalProductDecisionDraftMaterializationResultIntegrityV1,
  assertCanonicalProductMaterializationInstructionIntegrityV1,
  assertCanonicalProductMaterializationReceiptIntegrityV1,
  assertLeadershipConversationProductMaterializationRecordIntegrityV1,
  createCanonicalProductMaterializationReceiptDigestV1,
  createLeadershipConversationProductMaterializationRecordDigestV1,
  type CanonicalProductDecisionDraftMaterializationResultV1,
  type CanonicalProductMaterializationInstructionV1,
  type CanonicalProductMaterializationReceiptV1,
} from "./canonicalProductMaterializationContracts";

type Identity={userId:string;organizationId:string;questionId:string;conversationId:string;idempotencyKey:string};
export type LeadershipConversationSourceGateway={write(input:{organizationId:string;questionId:string;conversationId:string;frozenSnapshotId:string;purposeRef:string;mediaType:"text/plain"|"text/markdown";bytes:Uint8Array;storedAt:string;storedByActorRef:string;idempotencyKey:string}):Promise<SourceContentWriteReceiptV1&{sourceBindingMutationReceiptDigest:string}>;readForProposal(input:{organizationId:string;sourceBindingId:string;sourceContentVersionId:string;purposeRef:string;userId:string}):Promise<{bytes:Uint8Array;exactContentDigest:string;normalizedContentDigest:string}>;readForEvidenceAdmission(input:{organizationId:string;sourceBindingId:string;sourceContentVersionId:string;purposeRef:string;userId:string;proposalId:string;dispositionReceiptId:string}):Promise<{text:string;exactContentDigest:string;normalizedContentDigest:string}>};
export type LeadershipConversationOperationsDependencies={repository:ProductWorkflowArtifactRepository;bodyRepository?:ProductArtifactBodyRepository;clock:LeadershipConversationClock;authorize(input:{userId:string;organizationId:string;operation:string}):Promise<boolean>;verifyCanonicalInstructionProvenance?(instruction:CanonicalProductMaterializationInstructionV1):Promise<boolean>;loadBase(input:{userId:string;organizationId:string;questionId:string}):Promise<ProductQuestionWorkspaceV2>;source:LeadershipConversationSourceGateway};
const safe=<T>(value:T)=>JSON.parse(JSON.stringify(value)) as T;
export class LeadershipConversationProductOperations{
  constructor(private d:LeadershipConversationOperationsDependencies){}
  private async access(input:Identity,operation:string){if(!await this.d.authorize({userId:input.userId,organizationId:input.organizationId,operation}))throw new Error("Leadership Conversation access denied.");const base=await this.d.loadBase(input);if(base.organizationId!==input.organizationId||base.questionId!==input.questionId)throw new Error("Leadership Conversation access denied.");return base;}
  private fingerprint(value:unknown){return leadershipDigest(leadershipStableSerialize(value));}
  private async mutate(input:Identity,operation:string,build:(store:LeadershipConversationArtifactStoreV1,keyDigest:string,fingerprint:string)=>{recordRef:string;eventType:LeadershipConversationWorkflowEventType}):Promise<LeadershipConversationArtifactStoreV1>{await this.access(input,operation);const current=await this.d.repository.read(input.organizationId),keyDigest=leadershipDigest(input.idempotencyKey),{idempotencyKey:_rawKey,...safeInput}=input,fingerprint=this.fingerprint({...safeInput,operation});const prior=current.store.idempotency.find(item=>item.keyDigest===keyDigest);if(prior){if(prior.requestFingerprint!==fingerprint)throw new Error("Leadership Conversation idempotency conflict.");return current.store;}const store=safe(current.store),result=build(store,keyDigest,fingerprint),events=store.events.filter(item=>item.questionId===input.questionId),sequence=events.length+1,previous=events.at(-1)?.eventId??null,recordDigest=this.fingerprint(result.recordRef),eventId=leadershipId("leadership-event",input.organizationId,input.questionId,sequence,result.eventType,result.recordRef);store.events.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,eventId,eventSequence:sequence,previousEventId:previous,eventType:result.eventType,recordRef:result.recordRef,recordDigest,occurredAt:this.d.clock.now(),actorType:"user",actorRef:input.userId,idempotencyKeyDigest:keyDigest,requestFingerprint:fingerprint});store.idempotency.push({keyDigest,requestFingerprint:fingerprint,recordRef:result.recordRef});return (await this.d.repository.replace(input.organizationId,store,current.revision)).store;}
  async workspace(input:Omit<Identity,"idempotencyKey">){const base=await this.access({...input,idempotencyKey:"read"},"leadership-conversation:read"),snapshot=await this.d.repository.read(input.organizationId);return buildLeadershipConversationWorkspace({base,conversationId:input.conversationId,store:snapshot.store});}
  async recordContext(input:Identity&{title:string;purpose:string;intendedOutcome:string;timeframe:string;participants:LeadershipConversationContextV1["participants"];leaderContext:string|null}){return this.mutate(input,"leadership-conversation:context-write",(store,keyDigest,requestFingerprint)=>{const versions=store.contexts.filter(item=>item.conversationId===input.conversationId),version=versions.length+1,predecessor=versions.at(-1)?.contextVersionId??null,content={title:input.title,purpose:input.purpose,intendedOutcome:input.intendedOutcome,timeframe:input.timeframe,participants:input.participants,leaderContext:input.leaderContext},contentDigest=this.fingerprint(content),contextVersionId=leadershipId("leadership-context",input.organizationId,input.questionId,input.conversationId,version,contentDigest);store.contexts.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,contextVersionId,contextVersion:version,predecessorContextVersionId:predecessor,conversationType:"leadership-conversation",scenarioId:"northstar-recurring-cross-functional-staff-conversation",...content,recordedAt:this.d.clock.now(),recordedByUserId:input.userId,idempotencyKeyDigest:keyDigest,requestFingerprint,contentDigest});return{recordRef:contextVersionId,eventType:"context-recorded"};});}
  async recordPreparation(input:Identity&{contextVersionId:string;content:PreparedWorkProductContentV1;lineage:PreparedWorkProductLineageV1;changeSummary:string|null}){
    await this.access(input,"leadership-conversation:prepare");if(!this.d.bodyRepository)throw new Error("Prepared Work split-persistence owner is unavailable.");
    const before=await this.d.repository.read(input.organizationId),publications=before.store.preparedWorkPublications??[],version=publications.filter(item=>item.productWorkflowId===`leadership-conversation:${input.conversationId}`).length+1,predecessor=publications.filter(item=>item.productWorkflowId===`leadership-conversation:${input.conversationId}`).at(-1)?.artifactRevision??null,artifactId=leadershipId("prepared-work-product",input.organizationId,input.questionId,input.conversationId),createdAt=this.d.clock.now(),body={contractVersion:"1" as const,content:safe(input.content),lineage:safe(input.lineage),createdAt,createdBy:version===1?"product-communication" as const:"leader-edit" as const,createdByUserId:version===1?null:input.userId,changeSummary:input.changeSummary},bytes=serializeProductArtifactBodyV1(body),bodyDigest=productArtifactBodyDigest(bytes),artifactVersionId=leadershipId("prepared-work-product-version",artifactId,version,bodyDigest),staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"prepared-work",artifactId,artifactRevision:artifactVersionId,schemaRef:"discovery:product:prepared-work-body:v1",bytes});
    return this.mutate(input,"leadership-conversation:prepare",(store,keyDigest,requestFingerprint)=>{if(!store.contexts.some(item=>item.contextVersionId===input.contextVersionId))throw new Error("Leadership Conversation context mismatch.");store.preparedWorkPublications??=[];const creationEnvelopeDigest=this.fingerprint({contextVersionId:input.contextVersionId,createdAt,createdBy:body.createdBy}),materialReferencesDigest=this.fingerprint(input.lineage),headerBase={contractVersion:"1" as const,organizationId:input.organizationId,semanticOwner:"leadership-conversation" as const,artifactType:"prepared-work" as const,artifactId,artifactRevision:artifactVersionId,productQuestionId:input.questionId,productWorkflowId:`leadership-conversation:${input.conversationId}`,creationEnvelopeDigest,materialReferencesDigest,protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,contextVersionId:input.contextVersionId,artifactVersion:version,predecessorArtifactVersionId:predecessor,basedOnFrozenSnapshotId:(store.frozenSnapshotPublications??[]).at(-1)?.artifactId??null,idempotencyKeyDigest:keyDigest,requestFingerprint},headerDigest=this.fingerprint(headerBase);store.preparedWorkPublications.push({...headerBase,headerDigest});return{recordRef:artifactVersionId,eventType:"prepared-work-product-version-recorded"};});
  }
  async freeze(input:Identity&{artifactVersionId:string}){
    await this.access(input,"leadership-conversation:freeze");if(!this.d.bodyRepository)throw new Error("Frozen snapshot split-persistence owner is unavailable.");const before=await this.d.repository.read(input.organizationId),artifact=(before.store.preparedWorkPublications??[]).find(item=>item.artifactRevision===input.artifactVersionId);if(!artifact||(before.store.frozenSnapshotPublications??[]).some(item=>item.preparedWorkProductVersionId===input.artifactVersionId))throw new Error("Leadership Conversation freeze mismatch.");await this.d.bodyRepository.readStagedExact(artifact.protectedBody);const frozenAt=this.d.clock.now(),body={contractVersion:"1" as const,sourcePreparedWorkBodyRef:artifact.protectedBody,frozenAt,frozenByUserId:input.userId},bytes=serializeProductArtifactBodyV1(body),snapshotId=leadershipId("prepared-work-product-snapshot",artifact.artifactRevision,productArtifactBodyDigest(bytes)),staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"frozen-snapshot",artifactId:snapshotId,artifactRevision:"1",schemaRef:"discovery:product:frozen-prepared-work-snapshot-body:v1",bytes});
    return this.mutate(input,"leadership-conversation:freeze",(store,keyDigest,requestFingerprint)=>{store.frozenSnapshotPublications??=[];const headerBase={contractVersion:"1" as const,organizationId:input.organizationId,semanticOwner:"leadership-conversation" as const,artifactType:"frozen-snapshot" as const,artifactId:snapshotId,artifactRevision:"1",productQuestionId:input.questionId,productWorkflowId:`leadership-conversation:${input.conversationId}`,creationEnvelopeDigest:this.fingerprint({frozenAt,frozenByUserId:input.userId}),materialReferencesDigest:this.fingerprint([artifact.protectedBody.refDigest]),protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,contextVersionId:artifact.contextVersionId,preparedWorkProductVersionId:artifact.artifactRevision,idempotencyKeyDigest:keyDigest,requestFingerprint,snapshotDigest:productArtifactBodyDigest(bytes)},headerDigest=this.fingerprint(headerBase);store.frozenSnapshotPublications.push({...headerBase,headerDigest});return{recordRef:snapshotId,eventType:"prepared-work-product-frozen"};});
  }
  async receiveUpload(input:Identity&{frozenSnapshotId:string;purposeRef:string;mediaType:"text/plain"|"text/markdown";bytes:Uint8Array;displayLabel:string|null;originalFilename:string|null}){await this.access(input,"source-content:write");const stored=(await this.d.repository.read(input.organizationId)).store,snapshot=stored.frozenSnapshots.some(item=>item.snapshotId===input.frozenSnapshotId)||(stored.frozenSnapshotPublications??[]).some(item=>item.artifactId===input.frozenSnapshotId);if(!snapshot)throw new Error("Leadership Conversation frozen snapshot mismatch.");const receipt=await this.d.source.write({...input,frozenSnapshotId:input.frozenSnapshotId,purposeRef:input.purposeRef,mediaType:input.mediaType,bytes:input.bytes,storedAt:this.d.clock.now(),storedByActorRef:input.userId});return this.mutate(input,"leadership-conversation:upload-receipt",(store,keyDigest,requestFingerprint)=>{const uploadReceiptId=leadershipId("conversation-upload-receipt",input.organizationId,input.questionId,input.conversationId,receipt.sourceContentVersionId);const upload:ConversationUploadReceiptV1={contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,frozenSnapshotId:input.frozenSnapshotId,uploadReceiptId,sourceBindingId:receipt.sourceBindingId,sourceContentVersionId:receipt.sourceContentVersionId,sourceBindingMutationReceiptDigest:receipt.sourceBindingMutationReceiptDigest,mediaType:receipt.mediaType,byteLength:receipt.byteLength,exactContentDigest:receipt.exactContentDigest,normalizedContentDigest:receipt.normalizedContentDigest,sourceContentWriteReceiptDigest:receipt.receiptDigest,displayLabel:input.displayLabel,originalFilename:input.originalFilename,duplicateClassification:receipt.disposition,uploadedAt:this.d.clock.now(),uploadedByUserId:input.userId,idempotencyKeyDigest:keyDigest,requestFingerprint};store.uploadReceipts.push(upload);return{recordRef:uploadReceiptId,eventType:"conversation-upload-received"};});}
  async generateFixtureProposals(input:Identity&{uploadReceiptId:string;purposeRef:string}){await this.access(input,"source-content:read-for-proposal");const store=(await this.d.repository.read(input.organizationId)).store,upload=store.uploadReceipts.find(item=>item.uploadReceiptId===input.uploadReceiptId);if(!upload)throw new Error("Leadership Conversation upload mismatch.");const source=await this.d.source.readForProposal({organizationId:input.organizationId,sourceBindingId:upload.sourceBindingId,sourceContentVersionId:upload.sourceContentVersionId,purposeRef:input.purposeRef,userId:input.userId});if(source.exactContentDigest!==upload.exactContentDigest||source.normalizedContentDigest!==upload.normalizedContentDigest)throw new Error("Leadership Conversation source integrity failed.");const marker=new TextDecoder().decode(source.bytes);const fixture=marker.includes("NORTHSTAR-LEADERSHIP-CAPTURE-001");const definitions:Array<[ProposalKind,string,string]> = fixture?[["evidence-candidate","Canonical Evidence admission","Cross-team sequencing remains the material constraint."],["decision-draft","Decision owner","Draft a sequencing review decision."],["unknown","Unknown lifecycle","Which dependency creates the longest delay?"],["commitment","Product Workflow","Review sequencing weekly."]]:[];for(const [ordinal,[kind,targetOwner,summary]] of definitions.entries()){await this.mutate({...input,idempotencyKey:`${input.idempotencyKey}:${ordinal+1}`},"leadership-conversation:proposal",(next,keyDigest,requestFingerprint)=>{const payload={summary,targetRef:null},payloadDigest=this.fingerprint(payload),proposalId=leadershipId("takeaway-proposal",upload.uploadReceiptId,ordinal+1,kind,payloadDigest);next.proposals.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,frozenSnapshotId:upload.frozenSnapshotId,uploadReceiptId:upload.uploadReceiptId,sourceBindingId:upload.sourceBindingId,sourceContentVersionId:upload.sourceContentVersionId,proposalId,proposalOrdinal:ordinal+1,kind,targetOwner,routingPolicy:kind==="evidence-candidate"?"approved-then-authorized-reread":"approved-then-owner-route",payload,payloadDigest,sourceExcerptReferences:[{startByte:0,endByte:Math.min(upload.byteLength,64)}],proposedAt:this.d.clock.now(),proposedBy:"northstar-fixture",proposedByUserId:null,idempotencyKeyDigest:keyDigest,requestFingerprint});return{recordRef:proposalId,eventType:"takeaway-proposal-recorded"};});}return definitions.length;}
  async review(input:Identity&{proposalId:string;disposition:ProposalDisposition;effectivePayload:TakeawayProposalEnvelopeV1["payload"]|null;reason:string|null}){return this.mutate(input,"leadership-conversation:review",(store,keyDigest,requestFingerprint)=>{const proposal=store.proposals.find(item=>item.proposalId===input.proposalId);if(!proposal)throw new Error("Leadership Conversation proposal mismatch.");if(input.disposition==="approved-with-edit"&&!input.effectivePayload)throw new Error("Effective payload is required.");const effective=input.disposition==="approved-with-edit"?safe(input.effectivePayload):null,effectiveDigest=effective?this.fingerprint(effective):null,reviewRevision=store.dispositions.filter(item=>item.proposalId===proposal.proposalId).length+1,dispositionReceiptId=leadershipId("takeaway-disposition",proposal.proposalId,reviewRevision,input.disposition,effectiveDigest??proposal.payloadDigest);store.dispositions.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,dispositionReceiptId,proposalId:proposal.proposalId,originalPayloadDigest:proposal.payloadDigest,disposition:input.disposition,effectivePayload:effective,effectivePayloadDigest:effectiveDigest,duplicateProposalId:null,reason:input.reason,reviewedAt:this.d.clock.now(),reviewedByUserId:input.userId,reviewRevision,idempotencyKeyDigest:keyDigest,requestFingerprint});return{recordRef:dispositionReceiptId,eventType:"takeaway-disposition-recorded"};});}
  async linkFuturePreparation(input:Identity&{nextConversationId:string;nextContextVersionId:string;nextPreparedWorkProductVersionId:string}){return this.mutate(input,"leadership-conversation:prepare-again",(store,keyDigest,requestFingerprint)=>{const frozen=(store.frozenSnapshotPublications??[]).filter(item=>item.productWorkflowId===`leadership-conversation:${input.conversationId}`).at(-1),upload=store.uploadReceipts.filter(item=>item.conversationId===input.conversationId).at(-1),change=(store.whatChangedPublications??[]).filter(item=>item.productWorkflowId===`leadership-conversation:${input.conversationId}`).at(-1);if(!frozen||!upload||!change)throw new Error("Leadership Conversation future preparation is unavailable.");const approved=store.dispositions.filter(item=>item.conversationId===input.conversationId&&item.disposition.startsWith("approved")).map(item=>item.proposalId),routes=store.routingLinks.filter(item=>approved.includes(item.proposalId)).map(item=>item.routingLinkId),futurePreparationLinkId=leadershipId("future-preparation-link",change.artifactId,input.nextPreparedWorkProductVersionId);const link:FuturePreparationLinkV1={contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,futurePreparationLinkId,sourceFrozenSnapshotId:frozen.artifactId,sourceUploadReceiptId:upload.uploadReceiptId,approvedProposalIds:approved,canonicalRoutingLinkIds:routes,canonicalChangeReceiptRef:change.protectedBody.refDigest,nextConversationId:input.nextConversationId,nextContextVersionId:input.nextContextVersionId,nextPreparedWorkProductVersionId:input.nextPreparedWorkProductVersionId,linkedAt:this.d.clock.now(),idempotencyKeyDigest:keyDigest,requestFingerprint};store.futurePreparationLinks.push(link);return{recordRef:futurePreparationLinkId,eventType:"future-preparation-linked"};});}
  async materializeCanonicalProductInstruction(input:{instruction:CanonicalProductMaterializationInstructionV1;draftResult:CanonicalProductDecisionDraftMaterializationResultV1}):Promise<{receipt:CanonicalProductMaterializationReceiptV1;idempotent:boolean;repositoryRevision:string|null}>{
    const instruction=input.instruction;
    assertCanonicalProductMaterializationInstructionIntegrityV1(instruction);
    assertCanonicalProductDecisionDraftMaterializationResultIntegrityV1(input.draftResult);
    if(input.draftResult.canonicalOperationId!==instruction.canonicalOperationId||input.draftResult.instructionDigest!==instruction.instructionDigest)throw new Error("Canonical Product Draft stage belongs to another instruction.");
    if(instruction.draftMaterialization.required&&input.draftResult.status!=="materialized")throw new Error("Canonical Product Workflow materialization requires a completed Draft stage.");
    if(!instruction.draftMaterialization.required&&input.draftResult.status!=="not-applicable")throw new Error("Canonical Product Workflow materialization has an unexpected Draft stage.");
    if(!this.d.verifyCanonicalInstructionProvenance||!await this.d.verifyCanonicalInstructionProvenance(instruction))throw new Error("Canonical Product materialization instruction provenance is unavailable.");
    const current=await this.d.repository.read(instruction.organizationId),store=safe(current.store);
    store.productMaterializations??=[];store.productMaterializationReceipts??=[];
    const existing=store.productMaterializations.find(item=>item.canonicalOperationId===instruction.canonicalOperationId);
    if(existing){
      assertLeadershipConversationProductMaterializationRecordIntegrityV1(existing);
      if(existing.instructionDigest!==instruction.instructionDigest)throw new Error("Canonical Product materialization operation collision.");
      const receipt=store.productMaterializationReceipts.find(item=>item.receiptDigest===existing.receiptDigest);
      if(!receipt)throw new Error("Canonical Product materialization receipt is unavailable.");
      assertCanonicalProductMaterializationReceiptIntegrityV1(receipt);
      return{receipt:safe(receipt),idempotent:true,repositoryRevision:current.revision};
    }
    if(store.productMaterializationReceipts.some(item=>item.canonicalOperationId===instruction.canonicalOperationId))throw new Error("Canonical Product materialization receipt collision.");
    store.whatChangedPublications??=[];
    if(store.whatChangedPublications.some(item=>item.artifactId===instruction.whatChangedArtifactId))throw new Error("Canonical What Changed identity collision.");
    const draftReceipt=input.draftResult.receipt;
    const canonicalDraftReference=draftReceipt?{draftId:draftReceipt.draftId,draftRevisionId:draftReceipt.draftRevisionId,draftStageReceiptDigest:draftReceipt.receiptDigest,draftMutationDigest:draftReceipt.draftMutationDigest,draftEnvelopeDigest:draftReceipt.draftEnvelopeDigest,canonicalOperationId:instruction.canonicalOperationId,instructionDigest:instruction.instructionDigest}:null;
    const revisionBefore=current.revision??"product-workflow:none",revisionAfter=leadershipId("product-workflow-revision",revisionBefore,instruction.instructionDigest);
    const eventId=leadershipId("leadership-event",instruction.organizationId,instruction.questionId,store.events.filter(item=>item.questionId===instruction.questionId).length+1,"canonical-product-materialization-recorded",instruction.instructionDigest);
    const unsignedReceipt={contractVersion:"1" as const,receiptId:leadershipId("canonical-product-materialization-receipt",instruction.canonicalOperationId,instruction.instructionDigest),canonicalOperationId:instruction.canonicalOperationId,instructionDigest:instruction.instructionDigest,stage:"canonical-committed-product-materialized" as const,productWorkflowRevisionBefore:revisionBefore,productWorkflowRevisionAfter:revisionAfter,whatChangedArtifactId:instruction.whatChangedArtifactId,canonicalDraftReference,eventIds:[eventId]};
    const receipt:CanonicalProductMaterializationReceiptV1={...unsignedReceipt,receiptDigest:createCanonicalProductMaterializationReceiptDigestV1(unsignedReceipt)};
    const unsignedRecord={contractVersion:"1" as const,materializationRecordId:leadershipId("canonical-product-materialization-record",instruction.canonicalOperationId,instruction.instructionDigest),organizationId:instruction.organizationId,questionId:instruction.questionId,conversationId:instruction.conversationId,canonicalOperationId:instruction.canonicalOperationId,instructionDigest:instruction.instructionDigest,requestFingerprint:instruction.requestFingerprint,whatChangedArtifactId:instruction.whatChangedArtifactId,canonicalDraftReference,receiptDigest:receipt.receiptDigest};
    const record={...unsignedRecord,recordDigest:createLeadershipConversationProductMaterializationRecordDigestV1(unsignedRecord)};
    store.whatChangedPublications.push({contractVersion:"1",organizationId:instruction.organizationId,semanticOwner:"leadership-conversation",artifactType:"what-changed",artifactId:instruction.whatChangedArtifactId,artifactRevision:instruction.whatChangedEnvelope.artifactRevision,productQuestionId:instruction.questionId,productWorkflowId:instruction.whatChangedEnvelope.productWorkflowId,creationEnvelopeDigest:instruction.whatChangedEnvelope.creationEnvelopeDigest,materialReferencesDigest:instruction.whatChangedEnvelope.materialReferencesDigest,protectedBody:safe(instruction.whatChangedEnvelope.protectedBody),ownerStageReceiptDigest:instruction.whatChangedEnvelope.ownerStageReceiptDigest,headerDigest:instruction.whatChangedEnvelope.headerDigest});
    store.productMaterializations.push(record);store.productMaterializationReceipts.push(receipt);
    const priorEvents=store.events.filter(item=>item.questionId===instruction.questionId),sequence=priorEvents.length+1;
    store.events.push({contractVersion:"1",organizationId:instruction.organizationId,questionId:instruction.questionId,conversationId:instruction.conversationId,eventId,eventSequence:sequence,previousEventId:priorEvents.at(-1)?.eventId??null,eventType:"canonical-product-materialization-recorded",recordRef:record.materializationRecordId,recordDigest:record.recordDigest,occurredAt:instruction.evaluatedAt,actorType:"system",actorRef:instruction.actorRef,idempotencyKeyDigest:leadershipDigest(`canonical-product-materialization:${instruction.instructionDigest}`),requestFingerprint:instruction.requestFingerprint});
    store.idempotency.push({keyDigest:leadershipDigest(`canonical-product-materialization:${instruction.instructionDigest}`),requestFingerprint:instruction.requestFingerprint,recordRef:record.materializationRecordId});
    const persisted=await this.d.repository.replace(instruction.organizationId,store,current.revision);
    return{receipt:safe(receipt),idempotent:false,repositoryRevision:persisted.revision};
  }
  async reset(input:Identity&{environment:"development"|"sandbox"|"test"}){await this.access(input,"leadership-conversation:reset-development");return this.d.repository.resetDevelopmentFixture(input.organizationId);}
}
