import { constants } from "node:fs";
import { chmod, lstat, mkdir, open, readFile, realpath, rename, rm, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import type { LeadershipConversationArtifactStoreV1 } from "./contracts";
import { leadershipDigest, leadershipStableSerialize } from "./determinism";

const SAFE=/^[A-Za-z0-9_-]+$/;
const empty=(organizationId:string):LeadershipConversationArtifactStoreV1=>({contractVersion:"1",organizationId,contexts:[],preparedWorkProducts:[],frozenSnapshots:[],preparedWorkPublications:[],frozenSnapshotPublications:[],whatChangedPublications:[],uploadReceipts:[],proposals:[],dispositions:[],canonicalRoutingReceipts:[],routingLinks:[],changeLinks:[],futurePreparationLinks:[],productMaterializations:[],productMaterializationReceipts:[],events:[],idempotency:[],storeDigest:""});
export function normalizeLeadershipConversationArtifactStore(store:LeadershipConversationArtifactStoreV1):LeadershipConversationArtifactStoreV1{return{...store,preparedWorkPublications:store.preparedWorkPublications??[],frozenSnapshotPublications:store.frozenSnapshotPublications??[],whatChangedPublications:store.whatChangedPublications??[],productMaterializations:store.productMaterializations??[],productMaterializationReceipts:store.productMaterializationReceipts??[]};}
function assertNoLegacyCombinedBodies(store:LeadershipConversationArtifactStoreV1):void{if(store.preparedWorkProducts.length||store.frozenSnapshots.length||store.changeLinks.length)throw new Error("Product Workflow legacy combined artifact container is unsupported.");}
function bytes(store:LeadershipConversationArtifactStoreV1){const {storeDigest:_ignored,...safe}=store;const complete={...safe,storeDigest:leadershipDigest(leadershipStableSerialize(safe))};return new TextEncoder().encode(`${leadershipStableSerialize(complete)}\n`);}
export type ProductWorkflowStoreSnapshot={store:LeadershipConversationArtifactStoreV1;revision:string|null};
export interface ProductWorkflowArtifactRepository{read(organizationId:string):Promise<ProductWorkflowStoreSnapshot>;replace(organizationId:string,store:LeadershipConversationArtifactStoreV1,expectedRevision:string|null):Promise<ProductWorkflowStoreSnapshot>;resetDevelopmentFixture(organizationId:string):Promise<boolean>}
class FilesystemProductWorkflowArtifactRepository implements ProductWorkflowArtifactRepository{
  constructor(private root:string,private defaultRoot:string){if(!path.isAbsolute(root))throw new Error("Product Workflow root must be absolute.");}
  private id(value:string){if(!SAFE.test(value))throw new Error("Product Workflow organization identifier is invalid.");return value;}
  private target(id:string){return path.join(this.root,"organizations",`${this.id(id)}.json`);}
  private async noLink(target:string){try{if((await lstat(target)).isSymbolicLink())throw new Error("Product Workflow storage is unsafe.");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}
  private async prepare(){await this.noLink(this.root);await mkdir(path.join(this.root,"organizations"),{recursive:true,mode:0o700});for(const target of [this.root,path.join(this.root,"organizations")]){await this.noLink(target);await chmod(target,0o700);}const actual=await realpath(this.root),parent=await realpath(path.dirname(this.root));if(actual!==path.join(parent,path.basename(this.root)))throw new Error("Product Workflow storage is aliased.");}
  async read(organizationId:string):Promise<ProductWorkflowStoreSnapshot>{await this.prepare();const target=this.target(organizationId);await this.noLink(target);try{const status=await lstat(target);if(!status.isFile()||(status.mode&0o777)!==0o600)throw new Error("Product Workflow store integrity failed.");const raw=new Uint8Array(await readFile(target));const persisted=JSON.parse(new TextDecoder().decode(raw)) as LeadershipConversationArtifactStoreV1;if(persisted.organizationId!==organizationId||persisted.contractVersion!=="1"||!Buffer.from(raw).equals(Buffer.from(bytes(persisted))))throw new Error("Product Workflow store integrity failed.");assertNoLegacyCombinedBodies(persisted);return{store:normalizeLeadershipConversationArtifactStore(persisted),revision:leadershipDigest(raw)};}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return{store:empty(organizationId),revision:null};throw error;}}
  async replace(organizationId:string,store:LeadershipConversationArtifactStoreV1,expectedRevision:string|null){if(store.organizationId!==organizationId)throw new Error("Product Workflow store organization mismatch.");assertNoLegacyCombinedBodies(store);const current=await this.read(organizationId);if(current.revision!==expectedRevision)throw new Error("Product Workflow store revision changed.");const target=this.target(organizationId),next=bytes(store),temporary=`${target}.${leadershipDigest(next)}.tmp`;await this.noLink(temporary);try{await unlink(temporary);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}const handle=await open(temporary,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);try{await handle.writeFile(next);await handle.sync();}finally{await handle.close();}await rename(temporary,target);return this.read(organizationId);}
  async resetDevelopmentFixture(organizationId:string){if(path.resolve(this.root)===path.resolve(this.defaultRoot))throw new Error("Product Workflow reset refused.");await this.noLink(this.root);const actual=await realpath(this.root),temporary=await realpath(tmpdir());if(!actual.startsWith(`${temporary}${path.sep}`)||!path.basename(actual).startsWith("discovery-leadership-conversation-"))throw new Error("Product Workflow reset refused.");try{await rm(this.target(organizationId));return true;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return false;throw error;}}
}
export function createProductWorkflowArtifactRepository(input:{root:string;environment:"development"|"sandbox"|"test";defaultRoot?:string}):ProductWorkflowArtifactRepository{if(!["development","sandbox","test"].includes(input.environment))throw new Error("Product Workflow persistence is unavailable outside development.");return new FilesystemProductWorkflowArtifactRepository(path.resolve(input.root),path.resolve(input.defaultRoot??path.join(process.cwd(),".discovery-runtime/product-workflow")));}
