import { constants } from "node:fs";
import { chmod, lstat, mkdir, open, readFile, realpath, rename, rm, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { assertGovernedConsequenceScopeBindingV1, type LeadershipConversationArtifactStoreV1 } from "./contracts";
import { leadershipDigest, leadershipStableSerialize } from "./determinism";

const SAFE=/^[A-Za-z0-9_-]+$/;
const pause=(milliseconds:number)=>new Promise<void>(resolve=>setTimeout(resolve,milliseconds));
const empty=(organizationId:string):LeadershipConversationArtifactStoreV1=>({contractVersion:"1",organizationId,contexts:[],preparedWorkProducts:[],frozenSnapshots:[],preparedWorkPublications:[],frozenSnapshotPublications:[],publicationReceipts:[],whatChangedPublications:[],uploadReceipts:[],proposals:[],dispositions:[],canonicalRoutingReceipts:[],routingLinks:[],changeLinks:[],futurePreparationLinks:[],productMaterializations:[],productMaterializationReceipts:[],historicalCheckpointLifecycleLinks:[],historicalCheckpointLifecycleLinkReceipts:[],events:[],idempotency:[],storeDigest:""});
export function normalizeLeadershipConversationArtifactStore(store:LeadershipConversationArtifactStoreV1):LeadershipConversationArtifactStoreV1{return{...store,preparedWorkPublications:store.preparedWorkPublications??[],frozenSnapshotPublications:store.frozenSnapshotPublications??[],publicationReceipts:store.publicationReceipts??[],whatChangedPublications:store.whatChangedPublications??[],productMaterializations:store.productMaterializations??[],productMaterializationReceipts:store.productMaterializationReceipts??[],historicalCheckpointLifecycleLinks:store.historicalCheckpointLifecycleLinks??[],historicalCheckpointLifecycleLinkReceipts:store.historicalCheckpointLifecycleLinkReceipts??[]};}
function assertNoLegacyCombinedBodies(store:LeadershipConversationArtifactStoreV1):void{if(store.preparedWorkProducts.length||store.frozenSnapshots.length||store.changeLinks.length)throw new Error("Product Workflow legacy combined artifact container is unsupported.");}
function assertGovernedScopeLineage(store:LeadershipConversationArtifactStoreV1):void{for(const proposal of store.proposals){if(proposal.contractVersion==="2")assertGovernedConsequenceScopeBindingV1(proposal.governedScopeBinding,store.organizationId);else if(proposal.contractVersion!=="1"||("governedScopeBinding" in proposal&&proposal.governedScopeBinding))throw new Error("Product Workflow proposal version is invalid.");}for(const disposition of store.dispositions){const proposal=store.proposals.find(value=>value.proposalId===disposition.proposalId);if(!proposal)throw new Error("Product Workflow governed scope lineage is invalid.");const expected=proposal.contractVersion==="2"?proposal.governedScopeBinding.bindingDigest:undefined;if(disposition.governedScopeBindingDigest!==expected||(disposition.sourceProposalContractVersion!==undefined&&disposition.sourceProposalContractVersion!==proposal.contractVersion))throw new Error("Product Workflow governed scope lineage is invalid.");}for(const receipt of store.canonicalRoutingReceipts){if(receipt.sourceProposalContractVersion!==undefined&&receipt.sourceProposalContractVersion!=="2")throw new Error("Product Workflow governed routing lineage is invalid.");if(receipt.sourceProposalContractVersion==="2"&&!receipt.governedScopeBindingDigest)throw new Error("Product Workflow governed routing lineage is invalid.");}for(const link of store.routingLinks){if(link.sourceProposalContractVersion!==undefined&&link.sourceProposalContractVersion!=="2")throw new Error("Product Workflow governed routing lineage is invalid.");if(link.sourceProposalContractVersion==="2"&&!link.governedScopeBindingDigest)throw new Error("Product Workflow governed routing lineage is invalid.");}}
function bytes(store:LeadershipConversationArtifactStoreV1){const {storeDigest:_ignored,...safe}=store;const complete={...safe,storeDigest:leadershipDigest(leadershipStableSerialize(safe))};return new TextEncoder().encode(`${leadershipStableSerialize(complete)}\n`);}
export type ProductWorkflowStoreSnapshot={store:LeadershipConversationArtifactStoreV1;revision:string|null};
export interface ProductWorkflowArtifactRepository{read(organizationId:string):Promise<ProductWorkflowStoreSnapshot>;replace(organizationId:string,store:LeadershipConversationArtifactStoreV1,expectedRevision:string|null):Promise<ProductWorkflowStoreSnapshot>;resetDevelopmentFixture(organizationId:string):Promise<boolean>}
class FilesystemProductWorkflowArtifactRepository implements ProductWorkflowArtifactRepository{
  constructor(private root:string,private defaultRoot:string){if(!path.isAbsolute(root))throw new Error("Product Workflow root must be absolute.");}
  private id(value:string){if(!SAFE.test(value))throw new Error("Product Workflow organization identifier is invalid.");return value;}
  private target(id:string){return path.join(this.root,"organizations",`${this.id(id)}.json`);}
  private lockTarget(id:string){return path.join(this.root,"organizations",`${this.id(id)}.lock`);}
  private async noLink(target:string){try{if((await lstat(target)).isSymbolicLink())throw new Error("Product Workflow storage is unsafe.");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}
  private async prepare(){await this.noLink(this.root);await mkdir(path.join(this.root,"organizations"),{recursive:true,mode:0o700});for(const target of [this.root,path.join(this.root,"organizations")]){await this.noLink(target);await chmod(target,0o700);}const actual=await realpath(this.root),parent=await realpath(path.dirname(this.root));if(actual!==path.join(parent,path.basename(this.root)))throw new Error("Product Workflow storage is aliased.");}
  async read(organizationId:string):Promise<ProductWorkflowStoreSnapshot>{await this.prepare();const target=this.target(organizationId);await this.noLink(target);try{const status=await lstat(target);if(!status.isFile()||(status.mode&0o777)!==0o600)throw new Error("Product Workflow store integrity failed.");const raw=new Uint8Array(await readFile(target));const persisted=JSON.parse(new TextDecoder().decode(raw)) as LeadershipConversationArtifactStoreV1;if(persisted.organizationId!==organizationId||persisted.contractVersion!=="1"||!Buffer.from(raw).equals(Buffer.from(bytes(persisted))))throw new Error("Product Workflow store integrity failed.");assertNoLegacyCombinedBodies(persisted);assertGovernedScopeLineage(persisted);return{store:normalizeLeadershipConversationArtifactStore(persisted),revision:leadershipDigest(raw)};}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return{store:empty(organizationId),revision:null};throw error;}}
  private async acquire(organizationId:string){await this.prepare();const target=this.lockTarget(organizationId);for(let attempt=0;attempt<500;attempt+=1){try{const handle=await open(target,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);return{handle,target};}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;await pause(10);}}throw new Error("Product Workflow store is busy.");}
  async replace(organizationId:string,store:LeadershipConversationArtifactStoreV1,expectedRevision:string|null){if(store.organizationId!==organizationId)throw new Error("Product Workflow store organization mismatch.");const lock=await this.acquire(organizationId);try{const current=await this.read(organizationId);if(current.revision!==expectedRevision)throw new Error("Product Workflow store revision changed.");assertNoLegacyCombinedBodies(store);assertGovernedScopeLineage(store);const target=this.target(organizationId),next=bytes(normalizeLeadershipConversationArtifactStore(store)),temporary=`${target}.${leadershipDigest(next)}.${process.pid}.tmp`;await this.noLink(temporary);try{await unlink(temporary);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}const handle=await open(temporary,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);try{await handle.writeFile(next);await handle.sync();}finally{await handle.close();}await rename(temporary,target);return this.read(organizationId);}finally{await lock.handle.close();await unlink(lock.target).catch((error:NodeJS.ErrnoException)=>{if(error.code!=="ENOENT")throw error;});}}
  async resetDevelopmentFixture(organizationId:string){if(path.resolve(this.root)===path.resolve(this.defaultRoot))throw new Error("Product Workflow reset refused.");await this.noLink(this.root);const actual=await realpath(this.root),temporary=await realpath(tmpdir());if(!actual.startsWith(`${temporary}${path.sep}`)||!path.basename(actual).startsWith("discovery-leadership-conversation-"))throw new Error("Product Workflow reset refused.");try{await rm(this.target(organizationId));return true;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return false;throw error;}}
}
export function createProductWorkflowArtifactRepository(input:{root:string;environment:"development"|"sandbox"|"test";defaultRoot?:string}):ProductWorkflowArtifactRepository{if(!["development","sandbox","test"].includes(input.environment))throw new Error("Product Workflow persistence is unavailable outside development.");return new FilesystemProductWorkflowArtifactRepository(path.resolve(input.root),path.resolve(input.defaultRoot??path.join(process.cwd(),".discovery-runtime/product-workflow")));}
