import type { ScopedGovernanceContext } from "../../engine/v3/governance/scopedGovernanceContext";
import type { ProductArtifactInspectionMetadataV1 } from "./productArtifactInspectionMetadataContracts";

export const PRODUCT_ARTIFACT_CURRENT_ACCESS_CONTRACT_VERSION = "1" as const;
export type ProductArtifactCurrentAccessOperationV1 = "product-artifact:read"|"product-artifact:reuse"|"product-artifact:compare"|"product-artifact:prepare-again"|"product-artifact:create-successor";
export type ProductArtifactCurrentAccessRequestV1={contractVersion:"1";organizationId:string;subjectId:string;operation:ProductArtifactCurrentAccessOperationV1;purpose:string;scopeDigest:string;sensitivity:"standard"|"restricted"|"private";evaluatedAt:string;metadata:ProductArtifactInspectionMetadataV1;governance:ScopedGovernanceContext};
export type ProductArtifactCurrentOwnerStateV1={contractVersion:"1";organizationId:string;productQuestionId:string;sourceGovernanceDigest:string|null;eligibilityDigest:string|null;eligibilityDisposition:"eligible"|"withheld"|"unavailable";projectionRevision:string|null;projectionDigest:string|null;canonicalUnderstandingRevision:string|null;canonicalChangeResultDigest:string|"not-applicable"|null;lineagePolicyVersion:string|null};
export type ProductArtifactCurrentAccessResultV1={contractVersion:"1";organizationId:string;subjectId:string;artifactType:string;artifactId:string;artifactRevision:string;operation:ProductArtifactCurrentAccessOperationV1;purpose:string;scopeDigest:string;sensitivity:ProductArtifactCurrentAccessRequestV1["sensitivity"];evaluatedAt:string;disposition:"eligible"|"withheld"|"unavailable";metadataHeaderDigest:string;bodyRefDigest:string;authorityRevisionRefs:readonly string[];policyRevisionRefs:readonly string[];sourceGovernanceDigest:string|null;eligibilityDigest:string|null;projectionRevision:string|null;projectionDigest:string|null;canonicalUnderstandingRevision:string|null;canonicalChangeResultDigest:string|"not-applicable"|null;lineagePolicyVersion:string|null;resultDigest:string};
export type FuturePreparationItemStateV1="eligible-unchanged"|"eligible-changed"|"resolved"|"withheld"|"unavailable"|"superseded"|"invalid";
