import { productArtifactBodyDigest, validateProductArtifactBodyRefV1, type PersistedProductArtifactTypeV1, type ProductArtifactBodyRefV1, type ProductArtifactSemanticOwnerV1 } from "../persistence/productArtifactBodyContracts";

export type ProductArtifactInspectionMetadataV1 = {
  contractVersion: "1";
  organizationId: string;
  semanticOwner: "leadership-conversation" | "product-decision-draft";
  artifactType: PersistedProductArtifactTypeV1;
  artifactId: string;
  artifactRevision: string;
  productQuestionId: string;
  productWorkflowId: string | null;
  creationEnvelopeDigest: string;
  materialReferencesDigest: string;
  protectedBody: ProductArtifactBodyRefV1;
  ownerStageReceiptDigest: string;
  materialLineage?: ProductArtifactMaterialLineage;
  publicationProofVersion?: "1";
  headerDigest: string;
};

export type ProductArtifactMaterialLineageSeedV1={contractVersion:"1";organizationId:string;semanticOwner:ProductArtifactSemanticOwnerV1;productQuestionId:string;creationOperationId:string;lineagePolicyVersion:string;sourceBindings:Array<{sourceBindingId:string;bindingRevisionId:string}>;sourceContentVersions:Array<{sourceBindingId:string;sourceContentVersionId:string;normalizedContentDigest:string}>;canonicalMaterial:Array<{canonicalObjectId:string;revisionRef:string;owner:"canonical-evidence-admission"}>;canonicalUnderstandingRevision:string;projectionSourceRef:string;scopeDigest?:string;purpose?:string;sensitivity?:"standard"|"restricted"|"private";seedDigest:string};
export type DirectCanonicalEvidenceProvenanceV2={contractVersion:"2";lineageVariant:"direct-canonical-evidence";organizationId:string;productQuestionId:string;ownerScopeRef:string;sourceWorkflowRef:string;artifactWorkflowRef:string;artifactId:string;artifactRevision:string;operationEnvelope:{contributionOperationId:string;requestFingerprint:string;idempotencyKeyDigest:string;lineageEnvelopeDigest:string;operationRecordDigest:string};materialization:{canonicalOperationId:string;instructionDigest:string;materializationRecordId:string;materializationRecordDigest:string;receiptId:string;receiptDigest:string};admissionBatch:{batchDigest:string;admissionDisposition:"admitted"|"partially-admitted"|"not-admitted"};evidence:Array<{canonicalEvidenceId:string;canonicalAdmissionId:string;attributionId:string;attributionVersion:number;attributionDigest:string;sourceBindings:Array<{sourceBindingId:string;bindingRevisionId:string;bindingRevisionDigest:string;sourceContentVersionId:string;exactContentDigest:string;normalizedContentDigest:string;storageIntegrityDigest:string}>}>;bundleDigest:string};
export type ProductArtifactMaterialLineageSeedV2={contractVersion:"2";lineageVariant:"direct-canonical-evidence";organizationId:string;semanticOwner:ProductArtifactSemanticOwnerV1;productQuestionId:string;creationOperationId:string;lineagePolicyVersion:string;sourceBindings:Array<{sourceBindingId:string;bindingRevisionId:string}>;sourceContentVersions:Array<{sourceBindingId:string;sourceContentVersionId:string;normalizedContentDigest:string}>;canonicalMaterial:Array<{canonicalObjectId:string;revisionRef:string;owner:"canonical-evidence-admission"}>;canonicalUnderstandingRevision:null;projectionSourceRef:null;scopeDigest:string;purpose:string;sensitivity:"standard"|"restricted"|"private";directEvidenceProvenance:Omit<DirectCanonicalEvidenceProvenanceV2,"artifactId"|"artifactRevision"|"bundleDigest">;seedDigest:string};
export type ProductArtifactMaterialLineageSeed=ProductArtifactMaterialLineageSeedV1|ProductArtifactMaterialLineageSeedV2;
export type ProductArtifactMaterialLineageV1=ProductArtifactMaterialLineageSeedV1&{productWorkflowId?:string|null;artifactType:PersistedProductArtifactTypeV1;artifactId:string;artifactRevision:string;envelopeDigest:string};
export type ProductArtifactMaterialLineageV2=Omit<ProductArtifactMaterialLineageSeedV2,"directEvidenceProvenance">&{productWorkflowId:string;artifactType:PersistedProductArtifactTypeV1;artifactId:string;artifactRevision:string;directEvidenceProvenance:DirectCanonicalEvidenceProvenanceV2;envelopeDigest:string};
export type ProductArtifactMaterialLineage=ProductArtifactMaterialLineageV1|ProductArtifactMaterialLineageV2;

export function validateProductArtifactMaterialLineageSeedV1(seed:ProductArtifactMaterialLineageSeedV1):void{const{seedDigest,...unsigned}=seed,bindingIds=new Set(seed.sourceBindings.map(item=>item.sourceBindingId)),versionIds=new Set<string>();let valid=seed.contractVersion==="1"&&Boolean(seed.organizationId&&seed.productQuestionId&&seed.creationOperationId&&seed.lineagePolicyVersion&&seed.canonicalUnderstandingRevision&&seed.projectionSourceRef)&&seedDigest===productArtifactBodyDigest(unsigned)&&bindingIds.size===seed.sourceBindings.length&&bindingIds.size>0&&seed.sourceContentVersions.length>0&&seed.canonicalMaterial.length>0;for(const item of seed.sourceContentVersions){if(!bindingIds.has(item.sourceBindingId)||versionIds.has(item.sourceContentVersionId)||!/^[a-f0-9]{64}$/u.test(item.normalizedContentDigest))valid=false;versionIds.add(item.sourceContentVersionId);}if(!valid)throw new Error("Product artifact material lineage seed is invalid.");}

export function validateProductArtifactMaterialLineageSeed(seed:ProductArtifactMaterialLineageSeed):void{if(seed.contractVersion==="1")return validateProductArtifactMaterialLineageSeedV1(seed);const{seedDigest,...unsigned}=seed,p=seed.directEvidenceProvenance,hex=(value:string)=>/^[a-f0-9]{64}$/u.test(value);if(seed.lineageVariant!=="direct-canonical-evidence"||seed.canonicalUnderstandingRevision!==null||seed.projectionSourceRef!==null||!seed.scopeDigest||!seed.purpose||!seed.sensitivity||p.contractVersion!=="2"||p.lineageVariant!=="direct-canonical-evidence"||p.organizationId!==seed.organizationId||p.productQuestionId!==seed.productQuestionId||!p.ownerScopeRef||!p.sourceWorkflowRef||!p.artifactWorkflowRef||p.sourceWorkflowRef===p.artifactWorkflowRef||p.operationEnvelope.contributionOperationId!==seed.creationOperationId||p.materialization.canonicalOperationId!==p.operationEnvelope.contributionOperationId||p.admissionBatch.admissionDisposition==="not-admitted"||!p.evidence.length||![p.operationEnvelope.requestFingerprint,p.operationEnvelope.idempotencyKeyDigest,p.operationEnvelope.lineageEnvelopeDigest,p.operationEnvelope.operationRecordDigest,p.materialization.instructionDigest,p.materialization.materializationRecordDigest,p.materialization.receiptDigest,p.admissionBatch.batchDigest].every(hex)||!p.materialization.materializationRecordId||!p.materialization.receiptId||seedDigest!==productArtifactBodyDigest(unsigned))throw new Error("Direct Evidence material lineage seed is invalid.");const evidenceIds=new Set<string>(),admissionIds=new Set<string>(),attributionIds=new Set<string>(),bindings=new Map<string,string>();for(const evidence of p.evidence){if(evidenceIds.has(evidence.canonicalEvidenceId)||admissionIds.has(evidence.canonicalAdmissionId)||attributionIds.has(evidence.attributionId)||!evidence.sourceBindings.length||!hex(evidence.attributionDigest))throw new Error("Direct Evidence material lineage seed is ambiguous.");evidenceIds.add(evidence.canonicalEvidenceId);admissionIds.add(evidence.canonicalAdmissionId);attributionIds.add(evidence.attributionId);const local=new Set<string>();for(const binding of evidence.sourceBindings){const serialized=JSON.stringify(binding),prior=bindings.get(binding.sourceBindingId);if(local.has(binding.sourceBindingId)||(prior!==undefined&&prior!==serialized)||![binding.bindingRevisionDigest,binding.exactContentDigest,binding.normalizedContentDigest,binding.storageIntegrityDigest].every(hex))throw new Error("Direct Evidence material lineage seed is ambiguous.");local.add(binding.sourceBindingId);bindings.set(binding.sourceBindingId,serialized);}}}

export function completeProductArtifactMaterialLineageV1(input:{seed:ProductArtifactMaterialLineageSeed;productWorkflowId:string|null;artifactType:PersistedProductArtifactTypeV1;artifactId:string;artifactRevision:string}):ProductArtifactMaterialLineage{if(input.seed.contractVersion==="2"){if(!input.productWorkflowId)throw new Error("Direct Evidence material lineage target is invalid.");const provenanceUnsigned={...structuredClone(input.seed.directEvidenceProvenance),artifactId:input.artifactId,artifactRevision:input.artifactRevision},directEvidenceProvenance={...provenanceUnsigned,bundleDigest:productArtifactBodyDigest(provenanceUnsigned)},unsigned={...structuredClone(input.seed),productWorkflowId:input.productWorkflowId,artifactType:input.artifactType,artifactId:input.artifactId,artifactRevision:input.artifactRevision,directEvidenceProvenance};return{...unsigned,envelopeDigest:productArtifactBodyDigest(unsigned)};}const unsigned={...structuredClone(input.seed),productWorkflowId:input.productWorkflowId,artifactType:input.artifactType,artifactId:input.artifactId,artifactRevision:input.artifactRevision};return{...unsigned,envelopeDigest:productArtifactBodyDigest(unsigned)};}

export type ProductArtifactNonBodyClassV1="product-question-workspace"|"leadership-conversation-history"|"replay-receipt"|"materialization-receipt"|"source-reference"|"stage-record";
export function assertProductArtifactNonBodyClassV1(value:string):asserts value is ProductArtifactNonBodyClassV1{if(!["product-question-workspace","leadership-conversation-history","replay-receipt","materialization-receipt","source-reference","stage-record"].includes(value))throw new Error("Product artifact non-body classification is invalid.");}

export function completeProductArtifactInspectionMetadataV1(
  input: Omit<ProductArtifactInspectionMetadataV1, "contractVersion" | "headerDigest">,
): ProductArtifactInspectionMetadataV1 {
  validateProductArtifactBodyRefV1(input.protectedBody);
  if(input.materialLineage){const lineage=structuredClone(input.materialLineage);const{envelopeDigest,...unsignedLineage}=lineage;lineage.envelopeDigest=productArtifactBodyDigest(unsignedLineage);input={...input,materialLineage:lineage};}
  const unsigned = { contractVersion: "1" as const, ...input };
  return { ...unsigned, headerDigest: productArtifactBodyDigest(unsigned) };
}

export function validateProductArtifactInspectionMetadataV1(value: ProductArtifactInspectionMetadataV1): void {
  validateProductArtifactBodyRefV1(value.protectedBody);
  const { headerDigest, ...unsigned } = value;
  if(value.materialLineage){const{envelopeDigest,...lineage}=value.materialLineage;if(envelopeDigest!==productArtifactBodyDigest(lineage)||value.materialLineage.organizationId!==value.organizationId||value.materialLineage.semanticOwner!==value.semanticOwner||value.materialLineage.artifactType!==value.artifactType||value.materialLineage.artifactId!==value.artifactId||value.materialLineage.artifactRevision!==value.artifactRevision||value.materialLineage.productQuestionId!==value.productQuestionId||!value.materialLineage.seedDigest)throw new Error("Product artifact material lineage is invalid.");if(value.materialLineage.contractVersion==="2"){const p=value.materialLineage.directEvidenceProvenance,{bundleDigest,artifactId:_artifactId,artifactRevision:_artifactRevision,...bundle}=p,{productWorkflowId:_workflowId,artifactType:_artifactType,artifactId:_lineageArtifactId,artifactRevision:_lineageRevision,envelopeDigest:_envelope,directEvidenceProvenance:_provenance,...seed}=value.materialLineage;if(value.materialLineage.lineageVariant!=="direct-canonical-evidence"||value.materialLineage.productWorkflowId!==value.productWorkflowId||p.artifactId!==value.artifactId||p.artifactRevision!==value.artifactRevision||p.organizationId!==value.organizationId||p.productQuestionId!==value.productQuestionId||bundleDigest!==productArtifactBodyDigest({...bundle,artifactId:p.artifactId,artifactRevision:p.artifactRevision}))throw new Error("Direct Evidence material lineage is invalid.");validateProductArtifactMaterialLineageSeed({...seed,directEvidenceProvenance:bundle});}else{const bindingIds=new Set(value.materialLineage.sourceBindings.map(item=>item.sourceBindingId)),versionAssociations=new Map<string,string>();let associationValid=bindingIds.size===value.materialLineage.sourceBindings.length;for(const item of value.materialLineage.sourceContentVersions){const association=`${item.sourceBindingId}\u0000${item.normalizedContentDigest}`,previous=versionAssociations.get(item.sourceContentVersionId);if(!item.sourceBindingId||!item.sourceContentVersionId||!/^[a-f0-9]{64}$/u.test(item.normalizedContentDigest)||!bindingIds.has(item.sourceBindingId)||previous!==undefined)associationValid=false;versionAssociations.set(item.sourceContentVersionId,association);}const contextual=value.artifactType!=="prepared-work"&&value.artifactType!=="frozen-snapshot"||Boolean(value.materialLineage.productWorkflowId===value.productWorkflowId&&value.materialLineage.productWorkflowId&&value.materialLineage.scopeDigest&&value.materialLineage.purpose&&value.materialLineage.sensitivity);if(!value.materialLineage.sourceBindings.length||!value.materialLineage.sourceContentVersions.length||!value.materialLineage.canonicalMaterial.length||!associationValid||!contextual)throw new Error("Product artifact material lineage is invalid.");}}
  if (
    value.contractVersion !== "1" ||
    (value.publicationProofVersion !== undefined && value.publicationProofVersion !== "1") ||
    value.organizationId !== value.protectedBody.organizationId ||
    value.semanticOwner !== value.protectedBody.semanticOwner ||
    value.artifactType !== value.protectedBody.artifactType ||
    value.artifactId !== value.protectedBody.artifactId ||
    value.artifactRevision !== value.protectedBody.artifactRevision ||
    headerDigest !== productArtifactBodyDigest(unsigned)
  ) throw new Error("Product artifact inspection metadata is invalid.");
}
