import type { ScopedGovernanceContext } from "../../engine/v3/governance/scopedGovernanceContext";
import type { ProductArtifactInspectionMetadataV1 } from "./productArtifactInspectionMetadataContracts";

export const PRODUCT_ARTIFACT_CURRENT_ACCESS_CONTRACT_VERSION = "1" as const;
export type ProductArtifactCurrentAccessOperationV1 = "product-artifact:read"|"product-artifact:reuse"|"product-artifact:compare"|"product-artifact:prepare-again"|"product-artifact:create-successor";
export type ProductArtifactCurrentAccessRequestV1={contractVersion:"1";organizationId:string;subjectId:string;operation:ProductArtifactCurrentAccessOperationV1;purpose:string;scopeDigest:string;sensitivity:"standard"|"restricted"|"private";evaluatedAt:string;metadata:ProductArtifactInspectionMetadataV1;governance:ScopedGovernanceContext};
export type ProductArtifactCurrentAccessBasisV2=
  |{contractVersion:"2";kind:"canonical-understanding";canonicalUnderstandingRevision:string}
  |{contractVersion:"2";kind:"direct-canonical-evidence";canonicalUnderstandingRevision:null;provenanceBundleDigest:string};
export type ProductArtifactCurrentOwnerStateV1={contractVersion:"1";organizationId:string;productQuestionId:string;sourceGovernanceDigest:string|null;eligibilityDigest:string|null;eligibilityDisposition:"eligible"|"withheld"|"unavailable";projectionRevision:string|null;projectionDigest:string|null;canonicalUnderstandingRevision:string|null;canonicalChangeResultDigest:string|"not-applicable"|null;lineagePolicyVersion:string|null;accessBasis?:ProductArtifactCurrentAccessBasisV2};
export type ProductArtifactCurrentAccessResultV1={contractVersion:"1";organizationId:string;subjectId:string;artifactType:string;artifactId:string;artifactRevision:string;operation:ProductArtifactCurrentAccessOperationV1;purpose:string;scopeDigest:string;sensitivity:ProductArtifactCurrentAccessRequestV1["sensitivity"];evaluatedAt:string;disposition:"eligible"|"withheld"|"unavailable";metadataHeaderDigest:string;bodyRefDigest:string;authorityRevisionRefs:readonly string[];policyRevisionRefs:readonly string[];sourceGovernanceDigest:string|null;eligibilityDigest:string|null;projectionRevision:string|null;projectionDigest:string|null;canonicalUnderstandingRevision:string|null;canonicalChangeResultDigest:string|"not-applicable"|null;lineagePolicyVersion:string|null;accessBasis?:ProductArtifactCurrentAccessBasisV2;resultDigest:string};
export type FuturePreparationItemStateV1="eligible-unchanged"|"eligible-changed"|"resolved"|"withheld"|"unavailable"|"superseded"|"invalid";

export const HISTORICAL_PREDECESSOR_CURRENT_ACCESS_CONTRACT_VERSION = "2" as const;
/** Aggregate Prepared Work projection is all-or-nothing; section-level partial disclosure is unsupported. */
export type HistoricalPredecessorCurrentAccessOutcomeV2 = "accessible"|"withheld"|"absent"|"stale"|"revoked"|"foreign"|"ambiguous"|"malformed";
export type HistoricalPredecessorCurrentAccessRequestV2={contractVersion:"2";organizationId:string;predecessorArtifactOrganizationId:string;productQuestionId:string;meetingSeriesId:string;predecessorOccurrenceId:string;predecessorConversationId:string;predecessorCheckpointId:string;subjectId:string;artifactId:string;artifactRevision:string;headerDigest:string;bodyRefDigest:string;purpose:string;scopeDigest:string;sensitivity:"standard"|"restricted"|"private";evaluatedAt:string};
export type HistoricalPredecessorBodySafeProjectionV2={contractVersion:"2";organizationId:string;productQuestionId:string;meetingSeriesId:string;predecessorOccurrenceId:string;predecessorConversationId:string;predecessorCheckpointId:string;artifactId:string;artifactRevision:string;headerDigest:string;bodyRefDigest:string;materialLineageDigest:string;content:{whatChanged:string[];whatMattersNow:string[];tensions:string[];unknowns:string[];commitments:string[];questions:string[];uncertainty:string[]};projectionDigest:string};
export type HistoricalPredecessorCurrentAccessResultV2={contractVersion:"2";organizationId:string;productQuestionId:string;meetingSeriesId:string;predecessorOccurrenceId:string;predecessorConversationId:string;predecessorCheckpointId:string;subjectId:string;artifactId:string;artifactRevision:string;outcome:HistoricalPredecessorCurrentAccessOutcomeV2;projection:HistoricalPredecessorBodySafeProjectionV2|null;currentAccessResultDigest:string|null;resultDigest:string};
