"use client";

import { useActionState, useEffect, useMemo, useState, useTransition } from "react";
import type { ChiefFirstPrepareViewV1, LeadershipConversationWorkspaceV1, ProposalDisposition } from "../../../product/workflow/leadershipConversation";
import type { ChiefOfStaffValueLayerV1 } from "../../../product/workflow/leadershipConversation/chiefCommunicationPlan";
import type { ContentSafePersonalRoomSheetViewV1 } from "../../../product/workflow/leadershipConversation/personalRoomSheetContracts";
import { acceptOccurrence1EvidenceAction, captureOccurrence1Action, completeOccurrence1Action, freezeOccurrence1FormAction, prepareAgainOccurrence1Action, reviewOccurrence1ProposalAction, submitAlphaProgressiveDisclosureAction } from "../../../app/product-alpha/leadership-conversation/actions";
import { LeadershipConversationPrepare } from "./LeadershipConversationPrepare";
import { PersonalRoomSheetPanel } from "./PersonalRoomSheetPanel";
import { LeadershipConversationObservabilityObserver } from "./LeadershipConversationObservabilityObserver";
import type { AlphaContentSafeObservabilityEventV1 } from "../../../lib/observability/alphaContentSafeObservabilityContracts";
import styles from "./LeadershipConversationExperience.module.css";
import { AlphaTelemetryNotice } from "./AlphaTelemetryNotice";

type Props = { initialWorkspace: LeadershipConversationWorkspaceV1; prepare: ChiefFirstPrepareViewV1; valueLayer:ChiefOfStaffValueLayerV1; personalSheet: ContentSafePersonalRoomSheetViewV1; occurrenceRef: string; initialCheckpoint: { checkpointId: string; contributionArtifactIds: string[] } | null; initialNextPrepare?: ChiefFirstPrepareViewV1 | null; telemetryNotice?:boolean };
const stepLabels = ["Conversation ready", "Meeting brief", "Private notes", "Share selections", "Begin meeting", "Record outcome", "Review results", "Close cycle"];

export function LeadershipConversationExperience({ initialWorkspace, prepare, valueLayer, personalSheet, occurrenceRef, initialCheckpoint, initialNextPrepare = null, telemetryNotice=false }: Props) {
  const [freezeState, freezeFormAction] = useActionState(freezeOccurrence1FormAction, { checkpointId: initialCheckpoint?.checkpointId ?? null, contributionArtifactIds: initialCheckpoint?.contributionArtifactIds ?? [], workspace: initialWorkspace, error: null });
  const [workspace, setWorkspace] = useState(freezeState.workspace), [nextPrepare, setNextPrepare] = useState(initialNextPrepare), [nextValueLayer,setNextValueLayer]=useState<ChiefOfStaffValueLayerV1|null>(null), [selectedItems, setSelectedItems] = useState<string[]>([]), [meetingNotes, setMeetingNotes] = useState(""), [error, setError] = useState<string | null>(null), [pending, startTransition] = useTransition();
  const [browserObservation,setBrowserObservation]=useState<{stage:AlphaContentSafeObservabilityEventV1["workflowStage"];transition:AlphaContentSafeObservabilityEventV1["transitionCategory"];outcome:AlphaContentSafeObservabilityEventV1["outcomeCategory"];viewport:AlphaContentSafeObservabilityEventV1["viewportCategory"]}|null>(null);
  useEffect(() => { setWorkspace(freezeState.workspace); setError(freezeState.error); }, [freezeState]);
  useEffect(()=>{if(error)setBrowserObservation({stage:"acceptance",transition:"completed",outcome:"browser-failure",viewport:window.matchMedia("(max-width: 700px)").matches?"narrow":"desktop"});},[error]);
  const reviewed = useMemo(() => new Set(workspace.dispositions.map(item => item.proposalId)), [workspace.dispositions]);
  const dispositionByProposal = useMemo(() => new Map(workspace.dispositions.map(item => [item.proposalId, item.disposition])), [workspace.dispositions]);
  const hasFreeze = workspace.currentStep !== "freeze" && workspace.currentStep !== "prepare" && workspace.currentStep !== "set-up", hasCapture = Boolean(workspace.uploadReceipt), completed = Boolean(workspace.closureCompletion);
  const currentStage = completed ? null : workspace.currentStep === "review" ? 6 : workspace.currentStep === "capture" ? 5 : selectedItems.length ? 4 : 2;
  const completedStageCount = completed ? stepLabels.length : currentStage ?? 0;
  const nextAction = completed ? "Prepare the next occurrence" : workspace.currentStep === "review" ? "Review each result, then close this cycle" : workspace.currentStep === "capture" ? "Record what happened in the meeting" : selectedItems.length ? "Freeze the selected contribution and begin the meeting" : "Freeze with no contribution, or choose Private Working to contribute";
  const run = (work: () => Promise<LeadershipConversationWorkspaceV1>) => { setError(null); startTransition(() => { void work().then(setWorkspace).catch(() => setError("This step is unavailable. Refresh the page or confirm your access.")); }); };
  const capture = () => { if (freezeState.checkpointId && meetingNotes.trim()) run(() => captureOccurrence1Action({ meetingNotes })); };
  const review = (proposalId: string, disposition: ProposalDisposition) => run(() => reviewOccurrence1ProposalAction({ proposalId, disposition }));
  const acceptEvidence = (proposalId: string) => run(() => acceptOccurrence1EvidenceAction({ proposalId }));
  const prepareAgain = () => { setError(null); startTransition(() => { void prepareAgainOccurrence1Action().then(result => { setWorkspace(result.sourceWorkspace); setNextPrepare(result.nextPrepare);setNextValueLayer(result.valueLayer); }).catch(() => setError("Prepare Again is unavailable. Refresh the page or confirm your access.")); }); };

  const observeBrowser=(stage:AlphaContentSafeObservabilityEventV1["workflowStage"],transition:AlphaContentSafeObservabilityEventV1["transitionCategory"],outcome:AlphaContentSafeObservabilityEventV1["outcomeCategory"])=>setBrowserObservation({stage,transition,outcome,viewport:window.matchMedia("(max-width: 700px)").matches?"narrow":"desktop"});
  return <main className={styles.page}><LeadershipConversationObservabilityObserver observation={browserObservation}/>
    <header className={styles.hero}><p className={styles.eyebrow}>Leadership conversation · Occurrence 1</p><h1>{prepare.meeting.title}</h1><p>{prepare.meeting.purpose}</p><p role="status" aria-live="polite">{error ?? (pending ? "Saving this step…" : completed ? "Occurrence 1 is complete." : "Your meeting is ready.")}</p></header>
    <nav className={styles.workflow} aria-label="Occurrence 1 progress"><div className={styles.workflowSummary}><div><p className={styles.workflowLabel}>{completed ? "Cycle status" : "Current stage"}</p><h2>{completed ? "Cycle complete" : stepLabels[currentStage!]}</h2></div><p><strong>Next:</strong> {nextAction}</p></div><ol className={styles.steps}><li data-state="complete"><span>Completed</span>{completedStageCount} of {stepLabels.length} stages</li>{currentStage !== null && <li data-state="current" aria-current="step"><span>Now · step {currentStage + 1}</span>{stepLabels[currentStage]}</li>}{currentStage !== null && currentStage + 1 < stepLabels.length && <li data-state="future"><span>Later · step {currentStage + 2}</span>{stepLabels[currentStage + 1]}</li>}</ol></nav>
    {telemetryNotice&&<AlphaTelemetryNotice/>}<section className={styles.card} aria-labelledby="prepare-heading"><div className={styles.stageHeading}><p className={styles.badge}>Prepared</p><p>Use this to focus the conversation. It is guidance, not a meeting record.</p></div><LeadershipConversationPrepare prepare={prepare} valueLayer={valueLayer} onProgressiveDisclosure={category=>{void submitAlphaProgressiveDisclosureAction(category).catch(()=>{});}} /></section>
    <PersonalRoomSheetPanel initialSheet={personalSheet} occurrenceRef={occurrenceRef} contributedItemIds={selectedItems} onPrivateWorkingOpened={()=>observeBrowser("private-working","completed","success")} onContribute={items=>{observeBrowser("contribute","completed","success");setSelectedItems(items);}} contributionLocked={hasFreeze} disabled={hasCapture || completed} />
    <section className={`${styles.card} ${hasFreeze ? styles.completedCard : styles.currentCard}`} aria-labelledby="freeze-heading"><p className={styles.badge}>{hasFreeze ? "Meeting started" : "Consequential boundary"}</p><h2 id="freeze-heading">{hasFreeze ? "Preparation frozen" : "Freeze and begin the meeting"}</h2><p>{hasFreeze ? (freezeState.contributionArtifactIds.length ? "Only your explicitly selected contribution crossed the meeting boundary. Unselected Private Working was not retained." : "No Private Working content was contributed. Unselected Private Working was not retained.") : "Freeze fixes this preparation and only the Private Working items you explicitly selected. You may continue with no contribution; unselected private notes will not persist."}</p>{!hasFreeze && <form action={freezeFormAction}><input type="hidden" name="preparedWorkProductVersionId" value={prepare.provenance.preparedWorkProductVersionId} /><input type="hidden" name="expectedPersonalRoomSheetDigest" value={personalSheet.personalRoomSheetDigest} />{selectedItems.map(itemId => <input key={itemId} type="hidden" name="contributedItemId" value={itemId} />)}<button className={styles.primaryAction} type="submit" disabled={pending}>Freeze preparation and begin meeting</button></form>}</section>
    <section className={`${styles.card} ${!hasFreeze ? styles.futureCard : hasCapture ? styles.completedCard : styles.currentCard}`} aria-labelledby="capture-heading"><p className={styles.badge}>{hasCapture ? "Outcome recorded" : hasFreeze ? "After the meeting" : "Later"}</p><h2 id="capture-heading">Capture what happened</h2>{!hasFreeze ? <p>Available after you freeze the preparation and begin the meeting.</p> : <><p>{freezeState.contributionArtifactIds.length ? "Only the items you explicitly contributed from Private Working accompany this meeting record." : "No Private Working content accompanies this meeting record."}</p>{!hasCapture && <><p className={styles.selectionStatus}>{freezeState.contributionArtifactIds.length ? `${freezeState.contributionArtifactIds.length} private working item${freezeState.contributionArtifactIds.length === 1 ? "" : "s"} contributed at Freeze.` : "No Private Working content was contributed."}</p><label>Meeting notes<textarea value={meetingNotes} disabled={pending} onChange={event => setMeetingNotes(event.target.value)} placeholder="Record the decision, owner and next step, or what changed the view." /></label><button className={styles.primaryAction} type="button" disabled={!freezeState.checkpointId || !meetingNotes.trim() || pending} onClick={capture}>Record meeting outcome</button></>}{hasCapture && <p role="status">Capture is recorded and ready for your review.</p>}</>}</section>
    {workspace.proposals.length > 0 && <section className={styles.card} aria-labelledby="review-heading"><p className={styles.badge}>Review</p><h2 id="review-heading">Review the consequential results</h2><p>Choose what becomes durable Evidence, what remains open, and what should not be carried forward. Nothing is accepted automatically.</p><div className={styles.reviewList}>{workspace.proposals.map(proposal => { const disposition = dispositionByProposal.get(proposal.proposalId), routed = workspace.canonicalRoutingReceipts.some(item => item.proposalId === proposal.proposalId), evidenceAcceptance = disposition === "approved" && proposal.kind === "evidence-candidate"; return <article key={proposal.proposalId} className={styles.reviewItem}><h3>{proposal.kind === "decision-draft" ? "Possible decision" : proposal.kind === "commitment" ? "Possible follow-through" : proposal.kind === "unknown" ? "Open question" : "Possible new information"}</h3><p>{proposal.payload.summary}</p>{evidenceAcceptance ? <><p className={styles.reviewed}>{routed ? "Accepted as Evidence" : "Acceptance pending"}</p>{!routed && <div className={styles.actions}><button type="button" disabled={pending} onClick={() => acceptEvidence(proposal.proposalId)}>Complete Evidence acceptance</button></div>}</> : disposition === "approved" ? <p className={styles.reviewed}>{routed ? "Approved result" : "Approval pending"}</p> : reviewed.has(proposal.proposalId) ? <p className={styles.reviewed}>{disposition === "deferred" ? "Kept open" : "Not carried forward"}</p> : <div className={styles.actions}>{proposal.kind === "evidence-candidate" && <button type="button" disabled={pending} onClick={() => acceptEvidence(proposal.proposalId)}>Accept as Evidence</button>}<button type="button" disabled={pending} onClick={() => review(proposal.proposalId, "deferred")}>Keep open</button><button type="button" disabled={pending} onClick={() => review(proposal.proposalId, "rejected")}>Do not carry forward</button></div>}</article>; })}</div>{!completed && workspace.actions.some(action => action.id === "complete-closure" && action.enabled) && <button type="button" disabled={pending} onClick={() => run(completeOccurrence1Action)}>Complete Occurrence 1</button>}</section>}
    {workspace.closureCompletion && <section className={`${styles.card} ${styles.completion}`} aria-labelledby="complete-heading"><p className={styles.badge}>Occurrence 1 complete</p><h2 id="complete-heading">This meeting is closed</h2><p>The reviewed outcome below is the truthful record of this occurrence.</p>{workspace.closureCompletion.sections.map(section => <section key={section.label}><h3>{section.label}</h3>{section.items.map(item => <p key={item}>{item}</p>)}</section>)}</section>}
    {workspace.closureCompletion && <section className={styles.card} aria-labelledby="prepare-again-heading"><p className={styles.badge}>What changed</p><h2 id="prepare-again-heading">Carry the reviewed outcome forward</h2><p>Only the reviewed closure and current authorized evidence will shape the next preparation. Private Working and unreviewed meeting content do not carry forward.</p>{nextPrepare ? <><p role="status">Occurrence 2 is prepared, but the next meeting has not started.</p><LeadershipConversationPrepare prepare={nextPrepare} valueLayer={nextValueLayer??undefined} /></> : <button type="button" disabled={pending} onClick={prepareAgain}>Prepare Again</button>}</section>}
    {error && <p role="alert" className={styles.error}>{error}</p>}<footer><p>Protected details stay hidden when access is unavailable.</p><p className={styles.srOnly}>Current workflow step: {workspace.currentStep}</p></footer>
  </main>;
}
