import type { ChiefFirstPrepareViewV1, Cycle1ClosureCompletionV1, LeadershipConversationWorkspaceV1, ProposalDisposition } from "../../../product/workflow/leadershipConversation";
import type { LeadershipConversationConsequenceCandidateV1 } from "../../../product/workflow/leadershipConversation/contracts";
import type { ChiefOfStaffValueLayerV1 } from "../../../product/workflow/leadershipConversation/chiefCommunicationPlan";
import { LeadershipConversationPrepare } from "./LeadershipConversationPrepare";
import styles from "./LeadershipConversationExperience.module.css";
import type { StudioPresentationSnapshotV1 } from "../../../lib/discovery-studio/contracts";

export const DISCOVERY_STUDIO_PREVIEW_LABEL="Synthetic Studio Preview — not canonical Product history" as const;
type ReviewBase={workspace:LeadershipConversationWorkspaceV1;pending?:boolean};
type ReviewProps=ReviewBase&({mode:"preview";candidates?:LeadershipConversationConsequenceCandidateV1[];onReview?:never;onAcceptEvidence?:never;onComplete?:never}|{mode:"interactive";candidates?:never;onReview:(proposalId:string,disposition:ProposalDisposition)=>void;onAcceptEvidence:(proposalId:string)=>void;onComplete:()=>void});
const candidateLabel=(kind:LeadershipConversationConsequenceCandidateV1["candidateKind"])=>({decision:"Decision","non-decision":"Non-decision",commitment:"Commitment","open-question":"Open question","resolved-unknown":"Resolved unknown",recommendation:"Recommendation",contradiction:"Contradiction","inferred-assessment":"Assessment","source-grounded-observation":"Observation",mechanism:"Mechanism","new-unknown":"New unknown","suspected-possibility":"Possibility","executive-attention-item":"Attention shift","no-intervention-item":"No intervention"}[kind]);
export function LeadershipConversationReviewSurface(props:ReviewProps){
 if(props.mode==="preview")return <section className={styles.card} aria-labelledby="studio-review-heading"><p className={styles.badge}>Review</p><p role="note">{DISCOVERY_STUDIO_PREVIEW_LABEL}</p><h2 id="studio-review-heading">Review the consequential results</h2><p>Inspect what is supported, inferred, unresolved, or proposed. Preview actions never write Product history.</p><div className={styles.reviewList}>{(props.candidates??[]).map(candidate=><article key={candidate.candidateId} className={styles.reviewItem}><h3>{candidateLabel(candidate.candidateKind)}</h3><p>{candidate.statement}</p><p className={styles.reviewed}>{candidate.epistemicCategory} · {candidate.supportCategory}</p>{candidate.owner&&<p>Owner: {candidate.owner}</p>}{candidate.dueDate&&<p>Due: {candidate.dueDate}</p>}</article>)}</div></section>;
 const {workspace,pending=false}=props,reviewed=new Set(workspace.dispositions.map(item=>item.proposalId)),dispositionByProposal=new Map(workspace.dispositions.map(item=>[item.proposalId,item.disposition])),completed=Boolean(workspace.closureCompletion);
 return workspace.proposals.length?<section className={styles.card} aria-labelledby="review-heading"><p className={styles.badge}>Review</p><h2 id="review-heading">Review the consequential results</h2><p>Choose what becomes durable Evidence, what remains open, and what should not be carried forward. Nothing is accepted automatically.</p><div className={styles.reviewList}>{workspace.proposals.map(proposal=>{const disposition=dispositionByProposal.get(proposal.proposalId),routed=workspace.canonicalRoutingReceipts.some(item=>item.proposalId===proposal.proposalId),evidenceAcceptance=disposition==="approved"&&proposal.kind==="evidence-candidate";return <article key={proposal.proposalId} className={styles.reviewItem}><h3>{proposal.kind==="decision-draft"?"Possible decision":proposal.kind==="commitment"?"Possible follow-through":proposal.kind==="unknown"?"Open question":"Possible new information"}</h3><p>{proposal.payload.summary}</p>{evidenceAcceptance?<><p className={styles.reviewed}>{routed?"Accepted as Evidence":"Acceptance pending"}</p>{!routed&&<div className={styles.actions}><button type="button" disabled={pending} onClick={()=>props.onAcceptEvidence(proposal.proposalId)}>Complete Evidence acceptance</button></div>}</>:disposition==="approved"?<p className={styles.reviewed}>{routed?"Approved result":"Approval pending"}</p>:reviewed.has(proposal.proposalId)?<p className={styles.reviewed}>{disposition==="deferred"?"Kept open":"Not carried forward"}</p>:<div className={styles.actions}>{proposal.kind==="evidence-candidate"&&<button type="button" disabled={pending} onClick={()=>props.onAcceptEvidence(proposal.proposalId)}>Accept as Evidence</button>}<button type="button" disabled={pending} onClick={()=>props.onReview(proposal.proposalId,"deferred")}>Keep open</button><button type="button" disabled={pending} onClick={()=>props.onReview(proposal.proposalId,"rejected")}>Do not carry forward</button></div>}</article>})}</div>{!completed&&workspace.actions.some(action=>action.id==="complete-closure"&&action.enabled)&&<button type="button" disabled={pending} onClick={props.onComplete}>Complete Occurrence 1</button>}</section>:null;
}

export function LeadershipConversationClosureSurface({closure,mode}:{closure:Cycle1ClosureCompletionV1|null;mode:"interactive"|"preview"}){const headingId=mode==="interactive"?"complete-heading":"preview-complete-heading";return closure?<section className={`${styles.card} ${styles.completion}`} aria-labelledby={headingId}>{mode==="preview"&&<p role="note">{DISCOVERY_STUDIO_PREVIEW_LABEL}</p>}<p className={styles.badge}>Occurrence 1 complete</p><h2 id={headingId}>This meeting is closed</h2><p>The reviewed outcome below is the truthful record of this occurrence.</p>{closure.sections.map(section=><section key={section.label}><h3>{section.label}</h3>{section.items.map(item=><p key={item}>{item}</p>)}</section>)}</section>:null}

type WhatChangedProps={closure:Cycle1ClosureCompletionV1|null;nextPrepare:ChiefFirstPrepareViewV1|null;nextValueLayer?:ChiefOfStaffValueLayerV1|null}&({mode:"preview";studioSnapshot?:StudioPresentationSnapshotV1["whatChanged"];onPrepareAgain?:never}|{mode:"interactive";studioSnapshot?:never;onPrepareAgain:()=>void;pending?:boolean});
export function LeadershipConversationWhatChangedSurface(props:WhatChangedProps){const headingId=props.mode==="interactive"?"prepare-again-heading":"preview-prepare-again-heading",explanation=props.mode==="interactive"?"Only the reviewed closure and current authorized evidence will shape the next preparation. Private Working and unreviewed meeting content do not carry forward.":"Only supported before/after consequences are shown. A continuing statement is not treated as a change without an explicit comparison.";return props.closure?<section className={styles.card} aria-labelledby={headingId}>{props.mode==="preview"&&<p role="note">{DISCOVERY_STUDIO_PREVIEW_LABEL}</p>}<p className={styles.badge}>What changed</p><h2 id={headingId}>Carry the reviewed outcome forward</h2><p>{explanation}</p>{props.mode==="preview"&&props.studioSnapshot?<>{props.studioSnapshot.items.length?props.studioSnapshot.items.map((item,index)=><article key={`${item.kind}:${index}:${item.statement}`}><h3>{item.kind.replaceAll("-"," ")}</h3>{item.before&&<p>Before: {item.before}</p>}{item.after&&<p>After: {item.after}</p>}<p>{item.statement}</p>{item.sourceReferences.length?<p>{item.sourceReferences.length} source reference{item.sourceReferences.length===1?"":"s"}</p>:<p>Provenance unavailable</p>}</article>):<p>No supported changes are available.</p>}{props.studioSnapshot.omissions.map(item=><p key={item}>{item}</p>)}</>:props.nextPrepare?<><p role="status">Occurrence 2 is prepared, but the next meeting has not started.</p><LeadershipConversationPrepare prepare={props.nextPrepare} valueLayer={props.nextValueLayer??undefined}/></>:props.mode==="interactive"?<button type="button" disabled={props.pending} onClick={props.onPrepareAgain}>Prepare Again</button>:<p>Next preparation is unavailable in this snapshot.</p>}</section>:null}
