import type { OrganizationalMeaningId } from "./types";

export type MeaningDefinition = {
  id: OrganizationalMeaningId;
  label: string;
  description: string;
  terms: string[];
};

export const MEANING_CATALOG: MeaningDefinition[] = [
  {
    id: "decision_authority",
    label: "Decision Authority",
    description: "How decision rights are distributed across the organization.",
    terms: [
      "approval",
      "approve",
      "authorization",
      "permission",
      "sign-off",
      "decision",
      "decide",
      "authority",
      "empowered",
      "escalate",
      "executive",
      "leadership",
      "manager",
    ],
  },
  {
    id: "governance",
    label: "Governance",
    description: "How work is reviewed, controlled, and formally approved.",
    terms: [
      "committee",
      "review",
      "process",
      "approval",
      "governance",
      "control",
      "oversight",
      "revisit",
      "board",
    ],
  },
  {
    id: "execution_capacity",
    label: "Execution Capacity",
    description: "The organization’s ability to convert intent into delivery.",
    terms: [
      "execution",
      "delivery",
      "capacity",
      "bandwidth",
      "follow-through",
      "implementation",
      "complete",
      "slowing",
      "delayed",
      "constraint",
    ],
  },
  {
    id: "organizational_agility",
    label: "Organizational Agility",
    description: "How quickly the organization can adapt, decide, and move.",
    terms: [
      "agility",
      "slow",
      "stall",
      "wait",
      "delay",
      "momentum",
      "speed",
      "responsive",
      "adapt",
    ],
  },
  {
    id: "innovation_flow",
    label: "Innovation Flow",
    description: "The organization’s ability to move new ideas into action.",
    terms: [
      "innovation",
      "experiment",
      "new idea",
      "initiative",
      "prototype",
      "learning",
      "change",
      "creative",
    ],
  },
  {
    id: "knowledge_continuity",
    label: "Knowledge Continuity",
    description: "Whether important knowledge survives handoffs and turnover.",
    terms: [
      "knowledge",
      "handoff",
      "turnover",
      "lost",
      "leaves",
      "resign",
      "continuity",
      "context",
      "tribal",
    ],
  },
  {
    id: "organizational_memory",
    label: "Organizational Memory",
    description: "How well the organization preserves what it has learned.",
    terms: [
      "memory",
      "remember",
      "documented",
      "history",
      "learned",
      "rediscover",
      "repeat",
      "institutional",
    ],
  },
  {
    id: "risk_appetite",
    label: "Risk Appetite",
    description: "The organization’s willingness to act despite uncertainty.",
    terms: [
      "risk",
      "cautious",
      "fear",
      "failure",
      "safe",
      "avoid",
      "uncertain",
      "permission",
    ],
  },
  {
    id: "accountability",
    label: "Accountability",
    description: "Clarity about who owns outcomes and consequences.",
    terms: [
      "accountability",
      "responsible",
      "responsibility",
      "outcome",
      "owner",
      "ownership",
      "blame",
    ],
  },
  {
    id: "alignment",
    label: "Alignment",
    description: "Whether teams share priorities and direction.",
    terms: [
      "alignment",
      "misaligned",
      "priority",
      "priorities",
      "direction",
      "strategy",
      "disconnect",
      "conflict",
    ],
  },
  {
    id: "coordination",
    label: "Coordination",
    description: "How effectively teams work together across boundaries.",
    terms: [
      "coordination",
      "handoff",
      "silo",
      "cross-functional",
      "team",
      "dependencies",
      "collaborate",
    ],
  },
  {
    id: "communication",
    label: "Communication",
    description: "How clearly information moves through the organization.",
    terms: [
      "communication",
      "message",
      "narrative",
      "clarity",
      "unclear",
      "inform",
      "shared",
    ],
  },
  {
    id: "resource_allocation",
    label: "Resource Allocation",
    description: "How people, budget, and attention are assigned to work.",
    terms: [
      "resource",
      "budget",
      "staffing",
      "headcount",
      "hiring",
      "roles",
      "allocation",
      "capacity",
    ],
  },
  {
    id: "customer_responsiveness",
    label: "Customer Responsiveness",
    description: "How quickly the organization responds to customer needs.",
    terms: [
      "customer",
      "support",
      "issue",
      "resolve",
      "response",
      "frontline",
      "escalate",
    ],
  },
  {
    id: "strategic_uncertainty",
    label: "Strategic Uncertainty",
    description: "Unsettled questions about strategy, direction, or priorities.",
    terms: [
      "strategic",
      "strategy",
      "uncertain",
      "unknown",
      "bet",
      "direction",
      "market",
      "question",
    ],
  },
  {
    id: "leadership_dependency",
    label: "Leadership Dependency",
    description: "The degree to which progress depends on senior leaders.",
    terms: [
      "leadership",
      "executive",
      "founder",
      "ceo",
      "senior",
      "approval",
      "dependent",
      "sign-off",
    ],
  },
  {
    id: "operational_complexity",
    label: "Operational Complexity",
    description: "Complexity created by processes, dependencies, or structure.",
    terms: [
      "complexity",
      "complex",
      "process",
      "dependencies",
      "layers",
      "friction",
      "bureaucracy",
    ],
  },
];