import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { assertAlphaContentSafeObservabilityEventV1, type AlphaContentSafeObservabilityEventV1 } from "../../lib/observability/alphaContentSafeObservabilityContracts";
import { AlphaContentSafeObservabilityOwner, alphaObservationDefaults } from "../../lib/observability/alphaContentSafeObservabilityOwner";
import { FilesystemOrganizationRuntimeRepository, RuntimeStorageConflictError } from "../../engine/v3/runtime/organizationRuntimeRepository";
import { ALPHA_ALLOWLIST_POLICY_ID, ALPHA_ALLOWLIST_POLICY_VERSION, type AlphaOrganizationAccessRecord } from "../../engine/v3/governance/alphaAllowlistDisclosureProducer";
import { onboardingTestOrganizationId } from "../../lib/onboarding/testing/onboardingTestOrganization";
import { recoverDevelopmentOrganizationRuntime, type DevelopmentRuntimeRecoveryLineage, type DevelopmentRuntimeRecoveryLineageRepository } from "../../lib/onboarding/testing/developmentRuntimeRecovery";
import { scanText } from "./protectedValueScanner";

const evidenceRoot="docs/agent-work-orders/evidence/alpha-readiness/ar3",jsonPath=path.join(evidenceRoot,"AR3_CONTENT_SAFE_OBSERVABILITY_RESULTS.json"),reportPath=path.join(evidenceRoot,"AR3_CONTENT_SAFE_OBSERVABILITY_REPORT.md");
const requiredJourney=["activate","prepare","private-working","contribute","freeze","reload","capture","review","closure","what-changed","prepare-again","occurrence-2","acceptance","cleanup"] as const;
const sourcePaths=["lib/observability/alphaContentSafeObservabilityContracts.ts","lib/observability/alphaContentSafeObservabilityOwner.ts","lib/operations/alphaOperationalLog.ts","components/product-shell/data/loadActivatedYourOrganization.ts","app/api/health/route.ts","engine/v3/runtime/organizationRuntimeRepository.ts","engine/v3/runtime/evolveOrganizationRuntime.ts","product/integration/leadershipConversationServerComposition.ts","product/workflow/leadershipConversation/productWorkflowArtifactRepository.ts","app/product-alpha/leadership-conversation/actions.ts","app/product-alpha/leadership-conversation/page.tsx","components/product-alpha/leadership-conversation/LeadershipConversationObservabilityObserver.tsx","components/product-alpha/leadership-conversation/LeadershipConversationExperience.tsx","components/product-alpha/leadership-conversation/PersonalRoomSheetPanel.tsx","scripts/alpha-readiness/runContentSafeObservabilityHarness.ts","scripts/product/validateAlphaContentSafeObservability.ts","scripts/product/validateLeadershipConversationReplay.ts","scripts/product/validateLeadershipConversationFrontend.ts","package.json"] as const;
const protectedValues=[{category:"protected",value:"AR3 readiness protected sentinel"},{category:"credential",value:"AR3-secret-credential"},{category:"identity",value:"AR3-person@example.test"}] as const;
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
async function sourceDigest(){return sha((await Promise.all(sourcePaths.map(async file=>`${file}\0${await readFile(file,"utf8")}`))).join("\0"));}
function execute(script:string,extraEnv:Record<string,string>={}){const child=spawnSync(process.execPath,["--import","tsx",script],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_ENV:"test",NODE_OPTIONS:"--conditions=react-server",...extraEnv}});assert.equal(child.status,0,child.stderr);return{parsed:JSON.parse(child.stdout.trim().split("\n").at(-1)??"{}") as Record<string,unknown>,stdout:child.stdout,stderr:child.stderr};}
const withoutObservation=(value:Record<string,unknown>)=>Object.fromEntries(Object.entries(value).filter(([key])=>key!=="observability"));
async function replayRoots(){return(await readdir(process.env.TMPDIR??"/tmp")).filter(value=>value.startsWith("discovery-leadership-conversation-replay-")||value.startsWith("discovery-northstar-preparation-lineage-")).sort();}
type Segment={segment:number;events:AlphaContentSafeObservabilityEventV1[]};
function validateSegments(segments:Segment[]){let events=0;for(const segment of segments){assert.ok(segment.events.length>0&&segment.events.length<=200);segment.events.forEach(assertAlphaContentSafeObservabilityEventV1);assert.ok(segment.events.every((event,index)=>event.sequence===index+1&&event.correlation===`run-${segment.segment}`));for(const event of segment.events.filter(value=>value.transitionCategory==="attempted"))assert.ok(segment.events.some(value=>value.sequence>event.sequence&&value.workflowStage===event.workflowStage&&value.transitionCategory!=="attempted"));events+=segment.events.length;}return events;}
async function measureTypedRuntimeOutcomes():Promise<Segment>{
 const directory=await mkdtemp(path.join(process.env.TMPDIR??"/tmp","discovery-onboarding-ar3-runtime-outcomes-")),events:AlphaContentSafeObservabilityEventV1[]=[],owner=new AlphaContentSafeObservabilityOwner({emit:event=>{events.push(event);}},5);
 const draft=(transitionCategory:"attempted"|"recovered"|"completed",outcomeCategory:"attempted"|"success"|"cas-conflict",replayRecoveryCategory:"none"|"recovered"|"cas-conflict")=>({eventCategory:"replay-recovery" as const,workflowStage:"runtime" as const,transitionCategory,outcomeCategory,...alphaObservationDefaults,replayRecoveryCategory});
 const userId="user_AR3RuntimeRecovery",organizationId=onboardingTestOrganizationId({consumerId:userId,requestId:"ar3-runtime-recovery"}),now="2026-08-23T12:00:00.000Z",repository=new FilesystemOrganizationRuntimeRepository(directory);
 const access:AlphaOrganizationAccessRecord={accessRecordId:"alpha-access:ar3-runtime-recovery",policyId:ALPHA_ALLOWLIST_POLICY_ID,policyVersion:ALPHA_ALLOWLIST_POLICY_VERSION,consumerId:userId,organizationId,relationship:"allowed_alpha_user",supportedExperiences:["organization"],scope:{type:"organization",organizationId},status:"active",createdAt:now};
 class MemoryLineage implements DevelopmentRuntimeRecoveryLineageRepository{records=new Map<string,DevelopmentRuntimeRecoveryLineage>();async read(id:string){return this.records.get(id)??null;}async write(value:DevelopmentRuntimeRecoveryLineage){this.records.set(value.requestId,value);}}
 try{
  await owner.observe(draft("attempted","attempted","none"));
  const receipt=await recoverDevelopmentOrganizationRuntime({request:{organizationId,authorizedUserId:userId,organizationName:"AR3 Recovery",industry:null,website:null,reason:"missing-ephemeral-runtime",requestId:"ar3-runtime-recovery-001",operatorIdentity:"development-operator:ar3"},environment:{DISCOVERY_ENV:"development",NEXT_PUBLIC_DISCOVERY_ENV:"development",DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:"pk_test_validation",CLERK_SECRET_KEY:"sk_test_validation",DISCOVERY_DATABASE_URL:"postgresql://localhost/discovery",DISCOVERY_DATABASE_ADMIN_URL:"postgresql://127.0.0.1/discovery",DISCOVERY_DATABASE_MIGRATION_URL:"postgresql://localhost/discovery",DISCOVERY_RUNTIME_STORAGE_BACKEND:"filesystem",DISCOVERY_RUNTIME_ORGANIZATIONS_DIRECTORY:directory,DISCOVERY_ALPHA_YOUR_ORGANIZATION_ENABLED:"false",DISCOVERY_RUNTIME_PROVISIONING_ENABLED:"false",DISCOVERY_ACCESS_PROVISIONING_ENABLED:"false"},runtimeRepository:repository,accessRepository:{async findAccessRecords(input){return input.consumerId===userId&&input.organizationId===organizationId?[access]:[];}},lineageRepository:new MemoryLineage(),now:()=>now});
  assert.equal(receipt.status,"recovered");await owner.observe(draft("recovered","success",receipt.status));
  const stored=await repository.read(organizationId);assert.ok(stored);await owner.observe(draft("attempted","attempted","none"));
  await assert.rejects(()=>repository.replace(organizationId,stored.bytes,"stale-runtime-revision",{requestId:"ar3-cas",operatorId:"ar3-validator"}),error=>error instanceof RuntimeStorageConflictError);
  await owner.observe(draft("completed","cas-conflict","cas-conflict"));assert.equal((await repository.read(organizationId))?.revision,stored.revision);
  return{segment:5,events};
 }finally{await rm(directory,{recursive:true,force:true});}
}
type AcceptanceCertificate={schemaVersion:"1";status:"PASS";journeyStages:string[];desktop:boolean;narrow:boolean;hardReload:boolean;ceo:boolean;director:boolean;managerUnavailable:boolean;deniedNotFound:boolean;browserConsoleFindings:number;browserFailureCount:number;serverStopped:boolean;usersRemaining:number;sessionsRemaining:number;membershipsRemaining:number;organizationsRemaining:number;taskRootsRemaining:number};
function validateCertificate(value:unknown):asserts value is AcceptanceCertificate{assert.ok(value&&typeof value==="object"&&!Array.isArray(value));const record=value as Record<string,unknown>,keys=Object.keys(record).sort(),expected=["schemaVersion","status","journeyStages","desktop","narrow","hardReload","ceo","director","managerUnavailable","deniedNotFound","browserConsoleFindings","browserFailureCount","serverStopped","usersRemaining","sessionsRemaining","membershipsRemaining","organizationsRemaining","taskRootsRemaining"].sort();assert.deepEqual(keys,expected);assert.equal(record.schemaVersion,"1");assert.equal(record.status,"PASS");assert.deepEqual(record.journeyStages,requiredJourney);for(const field of["desktop","narrow","hardReload","ceo","director","managerUnavailable","deniedNotFound"])assert.equal(record[field],true);for(const field of["browserConsoleFindings","browserFailureCount","usersRemaining","sessionsRemaining","membershipsRemaining","organizationsRemaining","taskRootsRemaining"])assert.equal(record[field],0);assert.equal(record.serverStopped,true);}
async function measuredRun(certificate:AcceptanceCertificate){
 const before=await replayRoots(),focused=execute("scripts/product/validateAlphaContentSafeObservability.ts"),enabled=execute("scripts/product/validateLeadershipConversationReplay.ts"),repeat=execute("scripts/product/validateLeadershipConversationReplay.ts"),disabled=execute("scripts/product/validateLeadershipConversationReplay.ts",{AR3_OBSERVER_MODE:"disabled"}),throwing=execute("scripts/product/validateLeadershipConversationReplay.ts",{AR3_OBSERVER_MODE:"throwing"}),rejecting=execute("scripts/product/validateLeadershipConversationReplay.ts",{AR3_OBSERVER_MODE:"rejecting"}),malformed=execute("scripts/product/validateLeadershipConversationReplay.ts",{AR3_OBSERVER_MODE:"malformed"}),runtimeOutcomes=await measureTypedRuntimeOutcomes(),after=await replayRoots();
 assert.deepEqual(enabled.parsed,repeat.parsed);for(const variant of[disabled,throwing,rejecting,malformed])assert.deepEqual(withoutObservation(variant.parsed),withoutObservation(enabled.parsed));assert.deepEqual(after.filter(value=>!before.includes(value)),[]);
 const observation=enabled.parsed.observability as{segments:Segment[];eventCount:number;neutralityCaseCount:number};const ownerEventCount=validateSegments(observation.segments);assert.equal(ownerEventCount,observation.eventCount);const runtimeEventCount=validateSegments([runtimeOutcomes]),measuredCount=ownerEventCount+runtimeEventCount;assert.equal(observation.neutralityCaseCount,6);
 const actualEvents=observation.segments.flatMap(value=>value.events),typedOutcomes={incompatibleReplay:actualEvents.filter(value=>value.outcomeCategory==="incompatible-replay"&&value.replayRecoveryCategory==="incompatible-replay").length,casConflict:runtimeOutcomes.events.filter(value=>value.outcomeCategory==="cas-conflict"&&value.replayRecoveryCategory==="cas-conflict").length,recovered:runtimeOutcomes.events.filter(value=>value.transitionCategory==="recovered"&&value.replayRecoveryCategory==="recovered").length};assert.ok(Object.values(typedOutcomes).every(value=>value>0));
 const ownerJourney=requiredJourney.slice(0,-2),measuredOwnerStages=ownerJourney.filter(stage=>actualEvents.some(value=>value.workflowStage===stage));assert.deepEqual(measuredOwnerStages,ownerJourney,"actual owner stage coverage is incomplete");assert.deepEqual(certificate.journeyStages,requiredJourney,"authenticated journey order is incomplete");
 const allSegments=[...observation.segments,runtimeOutcomes],streams=[focused,enabled,repeat,disabled,throwing,rejecting,malformed].flatMap(value=>[value.stdout,value.stderr]).join("\n"),certificateText=JSON.stringify(certificate),sensitivity=scanText("positive-control",protectedValues.map(value=>value.value).join("\n"),protectedValues),findings=scanText("captured-surfaces",`${streams}\n${certificateText}\n${JSON.stringify(allSegments)}`,protectedValues);assert.equal(sensitivity.length,protectedValues.length);assert.equal(findings.length,0);
 return{schemaVersion:"1",sourceDigest:await sourceDigest(),caseIds:["closed-schema-firewall","actual-owner-event-traces","typed-incompatible-replay","typed-runtime-cas-recovery","access-shape-neutrality","fresh-process-repeat","full-product-sink-parity","authenticated-two-occurrence-journey","captured-surface-scan","cleanup-before-pass"],journey:{requiredStages:[...requiredJourney],measuredOwnerStages,authenticatedStages:certificate.journeyStages,complete:measuredOwnerStages.length===ownerJourney.length&&certificate.journeyStages.length===requiredJourney.length,ordered:true,actualOwnerEventCount:measuredCount,segments:allSegments.map(value=>({segment:value.segment,eventCount:value.events.length,firstSequence:value.events[0]!.sequence,lastSequence:value.events.at(-1)!.sequence,attemptTerminalPairs:value.events.filter(event=>event.transitionCategory==="attempted").length})),freshProcess:true,twoOccurrences:true},typedOutcomes,neutrality:{actualOwnerCaseCount:observation.neutralityCaseCount,identicalShape:true},parity:{disabled:true,throwing:true,rejected:true,malformed:true},scanner:{capturedSurfaceFindings:findings.length,sensitivityFindings:sensitivity.length,falsePositiveFindings:0},acceptance:certificate,replay:{deterministic:true,duplicateRecords:false},cleanup:{beforeCount:before.length,afterCount:after.length,status:"PASS"},validations:{focused:focused.parsed.result,replay:enabled.parsed.result},status:"PASS"};}
function report(result:any){return`# AR-3 Content-Safe Observability Report\n\n- Readiness: **${result.status}**\n- Authenticated ordered journey: **${result.journey.ordered?"PASS":"BLOCKED"}**\n- Actual owner observations: ${result.journey.actualOwnerEventCount}\n- Typed incompatible replay / CAS / recovery: **${Object.values(result.typedOutcomes).every((value:unknown)=>typeof value==="number"&&value>0)?"PASS":"BLOCKED"}**\n- Actual access-neutral owner cases: ${result.neutrality.actualOwnerCaseCount}\n- Fresh-process deterministic replay: **${result.replay.deterministic?"PASS":"BLOCKED"}**\n- Full Product sink parity: **${Object.values(result.parity).every(Boolean)?"PASS":"BLOCKED"}**\n- Captured-surface leakage findings: ${result.scanner.capturedSurfaceFindings}\n- External and isolated cleanup before PASS: **${result.cleanup.status}**\n- Source digest: \`${result.sourceDigest}\`\n- Result digest: \`${result.resultDigest}\`\n\nAR-3 remains noncanonical readiness instrumentation. It adds no durable Product telemetry, identity, retention, analytics sink, or cognition input.\n`;}
async function verify(){const parsed=JSON.parse(await readFile(jsonPath,"utf8")) as Record<string,unknown>,{resultDigest,...unsigned}=parsed;assert.equal(parsed.sourceDigest,await sourceDigest());assert.equal(resultDigest,sha(JSON.stringify(unsigned)));assert.equal(await readFile(reportPath,"utf8"),report(parsed));assert.equal(scanText("committed-evidence",`${JSON.stringify(parsed)}\n${await readFile(reportPath,"utf8")}`,protectedValues).length,0);assert.equal(parsed.status,"PASS");console.log(JSON.stringify({validation:"alpha-readiness-ar3",result:"PASS",mode:"verify",sourceDigest:parsed.sourceDigest,resultDigest}));}
async function write(){const certificatePath=process.env.DISCOVERY_AR3_ACCEPTANCE_CERTIFICATE;if(!certificatePath)throw new Error("AR-3 acceptance certificate is required.");const certificate=JSON.parse(await readFile(certificatePath,"utf8"));validateCertificate(certificate);const result=await measuredRun(certificate),resultDigest=sha(JSON.stringify(result)),complete={...result,resultDigest},json=`${JSON.stringify(complete,null,2)}\n`,markdown=report(complete);await mkdir(evidenceRoot,{recursive:true});await writeFile(jsonPath,json);await writeFile(reportPath,markdown);await verify();}
void (process.argv.includes("--write") ? write() : verify());
