import {auth} from "@clerk/nextjs/server";
import {notFound,redirect} from "next/navigation";
import DiscoveryShell from "../../../../components/product-shell/DiscoveryShell";
import {MeetingPortfolioNavigation,MeetingPortfolioShell} from "../../../../components/product-alpha/meetings/MeetingPortfolioShell";
import {LeadershipConversationExperience} from "../../../../components/product-alpha/leadership-conversation/LeadershipConversationExperience";
import {authorizedMeetingDirectory,resolveAuthorizedMeetingAddress} from "../../../../product/integration/authorizedMeetingDirectory";
import {createLeadershipConversationServerComposition,resolveCurrentLeadershipConversationCheckpoint} from "../../../../product/integration/leadershipConversationServerComposition";
import {getPersonalRoomSheetPreviewAction} from "../../leadership-conversation/actions";
import {composeChiefFirstPrepareViewFromWorkspace} from "../../../../product/integration/chiefLeadershipPreparationComposer";
import {compileChiefOfStaffValueLayerV1} from "../../../../product/workflow/leadershipConversation/chiefCommunicationPlan";
import {SANDBOX_ORGANIZATION_ID} from "../../../../lib/access/sandboxMultiUserAccess";
import {projectCrossMeetingRelevanceV1,projectMeetingExecutiveContinuity} from "../../../../product/integration/meetingExecutiveContentProjection";
import {createParticipantReferenceMeetingCurrentAccessFromEnvironment} from "../../../../lib/alpha-activation/participantReferenceMeetingAccessServer";
import {classifyLegacyMeetingOrganizationClaim,resolveFounderFirstUnderstandingMeetingHome} from "../../../../lib/alpha-activation/founderFirstUnderstandingMeetingHome";
export const dynamic="force-dynamic";
export default async function MeetingHome({params,searchParams}:{params:Promise<{seriesAddress:string}>;searchParams:Promise<{organizationId?:string|string[]}>}){
 const {userId}=await auth();if(!userId)notFound();
 const {seriesAddress}=await params;
 const suppliedOrganization=(await searchParams).organizationId;
 const founder=await resolveFounderFirstUnderstandingMeetingHome(seriesAddress,suppliedOrganization);
 if(founder?.status==="organization-conflict")notFound();
 if(founder?.status==="found"){if(suppliedOrganization!==undefined)redirect(`/product-alpha/meetings/${seriesAddress}`);const destination=`/product-alpha/meetings/${seriesAddress}`;return <DiscoveryShell organization={{organizationId:"",organizationName:founder.organizationName,runtimeAvailable:true,coherence:null,confidence:null,coherenceLabel:"Understanding beginning"}} showSessionImpact={false} opaqueMeetingHref={destination}><main style={{maxWidth:800,margin:"32px auto",padding:24,color:"#17221d"}}><h1>{founder.title}</h1><p>{founder.cadence}</p><h2>{founder.question}</h2><p>{founder.sourceCount} governed sources are connected to this question.</p><h2>Initial Prepared Work</h2><p>{founder.prepared.situationSummary}</p><ul>{founder.prepared.uncertaintyAndLimitations.map(value=><li key={value}>{value}</li>)}</ul><p>No prior reviewed state or meeting history exists.</p></main></DiscoveryShell>;}
 const meetingAccess=createParticipantReferenceMeetingCurrentAccessFromEnvironment(),meeting=await resolveAuthorizedMeetingAddress({userId,organizationId:SANDBOX_ORGANIZATION_ID,seriesAddress,currentAccess:meetingAccess});if(!meeting)notFound();
 const legacyClaim=classifyLegacyMeetingOrganizationClaim(suppliedOrganization,meeting.organizationId);if(legacyClaim==="conflict")notFound();if(legacyClaim==="matching")redirect(`/product-alpha/meetings/${seriesAddress}`);
 const server=createLeadershipConversationServerComposition(),workspace=await server.workspace({userId,organizationId:meeting.organizationId,questionId:meeting.questionId,conversationId:meeting.occurrenceId});
 let prepare=composeChiefFirstPrepareViewFromWorkspace(workspace);if(meeting.predecessorOccurrenceId){const priorWorkspace=await server.workspace({userId,organizationId:meeting.organizationId,questionId:meeting.questionId,conversationId:meeting.predecessorOccurrenceId}),closure=priorWorkspace.closureCompletion;if(!closure)notFound();const continuity=projectMeetingExecutiveContinuity(priorWorkspace);prepare={...prepare,seriesId:meeting.seriesId,priorCycle:{status:"completed",message:continuity.items.length?continuity.items.map(item=>`${item.label}: ${item.text}`).join("\n"):"No consequential reviewed continuity was recorded.",...continuity}};}
 let pack=null,unavailable=false;try{pack=await server.readMeetingPack({userId,organizationId:meeting.organizationId,questionId:meeting.questionId,conversationId:meeting.occurrenceId,seriesId:meeting.seriesId})}catch{unavailable=true}
 const analysisResponse=await server.analyzeSourceScopedForDevelopment({userId,organizationId:meeting.organizationId,questionId:meeting.questionId,seriesId:meeting.seriesId,occurrenceId:meeting.occurrenceId}),analysis=analysisResponse.result.status==="eligible"?analysisResponse.result.candidate:undefined,alignment=analysis?await server.readMeetingPerspectives({userId,organizationId:meeting.organizationId,questionId:meeting.questionId,conversationId:meeting.occurrenceId,seriesId:meeting.seriesId,workingAnalysisDigest:analysis.candidateDigest}):[];
 const personal=await getPersonalRoomSheetPreviewAction(seriesAddress),checkpoint=workspace.currentStep==="capture"||workspace.currentStep==="review"?await resolveCurrentLeadershipConversationCheckpoint({userId,organizationId:meeting.organizationId,questionId:meeting.questionId,conversationId:meeting.occurrenceId,seriesId:meeting.seriesId}):null,directory=await authorizedMeetingDirectory({userId,organizationId:meeting.organizationId,currentAccess:meetingAccess}),origins=await Promise.all(directory.filter(item=>item.occurrenceId!==meeting.occurrenceId).map(async item=>{const originWorkspace=await server.workspace({userId,organizationId:meeting.organizationId,questionId:item.questionId,conversationId:item.occurrenceId}),citations=originWorkspace.proposals.flatMap(value=>value.reviewedCarryForward?.citations??[]),citationAccess=citations.length>0&&await server.verifyReviewedCarryForwardCitations({userId,organizationId:meeting.organizationId,citations});return{meeting:item,workspace:originWorkspace,citationAccess};})),relevantElsewhere=projectCrossMeetingRelevanceV1(workspace,origins);
 return <DiscoveryShell organization={{organizationId:meeting.organizationId,organizationName:"Northstar Implementation Services",runtimeAvailable:true,coherence:null,confidence:null,coherenceLabel:"Understanding available"}} showSessionImpact={false} productNavigation={<MeetingPortfolioNavigation meetings={directory}/>}><MeetingPortfolioShell meetings={directory}><LeadershipConversationExperience initialWorkspace={workspace} prepare={prepare} valueLayer={compileChiefOfStaffValueLayerV1(prepare,analysis)} personalSheet={personal.sheet} occurrenceRef={personal.occurrenceRef} initialCheckpoint={checkpoint?{checkpointId:checkpoint.checkpointId,contributionArtifactIds:checkpoint.contributionArtifactIds}:null} initialMeetingPack={pack} meetingPackUnavailable={unavailable} relevantElsewhere={relevantElsewhere} alignment={alignment} workingAnalysisDigest={analysis?.candidateDigest??null} seriesAddress={seriesAddress} occurrenceLabel={meeting.predecessorOccurrenceId?"Successor occurrence":"Current occurrence"}/></MeetingPortfolioShell></DiscoveryShell>
}
