import { registerHooks } from "node:module";
const asModule = source => `data:text/javascript,${encodeURIComponent(source)}`;
const serverOnly=asModule("export default undefined");
const postgres=asModule('export default function postgres(){globalThis.__reconciliationComposition.push("postgres");return {end:async()=>globalThis.__reconciliationComposition.push("close")}}');
const db=asModule('export function requireDiscoveryDatabaseUrl(){globalThis.__reconciliationComposition.push("database-url");return "redacted"}');
const repositories=asModule('export class PostgresAlphaAccessRecordRepository{constructor(){globalThis.__reconciliationComposition.push("alpha-access")}} export class PostgresParticipantReferenceAccessRepository{constructor(){globalThis.__reconciliationComposition.push("participant-access")}}');
const stable=asModule('export function resolveClerkStableInstanceIdentity(){globalThis.__reconciliationComposition.push("instance");return "instance"}');
const verified=asModule('export async function resolveVerifiedConsumerIdentityFromClerk(){globalThis.__reconciliationComposition.push("clerk-request");return globalThis.__reconciliationIdentity}');
const authority=asModule('export async function verifyFounderFirstUnderstandingRequest(identity){globalThis.__reconciliationComposition.push("verify-v2");if(identity!==globalThis.__reconciliationIdentity)throw new Error("wrong identity");return {participantRef:"participant-existing",consumerId:"consumer-existing"}}');
const access=asModule('export class ParticipantReferenceAccessAdministration{constructor(){globalThis.__reconciliationComposition.push("access-administration")}}');
const bundle=asModule('export async function createFounderFirstUnderstandingOwnerBundleFromEnvironment(request){globalThis.__reconciliationComposition.push(`owner:${request.participantRef}:${request.consumerId}`);return {reconcileAddContext:async(address,apply)=>{globalThis.__reconciliationAddresses.push(`${address}:${apply}`);return {status:apply?"applied":"dry-run",sourceWrites:0,scopeWrites:1,preparedWorkWrites:1,sourceCount:5}},close:async()=>globalThis.__reconciliationComposition.push("owner-close")}} export class FounderFirstUnderstandingOwnerBundle{}');
const first=asModule('export class FounderFirstUnderstandingApplicationService{}');
const add=asModule('export class FounderAddGovernedContextApplicationService{}');
registerHooks({resolve(specifier,context,nextResolve){
 if(specifier==="server-only")return{url:serverOnly,shortCircuit:true}; if(specifier==="postgres")return{url:postgres,shortCircuit:true}; if(specifier.endsWith("/db/config"))return{url:db,shortCircuit:true}; if(specifier.endsWith("/db/governance/postgresRepositories"))return{url:repositories,shortCircuit:true}; if(specifier.endsWith("/auth/clerkStableInstanceIdentity"))return{url:stable,shortCircuit:true}; if(specifier.endsWith("/auth/resolveVerifiedConsumerIdentityFromClerk"))return{url:verified,shortCircuit:true}; if(specifier.endsWith("/founderFirstUnderstandingRequestAuthority"))return{url:authority,shortCircuit:true}; if(specifier.endsWith("/participantReferenceAccess"))return{url:access,shortCircuit:true}; if(specifier.endsWith("/founderFirstUnderstandingOwnerBundle"))return{url:bundle,shortCircuit:true}; if(specifier.endsWith("/founderFirstUnderstandingApplicationService"))return{url:first,shortCircuit:true}; if(specifier.endsWith("/founderAddGovernedContextApplicationService"))return{url:add,shortCircuit:true}; return nextResolve(specifier,context)},load(url,context,nextLoad){if(url.startsWith("data:text/javascript,"))return{format:"module",source:decodeURIComponent(url.slice(url.indexOf(",")+1)),shortCircuit:true};return nextLoad(url,context)}});
