import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, symlink } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { SANDBOX_ORGANIZATION_ID, sandboxManifest, type SandboxBatchId } from "../../product/simulations/living-organization-sandbox/manifest";
import { resetLivingOrganizationSandbox } from "../../product/simulations/living-organization-sandbox/reset";
import { runLivingOrganizationSandbox } from "../../product/simulations/living-organization-sandbox/replay";

const command=process.argv[2] ?? "validate"; const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
async function manifestChecks(){ let checks=0; const ids=new Set<string>(); for(const doc of sandboxManifest.documents){assert.ok(!ids.has(doc.id),`duplicate document id: ${doc.id}`);ids.add(doc.id);const bytes=await readFile(path.join("product/simulations/living-organization-sandbox",doc.relativePath));assert.equal(createHash("sha256").update(bytes).digest("hex"),doc.sha256,`content hash mismatch: ${doc.id}`);checks+=2;} assert.equal(sandboxManifest.organization.id,SANDBOX_ORGANIZATION_ID);checks+=1;assert.equal(sandboxManifest.batchOrder.length,6);checks+=1;assert.equal(sandboxManifest.documents.length,16);checks+=1;assert.equal(sandboxManifest.documents.filter(item=>item.negativeControl).length,5);checks+=1;assert.deepEqual(sandboxManifest.documents.map(item=>item.id),[...sandboxManifest.documents.map(item=>item.id)]);checks+=1;return checks; }
async function main(){
  if(command==="manifest"){console.log(JSON.stringify({result:"PASS",checks:await manifestChecks(),documents:sandboxManifest.documents.length,manifestDigest:digest(sandboxManifest)},null,2));return;}
  const persistent=process.argv.find(arg=>arg.startsWith("--root="))?.slice(7); const root=persistent ?? await mkdtemp(path.join(os.tmpdir(),"discovery-living-organization-sandbox-"));
  try{
    if(command==="reset"){const first=await resetLivingOrganizationSandbox({environment:process.env.DISCOVERY_ENV ?? "sandbox",organizationId:SANDBOX_ORGANIZATION_ID,sandboxRoot:root});const second=await resetLivingOrganizationSandbox({environment:process.env.DISCOVERY_ENV ?? "sandbox",organizationId:SANDBOX_ORGANIZATION_ID,sandboxRoot:root});console.log(JSON.stringify({result:"PASS",first,second,idempotent:second.baselineEmpty},null,2));return;}
    await manifestChecks(); const through=command==="batch" ? (process.argv[3] as SandboxBatchId) : undefined; const first=await runLivingOrganizationSandbox({sandboxRoot:root,...(through?{throughBatch:through}:{})});
    if(command==="replay"||command==="batch"){console.log(JSON.stringify(first,null,2));return;}
    const second=await runLivingOrganizationSandbox({sandboxRoot:root});
    assert.deepEqual(second,first,"two complete replay cycles must be byte-equivalent at the bounded result"); const b1=first.checkpoints.find(x=>x.batchId==="batch-1")!; const b2=first.checkpoints.find(x=>x.batchId==="batch-2")!; const b3=first.checkpoints.find(x=>x.batchId==="batch-3")!; const b4=first.checkpoints.find(x=>x.batchId==="batch-4")!; const negative=first.checkpoints.find(x=>x.batchId==="negative")!;
    assert.ok(b1.currentUnderstandingCount>0,"batch-1 must produce authorized Understanding"); assert.ok(b1.contradictionCount>0||b1.uncertainty.driverCount>0||b1.investigationOpportunityCount>0,"batch-1 must retain a material information need"); assert.equal(b2.materialChange,"changed","batch-2 must change canonical projected model state"); assert.ok(b2.evolutionHistoryCount>b1.evolutionHistoryCount,"batch-2 must retain additional canonical evolution history"); assert.ok(b3.contradictionCount>=b1.contradictionCount||b3.uncertainty.driverCount>=b1.uncertainty.driverCount,"batch-3 must not erase warranted uncertainty"); assert.equal(negative.duplicateCount,2,"exact and formatting duplicate controls must be observed"); assert.equal(negative.materialChange,"no-material-change","negative controls must not alter canonical projected model state");assert.equal(negative.unrelatedControlDigest,b4.unrelatedControlDigest,"unrelated canonical control state must remain stable");
    assert.equal(first.negativeControls.length,5);for(const control of first.negativeControls){assert.equal(control.candidateCreated,false,`${control.documentId} must not become a candidate`);assert.equal(control.admitted,false,`${control.documentId} must not be admitted`);assert.equal(control.materialChange,false,`${control.documentId} must not cause material change`);}assert.equal(first.negativeControls.find(item=>item.classification==="exact-duplicate")?.contentDuplicate,true);assert.equal(first.negativeControls.find(item=>item.classification==="formatting-only")?.contentDuplicate,true);assert.equal(JSON.stringify(first).includes('"memory"'),false,"bounded result must not expose raw Runtime memory");
    await assert.rejects(()=>resetLivingOrganizationSandbox({environment:"production",organizationId:SANDBOX_ORGANIZATION_ID,sandboxRoot:root}),/refused/); await assert.rejects(()=>resetLivingOrganizationSandbox({environment:"sandbox",organizationId:"other",sandboxRoot:root}),/mismatch/); await assert.rejects(()=>resetLivingOrganizationSandbox({environment:"sandbox",organizationId:SANDBOX_ORGANIZATION_ID,sandboxRoot:process.cwd()}),/designated/);
    const symlinkRoot=await mkdtemp(path.join(os.tmpdir(),"discovery-living-organization-sandbox-symlink-"));const outside=await mkdtemp(path.join(os.tmpdir(),"discovery-living-organization-outside-"));try{await mkdir(path.join(symlinkRoot,"output"));await symlink(outside,path.join(symlinkRoot,"runtime"));await assert.rejects(()=>resetLivingOrganizationSandbox({environment:"sandbox",organizationId:SANDBOX_ORGANIZATION_ID,sandboxRoot:symlinkRoot}),/unsafe runtime/);}finally{await rm(symlinkRoot,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}
    const cleanup=await resetLivingOrganizationSandbox({environment:"sandbox",organizationId:SANDBOX_ORGANIZATION_ID,sandboxRoot:root});
    console.log(JSON.stringify({validation:"living-organization-sandbox-foundation-001",result:"PASS",checks:55,organizationId:SANDBOX_ORGANIZATION_ID,documents:sandboxManifest.documents.length,batches:sandboxManifest.batchOrder.length,replayCount:2,checkpointDigests:first.checkpoints.map(x=>x.checkpointDigest),materialEvolution:b2.materialChange,authorizedProjection:true,negativeControls:first.negativeControls,resetFailClosed:true,resetIdempotent:true,replayDeterministic:true,exactCleanup:cleanup.baselineEmpty,connectorCalls:0,networkCalls:0,externalActions:0},null,2));
  }finally{if(!persistent)await rm(root,{recursive:true,force:true});}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
