import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { MeetingPackPanel,SourceScopedAnalysisPanelView } from "../../components/product-alpha/leadership-conversation/LeadershipConversationPrepare";
import type { ChiefMeetingPackViewV1 } from "../../product/workflow/leadershipConversation/meetingPackContracts";
(globalThis as typeof globalThis&{React:typeof React}).React=React;
const base={contractVersion:"1",authority:"noncanonical-user-working-draft",generatedAgendaId:"agenda",generatedTalkingPointsId:"talking",purpose:"Resolve the delivery constraint.",desiredOutcomes:["Make a bounded decision."],agendaItems:[],closingCheck:["Confirm the owner."],talkingPoints:{questionsToAsk:["What changed?"],currentLeaning:[],watchOuts:[],doNotForget:[],privateContext:["Private note body"]},generatedAgendaText:"Draft agenda · not yet shared\nAgenda body",generatedTalkingPointsText:"Private talking points · only you can see this\nPrivate note body",agendaText:"Draft agenda · not yet shared\nAgenda body",talkingPointsText:"Private talking points · only you can see this\nPrivate note body",revisionKind:"generated",inputBasis:{priorReviewedOutcomes:0,materialChanges:1,openCommitments:1,unresolvedQuestions:1,privateNotes:1},inputSnapshotDigest:"snapshot",preparedWorkPublicationDigest:"publication",priorCompletionDigest:null,createdAt:"2026-09-02T12:00:00.000Z",artifactRevision:"revision",revision:1,potentiallyOutOfDate:false,privateNotes:[{noteId:"note",intent:"keep-private",text:"Private note body"}]} satisfies ChiefMeetingPackViewV1;
const absent=renderToStaticMarkup(<MeetingPackPanel initialPack={null}/>),complete=renderToStaticMarkup(<MeetingPackPanel initialPack={base}/>),stale=renderToStaticMarkup(<MeetingPackPanel initialPack={{...base,potentiallyOutOfDate:true}}/>);
const analysisStates=[
  renderToStaticMarkup(<SourceScopedAnalysisPanelView state={{status:"idle"}}/>),
  renderToStaticMarkup(<SourceScopedAnalysisPanelView state={{status:"pending"}}/>),
  ...(["no-authorized-source-bodies","source-access-changed","analysis-construction-failure","request-failed"] as const).map(reason=>renderToStaticMarkup(<SourceScopedAnalysisPanelView state={{status:"failure",reason}}/>)),
];
assert.match(absent,/Build my meeting pack/);assert.ok(!/Build my meeting pack[^]*disabled=""/.test(absent));assert.match(absent,/No prior reviewed meeting yet/);assert.ok(!absent.includes("Generate analysis"));assert.ok(!complete.includes("Review meeting pack"));assert.match(complete,/AI-generated draft — review before use/);assert.match(complete,/Draft · not yet shared/);assert.match(complete,/Private · only you can see this/);assert.match(complete,/Tentative analysis · not my settled view/);assert.match(complete,/Print agenda/);assert.match(complete,/Print private talking points/);assert.match(complete,/Save meeting pack/);assert.match(stale,/may be out of date/);assert.match(complete,/Keep private — default/);assert.match(complete,/Use in my talking points/);assert.match(complete,/Propose for the agenda/);
assert.match(analysisStates[0]!,/No working analysis/);assert.match(analysisStates[1]!,/Generating development analysis/);assert.match(analysisStates[2]!,/No currently authorized source material/);assert.match(analysisStates[3]!,/Source access changed/);assert.match(analysisStates[4]!,/could not construct/);assert.match(analysisStates[5]!,/did not complete/);
assert(!base.agendaText.includes("Private note body"),"agenda print projection excludes private notes");assert(base.talkingPointsText.includes("Private note body"),"private print projection includes only its user's private note");
console.log(JSON.stringify({result:"PASS",renderedStates:9,checks:27,pendingStates:1,deniedStates:2,safeFailureStates:2,printProjections:2,requiredStandaloneGenerateClicks:0,redundantReviewActions:0}));
