import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {compileChiefOfStaffValueLayerV1} from "../../product/workflow/leadershipConversation/chiefCommunicationPlan";
import {PERSONAL_ROOM_SHEET_BOUNDARY_LABEL} from "../../product/workflow/leadershipConversation/personalRoomSheetContracts";
import type {ChiefFirstPrepareViewV1,LeadershipConversationWorkspaceV1} from "../../product/workflow/leadershipConversation";
async function main(){const input=JSON.parse(readFileSync(process.argv[2]!,"utf8")) as {states:Array<{name:string;workspace:LeadershipConversationWorkspaceV1;prepare:ChiefFirstPrepareViewV1;nextPrepare?:ChiefFirstPrepareViewV1|null;continuationError?:string|null}>};
(globalThis as typeof globalThis&{React:typeof React}).React=React;(React as typeof React&{useActionState?:unknown}).useActionState=((_action:unknown,initial:unknown)=>[initial,()=>{}]) as never;const{LeadershipConversationExperience}=await import("../../components/product-alpha/leadership-conversation/LeadershipConversationExperience");
const sheet={contractVersion:"1" as const,authority:"non-authoritative-personal-product-material" as const,boundaryLabel:PERSONAL_ROOM_SHEET_BOUNDARY_LABEL,sourceProjectionDigest:"render-source",candidate1AssessmentDigest:"render-assessment",b11CommunicationDigest:"render-communication",personalRoomSheetDigest:"render-sheet",sections:[]};
const html=new Map(input.states.map(({name,workspace,prepare,nextPrepare,continuationError})=>[name,renderToStaticMarkup(<LeadershipConversationExperience initialWorkspace={workspace} prepare={prepare} valueLayer={compileChiefOfStaffValueLayerV1(prepare)} personalSheet={sheet} occurrenceRef="occurrence-1" initialCheckpoint={{checkpointId:"render-checkpoint",contributionArtifactIds:[]}} initialNextPrepare={nextPrepare} initialContinuationError={continuationError} telemetryNotice={false}/>) ]));
for(const name of ["unreviewed","route-pending","route-failed","terminal","completion-failed"]){const value=html.get(name)!;assert.ok(!value.includes("Reviewed carry-forward is complete")&&!value.includes("Review complete"),`${name} must not render completion`);}
assert.match(html.get("unreviewed")!,/[1-9][0-9]*<\/strong> of 5 proposals unresolved/);for(const label of ["Accept","Correct this proposal","Reject","Needs information"])assert.ok(html.get("unreviewed")!.includes(label),label);assert.match(html.get("unreviewed")!,/Confirm what Discovery should carry forward/);for(const name of ["route-pending","route-failed"]){assert.match(html.get(name)!,/owner route pending/);assert.match(html.get(name)!,/Resume owner route/);assert.ok(!html.get(name)!.includes("Canonical owner route completed"));}for(const name of ["terminal","completion-failed"]){assert.match(html.get(name)!,/Ready to finalize reviewed carry-forward/);assert.match(html.get(name)!,/Finalize review summary/);}assert.match(html.get("completed")!,/Reviewed carry-forward is complete/);assert.match(html.get("completed")!,/Review complete/);assert.ok(!html.get("completed")!.includes("Finalize review summary"));assert.match(html.get("nonpromotion")!,/owner could not truthfully promote/);assert.match(html.get("nonauthoritative")!,/Recorded nonauthoritatively/);assert.match(html.get("canonical")!,/Canonical owner route completed/);for(const value of html.values()){assert.match(value,/Deterministic development analysis — not a live provider result/);assert.match(value,/Source .* · version .* · material /);assert.ok(!value.includes("Accept all"));}
const completed=html.get("completed")!,all=[...html.values()],expectedCitationLabels=[...new Set(input.states[0]!.workspace.proposals.flatMap(value=>value.reviewedCarryForward?.citations.map(citation=>`Source ${citation.sourceId} · version ${citation.sourceVersion} · material ${citation.bodyDigest}`)??[]))],checks={deterministic:all.every(value=>value.includes("Deterministic development analysis — not a live provider result")),distinctCitations:expectedCitationLabels.length>1&&all.every(value=>expectedCitationLabels.every(label=>value.includes(label))),noAuthorityFields:all.every(value=>!value.includes("authorityRefs")&&!value.includes("policyRefs")&&!value.includes("authorizationContextRef")),pendingNotRouted:!html.get("route-pending")!.includes("Canonical owner route completed"),failedNotRouted:!html.get("route-failed")!.includes("Canonical owner route completed"),nonauthoritative:html.get("nonauthoritative")!.includes("Recorded nonauthoritatively"),nonpromotion:html.get("nonpromotion")!.includes("owner could not truthfully promote"),terminalFinalize:html.get("terminal")!.includes("Finalize review summary"),failureFinalize:html.get("completion-failed")!.includes("Finalize review summary"),completedHeader:completed.includes("Reviewed carry-forward is complete"),completedSummary:completed.includes("Review complete"),completedNoFinalize:!completed.includes("Finalize review summary"),noBulkAcceptance:all.every(value=>!value.includes("Accept all")),...(html.has("gate-2-ready")?{gate2Incomplete:!html.get("gate-2-incomplete")!.includes("Close and continue"),gate2Ready:html.get("gate-2-ready")!.includes("Close and continue")&&!html.get("gate-2-ready")!.includes("This meeting is closed"),gate2ClosedPending:html.get("gate-2-closed-pending")!.includes("reviewed summary has not been saved yet")&&!html.get("gate-2-closed-pending")!.includes("What changed · Prepare Again"),gate2WhatChanged:html.get("gate-2-what-changed")!.includes("What changed · Prepare Again")&&html.get("gate-2-what-changed")!.includes("Continue preparing next occurrence"),gate2SuccessorPending:html.get("gate-2-successor-pending")!.includes("Preparation for the next occurrence is not finished")&&html.get("gate-2-successor-pending")!.includes("Continue preparing next occurrence"),gate2Complete:html.get("gate-2-complete")!.includes("Occurrence 2 is prepared. The next meeting has not started")&&!html.get("gate-2-complete")!.includes("Cycle complete"),gate2Resumable:html.get("gate-2-resumable")!.includes("Your saved progress is intact")&&html.get("gate-2-resumable")!.includes("Resume close and continue")}:{})};for(const [name,value] of Object.entries(checks))assert.equal(value,true,name);process.stdout.write(JSON.stringify({result:"PASS",renders:html.size,expectedCitationLabels,checks}));}void main();
