import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {compileChiefOfStaffValueLayerV1} from "../../product/workflow/leadershipConversation/chiefCommunicationPlan";
import {PERSONAL_ROOM_SHEET_BOUNDARY_LABEL} from "../../product/workflow/leadershipConversation/personalRoomSheetContracts";
import type {ChiefFirstPrepareViewV1,LeadershipConversationWorkspaceV1} from "../../product/workflow/leadershipConversation";
async function main(){const input=JSON.parse(readFileSync(process.argv[2]!,"utf8")) as {states:Array<{name:string;workspace:LeadershipConversationWorkspaceV1;prepare:ChiefFirstPrepareViewV1;nextPrepare?:ChiefFirstPrepareViewV1|null;continuationError?:string|null}>};
(globalThis as typeof globalThis&{React:typeof React}).React=React;(React as typeof React&{useActionState?:unknown}).useActionState=((_action:unknown,initial:unknown)=>[initial,()=>{}]) as never;const{LeadershipConversationExperience}=await import("../../components/product-alpha/leadership-conversation/LeadershipConversationExperience");
const sheet={contractVersion:"1" as const,authority:"non-authoritative-personal-product-material" as const,boundaryLabel:PERSONAL_ROOM_SHEET_BOUNDARY_LABEL,sourceProjectionDigest:"render-source",candidate1AssessmentDigest:"render-assessment",b11CommunicationDigest:"render-communication",personalRoomSheetDigest:"render-sheet",sections:[]};
if(process.env.CRITICAL_DURABLE_RENDER){
  const state=input.states[0]!,workspace=state.workspace,proposals=workspace.proposals.filter(value=>value.reviewedCarryForward),choices=workspace.dispositions.filter(value=>proposals.some(proposal=>proposal.proposalId===value.proposalId)),pending=choices.filter(choice=>choice.disposition.startsWith("approved")&&!workspace.canonicalRoutingReceipts.some(route=>route.proposalId===choice.proposalId&&route.dispositionReceiptId===choice.dispositionReceiptId)&&!workspace.reviewedCarryForwardNonpromotions.some(receipt=>receipt.proposalId===choice.proposalId&&receipt.dispositionReceiptId===choice.dispositionReceiptId));
  const rendered=renderToStaticMarkup(<LeadershipConversationExperience initialWorkspace={workspace} prepare={state.prepare} valueLayer={compileChiefOfStaffValueLayerV1(state.prepare)} personalSheet={sheet} occurrenceRef="occurrence-1" initialCheckpoint={{checkpointId:"render-checkpoint",contributionArtifactIds:[]}}/>);
  if(workspace.reviewedCarryForwardCompletion){assert.match(rendered,/Review complete/);assert.ok(!rendered.includes("Finalize review summary"));}
  else if(choices.length<proposals.length){assert.ok(rendered.includes(`${choices.length} of ${proposals.length} review choices saved.`));assert.match(rendered,/Review each remaining proposal/);}
  else if(pending.length){assert.ok(rendered.includes(`All ${proposals.length} review choices saved.`));assert.match(rendered,/Next: Resume recording through governed owners/);}
  else{assert.match(rendered,/Recording complete/);assert.match(rendered,/Next: Finalize review summary/);}
  for(const choice of choices){if(choice.disposition==="rejected")assert.ok(rendered.includes("This item will not carry forward."));if(choice.disposition==="deferred")assert.ok(rendered.includes("No owner action was taken."));if(choice.effectivePayload){assert.ok(rendered.includes(choice.effectivePayload.summary));assert.ok(rendered.includes("Your correction — effective wording"));assert.ok(rendered.includes("Your wording will carry forward instead of the original proposal."));}}
  const secrets=proposals.flatMap(proposal=>[proposal.proposalId,proposal.payloadDigest,proposal.reviewedCarryForward!.candidateDigest,...proposal.reviewedCarryForward!.citations.flatMap(citation=>[citation.sourceId,citation.sourceVersion,citation.bodyDigest])]);for(const secret of secrets)assert.ok(!rendered.includes(secret),"Protected fixture value in critical render");for(const field of ["governedScopeBinding","admissionBasis","authorityRefs","policyRefs","candidateBodyDigest","completionId","dispositionReceiptId","integrationReceiptId"])assert.ok(!rendered.includes(field));
  process.stdout.write(JSON.stringify({result:"PASS",proposals:proposals.length,choices:choices.length,corrections:choices.filter(value=>value.effectivePayload).length,pending:pending.length,completed:Boolean(workspace.reviewedCarryForwardCompletion),protectedDisclosures:0}));return;
}
if(process.env.FINALIZATION_RECONSTRUCT_RENDER){const state=input.states[0]!,completion=state.workspace.reviewedCarryForwardCompletion;assert.ok(completion);const rendered=renderToStaticMarkup(<LeadershipConversationExperience initialWorkspace={state.workspace} prepare={state.prepare} valueLayer={compileChiefOfStaffValueLayerV1(state.prepare)} personalSheet={sheet} occurrenceRef="occurrence-1" initialCheckpoint={{checkpointId:"render-checkpoint",contributionArtifactIds:[]}} telemetryNotice={false}/>),summary=`${completion.counts.accepted} accepted · ${completion.counts.corrected} corrected · ${completion.counts.rejected} rejected · ${completion.counts.needsInformation} need information · ${completion.counts.unresolved} unresolved · ${completion.counts.routePending} pending routes`;assert.match(rendered,/Reviewed carry-forward is complete/);assert.match(rendered,/Review complete/);assert.ok(rendered.includes(summary));assert.ok(!rendered.includes("Finalize review summary")&&!rendered.includes("completionId")&&!rendered.includes("contentDigest"));process.stdout.write(JSON.stringify({result:"PASS",completedBanner:true,firstTimeFinalization:false,summary,unresolved:completion.counts.unresolved,routePending:completion.counts.routePending}));return;}
const html=new Map(input.states.map(({name,workspace,prepare,nextPrepare,continuationError})=>[name,renderToStaticMarkup(<LeadershipConversationExperience initialWorkspace={workspace} prepare={prepare} valueLayer={compileChiefOfStaffValueLayerV1(prepare)} personalSheet={sheet} occurrenceRef="occurrence-1" initialCheckpoint={{checkpointId:"render-checkpoint",contributionArtifactIds:[]}} initialNextPrepare={nextPrepare} initialContinuationError={continuationError} telemetryNotice={false}/>) ]));
const unopenedWorkspace={...input.states[0]!.workspace,proposals:[],dispositions:[],canonicalRoutingReceipts:[],reviewedCarryForwardNonpromotions:[],reviewedCarryForwardCompletion:null,currentStep:"freeze" as const};
const unopened=renderToStaticMarkup(<LeadershipConversationExperience initialWorkspace={unopenedWorkspace} prepare={input.states[0]!.prepare} valueLayer={undefined} personalSheet={undefined} occurrenceRef="occurrence-1" initialCheckpoint={null} initialMeetingPack={null} reviewedCarryForwardAvailable seriesAddress="opaque-meeting-address" readOnlyMeetingHome/>);
assert.match(unopened,/Start Reviewed Carry-Forward/);assert.match(unopened,/nothing becomes organizational state without your decision/);assert.ok(!unopened.includes("Accept all"));
for(const name of ["unreviewed","route-pending","route-failed","terminal","completion-failed"]){const value=html.get(name)!;assert.ok(!value.includes("Reviewed carry-forward is complete")&&!value.includes("Review complete"),`${name} must not render completion`);}
assert.match(html.get("unreviewed")!,/[1-9][0-9]*<\/strong> of 5 proposals unresolved/);for(const label of ["Accept","Correct this proposal","Reject","Needs information"])assert.ok(html.get("unreviewed")!.includes(label),label);assert.match(html.get("unreviewed")!,/Confirm what Discovery should carry forward/);for(const name of ["route-pending","route-failed"]){assert.match(html.get(name)!,/Owner route pending/);assert.match(html.get(name)!,/Review each remaining proposal before recording/);assert.ok(!html.get(name)!.includes("Canonical owner route completed"));}for(const name of ["terminal","completion-failed"]){assert.match(html.get(name)!,/Ready to finalize reviewed carry-forward/);assert.match(html.get(name)!,/Finalize review summary/);}assert.match(html.get("completed")!,/Reviewed carry-forward is complete/);assert.match(html.get("completed")!,/Review complete/);assert.ok(!html.get("completed")!.includes("Finalize review summary"));assert.match(html.get("nonpromotion")!,/owner could not truthfully promote/);assert.match(html.get("nonauthoritative")!,/Recorded nonauthoritatively/);assert.match(html.get("canonical")!,/Canonical owner route completed/);for(const value of html.values()){assert.match(value,/Deterministic development analysis — not a live provider result/);assert.match(value,/Source [0-9]+/);assert.ok(!value.includes("Accept all"));}
const completed=html.get("completed")!,all=[...html.values()],expectedCitationLabels=[...new Set(input.states[0]!.workspace.proposals.flatMap(value=>value.reviewedCarryForward?.citations.map(citation=>citation.sourceId+"\0"+citation.sourceVersion)??[]))].map((_,index)=>`Source ${index+1}`),checks={deterministic:all.every(value=>value.includes("Deterministic development analysis — not a live provider result")),distinctCitations:expectedCitationLabels.length>1&&all.every(value=>expectedCitationLabels.every(label=>value.includes(label))),noAuthorityFields:all.every(value=>!value.includes("authorityRefs")&&!value.includes("policyRefs")&&!value.includes("authorizationContextRef")),pendingNotRouted:!html.get("route-pending")!.includes("Canonical owner route completed"),failedNotRouted:!html.get("route-failed")!.includes("Canonical owner route completed"),nonauthoritative:html.get("nonauthoritative")!.includes("Recorded nonauthoritatively"),nonpromotion:html.get("nonpromotion")!.includes("owner could not truthfully promote"),terminalFinalize:html.get("terminal")!.includes("Finalize review summary"),failureFinalize:html.get("completion-failed")!.includes("Finalize review summary"),completedHeader:completed.includes("Reviewed carry-forward is complete"),completedSummary:completed.includes("Review complete"),completedNoFinalize:!completed.includes("Finalize review summary"),noBulkAcceptance:all.every(value=>!value.includes("Accept all")),...(html.has("gate-2-ready")?{gate2Incomplete:!html.get("gate-2-incomplete")!.includes("Close and continue"),gate2Ready:html.get("gate-2-ready")!.includes("Close and continue")&&!html.get("gate-2-ready")!.includes("This meeting is closed"),gate2ClosedPending:html.get("gate-2-closed-pending")!.includes("reviewed summary has not been saved yet")&&!html.get("gate-2-closed-pending")!.includes("What changed · Prepare Again"),gate2WhatChanged:html.get("gate-2-what-changed")!.includes("What changed · Prepare Again")&&html.get("gate-2-what-changed")!.includes("Continue preparing next occurrence"),gate2SuccessorPending:html.get("gate-2-successor-pending")!.includes("Preparation for the next occurrence is not finished")&&html.get("gate-2-successor-pending")!.includes("Continue preparing next occurrence"),gate2Complete:html.get("gate-2-complete")!.includes("Occurrence 2 is prepared. The next meeting has not started")&&!html.get("gate-2-complete")!.includes("Cycle complete"),gate2Resumable:html.get("gate-2-resumable")!.includes("Your saved progress is intact")&&html.get("gate-2-resumable")!.includes("Resume close and continue")}:{})};
const text=(value:unknown):string=>Array.isArray(value)?value.map(text).join(""):value&&typeof value==="object"?text((value as {props?:{children?:unknown}}).props?.children):typeof value==="string"?value:"";
const findStartButton=(value:unknown):any=>{if(Array.isArray(value)){for(const item of value){const found=findStartButton(item);if(found)return found;}return null;}if(!value||typeof value!=="object")return null;const element=value as {type?:unknown;props?:{children?:unknown}};if(element.type==="button"&&text(element.props?.children)==="Start Reviewed Carry-Forward")return element;return findStartButton(element.props?.children);};
const findButton=(value:unknown,label:string):any=>{if(Array.isArray(value)){for(const item of value){const found=findButton(item,label);if(found)return found;}return null;}if(!value||typeof value!=="object")return null;const element=value as {type?:unknown;props?:{children?:unknown}};if(element.type==="button"&&text(element.props?.children)===label)return element;return findButton(element.props?.children,label);};
const originalHooks={useState:React.useState,useTransition:React.useTransition,useEffect:React.useEffect,useMemo:React.useMemo,useRef:React.useRef,useActionState:(React as typeof React&{useActionState?:unknown}).useActionState},browserGlobal=globalThis as unknown as {window?:{location:{reload():void}}},originalWindow=browserGlobal.window,mutableChecks=checks as Record<string,boolean>,runtimeGlobal=globalThis as any,originalRouter=runtimeGlobal.__reviewedCarryForwardRouter,originalSetTimeout=globalThis.setTimeout,originalClearTimeout=globalThis.clearTimeout;let hookValues:unknown[]=[],hookIndex=0,effects:Array<()=>void|(()=>void)>=[],timerQueue:Array<()=>void>=[];
const resetHooks=()=>{hookValues=[];hookIndex=0;effects=[];};
const fakeUseState=<T,>(initial:T)=>{const index=hookIndex++;if(!(index in hookValues))hookValues[index]=initial;return[hookValues[index] as T,(value:T|((prior:T)=>T))=>{hookValues[index]=typeof value==="function"?(value as (prior:T)=>T)(hookValues[index] as T):value;}] as const;};
const fakeUseRef=<T,>(initial:T)=>{const index=hookIndex++;if(!(index in hookValues))hookValues[index]={current:initial};return hookValues[index] as {current:T};};
Object.assign(React,{useState:fakeUseState,useTransition:()=>[false,(work:()=>void)=>work()] as const,useEffect:(effect:()=>void|(()=>void))=>{effects.push(effect);},useMemo:<T,>(work:()=>T)=>work(),useRef:fakeUseRef,useActionState:(_action:unknown,initial:unknown)=>[initial,()=>{}]});
try{
  let refreshes=0;browserGlobal.window={location:{reload:()=>{refreshes+=1;}}};
  const founderProps={initialWorkspace:unopenedWorkspace,prepare:input.states[0]!.prepare,valueLayer:undefined,personalSheet:undefined,occurrenceRef:"occurrence-1",initialCheckpoint:null,initialMeetingPack:null,reviewedCarryForwardAvailable:true,seriesAddress:"opaque-meeting-address",readOnlyMeetingHome:true};
  runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes+=1;}};globalThis.setTimeout=((work:()=>void)=>{timerQueue.push(work);return timerQueue.length as any;}) as typeof setTimeout;globalThis.clearTimeout=((id:any)=>{if(typeof id==="number")timerQueue[id-1]=()=>{};}) as typeof clearTimeout;
  const flushCritical=async()=>{for(let index=0;index<8;index++)await Promise.resolve();};
  const originalUnreviewed=input.states.find(state=>state.name==="unreviewed")!,unreviewed={...originalUnreviewed,workspace:{...originalUnreviewed.workspace,proposals:[...originalUnreviewed.workspace.proposals].sort((a,b)=>Number(b.kind==="commitment")-Number(a.kind==="commitment"))}},allReviewed={...unreviewed.workspace,dispositions:input.states.find(state=>state.name==="terminal")!.workspace.dispositions,canonicalRoutingReceipts:[],reviewedCarryForwardNonpromotions:[],reviewedCarryForwardCompletion:null};
  const renderCritical=(family:string,action:()=>Promise<unknown>,workspace?:LeadershipConversationWorkspaceV1)=>{hookIndex=0;effects=[];return LeadershipConversationExperience({...founderProps,readOnlyMeetingHome:family==="start-review",initialWorkspace:workspace??(family==="start-review"?unopenedWorkspace:family==="resume-recording"?allReviewed:unreviewed.workspace),personalSheet:sheet,initialCheckpoint:{checkpointId:"render-checkpoint",contributionArtifactIds:[]},reviewCarryForward:action,resumeCarryForward:action,startReviewedCarryForward:action});};
  const findTextarea=(value:any):any=>{if(Array.isArray(value))return value.map(findTextarea).find(Boolean);if(!value||typeof value!=="object")return null;if(value.type==="textarea"&&value.props.maxLength===500)return value;return findTextarea(value.props?.children);};
  const invokeCritical=(family:string,label:string,action:()=>Promise<unknown>)=>{let tree=renderCritical(family,action);if(label==="Save correction"){findTextarea(tree).props.onChange({target:{value:"Human correction for the supported next step."}});tree=renderCritical(family,action);}const button=findButton(tree,label);assert.ok(button,label);button.props.onClick();return button;};
  for(const [family,label,message] of [["start-review","Start Reviewed Carry-Forward","Creating proposed updates…"],["review-proposal","Accept","Saving acceptance…"],["review-proposal","Save correction","Saving correction…"],["resume-recording","Resume recording","Recording reviewed updates…"]]){
    resetHooks();let calls=0,resolve:(value:unknown)=>void=()=>{};const action=()=>{calls++;return new Promise(value=>{resolve=value;});},button=invokeCritical(family!,label!,action);button.props.onClick();assert.equal(calls,1);const tree=renderCritical(family!,action);assert.equal(findButton(tree,label!)?.props.disabled,true);assert.ok(text(tree).includes(message!));resolve({action:family,status:"not-saved",nextStep:"retry"});await flushCritical();
  }
  mutableChecks.criticalDuplicateClick=true;
  const tuples={"start-review":[["created","review-proposals"],["already-available","review-proposals"],["saved-refresh-required","reload"],["not-saved","retry"],["outcome-unavailable","reload"]],"review-proposal":[["saved","continue-review"],["saved","resume-recording"],["already-saved","continue-review"],["already-saved","resume-recording"],["saved-refresh-required","reload"],["not-saved","retry"],["integrity-conflict","none"],["outcome-unavailable","reload"]],"resume-recording":[["complete","finalize-review"],["partial","resume-recording"],["already-complete","finalize-review"],["saved-refresh-required","reload"],["not-saved","retry"],["integrity-conflict","none"],["outcome-unavailable","reload"]]};
  for(const [family,legal] of Object.entries(tuples))for(const label of family==="review-proposal"?["Accept","Reject","Needs information","Save correction"]:[family==="start-review"?"Start Reviewed Carry-Forward":"Resume recording"]){
    for(const [status,nextStep] of legal){resetHooks();refreshes=0;timerQueue=[];const action=async()=>({action:family,status,nextStep});invokeCritical(family,label,action);await flushCritical();let rendered=text(renderCritical(family,action));assert.equal(refreshes,0);if(status==="not-saved")assert.match(rendered,/Nothing new was saved/);else if(status==="outcome-unavailable")assert.match(rendered,/result could not be verified/);else if(status==="integrity-conflict")assert.match(rendered,/No additional action was taken/);else if(status==="saved-refresh-required")assert.match(rendered,/could not update automatically/);else if(status==="already-saved"||status==="already-available"||status==="already-complete")assert.match(rendered,/already/);else if(status==="saved"&&label==="Reject")assert.ok(rendered.includes("Rejected.\nThis item will not carry forward."));else if(status==="saved"&&label==="Needs information")assert.ok(rendered.includes("Marked Needs Information.\nNo owner action was taken."));else if(status==="saved"&&label==="Save correction")assert.ok(rendered.includes("Your wording will carry forward instead of the original proposal."));else if(status==="saved")assert.ok(rendered.includes("Accepted and saved."));else if(status==="complete")assert.ok(rendered.includes("All reviewed updates reached truthful terminal outcomes."));else if(status==="partial")assert.ok(rendered.includes("Some reviewed updates were recorded."));else assert.ok(rendered.includes("Proposed updates were created."));
      if(["created","already-available","saved","already-saved","complete","already-complete","partial"].includes(status!)){for(const effect of effects)effect();assert.equal(refreshes,1);for(const timer of timerQueue)timer();rendered=text(renderCritical(family,action));assert.match(rendered,/Reload/);assert.ok(!rendered.includes("Nothing new was saved"));}
    }
    for(const value of [{action:family,status:"not-saved",nextStep:"retry",extra:"protected"},{action:family,status:"not-saved"},{action:"other",status:"not-saved",nextStep:"retry"},{action:family,status:"other",nextStep:"retry"},{action:family,status:"not-saved",nextStep:"none"},null]){resetHooks();const action=async()=>value;invokeCritical(family,label,action);await flushCritical();const rendered=text(renderCritical(family,action));assert.match(rendered,/result could not be verified/);assert.ok(!rendered.includes("protected"));}
    resetHooks();const lost=async()=>{throw new Error("candidateBodyDigest authorityRefs secret-path");};invokeCritical(family,label,lost);await flushCritical();assert.match(text(renderCritical(family,lost)),/result could not be verified/);assert.ok(!text(renderCritical(family,lost)).includes("secret-path"));
  }
  for(const [family,label,status,nextStep] of [["start-review","Start Reviewed Carry-Forward","created","review-proposals"],["review-proposal","Accept","saved","continue-review"],["resume-recording","Resume recording","complete","finalize-review"]]){
    resetHooks();refreshes=0;timerQueue=[];runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes++;throw new Error("refresh failed");}};const action=async()=>({action:family,status,nextStep});invokeCritical(family!,label!,action);await flushCritical();renderCritical(family!,action);assert.equal(refreshes,0);for(const effect of effects)effect();const message=text(renderCritical(family!,action));assert.match(message,/could not update automatically/);assert.ok(!message.includes("Nothing new was saved"));assert.equal(refreshes,1);
  }
  for(const mode of ["props","unmount"]){resetHooks();refreshes=0;timerQueue=[];runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes++;}};const action=async()=>({action:"review-proposal",status:"saved",nextStep:"continue-review"});invokeCritical("review-proposal","Accept",action);await flushCritical();renderCritical("review-proposal",action);const cleanups=effects.map(effect=>effect()).filter((value):value is ()=>void=>typeof value==="function");assert.equal(timerQueue.length,1);
    if(mode==="props"){renderCritical("review-proposal",action,input.states.find(value=>value.name==="route-pending")!.workspace);for(const effect of effects)effect();}else for(const cleanup of cleanups)cleanup();for(const timer of timerQueue)timer();assert.ok(!text(renderCritical("review-proposal",action)).includes("could not update automatically"));assert.equal(refreshes,1);
  }
  for(const [family,label,status,nextStep] of [["start-review","Start Reviewed Carry-Forward","created","review-proposals"],["review-proposal","Accept","saved","continue-review"],["review-proposal","Save correction","saved","continue-review"],["resume-recording","Resume recording","partial","resume-recording"],["resume-recording","Resume recording","complete","finalize-review"]]){
    resetHooks();refreshes=0;timerQueue=[];runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes++;}};
    let calls=0;const action=async()=>{calls++;return{action:family,status,nextStep};};invokeCritical(family!,label!,action);await flushCritical();renderCritical(family!,action);for(const effect of effects)effect();assert.equal(refreshes,1);
    const origin=family==="start-review"?unopenedWorkspace:family==="resume-recording"?allReviewed:unreviewed.workspace,stale=structuredClone(origin);let staleTree=renderCritical(family!,action,stale);for(const effect of effects)effect();staleTree=renderCritical(family!,action,stale);const control=findButton(staleTree,label!);assert.equal(control?.props.disabled,true);control.props.onClick();assert.equal(calls,1);
    if(status==="partial"){assert.ok(text(staleTree).includes("Waiting for the saved recording progress."));assert.ok(!text(staleTree).includes("remain pending."));}
    for(const timer of timerQueue)timer();const message=text(renderCritical(family!,action,stale));assert.match(message,/could not update automatically/);assert.match(message,/Reload/);assert.ok(!message.includes("Nothing new was saved"));assert.equal(calls,1);assert.equal(refreshes,1);
  }
  mutableChecks.criticalStaleProjection=true;
  mutableChecks.criticalRefresh=true;
  mutableChecks.criticalTupleMatrix=true;mutableChecks.founderStartInteraction=true;
  let tree:any,button:any;
  runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes+=1;}};globalThis.setTimeout=((work:()=>void)=>{timerQueue.push(work);return timerQueue.length as any;}) as typeof setTimeout;globalThis.clearTimeout=((id:any)=>{if(typeof id==="number")timerQueue[id-1]=()=>{};}) as typeof clearTimeout;
  const terminal=input.states.find(value=>value.name==="terminal")!,finalProps={initialWorkspace:terminal.workspace,prepare:terminal.prepare,valueLayer:compileChiefOfStaffValueLayerV1(terminal.prepare),personalSheet:sheet,occurrenceRef:"occurrence-1",initialCheckpoint:{checkpointId:"render-checkpoint",contributionArtifactIds:[]},seriesAddress:"opaque-meeting-address"};
  const renderFinal=(action:()=>Promise<unknown>,workspace=terminal.workspace)=>{hookIndex=0;effects=[];return LeadershipConversationExperience({...finalProps,initialWorkspace:workspace,finalizeReviewedCarryForward:action});};
  const flush=async()=>{for(let index=0;index<8;index+=1)await Promise.resolve();};
  resetHooks();refreshes=0;timerQueue=[];let finalCalls=0,resolveFinal:(value:unknown)=>void=()=>{};const finalDeferred=new Promise<unknown>(resolve=>{resolveFinal=resolve;}),finalAction=async()=>{finalCalls+=1;return finalDeferred;};tree=renderFinal(finalAction);button=findButton(tree,"Finalize review summary");button.props.onClick();button.props.onClick();assert.equal(finalCalls,1);tree=renderFinal(finalAction);assert.match(text(tree),/Finalizing review…/);assert.equal(findButton(tree,"Finalize review summary")?.props.disabled,true);resolveFinal({status:"saved",reviewComplete:true,nextStep:"view-completed-review"});await flush();tree=renderFinal(finalAction);assert.match(text(tree),/Review finalized\.Your choices were saved\./);assert.equal(refreshes,0);for(const effect of effects)effect();assert.equal(refreshes,1);assert.equal(findButton(renderFinal(finalAction),"Finalize review summary"),null);mutableChecks.finalizationDuplicateClick=true;
  const outcomes=[
    [{status:"saved",reviewComplete:true,nextStep:"view-completed-review"},"Review finalized.Your choices were saved."],
    [{status:"already-saved",reviewComplete:true,nextStep:"view-completed-review"},"Review was already finalized.No duplicate completion was created."],
    [{status:"saved-refresh-required",reviewComplete:true,nextStep:"reload"},"Review finalized.Your choices were saved, but this page could not update automatically.Reload to view the completed summary."],
    [{status:"not-saved",reviewComplete:false,nextStep:"retry"},"Review could not be finalized.Nothing new was saved.Try again."],
    [{status:"integrity-conflict",reviewComplete:false,nextStep:"none"},"Review could not be verified.No additional action was taken."],
    [{status:"outcome-unavailable",reviewComplete:null,nextStep:"reload"},"The finalization result could not be verified.Reload to check the saved review before trying again."],
  ] as const;
  for(const [outcome,message] of outcomes){resetHooks();refreshes=0;timerQueue=[];tree=renderFinal(async()=>outcome);findButton(tree,"Finalize review summary").props.onClick();await flush();tree=renderFinal(async()=>outcome);assert.ok(text(tree).includes(message));assert.equal(Boolean(findButton(tree,"Finalize review summary")),outcome.status==="not-saved");}
  for(const malformed of [{status:"saved",reviewComplete:true,nextStep:"view-completed-review",extra:"secret"},{status:"saved",reviewComplete:false,nextStep:"view-completed-review"},{status:"saved",reviewComplete:true},{status:"saved",reviewComplete:true,nextStep:"reload"},{status:"not-saved",reviewComplete:true,nextStep:"retry"},{status:"unknown",reviewComplete:true,nextStep:"view-completed-review"},null]){resetHooks();tree=renderFinal(async()=>malformed);findButton(tree,"Finalize review summary").props.onClick();await flush();assert.match(text(renderFinal(async()=>malformed)),/finalization result could not be verified/);}
  resetHooks();tree=renderFinal(async()=>{throw new Error("candidateBodyDigest governedScopeBinding admissionBasis lifecycleOperationId");});findButton(tree,"Finalize review summary").props.onClick();await flush();const lostTransport=text(renderFinal(async()=>({})));assert.match(lostTransport,/finalization result could not be verified/);for(const secret of ["candidateBodyDigest","governedScopeBinding","admissionBasis","lifecycleOperationId"])assert.ok(!lostTransport.includes(secret));assert.equal(findButton(renderFinal(async()=>({})),"Finalize review summary"),null);
  resetHooks();refreshes=0;runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes+=1;throw new Error("refresh");}};tree=renderFinal(async()=>({status:"saved",reviewComplete:true,nextStep:"view-completed-review"}));findButton(tree,"Finalize review summary").props.onClick();await flush();tree=renderFinal(async()=>({}));assert.match(text(tree),/Your choices were saved/);for(const effect of effects)effect();assert.match(text(renderFinal(async()=>({}))),/could not update automatically/);assert.equal(refreshes,1);mutableChecks.finalizationRefreshFailure=true;
  for(const timeoutOutcome of [{status:"saved",reviewComplete:true,nextStep:"view-completed-review"},{status:"already-saved",reviewComplete:true,nextStep:"view-completed-review"}] as const){resetHooks();refreshes=0;timerQueue=[];runtimeGlobal.__reviewedCarryForwardRouter={refresh(){refreshes+=1;}};tree=renderFinal(async()=>timeoutOutcome);findButton(tree,"Finalize review summary").props.onClick();await flush();tree=renderFinal(async()=>({}));for(const effect of effects)effect();for(const timer of timerQueue)timer();assert.match(text(renderFinal(async()=>({}))),/could not update automatically/);assert.equal(refreshes,1);}mutableChecks.finalizationTimeout=true;
  const completedState=input.states.find(value=>value.name==="completed")!,completedCounts=completedState.workspace.reviewedCarryForwardCompletion!.counts,completedSummary=`${completedCounts.accepted} accepted · ${completedCounts.corrected} corrected · ${completedCounts.rejected} rejected · ${completedCounts.needsInformation} need information · ${completedCounts.unresolved} unresolved · ${completedCounts.routePending} pending routes`;assert.match(completed,/Reviewed carry-forward is complete/);assert.match(completed,/Review complete/);assert.ok(completed.includes(completedSummary));assert.match(completed,new RegExp(`<strong>${completedCounts.unresolved}</strong> of ${completedState.workspace.proposals.length} proposals unresolved`));assert.equal(completedCounts.unresolved,0);assert.equal(completedCounts.routePending,0);assert.ok(!completed.includes("Finalize review summary")&&!completed.includes("completionId")&&!completed.includes("contentDigest"));mutableChecks.finalizationDurableCompleted=true;mutableChecks.finalizationTupleMatrix=true;
}finally{Object.assign(React,originalHooks);globalThis.setTimeout=originalSetTimeout;globalThis.clearTimeout=originalClearTimeout;if(originalRouter===undefined)delete runtimeGlobal.__reviewedCarryForwardRouter;else runtimeGlobal.__reviewedCarryForwardRouter=originalRouter;if(originalWindow===undefined)delete browserGlobal.window;else browserGlobal.window=originalWindow;}for(const [name,value] of Object.entries(checks))assert.equal(value,true,name);process.stdout.write(JSON.stringify({result:"PASS",renders:html.size,expectedCitationLabels,checks}));}void main();
