import assert from "node:assert/strict";
import { createHash } from "node:crypto";

import { resolveCanonicalEvidenceAdmission, runDiscoveryV3 } from "../../engine/v3";
import { createCanonicalScopeTopology, createCanonicalSourceScopeBinding } from "../../engine/v3/governance/canonicalScopeLineage";
import { evolveOrganizationRuntime } from "../../engine/v3/runtime/evolveOrganizationRuntime";
import { createEmptyOrganizationRuntime } from "../../engine/v3/runtime/organizationRuntime";
import { FilesystemOrganizationRuntimeRepository, type StoredOrganizationRuntime } from "../../engine/v3/runtime/organizationRuntimeRepository";
import { atlasIndustrialArtifacts } from "../../engine/benchmark/judgment-lab/atlasIndustrialPilot";
import { CanonicalProductWorkspaceAdapter } from "../../product/integration";
import type { CanonicalEvidenceContribution } from "../../product/integration/contracts";
import { createDurableProductQuestion } from "../../product/questions/questionLifecycle";

const ORG="duplicate-cognition-fresh-process";const USER="fresh-process-validator";const QUESTION="fresh-process-question";const AT="2026-08-06T12:00:00.000Z";
const sha=(value:string)=>createHash("sha256").update(value).digest("hex");const material=atlasIndustrialArtifacts.map(item=>item.content).join("\n\n");
const rootScope={organizationId:ORG,type:"organization" as const,id:ORG};const topology=createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:AT,nodes:[rootScope],relationships:[]});
function context(runtime:StoredOrganizationRuntime["runtime"],question:string,contribution:CanonicalEvidenceContribution){const binding=createCanonicalSourceScopeBinding({organizationId:ORG,bindingVersion:1,source:{sourceId:contribution.sourceId,sourceVersion:"1",normalizedContentDigest:sha(contribution.content)},topology,assertions:[{relationship:"origin",scope:rootScope}],basisRefs:[`fresh:${contribution.sourceId}`],effectiveAt:AT,sourceType:"manual-takeaway",purposeRef:QUESTION,availability:"available"});const prior=runtime.memory.canonicalScopeLineageIndex;const bindings=[...(prior?.sourceBindings??[]).filter(item=>item.source.sourceId!==binding.source.sourceId),binding];const input={company:"Fresh process",website:"",industry:"Testing",question,context:"",evidenceSources:[{sourceId:contribution.sourceId,sourceType:contribution.sourceType,observedAt:AT,contentDigest:binding.source.normalizedContentDigest,content:contribution.content}]};const lineage={organizationId:ORG,effectiveAt:AT,topologyRevisions:[topology],sourceBindingRevisions:bindings,existingEvidenceAttributions:prior?.evidenceAttributions??[]};return{input,lineage};}
function service(repository:FilesystemOrganizationRuntimeRepository,counter:{value:number}){return new CanonicalProductWorkspaceAdapter({runtimeRepository:repository,authorize:async({userId,organizationId})=>userId===USER&&organizationId===ORG,preflightCanonicalEvidence:async({runtime,question,contribution})=>{const value=context(runtime,question,contribution);return resolveCanonicalEvidenceAdmission(value.input,value.lineage);},investigate:async({runtime,question,contribution})=>{counter.value+=1;const {input,lineage}=context(runtime,question,contribution);const result=runDiscoveryV3(input,lineage);const original=console.log;let evolved;try{console.log=()=>{};evolved=evolveOrganizationRuntime({runtime,result,input,semanticTime:AT});}finally{console.log=original;}return{runtime:evolved,evidenceAccepted:result.evidence.length>0,canonicalEvidenceAdmissionBatch:result.scopeLineageAdmission!.operationBatch};}});}
function summary(runtime:StoredOrganizationRuntime["runtime"]){const explanations=runtime.memory.organizationalExplanations??[];const compositions=runtime.memory.organizationalUnderstandingState.canonicalCompositions??[];const support=JSON.stringify({lineage:runtime.memory.canonicalScopeLineageIndex,understanding:runtime.memory.understandingState,model:runtime.organizationModel});return{explanationCount:explanations.length,compositionCount:compositions.length,explanationDigest:sha(JSON.stringify(explanations.map(item=>item.id))),compositionDigest:sha(JSON.stringify(compositions.map(item=>[item.id,item.revisionId]))),supportDigest:sha(support)};}
async function main(){const output=console.log;const stdoutWrite=process.stdout.write.bind(process.stdout);console.log=()=>{};process.stdout.write=((..._args:Parameters<typeof process.stdout.write>)=>true) as typeof process.stdout.write;const [role,root]=process.argv.slice(2);assert.ok(["A","B","C","D","E"].includes(role??""));assert.ok(root&&root.includes("discovery-duplicate-cognition-"));const repository=new FilesystemOrganizationRuntimeRepository(root);if(role==="A"){let runtime=createEmptyOrganizationRuntime({organizationId:ORG,name:"Fresh",now:AT});runtime=createDurableProductQuestion({runtime,title:"What changed?",questionId:QUESTION,createdAt:AT}).runtime;await repository.create(ORG,new TextEncoder().encode(JSON.stringify(runtime,null,2)),{requestId:"initialize",operatorId:USER});}
  const counter={value:0};const adapter=service(repository,counter);const sourceId=role==="D"?"source-new-provenance":role==="E"?"source-contradiction":"source-primary";const content=role==="E"?"The reported constraint is false; the opposite operating condition holds.":material;const key={A:"material",B:"duplicate-one",C:"duplicate-two",D:"new-provenance",E:"contradiction"}[role!]!;const result=await adapter.contributeEvidenceWithCanonicalResult({userId:USER,organizationId:ORG,questionId:QUESTION,contribution:{sourceId,sourceType:"paste",content,contributedAt:AT,idempotencyKey:key},operation:{requestId:key,operatorId:USER}});const stored=await repository.read(ORG);assert.ok(stored);process.stdout.write=stdoutWrite as typeof process.stdout.write;output(JSON.stringify({schemaVersion:"1",role,rootBinding:sha(root),disposition:result.contributionResult.cognitionDisposition,admissions:result.contributionResult.admissions.map(item=>item.disposition),cognitionInvocations:counter.value,...summary(stored.runtime)}));}
main().catch(error=>{console.error(error instanceof Error?error.message:"fresh-process role failed");process.exitCode=1;});
