import assert from "node:assert/strict";
import {spawnSync,spawn} from "node:child_process";
import {readFileSync,writeFileSync,existsSync,realpathSync} from "node:fs";
import {cp,mkdtemp,rm,readdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import * as nodeModule from "node:module";
import {pathToFileURL} from "node:url";
import {createHash} from "node:crypto";
import {resolveScopedGovernanceContext} from "../../engine/v3/governance/scopedGovernanceContext";
const {registerHooks}=nodeModule as unknown as {registerHooks(hooks:{resolve(specifier:string,context:{parentURL?:string},next:(specifier:string,context:unknown)=>any):any;load(url:string,context:unknown,next:(url:string,context:unknown)=>any):any}):{deregister():void}};
import {createProductArtifactBodyRepository} from "../../product/persistence/productArtifactBodyRepository";
import {founderAuthorizedMeetingDirectory} from "../../product/integration/founderAuthorizedMeetingDirectory";
Object.assign(process.env, { NODE_ENV: "test" });
Object.assign(process.env,{DISCOVERY_ENV:"development",NEXT_PUBLIC_DISCOVERY_ENV:"development",DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:"pk_test_validation",CLERK_SECRET_KEY:"sk_test_validation",DISCOVERY_DATABASE_URL:"postgresql://localhost/validation",DISCOVERY_DATABASE_ADMIN_URL:"postgresql://localhost/validation_admin",DISCOVERY_DATABASE_MIGRATION_URL:"postgresql://localhost/validation_migration",DISCOVERY_RUNTIME_STORAGE_BACKEND:"filesystem",DISCOVERY_RUNTIME_ORGANIZATIONS_DIRECTORY:"/tmp/discovery-onboarding-validation",DISCOVERY_SANDBOX_CEO_USER_ID:"user_validationceo",DISCOVERY_SANDBOX_DIRECTOR_USER_ID:"user_validationdirector",DISCOVERY_SANDBOX_MANAGER_USER_ID:"user_validationmanager"});

import {createProductWorkflowArtifactRepository} from "../../product/workflow/leadershipConversation/productWorkflowArtifactRepository";
import {FilesystemOrganizationRuntimeRepository} from "../../engine/v3/runtime/organizationRuntimeRepository";
import {LeadershipConversationProductOperations} from "../../product/workflow/leadershipConversation/operations";
import {createLeadershipConversationServerCompositionForValidation} from "../../product/integration/leadershipConversationServerComposition";
import {composeChiefFirstPrepareViewFromWorkspace} from "../../product/integration/chiefLeadershipPreparationComposer";
import {leadershipDigest,leadershipStableSerialize,leadershipId} from "../../product/workflow/leadershipConversation/determinism";
const hash=(value:unknown)=>leadershipDigest(leadershipStableSerialize(value));
const loader=path.join(process.cwd(),"scripts/product/reviewedCarryForwardValidationLoader.mjs"),seriesAddress="close-validation-address";
type Context={root:string;roots:{runtimeRoot:string;workflowRoot:string;sourceContentRoot:string;lineageFixtureRoot:string;analysisLifecycleRoot:string};userId:string;organizationId:string;questionId:string;conversationId:string;seriesId:string};
const repositories=(input:Context)=>({workflow:createProductWorkflowArtifactRepository({root:input.roots.workflowRoot,environment:"test"}),runtime:new FilesystemOrganizationRuntimeRepository(input.roots.runtimeRoot)});
const snapshot=async(input:Context)=>{const repos=repositories(input);const bodyRoot=path.join(path.dirname(input.roots.workflowRoot),"product-artifact-bodies"),bodies:Record<string,string>={};const walk=async(directory:string)=>{if(!existsSync(directory))return;for(const entry of await readdir(directory,{withFileTypes:true})){const filename=path.join(directory,entry.name);if(entry.isDirectory())await walk(filename);else bodies[path.relative(bodyRoot,filename)]=hash([...readFileSync(filename)]);}};await walk(bodyRoot);return{workflow:await repos.workflow.inspect(input.organizationId),runtime:await repos.runtime.read(input.organizationId),bodies};};
const configure=(input:Context,options:Record<string,unknown>={})=>{process.env.DISCOVERY_FOUNDER_LOCAL_ALPHA_ENABLED="true";process.env.REVIEWED_FINALIZATION_ACTION_CONTEXT=JSON.stringify({...input,...options,seriesAddress});delete (globalThis as any).__reviewedFinalizationValidationState;};
const child=(input:Record<string,unknown>)=>{const result=spawnSync(process.execPath,["--conditions=react-server","--import",loader,"--import","tsx",process.argv[1]!],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,CLOSE_LIFECYCLE_CHILD:JSON.stringify(input)}});assert.equal(result.status,0,result.stderr+result.stdout);return JSON.parse(result.stdout.trim().split("\n").at(-1)!);};
const summary=(value:Awaited<ReturnType<typeof snapshot>>)=>{const store=value.workflow.store,closure=store.cycle1ClosureCompletions??[],changes=store.whatChangedPublications??[],links=store.futurePreparationLinks;return{workflowRevision:value.workflow.revision,workflowDigest:hash(store),runtimeRevision:value.runtime?.revision,runtimeDigest:hash(value.runtime),closures:closure.map(item=>item.closureId),whatChanged:changes.map(item=>item.artifactId),futureLinks:links.map(item=>item.futurePreparationLinkId),successors:links.map(item=>item.nextConversationId),contexts:store.contexts.map(item=>item.contextVersionId),preparations:(store.preparedWorkPublications??[]).map(item=>item.artifactRevision)};};
// Real request composition and directory, with only external request identity,
// access-repository reads and runtime bootstrap metadata supplied by fixtures.
// The production grant construction and lifecycle implementation both execute.
async function founderRequestFixture(input:Context,options:Record<string,any>={}){
 const runtime=globalThis as any,participantRef="participant:isolated-founder",at="2026-01-01T00:00:00.000Z";
 const state={grants:[] as any[],protectedReads:0,providerRequests:0,accessWrites:0};
 const policy={organizationId:input.organizationId,mode:"participant-reference-v1",issuedBy:"isolated-issuer",operationId:"policy",requestFingerprint:"policy-fingerprint",createdAt:at};
 const grants=["organization","meeting-series"].map(scope=>({grantId:`grant:${scope}`,organizationId:input.organizationId,participantRef,scope,meetingSeriesId:scope==="meeting-series"?input.seriesId:null,status:"active",issuedBy:policy.issuedBy,operationId:`grant:${scope}`,requestFingerprint:`fingerprint:${scope}`,createdAt:at,revokedAt:null,supersedesGrantId:null}));
 const accessBefore=JSON.stringify({policy,grants});
 runtime.__resumeRequest=async()=>{if(options.absentAuthentication)throw new Error("Unauthenticated fixture");return{consumerId:options.wrongParticipant?"ungranted-user":input.userId,participantRef:options.additionalParticipant||options.wrongParticipant?"participant:ungranted":participantRef,close:async()=>{},accessRepository:{findOrganizationIdsForParticipant:async()=>[options.foreignOrganization?"foreign-organization":input.organizationId],findPolicy:async()=>options.unavailableAccess?undefined:policy,findGrants:async(query:any)=>options.foreignSeries?[]:grants.filter(grant=>grant.organizationId===query.organizationId&&grant.participantRef===query.participantRef&&grant.scope===query.scope&&(query.scope!=="meeting-series"||grant.meetingSeriesId===query.meetingSeriesId)),createGrant:async()=>{state.accessWrites++;throw new Error("Grant writes forbidden");}}};};
 runtime.__resumeMetadata=async(organizationId:string)=>organizationId!==input.organizationId?null:{runtime:{memory:{initialUnderstandingBootstrap:{initialProductQuestionId:options.foreignQuestion?"foreign-question":input.questionId}}}};
 runtime.__resumeConstruct=(construction:any)=>{
  state.grants=structuredClone(construction.authorityGrants);
  const authorityGrants=structuredClone(state.grants);for(const grant of authorityGrants)grant.operations=grant.operations.filter((operation:string)=>operation!==options.missingCapability);
  return createLeadershipConversationServerCompositionForValidation({...input.roots,userId:input.userId,organizationId:input.organizationId,authorityGrants,onProtectedArtifactRead:()=>{state.protectedReads++;},onProtectedSourceContentRead:()=>{state.protectedReads++;},analysisTransport:async()=>{state.providerRequests++;throw new Error("Provider forbidden");}});
 };
 const data=(source:string)=>`data:text/javascript,${encodeURIComponent(source)}`;
 const sources={request:data("export const createFounderFirstUnderstandingRequestComposition=()=>globalThis.__resumeRequest();"),root:data(`export const resolveFounderLocalAlphaRuntimeRootFromEnvironment=async()=>({status:'ready',value:${JSON.stringify({sourceContentRoot:input.roots.sourceContentRoot,productArtifactBodyRoot:path.join(path.dirname(input.roots.workflowRoot),"product-artifact-bodies")})}});`),runtime:data("export class FilesystemOrganizationRuntimeRepository{async read(id){return globalThis.__resumeMetadata(id);}}"),server:data("export const createFounderLocalAlphaLeadershipConversationComposition=input=>globalThis.__resumeConstruct(input);")};
 const hook=registerHooks({resolve(specifier,context,next){if(specifier.endsWith("/founderMeetingHomeComposition"))return{url:pathToFileURL(path.join(process.cwd(),"lib/alpha-activation/founderMeetingHomeComposition.ts")).href,shortCircuit:true};if(context.parentURL?.endsWith("/founderMeetingHomeComposition.ts")){const url=specifier.endsWith("/founderFirstUnderstandingRequestComposition")?sources.request:specifier.endsWith("/founderLocalAlphaRuntimeRoot")?sources.root:specifier.endsWith("/organizationRuntimeRepository")?sources.runtime:specifier.endsWith("/leadershipConversationServerComposition")?sources.server:null;if(url)return{url,shortCircuit:true};}return next(specifier,context);},load(url,context,next){if(Object.values(sources).includes(url))return{format:"module",source:decodeURIComponent(url.slice(url.indexOf(",")+1)),shortCircuit:true};return next(url,context);}});
 Object.assign(process.env,{DISCOVERY_FOUNDER_LOCAL_ALPHA_ENABLED:"true",DISCOVERY_RUNTIME_ORGANIZATIONS_DIRECTORY:input.roots.runtimeRoot,DISCOVERY_LEADERSHIP_CONVERSATION_WORKFLOW_ROOT:input.roots.workflowRoot});
 const address=createHash("sha256").update(`meeting-series-address:v1:${input.organizationId}:${input.seriesId}`).digest("base64url").slice(0,24);
 return{address,state,verify:()=>assert.equal(JSON.stringify({policy,grants}),accessBefore),hook};
}
async function main(){
 if(process.env.CLOSE_LIFECYCLE_CHILD){
  const request=JSON.parse(process.env.CLOSE_LIFECYCLE_CHILD),input=request.context as Context,before=await snapshot(input);assert.equal(hash(before),request.parentDigest);
  let faultCalls=0;const errors:string[]=[];for(const method of ["completeReviewedMeetingPackClosure","publishClosureWhatChanged","recordContext","recordPreparation","linkFuturePreparation"]){const proto=LeadershipConversationProductOperations.prototype as any,original=proto[method];proto[method]=async function(...args:unknown[]){try{return await original.apply(this,args);}catch(error){errors.push(String(error));throw error;}};}const faultMethod:Record<string,string>={"after-closure":"completeReviewedMeetingPackClosure","after-what-changed":"publishClosureWhatChanged","after-context":"recordContext","after-preparation":"recordPreparation","after-successor":"linkFuturePreparation"};
  const method=faultMethod[request.fault];if(method){const proto=LeadershipConversationProductOperations.prototype as any,original=proto[method];proto[method]=async function(...args:unknown[]){const result=await original.apply(this,args);faultCalls++;throw new Error("isolated post-stage interruption");return result;};}
  configure(input,request.options);const founder=request.resumeAuthority?await founderRequestFixture(input,request.options):null;let outcome:unknown=null,workspace:unknown=null;
  const {closeAndContinueOccurrence1Action,resumeOccurrence1CarryForwardCompletionAction}=await import("../../app/product-alpha/leadership-conversation/actions");
  if(request.barrier){writeFileSync(request.barrier+"."+request.actor,"ready");const deadline=Date.now()+30000;while(!existsSync(request.barrier+".go")){assert(Date.now()<deadline);await new Promise(resolve=>setTimeout(resolve,10));}}
  if(request.command==="finalize")outcome=await resumeOccurrence1CarryForwardCompletionAction(seriesAddress);
  else if(request.command==="read"){const server=createLeadershipConversationServerCompositionForValidation({...input.roots,userId:input.userId,organizationId:input.organizationId,analysisTransport:async()=>{throw new Error("provider forbidden");}});workspace=await server.workspace({...input,conversationId:request.successor??input.conversationId});}
  else if(request.command==="authority"||request.command==="scope"||request.command==="denied-projection"){
    const {createFounderMeetingHomeComposition}=await import("../../lib/alpha-activation/founderMeetingHomeComposition");
    try{const composition=await createFounderMeetingHomeComposition(founder!.address);outcome=request.command==="scope"?await composition.server.closeAndContinue({...input,...request.scopeOverride}):request.command==="denied-projection"?await composition.server.workspace(input):{status:"authorized"};await composition.close();}catch(error){errors.push(String(error));outcome={status:"denied"};}
  }
  else outcome=await closeAndContinueOccurrence1Action(...(request.arguments??[founder?.address??seriesAddress]));
  const after=await snapshot(input),state=(globalThis as any).__reviewedFinalizationValidationState??{};
  if(request.command==="read")assert.deepEqual(after,before,"Read-only reconstruction changed state");
  founder?.verify();console.log(JSON.stringify({rootRealpath:realpathSync(input.root),parentDigest:request.parentDigest,predecessorDigest:hash(before),afterDigest:hash(after),...summary(after),outcome,errors,faultCalls,providerRequests:founder?.state.providerRequests??state.providerRequests??0,protectedReads:founder?.state.protectedReads??((state.sourceReads??0)+(state.projectionReads??0)),authorityGrants:founder?.state.grants,accessWrites:founder?.state.accessWrites??0,workspace}));founder?.hook.deregister();return;
 }
 const controls=Object.fromEntries(Array.from({length:12},(_,index)=>[`G${index+1}`,false]));
 const resumeControls=Object.fromEntries(Array.from({length:12},(_,index)=>[`R${index+1}`,false]));
 const generated=spawnSync(process.execPath,["--conditions=react-server","--import",loader,"--import","tsx",path.join(process.cwd(),"scripts/product/validateReviewedCarryForward.ts")],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,V3_ISOLATED_FIXTURE_CHILD:"1"}});assert.equal(generated.status,0,generated.stderr);const fixture=JSON.parse(generated.stdout.trim().split("\n").at(-1)!);
 const workflow=createProductWorkflowArtifactRepository({root:fixture.roots.workflowRoot,environment:"test"}),organizationFile=(await readdir(path.join(fixture.roots.workflowRoot,"organizations"))).find(value=>value.endsWith(".json"));assert(organizationFile);const raw=JSON.parse(readFileSync(path.join(fixture.roots.workflowRoot,"organizations",organizationFile),"utf8"));
 const organizationId=raw.organizationId??raw.store?.organizationId;assert(organizationId);const store=(await workflow.inspect(organizationId)).store,proposal=store.proposals[0]!;
 const context:Context={root:fixture.root,roots:fixture.roots,organizationId,userId:store.dispositions[0]!.reviewedByUserId,questionId:proposal.questionId,conversationId:proposal.conversationId,seriesId:fixture.seriesId};
 const run=async(input:Context,options:Record<string,unknown>={})=>child({context:input,parentDigest:hash(await snapshot(input)),...options});
 const containers:string[]=[context.root];
 const clone=async(label:string)=>{const root=await mkdtemp(path.join(tmpdir(),`discovery-northstar-preparation-lineage-close-${label}-`));containers.push(root);await cp(context.root,root,{recursive:true});return{...context,root,roots:Object.fromEntries(Object.entries(context.roots).map(([key,value])=>[key,path.join(root,path.relative(context.root,value))])) as Context["roots"]};};
 try{
  const missing=await snapshot(context),missingResult=await run(context);assert.equal(missingResult.outcome.status,"integrity-conflict");assert.deepEqual(await snapshot(context),missing);
  const finalized=await run(context,{command:"finalize"});assert.equal(finalized.outcome.status,"saved");
  const terminal=await snapshot(context);assert.equal(terminal.workflow.store.reviewedCarryForwardCompletions?.length,1);
  const partial=await clone("resume-partial"),partialResult=await run(partial,{fault:"after-context"});assert.equal(partialResult.outcome.status,"partial");
  const partialInventory=await snapshot(partial);assert.equal(partialInventory.workflow.store.contexts.length,2);assert.equal(partialInventory.workflow.store.futurePreparationLinks.length,0);assert.equal(partialInventory.workflow.store.preparedWorkPublications!.length,1);
  const authority=await run(partial,{resumeAuthority:true,command:"authority"});assert.equal(authority.outcome.status,"authorized",JSON.stringify(authority));assert.equal(authority.accessWrites,0);assert.equal(authority.protectedReads,0);assert.deepEqual(await snapshot(partial),partialInventory);
  const expectedOperations=["source-binding:resolve-current","source-content:read-for-proposal","source-content:read-for-claim-support","product-artifact:read","product-artifact:reuse","product-artifact:compare","product-workspace:read","product-artifact:prepare-again","product-artifact:create-successor"];
  assert.equal(authority.authorityGrants.length,1);assert.deepEqual(authority.authorityGrants[0].operations,expectedOperations);
  for(const operation of ["product-artifact:prepare-again","product-artifact:create-successor"] as const){const grant=authority.authorityGrants[0],request={organizationId:context.organizationId,subjectId:context.userId,requestedScope:grant.scope,operation,purpose:"resume-validation",sensitivity:"standard" as const,evaluatedAt:"2026-09-14T00:00:00.000Z",temporal:{mode:"current" as const},serverResolvedAuthority:[grant]};assert.equal(resolveScopedGovernanceContext(request).disposition,"authorized");for(const altered of [{...grant,status:"revoked"},{...grant,validFrom:"2099-01-01T00:00:00.000Z"},{...grant,validUntil:"2026-01-02T00:00:00.000Z"},{...grant,scope:{...grant.scope,id:"foreign"}},{...grant,subjectId:"ungranted"}])assert.notEqual(resolveScopedGovernanceContext({...request,serverResolvedAuthority:[altered]}).disposition,"authorized");}resumeControls.R1=true;
  for(const name of ["additionalParticipant","wrongParticipant","foreignOrganization","foreignSeries","foreignQuestion","absentAuthentication","unavailableAccess"]){const result=await run(partial,{resumeAuthority:true,command:"authority",options:{[name]:true}});assert.equal(result.outcome.status,"denied",name);assert.equal(result.protectedReads,0);assert.equal(result.accessWrites,0);assert.equal(result.authorityGrants.length,0);assert.deepEqual(await snapshot(partial),partialInventory);}resumeControls.R2=true;
  for(const scopeOverride of [{conversationId:"unrelated-occurrence"},{questionId:"unrelated-question"},{seriesId:"unrelated-series"},{organizationId:"foreign-organization"},{userId:"ungranted-user"}]){const denied=await run(partial,{resumeAuthority:true,command:"scope",scopeOverride});assert.equal(denied.outcome.status,"integrity-conflict");assert.equal(denied.protectedReads,0);assert.deepEqual(await snapshot(partial),partialInventory);}
  for(const capability of ["product-artifact:prepare-again","product-artifact:create-successor"]){const denied=await run(partial,{resumeAuthority:true,options:{missingCapability:capability}});assert.deepEqual(denied.outcome,{status:"integrity-conflict",stage:"unknown",nextStep:"none"});assert.equal(denied.protectedReads,0);assert.deepEqual(await snapshot(partial),partialInventory);}resumeControls.R7=true;
  for(const capability of ["product-artifact:prepare-again","product-artifact:create-successor"]){const denied=await run(partial,{resumeAuthority:true,command:"denied-projection",options:{missingCapability:capability}});assert.equal(denied.outcome.status,"denied");assert.equal(denied.protectedReads,0);assert.deepEqual(await snapshot(partial),partialInventory);}
  const partialRead=await run(partial,{command:"read"});assert.deepEqual(await snapshot(partial),partialInventory);
  const resumed=await run(partial,{resumeAuthority:true});assert.equal(resumed.outcome.status,"complete",JSON.stringify(resumed));const resumedInventory=await snapshot(partial),rs=resumedInventory.workflow.store;
  assert.equal(rs.cycle1ClosureCompletions!.length,1);assert.equal(rs.whatChangedPublications!.length,1);assert.equal(rs.contexts.length,2);assert.equal(rs.futurePreparationLinks.length,1);assert.equal(rs.preparedWorkPublications!.length,2);assert.equal(rs.contexts.filter(value=>value.conversationId===leadershipId("leadership-conversation",context.seriesId,"occurrence",3)).length,0);
  for(const key of ["cycle1ClosureCompletions","whatChangedPublications","contexts","proposals","dispositions","canonicalRoutingReceipts","reviewedCarryForwardCompletions"] as const)assert.deepEqual(rs[key],partialInventory.workflow.store[key],key);assert.deepEqual(resumedInventory.runtime,partialInventory.runtime);assert.equal(resumed.providerRequests,0);resumeControls.R8=true;
  const resumedReplay=await run(partial,{resumeAuthority:true});assert.equal(resumedReplay.outcome.status,"already-complete");assert.deepEqual(await snapshot(partial),resumedInventory);resumeControls.R10=true;
  for(const capability of ["product-artifact:prepare-again","product-artifact:create-successor"]){const denied=await run(partial,{resumeAuthority:true,options:{missingCapability:capability}});assert.equal(denied.outcome.status,"integrity-conflict");assert.equal(denied.protectedReads,0);assert.deepEqual(await snapshot(partial),resumedInventory);}
  for(const field of ["seriesId","occurrenceId","successorId","closureId","whatChangedId","owner","capability"]){const denied=await run(partial,{resumeAuthority:true,arguments:["invalid-client-address",{[field]:"forged"}]});assert.equal(denied.outcome.status,"integrity-conflict");assert.equal(denied.protectedReads,0);assert.equal(denied.authorityGrants.length,0);assert.deepEqual(await snapshot(partial),resumedInventory);}resumeControls.R9=true;
  const lawful=await clone("lawful"),result=await run(lawful);assert.equal(result.outcome.status,"complete",JSON.stringify(result));
  const inventory=await snapshot(lawful),assertComplete=(value:Awaited<ReturnType<typeof snapshot>>)=>{const w=value.workflow.store;assert.equal(w.cycle1ClosureCompletions?.length,1);assert.equal(w.whatChangedPublications?.length,1);assert.equal(w.futurePreparationLinks.length,1);assert.equal(w.contexts.length,2);assert.equal(w.preparedWorkPublications?.length,2);assert.equal(w.contexts.filter(value=>value.conversationId===leadershipId("leadership-conversation",context.seriesId,"occurrence",3)).length,0);assert.deepEqual(w.proposals,terminal.workflow.store.proposals);assert.deepEqual(w.canonicalRoutingReceipts,terminal.workflow.store.canonicalRoutingReceipts);assert.deepEqual(value.runtime,terminal.runtime);const closure=w.cycle1ClosureCompletions![0]!,link=w.futurePreparationLinks[0]!;assert.equal(closure.seriesId,context.seriesId);assert.equal(closure.conversationId,context.conversationId);assert.equal(link.nextConversationId,leadershipId("leadership-conversation",context.seriesId,"occurrence",2));assert.notEqual(link.nextConversationId,context.conversationId);assert.equal(link.questionId,context.questionId);assert.equal(closure.contractVersion,"2");assert.equal(link.contractVersion,"2");assert.equal(closure.checkpointId,null);assert.equal(link.sourceFrozenSnapshotId,null);};
  assertComplete(inventory);assert.equal(result.providerRequests,0);controls.G2=true;console.log("G2 executed");
  for(const name of ["unresolved","pending","conflicting-completion","wrong-occurrence","wrong-series","denied"]){const test=await clone(name),repository=repositories(test).workflow,old=await repository.read(test.organizationId),store=structuredClone(old.store);if(name==="unresolved")store.dispositions.pop();if(name==="pending")store.canonicalRoutingReceipts.pop();if(name==="conflicting-completion")store.reviewedCarryForwardCompletions![0]!.contentDigest="0".repeat(64);if(["unresolved","pending","conflicting-completion"].includes(name))await repository.replace(test.organizationId,store,old.revision);const before=await snapshot(test),outcome=await run(name==="wrong-occurrence"?{...test,conversationId:"wrong-occurrence"}:name==="wrong-series"?{...test,seriesId:"wrong-series"}:test,{options:name==="denied"?{denyAccess:true}:{}});assert.notEqual(outcome.outcome.status,"complete");assert.deepEqual(await snapshot(test),before,name);assert.equal(outcome.protectedReads,0,name);assert.equal(outcome.providerRequests,0);}controls.G1=true;console.log("G1 executed");
  const bodyRepository=createProductArtifactBodyRepository({root:path.join(path.dirname(lawful.roots.workflowRoot),"product-artifact-bodies")}),body=JSON.parse(new TextDecoder().decode(await bodyRepository.readStagedExact(inventory.workflow.store.whatChangedPublications![0]!.protectedBody))),closure=inventory.workflow.store.cycle1ClosureCompletions![0]!;
  for(const proposal of terminal.workflow.store.proposals){const choice=terminal.workflow.store.dispositions.find(value=>value.proposalId===proposal.proposalId)!,item=body.terminalItems.find((value:any)=>value.proposalId===proposal.proposalId);assert(item);assert.equal(item.summary,(choice.effectivePayload??proposal.payload).summary);if(choice.disposition==="rejected"||choice.disposition==="deferred"){assert.equal(item.authority,"excluded-from-promotion");assert(!JSON.stringify(closure.sections).includes(item.summary));}else if(terminal.workflow.store.reviewedCarryForwardNonpromotions?.some(value=>value.proposalId===proposal.proposalId)){assert.equal(item.authority,"reviewed-nonpromotion");assert(JSON.stringify(closure.sections).includes("exact current Product Answer required by the Decision owner was unavailable"));}else{const route=terminal.workflow.store.canonicalRoutingReceipts.find(value=>value.proposalId===proposal.proposalId)!;assert.equal(item.terminalReceiptDigest,route.receiptDigest);assert.equal(item.authority,["commitment","assumption-change"].includes(route.ownerKind)?"nonauthoritative-owner-result":"canonical-owner-result");}if(choice.effectivePayload){assert(JSON.stringify(closure.sections).includes("Founder corrected:"));assert(!JSON.stringify(closure.sections).includes(proposal.payload.summary));}}
  controls.G3=true;
  const replay=await run(lawful);assert.equal(replay.outcome.status,"already-complete");assert.deepEqual(await snapshot(lawful),inventory);controls.G4=true;
  const failureReports=[];
  for(const [fault,stage,status] of [["after-closure","what-changed","partial"],["after-what-changed","prepare-again","partial"],["after-context","prepare-again","partial"],["after-preparation","successor","partial"],["after-successor","complete","saved-refresh-required"]]){const test=await clone(fault!),failed=await run(test,{fault});assert.equal(failed.faultCalls,1,JSON.stringify(failed));assert.equal(failed.outcome.status,status,JSON.stringify(failed));assert.equal(failed.outcome.stage,stage);const saved=summary(await snapshot(test)),resumed=await run(test);assert(["complete","already-complete"].includes(resumed.outcome.status),JSON.stringify(resumed));const after=await snapshot(test);assertComplete(after);assert.deepEqual(summary(after).closures,saved.closures);for(const name of ["whatChanged","futureLinks"] as const)if(saved[name].length)assert.deepEqual(summary(after)[name],saved[name]);failureReports.push({fault,stage,status,resumed:resumed.outcome.status});}controls.G5=true;console.log("G5 executed");
  const race=await clone("race"),barrier=path.join(race.root,"race-ready"),parentDigest=hash(await snapshot(race)),startRace=(actor:string)=>new Promise<any>((resolve,reject)=>{const processChild=spawn(process.execPath,["--conditions=react-server","--import",loader,"--import","tsx",process.argv[1]!],{cwd:process.cwd(),env:{...process.env,CLOSE_LIFECYCLE_CHILD:JSON.stringify({context:race,parentDigest,barrier,actor})}});let output="",error="";processChild.stdout.on("data",value=>output+=value);processChild.stderr.on("data",value=>error+=value);processChild.on("exit",code=>code===0?resolve(JSON.parse(output.trim().split("\n").at(-1)!)):reject(new Error(error)));});const processes=[startRace("A"),startRace("B")],deadline=Date.now()+30000;while(!existsSync(barrier+".A")||!existsSync(barrier+".B")){assert(Date.now()<deadline);await new Promise(resolve=>setTimeout(resolve,10));}writeFileSync(barrier+".go","go");const raced=await Promise.all(processes);assertComplete(await snapshot(race));for(const report of raced){assert.equal(report.rootRealpath,realpathSync(race.root));assert(["complete","already-complete","saved-refresh-required"].includes(report.outcome.status),JSON.stringify(report));assert.equal(report.providerRequests,0);}assert.equal(raced.filter(value=>value.outcome.status==="complete").length,1);controls.G6=true;console.log("G6 executed");
  const resumeRace=await clone("resume-race");await run(resumeRace,{fault:"after-context"});const raceBefore=await snapshot(resumeRace),resumeBarrier=path.join(resumeRace.root,"resume-ready"),raceChild=(actor:string)=>new Promise<any>((resolve,reject)=>{const processChild=spawn(process.execPath,["--conditions=react-server","--import",loader,"--import","tsx",process.argv[1]!],{cwd:process.cwd(),env:{...process.env,CLOSE_LIFECYCLE_CHILD:JSON.stringify({context:resumeRace,parentDigest:hash(raceBefore),barrier:resumeBarrier,actor,resumeAuthority:true})}});let output="",errors="";processChild.stdout.on("data",chunk=>output+=chunk);processChild.stderr.on("data",chunk=>errors+=chunk);processChild.on("exit",code=>code===0?resolve(JSON.parse(output.trim().split("\n").at(-1)!)):reject(new Error(errors+output)));});const concurrent=[raceChild("A"),raceChild("B")],resumeDeadline=Date.now()+30000;while(!existsSync(resumeBarrier+".A")||!existsSync(resumeBarrier+".B")){assert(Date.now()<resumeDeadline);await new Promise(resolve=>setTimeout(resolve,10));}writeFileSync(resumeBarrier+".go","go");const resumeRaced=await Promise.all(concurrent);for(const result of resumeRaced){assert(["complete","already-complete","saved-refresh-required"].includes(result.outcome.status));assert.equal(result.providerRequests,0);}const raceAfter=await snapshot(resumeRace);assertComplete(raceAfter);for(const key of ["contexts","cycle1ClosureCompletions","whatChangedPublications"] as const)assert.deepEqual(raceAfter.workflow.store[key],raceBefore.workflow.store[key]);await run(resumeRace,{command:"read"});assert.deepEqual(await snapshot(resumeRace),raceAfter);resumeControls.R12=true;
  for(const field of ["successorId","seriesId","occurrenceId","owner","capability","closureId","whatChangedId"]){const before=await snapshot(context),forged=await run(context,{arguments:[seriesAddress,{[field]:"forged"}]});assert.deepEqual(forged.outcome,{status:"integrity-conflict",stage:"unknown",nextStep:"none"});assert.equal(forged.protectedReads,0);assert.deepEqual(await snapshot(context),before);}controls.G7=true;
  const revoked=await clone("revoked"),interrupted=await run(revoked,{fault:"after-closure"});assert.equal(interrupted.outcome.status,"partial");const revokedBefore=await snapshot(revoked),denied=await run(revoked,{options:{denyAccess:true}});assert.equal(denied.outcome.status,"integrity-conflict");assert.equal(denied.protectedReads,0);assert.deepEqual(await snapshot(revoked),revokedBefore);controls.G8=true;
  const privateBefore=await snapshot(lawful),manager=createLeadershipConversationServerCompositionForValidation({...lawful.roots,userId:lawful.userId,organizationId:lawful.organizationId,personaKey:"sandbox-manager"}),managerView=await manager.workspace(lawful);assert.equal(managerView.closureCompletion,null);assert.equal(managerView.closeContinuation,undefined);assert.deepEqual(await snapshot(lawful),privateBefore);
  const nextPublication=inventory.workflow.store.preparedWorkPublications!.find(value=>value.productWorkflowId!==`leadership-conversation:${context.conversationId}`)!,nextBody=JSON.parse(new TextDecoder().decode(await bodyRepository.readStagedExact(nextPublication.protectedBody)));for(const choice of terminal.workflow.store.dispositions)if(choice.effectivePayload)assert(!JSON.stringify(nextBody.content).includes(choice.effectivePayload.summary));assert.equal(Object.keys(result.outcome).sort().join(","),"nextStep,stage,status");controls.G9=true;
  const sequence=await clone("process-sequence"),manifests=[];for(const request of [{fault:"after-closure"},{fault:"after-what-changed"},{fault:"after-preparation"},{},{command:"read"}]){const before=await snapshot(sequence),report=await run(sequence,request);assert.equal(report.parentDigest,hash(before));assert.equal(report.predecessorDigest,hash(before));assert.equal(report.afterDigest,hash(await snapshot(sequence)));assert.equal(report.rootRealpath,realpathSync(sequence.root));assert.equal(report.providerRequests,0);manifests.push(report);}assertComplete(await snapshot(sequence));const successor=manifests[3]!.successors[0],reconstructed=await run(sequence,{command:"read",successor});assert.equal(reconstructed.workspace.closeContinuation.stage,"complete");const cards=await founderAuthorizedMeetingDirectory({userId:context.userId,organizationId:context.organizationId,questionId:context.questionId,workflowRoot:sequence.roots.workflowRoot,currentAccess:{authorize:async()=>"authorized"}});assert.equal(cards.length,1);assert.equal(cards[0]!.occurrenceId,successor);assert.equal(cards[0]!.predecessorOccurrenceId,context.conversationId);controls.G10=true;console.log("G10 executed");
  const ready=await run(context,{command:"read"}),renderManifest=path.join(sequence.root,"close-render.json");writeFileSync(renderManifest,JSON.stringify({states:[{name:"ready",workspace:ready.workspace,prepare:composeChiefFirstPrepareViewFromWorkspace(ready.workspace)},{name:"partial",workspace:partialRead.workspace,prepare:composeChiefFirstPrepareViewFromWorkspace(partialRead.workspace)},{name:"complete",workspace:reconstructed.workspace,prepare:composeChiefFirstPrepareViewFromWorkspace(reconstructed.workspace)}]}));const renderer=spawnSync(process.execPath,["--import",loader,"--import",path.join(process.cwd(),"scripts/product/reviewedCarryForwardRenderLoader.mjs"),"--import","tsx",path.join(process.cwd(),"scripts/product/renderReviewedCarryForwardUi.tsx"),renderManifest],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_OPTIONS:"",CLOSE_RENDER:"1"}});assert.equal(renderer.status,0,renderer.stderr+renderer.stdout);const renderResult=JSON.parse(renderer.stdout);assert.equal(renderResult.result,"PASS");for(const name of ["R3","R4","R5","R6","R11"]){assert.equal(renderResult.resumeControls[name],true);resumeControls[name]=true;}for(const name of ["U1","U2","U3","U4","U5","U6","U7","U8","U9","U10"]){assert.equal(renderResult.partialFeedbackControls[name],true);resumeControls[name]=true;}assert.deepEqual({workflowWrites:renderResult.workflowWrites,runtimeWrites:renderResult.runtimeWrites,providerRequests:renderResult.providerRequests,liveStateWrites:renderResult.liveStateWrites},{workflowWrites:0,runtimeWrites:0,providerRequests:0,liveStateWrites:0});controls.G11=true;console.log("G11 executed");
  const regressions=spawnSync(process.execPath,["--conditions=react-server","--import",loader,"--import","tsx",path.join(process.cwd(),"scripts/product/validateReviewedCarryForward.ts")],{cwd:process.cwd(),encoding:"utf8",env:{...process.env}});writeFileSync("/private/tmp/close-reviewed-regression.log",regressions.stdout+regressions.stderr);assert.equal(regressions.status,0,regressions.stderr);const reports=regressions.stdout.split("\n").flatMap(line=>{try{return[JSON.parse(line)];}catch{return[];}});assert.equal(reports.filter(value=>value.validation&&value.result==="PASS").length,1);const critical=reports.find(value=>value.criticalControls)?.criticalControls;assert(critical);assert.equal(Object.keys(critical).length,12);assert(Object.values(critical).every(value=>value===true));assert(regressions.stdout.includes("PASS truthful Reviewed Carry-Forward finalization acknowledgement"));controls.G12=true;
  for(const [name,executed] of Object.entries(controls))assert.equal(executed,true,`${name} did not execute`);
  for(const [name,executed] of Object.entries(resumeControls))assert.equal(executed,true,`${name} did not execute`);
  console.log("PASS Founder successor authority and partial resume R1–R12");
  console.log(JSON.stringify({result:"PASS",controls,resumeControls,failureReports,concurrentStatuses:raced.map(value=>value.outcome.status),resumeConcurrentStatuses:resumeRaced.map(value=>value.outcome.status),freshProcesses:6,providerRequests:0,liveMutations:0,inventory:summary(inventory)}));
 }finally{if(!process.env.CLOSE_KEEP_FIXTURES)for(const root of containers)await rm(root,{recursive:true,force:true});}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
