import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {mkdtemp,readFile,readdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import postgres from "postgres";
import {PostgresParticipantReferenceAccessRepository} from "../../db/governance/postgresRepositories";
import {FilesystemOrganizationRuntimeRepository} from "../../engine/v3/runtime/organizationRuntimeRepository";
import {FounderFirstUnderstandingApplicationService} from "../../lib/alpha-activation/founderFirstUnderstandingApplicationService";
import {FounderAddGovernedContextApplicationService} from "../../lib/alpha-activation/founderAddGovernedContextApplicationService";
import {parseFounderAddGovernedContextForm} from "../../lib/alpha-activation/founderAddGovernedContextForm";
import {normalizeFounderAddGovernedContextActionForm} from "../../lib/alpha-activation/founderAddGovernedContextTransport";
import {createFounderFirstUnderstandingOwnerBundleForIsolatedValidation} from "../../lib/alpha-activation/founderFirstUnderstandingOwnerBundle";
import {resolveCurrentPreparedWorkPublication} from "../../lib/alpha-activation/founderCurrentPreparation";
import {parseFirstUnderstandingForm} from "../../lib/alpha-activation/founderFirstUnderstandingForm";
import type {RegisteredMeetingPreparationScopeV1} from "../../product/workflow/leadershipConversation";

const initialForm=(name:string)=>{const data=new FormData();for(const[key,value]of Object.entries({organizationDisplayName:name,understandingPurpose:"Decide the safest launch path",primaryQuestion:"Should the launch proceed, be delayed, or use a controlled pilot?",meetingTitle:"Weekly launch readiness",cadence:"Weekly",confirmation:"confirmed"}))data.set(key,value);data.append("files",new File(["The launch decision requires a governed starting point."],"01_strategy.txt"));data.append("sourcePurpose","Defines the launch decision and success criteria.");return data;};
const additiveForm=()=>{const data=new FormData();data.set("intent","add-governed-context");for(let index=2;index<=5;index++){data.append("files",new File([`Governed source ${index} adds distinct launch evidence.`],`0${index}_context.txt`));data.append("sourcePurpose",`Explains the decision relevance of source ${index}.`);}return data;};
const oneSourceForm=(index:number)=>{const data=new FormData();data.set("intent","add-governed-context");data.append("files",new File([`Governed source ${index} adds distinct launch evidence.`],`0${index}_context.txt`));data.append("sourcePurpose",`Explains the decision relevance of source ${index}.`);return data;};

async function main(){
 const root=await mkdtemp(path.join(tmpdir(),"discovery-add-governed-context-")),url=process.env.DISCOVERY_TEST_DATABASE_URL;if(!url||!/^postgres(?:ql)?:\/\/[^/]+@(127\.0\.0\.1|localhost):55432\//u.test(url))throw new Error("An explicitly configured local validation database is required.");
 const sql=postgres(url,{max:1}),rollback=new Error("ROLLBACK_VALIDATION");let checks=0;
 try{await sql.begin("isolation level serializable",async tx=>{const nested=new Proxy(tx,{get(target,key,receiver){return key==="begin"?(_options:unknown,operation:(value:typeof tx)=>Promise<unknown>)=>target.savepoint(operation):Reflect.get(target,key,receiver);}}),participantRef=`participant:${randomUUID()}`,consumerId="user_add_context_validation",accessRepository=new PostgresParticipantReferenceAccessRepository(nested as unknown as typeof sql);
  const createBundle=(scenarioRoot:string)=>createFounderFirstUnderstandingOwnerBundleForIsolatedValidation({runtime:new FilesystemOrganizationRuntimeRepository(path.join(scenarioRoot,"runtime")),accessRepository,workflowRoot:path.join(scenarioRoot,"workflow"),sourceRoot:path.join(scenarioRoot,"sources"),bodyRoot:path.join(scenarioRoot,"bodies"),participantRef,consumerId,close:async()=>undefined});
  const prepare=async(label:string)=>{const scenarioRoot=path.join(root,label),initial=await parseFirstUnderstandingForm(initialForm(`Add Context ${label} ${randomUUID()}`)),firstBundle=createBundle(scenarioRoot),first=new FounderFirstUnderstandingApplicationService(firstBundle),applied=await first.apply(initial);assert.ok("meetingHomeDestination" in applied);const seriesAddress=applied.meetingHomeDestination.split("/").at(-1)!;return{scenarioRoot,seriesAddress,input:await parseFounderAddGovernedContextForm(additiveForm()),bundle:createBundle(scenarioRoot)};};
  const malformed=additiveForm();malformed.set("organizationId","forged");await assert.rejects(()=>parseFounderAddGovernedContextForm(malformed));checks++;
  assert.equal(resolveCurrentPreparedWorkPublication([{artifactVersion:1,artifactRevision:"one",predecessorArtifactVersionId:null},{artifactVersion:2,artifactRevision:"two",predecessorArtifactVersionId:"one"}]).artifactRevision,"two");assert.throws(()=>resolveCurrentPreparedWorkPublication([{artifactVersion:1,artifactRevision:"one",predecessorArtifactVersionId:null},{artifactVersion:2,artifactRevision:"other",predecessorArtifactVersionId:"missing"}]));checks++;
  const invalid=additiveForm();invalid.append("files",new File(["extra"],"06_extra.txt"));invalid.append("sourcePurpose","Invalid fifth source");await assert.rejects(()=>parseFounderAddGovernedContextForm(invalid));checks++;
  const rendered=additiveForm(),reference="rsc-generated-reference-7F3a";for(const key of ["$ACTION_KEY",`$ACTION_REF_${reference}`,`$ACTION_${reference}:0`,`$ACTION_${reference}:1`,`$ACTION_REF_another-generated-reference`,`$ACTION_another-generated-reference:metadata`,`$ACTION_future-framework-field`])rendered.append(key,"opaque-framework-metadata");const normalized=normalizeFounderAddGovernedContextActionForm(rendered);assert.equal([...normalized.keys()].some(key=>key.startsWith("$ACTION_")),false);assert.equal((await parseFounderAddGovernedContextForm(normalized)).sources.length,4);for(const key of ["ACTION_FAKE","$ACTION","$action_fake","X$ACTION_FAKE"]){const near=additiveForm();near.append(key,"forged");await assert.rejects(()=>parseFounderAddGovernedContextForm(normalizeFounderAddGovernedContextActionForm(near)));}checks++;
  for(const field of ["participantRef","organizationId","productQuestionId","occurrenceId","scopeId","expectedRevision","sourceDigest","capability","callback"]){const forged=additiveForm();forged.append(field,"forged");await assert.rejects(()=>parseFounderAddGovernedContextForm(normalizeFounderAddGovernedContextActionForm(forged)));checks++;}
  const duplicateIntent=additiveForm();duplicateIntent.append("intent","add-governed-context");await assert.rejects(()=>parseFounderAddGovernedContextForm(duplicateIntent));const missingPurpose=new FormData();missingPurpose.set("intent","add-governed-context");missingPurpose.append("files",new File(["source"],"missing-purpose.txt"));await assert.rejects(()=>parseFounderAddGovernedContextForm(missingPurpose));const extraPurpose=additiveForm();extraPurpose.append("sourcePurpose","orphaned purpose");await assert.rejects(()=>parseFounderAddGovernedContextForm(extraPurpose));const duplicateSource=new FormData();duplicateSource.set("intent","add-governed-context");for(let index=0;index<2;index++){duplicateSource.append("files",new File(["same source"],`duplicate-${index}.txt`));duplicateSource.append("sourcePurpose","Duplicate source");}await assert.rejects(()=>parseFounderAddGovernedContextForm(duplicateSource));const unsupported=new FormData();unsupported.set("intent","add-governed-context");unsupported.append("files",new File(["source"],"unsupported.pdf"));unsupported.append("sourcePurpose","Unsupported source");await assert.rejects(()=>parseFounderAddGovernedContextForm(unsupported));const empty=new FormData();empty.set("intent","add-governed-context");empty.append("files",new File([],"empty.txt"));empty.append("sourcePurpose","Empty source");await assert.rejects(()=>parseFounderAddGovernedContextForm(empty));checks+=6;
  const mainScenario=await prepare("success"),service=new FounderAddGovernedContextApplicationService(mainScenario.bundle),result=await service.apply(mainScenario.seriesAddress,mainScenario.input);assert.equal(result.status,"applied");checks++;
  const stored=await mainScenario.bundle.runtime.read((await mainScenario.bundle.planAddContext(mainScenario.seriesAddress,mainScenario.input.sources)).organizationId);assert.ok(stored);assert.equal(stored.runtime.memory.canonicalScopeLineageIndex?.sourceBindings.length,5);checks++;
  const plan=await mainScenario.bundle.planAddContext(mainScenario.seriesAddress,mainScenario.input.sources),organizationId=stored.runtime.metadata.organizationId,workflow=(await mainScenario.bundle.workflow.read(organizationId)).store,scopes=(workflow as typeof workflow&{registeredMeetingPreparationScopes:RegisteredMeetingPreparationScopeV1[]}).registeredMeetingPreparationScopes,pubs=workflow.preparedWorkPublications??[];assert.equal(scopes.length,2);assert.deepEqual(scopes.map(value=>value.sourceVersions.length).sort((a,b)=>a-b),[1,5]);assert.equal(pubs.length,2);assert.equal(pubs[0]!.materialLineage?.sourceContentVersions.length,1);assert.equal(pubs[1]!.materialLineage?.sourceContentVersions.length,5);assert.equal(workflow.contexts.length,1);assert.equal(workflow.meetingPackPublications?.length??0,0);const occurrence=await mainScenario.bundle.workflow.readOccurrence!({organizationId,questionId:plan.questionId,conversationId:plan.conversationId,seriesId:plan.seriesId});const occurrenceScopes=(occurrence.store as typeof occurrence.store&{registeredMeetingPreparationScopes:RegisteredMeetingPreparationScopeV1[]}).registeredMeetingPreparationScopes??[];assert.equal(occurrenceScopes.length,2);assert.deepEqual(occurrenceScopes.map(value=>value.scopeDigest).sort(),scopes.map(value=>value.scopeDigest).sort());assert.deepEqual((occurrence.store.preparedWorkPublications??[]).map(value=>value.artifactRevision).sort(),pubs.map(value=>value.artifactRevision).sort());checks++;
  const replayBundle=createBundle(mainScenario.scenarioRoot),replay=await new FounderAddGovernedContextApplicationService(replayBundle).apply(mainScenario.seriesAddress,mainScenario.input);assert.equal(replay.status,"replayed");const replayStore=(await replayBundle.workflow.read(organizationId)).store;assert.equal((replayStore as typeof replayStore&{registeredMeetingPreparationScopes:RegisteredMeetingPreparationScopeV1[]}).registeredMeetingPreparationScopes.length,2);assert.equal(replayStore.preparedWorkPublications?.length,2);checks++;
  // Model the exact recoverable failure shape: historic 1/2/3/4-source
  // preparations plus a complete fifth source that was admitted before its
  // scope write. The generic recovery must preserve every history entry and
  // add only the missing complete successor.
  const reconciliation=await prepare("reconciliation");
  for(let index=2;index<=4;index++){const input=await parseFounderAddGovernedContextForm(oneSourceForm(index));assert.equal((await new FounderAddGovernedContextApplicationService(createBundle(reconciliation.scenarioRoot)).apply(reconciliation.seriesAddress,input)).status,"applied");}
  const fifth=await parseFounderAddGovernedContextForm(oneSourceForm(5)),incomplete=createBundle(reconciliation.scenarioRoot),fifthPlan=await incomplete.planAddContext(reconciliation.seriesAddress,fifth.sources);await incomplete.admitSources(fifthPlan.questionId);
  const beforeRecovery=(await incomplete.workflow.read(fifthPlan.organizationId)).store,beforeScopes=(beforeRecovery as typeof beforeRecovery&{registeredMeetingPreparationScopes:RegisteredMeetingPreparationScopeV1[]}).registeredMeetingPreparationScopes??[];assert.deepEqual(beforeScopes.map(value=>value.sourceVersions.length).sort((a,b)=>a-b),[1,2,3,4]);assert.equal(beforeRecovery.preparedWorkPublications?.length,4);
  const dry=await createBundle(reconciliation.scenarioRoot).reconcileAddContext(reconciliation.seriesAddress,false);assert.deepEqual(dry,{status:"dry-run",sourceWrites:0,scopeWrites:1,preparedWorkWrites:1,sourceCount:5});
  const repaired=await createBundle(reconciliation.scenarioRoot).reconcileAddContext(reconciliation.seriesAddress,true);assert.equal(repaired.status,"applied");assert.equal(repaired.sourceWrites,0);assert.equal(repaired.scopeWrites,1);assert.equal(repaired.preparedWorkWrites,1);assert.equal(repaired.sourceCount,5);
  const freshRecovery=createBundle(reconciliation.scenarioRoot),recoveryReplay=await freshRecovery.reconcileAddContext(reconciliation.seriesAddress,true),recoveredStore=(await freshRecovery.workflow.read(fifthPlan.organizationId)).store,recoveredScopes=(recoveredStore as typeof recoveredStore&{registeredMeetingPreparationScopes:RegisteredMeetingPreparationScopeV1[]}).registeredMeetingPreparationScopes??[];assert.equal(recoveryReplay.sourceWrites,0);assert.equal(recoveryReplay.scopeWrites,0);assert.equal(recoveryReplay.preparedWorkWrites,0);assert.deepEqual(recoveredScopes.map(value=>value.sourceVersions.length).sort((a,b)=>a-b),[1,2,3,4,5]);assert.equal(recoveredStore.preparedWorkPublications?.length,5);checks++;
  const changedMetadata={...mainScenario.input,sources:mainScenario.input.sources.map((source,index)=>index===0?{...source,purpose:`${source.purpose} changed`}:source)};await assert.rejects(()=>createBundle(mainScenario.scenarioRoot).planAddContext(mainScenario.seriesAddress,changedMetadata.sources),/conflicts/);checks++;
  const deniedScenario=await prepare("denied"),deniedBundle=createFounderFirstUnderstandingOwnerBundleForIsolatedValidation({runtime:new FilesystemOrganizationRuntimeRepository(path.join(deniedScenario.scenarioRoot,"runtime")),accessRepository,workflowRoot:path.join(deniedScenario.scenarioRoot,"workflow"),sourceRoot:path.join(deniedScenario.scenarioRoot,"sources"),bodyRoot:path.join(deniedScenario.scenarioRoot,"bodies"),participantRef:`participant:${randomUUID()}`,consumerId:"unauthorized_user",close:async()=>undefined}),denied=await new FounderAddGovernedContextApplicationService(deniedBundle).apply(deniedScenario.seriesAddress,deniedScenario.input);assert.equal(denied.status,"unavailable");checks++;
  const wrongIssuerScenario=await prepare("wrong-issuer"),findGrants=accessRepository.findGrants.bind(accessRepository);accessRepository.findGrants=async input=>(await findGrants(input)).map(grant=>grant.status==="active"?{...grant,issuedBy:"unrelated-authority"}:grant);await assert.rejects(()=>wrongIssuerScenario.bundle.planAddContext(wrongIssuerScenario.seriesAddress,wrongIssuerScenario.input.sources),/unavailable/);accessRepository.findGrants=findGrants;checks++;
  const packedScenario=await prepare("packed"),packedPlan=await packedScenario.bundle.planAddContext(packedScenario.seriesAddress,packedScenario.input.sources),packedRead=packedScenario.bundle.workflow.read.bind(packedScenario.bundle.workflow);packedScenario.bundle.workflow.read=async organization=>{const value=await packedRead(organization);return{...value,store:{...value.store,meetingPackPublications:[...(value.store.meetingPackPublications??[]),{conversationId:packedPlan.conversationId}]}} as typeof value;};await assert.rejects(()=>packedScenario.bundle.planAddContext(packedScenario.seriesAddress,packedScenario.input.sources),/unavailable/);checks++;
  const productionScenario=await prepare("production"),mutableEnvironment=process.env as Record<string,string|undefined>,priorEnvironment=mutableEnvironment.NODE_ENV;mutableEnvironment.NODE_ENV="production";await assert.rejects(()=>productionScenario.bundle.planAddContext(productionScenario.seriesAddress,productionScenario.input.sources));mutableEnvironment.NODE_ENV=priorEnvironment;checks++;
  for(const failure of ["third-source","scope","prepared","lost-response"] as const){const scenario=await prepare(failure),candidate=scenario.bundle,add=new FounderAddGovernedContextApplicationService(candidate);if(failure==="third-source"){const write=candidate.sourceContent.write.bind(candidate.sourceContent);let writes=0;candidate.sourceContent.write=async input=>{if(++writes>=3)throw new Error("injected third source failure");return write(input);};assert.equal((await add.apply(scenario.seriesAddress,scenario.input)).status,"retry-required");}
   if(failure==="scope"){const register=candidate.workflow.registerMeetingPreparationScope.bind(candidate.workflow);candidate.workflow.registerMeetingPreparationScope=async input=>{if(input.sourceVersions.length>1)throw new Error("injected scope failure");return register(input);};assert.equal((await add.apply(scenario.seriesAddress,scenario.input)).status,"retry-required");}
   if(failure==="prepared"){const stage=candidate.bodies.stage.bind(candidate.bodies);candidate.bodies.stage=async input=>{if(input.artifactType==="prepared-work")throw new Error("injected Prepared Work failure");return stage(input);};assert.equal((await add.apply(scenario.seriesAddress,scenario.input)).status,"retry-required");}
   if(failure==="lost-response")assert.equal((await add.apply(scenario.seriesAddress,scenario.input)).status,"applied");
   const recovered=createBundle(scenario.scenarioRoot),recoveredResult=await new FounderAddGovernedContextApplicationService(recovered).apply(scenario.seriesAddress,scenario.input);assert.ok(["applied","replayed"].includes(recoveredResult.status));const plan=await recovered.planAddContext(scenario.seriesAddress,scenario.input.sources),state=(await recovered.workflow.read(plan.organizationId)).store,finalScopes=(state as typeof state&{registeredMeetingPreparationScopes:RegisteredMeetingPreparationScopeV1[]}).registeredMeetingPreparationScopes;assert.equal(finalScopes.length,2);assert.equal(state.preparedWorkPublications?.length,2);assert.equal((await recovered.runtime.read(plan.organizationId))?.runtime.memory.canonicalScopeLineageIndex?.sourceBindings.length,5);checks++;}
  const manifest=JSON.parse(await readFile(path.join(mainScenario.scenarioRoot,"sources","organizations",organizationId,"manifest.json"),"utf8")) as{versions:unknown[]};assert.equal(manifest.versions.length,5);assert.deepEqual((await readdir(path.join(mainScenario.scenarioRoot,"sources","organizations",organizationId,"blobs"))).length,5);checks++;
  console.log(`PASS Founder Add Governed Context actual-owner checks=${checks} sources=1->5 scopes=1->2 prepared=1->2 packs=0 replay=reconciled partial-recovery=4`);throw rollback;
 }).catch(error=>{if(error!==rollback)throw error;});console.log("PASS isolated SQL transaction rolled back; founder state writes=0");}finally{await sql.end({timeout:1});await rm(root,{recursive:true,force:true});}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
