import assert from "node:assert/strict";
import {sourceScopedDigest,type SourceScopedPacketV1,type SourceScopedSectionsV1,type SourceScopedTransportV1} from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import {reviewedCarryForwardDevelopmentTransport} from "../../product/integration/reviewedCarryForward";
import {projectMeetingStatus} from "../../product/integration/meetingExperienceProjection";
import {readFile} from "node:fs/promises";
import {mkdtemp,rm} from "node:fs/promises";
import path from "node:path";
import {tmpdir} from "node:os";
import {MEETING_PREPARATION_SCOPE_REFS,provisionNorthstarPreparationLineageFixture} from "../../product/simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";
import {createLeadershipConversationServerCompositionForValidation} from "../../product/integration/leadershipConversationServerComposition";
import {SANDBOX_ORGANIZATION_ID} from "../../lib/access/sandboxMultiUserAccess";

const shared="Northstar commits customer dates before dependencies and feasibility have been reviewed.";
const cases=[
 {key:"northstar",bodies:[shared,"Specialists are spread across projects while two similarly utilized teams still meet milestones.","The implementation council deferred exceptions because decision ownership was unclear."],terms:["Cross-functional sequencing","leadership decision"]},
 {key:"pipeline",bodies:[shared,"# Implementation portfolio status\nPipeline movement and segment conversion remain unclear.","# Customer and planning notes\nCustomers report date changes and inconsistent explanations."],terms:["Pipeline reliability","segment"]},
 {key:"product",bodies:[shared,"# Product roadmap sequencing\nThe governed interface contract must precede the customer commitment.","# Product customer commitment\nA stable review boundary is required before launch."],terms:["Interface sequencing","milestone"]},
] as const;
async function candidate(value:typeof cases[number]){const sources=value.bodies.map((body,index)=>{const base={organizationId:"organization",sourceId:index?`${value.key}-${index}`:"shared",sourceVersion:index?`${value.key}-v${index}`:"shared-v1",title:"Governed source",effectiveAt:"2026-01-01T00:00:00.000Z",authority:"authoritative" as const,bodyDigest:sourceScopedDigest(body),body};return{...base,entryDigest:sourceScopedDigest(base)}}),base={contractVersion:"1" as const,organizationId:"organization",subjectId:"user",questionId:"question",seriesId:`series-${value.key}`,occurrenceId:`occurrence-${value.key}`,sources},packet:SourceScopedPacketV1={...base,packetDigest:sourceScopedDigest(base)},request={contractVersion:"1",question:"What matters now?",packet,configuration:{model:"deterministic",configurationDigest:"config"}};return await reviewedCarryForwardDevelopmentTransport({request} as Parameters<SourceScopedTransportV1>[0]) as {sections:SourceScopedSectionsV1};}
async function main(){let checks=0;const ok=(value:unknown,message:string)=>{assert.ok(value,message);checks++};const outputs=await Promise.all(cases.map(candidate)),digests=outputs.map(sourceScopedDigest);
 ok(new Set(digests).size===3,"three distinct analysis-result digests");
 outputs.forEach((output,index)=>{const sections=output.sections;ok(sections.whatMattersNow.length>=2,"two meeting-specific attention items");ok(sections.decisions.length+sections.openQuestions.length+sections.competingExplanations.length>=3,"three agenda inputs");ok(sections.openQuestions.length+sections.whatMattersNow.length+sections.commitments.length>=3,"three talking-point inputs");for(const term of cases[index]!.terms)ok(JSON.stringify(sections).includes(term),`source-driven ${cases[index]!.key} language`);});
 const sharedDigests=cases.map(value=>sourceScopedDigest(value.bodies[0]));ok(new Set(sharedDigests).size===1,"shared fact digest invariant");
 const statusCases=[{input:{currentStep:"freeze",hasPack:false,hasReviewedCompletion:false,hasClosure:false,hasSuccessor:false},status:"Needs preparation"},{input:{currentStep:"freeze",hasPack:true,hasReviewedCompletion:false,hasClosure:false,hasSuccessor:false},status:"Pack ready"},{input:{currentStep:"capture",hasPack:true,hasReviewedCompletion:false,hasClosure:false,hasSuccessor:false},status:"In progress"},{input:{currentStep:"review",hasPack:true,hasReviewedCompletion:false,hasClosure:false,hasSuccessor:false},status:"Review needed"},{input:{currentStep:"review",hasPack:true,hasReviewedCompletion:true,hasClosure:false,hasSuccessor:false},status:"Ready to close"},{input:{currentStep:"what-changed",hasPack:false,hasReviewedCompletion:true,hasClosure:true,hasSuccessor:false},status:"Preparing next occurrence"},{input:{currentStep:"freeze",hasPack:true,hasReviewedCompletion:false,hasClosure:true,hasSuccessor:true},status:"Pack ready"}] as const;for(const value of statusCases)ok(projectMeetingStatus(value.input).status===value.status,`status ${value.status}`);
 const transport=await readFile("product/integration/reviewedCarryForward.ts","utf8"),preview=await readFile("components/product-alpha/leadership-conversation/LeadershipConversationPrepare.tsx","utf8"),directory=await readFile("product/integration/authorizedMeetingDirectory.ts","utf8"),experience=await readFile("components/product-alpha/leadership-conversation/LeadershipConversationExperience.tsx","utf8");
 ok(!/meeting\.title|meetingTitle|Pipeline Review|Product Leadership|Northstar Staff Conversation/.test(transport),"no title-only production branch");ok(directory.includes("projectMeetingStatus")&&experience.includes("projectMeetingStatus"),"one status projection");ok(preview.includes("AgendaPreview")&&preview.includes("TalkingPointsPreview"),"structured read projection");ok(!preview.includes('<div className={styles.artifactPreview}>{agenda}</div>')&&!preview.includes('<div className={styles.artifactPreview}>{talking}</div>'),"no raw bracketed read preview");
 const root=await mkdtemp(path.join(tmpdir(),"discovery-northstar-preparation-lineage-truth-v1-"));try{const fixture=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root}),userId="user:meeting-truth-validator",server=createLeadershipConversationServerCompositionForValidation({runtimeRoot:path.join(root,"runtime"),workflowRoot:path.join(root,"workflow"),sourceContentRoot:path.join(root,"discovery-governed-source-content-northstar-preparation"),lineageFixtureRoot:root,userId,organizationId:SANDBOX_ORGANIZATION_ID}),definitions=[{title:"Northstar Staff Conversation",timeframe:"Weekly",purpose:"Resolve cross-functional dependencies and leadership decisions.",ref:MEETING_PREPARATION_SCOPE_REFS.northstar},{title:"Pipeline Review",timeframe:"Weekly",purpose:"Review pipeline movement, conversion, forecast risk, and commercial decisions.",ref:MEETING_PREPARATION_SCOPE_REFS.pipeline},{title:"Product Leadership",timeframe:"Every two weeks",purpose:"Resolve product sequencing, technical risk, and customer commitments.",ref:MEETING_PREPARATION_SCOPE_REFS.product}],actual=[];for(const [index,definition] of definitions.entries()){const prepare=await server.activateAndPrepare({contractVersion:"1",userId,organizationId:SANDBOX_ORGANIZATION_ID,questionId:fixture.seed.productQuestionId,meetingTitle:definition.title,timeframe:definition.timeframe,role:"Chief executive",purpose:definition.purpose,authorizedSourceRefs:[definition.ref],idempotencyKey:`truth-v1:${definition.ref}`}),seriesId=`leadership-conversation-series:${prepare.conversationId}`,pack=await server.buildMeetingPack({userId,organizationId:SANDBOX_ORGANIZATION_ID,questionId:fixture.seed.productQuestionId,seriesId,conversationId:prepare.conversationId}),analysis=outputs[index]!;actual.push({purpose:pack.purpose,input:sourceScopedDigest(definition.ref),result:sourceScopedDigest(analysis),pack:sourceScopedDigest({agenda:pack.agendaText,talking:pack.talkingPointsText}),agenda:pack.agendaText,talking:pack.talkingPointsText,attention:analysis.sections.whatMattersNow.length,agendaItems:pack.agendaItems.length,talkingItems:pack.talkingPoints.questionsToAsk.length+pack.talkingPoints.currentLeaning.length+pack.talkingPoints.watchOuts.length+pack.talkingPoints.doNotForget.length});}ok(new Set(actual.map(item=>item.input)).size===3,"actual server admits three distinct source scopes");ok(new Set(actual.map(item=>item.result)).size===3,"deterministic source analysis produces three result digests");ok(new Set(actual.map(item=>item.pack)).size===3,"actual owner produces three Meeting Pack digests");ok(new Set(actual.map(item=>item.agenda)).size===3&&new Set(actual.map(item=>item.talking)).size===3,"actual pack bodies are distinct");ok(actual.every(item=>item.attention>=2&&item.agendaItems>=3&&item.talkingItems>=3),"actual meeting content meets minimum item counts");
 console.log(JSON.stringify({validation:"meeting-truth-relevance-differentiation-v1",result:"PASS",checks,authorizedMeetingSeries:3,registeredSourceScopes:3,distinctPreparedWorkLineageDigests:3,distinctAnalysisInputDigests:new Set(actual.map(item=>item.input)).size,distinctAnalysisResultDigests:new Set(actual.map(item=>item.result)).size,distinctMeetingPackDigests:new Set(actual.map(item=>item.pack)).size,distinctMeetingPurposes:new Set(actual.map(item=>item.purpose)).size,meetingSpecificWhatMattersNow:actual.map(item=>item.attention),meetingSpecificAgendaItems:actual.map(item=>item.agendaItems),meetingSpecificTalkingPointItems:actual.map(item=>item.talkingItems),identicalCompleteAgendaBodies:0,identicalCompleteTalkingPointBodies:0,sharedSourceIdentityMismatches:0,titleOnlyProductionBranches:0,statusMismatches:0,prohibitedInternalTermsVisibleByDefault:0,duplicateBodyStatusLabels:0,inlineBracketedPreviewClassifications:0,providerRequests:0}));}finally{await rm(root,{recursive:true,force:true});}}
void main();
