import assert from "node:assert/strict";
import {existsSync} from "node:fs";
import {mkdir,mkdtemp,readFile,readdir,rm} from "node:fs/promises";
import {spawnSync} from "node:child_process";
import {createHash} from "node:crypto";
import {tmpdir} from "node:os";
import path from "node:path";

import {resolvePersonaForSignedInUser} from "../../lib/access/sandboxMultiUserAccess";
import {sourceScopedDigest,sourceScopedStable,type SourceScopedResultV1} from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import {createLeadershipConversationServerComposition,createLeadershipConversationServerCompositionForValidation} from "../../product/integration/leadershipConversationServerComposition";
import {createProductWorkflowArtifactRepository} from "../../product/workflow/leadershipConversation/productWorkflowArtifactRepository";
import {provisionNorthstarPreparationLineageFixture} from "../../product/simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";
import {SANDBOX_ORGANIZATION_ID} from "../../product/simulations/living-organization-sandbox/manifest";
import {NORTHSTAR_PREPARED_CONTENT,NORTHSTAR_PREPARED_LINEAGE,northstarLeadershipConversationFixture} from "../../product/workflow/leadershipConversation";

function assertCanonicalResultDigest(result:SourceScopedResultV1){
  const{resultDigest,...unsigned}=result;
  assert.equal(resultDigest,sourceScopedDigest(unsigned));
  assert.deepEqual(Object.keys(result).sort(),result.status==="eligible"
    ?["candidate","contractVersion","dispatchCount","resultDigest","status"].sort()
    :["contractVersion","dispatchCount","resultDigest","status"].sort());
}

async function main(){
  const root=await mkdtemp(path.join(tmpdir(),"discovery-northstar-preparation-lineage-onboarding-generate-action-boundary-")),workflowRoot=path.join(root,"workflow"),actor="user_GenerateRouteCeo";
  await mkdir(workflowRoot,{mode:0o700});
  const environment={NODE_ENV:"development",DISCOVERY_ENV:"development",NEXT_PUBLIC_DISCOVERY_ENV:"development",DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:["pk","test","generate-action-boundary"].join("_"),CLERK_SECRET_KEY:["sk","test","generate-action-boundary"].join("_"),DISCOVERY_DATABASE_URL:"postgresql://127.0.0.1/discovery_validation",DISCOVERY_DATABASE_ADMIN_URL:"postgresql://127.0.0.1/discovery_validation",DISCOVERY_DATABASE_MIGRATION_URL:"postgresql://127.0.0.1/discovery_validation",DISCOVERY_RUNTIME_STORAGE_BACKEND:"filesystem",DISCOVERY_NORTHSTAR_PREPARATION_LINEAGE_ROOT:root,DISCOVERY_NORTHSTAR_PREPARATION_LINEAGE_FIXTURE_ROOT:root,DISCOVERY_RUNTIME_ORGANIZATIONS_DIRECTORY:path.join(root,"runtime"),DISCOVERY_LEADERSHIP_CONVERSATION_WORKFLOW_ROOT:workflowRoot,DISCOVERY_RUNTIME_PROVISIONING_ENABLED:"false",DISCOVERY_ACCESS_PROVISIONING_ENABLED:"false",DISCOVERY_ATLAS_LIVE_PROVISIONING_ENABLED:"false",DISCOVERY_HOSTED_ENVIRONMENT:"false",DISCOVERY_SANDBOX_CEO_USER_ID:actor,DISCOVERY_SANDBOX_DIRECTOR_USER_ID:"user_GenerateRouteDirector",DISCOVERY_SANDBOX_MANAGER_USER_ID:"user_GenerateRouteManager",DISCOVERY_GENERATE_ANALYSIS_TEST_USER_ID:actor};
  const prior=new Map(Object.keys(environment).map(key=>[key,process.env[key]])),unset=["DISCOVERY_LEADERSHIP_CONVERSATION_SOURCE_CONTENT_ROOT","DISCOVERY_GOVERNED_SOURCE_CONTENT_ROOT","DISCOVERY_ALPHA_ANALYSIS_LIFECYCLE_ROOT"],priorUnset=new Map(unset.map(key=>[key,process.env[key]])),priorTimeout=process.env.DISCOVERY_ALPHA_ANALYSIS_TIMEOUT_MS,priorFetch=globalThis.fetch;
  try{
    Object.assign(process.env,environment);for(const key of unset)delete process.env[key];
    assert.equal(resolvePersonaForSignedInUser(actor)?.userId,actor,"auth stub identity reconstructs the canonical persona");
    const setup=await provisionNorthstarPreparationLineageFixture({environment:"development",fixtureRoot:root}),fixture=northstarLeadershipConversationFixture(setup.seed.productQuestionId),identity={userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:fixture.questionId,conversationId:fixture.conversationId},server=createLeadershipConversationServerComposition();
    assert.equal(await server.authorizePageCurrentAccess(identity),true,"development CEO access");
    const stored=await server.recordContext({...identity,idempotencyKey:"generate-action-boundary:context",title:"Northstar staff conversation",purpose:"Resolve the next delivery constraint.",intendedOutcome:"Agree one bounded owner action.",timeframe:"Weekly",participants:[{participantRef:`participant:${actor}`,displayName:"Leader",titleLabel:"Chief executive"}],leaderContext:null}),context=stored.contexts.find(value=>value.conversationId===fixture.conversationId);assert.ok(context);
    await server.recordPreparation({...identity,idempotencyKey:"generate-action-boundary:prepare",contextVersionId:context.contextVersionId,content:NORTHSTAR_PREPARED_CONTENT,lineage:NORTHSTAR_PREPARED_LINEAGE,changeSummary:null});
    const runtimeFile=path.join(root,"runtime",`${SANDBOX_ORGANIZATION_ID}.json`),workflowFile=path.join(workflowRoot,"organizations",`${SANDBOX_ORGANIZATION_ID}.json`),runtimeBefore=await readFile(runtimeFile),workflowBefore=await readFile(workflowFile),initialSeriesId=`leadership-conversation-series:${fixture.conversationId}`;
    let absentPackSourceReads=0;
    const mutableEnvironment=process.env as Record<string,string|undefined>,nodeEnvironment=mutableEnvironment.NODE_ENV;
    try{
      mutableEnvironment.NODE_ENV="test";
      const absentPackServer=createLeadershipConversationServerCompositionForValidation({runtimeRoot:path.join(root,"runtime"),workflowRoot,sourceContentRoot:path.join(root,"discovery-governed-source-content-northstar-preparation"),lineageFixtureRoot:root,userId:actor,organizationId:identity.organizationId,onProtectedSourceContentRead:()=>{absentPackSourceReads++;}});
      assert.equal(await absentPackServer.readMeetingPack({...identity,seriesId:initialSeriesId}),null,"an authorized absent Meeting Pack resolves before analysis or body reconstruction");
      assert.equal(absentPackSourceReads,0,"an absent Meeting Pack does not read protected source content");
      assert.deepEqual(await readFile(workflowFile),workflowBefore,"an absent Meeting Pack read does not write Product Workflow");
    }finally{nodeEnvironment===undefined?delete mutableEnvironment.NODE_ENV:mutableEnvironment.NODE_ENV=nodeEnvironment;}
    let providerRequests=0;globalThis.fetch=async()=>{providerRequests++;throw new Error("provider access is forbidden in deterministic development validation");};
    const{generateSourceScopedExecutiveAnalysisAction,addMeetingPackPrivateNoteAction,buildMeetingPackAction,saveMeetingPackAction,getMeetingPackAction,getPersonalRoomSheetPreviewAction,freezeOccurrence1Action,captureOccurrence1Action,dispositionOccurrence1CarryForwardAction,closeAndContinueOccurrence1Action}=await import("../../app/product-alpha/leadership-conversation/actions");
    await addMeetingPackPrivateNoteAction({intent:"keep-private",text:"Founder-only Occurrence 1 context."});await addMeetingPackPrivateNoteAction({intent:"talking-points",text:"Ask about the Occurrence 1 owner."});await addMeetingPackPrivateNoteAction({intent:"agenda",text:"Discuss Occurrence 1 launch sequencing."});const[packA,packB]=await Promise.all([buildMeetingPackAction(),buildMeetingPackAction()]);assert.equal(packA.artifactRevision,packB.artifactRevision,"concurrent Occurrence 1 action builds converge without a prior Generate action");assert(!packA.agendaText.includes("Founder-only Occurrence 1 context."));assert(packA.talkingPointsText.includes("Ask about the Occurrence 1 owner."));const workflowAfterBuild=await readFile(workflowFile);
    delete process.env.DISCOVERY_ALPHA_ANALYSIS_TIMEOUT_MS;const ordinary=await generateSourceScopedExecutiveAnalysisAction();process.env.DISCOVERY_ALPHA_ANALYSIS_TIMEOUT_MS="disabled";const stale=await generateSourceScopedExecutiveAnalysisAction(),replay=await generateSourceScopedExecutiveAnalysisAction();
    for(const response of [ordinary,stale,replay]){assert.equal(response.failureCategory,null);assert.equal(response.result.status,"eligible");assertCanonicalResultDigest(response.result);}
    if(ordinary.result.status!=="eligible"||stale.result.status!=="eligible"||replay.result.status!=="eligible")throw new Error("deterministic action result is unavailable");
    assert.equal(sourceScopedStable(ordinary.result),sourceScopedStable(stale.result));assert.equal(sourceScopedStable(stale.result),sourceScopedStable(replay.result));
    for(const key of ["candidateDigest","requestDigest","configurationDigest","sourcePacketDigest"] as const)assert.equal(ordinary.result.candidate[key],stale.result.candidate[key],`${key} ignores stale provider timeout`);
    assert.equal(ordinary.result.resultDigest,stale.result.resultDigest);assert.equal(sourceScopedStable(ordinary.result.candidate.sections),sourceScopedStable(stale.result.candidate.sections));assert.equal(sourceScopedStable(Object.values(ordinary.result.candidate.sections).flat().flatMap(item=>item.citations)),sourceScopedStable(Object.values(stale.result.candidate.sections).flat().flatMap(item=>item.citations)));assert.equal(providerRequests,0);
    assert.deepEqual(await readFile(runtimeFile),runtimeBefore);assert.deepEqual(await readFile(workflowFile),workflowAfterBuild);assert.notDeepEqual(workflowAfterBuild,workflowBefore,"Build persisted only the permitted private notes and drafts");assert.equal(existsSync(path.join(root,"lifecycle")),false);
    const saved=await saveMeetingPackAction({agendaText:`${packA.agendaText}\nFounder edit`,talkingPointsText:`${packA.talkingPointsText}\nPrivate edit`,expectedArtifactRevision:packA.artifactRevision}),reloaded=await getMeetingPackAction();assert(saved&&reloaded);assert.equal(saved.artifactRevision,reloaded.artifactRevision);assert.deepEqual(await readFile(runtimeFile),runtimeBefore,"Occurrence 1 Meeting Pack does not write Runtime");
    const personal=await getPersonalRoomSheetPreviewAction(),prepared=(await server.workspace(identity)).currentPreparedWorkProduct;assert(prepared);await freezeOccurrence1Action({preparedWorkProductVersionId:prepared.artifactVersionId,expectedPersonalRoomSheetDigest:personal.sheet.personalRoomSheetDigest,contributedItemIds:[]});const captured=await captureOccurrence1Action({meetingNotes:"The founder reviewed the bounded meeting result."}),reviewed=captured.proposals.filter(value=>value.reviewedCarryForward);assert(reviewed.length>0);for(const proposal of reviewed)await dispositionOccurrence1CarryForwardAction({proposalId:proposal.proposalId,disposition:"needs-information"});const continued=await closeAndContinueOccurrence1Action();assert.equal(continued.error,null);assert(continued.nextWorkspace&&continued.nextPrepare);const occurrence2Id=continued.nextWorkspace.conversationId,seriesId=continued.nextPrepare.seriesId;assert.notEqual(occurrence2Id,fixture.conversationId);assert.equal(seriesId,`leadership-conversation-series:${fixture.conversationId}`);assert.equal(continued.nextWorkspace.organizationId,identity.organizationId);assert.equal(continued.nextWorkspace.questionId,identity.questionId);
    const occurrence2Analysis=await generateSourceScopedExecutiveAnalysisAction();assert.equal(occurrence2Analysis.result.status,"eligible","Occurrence 2 Generate action uses the recurring series");await addMeetingPackPrivateNoteAction({intent:"keep-private",text:"Founder-only Occurrence 2 context."});await addMeetingPackPrivateNoteAction({intent:"agenda",text:"Discuss the Occurrence 2 evidence gap."});const[o2A,o2B]=await Promise.all([buildMeetingPackAction(),buildMeetingPackAction()]);assert.equal(o2A.artifactRevision,o2B.artifactRevision,"concurrent Occurrence 2 action builds converge");assert.notEqual(o2A.artifactRevision,packA.artifactRevision,"packs are occurrence-bound");assert(!o2A.agendaText.includes("Founder-only Occurrence 1 context."));assert(!o2A.talkingPointsText.includes("Founder-only Occurrence 1 context."));assert(!o2A.agendaText.includes("Founder-only Occurrence 2 context."));assert(o2A.agendaText.includes("Discuss the Occurrence 2 evidence gap."));assert.equal(o2A.inputBasis.priorReviewedOutcomes>0,true);const o2Saved=await saveMeetingPackAction({agendaText:`${o2A.agendaText}\nOccurrence 2 edit`,talkingPointsText:`${o2A.talkingPointsText}\nOccurrence 2 private edit`,expectedArtifactRevision:o2A.artifactRevision}),o2Reloaded=await getMeetingPackAction(),o2Replay=await buildMeetingPackAction();assert(o2Saved&&o2Reloaded);assert.equal(o2Saved.artifactRevision,o2Reloaded.artifactRevision);assert.equal(o2Replay.artifactRevision,o2Saved.artifactRevision);
    const repository=createProductWorkflowArtifactRepository({root:workflowRoot,environment:"development"}),afterPositive=await repository.read(identity.organizationId),o1Headers=(afterPositive.store.meetingPackPublications??[]).filter(value=>value.conversationId===fixture.conversationId&&value.userScopeDigest),o2Headers=(afterPositive.store.meetingPackPublications??[]).filter(value=>value.conversationId===occurrence2Id&&value.seriesId===seriesId);assert.equal(o1Headers.length,2);assert.equal(o2Headers.length,2);assert.notEqual(o1Headers[0]!.artifactId,o2Headers[0]!.artifactId);assert.equal(new Set(o2Headers.map(value=>value.artifactId)).size,1);
    const bodyRoot=path.join(root,"product-artifact-bodies"),sha=(bytes:Uint8Array)=>createHash("sha256").update(bytes).digest("hex"),exactSnapshot=async()=>{const runtimeBytes=await readFile(runtimeFile),workflowBytes=await readFile(workflowFile),paths=(await readdir(bodyRoot,{recursive:true})).map(String).sort(),bodies:Array<{path:string;sha256:string}>=[];for(const relative of paths){try{bodies.push({path:relative,sha256:sha(await readFile(path.join(bodyRoot,relative))) });}catch{}}const runtimeRecord=JSON.parse(runtimeBytes.toString()) as {revision?:unknown;runtime?:{revision?:unknown}},workflowRecord=await repository.read(identity.organizationId);return{workflowSha256:sha(workflowBytes),workflowRevision:workflowRecord.revision,runtimeSha256:sha(runtimeBytes),runtimeRevision:runtimeRecord.revision??runtimeRecord.runtime?.revision??null,bodies};};let protectedArtifactReads=0,protectedSourceReads=0,negativeAttempts=0;(process.env as Record<string,string|undefined>).NODE_ENV="test";const negativeServer=createLeadershipConversationServerCompositionForValidation({runtimeRoot:path.join(root,"runtime"),workflowRoot,sourceContentRoot:path.join(root,"discovery-governed-source-content-northstar-preparation"),lineageFixtureRoot:root,userId:actor,organizationId:identity.organizationId,onProtectedArtifactRead:()=>{protectedArtifactReads++;},onProtectedSourceContentRead:()=>{protectedSourceReads++;}}),assertZeroTransition=async(label:string,work:()=>Promise<unknown>,pattern:RegExp)=>{const before=await exactSnapshot(),artifactReads=protectedArtifactReads,sourceReads=protectedSourceReads;await assert.rejects(work,pattern,label);const after=await exactSnapshot();assert.deepEqual(after,before,`${label} changed durable state`);assert.equal(protectedArtifactReads,artifactReads,`${label} read a protected artifact`);assert.equal(protectedSourceReads,sourceReads,`${label} read protected source content`);negativeAttempts++;},wrongSeries=[`leadership-conversation-series:${occurrence2Id}`,"leadership-conversation-series:unrelated","foreign-organization-series","client-forged-series"];
    for(const forgedSeries of wrongSeries)await assertZeroTransition(`wrong series ${forgedSeries}`,()=>negativeServer.buildMeetingPack({...identity,conversationId:occurrence2Id,seriesId:forgedSeries}),/Meeting Pack is unavailable/);const forgedAction={seriesId:"client-forged-series"};await assertZeroTransition("build extra argument",()=>(buildMeetingPackAction as unknown as (...args:unknown[])=>Promise<unknown>)(forgedAction),/Meeting Pack request is invalid/);await assertZeroTransition("get extra argument",()=>(getMeetingPackAction as unknown as (...args:unknown[])=>Promise<unknown>)(forgedAction),/Meeting Pack request is invalid/);await assertZeroTransition("generate extra argument",()=>(generateSourceScopedExecutiveAnalysisAction as unknown as (...args:unknown[])=>Promise<unknown>)(forgedAction),/Generate analysis request is invalid/);await assertZeroTransition("add forged identity field",()=>(addMeetingPackPrivateNoteAction as unknown as (...args:unknown[])=>Promise<unknown>)({intent:"keep-private",text:"forged",seriesId:"client-forged-series"}),/Private context request is invalid/);await assertZeroTransition("save forged identity field",()=>(saveMeetingPackAction as unknown as (...args:unknown[])=>Promise<unknown>)({agendaText:o2Saved.agendaText,talkingPointsText:o2Saved.talkingPointsText,expectedArtifactRevision:o2Saved.artifactRevision,occurrenceId:"forged"}),/Meeting Pack save request is invalid/);assert.equal(protectedArtifactReads,0);assert.equal(protectedSourceReads,0);
    const child=spawnSync(process.execPath,["--conditions=react-server","--import","tsx",path.join(process.cwd(),"scripts/product/validateChiefMeetingPackFreshProcess.ts"),root,JSON.stringify({runtimeRoot:path.join(root,"runtime"),workflowRoot,sourceContentRoot:path.join(root,"discovery-governed-source-content-northstar-preparation"),lineageFixtureRoot:root,userId:actor,organizationId:identity.organizationId,questionId:identity.questionId,conversationId:occurrence2Id,seriesId})],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_ENV:"test"}});assert.equal(child.status,0,child.stderr);const fresh=JSON.parse(child.stdout);assert.equal(fresh.artifactRevision,o2Saved.artifactRevision);
    assert.equal(providerRequests,0);process.stdout.write(JSON.stringify({validation:"generate-analysis-actual-action-boundary-001",result:"PASS",actionCalls:reviewed.length+21,authReconstruction:"actual",composition:"actual",buildWithoutPriorGenerate:"PASS",requiredStandaloneGenerateClicks:0,ordinaryTimeout:"absent",staleTimeout:"disabled",providerRequests,runtimeWritesFromMeetingPack:0,occurrence1:{seriesId,occurrenceId:fixture.conversationId,artifactId:o1Headers[0]!.artifactId,revisions:o1Headers.length},occurrence2:{seriesId,occurrenceId:occurrence2Id,predecessor:fixture.conversationId,artifactId:o2Headers[0]!.artifactId,revisions:o2Headers.length,priorReviewedOutcomes:o2A.inputBasis.priorReviewedOutcomes},freshProcesses:1,wrongSeriesAttempts:wrongSeries.length,forgedActionArguments:negativeAttempts-wrongSeries.length,independentZeroTransitionSnapshots:negativeAttempts,workflowRuntimeBodyHashComparisons:negativeAttempts,wrongSeriesMeetingPackWrites:0,wrongSeriesProtectedArtifactReads:protectedArtifactReads,wrongSeriesProtectedSourceReads:protectedSourceReads,crossOccurrencePrivateDisclosures:0,replayDuplicates:0,concurrentOccurrence1Build:"converged",concurrentOccurrence2Build:"converged",canonicalResultDigest:"PASS",deterministicReplay:"PASS"}));
  }finally{
    for(const[key,value]of prior)value===undefined?delete process.env[key]:process.env[key]=value;
    for(const[key,value]of priorUnset)value===undefined?delete process.env[key]:process.env[key]=value;
    priorTimeout===undefined?delete process.env.DISCOVERY_ALPHA_ANALYSIS_TIMEOUT_MS:process.env.DISCOVERY_ALPHA_ANALYSIS_TIMEOUT_MS=priorTimeout;globalThis.fetch=priorFetch;
    await rm(root,{recursive:true,force:true});
  }
}
void main();
