import assert from "node:assert/strict";import { chmod,mkdir,mkdtemp,readFile,rm,symlink,utimes,writeFile } from "node:fs/promises";import path from "node:path";import { tmpdir } from "node:os";import { execFile } from "node:child_process";import { promisify } from "node:util";
import { alphaObservationDefaults } from "../../lib/observability/alphaContentSafeObservabilityOwner";import { ALPHA_OBSERVABILITY_SCHEMA_VERSION,alphaBuildCategory } from "../../lib/observability/alphaContentSafeObservabilityContracts";
import { createAlphaTelemetryComposition } from "../../lib/telemetry/alphaTelemetryComposition";import { deriveAlphaTelemetryPseudonym } from "../../lib/telemetry/alphaTelemetryPseudonymization";import { assertClosedFeedback } from "../../lib/telemetry/alphaProductTelemetryContracts";
import { scanRoot,scanText } from "../alpha-readiness/protectedValueScanner";
const keyA=Buffer.alloc(32,1).toString("base64"),keyB=Buffer.alloc(32,2).toString("base64"),org="synthetic-organization",operator="synthetic-operator",DAY=86_400_000;
async function worker(){const root=process.argv[3]!,at=process.argv[4]!,ring={environment:"test",activeVersion:"v2",keys:{v1:keyA,v2:keyB}},c=createAlphaTelemetryComposition({root,ring,now:()=>at})!;await c.ready;const state=await c.repository.read(at);process.stdout.write(`${JSON.stringify({result:"PASS",revision:state.revision,records:state.records.length,primary:Object.keys(state.indexes.primary).length})}\n`);}
async function sweepWorker(){const [root,at,operatorId,organizationId,grantId]=process.argv.slice(3),ring={environment:"test",activeVersion:"v2",keys:{v1:keyA,v2:keyB}},c=createAlphaTelemetryComposition({root,ring,now:()=>at!,startupMaintenance:"none"})!;await c.ready;const pseudonyms=Object.keys(ring.keys).map(version=>deriveAlphaTelemetryPseudonym(ring,"organization",organizationId!,version)),foreignPseudonyms=Object.keys(ring.keys).map(version=>deriveAlphaTelemetryPseudonym(ring,"organization","scoped-foreign",version)),foreignBefore=await c.repository.read(at!,foreignPseudonyms),result=await c.operators.sweep({operatorId:operatorId!,organizationId:organizationId!}),after=await c.repository.read(at!,pseudonyms),foreignAfter=await c.repository.read(at!,foreignPseudonyms);process.stdout.write(`${JSON.stringify({result:"PASS",removed:result.removed,targetRecords:after.records.length,foreignBefore,foreignAfter,audit:after.audits.some(value=>value.operation==="sweep"&&value.outcome==="success"),grantId})}\n`);}
async function main(){const root=await mkdtemp(path.join(tmpdir(),"discovery-ar4-"));let checks=0,nowMs=Date.parse("2026-08-23T12:00:00.000Z"),now=()=>new Date(nowMs).toISOString(),ring={environment:"test",activeVersion:"v2",keys:{v1:keyA,v2:keyB}},c=createAlphaTelemetryComposition({root,ring,now})!;try{await c.ready;checks++;
 const orgA=deriveAlphaTelemetryPseudonym(ring,"organization",org),orgAgain=deriveAlphaTelemetryPseudonym(ring,"organization",org),operatorP=deriveAlphaTelemetryPseudonym(ring,"operator",operator);assert.equal(orgA,orgAgain);assert.notEqual(orgA,operatorP);checks+=3;
 const other=deriveAlphaTelemetryPseudonym({...ring,environment:"development"},"organization",org);assert.notEqual(orgA,other);checks++;
 const grant=await c.operators.issue({operatorId:operator,organizationId:org,scopes:["consent-admin","telemetry-read","telemetry-delete","retention-sweep","zero-verify"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});assert.equal(grant.status,"active");checks++;
 await assert.rejects(()=>c.operators.issue({operatorId:operator,organizationId:org,scopes:["telemetry-read"],validUntil:new Date(nowMs+30*DAY+1).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"}));checks++;
 await assert.rejects(()=>c.operators.issue({operatorId:operator,organizationId:org,scopes:["telemetry-read"],validUntil:new Date(nowMs+20*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"}));checks++;
 assert.equal(await c.consent.current(org),null);checks++;await c.operators.consent({operatorId:operator,organizationId:org,grantId:grant.grantId,writtenConsentProofDigest:"a".repeat(64),validUntil:new Date(nowMs+365*DAY).toISOString(),owner:c.consent});assert.ok(await c.consent.current(org));checks++;
 const event={schemaVersion:ALPHA_OBSERVABILITY_SCHEMA_VERSION,...alphaObservationDefaults,eventCategory:"workflow-transition" as const,workflowStage:"prepare" as const,transitionCategory:"completed" as const,outcomeCategory:"success" as const,buildCategory:alphaBuildCategory(),sequence:1,correlation:"run-1" as const};assert.equal(await c.telemetry.observe(org,event),"persisted");checks++;
 assert.equal((await c.repository.read(now())).records.length,1);checks++;const child=await promisify(execFile)(process.execPath,["--import","tsx",process.argv[1]!,"--worker",root,now()],{env:{...process.env,NODE_ENV:"test",NODE_OPTIONS:"--conditions=react-server"}}),reconstructed=JSON.parse(child.stdout.trim());assert.equal(reconstructed.result,"PASS");assert.equal(reconstructed.records,1);assert.equal(reconstructed.primary,1);checks+=3;nowMs+=90*DAY-1;assert.equal(await c.repository.sweep(now()),0);checks++;nowMs+=1;assert.ok(await c.repository.sweep(now())>=1);assert.equal((await c.repository.read(now())).records.length,0);checks+=2;nowMs+=1;assert.equal((await c.repository.read(now())).records.length,0);checks++;
 nowMs=Date.parse("2026-08-23T12:00:00.000Z");await c.telemetry.feedback(org,{dimension:"usefulness",rating:"helpful"});assert.equal((await c.repository.read(now())).records.length,1);checks++;const deleted=await c.operators.delete({operatorId:operator,organizationId:org,grantId:grant.grantId,owner:c.consent});assert.equal(deleted.outcome,"deleted");const zero=await c.repository.verifyZero([orgA]);assert.equal(zero.payloadRecords+zero.organizationIndexEntries+zero.expiryIndexEntries+zero.feedbackIndexEntries,0);checks+=2;
 assert.equal(await c.telemetry.feedback(org,{dimension:"usefulness",rating:"helpful"}),"disabled");checks++;await assert.rejects(()=>c.operators.read({operatorId:"foreign",organizationId:org}));assert.ok((await c.repository.read(now())).audits.some(v=>v.outcome==="denied"));checks+=2;
 await assert.rejects(()=>c.operators.consent({operatorId:operator,organizationId:org,grantId:grant.grantId,writtenConsentProofDigest:"b".repeat(64),validUntil:new Date(nowMs+365*DAY+1).toISOString(),owner:c.consent}));checks++;
 assert.throws(()=>assertClosedFeedback({dimension:"usefulness",rating:"helpful",text:"forbidden"}));checks++;
 const foreignOrg="synthetic-foreign-organization",foreignGrant=await c.operators.issue({operatorId:operator,organizationId:foreignOrg,scopes:["consent-admin","telemetry-read","telemetry-delete"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await c.operators.consent({operatorId:operator,organizationId:foreignOrg,grantId:foreignGrant.grantId,writtenConsentProofDigest:"c".repeat(64),validUntil:new Date(nowMs+100*DAY).toISOString(),owner:c.consent});assert.equal(await c.telemetry.feedback(foreignOrg,{dimension:"surprise-reduction",rating:"helpful"}),"persisted");checks+=3;
 const rotated=createAlphaTelemetryComposition({root,ring:{...ring,activeVersion:"v1"},now})!;await rotated.ready;assert.equal(await rotated.telemetry.feedback(foreignOrg,{dimension:"understanding-improvement",rating:"somewhat-helpful"}),"persisted");checks++;const stateAfterRotation=await c.repository.read(now());assert.equal(new Set(stateAfterRotation.records.filter(v=>v.kind==="feedback").map(v=>v.keyVersion)).size,2);checks++;
 const missing=createAlphaTelemetryComposition({root,ring:{environment:"test",activeVersion:"v1",keys:{v1:keyA}},now,startupMaintenance:"none"})!;await missing.ready;await assert.rejects(()=>missing.consent.current(foreignOrg),/historical key/);checks+=2;
 await c.operators.revoke({operatorId:operator,organizationId:foreignOrg,grantId:foreignGrant.grantId,issuanceAuthority:"development-telemetry-bootstrap"});await assert.rejects(()=>c.operators.authorize({operatorId:operator,organizationId:foreignOrg,scope:"telemetry-read"}));assert.ok((await c.repository.read(now())).audits.some(value=>value.operation==="revoke"&&value.outcome==="success"));checks+=3;
 const foreignPseudonyms=Object.keys(ring.keys).map(version=>deriveAlphaTelemetryPseudonym(ring,"organization",foreignOrg,version));assert.ok((await c.repository.read(now())).records.some(v=>foreignPseudonyms.includes(v.organizationPseudonym)));checks++;
 const preserveOrg="synthetic-preserve-organization",preserveGrant=await c.operators.issue({operatorId:operator,organizationId:preserveOrg,scopes:["consent-admin","telemetry-delete"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await c.operators.consent({operatorId:operator,organizationId:preserveOrg,grantId:preserveGrant.grantId,writtenConsentProofDigest:"d".repeat(64),validUntil:new Date(nowMs+100*DAY).toISOString(),owner:c.consent});assert.equal(await c.telemetry.feedback(preserveOrg,{dimension:"usefulness",rating:"helpful"}),"persisted");const foreignDeleteGrant=await c.operators.issue({operatorId:operator,organizationId:foreignOrg,scopes:["telemetry-delete"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await c.operators.delete({operatorId:operator,organizationId:foreignOrg,grantId:foreignDeleteGrant.grantId,owner:c.consent});const foreignZero=await c.repository.verifyZero(foreignPseudonyms);assert.equal(foreignZero.payloadRecords+foreignZero.organizationIndexEntries+foreignZero.expiryIndexEntries+foreignZero.feedbackIndexEntries,0);assert.ok((await c.repository.read(now())).records.some(value=>value.organizationPseudonym===deriveAlphaTelemetryPseudonym(ring,"organization",preserveOrg)));const missingDeletionKey=createAlphaTelemetryComposition({root,ring:{environment:"test",activeVersion:"v1",keys:{v1:keyA}},now,startupMaintenance:"none"})!;await missingDeletionKey.ready;await assert.rejects(()=>missingDeletionKey.consent.current(foreignOrg),/historical key/);await assert.rejects(()=>missingDeletionKey.consent.current(preserveOrg),/historical key/);await c.operators.delete({operatorId:operator,organizationId:foreignOrg,grantId:foreignDeleteGrant.grantId,owner:c.consent});checks+=10;
 const raceOrg="synthetic-race-organization",raceGrant=await c.operators.issue({operatorId:operator,organizationId:raceOrg,scopes:["consent-admin","telemetry-delete"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await c.operators.consent({operatorId:operator,organizationId:raceOrg,grantId:raceGrant.grantId,writtenConsentProofDigest:"e".repeat(64),validUntil:new Date(nowMs+100*DAY).toISOString(),owner:c.consent});await Promise.all([c.telemetry.feedback(raceOrg,{dimension:"understanding-improvement",rating:"helpful"}),c.operators.delete({operatorId:operator,organizationId:raceOrg,grantId:raceGrant.grantId,owner:c.consent})]);const racePseudonyms=Object.keys(ring.keys).map(version=>deriveAlphaTelemetryPseudonym(ring,"organization",raceOrg,version)),raceZero=await c.repository.verifyZero(racePseudonyms);assert.equal(raceZero.payloadRecords+raceZero.organizationIndexEntries+raceZero.expiryIndexEntries+raceZero.feedbackIndexEntries,0);checks+=3;
 const append=c.repository.append.bind(c.repository);c.repository.append=async()=>{throw new Error("synthetic sink failure")};assert.equal(await c.telemetry.feedback(preserveOrg,{dimension:"usefulness",rating:"helpful"}),"repository-unavailable");c.repository.append=append;checks++;
 assert.equal(await c.telemetry.observe(foreignOrg,{bad:"metadata"} as never),"disabled");checks++;
 const auditBefore=(await c.repository.read(now())).audits.length;await c.operators.read({operatorId:operator,organizationId:org});await c.operators.read({operatorId:operator,organizationId:org});await c.operators.sweep({operatorId:operator,organizationId:org});await c.operators.verify({operatorId:operator,organizationId:org});const audited=(await c.repository.read(now())).audits.slice(auditBefore);assert.equal(new Set(audited.map(value=>value.auditId)).size,audited.length);assert.ok(audited.every(value=>value.outcome==="success"));checks+=5;
 await c.operators.delete({operatorId:operator,organizationId:org,grantId:grant.grantId,owner:c.consent});checks++;
 const scopedRoot=await mkdtemp(path.join(tmpdir(),"discovery-ar4-scoped-sweep-"));try{let scopedMs=Date.parse("2026-01-01T00:00:00.000Z"),scopedNow=()=>new Date(scopedMs).toISOString(),scoped=createAlphaTelemetryComposition({root:scopedRoot,ring,now:scopedNow,startupMaintenance:"none"})!;await scoped.ready;const target="scoped-target",foreign="scoped-foreign";for(const organizationId of [target,foreign]){const bootstrap=await scoped.operators.issue({operatorId:operator,organizationId,scopes:["consent-admin"],validUntil:new Date(scopedMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await scoped.operators.consent({operatorId:operator,organizationId,grantId:bootstrap.grantId,writtenConsentProofDigest:"f".repeat(64),validUntil:new Date(scopedMs+365*DAY).toISOString(),owner:scoped.consent});await scoped.telemetry.feedback(organizationId,{dimension:"usefulness",rating:"helpful"});}scopedMs+=90*DAY;const sweepGrant=await scoped.operators.issue({operatorId:operator,organizationId:target,scopes:["retention-sweep"],validUntil:new Date(scopedMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"}),swept=await promisify(execFile)(process.execPath,["--import","tsx",process.argv[1]!,"--sweep-worker",scopedRoot,scopedNow(),operator,target,sweepGrant.grantId],{env:{...process.env,NODE_ENV:"test",NODE_OPTIONS:"--conditions=react-server"}}),measured=JSON.parse(swept.stdout.trim());assert.equal(measured.result,"PASS");assert.equal(measured.targetRecords,0);assert.deepEqual(measured.foreignAfter,measured.foreignBefore);assert.equal(measured.audit,true);checks+=4;}finally{await rm(scopedRoot,{recursive:true,force:true});}
 const renewalGrant=await c.operators.issue({operatorId:operator,organizationId:foreignOrg,scopes:["consent-admin"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await c.operators.consent({operatorId:operator,organizationId:foreignOrg,grantId:renewalGrant.grantId,writtenConsentProofDigest:"9".repeat(64),validUntil:new Date(nowMs+100*DAY).toISOString(),owner:c.consent});const missingV1=createAlphaTelemetryComposition({root,ring:{environment:"test",activeVersion:"v2",keys:{v2:keyB}},now,startupMaintenance:"none"})!;await missingV1.ready;await assert.rejects(()=>missingV1.consent.current(foreignOrg),/historical key/);assert.ok(await missingV1.consent.current(preserveOrg));checks+=5;
 const aliasPreserveOrg="synthetic-alias-preserve",aliasPreserveGrant=await c.operators.issue({operatorId:operator,organizationId:aliasPreserveOrg,scopes:["consent-admin","telemetry-delete"],validUntil:new Date(nowMs+30*DAY).toISOString(),issuanceAuthority:"development-telemetry-bootstrap"});await c.operators.consent({operatorId:operator,organizationId:aliasPreserveOrg,grantId:aliasPreserveGrant.grantId,writtenConsentProofDigest:"8".repeat(64),validUntil:new Date(nowMs+100*DAY).toISOString(),owner:c.consent});await c.telemetry.feedback(aliasPreserveOrg,{dimension:"usefulness",rating:"helpful"});await c.operators.delete({operatorId:operator,organizationId:aliasPreserveOrg,grantId:aliasPreserveGrant.grantId,owner:c.consent});const preservePseudonyms=Object.keys(ring.keys).map(version=>deriveAlphaTelemetryPseudonym(ring,"organization",aliasPreserveOrg,version)),aliasRepositoryFile=path.join(root,"alpha-telemetry-v1.json"),preserveDeletionBefore=(JSON.parse(await readFile(aliasRepositoryFile,"utf8")) as import("../../lib/telemetry/alphaProductTelemetryContracts").AlphaTelemetryState).deletions.filter(value=>value.organizationPseudonyms.some(pseudonym=>preservePseudonyms.includes(pseudonym))),priorNowMs=nowMs;assert.equal(preserveDeletionBefore.length,1);nowMs+=91*DAY;await c.repository.sweep(now(),[deriveAlphaTelemetryPseudonym(ring,"organization",foreignOrg,"v2")]);assert.equal((await c.repository.read(now(),foreignPseudonyms)).deletions.length,0);const preserveDeletionAfter=(JSON.parse(await readFile(aliasRepositoryFile,"utf8")) as import("../../lib/telemetry/alphaProductTelemetryContracts").AlphaTelemetryState).deletions.filter(value=>value.organizationPseudonyms.some(pseudonym=>preservePseudonyms.includes(pseudonym)));assert.deepEqual(preserveDeletionAfter,preserveDeletionBefore);nowMs=priorNowMs;checks+=7;
 const scannerValues=[{category:"raw-organization",value:org},{category:"raw-operator",value:operator},{category:"protected-canary",value:"PROTECTED-AR4-CANARY-7f91"}],scan=await scanRoot(root,scannerValues);assert.deepEqual(scan,[]);assert.equal(scanText("sensitivity","PROTECTED-AR4-CANARY-7f91",scannerValues).length,1);assert.deepEqual(scanText("false-positive","ordinary bounded telemetry",scannerValues),[]);checks+=3;
 const repositoryFile=path.join(root,"alpha-telemetry-v1.json"),original=await readFile(repositoryFile,"utf8"),raw=JSON.parse(original);for(const name of ["primary","organization","expiry","feedback","audit"]){const corrupt=structuredClone(raw);corrupt.indexes[name]={};await writeFile(repositoryFile,JSON.stringify(corrupt));await assert.rejects(()=>c.repository.read(now()));await writeFile(repositoryFile,original);checks++;}const unknown=structuredClone(raw);unknown.unexpected={nested:"metadata"};await writeFile(repositoryFile,JSON.stringify(unknown));await assert.rejects(()=>c.repository.read(now()));await writeFile(repositoryFile,original);checks++;
 assert.ok(!original.includes(org)&&!original.includes(operator));checks++;await chmod(repositoryFile,0o644);await assert.rejects(()=>c.repository.read(now()));await chmod(repositoryFile,0o600);const staleLock=`${repositoryFile}.lock`;await mkdir(staleLock);await writeFile(path.join(staleLock,"owner"),JSON.stringify({pid:999999,createdAt:0}),{mode:0o600});const old=new Date(Date.now()-120_000);await utimes(staleLock,old,old);await c.repository.mutate(state=>state);const linkedRoot=path.join(root,"linked-root");await symlink(root,linkedRoot);const linked=createAlphaTelemetryComposition({root:linkedRoot,ring,now})!;await assert.rejects(()=>linked.ready);checks+=3;nowMs=Date.parse("2028-01-01T00:00:00.000Z");await c.consent.expireCompliance();await c.operators.expireCompliance();await c.repository.sweep(now());const expired=await c.repository.read(now());assert.equal(expired.records.length+expired.consents.length+expired.grants.length+expired.audits.length+expired.deletions.length,0);checks+=4;
 }finally{await rm(root,{recursive:true,force:true});await assert.rejects(()=>readFile(path.join(root,"alpha-telemetry-v1.json")));}process.stdout.write(`${JSON.stringify({result:"PASS",checks,cleanup:"PASS",cases:{startupMaintenance:true,retentionBoundaries:["90d-1ms","90d","90d+1ms"],operatorAudits:["read","sweep","zero-verify","denied"],repeatDeletion:true,multiKeyDeletion:true,foreignPreservation:true,concurrentAppendRevocation:true,indexes:["primary","organization","expiry","feedback","audit"],scanner:{findings:0,sensitivity:1,falsePositives:0}}})}\nAR-4 privacy-safe Product telemetry: PASS (${checks} checks; cleanup PASS)\n`);}
(process.argv[2]==="--worker"?worker():process.argv[2]==="--sweep-worker"?sweepWorker():main()).catch(error=>{process.stderr.write(`AR-4 privacy-safe Product telemetry: FAIL ${(error as Error).message}\n`);process.exitCode=1;});
