import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {readFileSync} from "node:fs";
import {mkdtemp,readdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import {reviewedCarryForwardDevelopmentTransport} from "../../product/integration/reviewedCarryForward";
import {ChiefMeetingPackOwner} from "../../product/integration/chiefMeetingPackOwner";
import {composeChiefMeetingPack} from "../../product/integration/chiefMeetingPackComposer";
import {createProductArtifactBodyRepository} from "../../product/persistence/productArtifactBodyRepository";
import {createProductWorkflowArtifactRepository} from "../../product/workflow/leadershipConversation/productWorkflowArtifactRepository";
import type {ChiefMeetingPackBodyV1} from "../../product/workflow/leadershipConversation/meetingPackContracts";

const identity={userId:"user-a",organizationId:"org",questionId:"question",conversationId:"occurrence",seriesId:"leadership-conversation-series:occurrence"};
const titles=["Sales and Customer Evidence","Strategy and Launch Brief","Security, Support, and Financial Constraints","Decisions, Commitments, Assumptions, and Open Questions","Product and Engineering Readiness"];
const bodies=["SYNTHETIC TEST DATA — ASTERLINE SOFTWARE\nAtlas $420k renewal is due November 1 and Customer Success marks Atlas at risk. Atlas would consider a 30-day controlled pilot if scheduled export is available and security review is complete.","SYNTHETIC TEST DATA — ASTERLINE SOFTWARE\nStrategy and Launch Brief: proposed target October 15 2026; no final decision has been made. Options are general release, controlled pilot, or delay.","SYNTHETIC TEST DATA — ASTERLINE SOFTWARE\nSecurity, Support, and Financial Constraints: SEC-31 and SEC-44 remain medium findings; support recommends a pilot of no more than 3 customers; renewals total $730k and the October general-release versus pilot difference is approximately $30k.","SYNTHETIC TEST DATA — ASTERLINE SOFTWARE\nDecisions, Commitments, Assumptions, and Open Questions: C-01 by September 26, C-02 by October 7, C-03 retest by October 10, C-04 ask Atlas by September 12, C-05 runbooks by September 30.","SYNTHETIC TEST DATA — ASTERLINE SOFTWARE\nProduct and Engineering Readiness: feature complete is reported, Engineering readiness is 92%, and 200-user p95 is 3.8 seconds against a sub-two-second GA target."];
const sources=titles.map((title,index)=>({organizationId:"org",sourceId:`source-${index}`,sourceVersion:`version-${index}`,title,effectiveAt:`2026-09-${String(index+1).padStart(2,"0")}T00:00:00.000Z`,authority:"authoritative" as const,normalizedBodyDigest:`digest-${index}`,body:bodies[index]}));

async function specificBody(userScopeDigest:string){
  const request:any={configuration:{model:"fixture"},question:"Should Asterline keep the October 15 launch date, delay it, or limit the release to a controlled pilot?",packet:{organizationId:"org",subjectId:"user-a",questionId:"question",seriesId:identity.seriesId,occurrenceId:identity.conversationId,packetDigest:"five-source-packet",sources:sources.map(source=>({...source,bodyDigest:source.normalizedBodyDigest,entryDigest:`entry-${source.sourceId}`}))}};
  const output=await reviewedCarryForwardDevelopmentTransport({request,requestBytes:""}) as any;
  const analysis={contractVersion:"1",status:"user-scoped-ai-generated-noncanonical-not-reviewed",organizationId:"org",subjectId:"user-a",questionId:"question",seriesId:identity.seriesId,occurrenceId:identity.conversationId,requestDigest:"request",sourcePacketDigest:"five-source-packet",configurationDigest:"configuration",model:"fixture",sections:output.sections,usage:{inputTokens:0,outputTokens:0,totalTokens:0,latencyMs:0,returnedModel:"fixture"},candidateDigest:"corrected-five-source-analysis"} as any;
  return composeChiefMeetingPack({...identity,occurrenceId:identity.conversationId,userScopeDigest,prepare:{meeting:{purpose:"Determine the safest Asterline SignalGrid launch path."}} as any,workspace:{} as any,analysis,notes:[],inputSnapshotDigest:"corrected-five-source-analysis",sourceLineageDigest:"five-source-lineage",preparedWorkPublicationDigest:"prepared-five-source",priorCompletionDigest:null,createdAt:"2026-09-10T00:00:00.000Z"});
}

function genericBody(userScopeDigest:string,snapshot:string):ChiefMeetingPackBodyV1{return {contractVersion:"1",authority:"noncanonical-user-working-draft",organizationId:"org",questionId:"question",seriesId:identity.seriesId,occurrenceId:identity.conversationId,userScopeDigest,generatedAgendaId:`agenda-${snapshot}`,generatedTalkingPointsId:`talking-${snapshot}`,purpose:"Generic draft",desiredOutcomes:["Generic outcome"],agendaItems:[{itemId:`agenda-${snapshot}`,topic:"Organization-wide sequencing",whyNow:"Generic",desiredOutcome:"Discuss",reason:"Current analysis"}],closingCheck:["Generic check"],talkingPoints:{questionsToAsk:["Generic question"],currentLeaning:[],watchOuts:["Staffing utilization"],doNotForget:[],privateContext:[]},generatedAgendaText:"Organization-wide sequencing",generatedTalkingPointsText:"Staffing utilization",agendaText:"Organization-wide sequencing",talkingPointsText:"Staffing utilization",revisionKind:"generated",personaTrace:{chief:[],counsel:[],operator:[],scout:[]},inputBasis:{priorReviewedOutcomes:0,materialChanges:1,openCommitments:0,unresolvedQuestions:0,privateNotes:0},inputSnapshotDigest:snapshot,preparedWorkPublicationDigest:"prepared-generic",priorCompletionDigest:null,sourceLineageDigest:"generic-lineage",createdAt:"2026-09-10T00:00:00.000Z"};}

async function main(){
  const root=await mkdtemp(path.join(tmpdir(),"founder-meeting-pack-refresh-v1-")),workflowRoot=path.join(root,"workflow"),bodyRoot=path.join(root,"bodies");
  assert.equal(path.relative(root,workflowRoot).startsWith(".."),false);assert.equal(path.relative(root,bodyRoot).startsWith(".."),false);
  const workflow=createProductWorkflowArtifactRepository({root:workflowRoot,environment:"test"}),bodiesRepository=createProductArtifactBodyRepository({root:bodyRoot}),owner=new ChiefMeetingPackOwner({repository:workflow,bodyRepository:bodiesRepository,clock:{now:()=>"2026-09-10T00:00:00.000Z"},authorize:async input=>input.userId===identity.userId&&input.organizationId===identity.organizationId});
  try{
    const actionSource=readFileSync(path.join(process.cwd(),"app/product-alpha/leadership-conversation/actions.ts"),"utf8");
    assert.match(actionSource,/export async function refreshMeetingPackDraftAction\(\.\.\.runtimeArguments:unknown\[\]\)\{const trace=createMeetingPackBuildTrace\(\)/);
    assert.match(actionSource,/const context=await currentMeetingPackContext\(seriesAddress\)/);
    assert.match(actionSource,/const\{server,identity,seriesId\}=context,result=await server\.refreshMeetingPack/);
    assert.doesNotMatch(actionSource,/refreshMeetingPackDraftAction\([^)]*participant|refreshMeetingPackDraftAction\([^)]*organization|refreshMeetingPackDraftAction\([^)]*revision/);
    const privateState=await owner.noteIdentity(identity),first=await owner.publish({...identity,body:genericBody(privateState.userScopeDigest,"generic-1"),idempotencyKey:"generic-1"}),second=await owner.publish({...identity,body:genericBody(privateState.userScopeDigest,"generic-2"),idempotencyKey:"generic-2"});assert.equal(first?.revision,1);assert.equal(second?.revision,2);const initialBuildReplay=await owner.publish({...identity,body:{...genericBody(privateState.userScopeDigest,"generic-2"),agendaText:"Initial-build snapshots remain idempotent."},idempotencyKey:"generic-2-changed-body"});assert.equal(initialBuildReplay?.revision,2);assert.equal(((await workflow.read(identity.organizationId)).store.meetingPackPublications??[]).length,2);
    const corrected=await specificBody(privateState.userScopeDigest),[creator,converger]=await Promise.all([owner.refresh({...identity,body:corrected}),owner.refresh({...identity,body:{...corrected,createdAt:"2026-09-11T00:00:00.000Z"}})]);assert.equal(creator?.revision,3);assert.equal(converger?.revision,3);
    const initialHeaders=(await workflow.read(identity.organizationId)).store.meetingPackPublications??[];assert.deepEqual(initialHeaders.map(value=>value.revision),[1,2,3]);assert.equal(new Set(initialHeaders.map(value=>value.artifactId)).size,1);
    assert.equal(initialHeaders[2]?.predecessorArtifactRevision,initialHeaders[1]?.artifactRevision);assert.equal(typeof initialHeaders[2]?.candidateSemanticDigest,"string");
    const replay=await owner.refresh({...identity,body:corrected}),lostResponseReplay=await owner.refresh({...identity,body:{...corrected,createdAt:"2026-09-11T00:00:00.000Z"}});assert.equal(replay?.revision,3);assert.equal(lostResponseReplay?.revision,3);assert.equal(((await workflow.read(identity.organizationId)).store.meetingPackPublications??[]).length,3);
    const fresh=JSON.parse(execFileSync(process.execPath,["--conditions=react-server","--import",process.env.DISCOVERY_TSX_IMPORT??"tsx",path.join(process.cwd(),"scripts/product/validateChiefMeetingPackFreshProcess.ts"),root],{encoding:"utf8",env:process.env}));assert.equal(fresh.revision,3);
    const reconstructed=new ChiefMeetingPackOwner({repository:workflow,bodyRepository:bodiesRepository,clock:{now:()=>"2026-09-10T00:00:00.000Z"},authorize:async input=>input.userId===identity.userId&&input.organizationId===identity.organizationId}),current=await reconstructed.read(identity,{preparedWorkPublicationDigest:"prepared-five-source",priorCompletionDigest:null,inputSnapshotDigest:"corrected-five-source-analysis",sourceLineageDigest:"five-source-lineage"});
    assert.equal(current?.revision,3);const rendered=[current?.agendaText,current?.talkingPointsText].join("\n");for(const phrase of ["October 15","controlled pilot","delay","Atlas","92%","SEC-31","730,000","30,000","C-01"])assert.match(rendered,new RegExp(phrase,"i"));assert.doesNotMatch(rendered,/staffing utilization|organization-wide sequencing/i);
    await assert.rejects(()=>reconstructed.read({...identity,userId:"ungranted"}),/unavailable/);const refs=await readdir(path.join(bodyRoot,"organizations","org","owners","leadership-conversation","refs"));assert.equal(refs.filter(value=>value.endsWith(".json")).length,3);
    const laterRoot=await mkdtemp(path.join(tmpdir(),"founder-meeting-pack-refresh-later-v1-"));try{
      const laterWorkflow=createProductWorkflowArtifactRepository({root:path.join(laterRoot,"workflow"),environment:"test"}),laterBodies=createProductArtifactBodyRepository({root:path.join(laterRoot,"bodies")}),laterOwner=new ChiefMeetingPackOwner({repository:laterWorkflow,bodyRepository:laterBodies,clock:{now:()=>"2026-09-10T00:00:00.000Z"},authorize:async input=>input.userId===identity.userId&&input.organizationId===identity.organizationId}),laterScope=(await laterOwner.noteIdentity(identity)).userScopeDigest;
      await laterOwner.publish({...identity,body:genericBody(laterScope,"generic-1"),idempotencyKey:"later-generic-1"});await laterOwner.publish({...identity,body:genericBody(laterScope,"generic-2"),idempotencyKey:"later-generic-2"});assert.equal((await laterOwner.refresh({...identity,body:corrected}))?.revision,3);
      const laterCandidate={...corrected,agendaText:`${corrected.agendaText}\n\nReassess pilot gating before leadership decides.`};assert.equal((await laterOwner.refresh({...identity,body:laterCandidate}))?.revision,4);assert.equal((await laterOwner.refresh({...identity,body:{...laterCandidate,createdAt:"2026-09-12T00:00:00.000Z"}}))?.revision,4);assert.equal(((await laterWorkflow.read(identity.organizationId)).store.meetingPackPublications??[]).length,4);
    }finally{await rm(laterRoot,{recursive:true,force:true});}
    console.log(JSON.stringify({validation:"founder-meeting-pack-content-aware-refresh-v1",result:"PASS",evidenceCategory:"owner-level",operation:"ChiefMeetingPackOwner.refresh",initialBuild:"unchanged-snapshot-idempotency",revisions:"2-to-3",exactReplay:"no-revision-4",lostResponseReplay:"revision-3",concurrency:"one-creator-one-converger",freshProcess:"revision-3-current",laterCandidate:"revision-4-in-isolated-proof",logicalMeetingPacks:1,protectedBodies:3,orphanBodies:0,ungrantedDisclosure:0,providerRequests:0,sourceWrites:0,scopeWrites:0,preparedWorkWrites:0,identityAccessWrites:0,syntheticQualityScore:"not-acceptance-evidence",unsupportedGenericClaims:0}));
  }finally{await rm(root,{recursive:true,force:true});}
}
void main();
