import assert from "node:assert/strict";
import { createHash } from "node:crypto";

import { CanonicalLocalSourceBindingService } from "../../engine/v3/governance/canonicalLocalSourceBindingService";
import { createCanonicalScopeLineageIndex, createCanonicalScopeLineageIndexV1, createCanonicalScopeTopology } from "../../engine/v3/governance/canonicalScopeLineage";
import { resolveScopedGovernanceContext, type ScopedGovernanceOperation } from "../../engine/v3/governance/scopedGovernanceContext";
import { createEmptyOrganizationRuntime, type OrganizationRuntime } from "../../engine/v3/runtime/organizationRuntime";

const ORG="sandbox-local-binding-001",ACTOR="person:local-binding-validator",QUESTION="product-question:local-binding-001",AT="2026-08-06T12:00:00.000Z",LATER="2026-08-06T13:00:00.000Z",PURPOSE="leadership-conversation-capture" as const;
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`:JSON.stringify(value);
const semanticDigest=(value:unknown)=>sha(stable(value));
const scope={organizationId:ORG,type:"organization" as const,id:ORG};const assertions=[{relationship:"applies-to" as const,scope}];
const topology=createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:AT,nodes:[scope],relationships:[]});
function authorization(operation:ScopedGovernanceOperation,at:string,allowed=true){return resolveScopedGovernanceContext({organizationId:ORG,subjectId:ACTOR,requestedScope:scope,operation,purpose:PURPOSE,sensitivity:"standard",evaluatedAt:at,temporal:{mode:"current"},serverResolvedAuthority:allowed?[{authorityRef:"authority:local-binding",policyRef:"policy:local-binding:v1",organizationId:ORG,subjectId:ACTOR,scope,operations:[operation],sensitivity:["standard"],relationship:"direct",status:"active",validFrom:AT}]:[]});}
let runtime=createEmptyOrganizationRuntime({organizationId:ORG,name:"Local Binding",now:AT});runtime.memory.canonicalScopeLineageIndex=createCanonicalScopeLineageIndex({organizationId:ORG,topology});
let revision="runtime:0",reads=0,replaces=0;
const repository={read:async(id:string)=>{reads++;return id===ORG?{runtime:structuredClone(runtime),bytes:new Uint8Array(),revision}:null;},replace:async(id:string,bytes:Uint8Array,expected:string)=>{assert.equal(id,ORG);assert.equal(expected,revision);replaces++;runtime=JSON.parse(new TextDecoder().decode(bytes)) as OrganizationRuntime;revision=`runtime:${replaces}`;return{runtime:structuredClone(runtime),bytes,revision};}};
let now=AT;const service=new CanonicalLocalSourceBindingService(repository,{now:()=>now});let checks=0;const check=(value:unknown,message:string)=>{assert.ok(value,message);checks++;};const rejects=async(fn:()=>Promise<unknown>)=>{await assert.rejects(fn,/operation denied/);checks++;};
const base={contractVersion:"1" as const,organizationId:ORG,productQuestionId:QUESTION,sourceType:"pasted-text" as const,purposeRef:PURPOSE,normalizedContentDigest:sha("normalized conversation"),requestedScopeAssertions:assertions,sensitivity:"standard" as const,recordedAt:AT,recordedByActorRef:ACTOR,idempotencyKey:"binding:001",expectedRuntimeRevision:"runtime:0",operation:{requestId:"register",operatorId:ACTOR},authorization:authorization("source-binding:register-local",AT)};

async function main(){
  const readsBefore=reads;await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,authorization:authorization("source-binding:register-local",AT,false)}));check(reads===readsBefore,"authorization precedes Runtime read");
  const registered=await service.registerCanonicalLocalSourceBinding(base);check(registered.disposition==="registered"&&registered.bindingVersion===1,"registered v1");check(replaces===1,"one CAS replacement");check(!JSON.stringify(runtime.memory.canonicalScopeLineageIndex).includes("normalized conversation"),"no raw bytes persisted");check(!JSON.stringify(runtime.memory.events).includes(base.idempotencyKey),"raw idempotency key absent");
  const persistedIndex=runtime.memory.canonicalScopeLineageIndex!;assert.equal(persistedIndex.schemaVersion,"2");const {digest:indexDigest,...indexUnsigned}=persistedIndex;check(indexDigest===semanticDigest(indexUnsigned),"independent v2 index digest");const persistedBinding=persistedIndex.sourceBindings[0]!;const {bindingId:_,digest:bindingDigest,...bindingUnsigned}=persistedBinding;check(bindingDigest===semanticDigest(bindingUnsigned),"independent binding digest");check(persistedBinding.bindingId===`source-scope-binding:${ORG}:${persistedBinding.source.sourceId}:v1:${persistedBinding.digest}`,"independent binding identity");const {receiptDigest,...receiptUnsigned}=registered;check(receiptDigest===semanticDigest(receiptUnsigned),"independent receipt digest");check(registered.bindingRevisionId===registered.sourceBindingId,"exact revision identity");
  await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,sourceBindingId:"caller-controlled"} as never));await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,sourceType:"authorized-record"} as never));await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,productQuestionId:""}));
  const replay=await service.registerCanonicalLocalSourceBinding(base);check(JSON.stringify(replay)===JSON.stringify(registered)&&replaces===1,"exact immutable replay without replacement");
  await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,normalizedContentDigest:sha("changed")}));
  now=LATER;const reused=await service.registerCanonicalLocalSourceBinding({...base,recordedAt:LATER,idempotencyKey:"binding:002",expectedRuntimeRevision:revision,operation:{requestId:"reuse",operatorId:ACTOR},authorization:authorization("source-binding:register-local",LATER)});check(reused.disposition==="current-binding-reused"&&reused.sourceBindingId===registered.sourceBindingId,"semantic duplicate reuses current binding");
  const resolved=await service.resolveCanonicalCurrentSourceBinding({contractVersion:"1",organizationId:ORG,productQuestionId:QUESTION,sourceType:"pasted-text",purposeRef:PURPOSE,normalizedContentDigest:base.normalizedContentDigest,requestedScopeAssertions:assertions,sensitivity:"standard",resolvedAt:LATER,authorization:authorization("source-binding:resolve-current",LATER)});check(resolved.binding.bindingId===registered.sourceBindingId&&resolved.topology.topologyId===topology.topologyId,"current resolution uses persisted topology");
  const beforeDenied=reads;await rejects(()=>service.resolveCanonicalCurrentSourceBinding({...{contractVersion:"1" as const,organizationId:ORG,productQuestionId:QUESTION,sourceType:"pasted-text" as const,purposeRef:PURPOSE,normalizedContentDigest:base.normalizedContentDigest,requestedScopeAssertions:assertions,sensitivity:"standard" as const,resolvedAt:LATER},authorization:authorization("source-binding:resolve-current",LATER,false)}));check(reads===beforeDenied,"denied resolution performs zero Runtime reads");const beforeCross=reads;await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,organizationId:"other-organization",recordedAt:LATER,expectedRuntimeRevision:revision,authorization:authorization("source-binding:register-local",LATER)}));check(reads===beforeCross,"cross-organization denial performs zero Runtime reads");
  now="2026-08-06T14:00:00.000Z";const revoked=await service.reviseCanonicalSourceBindingAvailability({...base,availability:"revoked",recordedAt:now,idempotencyKey:"binding:revoke",expectedRuntimeRevision:revision,operation:{requestId:"revoke",operatorId:ACTOR},authorization:authorization("source-binding:revise-availability",now)});check(revoked.disposition==="availability-revised"&&revoked.bindingVersion===2&&revoked.predecessorRevisionId===registered.sourceBindingId,"immutable revocation successor");
  await rejects(()=>service.resolveCanonicalCurrentSourceBinding({contractVersion:"1",organizationId:ORG,productQuestionId:QUESTION,sourceType:"pasted-text",purposeRef:PURPOSE,normalizedContentDigest:base.normalizedContentDigest,requestedScopeAssertions:assertions,sensitivity:"standard",resolvedAt:now,authorization:authorization("source-binding:resolve-current",now)}));
  const staleRevision=revision;now="2026-08-06T15:00:00.000Z";const restored=await service.reviseCanonicalSourceBindingAvailability({...base,availability:"available",recordedAt:now,idempotencyKey:"binding:restore",expectedRuntimeRevision:revision,operation:{requestId:"restore",operatorId:ACTOR},authorization:authorization("source-binding:revise-availability",now)});check(restored.bindingVersion===3&&restored.predecessorRevisionId===revoked.sourceBindingId,"append-only restoration");await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,recordedAt:now,idempotencyKey:"binding:stale",expectedRuntimeRevision:staleRevision,authorization:authorization("source-binding:register-local",now)}));
  const legacy=createEmptyOrganizationRuntime({organizationId:ORG,now:AT});legacy.memory.canonicalScopeLineageIndex=createCanonicalScopeLineageIndexV1({organizationId:ORG,topology});const legacyDigest=legacy.memory.canonicalScopeLineageIndex.digest;runtime=legacy;revision="legacy:0";now=AT;await rejects(()=>service.registerCanonicalLocalSourceBinding({...base,expectedRuntimeRevision:revision}));check(runtime.memory.canonicalScopeLineageIndex?.schemaVersion==="1"&&runtime.memory.canonicalScopeLineageIndex.digest===legacyDigest,"valid v1 remains readable and is not rewritten");
  console.log(JSON.stringify({validation:"canonical-local-source-binding-registration-001",result:"PASS",checks,authorizationBeforeRuntime:true,indexVersion:"2",legacyFailClosed:true,immutableReceipts:true,optimisticConcurrency:true,evidenceCreated:0,cognitionInvocations:0,networkCalls:0,connectorCalls:0,driveReads:0,driveWrites:0,productionAccess:0,deploymentOperations:0}));
}
void main();
