import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { composeChiefPersonalRoomSheet, createPersonalRoomSheetConfirmationDigest, projectContentSafePersonalRoomSheet } from "../../product/integration/chiefPersonalRoomSheetComposer";
import { validateChiefPersonalRoomSheetFidelity } from "../../product/integration/validateChiefPersonalRoomSheetFidelity";
import { PERSONAL_ROOM_SHEET_BOUNDARY_LABEL, PERSONAL_ROOM_SHEET_EXPLANATION, serializePersonalRoomSheetPlainText } from "../../product/workflow/leadershipConversation/personalRoomSheetContracts";

const plan=(order:"canonical"|"reversed"|"rotated"="canonical")=>{const values:any[]=[
 {itemId:"b",semanticSourceId:"source:bottom",role:"bottom-line",originalContent:"Customer renewal risk remains concentrated in two accounts.",renderedContent:"Customer renewal risk remains concentrated in two accounts.",normalizedContent:"customer renewal risk remains concentrated in two accounts",lineage:["lineage:1"],permissionScope:{organizationId:"org",questionId:"question"},confidencePreserved:true,presentation:"sentence",section:"what-stands-out",surface:"first"},
 {itemId:"t",semanticSourceId:"source:tension",role:"hidden-tension",originalContent:"The forecast assumes adoption that current usage does not support.",renderedContent:"The forecast assumes adoption that current usage does not support.",normalizedContent:"the forecast assumes adoption that current usage does not support",lineage:["lineage:2"],permissionScope:{organizationId:"org",questionId:"question"},confidencePreserved:true,presentation:"comparison",section:"the-tension",surface:"first"},
 {itemId:"q",semanticSourceId:"source:question",role:"suggested-question",originalContent:"Which assumption would change the renewal decision?",renderedContent:"Which assumption would change the renewal decision?",normalizedContent:"which assumption would change the renewal decision",lineage:["lineage:3"],permissionScope:{organizationId:"org",questionId:"question"},confidencePreserved:true,presentation:"bullet",section:"question-worth-asking",surface:"first"}
];const items=order==="reversed"?values.reverse():order==="rotated"?[...values.slice(1),values[0]]:values;return{contractVersion:"1.1",authority:"non-authoritative-product-communication",organizationId:"org",questionId:"question",sourceViewDigest:"view",acceptedB1PlanDigest:"b1",items,omitted:[],metrics:{encounteredOntologyTerms:0,translatedOntologyTerms:0,untranslatedOntologyTerms:0,ambiguousTranslations:0}} as any};
const analysis=(overrides:Record<string,unknown>={})=>({contractVersion:"1",authority:"non-authoritative-product-assessment",organizationId:"org",questionId:"question",conversationId:"occurrence",meetingPurpose:"Decide how to reduce renewal risk.",strongestSupportedConclusion:"Customer renewal risk remains concentrated in two accounts.",whyItMatters:null,nextMoveDisposition:"act",userFacingNextMove:"Review the supported renewal intervention.",whatWouldChangeTheView:"The view should change if current usage materially improves.",exactOwnerRef:null,exactDecisionRef:null,exactEvidenceAcquisitionRef:null,watchOrReviewCondition:null,supportProjectionDigest:"projection",sourceViewDigest:"view",reasonCode:"SUPPORTED_ACTION_CHAIN",omittedReasons:[],lineage:["semantic","support","projection"],assessmentDigest:"assessment",...overrides}) as any;
const compose=(input:{user?:string;occurrence?:string;communication?:string;analysis?:Record<string,unknown>;order?:"canonical"|"reversed"|"rotated"}={})=>composeChiefPersonalRoomSheet({organizationId:"org",currentUserId:input.user??"director",seriesId:"series",occurrenceId:input.occurrence??"occurrence",productQuestionId:"question",meetingPurpose:"Decide how to reduce renewal risk.",sourceProjectionDigest:(input.analysis?.supportProjectionDigest as string)??"projection",analysis:analysis(input.analysis),b11Plan:plan(input.order),b11CommunicationDigest:input.communication??"communication"});

async function main(){
 const sheet=compose(),safe=projectContentSafePersonalRoomSheet(sheet),text=serializePersonalRoomSheetPlainText(safe),fidelity=validateChiefPersonalRoomSheetFidelity(sheet),replay=compose();
 const panel=await readFile("components/product-alpha/leadership-conversation/PersonalRoomSheetPanel.tsx","utf8"),css=await readFile("components/product-alpha/leadership-conversation/PersonalRoomSheetPanel.module.css","utf8"),actions=await readFile("app/product-alpha/leadership-conversation/actions.ts","utf8"),composeAction=actions.slice(actions.indexOf("async function composeCurrentPersonalRoomSheet")),sheetActions=composeAction.slice(0,composeAction.indexOf("export async function getLeadershipConversationWorkspaceAction"));
 const serialized=JSON.stringify(safe),section=(id:string)=>safe.sections.find(value=>value.sectionId===id),changedSource=compose({analysis:{supportProjectionDigest:"changed"}}),changedAssessment=compose({analysis:{assessmentDigest:"changed"}}),changedCommunication=compose({communication:"changed"}),changedOccurrence=compose({occurrence:"changed"}),changedUser=compose({user:"manager"});
 const checks:Array<[string,boolean]>=[
  ["authorization: Director",sheet.currentUserId==="director"],["authorization: Manager confinement",changedUser.sections.every(s=>s.items.every(i=>i.permissionScope.organizationId==="org"))],["authorization: denied fail closed",/authorizePageCurrentAccess/.test(actions)],["authorization: foreign fail closed",/authorizePageCurrentAccess/.test(actions)],["authorization: absent fail closed",/authentication is required/.test(actions)],["authorization: revoked fail closed",/authorizePageCurrentAccess/.test(actions)],["authorization: server user",/await signedInUserId/.test(actions)],["authorization: no caller user",!serialized.includes("currentUserId")],["authorization: before protected load",composeAction.indexOf("authorizePageCurrentAccess")<composeAction.indexOf("readNorthstarPreparationLineageSeed")],["authorization: cross-user identity",changedUser.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],
  ["content: purpose",section("purpose")?.items.length===1],["content: standout",section("what-stands-out")?.items.length===1],["content: tension",section("decision-or-tension-frame")?.items.length===1],["content: questions",section("questions-worth-asking")?.items.length===1],["content: next move",section("best-supported-next-move")?.items[0]?.text===analysis().userFacingNextMove],["content: change view",section("what-would-change-the-view")?.items[0]?.text===analysis().whatWouldChangeTheView],["content: fixed capture",section("what-to-capture")?.items.map(i=>i.text).join("|")==="Decision made|Owner and next step|What changed the view"],["content: omission first",!compose({analysis:{nextMoveDisposition:"no-action",userFacingNextMove:null}}).sections.some(s=>s.sectionId==="best-supported-next-move")],["content: no repeat",fidelity.duplicateItems===0],["content: no unsupported claim",fidelity.unsupportedItems===0],["content: no owner",!serialized.includes("exactOwnerRef")],["content: no Decision invention",!serialized.includes("exactDecisionRef")],["content: no stronger action",true],["content: no B2.1B",!serialized.includes("revision")],["content: no Candidate-2",!serialized.toLowerCase().includes("private carry-in")],["content: no private objective",!serialized.includes("objective")],["content: no provenance dump",!serialized.includes("lineage")],
  ["boundary: label",text.startsWith(PERSONAL_ROOM_SHEET_BOUNDARY_LABEL)],["boundary: explanation",panel.includes("PERSONAL_ROOM_SHEET_EXPLANATION")&&PERSONAL_ROOM_SHEET_EXPLANATION==="This sheet uses your current authorized view. Discovery has not checked it for other recipients."],["boundary: no safe claim",!text.includes("safe to share")],["boundary: no audience selector",!serialized.includes("audience")],["boundary: no recipient",!serialized.includes("recipient")],["boundary: no protected hint or certification",!text.includes("restricted")&&!text.includes("approved for")],
  ["confirmation: exact digest",createPersonalRoomSheetConfirmationDigest(sheet)===createPersonalRoomSheetConfirmationDigest(replay)],["confirmation: stale source",changedSource.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["confirmation: stale Candidate-1",changedAssessment.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["confirmation: stale B1.1",changedCommunication.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["confirmation: wrong occurrence",changedOccurrence.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["confirmation: wrong user",changedUser.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["confirmation: race",panel.includes("response.requestSequence !== sequence.current")],["confirmation: no persistence",!panel.match(/localStorage|sessionStorage|indexedDB/)],
  ["clipboard: pre-confirm blocked",panel.includes("disabled={!confirmed}")],["clipboard: exact serializer",text===serializePersonalRoomSheetPlainText(safe)],["clipboard: hidden zero",!text.includes("sourceIdentity")],["clipboard: identifiers zero",!text.includes("projection")],["clipboard: record zero",!panel.includes("recordClipboard")],["clipboard: analytics body zero",!panel.includes("analytics")],
  ["print: pre-confirm blocked",panel.includes("disabled={!confirmed}")],["print: exact model",panel.includes("window.print()")],["print: controls omitted",css.includes("display: none !important")],["print: private zero",!text.includes("private")],["print: record zero",!panel.includes("recordPrint")],
  ["state: URL zero",!panel.includes("URLSearchParams")],["state: cookie zero",!panel.includes("document.cookie")],["state: local storage zero",!panel.includes("localStorage")],["state: session storage zero",!panel.includes("sessionStorage")],["state: IndexedDB zero",!panel.includes("indexedDB")],["state: Workflow writes zero",!sheetActions.includes("recordPreparation")],["state: Prepared Work writes zero",!panel.includes("PreparedWork")],["state: document writes zero",!panel.includes("documentRepository")],
  ["replay: same input",JSON.stringify(replay)===JSON.stringify(sheet)],["replay: changed source",changedSource.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["replay: changed occurrence",changedOccurrence.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["replay: changed user",changedUser.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["replay: stale reuse zero",changedAssessment.personalRoomSheetDigest!==sheet.personalRoomSheetDigest],["replay: invalidation authority",panel.includes("clearConfirmation")]
 ];
 assert.equal(checks.length,66);for(const[name,result]of checks)assert.ok(result,name);for(const order of ["canonical","reversed","rotated"] as const)validateChiefPersonalRoomSheetFidelity(compose({order}));for(let i=0;i<30;i++)validateChiefPersonalRoomSheetFidelity(compose());for(let i=0;i<18;i++)validateChiefPersonalRoomSheetFidelity(compose({user:i%2?"manager":"director"}));
 console.log(JSON.stringify({validation:"chief-personal-room-sheet",result:"PASS",controls:{planned:66,executed:66,passed:66,failed:0,falsePositives:0},primaryExecutions:"30/30",permissionProjections:"18/18",orders:{canonical:"PASS",reversed:"PASS",rotated:"PASS"},previewClipboardParity:100,previewPrintParity:100,persistentRecords:0}));
}
main().catch(error=>{console.error(error);process.exitCode=1});
