import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createCanonicalScopeTopology, createCanonicalSourceScopeBinding, type CanonicalSourceScopeBinding } from "../../engine/v3/governance/canonicalScopeLineage";
import { resolveScopedGovernanceContext, type ScopedGovernanceOperation } from "../../engine/v3/governance/scopedGovernanceContext";
import { createFilesystemSourceContentRepository, decodeAndNormalizeSourceContent, GovernedSourceContentService, sourceContentDigest } from "../../engine/v3/sources";
import { SourceScopedExecutiveAnalysisOwner } from "../../product/integration/sourceScopedExecutiveAnalysis";
import { deterministicSourceScopedFakeTransport } from "../../lib/analysis/runSourceScopedFrontierAnalysis";

const ORG="sandbox-source-restoration-001",ACTOR="person:source-provisioner",PURPOSE="leadership-conversation-capture",AT="2026-09-06T12:00:00.000Z";
const BODY=new TextEncoder().encode("Product sequencing depends on resolving the interface contract before implementation. The unresolved contract is delaying the next release decision. Leadership should assign an owner and confirm the interface this week.\n");
const CORRUPT_BODY=new TextEncoder().encode("Corrupt target body.\n"),UNRELATED_BODY=new TextEncoder().encode("Unrelated retained source.\n");
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const topology=createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:AT,nodes:[{organizationId:ORG,type:"organization",id:ORG}],relationships:[]});
function binding(label:string,bytes:Uint8Array):CanonicalSourceScopeBinding{const normalized=decodeAndNormalizeSourceContent(bytes).normalizedText;return createCanonicalSourceScopeBinding({organizationId:ORG,bindingVersion:1,source:{sourceId:`local:${label}`,sourceVersion:"1",normalizedContentDigest:sha(new TextEncoder().encode(normalized))},topology,assertions:[{relationship:"applies-to",scope:{organizationId:ORG,type:"organization",id:ORG}}],basisRefs:[`purpose:${PURPOSE}`],effectiveAt:AT,sourceType:"plain-text-upload",purposeRef:PURPOSE,availability:"available"});}
const primary=binding("restoration-primary",BODY),corrupt=binding("restoration-corrupt",CORRUPT_BODY),unrelated=binding("restoration-unrelated",UNRELATED_BODY);
function context(operation:ScopedGovernanceOperation,granted=true,organizationId=ORG){return resolveScopedGovernanceContext({organizationId,subjectId:ACTOR,requestedScope:{organizationId,type:"organization",id:organizationId},operation,purpose:PURPOSE,sensitivity:"standard",evaluatedAt:AT,temporal:{mode:"current"},serverResolvedAuthority:granted?[{authorityRef:"authority:source-provisioner",policyRef:"policy:source-provisioner:v1",organizationId,subjectId:ACTOR,scope:{organizationId,type:"organization",id:organizationId},operations:[operation],sensitivity:["standard"],relationship:"direct",status:"active",validFrom:AT}]:[]});}

async function main(){
  const root=await mkdtemp(path.join(tmpdir(),"discovery-governed-source-content-restoration-"));let checks=0,repositoryRestorationCalls=0;
  const ok=(value:unknown,message:string)=>{assert.ok(value,message);checks++;},rejects=async(work:()=>Promise<unknown>,message:string)=>{await assert.rejects(work);checks++;ok(true,message);};
  try{
    const mechanical=createFilesystemSourceContentRepository({root,environment:"test"}),histories=new Map([[primary.bindingId,[primary]],[corrupt.bindingId,[corrupt]],[unrelated.bindingId,[unrelated]]] as const);
    const repository={inspectRevision:(id:string)=>mechanical.inspectRevision(id),write:(input:Parameters<typeof mechanical.write>[0])=>mechanical.write(input),read:(org:string,id:string)=>mechanical.read(org,id),resolveExactMetadata:(org:string,bindingId:string,digest:string)=>mechanical.resolveExactMetadata!(org,bindingId,digest),restoreMissingBody:(input:Parameters<NonNullable<typeof mechanical.restoreMissingBody>>[0])=>{repositoryRestorationCalls++;return mechanical.restoreMissingBody!(input);},resetDevelopmentFixture:(id:string)=>mechanical.resetDevelopmentFixture(id)};
    const service=new GovernedSourceContentService(repository,{loadRevisions:async({sourceBindingId})=>histories.get(sourceBindingId)??[]},{now:()=>AT});
    const write=async(item:CanonicalSourceScopeBinding,bytes:Uint8Array,key:string)=>service.write({contractVersion:"1",organizationId:ORG,sourceBindingId:item.bindingId,purposeRef:PURPOSE,mediaType:"text/plain",bytes,storedAt:AT,storedByActorRef:ACTOR,idempotencyKey:key,expectedRepositoryRevision:await mechanical.inspectRevision(ORG),authorization:context("source-content:write")});
    const primaryVersion=await write(primary,BODY,"restore:primary"),corruptVersion=await write(corrupt,CORRUPT_BODY,"restore:corrupt"),unrelatedVersion=await write(unrelated,UNRELATED_BODY,"restore:unrelated");
    const organizationRoot=path.join(root,"organizations",ORG),manifestPath=path.join(organizationRoot,"manifest.json"),blob=(digest:string)=>path.join(organizationRoot,"blobs",`${digest}.blob`);
    const manifestBefore=await readFile(manifestPath),manifest=JSON.parse(manifestBefore.toString()) as {versions:unknown[]},unrelatedBefore=await readFile(blob(unrelatedVersion.exactContentDigest));
    await rm(blob(primaryVersion.exactContentDigest));
    const baseRequest={contractVersion:"1" as const,organizationId:ORG,sourceBindingId:primary.bindingId,sourceContentVersionId:primaryVersion.sourceContentVersionId,purposeRef:PURPOSE,bytes:BODY,restoredByActorRef:ACTOR,authorization:context("source-content:write")};
    await rejects(()=>service.restoreMissingBody({...baseRequest,bytes:new Uint8Array(BODY.subarray(0,BODY.byteLength-1))}),"wrong length rejected");
    await rejects(()=>service.restoreMissingBody({...baseRequest,bytes:new TextEncoder().encode("x".repeat(BODY.byteLength))}),"wrong digest rejected");
    await assert.rejects(()=>stat(blob(primaryVersion.exactContentDigest)));checks++;
    const callsBeforeUnauthorized=repositoryRestorationCalls;
    await rejects(()=>service.restoreMissingBody({...baseRequest,authorization:context("source-content:write",false)}),"unauthorized rejected before repository");
    await rejects(()=>service.restoreMissingBody({...baseRequest,authorization:context("source-content:write",true,"foreign-organization")}),"foreign organization rejected before repository");
    await rejects(()=>service.restoreMissingBody({...baseRequest,sourceBindingId:"source-binding:absent"}),"absent source rejected before repository");
    ok(repositoryRestorationCalls===callsBeforeUnauthorized,"negative identity and authority cases disclose nothing to repository");
    const restored=await service.restoreMissingBody(baseRequest);ok(restored.disposition==="restored","exact missing body restored once");ok(restored.sourceContentVersionId===primaryVersion.sourceContentVersionId,"source version identity unchanged");ok(restored.exactContentDigest===primaryVersion.exactContentDigest&&restored.byteLength===BODY.byteLength,"restored metadata exact");
    const restoredBytes=await readFile(blob(primaryVersion.exactContentDigest));ok(sha(restoredBytes)===primaryVersion.exactContentDigest&&restoredBytes.byteLength===BODY.byteLength,"restored physical body exact");
    const restoredState=await stat(blob(primaryVersion.exactContentDigest)),replay=await service.restoreMissingBody(baseRequest),replayState=await stat(blob(primaryVersion.exactContentDigest));ok(replay.disposition==="already-present","exact replay converges");ok(replayState.mtimeMs===restoredState.mtimeMs,"exact replay writes no body");
    const existingState=await stat(blob(unrelatedVersion.exactContentDigest)),existing=await service.restoreMissingBody({...baseRequest,sourceBindingId:unrelated.bindingId,sourceContentVersionId:unrelatedVersion.sourceContentVersionId,bytes:UNRELATED_BODY}),existingAfter=await stat(blob(unrelatedVersion.exactContentDigest));ok(existing.disposition==="already-present"&&existingState.mtimeMs===existingAfter.mtimeMs,"existing valid body is not overwritten");
    await writeFile(blob(corruptVersion.exactContentDigest),new TextEncoder().encode("tampered"),{mode:0o600});const corruptBefore=await readFile(blob(corruptVersion.exactContentDigest));await rejects(()=>service.restoreMissingBody({...baseRequest,sourceBindingId:corrupt.bindingId,sourceContentVersionId:corruptVersion.sourceContentVersionId,bytes:CORRUPT_BODY}),"existing corrupt body rejected");ok(Buffer.from(await readFile(blob(corruptVersion.exactContentDigest))).equals(corruptBefore),"corrupt body not overwritten");
    const read=await service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:primary.bindingId,sourceContentVersionId:primaryVersion.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-claim-support")});ok(Buffer.from(read.bytes).equals(Buffer.from(BODY)),"normal owner read resolves restored body");
    const normalizedRestored=decodeAndNormalizeSourceContent(read.bytes).normalizedText;ok(sha(normalizedRestored)===primary.source.normalizedContentDigest,"restored normalized digest remains binding-exact");
    const analysis=new SourceScopedExecutiveAnalysisOwner({providerFamily:"deterministic-development",model:"gpt-5.6-sol",authorizeDesignatedPrincipal:async()=>true,selectCurrentPrepareSources:async()=>[{organizationId:ORG,sourceId:primary.bindingId,sourceVersion:primaryVersion.sourceContentVersionId,title:"Restored source",effectiveAt:AT,authority:"authoritative",normalizedBodyDigest:sha(normalizedRestored)}],resolveCurrentAccess:async()=>({disposition:"eligible",accessDigest:"restoration-access"}),readProtectedBody:async()=>normalizedRestored,transport:deterministicSourceScopedFakeTransport});
    const analyzed=await analysis.analyze({subjectId:ACTOR,organizationId:ORG,questionId:"product-question:restoration",seriesId:"series:restoration",occurrenceId:"occurrence:restoration",question:"What should leadership focus on now?"});ok(analyzed.status==="eligible",`source-scoped analysis reads restored isolated body (${analysis.unavailableReason()??"eligible"})`);
    ok(Buffer.from(await readFile(manifestPath)).equals(manifestBefore),"manifest remains byte-identical");ok((JSON.parse((await readFile(manifestPath)).toString()) as {versions:unknown[]}).versions.length===manifest.versions.length,"no source version created");ok(Buffer.from(await readFile(blob(unrelatedVersion.exactContentDigest))).equals(unrelatedBefore),"unrelated body byte-identical");
    console.log(JSON.stringify({validation:"governed-source-body-restoration-v1",result:"PASS",checks,exactMissingBodyRestorations:1,exactReplayBodyWrites:0,manifestMutations:0,newSourceVersions:0,validExistingBodiesOverwritten:0,corruptExistingBodiesOverwritten:0,wrongDigestRestorationsAccepted:0,wrongLengthRestorationsAccepted:0,foreignOrUnauthorizedRestorationsAccepted:0,unrelatedBodyChanges:0,publicClientEndpointsAdded:0,providerRequests:0,newOwnersOrPersistenceFamilies:0,newArchitectureFindings:0,sourceScopedAnalysisReadRegression:analyzed.status}));
  }finally{await rm(root,{recursive:true,force:true});}
}
void main();
