import assert from "node:assert/strict";
import { mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { createProductArtifactBodyRepository } from "../../product/persistence/productArtifactBodyRepository";
import { createProductWorkflowArtifactRepository } from "../../product/workflow/leadershipConversation/productWorkflowArtifactRepository";
import { ChiefMeetingPackOwner, ChiefMeetingPackRevisionConflictError } from "../../product/integration/chiefMeetingPackOwner";
import { chiefMeetingPackInputSnapshotDigest, composeChiefMeetingPack } from "../../product/integration/chiefMeetingPackComposer";
import type { SourceScopedCandidateV1, SourceScopedSectionsV1 } from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import type { ChiefFirstPrepareViewV1, LeadershipConversationWorkspaceV1 } from "../../product/workflow/leadershipConversation";
import { reconcileMeetingPackDraftBuffers } from "../../product/workflow/leadershipConversation/meetingPackContracts";

async function main(){
const root=await mkdtemp(path.join(tmpdir(),"chief-meeting-pack-v1-")),workflow=createProductWorkflowArtifactRepository({root:path.join(root,"workflow"),environment:"test"}),bodyRepository=createProductArtifactBodyRepository({root:path.join(root,"bodies")}),now="2026-09-02T12:00:00.000Z",authorized=new Set(["user-a","user-b"]),owner=new ChiefMeetingPackOwner({repository:workflow,bodyRepository,clock:{now:()=>now},authorize:async input=>authorized.has(input.userId)&&input.organizationId==="org"}),base={organizationId:"org",questionId:"question",conversationId:"occurrence",seriesId:"leadership-conversation-series:occurrence"},a={...base,userId:"user-a"},b={...base,userId:"user-b"};
const item=(statement:string)=>({statement,citations:[{sourceId:"source",sourceVersion:"v1",bodyDigest:"a".repeat(64),sourcePacketDigest:"packet"}],factCheck:"PASS" as const}),empty=()=>[] as ReturnType<typeof item>[];
const sections:SourceScopedSectionsV1={whatMattersNow:[item("Release coordination is the leading current explanation.")],whyItMatters:[item("Coordination delays affect delivery.")],competingExplanations:[item("Staffing may still contribute.")],whatChanged:[item("Interface latency improved.")],decisions:[item("Decide whether to change the release sequence.")],notDecided:empty(),commitments:[item("Confirm an owner for release readiness.")],openQuestions:[item("Which dependency remains unresolved?")],contradictions:[item("The staffing account conflicts with rework evidence.")],evidenceUncertainty:[item("Customer impact evidence is missing.")],modelUncertainty:empty(),organizationalDisagreement:empty(),attention:[item("Keep ownership explicit.")],whatWouldChangeAssessment:[item("Matched delivery evidence would change the view.")]};
const candidate={sections,candidateDigest:"candidate"} as SourceScopedCandidateV1,prepare={meeting:{purpose:"Resolve the delivery constraint."},priorCycle:{status:"none"}} as ChiefFirstPrepareViewV1,workspace={reviewedCarryForwardCompletion:null} as unknown as LeadershipConversationWorkspaceV1;
try{
  assert.equal(await owner.read(a),null,"analysis-not-yet / pack-absent");
  await owner.addPrivateNote({...a,intent:"keep-private",text:"Founder-only concern.",idempotencyKey:"note-private"});
  await owner.addPrivateNote({...a,intent:"talking-points",text:"Ask about the partner dependency.",idempotencyKey:"note-talking"});
  await owner.addPrivateNote({...a,intent:"agenda",text:"Discuss the launch sequence.",idempotencyKey:"note-agenda"});
  const state=await owner.noteIdentity(a),inputSnapshotDigest=chiefMeetingPackInputSnapshotDigest({...base,occurrenceId:base.conversationId,userScopeDigest:state.userScopeDigest,preparedWorkPublicationDigest:"publication",analysisDigest:"candidate",priorCompletionDigest:null,notes:state.notes.map(note=>({noteId:note.noteId,noteRevisionId:note.noteRevisionId,intent:note.intent}))}),packBody=composeChiefMeetingPack({...base,occurrenceId:base.conversationId,userScopeDigest:state.userScopeDigest,prepare,workspace,analysis:candidate,notes:state.notes,inputSnapshotDigest,sourceLineageDigest:"lineage",preparedWorkPublicationDigest:"publication",priorCompletionDigest:null,createdAt:now});
  assert(!packBody.agendaText.includes("Founder-only concern."));assert(!packBody.agendaText.includes("Ask about the partner dependency."));assert(packBody.agendaText.includes("Discuss the launch sequence."));assert(!packBody.agendaText.includes("Changed since last time"),"first occurrence makes no prior-change claim");assert.equal(packBody.inputBasis.priorReviewedOutcomes,0);assert(packBody.talkingPointsText.includes("Ask about the partner dependency."));assert(!packBody.talkingPointsText.includes("Founder-only concern."));
  const[first,replay]=await Promise.all([owner.publish({...a,body:packBody,idempotencyKey:`build:${inputSnapshotDigest}`}),owner.publish({...a,body:packBody,idempotencyKey:`build:${inputSnapshotDigest}`})]);assert(first);assert.equal(replay?.artifactRevision,first?.artifactRevision,"actual concurrent build CAS convergence");
  assert.equal(await owner.read(b),null,"cross-user private isolation");
  const revised=await owner.revise({...a,agendaText:`${first!.agendaText}\nUser agenda edit`,talkingPointsText:`${first!.talkingPointsText}\nUser private edit`,expectedArtifactRevision:first!.artifactRevision,idempotencyKey:"revise-1"});assert.equal(revised?.revision,2);assert(revised?.agendaText.includes("User agenda edit"));
  const reconstructedOwner=new ChiefMeetingPackOwner({repository:workflow,bodyRepository,clock:{now:()=>now},authorize:async input=>authorized.has(input.userId)&&input.organizationId==="org"}),fresh=await reconstructedOwner.read(a,{preparedWorkPublicationDigest:"publication",priorCompletionDigest:null});assert.equal(fresh?.artifactRevision,revised?.artifactRevision,"fresh-process reconstruction");
  const child=JSON.parse(execFileSync(process.execPath,["--conditions=react-server","--import","tsx",path.join(process.cwd(),"scripts/product/validateChiefMeetingPackFreshProcess.ts"),root],{encoding:"utf8"}));assert.equal(child.artifactRevision,revised?.artifactRevision,"true child-process reconstruction");
  const replayRevision=await reconstructedOwner.revise({...a,agendaText:revised!.agendaText,talkingPointsText:revised!.talkingPointsText,expectedArtifactRevision:first!.artifactRevision,idempotencyKey:"revise-1"});assert.equal(replayRevision?.artifactRevision,revised?.artifactRevision,"exact save replay");
  await assert.rejects(()=>owner.revise({...a,agendaText:"conflict",talkingPointsText:"conflict",expectedArtifactRevision:first!.artifactRevision,idempotencyKey:"revise-conflict"}),ChiefMeetingPackRevisionConflictError);
  const stale=await owner.read(a,{preparedWorkPublicationDigest:"changed-input",priorCompletionDigest:null});assert.equal(stale?.potentiallyOutOfDate,true);assert(stale?.agendaText.includes("User agenda edit"));
  assert.deepEqual(reconcileMeetingPackDraftBuffers({agendaText:"unsaved agenda",talkingPointsText:"unsaved talking"},stale,true),{agendaText:"unsaved agenda",talkingPointsText:"unsaved talking"},"saving a note preserves both dirty buffers");
  await owner.addPrivateNote({...b,intent:"keep-private",text:"User B only.",idempotencyKey:"note-b"});const bState=await owner.noteIdentity(b),bDigest=chiefMeetingPackInputSnapshotDigest({...base,occurrenceId:base.conversationId,userScopeDigest:bState.userScopeDigest,preparedWorkPublicationDigest:"publication",analysisDigest:"candidate",priorCompletionDigest:null,notes:bState.notes.map(note=>({noteId:note.noteId,noteRevisionId:note.noteRevisionId,intent:note.intent}))}),bBody=composeChiefMeetingPack({...base,occurrenceId:base.conversationId,userScopeDigest:bState.userScopeDigest,prepare,workspace,analysis:candidate,notes:bState.notes,inputSnapshotDigest:bDigest,sourceLineageDigest:"lineage",preparedWorkPublicationDigest:"publication",priorCompletionDigest:null,createdAt:now}),bPack=await owner.publish({...b,body:bBody,idempotencyKey:`build:${bDigest}`});assert(bPack);assert.notEqual(bPack.artifactRevision,revised?.artifactRevision);assert(!bPack.talkingPointsText.includes("Founder-only concern."));assert(!revised?.talkingPointsText.includes("User B only."));
  const occurrence2=composeChiefMeetingPack({organizationId:base.organizationId,questionId:base.questionId,seriesId:base.seriesId,occurrenceId:"occurrence-2",userScopeDigest:state.userScopeDigest,prepare,workspace,analysis:candidate,notes:[],inputSnapshotDigest:"occurrence-2-snapshot",sourceLineageDigest:"lineage-2",preparedWorkPublicationDigest:"publication-2",priorCompletionDigest:"closure-1",priorReviewedItems:["Approved prior decision."],priorMaterialChanges:["Approved understanding changed."],createdAt:now});assert.equal(occurrence2.inputBasis.priorReviewedOutcomes,1);assert(occurrence2.agendaText.includes("Approved understanding changed."));assert(occurrence2.talkingPointsText.includes("Approved prior decision."));assert(!occurrence2.agendaText.includes("Rejected claim"));
  const a2={...a,conversationId:"occurrence-2"},b2={...b,conversationId:"occurrence-2"};await owner.addPrivateNote({...a2,intent:"talking-points",text:"User A Occurrence 2 only.",idempotencyKey:"note-a-o2"});await owner.addPrivateNote({...b2,intent:"keep-private",text:"User B Occurrence 2 only.",idempotencyKey:"note-b-o2"});const buildO2=async(input:typeof a2)=>{const privateState=await owner.noteIdentity(input),digest=chiefMeetingPackInputSnapshotDigest({organizationId:input.organizationId,questionId:input.questionId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest:privateState.userScopeDigest,preparedWorkPublicationDigest:"publication-2",analysisDigest:"candidate",priorCompletionDigest:"closure-1",notes:privateState.notes.map(note=>({noteId:note.noteId,noteRevisionId:note.noteRevisionId,intent:note.intent}))}),body=composeChiefMeetingPack({organizationId:input.organizationId,questionId:input.questionId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest:privateState.userScopeDigest,prepare,workspace,analysis:candidate,notes:privateState.notes,inputSnapshotDigest:digest,sourceLineageDigest:"lineage-2",preparedWorkPublicationDigest:"publication-2",priorCompletionDigest:"closure-1",priorReviewedItems:["Approved prior decision."],priorMaterialChanges:["Approved understanding changed."],createdAt:now});return owner.publish({...input,body,idempotencyKey:`build:${digest}`});},a2Pack=await buildO2(a2),b2Pack=await buildO2(b2);assert(a2Pack&&b2Pack);assert.notEqual(a2Pack.artifactRevision,b2Pack.artifactRevision,"two users receive distinct private Occurrence 2 artifacts");assert(a2Pack.talkingPointsText.includes("User A Occurrence 2 only."));assert(!a2Pack.talkingPointsText.includes("User B Occurrence 2 only."));assert(!b2Pack.talkingPointsText.includes("User A Occurrence 2 only."));assert(!a2Pack.talkingPointsText.includes("Founder-only concern."));assert(!b2Pack.talkingPointsText.includes("User B only."),"Occurrence 1 private context does not carry forward");assert(!a2Pack.agendaText.includes("User A Occurrence 2 only."));assert(!b2Pack.agendaText.includes("User B Occurrence 2 only."));await assert.rejects(()=>owner.revise({...b2,agendaText:a2Pack.agendaText,talkingPointsText:a2Pack.talkingPointsText,expectedArtifactRevision:a2Pack.artifactRevision,idempotencyKey:"cross-user-edit"}),ChiefMeetingPackRevisionConflictError);
  authorized.delete("user-a");await assert.rejects(()=>owner.read(a),/unavailable/);authorized.add("user-a");assert.equal(await owner.read({...a,conversationId:"wrong",seriesId:"leadership-conversation-series:wrong"}),null,"wrong occurrence discloses nothing");
  const stored=(await workflow.read("org")).store;assert.equal(stored.meetingPackPublications?.length,5);assert.equal(stored.meetingPackPrivateNotePublications?.length,6);assert.equal(stored.proposals.length+stored.dispositions.length+stored.canonicalRoutingReceipts.length+(stored.cycle1ClosureCompletions?.length??0)+(stored.reviewedCarryForwardCompletions?.length??0),0,"canonical review lifecycle writes");const bodyRoot=path.join(root,"bodies/organizations/org/owners/leadership-conversation"),physicalBodyRefs=(await readdir(path.join(bodyRoot,"refs"))).filter(value=>value.endsWith(".json")).length,physicalBlobs=(await readdir(path.join(bodyRoot,"blobs"))).filter(value=>value.endsWith(".blob")).length;assert.equal(physicalBodyRefs,11,"every durable private publication has exactly one protected-body ref");assert.equal(physicalBlobs,11,"no losing-CAS body orphan or duplicate blob");
  console.log(JSON.stringify({result:"PASS",scenarios:18,freshProcesses:1,concurrentBuildConvergence:"actual Promise.all CAS convergence",users:2,occurrences:2,twoUserOccurrence2Builds:2,crossUserOccurrence2EditDenials:1,meetingPackPublications:5,privateNotePublications:6,physicalBodyRefs,physicalBlobs,orphanBodyRefs:0,orphanBlobs:0,providerRequests:0,canonicalWrites:0,reviewPromotionWrites:0,lifecycleWrites:0,crossUserPrivateDisclosures:0,crossOccurrencePrivateDisclosures:0,privateAgendaLeaks:0,duplicateAgendaDrafts:0,duplicateTalkingPointDrafts:0,duplicateUserRevisions:0}));
}finally{await rm(root,{recursive:true,force:true});}}
void main();
