import assert from "node:assert/strict";
import { mkdtemp, readFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { CanonicalLocalSourceBindingService } from "../../engine/v3/governance/canonicalLocalSourceBindingService";
import { createCanonicalDerivedScopeLineage, lineageSupportsRequestedScope, readCanonicalScopeLineageTopology } from "../../engine/v3/governance/canonicalScopeLineage";
import { resolveScopedGovernanceContext, type GovernedScopeRef } from "../../engine/v3/governance/scopedGovernanceContext";
import { FilesystemOrganizationRuntimeRepository } from "../../engine/v3/runtime/organizationRuntimeRepository";
import { runDiscoveryV3 } from "../../engine/v3";
import { decodeAndNormalizeSourceContent, sourceContentDigest } from "../../engine/v3/sources/sourceContentDeterminism";
import { SANDBOX_ORGANIZATION_ID } from "../../product/simulations/living-organization-sandbox/manifest";
import { NORTHSTAR_SCOPES } from "../../product/simulations/living-organization-sandbox/sourceScopeBindings";
import { provisionNorthstarPreparationLineageFixture, resetNorthstarPreparationLineageFixture } from "../../product/simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";

let checks=0;const check=(value:unknown,message:string)=>{assert.ok(value,message);checks+=1;};
const AT="2026-02-02T09:00:00.000Z",ACTOR="person:northstar-preparation-lineage-fixture",PURPOSE="leadership-conversation-capture" as const,scope={organizationId:SANDBOX_ORGANIZATION_ID,type:"organization" as const,id:SANDBOX_ORGANIZATION_ID};
const auth=(operation:"source-binding:register-local"|"source-binding:resolve-current"|"source-binding:revise-availability",requestedScope:GovernedScopeRef=scope)=>resolveScopedGovernanceContext({organizationId:SANDBOX_ORGANIZATION_ID,subjectId:ACTOR,requestedScope,operation,purpose:PURPOSE,sensitivity:"standard",evaluatedAt:AT,temporal:{mode:"current"},serverResolvedAuthority:[{authorityRef:"authority:northstar-preparation-lineage-fixture",policyRef:"policy:northstar-preparation-lineage-fixture:v1",organizationId:SANDBOX_ORGANIZATION_ID,subjectId:ACTOR,scope:requestedScope,operations:[operation],sensitivity:["standard"],relationship:"direct",status:"active",validFrom:"2026-01-05T09:00:00.000Z"}]});

async function child(root:string){const result=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});console.log(JSON.stringify({seed:result.seed,runtimeRevision:result.runtimeRevision,disposition:result.disposition}));}
async function main(){
  if(process.argv[2]==="--child"){await child(process.argv[3]!);return;}
  const root=await mkdtemp(path.join(tmpdir(),"discovery-northstar-preparation-lineage-"));
  const first=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});
  check(first.disposition==="provisioned","first run provisions");check(first.counts.sources===5,"frozen source set exact");check(first.counts.material>0&&first.counts.understandings>0,"canonical material and Understanding exist");check(first.seed.sourceBindings.length===first.seed.sourceContentVersions.length,"lineage complete");check(first.seed.canonicalMaterial.length===first.counts.material,"owner admissions retained");check(first.seed.sourceBindings.every(item=>item.sourceBindingId===item.bindingRevisionId),"owner binding revisions retained");check(Boolean(first.seed.canonicalUnderstandingRevision&&first.seed.projectionSourceRef),"canonical projection basis retained");check(!JSON.stringify(first.seed).includes("northstar-runtime:824a4c2e"),"Runtime alias absent");check(!JSON.stringify(first.seed).includes("company-overview.md"),"paths absent");check(!Object.keys(first.seed).some(key=>/prepared|body|eligib|authoriz|projectionMembership/i.test(key)),"seed excludes downstream authority and artifact state");
  const second=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});check(second.disposition==="idempotent-replay","replay explicit");assert.deepEqual(second.seed,first.seed);checks+=1;check(second.runtimeRevision===first.runtimeRevision,"replay no mutation");
  const fresh=spawnSync(process.execPath,["--conditions=react-server","--import","tsx",process.argv[1]!,"--child",root],{cwd:process.cwd(),encoding:"utf8",env:{NODE_ENV:"test",PATH:process.env.PATH??"",...(process.env.TMPDIR?{TMPDIR:process.env.TMPDIR}:{})}});assert.equal(fresh.status,0,fresh.stderr);const freshResult=JSON.parse(fresh.stdout.trim().split("\n").at(-1)!);assert.deepEqual(freshResult.seed,first.seed);checks+=1;check(freshResult.runtimeRevision===first.runtimeRevision&&freshResult.disposition==="idempotent-replay","fresh-process replay exact");
  const repository=new FilesystemOrganizationRuntimeRepository(path.join(root,"runtime"));const stored=await repository.read(SANDBOX_ORGANIZATION_ID);assert.ok(stored?.runtime.memory.canonicalScopeLineageIndex);const index=stored.runtime.memory.canonicalScopeLineageIndex,topology=readCanonicalScopeLineageTopology(index);assert.ok(topology);check(index.evidenceAttributions.length>0&&index.derivedLineages.length>0,"persisted admission and derived lineage reload");check(index.derivedLineages.some(item=>lineageSupportsRequestedScope(item,scope)),"direct lineage resolves");
  const binding=index.sourceBindings[0]!;const service=new CanonicalLocalSourceBindingService(repository,{now:()=>AT});await assert.rejects(()=>service.registerCanonicalLocalSourceBinding({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:"markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:"0".repeat(64),requestedScopeAssertions:[{relationship:"applies-to",scope}],sensitivity:"standard",recordedAt:AT,recordedByActorRef:ACTOR,idempotencyKey:"northstar-preparation-binding:foundation-overview:v1",expectedRuntimeRevision:stored.revision,operation:{requestId:"collision",operatorId:ACTOR},authorization:auth("source-binding:register-local")}),/denied/);checks+=1;
  const revoked=await service.reviseCanonicalSourceBindingAvailability({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:binding.sourceType as "markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:binding.source.normalizedContentDigest,requestedScopeAssertions:binding.assertions,sensitivity:"standard",availability:"revoked",recordedAt:AT,recordedByActorRef:ACTOR,idempotencyKey:"northstar-preparation-revoke:v1",expectedRuntimeRevision:stored.revision,operation:{requestId:"revoke",operatorId:ACTOR},authorization:auth("source-binding:revise-availability")});check(revoked.availability==="revoked","canonical direct revocation owner used");await assert.rejects(()=>service.resolveCanonicalCurrentSourceBinding({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:binding.sourceType as "markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:binding.source.normalizedContentDigest,requestedScopeAssertions:binding.assertions,sensitivity:"standard",resolvedAt:AT,authorization:auth("source-binding:resolve-current")}),/denied/);checks+=1;
  const inheritedScope=NORTHSTAR_SCOPES.platformDelivery;
  const inheritedBytes=new Uint8Array(await readFile(path.join(process.cwd(),"product/simulations/living-organization-sandbox/corpus/batch-1/capacity-summary.md")));
  const inheritedNormalized=decodeAndNormalizeSourceContent(inheritedBytes);
  const inheritedDigest=sourceContentDigest(new TextEncoder().encode(inheritedNormalized.normalizedText));
  let currentStored=(await repository.read(SANDBOX_ORGANIZATION_ID))!;
  const inheritedReceipt=await service.registerCanonicalLocalSourceBinding({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:"markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:inheritedDigest,requestedScopeAssertions:[{relationship:"applies-to",scope:inheritedScope}],sensitivity:"standard",recordedAt:AT,recordedByActorRef:ACTOR,idempotencyKey:"northstar-preparation-inherited-binding:v1",expectedRuntimeRevision:currentStored.revision,operation:{requestId:"register-inherited",operatorId:ACTOR},authorization:auth("source-binding:register-local",inheritedScope)});
  const inheritedResolved=await service.resolveCanonicalCurrentSourceBinding({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:"markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:inheritedDigest,requestedScopeAssertions:[{relationship:"applies-to",scope:inheritedScope}],sensitivity:"standard",resolvedAt:AT,authorization:auth("source-binding:resolve-current",inheritedScope)});
  check(inheritedResolved.binding.bindingId===inheritedReceipt.sourceBindingId,"owner-backed inherited binding resolves");
  const inheritedRun=runDiscoveryV3({company:"Northstar",website:"https://sandbox.invalid",industry:"Industrial automation implementation",question:"Why are customer implementations taking longer?",context:"",evidenceSources:[{sourceId:inheritedResolved.binding.source.sourceId,sourceType:"upload",observedAt:AT,contentDigest:inheritedDigest,content:inheritedNormalized.normalizedText}]},{organizationId:SANDBOX_ORGANIZATION_ID,effectiveAt:AT,topologyRevisions:[inheritedResolved.topology],sourceBindingRevisions:[inheritedResolved.binding]});const inheritedAttribution=inheritedRun.scopeLineageAdmission!.evidenceAttributions[0]!,inheritedLineage=createCanonicalDerivedScopeLineage({organizationId:SANDBOX_ORGANIZATION_ID,derivedObjectRef:"validator:inherited-lineage-control",supportingEvidenceIds:[inheritedAttribution.evidenceId],attributions:[inheritedAttribution],topology:inheritedResolved.topology,effectiveAt:AT});check(lineageSupportsRequestedScope(inheritedLineage,inheritedScope),"topology-derived inherited lineage resolves");
  currentStored=(await repository.read(SANDBOX_ORGANIZATION_ID))!;
  const inheritedRevoked=await service.reviseCanonicalSourceBindingAvailability({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:"markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:inheritedDigest,requestedScopeAssertions:[{relationship:"applies-to",scope:inheritedScope}],sensitivity:"standard",availability:"revoked",recordedAt:AT,recordedByActorRef:ACTOR,idempotencyKey:"northstar-preparation-inherited-revoke:v1",expectedRuntimeRevision:currentStored.revision,operation:{requestId:"revoke-inherited",operatorId:ACTOR},authorization:auth("source-binding:revise-availability",inheritedScope)});check(inheritedRevoked.availability==="revoked","canonical inherited revocation owner used");await assert.rejects(()=>service.resolveCanonicalCurrentSourceBinding({contractVersion:"1",organizationId:SANDBOX_ORGANIZATION_ID,productQuestionId:first.seed.productQuestionId,sourceType:"markdown-upload",purposeRef:PURPOSE,normalizedContentDigest:inheritedDigest,requestedScopeAssertions:[{relationship:"applies-to",scope:inheritedScope}],sensitivity:"standard",resolvedAt:AT,authorization:auth("source-binding:resolve-current",inheritedScope)}),/denied/);checks+=1;
  await assert.rejects(()=>provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root}),/denied|unavailable|eligible/);checks+=1;
  await assert.rejects(()=>provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:process.cwd()}),/fixture boundary/);checks+=1;await resetNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});await assert.rejects(()=>stat(root),/ENOENT/);checks+=1;
  console.log(JSON.stringify({result:"PASS",validation:"northstar-preparation-lineage-fixture-provisioning-001",checks,sourceCount:first.counts.sources,materialCount:first.counts.material,understandingCount:first.counts.understandings,replay:"fresh-process-idempotent",lineage:{direct:true,inherited:true},revocation:{direct:"withheld",inherited:"withheld"},reset:"bounded",runtimeDigestAlias:"absent",externalActivity:{network:0,database:0,connector:0,drive:0,clerk:0,production:0,deployment:0}}));
}
void main();
