import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { access,mkdtemp,readFile,realpath,rm,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { runDiscoveryV3 } from "../../engine/v3";
import { createCanonicalScopeTopology,createCanonicalSourceScopeBinding } from "../../engine/v3/governance/canonicalScopeLineage";
import { evolveOrganizationRuntime } from "../../engine/v3/runtime/evolveOrganizationRuntime";
import { createEmptyOrganizationRuntime } from "../../engine/v3/runtime/organizationRuntime";
import { atlasIndustrialArtifacts } from "../../engine/benchmark/judgment-lab/atlasIndustrialPilot";
import { createDurableProductQuestion } from "../../product/questions/questionLifecycle";
const ORG="canonical-material-origin-fresh-process",QUESTION="product-question:material-origin-fresh-process",SOURCE="governed-source:material-origin-fresh-process",AT="2026-08-07T12:00:00.000Z";
const roles=["build-governed-evidence-input","run-governed-cognition-and-admission","reload-verify-material-lineage","legacy-and-tamper-controls"] as const;type Role=typeof roles[number];const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
function fixture(content:string){const scope={organizationId:ORG,type:"organization" as const,id:ORG},topology=createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:AT,nodes:[scope],relationships:[]}),binding=createCanonicalSourceScopeBinding({organizationId:ORG,bindingVersion:1,source:{sourceId:SOURCE,sourceVersion:"1",normalizedContentDigest:sha(content)},topology,assertions:[{relationship:"origin",scope}],basisRefs:[QUESTION,"purpose:fresh-process"],effectiveAt:AT,sourceType:"manual-takeaway",purposeRef:QUESTION,availability:"available"}),input={company:"Fresh Framing",website:"https://framing.invalid",industry:"Framing",question:"What is supported?",context:"",evidenceSources:[{sourceId:SOURCE,sourceType:"paste",observedAt:AT,contentDigest:binding.source.normalizedContentDigest,content}]},lineage={organizationId:ORG,effectiveAt:AT,topologyRevisions:[topology],sourceBindingRevisions:[binding],existingEvidenceAttributions:[]};return{input,lineage};}
async function child(role:Role,root:string){const canonicalRoot=await realpath(root),canonicalTmp=await realpath(tmpdir());assert.ok(canonicalRoot.startsWith(path.join(canonicalTmp,"discovery-material-origin-")));const inputPath=path.join(root,"input.json"),runtimePath=path.join(root,"runtime.json"),safePath=path.join(root,"safe.json");
 if(role==="build-governed-evidence-input"){const content=atlasIndustrialArtifacts.map(item=>item.content).join("\n\n");let runtime=createEmptyOrganizationRuntime({organizationId:ORG,name:"Fresh",now:AT});runtime=createDurableProductQuestion({runtime,title:"What is supported?",questionId:QUESTION,createdAt:AT}).runtime;await writeFile(inputPath,JSON.stringify({content}),{mode:0o600});await writeFile(runtimePath,JSON.stringify(runtime),{mode:0o600});return{role,result:"PASS",inputDigest:sha(content),runtimeDigest:sha(JSON.stringify(runtime))};}
 const {content}=JSON.parse(await readFile(inputPath,"utf8")) as {content:string};const {input,lineage}=fixture(content);
 if(role==="run-governed-cognition-and-admission"){const runtime=JSON.parse(await readFile(runtimePath,"utf8")),result=runDiscoveryV3(input,lineage),evidenceIds=result.evidence.map(item=>item.id),admissionIds=result.scopeLineageAdmission!.operationBatch.admissions.flatMap(item=>item.investigationEvidenceIds).sort();assert.equal(evidenceIds.length,16);assert.deepEqual([...evidenceIds].sort(),admissionIds);const original=console.log;let evolved;try{console.log=()=>{};evolved=evolveOrganizationRuntime({runtime,result,input,semanticTime:AT});}finally{console.log=original;}const safe={evidenceIds,admissionIds,batchDigest:result.scopeLineageAdmission!.operationBatch.batchDigest,explanationIds:(evolved.memory.organizationalExplanations??[]).map(item=>item.id),compositionIds:(evolved.memory.organizationalUnderstandingState.canonicalCompositions??[]).map(item=>[item.id,item.revisionId])};await writeFile(runtimePath,JSON.stringify(evolved),{mode:0o600});await writeFile(safePath,JSON.stringify(safe),{mode:0o600});return{role,result:"PASS",governedEvidenceCount:16,admissionCount:16,framingCount:0,batchDigest:safe.batchDigest};}
 if(role==="reload-verify-material-lineage"){const runtime=JSON.parse(await readFile(runtimePath,"utf8")),safe=JSON.parse(await readFile(safePath,"utf8")) as {admissionIds:string[];explanationIds:string[];compositionIds:string[][];batchDigest:string},material=[...new Set((runtime.memory.organizationalExplanations??[]).flatMap((item:{evidenceIds?:string[];comparativeEvidenceRoles?:Array<{evidenceId:string}>})=>[...(item.evidenceIds??[]),...(item.comparativeEvidenceRoles??[]).map(role=>role.evidenceId)]))] as string[];assert.ok(material.length>0&&material.every(id=>safe.admissionIds.includes(id)));assert.ok(material.every(id=>!["E1","E2","E3","E4","E5"].includes(id)));return{role,result:"PASS",materialCount:material.length,missingCount:0,framingCount:0,explanationDigest:sha(JSON.stringify(safe.explanationIds)),compositionDigest:sha(JSON.stringify(safe.compositionIds)),batchDigest:safe.batchDigest};}
 const before=sha(await readFile(runtimePath)),legacy=runDiscoveryV3(input),governed=runDiscoveryV3(input,lineage);assert.equal(legacy.evidence.length,21);assert.equal(governed.evidence.length,16);assert.throws(()=>runDiscoveryV3({...input,evidenceSources:[{...input.evidenceSources[0],sourceId:"",contentDigest:""}]},lineage),/source provenance/i);assert.throws(()=>runDiscoveryV3(input,{...lineage,sourceBindingRevisions:[]}),/admission/i);assert.equal(sha(await readFile(runtimePath)),before);return{role,result:"PASS",legacyCount:21,governedCount:16,partialPersistence:false,runtimeDigest:before};}
function execute(role:Role,root:string){const run=spawnSync(process.execPath,["--import","tsx",new URL(import.meta.url).pathname,"--role",role,root],{shell:false,encoding:"utf8",timeout:30000,maxBuffer:128*1024,env:{NODE_ENV:"test",PATH:process.env.PATH??"",TMPDIR:tmpdir()}});assert.equal(run.status,0,`${role}: ${run.stderr.slice(0,500)}`);const lines=run.stdout.trim().split("\n").filter(Boolean);assert.equal(lines.length,1);const output=JSON.parse(lines[0]!);assert.equal(output.role,role);assert.equal(output.result,"PASS");return output;}
async function parent(){const runs=[];for(let i=0;i<2;i+=1){const root=await mkdtemp(path.join(tmpdir(),"discovery-material-origin-"));try{runs.push(roles.map(role=>execute(role,root)).map(({runtimeDigest:_r,...rest})=>rest));}finally{await rm(root,{recursive:true,force:true});await assert.rejects(access(root));}}assert.deepEqual(runs[0],runs[1]);console.log(JSON.stringify({result:"PASS",processes:8,runs:2,roles,identicalBoundedOutputs:true,temporaryRootsRemoved:true,externalActivity:{network:0,connector:0,drive:0,production:0}}));}
const args=process.argv.slice(2);(args[0]==="--role"?child(args[1] as Role,args[2]!).then(value=>console.log(JSON.stringify(value))):parent()).catch(error=>{console.error(error instanceof Error?error.message:"validation failed");process.exitCode=1;});
