import assert from "node:assert/strict";

import { createCanonicalScopeTopology } from "../../engine/v3/governance/canonicalScopeLineage";
import {
  FIELD_AUDIENCE_OPERATION, FIELD_AUDIENCE_PURPOSE, FIELD_AUDIENCE_RESOURCE,
  authorizeNewFieldAudienceRequirementIssuance, canonicalFieldAudienceJson,
  createExactFieldAudienceRequirement, createFieldAudienceAdministrativeAuthority,
  createFieldAudienceFamilyPolicy, createFieldAudienceRequirementApproval,
  deriveFieldAudienceApprovalPolicy, fieldAudienceDigest, issueFieldAudienceRequirement,
  resolveCurrentFieldAudienceRequirement, validateAuthorizedFieldAudienceRequirementIssuance,
  validateFieldAudienceIssuanceReceipt, type AuthorizedFieldAudienceRequirementIssuance,
  type ExactFieldAudienceRequirement, type FieldAudienceAdministrativeAuthority,
  type FieldAudienceFamilyPolicy, type FieldAudienceIssuanceReceipt,
  type FieldAudienceRequirementApproval, type FieldAudienceTarget,
} from "../../engine/v3/governance/fieldAudienceRequirement";
import type { GovernedScopeRef } from "../../engine/v3/governance/scopedGovernanceContext";

const ORG="direct-security-test-organization", OTHER="other-organization";
const NOW="2026-08-05T20:00:00.000Z", LATER="2026-09-05T20:00:00.000Z";
const scope=(type:GovernedScopeRef["type"],id:string,organizationId=ORG):GovernedScopeRef=>({organizationId,type,id});
const root=scope("organization",ORG),fn=scope("function","engineering"),team=scope("team","platform"),initiative=scope("initiative","northstar");
const topology=(reverse=false)=>createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:NOW,nodes:[root,fn,team,initiative],relationships:(reverse?[{kind:"initiative-relates" as const,from:initiative,to:team},{kind:"contains" as const,from:fn,to:team},{kind:"contains" as const,from:root,to:fn}]:[{kind:"contains" as const,from:root,to:fn},{kind:"contains" as const,from:fn,to:team},{kind:"initiative-relates" as const,from:initiative,to:team}])});
const authority=(principalId:string,over:Partial<Parameters<typeof createFieldAudienceAdministrativeAuthority>[0]>={}):FieldAudienceAdministrativeAuthority=>createFieldAudienceAdministrativeAuthority({revision:1,organizationId:ORG,principalId,capability:"manage-field-audience-requirements",state:"active",effectiveAt:NOW,expiresAt:null,supersedesRevisionId:null,issuerAuthorityRef:"direct-security-validator",...over});
const issuer=authority("principal:issuer"),approver=authority("principal:approver"),authorities=[issuer,approver];
const target=(id:string,over:Partial<FieldAudienceTarget>={}):FieldAudienceTarget=>({organizationId:ORG,objectKind:"canonical-understanding-composition",objectId:`composition:${id}`,objectRevision:"composition-revision:1",fieldFamily:"composition-claim",fieldPath:"composition-claim.text",...over});
const policy=(over:Partial<FieldAudienceFamilyPolicy>&{authorities?:readonly FieldAudienceAdministrativeAuthority[];asOf?:string}={}):FieldAudienceFamilyPolicy=>createFieldAudienceFamilyPolicy({revision:1,organizationId:ORG,resourceFamily:FIELD_AUDIENCE_RESOURCE,operation:FIELD_AUDIENCE_OPERATION,purpose:FIELD_AUDIENCE_PURPOSE,fieldFamily:"composition-claim",fieldPath:"composition-claim.text",policyVersion:"policy:1",disposition:"classified",requirements:[[fn]],state:"active",effectiveAt:NOW,supersedesRevisionId:null,issuerAuthorityRevisionId:issuer.revisionId,authorities,asOf:NOW,...over});
const exact=(value:FieldAudienceTarget,requirements=[[team]] as GovernedScopeRef[][],over:Partial<ExactFieldAudienceRequirement>&{authorities?:readonly FieldAudienceAdministrativeAuthority[];asOf?:string}={}):ExactFieldAudienceRequirement=>createExactFieldAudienceRequirement({revision:1,organizationId:ORG,resourceFamily:FIELD_AUDIENCE_RESOURCE,operation:FIELD_AUDIENCE_OPERATION,purpose:FIELD_AUDIENCE_PURPOSE,fieldFamily:value.fieldFamily,target:value,overridePolicyVersion:"policy:1",disposition:"classified",requirements,state:"active",effectiveAt:NOW,supersedesRevisionId:null,issuerAuthorityRevisionId:issuer.revisionId,authorities,asOf:NOW,...over});
const approval=(proposal:FieldAudienceFamilyPolicy|ExactFieldAudienceRequirement,admin=issuer,over:Partial<FieldAudienceRequirementApproval>={}):FieldAudienceRequirementApproval=>createFieldAudienceRequirementApproval({organizationId:proposal.organizationId,requirementKind:proposal.kind,proposalId:proposal.proposalId,proposalRevisionId:proposal.proposalRevisionId,proposalDigest:proposal.proposalDigest,target:proposal.kind==="exact-field-audience-requirement"?proposal.target:null,fieldFamily:proposal.fieldFamily,fieldPath:proposal.kind==="exact-field-audience-requirement"?proposal.target.fieldPath:proposal.fieldPath,approvingPrincipalId:admin.principalId,authorityId:admin.authorityId,authorityRevisionId:admin.revisionId,decision:"approved",effectiveAt:NOW,proposal,authority:admin,...over});
const authorize=(proposal:FieldAudienceFamilyPolicy|ExactFieldAudienceRequirement,governing:FieldAudienceFamilyPolicy|null,approvals:FieldAudienceRequirementApproval[],administrativeAuthorities=authorities,asOf=NOW)=>authorizeNewFieldAudienceRequirementIssuance({proposal,governingFamilyPolicy:governing,approvals,currentAdministrativeAuthorities:administrativeAuthorities,currentRequirementState:[proposal],topology:topology(),issuingPrincipalId:issuer.principalId,issuingAuthorityRevisionId:issuer.revisionId,asOf});
const issue=(authorization:AuthorizedFieldAudienceRequirementIssuance,proposal:FieldAudienceFamilyPolicy|ExactFieldAudienceRequirement,governing:FieldAudienceFamilyPolicy|null,approvals:FieldAudienceRequirementApproval[],over:Partial<Parameters<typeof issueFieldAudienceRequirement>[0]>={})=>issueFieldAudienceRequirement({authorizedIssuance:authorization,proposal,governingFamilyPolicy:governing,topology:topology(),approvals,referencedAdministrativeAuthorities:authorities,currentRequirementState:[proposal],finalRequirement:proposal,issuingAuthority:issuer,issuedAt:NOW,...over});
const historical=(receipt:FieldAudienceIssuanceReceipt,authorization:AuthorizedFieldAudienceRequirementIssuance,proposal:FieldAudienceFamilyPolicy|ExactFieldAudienceRequirement,governing:FieldAudienceFamilyPolicy|null,approvals:FieldAudienceRequirementApproval[],over:Partial<Parameters<typeof validateFieldAudienceIssuanceReceipt>[0]>={})=>validateFieldAudienceIssuanceReceipt({receipt,authorization,proposal,governingFamilyPolicy:governing,topology:topology(),finalRequirement:proposal,approvals,referencedAuthorityRevisions:authorities,historicalRequirementState:[proposal],...over});
const throws=(operation:()=>unknown)=>{try{operation();return false}catch{return true}};
const tests:{id:number;name:string;passed:boolean}[]=[];const test=(id:number,name:string,value:unknown)=>{assert(value,`${id}: ${name}`);tests.push({id,name,passed:true})};

const ordinary=policy(),wide=policy({requirements:[[root]],policyVersion:"policy:wide"});
const equalRule=exact(target("equal"),[[fn]]),narrowRule=exact(target("narrow"),[[team]]),broadRule=exact(target("broad"),[[root]]),incomparableRule=exact(target("incomparable"),[[initiative]]);
const policyCases={ordinary:deriveFieldAudienceApprovalPolicy({proposal:ordinary,governingFamilyPolicy:null,topology:topology(),asOf:NOW}),wide:deriveFieldAudienceApprovalPolicy({proposal:wide,governingFamilyPolicy:null,topology:topology(),asOf:NOW}),equal:deriveFieldAudienceApprovalPolicy({proposal:equalRule,governingFamilyPolicy:ordinary,topology:topology(),asOf:NOW}),narrow:deriveFieldAudienceApprovalPolicy({proposal:narrowRule,governingFamilyPolicy:ordinary,topology:topology(),asOf:NOW}),broad:deriveFieldAudienceApprovalPolicy({proposal:broadRule,governingFamilyPolicy:ordinary,topology:topology(),asOf:NOW}),incomparable:deriveFieldAudienceApprovalPolicy({proposal:incomparableRule,governingFamilyPolicy:ordinary,topology:topology(),asOf:NOW}),invalid:deriveFieldAudienceApprovalPolicy({proposal:broadRule,governingFamilyPolicy:ordinary,topology:{...topology(),digest:"tampered"},asOf:NOW})};
test(1,"ordinary policy requires one",policyCases.ordinary.requiredDistinctPrincipalCount===1);test(2,"organization-wide policy requires two",policyCases.wide.requiredDistinctPrincipalCount===2);test(3,"equal override requires one",policyCases.equal.requiredDistinctPrincipalCount===1);test(4,"narrowing override requires one",policyCases.narrow.requiredDistinctPrincipalCount===1);test(5,"broadening override requires two",policyCases.broad.requiredDistinctPrincipalCount===2);test(6,"incomparable override unresolved",policyCases.incomparable.disposition==="unresolved");test(7,"invalid topology invalid",policyCases.invalid.disposition==="invalid");

const singleApprovals=[approval(ordinary)],singleResult=authorize(ordinary,null,singleApprovals);assert(singleResult.authorized);const singleAuthorization=singleResult.authorization;
const dualApprovals=[approval(wide,issuer),approval(wide,approver)],dualResult=authorize(wide,null,dualApprovals);assert(dualResult.authorized);const dualAuthorization=dualResult.authorization;
const validateAuth=(authorization:AuthorizedFieldAudienceRequirementIssuance,proposal=wide,governing:FieldAudienceFamilyPolicy|null=null,approvals=dualApprovals,over:Partial<Parameters<typeof validateAuthorizedFieldAudienceRequirementIssuance>[0]>={})=>validateAuthorizedFieldAudienceRequirementIssuance({authorization,proposal,governingFamilyPolicy:governing,approvals,administrativeAuthorities:authorities,currentRequirementState:[proposal],topology:topology(),...over});
test(8,"valid single authorization",validateAuthorizedFieldAudienceRequirementIssuance({authorization:singleAuthorization,proposal:ordinary,governingFamilyPolicy:null,approvals:singleApprovals,administrativeAuthorities:authorities,currentRequirementState:[ordinary],topology:topology()}).valid);test(9,"valid dual authorization",validateAuth(dualAuthorization).valid);
test(10,"forged authorization identity rejected",!validateAuth({...dualAuthorization,authorizationId:"forged"}).valid);test(11,"forged authorization revision rejected",!validateAuth({...dualAuthorization,revisionId:"forged"}).valid);test(12,"forged authorization integrity rejected",!validateAuth({...dualAuthorization,digest:"forged"}).valid);test(13,"lowered authorization threshold rejected",!validateAuth({...dualAuthorization,requiredDistinctPrincipalCount:1}).valid);test(14,"changed policy revision rejected",!validateAuth({...dualAuthorization,approvalPolicyRevisionId:"forged"}).valid);test(15,"changed policy integrity rejected",!validateAuth({...dualAuthorization,approvalPolicyIntegrity:"forged"}).valid);test(16,"changed approval-set digest rejected",!validateAuth({...dualAuthorization,approvalSetDigest:"forged"}).valid);
const issuerRevision2=authority(issuer.principalId,{revision:2,supersedesRevisionId:issuer.revisionId});const duplicatePrincipalApprovals=[approval(wide,issuer),approval(wide,issuerRevision2)];test(17,"multiple authority revisions do not become two principals",!authorizeNewFieldAudienceRequirementIssuance({proposal:wide,governingFamilyPolicy:null,approvals:duplicatePrincipalApprovals,currentAdministrativeAuthorities:[issuer,issuerRevision2,approver],currentRequirementState:[wide],topology:topology(),issuingPrincipalId:issuer.principalId,issuingAuthorityRevisionId:issuerRevision2.revisionId,asOf:NOW}).authorized);test(18,"one approval cannot authorize dual control",!authorize(wide,null,[dualApprovals[0]!]).authorized);

const receipt=issue(singleAuthorization,ordinary,null,singleApprovals),exactApprovals=[approval(equalRule)],exactAuthResult=authorize(equalRule,ordinary,exactApprovals);assert(exactAuthResult.authorized);test(19,"valid authorization creates valid receipt",historical(receipt,singleAuthorization,ordinary,null,singleApprovals).valid);test(20,"forged authorization creates no receipt",throws(()=>issue({...singleAuthorization,digest:"forged"},ordinary,null,singleApprovals)));test(21,"different proposal creates no receipt",throws(()=>issue(singleAuthorization,policy({policyVersion:"other"}),null,singleApprovals)));test(22,"different governing policy creates no receipt",throws(()=>issue(exactAuthResult.authorization,equalRule,wide,exactApprovals)));test(23,"different topology creates no receipt",throws(()=>issue(singleAuthorization,ordinary,null,singleApprovals,{topology:{...topology(),digest:"forged"}})));test(24,"different approvals create no receipt",throws(()=>issue(singleAuthorization,ordinary,null,[])));test(25,"different final requirement creates no receipt",throws(()=>issue(singleAuthorization,ordinary,null,singleApprovals,{finalRequirement:policy({policyVersion:"final-other"})})));
const exactReceipt=issue(exactAuthResult.authorization,equalRule,ordinary,exactApprovals);test(26,"receipt threshold tamper rejected",!historical({...receipt,requiredDistinctPrincipalCount:2},singleAuthorization,ordinary,null,singleApprovals).valid);test(27,"receipt policy revision tamper rejected",!historical({...receipt,approvalPolicyRevisionId:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(28,"receipt policy integrity tamper rejected",!historical({...receipt,approvalPolicyIntegrity:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(29,"receipt authorization identity tamper rejected",!historical({...receipt,authorizationId:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(30,"receipt authorization revision tamper rejected",!historical({...receipt,authorizationRevisionId:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(31,"receipt authorization integrity tamper rejected",!historical({...receipt,authorizationIntegrity:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(32,"governing policy revision swap rejected",!historical(exactReceipt,exactAuthResult.authorization,equalRule,wide,exactApprovals).valid);test(33,"topology integrity swap rejected",!historical(receipt,singleAuthorization,ordinary,null,singleApprovals,{topology:{...topology(),digest:"forged"}}).valid);test(34,"receipt reused for proposal revision rejected",!historical(receipt,singleAuthorization,policy({policyVersion:"another"}),null,singleApprovals).valid);test(35,"receipt reused for target rejected",!historical(receipt,singleAuthorization,exact(target("other-target")),ordinary,singleApprovals).valid);test(36,"receipt reused across organization rejected",!historical({...receipt,organizationId:OTHER},singleAuthorization,ordinary,null,singleApprovals).valid);

test(37,"pre-revocation issuance valid",historical(receipt,singleAuthorization,ordinary,null,singleApprovals).valid);const revokedIssuer=authority(issuer.principalId,{revision:2,state:"revoked",effectiveAt:LATER,supersedesRevisionId:issuer.revisionId});test(38,"historical validation remains valid after revocation",historical(receipt,singleAuthorization,ordinary,null,singleApprovals).valid);test(39,"pre-revocation approval cannot issue after revocation",!authorizeNewFieldAudienceRequirementIssuance({proposal:ordinary,governingFamilyPolicy:null,approvals:singleApprovals,currentAdministrativeAuthorities:[issuer,approver,revokedIssuer],currentRequirementState:[ordinary],topology:topology(),issuingPrincipalId:issuer.principalId,issuingAuthorityRevisionId:issuer.revisionId,asOf:LATER}).authorized);test(40,"approval after revocation denied",throws(()=>approval(ordinary,revokedIssuer,{effectiveAt:LATER})));
const revokedRule=exact(target("lifecycle"),[[team]],{revision:2,state:"revoked",effectiveAt:LATER,supersedesRevisionId:narrowRule.revisionId,asOf:LATER});test(41,"requirement revocation leaves history valid and current revoked",historical(receipt,singleAuthorization,ordinary,null,singleApprovals).valid&&resolveCurrentFieldAudienceRequirement({organizationId:ORG,target:revokedRule.target,policies:[ordinary],exactRequirements:[narrowRule,revokedRule],historicalAuthorities:authorities,approvals:[],issuanceReceipts:[],topology:topology(),asOf:LATER}).disposition==="revoked");
const successor=policy({revision:2,policyVersion:"policy:2",effectiveAt:LATER,supersedesRevisionId:ordinary.revisionId,asOf:LATER}),successorApprovals=[approval(successor,issuer,{effectiveAt:LATER})],successorAuthResult=authorizeNewFieldAudienceRequirementIssuance({proposal:successor,governingFamilyPolicy:null,approvals:successorApprovals,currentAdministrativeAuthorities:authorities,currentRequirementState:[ordinary,successor],topology:topology(),issuingPrincipalId:issuer.principalId,issuingAuthorityRevisionId:issuer.revisionId,asOf:LATER});assert(successorAuthResult.authorized);const successorReceipt=issue(successorAuthResult.authorization,successor,null,successorApprovals,{currentRequirementState:[ordinary,successor],issuedAt:LATER});test(42,"supersession preserves prior receipt and selects immutable successor",historical(receipt,singleAuthorization,ordinary,null,singleApprovals).valid&&historical(successorReceipt,successorAuthResult.authorization,successor,null,successorApprovals,{historicalRequirementState:[ordinary,successor]}).valid);
test(43,"receipt identity tamper rejected",!historical({...receipt,receiptId:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(44,"receipt revision tamper rejected",!historical({...receipt,revisionId:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(45,"receipt integrity tamper rejected",!historical({...receipt,digest:"forged"},singleAuthorization,ordinary,null,singleApprovals).valid);test(46,"final requirement revision tamper rejected",!historical(receipt,singleAuthorization,ordinary,null,singleApprovals,{finalRequirement:{...ordinary,revisionId:"forged"}}).valid);test(47,"final requirement integrity tamper rejected",!historical(receipt,singleAuthorization,ordinary,null,singleApprovals,{finalRequirement:{...ordinary,digest:"forged"}}).valid);

const injected={...({requiredDistinctPrincipalCount:0,organizationWide:false,comparison:"narrower",approvalPolicyRevisionId:"caller",reason:"caller"} as Record<string,unknown>)};
const injectionResult=authorizeNewFieldAudienceRequirementIssuance({...({proposal:wide,governingFamilyPolicy:null,approvals:[dualApprovals[0]!],currentAdministrativeAuthorities:authorities,currentRequirementState:[wide],topology:topology(),issuingPrincipalId:issuer.principalId,issuingAuthorityRevisionId:issuer.revisionId,asOf:NOW,...injected} as unknown as Parameters<typeof authorizeNewFieldAudienceRequirementIssuance>[0])});assert.equal(injectionResult.authorized,false);
const reversedPolicy=policy({requirements:[[fn],[team,fn],[fn,team]]}),orderedPolicy=policy({requirements:[[fn,team],[fn]]});assert.equal(reversedPolicy.proposalDigest,orderedPolicy.proposalDigest);assert.equal(topology(true).digest,topology().digest);
const reversedAuth=authorizeNewFieldAudienceRequirementIssuance({proposal:wide,governingFamilyPolicy:null,approvals:[...dualApprovals].reverse(),currentAdministrativeAuthorities:[...authorities].reverse(),currentRequirementState:[wide],topology:topology(true),issuingPrincipalId:issuer.principalId,issuingAuthorityRevisionId:issuer.revisionId,asOf:NOW});assert(reversedAuth.authorized);assert.equal(reversedAuth.authorization.digest,dualAuthorization.digest);

const normalized={status:"PASS",classification:"A",tests,negativeCallerControl:"PASS",orderInvariance:"PASS",digests:{approvalPolicy:policyCases.wide.digest,authorization:dualAuthorization.digest,receipt:receipt.digest},sideEffects:{runtimeReads:0,runtimeWrites:0,currentPoliciesCreated:0,currentExactRequirementsCreated:0,currentApprovalsCreated:0,currentIssuanceReceiptsCreated:0,productionBehaviorChanges:0}};const output={...normalized,directSecurityValidationResultDigest:fieldAudienceDigest(normalized)};console.log(canonicalFieldAudienceJson(output));
