import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createEmptyOrganizationRuntime, type OrganizationRuntime } from "../../engine/v3/runtime/organizationRuntime";
import { FilesystemOrganizationRuntimeRepository } from "../../engine/v3/runtime/organizationRuntimeRepository";
import { buildFrontendReadyProductQuestionWorkspace } from "../../product/workflow";
import { buildImprovementProposal, materialAcquisitionEnvelopeDigest, productConfidenceImprovementEvents, productConfidenceImprovementOutcomeObservations, productLocalInformationOperationResults, type ProductConfidenceImprovementEnvelopeContext, type ProductConfidenceImprovementGovernedEvent, type ProductLocalInformationOperationRequest } from "../../product/improvements";
import { CanonicalLocalInformationOperationAdapter } from "../../product/integration";
import { createDurableProductQuestion } from "../../product/questions";
import { deriveProductUnknownCandidate, getProductUnknownHistory, recordProductUnknownOperation } from "../../product/unknowns";
import { stableId } from "../../product/workflow/text";

const organizationId = "onb-dev-gap-a-005-operation-001";
const userId = "development-user:gap-a-005";
const questionId = "question-gap-a-005";
const at = "2026-08-01T20:00:00.000Z";
const later = "2026-08-01T20:01:00.000Z";
const available = <T>(value: T, sourceRef: string) => ({ state: "available" as const, value, sourceRef, qualification: "Controlled local operation input.", maturity: "owner-provided" as const });

function fixture(): { runtime: OrganizationRuntime; proposal: ReturnType<typeof buildImprovementProposal>; context: ProductConfidenceImprovementEnvelopeContext; unknownRevisionRef: string } {
  let runtime = createEmptyOrganizationRuntime({ organizationId, name: "GAP-A-005 Local Operation" });
  runtime.metadata = { ...runtime.metadata, createdAt: at, updatedAt: at, investigationCount: 1 };
  runtime.organizationModel = { ...runtime.organizationModel, nodes: [{ id: "evidence:gap-a-005:ownership", type: "evidence", label: "Ownership timing", summary: "Ownership is assigned after the onboarding handoff.", confidence: 0.8, createdAt: at, updatedAt: at, metadata: { contentDigest: "sha256:ownership" } }] };
  runtime = createDurableProductQuestion({ runtime, questionId, title: "Why are onboarding handoffs delayed?", createdAt: at }).runtime;
  const candidate = deriveProductUnknownCandidate({ organizationId, questionId, category: "competing-explanation-discrimination", target: { kind: "relationship", subjectRef: "ownership", predicate: "versus", objectRef: "credentials" }, summary: "Ownership timing and credential readiness remain plausible.", whyItMatters: "The explanations imply different next actions.", sourceAncestry: [{ kind: "evidence", id: "evidence:gap-a-005:ownership" }] });
  const opened = recordProductUnknownOperation({ runtime, questionId, operationId: "unknown-open", occurredAt: at, actorRef: userId, authorizationScopeRef: `organization:${organizationId}:question:${questionId}`, candidate, transition: { type: "open" }, reason: "The exact explanation remains unresolved." });
  runtime = opened.runtime;
  const proposal = buildImprovementProposal({ organizationId, questionId, unknownId: candidate.unknownId, actionType: "inspect-existing-evidence", actionTarget: { kind: "existing-evidence-set", evidenceIds: ["evidence:gap-a-005:ownership"] }, summary: "Inspect exact admitted Evidence.", rationale: "Review the bounded Evidence against the current Unknown.", expectedValue: { understandingImprovement: "moderate", discriminationGain: "moderate", confidenceImpact: "possible", explanation: "The inspection may clarify the Unknown; no change is guaranteed." }, executionCost: { effort: "low", delay: "immediate", burden: "low", governanceRisk: "low" }, prerequisites: [], sourceScopeRefs: [`organization:${organizationId}:evidence-scope:admitted`], personScopeRefs: [], answerVersionId: null, abstentionOperationId: "abstention-gap-a-005", understandingRevisionRef: `organization:${organizationId}:understanding:1`, unknownRevisionRef: opened.receipt.eventId, generatedAt: at });
  const context: ProductConfidenceImprovementEnvelopeContext = { authorityRef: `organization:${organizationId}:authority:local-inspection:v1`, authorizationSatisfied: true, governanceAllowed: true, governanceContextRefs: [`organization:${organizationId}:governance:local-read-only:v1`], consentState: "not-required", targetAccessible: true, executionAvailable: true, ownerAvailable: true, expectedInformationClass: "existing-admitted-evidence-inspection", expectedOrganizationalRelevance: available("high", "owner:relevance"), relevanceToUnknown: available("high", "owner:unknown-relevance"), reliability: available("high", "owner:reliability"), existingEvidenceQuality: available("moderate", "owner:evidence-quality"), directCost: available("none", "owner:cost"), reversibility: available("reversible", "owner:reversibility"), organizationalBurden: available("low", "owner:burden"), requiredSourceAccess: [{ sourceScopeRef: `organization:${organizationId}:evidence-scope:admitted`, authorizationRef: `organization:${organizationId}:authority:local-inspection:v1`, state: "authorized" }], privacyConstraints: ["organization-only"], cancellation: { supported: true, characteristics: "Read-only inspection may stop before completion." }, resourceConstraintRefs: [], assumptions: ["The exact admitted Evidence remains present."], lineage: ["gap-a-005:controlled-local-replay"], objectiveVersionRef: null, optimizationContextVersionRef: null, stoppingCondition: "Stop after the exact admitted Evidence is inspected.", expectedEvidenceLineage: { sourceKind: "canonical-evidence", sourceScopeRef: `organization:${organizationId}:evidence-scope:admitted`, admissionRequired: true }, materialEffectTargets: ["unknown", "answer"], projectedAt: at };
  return { runtime, proposal, context, unknownRevisionRef: opened.receipt.eventId };
}

async function main() {
  const directory = await mkdtemp(path.join(tmpdir(), "discovery-gap-a-005-operation-"));
  try {
    const seeded = fixture();
    const repository = new FilesystemOrganizationRuntimeRepository(directory);
    await repository.create(organizationId, new TextEncoder().encode(JSON.stringify(seeded.runtime)), { requestId: "seed", operatorId: userId });
    let reads = 0; let connectorCalls = 0; let networkCalls = 0; let externalActions = 0; let allowed = true; let operationAllowed = true;
    const counted = { read: async (id: string) => { reads += 1; return repository.read(id); }, replace: repository.replace.bind(repository) };
    const adapter = new CanonicalLocalInformationOperationAdapter({ runtimeRepository: counted, authorize: async ({ userId: principal, organizationId: org }) => allowed && principal === userId && org === organizationId, authorizeImprovementOperation: async ({ operation }) => operationAllowed && ["candidate:project", "choice:authorize", "outcome:observe"].includes(operation), authorizeLocalInformationOperation: async () => operationAllowed, investigate: async () => { throw new Error("No investigation, connector, network, or external action is permitted."); } });
    const projected = await adapter.projectImprovementCandidateEnvelope({ userId, organizationId, questionId, proposal: seeded.proposal, context: seeded.context });
    const choice = await adapter.recordGovernedImprovementChoice({ userId, organizationId, questionId, proposal: seeded.proposal, context: seeded.context, disposition: "authorized", operationId: "gap-a-005-operation", expectedCurrentEventVersion: null, occurredAt: at, operation: { requestId: "choice", operatorId: userId } });
    const sourceDigest = stableId("product-local-information-source", "evidence:gap-a-005:ownership", "Ownership is assigned after the onboarding handoff.", "sha256:ownership");
    const request: ProductLocalInformationOperationRequest = { organizationId, actorRef: userId, authorityRef: seeded.context.authorityRef, humanChoiceReceipt: choice.receipt, executionAuthorization: "execute-existing-local-read-only-operation", proposal: seeded.proposal, operationId: "gap-a-005-operation", questionId, questionRevision: 0, unknownId: seeded.proposal.unknownId, unknownRevisionRef: seeded.unknownRevisionRef, understandingRevisionRef: seeded.proposal.understandingRevisionRef, objectiveVersionRef: null, optimizationContextVersionRef: null, candidateEnvelopeId: projected.envelope.envelopeId, candidateEnvelopeDigest: materialAcquisitionEnvelopeDigest(projected.envelope), operationType: "inspect-existing-evidence", sourceEvidenceIds: ["evidence:gap-a-005:ownership"], sourceDigests: [{ evidenceId: "evidence:gap-a-005:ownership", digest: sourceDigest }], idempotencyKey: "gap-a-005-operation:v1", requestedAt: later };
    const readsBeforeDenial = reads; allowed = false;
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "denied", operatorId: userId } }), /access denied/);
    assert.equal(reads, readsBeforeDenial); allowed = true;
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId: "onb-dev-foreign", request: { ...request, organizationId: "onb-dev-foreign" }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "foreign", operatorId: userId } }), /access denied/);
    operationAllowed = false; const readsBeforeOperationDenial = reads;
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "revoked", operatorId: userId } }), /access denied/);
    assert.equal(reads, readsBeforeOperationDenial); operationAllowed = true;
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, executionAuthorization: "do-not-execute" }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "no-execute", operatorId: userId } }), /not authorized/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, executionAuthorization: "defer-execution" }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "defer", operatorId: userId } }), /not authorized/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, operationType: "run-comparison" }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "unsupported", operatorId: userId } }), /not implemented/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, questionRevision: 1 }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "question-changed", operatorId: userId } }), /Question revision changed/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, unknownRevisionRef: "unknown:changed" }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "unknown-changed", operatorId: userId } }), /Unknown revision changed|proposal changed/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, understandingRevisionRef: `organization:${organizationId}:understanding:2` }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "understanding-changed", operatorId: userId } }), /Understanding revision changed/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, candidateEnvelopeDigest: "changed-envelope" }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "envelope-changed", operatorId: userId } }), /candidate envelope changed/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, humanChoiceReceipt: { ...request.humanChoiceReceipt, eventId: "stale-choice" } }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "stale-choice", operatorId: userId } }), /current governed human-choice receipt/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, sourceEvidenceIds: ["evidence:foreign"] }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "source-scope", operatorId: userId } }), /source scope changed/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, sourceDigests: [{ evidenceId: "evidence:gap-a-005:ownership", digest: "changed" }] }, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "source-digest", operatorId: userId } }), /source digest changed/);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request, expectedRuntimeRevision: "stale-runtime-revision", operation: { requestId: "stale", operatorId: userId } }), /revision changed/);
    const eligibleWorkspace = buildFrontendReadyProductQuestionWorkspace({ workspace: (await adapter.getQuestionWorkspace({ userId, organizationId, questionId })).workspace, humanDecision: choice.receipt, operationOwnerAvailable: true, operationEligibility: { operationType: "inspect-existing-evidence", status: "eligible", blockedReason: null } });
    const eligibleAction = eligibleWorkspace.actions.find((action) => action.id === "execute-existing-local-read-only-operation")!; assert.equal(eligibleAction.enabled, true); assert.equal(eligibleAction.blockedReason, null);
    const compareWorkspace = buildFrontendReadyProductQuestionWorkspace({ workspace: eligibleWorkspace.base, humanDecision: choice.receipt, operationOwnerAvailable: true, operationEligibility: { operationType: "run-comparison", status: "blocked", blockedReason: "operation-type-not-implemented" } });
    const compareAction = compareWorkspace.actions.find((action) => action.id === "execute-existing-local-read-only-operation")!; assert.equal(compareAction.enabled, false); assert.equal(compareAction.blockedReason, "operation-type-not-implemented");
    const executed = await adapter.executeLocalInformationOperation({ userId, organizationId, request, expectedRuntimeRevision: choice.runtimeRevision, operation: { requestId: "execute", operatorId: userId } });
    assert.equal(executed.result.status, "completed"); assert.equal(executed.result.informationProduced, true); assert.equal(executed.result.information.length, 1); assert.deepEqual(executed.result.evidenceCandidateRefs, []); assert.deepEqual(executed.result.admittedEvidenceIds, []); assert.equal(executed.result.operationType, "inspect-existing-evidence");
    const retry = await adapter.executeLocalInformationOperation({ userId, organizationId, request, expectedRuntimeRevision: executed.runtimeRevision, operation: { requestId: "retry", operatorId: userId } });
    assert.equal(retry.idempotent, true); assert.equal(retry.result.resultId, executed.result.resultId); assert.equal(retry.runtimeRevision, executed.runtimeRevision);
    await assert.rejects(() => adapter.executeLocalInformationOperation({ userId, organizationId, request: { ...request, idempotencyKey: "conflict" }, expectedRuntimeRevision: executed.runtimeRevision, operation: { requestId: "conflict", operatorId: userId } }), /ID conflict/);
    const reloaded = await repository.read(organizationId); assert.ok(reloaded);
    const completed = productConfidenceImprovementEvents(reloaded.runtime).find((event): event is ProductConfidenceImprovementGovernedEvent => event.schemaVersion === "3" && event.operationId === request.operationId && event.eventType === "improvement-completed"); assert.ok(completed);
    assert.equal(productLocalInformationOperationResults(reloaded.runtime).length, 1);
    const currentUnknownRef = getProductUnknownHistory({ runtime: reloaded.runtime, questionId, unknownId: request.unknownId }).at(-1)!.eventId;
    const observed = await adapter.recordImprovementOutcomeObservation({ userId, organizationId, expectedCurrentVersion: null, observation: { operationId: request.operationId, operationEventId: completed.eventId, organizationId, questionId, unknownId: request.unknownId, proposalId: request.proposal.proposalId, state: "completed", completedAt: later, actualBurden: "low", actualDirectCost: { state: "not-applicable" }, actualDelay: "immediate", resultArtifactRefs: [executed.result.resultId], informationRefs: executed.result.information.map((item) => item.informationId), evidenceCandidateRefs: [], admittedEvidenceIds: [], evidenceAdmissionDisposition: "not-evaluated", before: { unknownVersionRef: currentUnknownRef, answerVersionRef: null, understandingRevisionRef: request.understandingRevisionRef }, after: { unknownVersionRef: currentUnknownRef, answerVersionRef: null, understandingRevisionRef: request.understandingRevisionRef }, observedChange: { unknown: "unchanged", answer: "unmeasured", understanding: "unchanged" }, limitations: executed.result.limitations, observationSourceRef: `organization:${organizationId}:operation-result:${executed.result.resultId}`, observerRef: userId, observerAuthorityRef: request.authorityRef, occurredAt: later }, operation: { requestId: "observe", operatorId: userId } });
    const finalRuntime = (await repository.read(organizationId))!.runtime;
    assert.equal(productConfidenceImprovementOutcomeObservations(finalRuntime).length, 1);
    const base = await adapter.getQuestionWorkspace({ userId, organizationId, questionId });
    const workspace = buildFrontendReadyProductQuestionWorkspace({ workspace: base.workspace, humanDecision: choice.receipt, operationResult: executed.result, outcome: observed.observation, operationOwnerAvailable: true, operationEligibility: { operationType: "inspect-existing-evidence", status: "eligible", blockedReason: null } });
    assert.equal(workspace.stages.find((stage) => stage.id === "operation")?.status, "complete"); assert.equal(workspace.stages.find((stage) => stage.id === "outcome")?.status, "complete"); assert.equal(workspace.stages.find((stage) => stage.id === "learning")?.blockedReason, "evidence-not-admitted");
    const executeAction = workspace.actions.find((action) => action.id === "execute-existing-local-read-only-operation")!; assert.equal(executeAction.enabled, false); assert.equal(executeAction.blockedReason, "operation-already-completed"); assert.equal(executeAction.mayAccessExternalSystem, false);
    assert.equal(getProductUnknownHistory({ runtime: finalRuntime, questionId, unknownId: request.unknownId }).at(-1)!.eventId, currentUnknownRef); assert.equal(finalRuntime.metadata.investigationCount, 1);
    assert.equal(connectorCalls, 0); assert.equal(networkCalls, 0); assert.equal(externalActions, 0);
    console.log(JSON.stringify({ validation: "gap-a-005-local-information-operation-executor-001", result: "PASS", classification: "A — GAP-A-005 CANONICAL LOCAL OPERATION WORKFLOW VALIDATED", operationRan: true, informationProduced: true, evidenceCandidateCreated: false, evidenceAdmitted: false, unknownChanged: false, answerChanged: false, understandingChanged: false, recommendationChanged: false, learningProjectionProduced: true, independentlyReloaded: true, exactCleanup: true, connectorCalls, networkCalls, externalActions }, null, 2));
  } finally { await rm(directory, { recursive: true, force: true }); }
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
