import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {projectExecutiveTalkingPoints,projectMeetingExecutiveContinuity,projectSavedTalkingPointAdditions} from "../../product/integration/meetingExecutiveContentProjection";
import type {LeadershipConversationWorkspaceV1} from "../../product/workflow/leadershipConversation";
const workflowVariants=["No contribution crossed the boundary.","THE OCCURRENCE IS CLOSED!","Review completion is durable; proceed later.","A successor can be prepared after this checkpoint."];
const overlap=["Review enterprise capacity before revising the forecast.","Confirm whether the customer has closed the scope question.","Prepare evidence for the next commercial checkpoint."];
const original="A reviewed decision draft was not promoted because the current Product Answer was unavailable.";
const workspace={proposals:[{proposalId:"decision-1",kind:"decision-draft",payload:{summary:"Choose the delivery sequence."}}],dispositions:[{proposalId:"decision-1",dispositionReceiptId:"disposition-1",disposition:"approved"}],reviewedCarryForwardNonpromotions:[{proposalId:"decision-1",dispositionReceiptId:"disposition-1"}],canonicalRoutingReceipts:[],closureCompletion:{closureId:"closure-1",sections:[{label:"What remains unresolved",items:[original]},{label:"What was decided",items:overlap},{label:"Checkpoint status",items:workflowVariants}]}} as unknown as LeadershipConversationWorkspaceV1;
const projection=projectMeetingExecutiveContinuity(workspace);
assert.ok(!/Product Answer|promotion|owner result|route receipt|Prepared Work|publication|CAS|Private Working|Prepare Again/.test(projection.items.map(value=>value.text).join(" ")));
assert.ok(projection.workflowDetails.some(value=>value.includes(original)));
assert.deepEqual(projection.workflowOnlyTalkingPoints.map(value=>value.semanticKind),["workflow-status","workflow-status","workflow-status"]);
assert.deepEqual(projection.workflowOnlyTalkingPoints.map(value=>value.itemIndex),[3,4,5]);
assert.ok(projection.workflowOnlyTalkingPoints.every(value=>value.originKind==="reviewed-closure"&&value.itemId.startsWith("closure-1:section:")));
const identical=workflowVariants[0],talkingPoints={questionsToAsk:[overlap[0]],currentLeaning:[overlap[1]],watchOuts:[overlap[2]],doNotForget:[identical,"Keep this commitment"],privateContext:[identical]},visible=projectExecutiveTalkingPoints(talkingPoints,[{itemId:"typed-workflow-1",itemIndex:0,originKind:"reviewed-closure",semanticKind:"workflow-status"}]);
assert.deepEqual(visible.doNotForget,["Keep this commitment"]);assert.deepEqual(visible.privateContext,[identical]);assert.deepEqual(visible.questionsToAsk,talkingPoints.questionsToAsk);
const generated="Private talking points\n- Keep this commitment",saved=`${generated}\n- SAVED USER EDIT`,unsaved=`${saved}\n- UNSAVED SENTINEL`;
assert.deepEqual(projectSavedTalkingPointAdditions(generated,saved),["SAVED USER EDIT"]);assert.ok(!projectSavedTalkingPointAdditions(generated,saved).includes("UNSAVED SENTINEL"));assert.deepEqual(projectSavedTalkingPointAdditions(generated,generated),[]);assert.ok(projectSavedTalkingPointAdditions(generated,unsaved).includes("UNSAVED SENTINEL"),"only persisted input controls projection");
const product=["product/integration/meetingExecutiveContentProjection.ts","components/product-alpha/leadership-conversation/LeadershipConversationPrepare.tsx","components/product-alpha/leadership-conversation/LeadershipConversationExperience.module.css"].map(path=>readFileSync(path,"utf8"));
assert.ok(!product.join("\n").includes(workflowVariants[0]));
assert.ok(product[1].includes("workflowOnlyTalkingPointIndexes")&&product[1].includes("TalkingPointsPreview pack={pack}"));
assert.ok(product[1].includes("Save or cancel your edits before printing")&&product[1].includes("Last saved private talking points"));
assert.ok(product[2].includes(".page * { visibility:hidden !important; }")&&product[2].includes(".page .privateSavedPrint * { visibility:visible !important; }")&&product[2].includes(".privatePrint { display:none !important; }"));
console.log(JSON.stringify({validation:"typed-private-talking-point-hygiene-v1",result:"PASS",typedClassifications:4,wordingVariantsExcluded:4,substantiveOverlapRemoved:0,userAuthoredIdenticalTextRemoved:0,previewWorkflowItems:0,printWorkflowItems:0,storedWrites:0}));
