import assert from "node:assert/strict";
import {mkdtemp,mkdir,readFile,rename,rm,writeFile} from "node:fs/promises";
import path from "node:path";
import {tmpdir} from "node:os";
import {askMeetingDiscoveryAction} from "../../app/product-alpha/leadership-conversation/actions";
import {authorizedMeetingDirectory} from "../../product/integration/authorizedMeetingDirectory";
import {createLeadershipConversationServerComposition,setOptionalMeetingPackForAskValidationReadV1} from "../../product/integration/leadershipConversationServerComposition";
import {projectMeetingAskAnswer} from "../../product/integration/meetingAskProjection";
import {provisionNorthstarPreparationLineageFixture} from "../../product/simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";
import {SANDBOX_ORGANIZATION_ID} from "../../product/simulations/living-organization-sandbox/manifest";
import {createProductWorkflowArtifactRepository} from "../../product/workflow/leadershipConversation/productWorkflowArtifactRepository";
import {productArtifactBodyDigest} from "../../product/persistence/productArtifactBodyContracts";
import type {ChiefMeetingPackViewV1} from "../../product/workflow/leadershipConversation/meetingPackContracts";

const actor="user_AskRuntimeRepairCeo",director="user_AskRuntimeRepairDirector",manager="user_AskRuntimeRepairManager";
const definitions=[
  {title:"Northstar Staff Conversation",timeframe:"Weekly",purpose:"Resolve cross-functional dependencies and leadership decisions.",question:"What evidence supports cross-functional sequencing and unclear decision ownership?"},
  {title:"Pipeline Review",timeframe:"Weekly",purpose:"Review pipeline movement, conversion, forecast risk, and commercial decisions.",question:"What evidence supports conversion and delivery capacity that must be separated before revising the forecast?"},
  {title:"Product Leadership",timeframe:"Every two weeks",purpose:"Resolve product sequencing, technical risk, and customer commitments.",question:"What evidence supports interface sequencing?"},
] as const;

async function main(){
  const fixtureRoot=await mkdtemp(path.join(tmpdir(),"discovery-northstar-preparation-lineage-onboarding-ask-runtime-")),stateRoot=path.join(fixtureRoot,"state"),workflowRoot=path.join(stateRoot,"workflow"),runtimeRoot=path.join(fixtureRoot,"runtime"),sourceContentRoot=path.join(fixtureRoot,"discovery-governed-source-content-northstar-preparation");
  await mkdir(workflowRoot,{recursive:true,mode:0o700});
  const environment={NODE_ENV:"development",DISCOVERY_ENV:"development",NEXT_PUBLIC_DISCOVERY_ENV:"development",DISCOVERY_UNIVERSAL_ASK_RUNTIME_REPAIR_VALIDATION:"true",DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_DISCOVERY_ONBOARDING_TEST_ENABLED:"true",NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:"pk_test_ask_runtime_repair",CLERK_SECRET_KEY:"sk_test_ask_runtime_repair",DISCOVERY_DATABASE_URL:"postgresql://127.0.0.1/discovery_validation",DISCOVERY_DATABASE_ADMIN_URL:"postgresql://127.0.0.1/discovery_validation",DISCOVERY_DATABASE_MIGRATION_URL:"postgresql://127.0.0.1/discovery_validation",DISCOVERY_RUNTIME_STORAGE_BACKEND:"filesystem",DISCOVERY_RUNTIME_PROVISIONING_ENABLED:"false",DISCOVERY_ACCESS_PROVISIONING_ENABLED:"false",DISCOVERY_ATLAS_LIVE_PROVISIONING_ENABLED:"false",DISCOVERY_HOSTED_ENVIRONMENT:"false",DISCOVERY_NORTHSTAR_PREPARATION_LINEAGE_ROOT:fixtureRoot,DISCOVERY_NORTHSTAR_PREPARATION_LINEAGE_FIXTURE_ROOT:fixtureRoot,DISCOVERY_RUNTIME_ORGANIZATIONS_DIRECTORY:runtimeRoot,DISCOVERY_LEADERSHIP_CONVERSATION_WORKFLOW_ROOT:workflowRoot,DISCOVERY_GOVERNED_SOURCE_CONTENT_ROOT:sourceContentRoot,DISCOVERY_LEADERSHIP_CONVERSATION_SOURCE_CONTENT_ROOT:sourceContentRoot,DISCOVERY_SANDBOX_CEO_USER_ID:actor,DISCOVERY_SANDBOX_DIRECTOR_USER_ID:director,DISCOVERY_SANDBOX_MANAGER_USER_ID:manager,DISCOVERY_GENERATE_ANALYSIS_TEST_USER_ID:actor};
  const prior=new Map(Object.keys(environment).map(key=>[key,process.env[key]]));
  try{
    Object.assign(process.env,environment);
    const provisioned=await provisionNorthstarPreparationLineageFixture({environment:"development",fixtureRoot}),server=createLeadershipConversationServerComposition(),meetings=[] as Array<{title:string;seriesId:string;conversationId:string;questionId:string}>;
    for(const definition of definitions){const prepare=await server.activateAndPrepare({contractVersion:"1",userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:provisioned.seed.productQuestionId,meetingTitle:definition.title,timeframe:definition.timeframe,role:"Chief executive",purpose:definition.purpose,authorizedSourceRefs:[definition.title.startsWith("Northstar")?"meeting-preparation-scope:northstar-staff:v1":definition.title.startsWith("Pipeline")?"meeting-preparation-scope:pipeline-review:v1":"meeting-preparation-scope:product-leadership:v1"],idempotencyKey:`ask-runtime:${definition.title}`});meetings.push({title:definition.title,seriesId:`leadership-conversation-series:${prepare.conversationId}`,conversationId:prepare.conversationId,questionId:provisioned.seed.productQuestionId});}
    for(const [index,meeting] of [meetings[0]!,meetings[1]!,meetings[2]!,meetings[0]!].entries()){const workspace=await server.workspace({userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:meeting.questionId,conversationId:meeting.conversationId}),current=workspace.currentPreparedWorkProduct;assert(workspace.context&&current);await server.recordPreparation({userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:meeting.questionId,conversationId:meeting.conversationId,contextVersionId:workspace.context.contextVersionId,content:current.content,lineage:current.lineage,changeSummary:`Ask runtime validation revision ${index+1}.`,idempotencyKey:`ask-runtime:prepared:${index+1}`});}
    await server.addMeetingPackPrivateNote({userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:meetings[0]!.questionId,conversationId:meetings[0]!.conversationId,seriesId:meetings[0]!.seriesId,intent:"keep-private",text:"A private executive reminder.",idempotencyKey:"ask-runtime:private-note"});
    const packs:ChiefMeetingPackViewV1[]=[];for(const meeting of meetings)packs.push(await server.buildMeetingPack({userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:meeting.questionId,conversationId:meeting.conversationId,seriesId:meeting.seriesId}));
    for(let index=0;index<7;index++){const meeting=meetings[index%3]!,current=packs[index%3]!;packs[index%3]=await server.reviseMeetingPack({userId:actor,organizationId:SANDBOX_ORGANIZATION_ID,questionId:meeting.questionId,conversationId:meeting.conversationId,seriesId:meeting.seriesId,agendaText:`${current.agendaText}\nValidation revision ${index+1}.`,talkingPointsText:current.talkingPointsText,expectedArtifactRevision:current.artifactRevision,idempotencyKey:`ask-runtime:pack-revision:${index+1}`}) as typeof current;assert(packs[index%3]);}
    const repository=createProductWorkflowArtifactRepository({root:workflowRoot,environment:"development"}),before=await repository.read(SANDBOX_ORGANIZATION_ID),counts={admittedSources:8,seedSources:provisioned.seed.sourceContentVersions.length,prepared:before.store.preparedWorkPublications?.length??0,packs:before.store.meetingPackPublications?.length??0,notes:before.store.meetingPackPrivateNotePublications?.length??0};assert.deepEqual(counts,{admittedSources:8,seedSources:7,prepared:7,packs:10,notes:1});
    const workflowFile=path.join(workflowRoot,"organizations",`${SANDBOX_ORGANIZATION_ID}.json`),runtimeFile=path.join(runtimeRoot,`${SANDBOX_ORGANIZATION_ID}.json`),workflowBefore=await readFile(workflowFile),runtimeBefore=await readFile(runtimeFile),directory=await authorizedMeetingDirectory({userId:actor,organizationId:SANDBOX_ORGANIZATION_ID});assert.equal(directory.length,3);
    const answers=[];for(const definition of definitions){const meeting=directory.find(value=>value.title.toLowerCase()===definition.title.toLowerCase());assert(meeting);const answer=await askMeetingDiscoveryAction({seriesAddress:meeting.seriesAddress,question:definition.question});assert.notEqual(answer.status,"Unknown");assert(answer.citations.length>0);assert.equal(answer.scope,meeting.title);answers.push(answer);}
    const product=directory.find(value=>value.title==="Product Leadership")!,productPack=packs[2]!,agenda=await askMeetingDiscoveryAction({seriesAddress:product.seriesAddress,question:"Why is choose whether to delay the product milestone or narrow its scope on the agenda?"});assert.notEqual(agenda.status,"Unknown");assert(agenda.citations.length>0);assert.match(agenda.answer,/intended outcome/i);
    const lunarQuestion="What evidence supports the lunar capacity claim?",lunar=await askMeetingDiscoveryAction({seriesAddress:product.seriesAddress,question:lunarQuestion});assert.equal(lunar.status,"Unknown");assert.equal(lunar.citations.length,0);
    const analysis=await server.analyzeSourceScopedForDevelopment({userId:actor,organizationId:product.organizationId,questionId:product.questionId,seriesId:product.seriesId,occurrenceId:product.occurrenceId});assert.equal(analysis.result.status,"eligible");const candidate=analysis.result.status==="eligible"?analysis.result.candidate:null;
    const currentPack=await server.readMeetingPack({userId:actor,organizationId:product.organizationId,questionId:product.questionId,conversationId:product.occurrenceId,seriesId:product.seriesId});assert.equal(currentPack?.artifactRevision,packs[2]!.artifactRevision);const agendaQuestion="Why is choose whether to delay the product milestone or narrow its scope on the agenda?",withPackRead=async(read:Parameters<typeof setOptionalMeetingPackForAskValidationReadV1>[0],question:string)=>{setOptionalMeetingPackForAskValidationReadV1(read);try{return await askMeetingDiscoveryAction({seriesAddress:product.seriesAddress,question});}finally{setOptionalMeetingPackForAskValidationReadV1();}};
    const absentSupported=await withPackRead(async()=>null,definitions[2].question),absentAgenda=await withPackRead(async()=>null,agendaQuestion),absentLunar=await withPackRead(async()=>null,lunarQuestion);assert.notEqual(absentSupported.status,"Unknown");assert(absentSupported.citations.length>0);assert.equal(absentAgenda.status,"Unknown");assert.equal(absentAgenda.citations.length,0);assert.equal(absentLunar.status,"Unknown");assert.equal(absentLunar.citations.length,0);
    const stalePack={...currentPack!,potentiallyOutOfDate:true},staleSupported=await withPackRead(async()=>stalePack,definitions[2].question),staleAgenda=await withPackRead(async()=>stalePack,agendaQuestion);assert.notEqual(staleSupported.status,"Unknown");assert(staleSupported.citations.length>0);assert.equal(staleAgenda.status,"Unknown");assert.equal(staleAgenda.citations.length,0);
    const mandatory=(code:string)=>Object.assign(new Error("Meeting Pack mandatory read failure."),{code});for(const code of ["current-access-denied","foreign-pack-identity","cross-series-identity","unexpected-internal"]){await assert.rejects(()=>withPackRead(async()=>{throw mandatory(code);},definitions[2].question));}
    const latestHeader=before.store.meetingPackPublications!.filter(value=>value.seriesId===product.seriesId).at(-1)!,body=latestHeader.protectedBody,refName=productArtifactBodyDigest({organizationId:body.organizationId,semanticOwner:body.semanticOwner,artifactType:body.artifactType,artifactId:body.artifactId,artifactRevision:body.artifactRevision}),refPath=path.join(stateRoot,"product-artifact-bodies","organizations",body.organizationId,"owners",body.semanticOwner,"refs",`${refName}.json`),hidden=`${refPath}.unavailable`;await rename(refPath,hidden);try{await assert.rejects(()=>askMeetingDiscoveryAction({seriesAddress:product.seriesAddress,question:definitions[2].question}));await assert.rejects(()=>askMeetingDiscoveryAction({seriesAddress:product.seriesAddress,question:agendaQuestion}));}finally{await rename(hidden,refPath);}
    await assert.rejects(()=>askMeetingDiscoveryAction({seriesAddress:product.seriesAddress,question:definitions[2].question,organizationId:"foreign"} as never));process.env.DISCOVERY_GENERATE_ANALYSIS_TEST_USER_ID=director;await assert.rejects(()=>askMeetingDiscoveryAction({seriesAddress:directory.find(value=>value.title.toLowerCase().startsWith("northstar"))!.seriesAddress,question:definitions[0].question}));process.env.DISCOVERY_GENERATE_ANALYSIS_TEST_USER_ID=actor;
    assert.deepEqual(await readFile(workflowFile),workflowBefore);assert.deepEqual(await readFile(runtimeFile),runtimeBefore);
    console.log(JSON.stringify({validation:"universal-ask-typed-optional-pack-fault-matrix-v1",result:"PASS",founderEquivalent:counts,supportedRealActionQuestions:answers.length,typedLawfulOptionalOutcomes:2,blanketPackReadCatchesRemaining:0,authorizationFailuresClassifiedOptional:0,integrityFailuresClassifiedOptional:0,unexpectedFailuresClassifiedOptional:0,supportedAnswersAfterMandatoryPackReadFailures:0,sourceSupportedQuestionsBlockedByLawfulAbsence:0,agendaQuestionsAnsweredWithoutLawfulCurrentAgenda:0,stalePacksUsedAsCurrent:0,meetingHomeAskPackIdentityMismatches:0,lunarSupportedAnswers:0,lunarSupportCitations:0,crossUserPackDisclosures:0,crossSeriesPackDisclosures:0,askCreatedMeetingPacks:0,askCreatedPreparedWork:0,askCreatedProductWrites:0,askCreatedCanonicalWrites:0,askCreatedReviewOrPromotionWrites:0,askCreatedLifecycleWrites:0,durableAskTranscripts:0,addContextRegressions:0,packageLockChanges:0,providerRequests:0,newOwners:0,newPersistenceFamilies:0,newArchitectureFindings:0}));
  }finally{for(const[key,value]of prior)value===undefined?delete process.env[key]:process.env[key]=value;await rm(fixtureRoot,{recursive:true,force:true});}
}
void main();
