import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { compileChiefOfStaffValueLayerV1 } from "../../product/workflow/leadershipConversation/chiefCommunicationPlan";
import type { ChiefFirstPrepareViewV1 } from "../../product/workflow/leadershipConversation";

let checks=0;const check=(value:unknown,message:string)=>{assert.ok(value,message);checks++};
async function main(){const view:ChiefFirstPrepareViewV1={contractVersion:"1",organizationId:"org-1",questionId:"question-1",seriesId:"series-1",conversationId:"occurrence-1",meeting:{title:"Leadership meeting",timeframe:"Weekly",role:"Chief",purpose:"Resolve the constraint"},whatChanged:["A governed change is now visible."],whatMattersNow:["Customer handoffs deserve attention.","Clarify the accountable owner."],hiddenTension:["Speed conflicts with review quality."],possibleSurprise:["The delay may begin before approval."],questions:["Where does the handoff first fail?"],priorCycle:{status:"completed",message:"The reviewed outcome is reflected here."},sourceBasis:[{sourceRef:"source-1",label:"Current authorized Evidence"}],uncertainty:["The first failure point is not established."],reasoning:["This bears directly on the meeting purpose."],competingExplanations:["Capacity may explain the same pattern."],provenance:{contextVersionId:"context-1",preparedWorkProductVersionId:"prepared-1",authorizedProjectionRevision:"projection-1",authorizedProjectionDigest:"digest-1",sourceRevisionReferences:["source-version-1"]},status:"non-authoritative",currentStep:"freeze"};
const first=compileChiefOfStaffValueLayerV1(view),replay=compileChiefOfStaffValueLayerV1(structuredClone(view));
check(JSON.stringify(first)===JSON.stringify(replay),"exact replay deterministic");
check(first.authority==="non-authoritative-product-communication","no semantic authority created");
check(first.attention.length>0&&first.attention.every(item=>item.status==="supported"),"attention is supported and prioritized");
check(first.whyItMatters.every(item=>item.status==="inferred"),"reasoning remains explicitly inferred");
check(first.surprises.every(item=>item.status==="suspected"),"surprise remains explicitly suspected");
check(first.unknowns.every(item=>item.status==="unknown"),"unknowns remain explicit");
check(first.acquisition[0]?.itemId!==first.questions[0]?.itemId&&first.acquisition[0]?.text===`Request the evidence needed to resolve: ${first.questions[0]?.text}`,"acquisition is a distinct request bounded to a grounded question");
const abstain=compileChiefOfStaffValueLayerV1({...view,questions:[],uncertainty:[]});
check(abstain.acquisition.length===0,"unsupported acquisition abstains");
check(first.organizationId===view.organizationId&&first.questionId===view.questionId,"permission scope preserved");
const firstCycle=compileChiefOfStaffValueLayerV1({...view,priorCycle:{status:"none",message:"No prior completed conversation cycle is available yet."}});check(firstCycle.changed.length===0&&firstCycle.attention.some(item=>item.text.includes("governed change")),"first-cycle hypothesis may inform attention but never impersonates a comparison");
const bounded=compileChiefOfStaffValueLayerV1({...view,whatMattersNow:["A provisional capacity hypothesis deserves attention."],whatChanged:["Undetermined because current material is unavailable."]});
check(bounded.attention.some(item=>item.text.includes("provisional")&&item.status==="suspected"),"tentative hypothesis language is never labeled supported");
check(bounded.changed.every(item=>item.status==="unknown"),"unavailable and undetermined language remains unknown");
const occurrence2=compileChiefOfStaffValueLayerV1({...view,conversationId:"occurrence-2",whatMattersNow:["Current evidence is available, but protected predecessor comparison is withheld."],whatChanged:["Undetermined because the required predecessor content is not currently accessible."],hiddenTension:[],possibleSurprise:[],questions:[],uncertainty:["The required predecessor content is not currently accessible."],reasoning:[],competingExplanations:[],priorCycle:{status:"completed",message:"Occurrence 1 is closed."}});
check(occurrence2.attention.length===0&&occurrence2.changed.length===0&&occurrence2.whyItMatters.length===0&&occurrence2.surprises.length===0&&occurrence2.tensions.length===0&&occurrence2.questions.length===0,"access limitations never influence active meeting value sections");
check(occurrence2.acquisition.length===0,"access-only limitation causes acquisition abstention");
check(occurrence2.unknowns.length>0&&occurrence2.unknowns.every(item=>item.status==="unknown")&&occurrence2.details.some(item=>item.text.includes("withheld")),"Occurrence-2 access limitation remains body-safe progressive availability context");
check(!JSON.stringify(first).includes("source-version-1")&&!JSON.stringify(first).includes("prepared-1"),"frontend projection omits internal lineage identifiers");
const component=await readFile("components/product-alpha/leadership-conversation/LeadershipConversationPrepare.tsx","utf8"),page=await readFile("app/product-alpha/leadership-conversation/page.tsx","utf8");
for(const heading of ["What deserves your attention","Why it matters","What may surprise you","Consequential tensions","Questions worth asking","What would improve understanding","What changed since last time","What Discovery does not know"])check(component.includes(heading),`renders ${heading}`);
check(component.includes("<details>")&&component.includes("How Discovery reached this view"),"progressive disclosure retained");
check(component.includes("Discovery abstains")&&component.includes("Supported = grounded"),"truthful abstention and epistemic legend rendered");
check(page.match(/compileChiefOfStaffValueLayerV1/g)?.length===3,"both occurrences receive server-composed value layer");
check(!component.includes("OrganizationRuntime")&&!component.includes("SourceContentRepository"),"frontend firewall preserved");
console.log(JSON.stringify({validation:"chief-of-staff-value-layer-001",result:"PASS",checks,contractVersion:first.contractVersion,duplicateOwners:0,persistenceChanges:0,coreContractChanges:0,frontendReasoning:0,unsupportedAcquisition:0,networkCalls:0,productionAccess:0}));
}void main();
