import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { CanonicalLocalSourceBindingService } from "../../engine/v3/governance/canonicalLocalSourceBindingService";
import { createCanonicalScopeLineageIndex, createCanonicalScopeTopology } from "../../engine/v3/governance/canonicalScopeLineage";
import { resolveScopedGovernanceContext, type ScopedGovernanceOperation } from "../../engine/v3/governance/scopedGovernanceContext";
import { createEmptyOrganizationRuntime } from "../../engine/v3/runtime/organizationRuntime";
import { FilesystemOrganizationRuntimeRepository } from "../../engine/v3/runtime/organizationRuntimeRepository";
import { createFilesystemSourceContentRepository, decodeAndNormalizeSourceContent, GovernedSourceContentService, sourceContentDigest } from "../../engine/v3/sources";

const runFile=promisify(execFile);const ORG="sandbox-local-binding-replay-001",ACTOR="person:replay-validator",QUESTION="product-question:replay-001",PURPOSE="leadership-conversation-capture" as const,AT="2026-08-06T12:00:00.000Z";const BODY=new TextEncoder().encode("Northstar conversation evidence.\n");const sha=(value:Uint8Array|string)=>createHash("sha256").update(value).digest("hex");const scope={organizationId:ORG,type:"organization" as const,id:ORG};const assertions=[{relationship:"applies-to" as const,scope}];
function auth(operation:ScopedGovernanceOperation){return resolveScopedGovernanceContext({organizationId:ORG,subjectId:ACTOR,requestedScope:scope,operation,purpose:PURPOSE,sensitivity:"standard",evaluatedAt:AT,temporal:{mode:"current"},serverResolvedAuthority:[{authorityRef:"authority:replay",policyRef:"policy:replay:v1",organizationId:ORG,subjectId:ACTOR,scope,operations:[operation],sensitivity:["standard"],relationship:"direct",status:"active",validFrom:AT}]});}
const requestBase={contractVersion:"1" as const,organizationId:ORG,productQuestionId:QUESTION,sourceType:"pasted-text" as const,purposeRef:PURPOSE,normalizedContentDigest:sourceContentDigest(new TextEncoder().encode(decodeAndNormalizeSourceContent(BODY).normalizedText)),requestedScopeAssertions:assertions,sensitivity:"standard" as const};
async function worker(role:string,runtimeRoot:string,contentRoot:string,contentVersionId?:string){
  assert.ok(["A","B_FAIL","B","B_REPLAY","C"].includes(role));assert.ok(path.basename(path.dirname(runtimeRoot)).startsWith("discovery-local-binding-replay-"));assert.equal(path.dirname(runtimeRoot),path.dirname(contentRoot));
  const repository=new FilesystemOrganizationRuntimeRepository(runtimeRoot);const service=new CanonicalLocalSourceBindingService(repository,{now:()=>AT});
  if(role==="A"){const topology=createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:AT,nodes:[scope],relationships:[]});const runtime=createEmptyOrganizationRuntime({organizationId:ORG,name:"Replay",now:AT});runtime.memory.canonicalScopeLineageIndex=createCanonicalScopeLineageIndex({organizationId:ORG,topology});const created=await repository.create(ORG,new TextEncoder().encode(JSON.stringify(runtime,null,2)),{requestId:"initialize",operatorId:ACTOR});const receipt=await service.registerCanonicalLocalSourceBinding({...requestBase,recordedAt:AT,recordedByActorRef:ACTOR,idempotencyKey:"replay:register",expectedRuntimeRevision:created.revision,operation:{requestId:"register",operatorId:ACTOR},authorization:auth("source-binding:register-local")});return{role,bindingId:receipt.sourceBindingId,bindingVersion:receipt.bindingVersion};}
  const resolved=await service.resolveCanonicalCurrentSourceBinding({...requestBase,resolvedAt:AT,authorization:auth("source-binding:resolve-current")});
  const contentRepository=createFilesystemSourceContentRepository({root:contentRoot,environment:"test",defaultRoot:path.join(process.cwd(),".discovery-runtime/source-content")});const contentService=new GovernedSourceContentService(contentRepository,{loadRevisions:async()=>{const stored=await repository.read(ORG);return stored?.runtime.memory.canonicalScopeLineageIndex?.sourceBindings??[];}},{now:()=>AT});
  if(role==="B_FAIL"){await assert.rejects(()=>contentService.write({contractVersion:"1",organizationId:ORG,sourceBindingId:resolved.binding.bindingId,purposeRef:PURPOSE,mediaType:"text/plain",bytes:new TextEncoder().encode("different normalized content"),storedAt:AT,storedByActorRef:ACTOR,idempotencyKey:"replay:failed-content",expectedRepositoryRevision:null,authorization:auth("source-content:write")}));return{role,bindingId:resolved.binding.bindingId,bindingVersion:resolved.binding.bindingVersion,recovery:"binding-retained"};}
  if(role==="B"||role==="B_REPLAY"){const receipt=await contentService.write({contractVersion:"1",organizationId:ORG,sourceBindingId:resolved.binding.bindingId,purposeRef:PURPOSE,mediaType:"text/plain",bytes:BODY,storedAt:AT,storedByActorRef:ACTOR,idempotencyKey:"replay:content",expectedRepositoryRevision:null,authorization:auth("source-content:write")});return{role,bindingId:resolved.binding.bindingId,bindingVersion:resolved.binding.bindingVersion,contentVersionId:receipt.sourceContentVersionId,contentDisposition:receipt.disposition};}
  assert.ok(contentVersionId);const storedContent=await contentRepository.read(ORG,contentVersionId);assert.ok(storedContent);const content=await contentService.read({contractVersion:"1",organizationId:ORG,sourceBindingId:resolved.binding.bindingId,sourceContentVersionId:contentVersionId,purposeRef:PURPOSE,authorization:auth("source-content:read-for-proposal")});assert.equal(sha(content.bytes),storedContent.version.exactContentDigest);return{role,bindingId:resolved.binding.bindingId,bindingVersion:resolved.binding.bindingVersion,contentVersionId};
}
type SafeResult={role:string;bindingId:string;bindingVersion:number;contentVersionId?:string;contentDisposition?:string;recovery?:string};
function parseResult(stdout:string,role:string):SafeResult{const value=JSON.parse(stdout) as Record<string,unknown>;assert.deepEqual(Object.keys(value).sort(),Object.keys(value).filter(key=>["role","bindingId","bindingVersion","contentVersionId","contentDisposition","recovery"].includes(key)).sort());assert.equal(value.role,role);assert.equal(typeof value.bindingId,"string");assert.equal(typeof value.bindingVersion,"number");return value as SafeResult;}
async function main(){if(process.argv.includes("--worker")){const [role,runtimeRoot,contentRoot,contentVersionId]=process.argv.slice(process.argv.indexOf("--worker")+1);const original=console.info;console.info=()=>{};try{const result=await worker(role!,runtimeRoot!,contentRoot!,contentVersionId);process.stdout.write(JSON.stringify(result));}finally{console.info=original;}return;}let checks=0;const cycles:SafeResult[][]=[];for(let cycle=0;cycle<2;cycle++){const root=await mkdtemp(path.join(tmpdir(),"discovery-local-binding-replay-"));const runtimeRoot=path.join(root,"runtime"),contentRoot=path.join(root,"content");try{const execute=async(role:string,contentVersionId?:string)=>{const {stdout,stderr}=await runFile(process.execPath,[...process.execArgv,import.meta.filename,"--worker",role,runtimeRoot,contentRoot,...(contentVersionId?[contentVersionId]:[])],{cwd:process.cwd(),env:{PATH:process.env.PATH??"",NODE_PATH:process.env.NODE_PATH??"",NODE_ENV:"test"},timeout:10000,maxBuffer:64*1024,shell:false});assert.equal(stderr,"");return parseResult(stdout,role);};const a=await execute("A"),failed=await execute("B_FAIL"),b=await execute("B"),replay=await execute("B_REPLAY"),c=await execute("C",b.contentVersionId);assert.equal(a.bindingId,failed.bindingId);checks++;assert.equal(a.bindingId,b.bindingId);checks++;assert.equal(b.bindingId,c.bindingId);checks++;assert.equal(a.bindingVersion,c.bindingVersion);checks++;assert.equal(b.contentVersionId,replay.contentVersionId);checks++;assert.equal(b.contentVersionId,c.contentVersionId);checks++;assert.equal(replay.contentDisposition,"idempotent-replay");checks++;cycles.push([a,failed,b,replay,c]);}finally{await rm(root,{recursive:true,force:true});await assert.rejects(()=>import("node:fs/promises").then(fs=>fs.lstat(root)));checks++;}}assert.deepEqual(cycles[0],cycles[1]);checks++;console.log(JSON.stringify({validation:"canonical-local-source-binding-replay-001",result:"PASS",checks,freshProcesses:10,processes:["register","failed-content-write","write-content","idempotent-content-replay","resolve-and-read"],repeatedRuns:2,deterministicOutputs:true,boundedChildEnvironment:true,timeoutMilliseconds:10000,temporaryRootsRemoved:true,networkCalls:0,connectorCalls:0,driveReads:0,driveWrites:0,productionAccess:0,deploymentOperations:0}));}
void main();
