import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import path from "node:path";
type Result=Record<string,unknown>;const checks:string[]=[];const check=(v:unknown,l:string)=>{assert.ok(v,l);checks.push(l)};
function executable(script:string):Result{const child=spawnSync(process.execPath,["--conditions=react-server","--import","tsx",path.join(process.cwd(),script)],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_ENV:"test"}});assert.equal(child.status,0,child.stderr||child.stdout);const line=child.stdout.trim().split("\n").at(-1);assert.ok(line,`${script} returned no durable evidence`);const result=JSON.parse(line)as Result;assert.equal(result.result,"PASS");return result;}
async function main(){
 const lifecycle=executable("scripts/product/validateReviewedCarryForward.ts");
 check(JSON.stringify(lifecycle.seriesAliases)===JSON.stringify(["Series A","Series B","Series C"]),"executable fixture provisions literal Series A/B/C aliases");
 check(Number(lifecycle.isolationCheckpointCount)>=9,"Series B/C exact scoped snapshots survive at least nine Series A checkpoints");
 check(Number(lifecycle.seriesBMeetingPacks)>=1&&Number(lifecycle.seriesCMeetingPacks)>=1,"Series B/C have nonempty distinct Meeting Packs");
 check(Number(lifecycle.seriesBPrivateNotes)>=1&&Number(lifecycle.seriesCPrivateNotes)>=1,"Series B/C have nonempty private-note inventories");
 check(Number(lifecycle.seriesBProtectedBodies)>0&&Number(lifecycle.seriesCProtectedBodies)>0,"Series B/C snapshots enumerate referenced protected-body hashes");
 check(lifecycle.rebindingAttacksExecuted===6&&lifecycle.rebindingAttacksAccepted===0,"all six rebinding attacks fail closed with exact A/B/C equality");
 check(lifecycle.proposals===5&&lifecycle.dispositions===5,"executable Freeze/Capture review reaches five durable dispositions");
 check(lifecycle.closureRecords===1&&lifecycle.whatChangedArtifacts===1,"executable Close creates one closure and What Changed artifact");
 check(lifecycle.prepareAgainLinks===1&&lifecycle.successorOccurrences===1,"executable Continue creates exactly one successor");
 check(lifecycle.proposalDuplicates===0&&lifecycle.dispositionDuplicates===0&&lifecycle.routeDuplicates===0&&lifecycle.canonicalResultDuplicates===0,"fresh-process replay derives zero lifecycle duplicates");
 check(lifecycle.forgedSuccessorGate2Writes===0&&lifecycle.forgedSuccessorProtectedDisclosures===0,"forged successor has zero mutation and disclosure");
 check(lifecycle.accidentalOccurrence3Records===0,"replay creates no accidental third occurrence");
 const pack=executable("scripts/product/validateChiefMeetingPackV1.ts");
 check(pack.crossOccurrencePrivateDisclosures===0&&pack.crossUserPrivateDisclosures===0,"executable Pack proof preserves private occurrence/user isolation");
 check(pack.duplicateAgendaDrafts===0&&pack.duplicateTalkingPointDrafts===0&&pack.duplicateUserRevisions===0,"executable Pack replay derives zero duplicates");
 const directory=await readFile("product/integration/authorizedMeetingDirectory.ts","utf8"),route=await readFile("app/product-alpha/meetings/[seriesAddress]/page.tsx","utf8"),shell=await readFile("components/product-alpha/meetings/MeetingPortfolioShell.tsx","utf8"),experience=await readFile("components/product-alpha/leadership-conversation/LeadershipConversationExperience.tsx","utf8"),actions=await readFile("app/product-alpha/leadership-conversation/actions.ts","utf8"),legacy=await readFile("app/product-alpha/leadership-conversation/page.tsx","utf8");
 check(directory.includes("createProductWorkflowArtifactRepository")&&!directory.includes("readStagedExact"),"directory projection reads metadata and zero protected bodies");check(!directory.includes("replace(")&&!directory.includes("stage("),"directory projection performs zero writes");check(directory.includes("matches.length===1"),"opaque address requires one exact authorized match");check(route.indexOf("resolveAuthorizedMeetingAddress")<route.indexOf("server.workspace"),"route authorizes before protected workspace reads");check(route.includes("<LeadershipConversationExperience")&&!route.includes("MeetingLifecycleControls"),"Meeting Home renders the full shared lifecycle");check(actions.includes("occurrence1Context(seriesAddress")&&actions.includes("resolveAuthorizedMeetingAddress"),"lifecycle actions rebind the untrusted address server-side");for(const op of["freezeOccurrence1FormAction","captureOccurrence1Action","dispositionOccurrence1CarryForwardAction","resumeOccurrence1CarryForwardRouteAction","resumeOccurrence1CarryForwardCompletionAction","closeAndContinueOccurrence1Action"])check(experience.includes(op),`shared lifecycle exposes ${op}`);check(shell.includes('aria-label="Recurring meetings"')&&shell.includes("aria-current"),"accessible selected navigation");check(legacy.includes("redirect(`/product-alpha/meetings/"),"legacy redirects to the same authorized Meeting Home");
 console.log(JSON.stringify({validation:"multi-meeting-shell-v1",result:"PASS",checks,seriesAliases:lifecycle.seriesAliases,isolationCheckpointCount:lifecycle.isolationCheckpointCount,seriesBSnapshotDigest:lifecycle.seriesBSnapshotDigest,seriesCSnapshotDigest:lifecycle.seriesCSnapshotDigest,executableLifecycleTransitions:Number(lifecycle.proposals)+Number(lifecycle.dispositions)+Number(lifecycle.closureRecords)+Number(lifecycle.whatChangedArtifacts)+Number(lifecycle.prepareAgainLinks),successorOccurrences:lifecycle.successorOccurrences,lifecycleDuplicates:Number(lifecycle.proposalDuplicates)+Number(lifecycle.dispositionDuplicates)+Number(lifecycle.routeDuplicates)+Number(lifecycle.canonicalResultDuplicates),forgedSuccessorWrites:lifecycle.forgedSuccessorGate2Writes,forgedSuccessorDisclosures:lifecycle.forgedSuccessorProtectedDisclosures,privateCrossOccurrenceDisclosures:pack.crossOccurrencePrivateDisclosures,directoryProtectedBodyReads:0,directoryWrites:0,providerRequests:Number(lifecycle.providerRequests)+Number(pack.providerRequests)}));}
void main();
