import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
async function main(): Promise<void> {
  const [route, handler, operation] = await Promise.all([readFile(path.join(process.cwd(), "app/api/ops/migrate-runtime-to-postgres/route.ts"), "utf8"), readFile(path.join(process.cwd(), "lib/alpha-provisioning/productionRuntimeMigrationRoute.ts"), "utf8"), readFile(path.join(process.cwd(), "lib/alpha-provisioning/productionRuntimeMigrationOperation.ts"), "utf8")]);
  assert.ok(route.includes('import "server-only"') && route.includes('runtime = "nodejs"'));
  assert.ok(handler.includes("timingSafeEqual") && handler.includes("DISCOVERY_RUNTIME_MIGRATION_SECRET"));
  assert.ok(handler.indexOf("if (!authorized(request))") < handler.indexOf("await operation()"));
  assert.ok(handler.includes("RuntimeMigrationOperationError") && handler.includes("error.receipt"));
  assert.ok(!route.includes("postgres(") && !route.includes("INSERT INTO") && !route.includes("console."));
  assert.ok(operation.includes("applyGovernanceMigrations") && operation.includes("importLegacyOrganizationRuntime"));
  assert.ok(operation.includes('before.appliedMigrations === 8') && operation.includes('before.expectedMigrations === 9'));
  assert.ok(operation.includes('before.status === "PENDING"') && operation.includes("dependencies.apply(sql") && operation.includes(': before;'));
  assert.ok(operation.includes("ALREADY_COMPLETE") && operation.includes("RuntimeStorageConflictError"));
  for (const stage of ["PRECHECK", "MIGRATION_STATUS_BEFORE", "MIGRATION_0008_APPLY", "MIGRATION_STATUS_AFTER", "LEGACY_BLOB_RUNTIME_READ", "POSTGRES_RUNTIME_CONFLICT_CHECK", "POSTGRES_RUNTIME_IMPORT", "POSTGRES_RUNTIME_CREATE_VALIDATE", "POSTGRES_RUNTIME_CREATE_INSERT", "POSTGRES_RUNTIME_CREATE_RETURN_VALIDATE", "POSTGRES_RUNTIME_READBACK", "PAYLOAD_PARITY_VERIFY", "CAS_SMOKE"]) assert.ok(operation.includes(`\"${stage}\"`));
  for (const value of ["BEFORE_ANY_DURABLE_WRITE", "AFTER_MIGRATION_BEFORE_IMPORT", "AFTER_OR_DURING_IMPORT", "AFTER_IMPORT", "UNKNOWN", "RUNTIME_MIGRATION_STAGE_FAILED", "POSTGRES_RUNTIME_ORGANIZATION_PARENT_MISSING", "POSTGRES_RUNTIME_ALREADY_EXISTS", "POSTGRES_RUNTIME_CONSTRAINT_FAILED", "POSTGRES_RUNTIME_PERSISTENCE_FAILED", "POSTGRES_RUNTIME_UNKNOWN"]) assert.ok(operation.includes(`\"${value}\"`));
  assert.ok(operation.indexOf('stage = "MIGRATION_0008_APPLY"') < operation.indexOf("dependencies.apply(sql"));
  assert.ok(operation.includes('() => { stage = "MIGRATION_STATUS_AFTER"; durableWriteState = "AFTER_MIGRATION_BEFORE_IMPORT"; }'));
  assert.ok(operation.indexOf('stage = "MIGRATION_STATUS_AFTER"') < operation.indexOf('stage = "POSTGRES_RUNTIME_CONFLICT_CHECK"'));
  assert.ok(operation.indexOf("dependencies.apply(sql") < operation.indexOf("application.read(organizationId)"));
  assert.ok(operation.indexOf('stage = "POSTGRES_RUNTIME_IMPORT"') < operation.indexOf("dependencies.importLegacy"));
  assert.ok(operation.includes("onBoundary: (boundary: string)") && operation.includes('boundary === "legacy-read" ? "LEGACY_BLOB_RUNTIME_READ"'));
  assert.ok(operation.indexOf('stage = "PAYLOAD_PARITY_VERIFY"') < operation.lastIndexOf("currentDigest !== sourceDigest"));
  assert.ok(operation.indexOf('stage = "CAS_SMOKE"') < operation.lastIndexOf("RuntimeStorageConflictError"));
  assert.ok(operation.includes("new RuntimeMigrationOperationError") && !operation.includes("error.message"));
  assert.ok(!operation.includes("payload_text") && !operation.includes("console."));
  const { importLegacyOrganizationRuntime } = await import("../../engine/v3/runtime/organizationRuntimeLegacyImport");
  const bytes = new TextEncoder().encode("{}");
  const stored = (revision: string) => ({ bytes, revision, runtime: {} as never });
  const boundaries: string[] = [];
  await assert.rejects(() => importLegacyOrganizationRuntime({ organizationId: "test_org", legacy: { read: async () => { throw new Error("private"); } }, destination: { read: async () => null, create: async () => { throw new Error("unreached"); } }, requestId: "test", operatorId: "test", onBoundary: (boundary) => boundaries.push(boundary) }));
  assert.deepEqual(boundaries, ["legacy-read"]);
  boundaries.length = 0;
  await assert.rejects(() => importLegacyOrganizationRuntime({ organizationId: "test_org", legacy: { read: async () => stored("legacy") }, destination: { read: async () => null, create: async () => { throw new Error("private"); } }, requestId: "test", operatorId: "test", onBoundary: (boundary) => boundaries.push(boundary) }));
  assert.deepEqual(boundaries, ["legacy-read", "destination-read", "destination-create"]);
  const imported = await importLegacyOrganizationRuntime({ organizationId: "test_org", legacy: { read: async () => stored("legacy") }, destination: { read: async () => null, create: async () => stored("1") }, requestId: "test", operatorId: "test", onBoundary: () => { throw new Error("observability-only"); } });
  assert.equal(imported.disposition, "IMPORTED");
  const { migrateProductionRuntimeToPostgres, RuntimeMigrationOperationError } = await import("../../lib/alpha-provisioning/productionRuntimeMigrationOperation");
  const { PostgresRuntimeCreateConflictError, PostgresRuntimeCreateError, RuntimeStorageConflictError, RuntimeStorageIntegrityError } = await import("../../engine/v3/runtime/organizationRuntimeRepository");
  const environment = { VERCEL_ENV: "production", NODE_ENV: "production", DISCOVERY_ALPHA_ORGANIZATION_ID: "test_org", DISCOVERY_DATABASE_MIGRATION_URL: "postgresql://safe/test" } as NodeJS.ProcessEnv;
  const current = { status: "CURRENT", appliedMigrations: 9, expectedMigrations: 9, schemaComplete: true, missingSchemaObjects: [] };
  const pending = { ...current, status: "PENDING", appliedMigrations: 8 };
  const runtime = (value: Uint8Array = bytes, revision = "1") => ({ bytes: value, revision, runtime: {} as never });
  const dependencies = (overrides: Record<string, unknown> = {}) => ({ openSql: () => ({ end: async () => {} }), inspect: async () => current, apply: async (_sql: unknown, callback: () => void) => { callback(); return current; }, legacy: () => ({ read: async () => runtime() }), application: () => { let reads = 0; return { read: async () => reads++ ? runtime() : null, replace: async () => { throw new RuntimeStorageConflictError("safe"); } }; }, importLegacy: async () => ({ disposition: "IMPORTED" }), ...overrides });
  const failed = async (env: NodeJS.ProcessEnv, dependencies?: Record<string, unknown>) => {
    try { await migrateProductionRuntimeToPostgres(env, dependencies); assert.fail("expected failure"); } catch (error) { assert.ok(error instanceof RuntimeMigrationOperationError); return error.receipt; }
  };
  let receipt = await failed({} as NodeJS.ProcessEnv); assert.equal(receipt.stage, "PRECHECK"); assert.equal(receipt.durableWriteState, "BEFORE_ANY_DURABLE_WRITE");
  receipt = await failed(environment, dependencies({ inspect: async () => { throw new Error("private"); } })); assert.equal(receipt.stage, "MIGRATION_STATUS_BEFORE");
  let applicationReads = 0, imports = 0;
  receipt = await failed(environment, dependencies({ inspect: async () => pending, application: () => { applicationReads += 1; return { read: async () => null }; }, importLegacy: async () => { imports += 1; return { disposition: "IMPORTED" }; }, apply: async () => { throw new Error("private"); } })); assert.equal(receipt.stage, "MIGRATION_0008_APPLY"); assert.equal(receipt.durableWriteState, "UNKNOWN"); assert.equal(applicationReads, 0); assert.equal(imports, 0);
  applicationReads = 0; imports = 0;
  receipt = await failed(environment, dependencies({ inspect: async () => pending, application: () => { applicationReads += 1; return { read: async () => null }; }, importLegacy: async () => { imports += 1; return { disposition: "IMPORTED" }; }, apply: async (_sql: unknown, callback: () => void) => { callback(); return pending; } })); assert.equal(receipt.stage, "MIGRATION_STATUS_AFTER"); assert.equal(applicationReads, 0); assert.equal(imports, 0);
  receipt = await failed(environment, dependencies({ legacy: () => ({ read: async () => { throw new Error("private"); } }) })); assert.equal(receipt.stage, "LEGACY_BLOB_RUNTIME_READ");
  const pendingEvents: string[] = [];
  let pendingApplied = false, pendingReads = 0;
  const pendingSuccess = await migrateProductionRuntimeToPostgres(environment, dependencies({ inspect: async () => pending, apply: async (_sql: unknown, callback: () => void) => { pendingEvents.push("apply"); pendingApplied = true; callback(); return current; }, application: () => ({ read: async () => { assert.equal(pendingApplied, true); pendingEvents.push("postgres-read"); return pendingReads++ < 2 ? null : runtime(); }, create: async () => { pendingEvents.push("create"); return runtime(); }, replace: async () => { pendingEvents.push("cas"); throw new RuntimeStorageConflictError("safe"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(pendingSuccess.status, "COMPLETE"); assert.equal(pendingSuccess.migrationBefore, "PENDING"); assert.equal(pendingSuccess.migrationAfter, "CURRENT"); assert.deepEqual(pendingEvents, ["apply", "postgres-read", "postgres-read", "create", "postgres-read", "cas"]);
  const resumedEvents: string[] = [];
  let resumedReads = 0;
  const resumed = await migrateProductionRuntimeToPostgres(environment, dependencies({ apply: async () => { throw new Error("unreached"); }, application: () => ({ read: async () => { resumedEvents.push("postgres-read"); return resumedReads++ < 2 ? null : runtime(); }, create: async () => { resumedEvents.push("create"); return runtime(); }, replace: async () => { resumedEvents.push("cas"); throw new RuntimeStorageConflictError("safe"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(resumed.status, "COMPLETE"); assert.equal(resumed.migrationBefore, "CURRENT"); assert.deepEqual(resumedEvents, ["postgres-read", "postgres-read", "create", "postgres-read", "cas"]);
  let matchingWrites = 0;
  const matching = await migrateProductionRuntimeToPostgres(environment, dependencies({ application: () => ({ read: async () => runtime(), create: async () => { matchingWrites += 1; return runtime(); }, replace: async () => { matchingWrites += 1; throw new RuntimeStorageConflictError("safe"); } }), importLegacy: async () => { matchingWrites += 1; return { disposition: "IMPORTED" }; } }));
  assert.equal(matching.status, "ALREADY_COMPLETE"); assert.equal(matchingWrites, 0);
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => { throw new Error("private"); } }) })); assert.equal(receipt.stage, "POSTGRES_RUNTIME_CONFLICT_CHECK");
  let legacyReads = 0, creates = 0, replaces = 0;
  receipt = await failed(environment, dependencies({ legacy: () => ({ read: async () => { legacyReads += 1; return runtime(); } }), application: () => { let reads = 0; return { read: async () => { if (reads++ === 0) return null; throw new Error("private-pre-create-read"); }, create: async () => { creates += 1; return runtime(); }, replace: async () => { replaces += 1; throw new RuntimeStorageConflictError("safe"); } }; }, importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(receipt.stage, "POSTGRES_RUNTIME_CONFLICT_CHECK"); assert.equal(receipt.durableWriteState, "AFTER_MIGRATION_BEFORE_IMPORT"); assert.equal(receipt.retrySafe, "unknown"); assert.equal(legacyReads, 2); assert.equal(creates, 0); assert.equal(replaces, 0); assert.ok(!JSON.stringify(receipt).includes("private-pre-create-read"));
  let createCalls = 0;
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => null, create: async (_organizationId: string, _bytes: Uint8Array, metadata: any) => { createCalls += 1; metadata.onPostgresRuntimeCreateBoundary?.("validate"); throw new RuntimeStorageIntegrityError("private-create-validation"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(receipt.stage, "POSTGRES_RUNTIME_CREATE_VALIDATE"); assert.equal(receipt.errorCode, "RUNTIME_MIGRATION_STAGE_FAILED"); assert.equal(receipt.durableWriteState, "AFTER_OR_DURING_IMPORT"); assert.equal(createCalls, 1); assert.ok(!JSON.stringify(receipt).includes("private-create-validation"));
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => null, create: async (_organizationId: string, _bytes: Uint8Array, metadata: any) => { metadata.onPostgresRuntimeCreateBoundary?.("validate"); metadata.onPostgresRuntimeCreateBoundary?.("insert"); throw new PostgresRuntimeCreateError("POSTGRES_RUNTIME_ORGANIZATION_PARENT_MISSING", "insert"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(receipt.stage, "POSTGRES_RUNTIME_CREATE_INSERT"); assert.equal(receipt.errorCode, "POSTGRES_RUNTIME_ORGANIZATION_PARENT_MISSING"); assert.equal(receipt.durableWriteState, "AFTER_OR_DURING_IMPORT");
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => null, create: async (_organizationId: string, _bytes: Uint8Array, metadata: any) => { metadata.onPostgresRuntimeCreateBoundary?.("validate"); metadata.onPostgresRuntimeCreateBoundary?.("insert"); throw new PostgresRuntimeCreateConflictError("insert"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(receipt.stage, "POSTGRES_RUNTIME_CREATE_INSERT"); assert.equal(receipt.errorCode, "POSTGRES_RUNTIME_ALREADY_EXISTS");
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => null, create: async (_organizationId: string, _bytes: Uint8Array, metadata: any) => { metadata.onPostgresRuntimeCreateBoundary?.("validate"); metadata.onPostgresRuntimeCreateBoundary?.("insert"); throw new PostgresRuntimeCreateError("POSTGRES_RUNTIME_PERSISTENCE_FAILED", "insert"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(receipt.stage, "POSTGRES_RUNTIME_CREATE_INSERT"); assert.equal(receipt.errorCode, "POSTGRES_RUNTIME_PERSISTENCE_FAILED");
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => null, create: async (_organizationId: string, _bytes: Uint8Array, metadata: any) => { metadata.onPostgresRuntimeCreateBoundary?.("validate"); metadata.onPostgresRuntimeCreateBoundary?.("insert"); metadata.onPostgresRuntimeCreateBoundary?.("return-validate"); throw new RuntimeStorageIntegrityError("private-return-validation"); } }), importLegacy: importLegacyOrganizationRuntime }));
  assert.equal(receipt.stage, "POSTGRES_RUNTIME_CREATE_RETURN_VALIDATE"); assert.equal(receipt.errorCode, "RUNTIME_MIGRATION_STAGE_FAILED"); assert.ok(!JSON.stringify(receipt).includes("private-return-validation"));
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => runtime(new TextEncoder().encode("conflict")) }) })); assert.equal(receipt.stage, "PAYLOAD_PARITY_VERIFY"); assert.equal(receipt.retrySafe, false);
  receipt = await failed(environment, dependencies({ importLegacy: async () => { throw new Error("private"); } })); assert.equal(receipt.stage, "POSTGRES_RUNTIME_IMPORT"); assert.equal(receipt.durableWriteState, "AFTER_MIGRATION_BEFORE_IMPORT");
  receipt = await failed(environment, dependencies({ application: () => { let reads = 0; return { read: async () => reads++ ? runtime(new TextEncoder().encode("different")) : null, replace: async () => { throw new RuntimeStorageConflictError("safe"); } }; } })); assert.equal(receipt.stage, "PAYLOAD_PARITY_VERIFY");
  receipt = await failed(environment, dependencies({ application: () => { let reads = 0; return { read: async () => reads++ ? runtime() : null, replace: async () => { throw new Error("private"); } }; } })); assert.equal(receipt.stage, "CAS_SMOKE");
  receipt = await failed(environment, dependencies({ application: () => ({ read: async () => null, replace: async () => { throw new RuntimeStorageConflictError("safe"); } }) })); assert.equal(receipt.stage, "POSTGRES_RUNTIME_READBACK");
  const success = await migrateProductionRuntimeToPostgres(environment, dependencies()); assert.equal(success.status, "COMPLETE");
  const already = await migrateProductionRuntimeToPostgres(environment, dependencies({ application: () => ({ read: async () => runtime(), replace: async () => { throw new Error("unreached"); } }) })); assert.equal(already.status, "ALREADY_COMPLETE");
  const { createMigrationPostHandler } = await import("../../lib/alpha-provisioning/productionRuntimeMigrationRoute");
  Object.assign(process.env, { VERCEL_ENV: "production", NODE_ENV: "production", DISCOVERY_RUNTIME_MIGRATION_SECRET: "x".repeat(32) });
  let invoked = 0;
  const routeFailure = new RuntimeMigrationOperationError({ status: "FAILED_CLOSED", correlationId: "00000000-0000-4000-8000-000000000000", stage: "CAS_SMOKE", errorCode: "RUNTIME_MIGRATION_STAGE_FAILED", durableWriteState: "AFTER_IMPORT", retrySafe: true });
  let response = await createMigrationPostHandler(async () => { invoked += 1; throw routeFailure; })(new Request("https://safe.test", { method: "POST" })); assert.equal(response.status, 401); assert.equal(invoked, 0);
  response = await createMigrationPostHandler(async () => { invoked += 1; throw routeFailure; })(new Request("https://safe.test", { method: "POST", headers: { authorization: `Bearer ${process.env.DISCOVERY_RUNTIME_MIGRATION_SECRET}` } })); assert.equal(response.status, 409); assert.deepEqual(await response.json(), routeFailure.receipt);
  response = await createMigrationPostHandler(async () => { throw new Error("private-sentinel"); })(new Request("https://safe.test", { method: "POST", headers: { authorization: `Bearer ${process.env.DISCOVERY_RUNTIME_MIGRATION_SECRET}` } })); assert.equal(response.status, 409); assert.equal(await response.text(), "Runtime migration operation failed.");
  response = await createMigrationPostHandler(async () => success)(new Request("https://safe.test", { method: "POST", headers: { authorization: `Bearer ${process.env.DISCOVERY_RUNTIME_MIGRATION_SECRET}` } })); assert.equal(response.status, 200); assert.deepEqual(await response.json(), success);
  console.log("RESULT PASS production-runtime-migration-ops-route");
}
void main();
