import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { chmod, lstat, mkdtemp, readFile, readdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { resolveScopedGovernanceContext, type ScopedAuthorityGrant } from "../../engine/v3/governance/scopedGovernanceContext";
import { createProductArtifactBodyRepository, productArtifactBodyDigest, serializeProductArtifactBodyV1 } from "../../product/persistence";
import { CanonicalProductArtifactCurrentAccessComposition } from "../../product/integration/canonicalProductArtifactCurrentAccessComposition";
import { resolveProductArtifactCurrentAccessV1 } from "../../product/integration/productArtifactCurrentAccessResolver";
import { completeProductArtifactInspectionMetadataV1, validateProductArtifactInspectionMetadataV1 } from "../../product/workflow/productArtifactInspectionMetadataContracts";
import type { ProductArtifactCurrentOwnerStateV1 } from "../../product/workflow/productArtifactCurrentAccessContracts";
import { buildCurrentAuthorizedProductQuestionWorkspaceV1, classifyFuturePreparationItemsV1, deriveCurrentAuthorizedLeadershipHistoryV1 } from "../../product/workflow/leadershipConversation/operations";
import { provisionNorthstarPreparationLineageFixture, readNorthstarPreparationLineageSeed, resetNorthstarPreparationLineageFixture } from "../../product/simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";

const NORTHSTAR_ORGANIZATION="sandbox-northstar-implementation-services-001" as const,NORTHSTAR_FIXTURE="northstar-preparation-lineage-fixture-v1" as const,NORTHSTAR_KEY="northstar-preparation-lineage:v1" as const;
async function seedChild(root:string,expectedSeedDigest:string):Promise<void>{const seed=await readNorthstarPreparationLineageSeed({fixtureRoot:root,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY,expectedSeedDigest});process.stdout.write(`${seed.seedDigest}\n`)}
async function childDigest(root:string,expected:string):Promise<string>{return new Promise((resolve,reject)=>{const child=spawn(process.execPath,["--conditions=react-server","--import","tsx",process.argv[1]!,"--seed-child",root,expected],{cwd:process.cwd(),env:{...process.env,NODE_ENV:"test"},stdio:["ignore","pipe","pipe"]});let output="",error="";child.stdout.on("data",chunk=>output+=String(chunk));child.stderr.on("data",chunk=>error+=String(chunk));child.on("exit",code=>code===0?resolve(output.trim()):reject(new Error(error||`seed child failed: ${code}`)));});}
async function validateSeedRecordScenario():Promise<number>{const root=await mkdtemp(path.join(tmpdir(),"discovery-northstar-preparation-lineage-seed-record-"));let checks=0;try{await assert.rejects(()=>readNorthstarPreparationLineageSeed({fixtureRoot:root,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY}),/unavailable/);checks++;const first=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});const loaded=await readNorthstarPreparationLineageSeed({fixtureRoot:root,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY,expectedSeedDigest:first.seed.seedDigest});assert.deepEqual(loaded,first.seed);checks+=2;assert.equal(await childDigest(root,first.seed.seedDigest),first.seed.seedDigest);checks++;const second=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});assert.equal(second.disposition,"idempotent-replay");assert.deepEqual(second.seed,first.seed);checks+=2;await assert.rejects(()=>readNorthstarPreparationLineageSeed({fixtureRoot:root,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY,expectedSeedDigest:"0".repeat(64)}),/integrity/);checks++;
 const recordDirectory=path.join(root,"preparation-lineage-seeds",NORTHSTAR_ORGANIZATION),recordName=(await readdir(recordDirectory)).find(name=>name.endsWith(".json"));assert.ok(recordName);const recordPath=path.join(recordDirectory,recordName),original=await readFile(recordPath),status=await lstat(recordPath);assert.equal(status.mode&0o777,0o600);checks++;const parsed=JSON.parse(original.toString("utf8"));parsed.seed.projectionSourceRef="tampered";await writeFile(recordPath,`${JSON.stringify(parsed)}\n`,{mode:0o600});await assert.rejects(()=>readNorthstarPreparationLineageSeed({fixtureRoot:root,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY}),/integrity/);checks++;await writeFile(recordPath,original,{mode:0o600});const alias=`${root}-alias`;await symlink(root,alias);await assert.rejects(()=>readNorthstarPreparationLineageSeed({fixtureRoot:alias,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY}),/unsafe/);await rm(alias);checks++;await chmod(recordPath,0o644);await assert.rejects(()=>readNorthstarPreparationLineageSeed({fixtureRoot:root,organizationId:NORTHSTAR_ORGANIZATION,fixtureId:NORTHSTAR_FIXTURE,provisioningKey:NORTHSTAR_KEY}),/integrity/);await chmod(recordPath,0o600);checks++;await resetNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});await assert.rejects(()=>lstat(root),/ENOENT/);checks++;await mkdirForReprovision(root);const reprovisioned=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:root});assert.equal(reprovisioned.seed.seedDigest,first.seed.seedDigest);checks++;console.log(`northstar-seed-record: PASS (${checks} checks)`);return checks;}finally{await rm(root,{recursive:true,force:true})}}
async function mkdirForReprovision(root:string):Promise<void>{const{mkdir}=await import("node:fs/promises");await mkdir(root,{mode:0o700})}

export async function validateCurrentAccessScenario(label="authorization-before-body-read"):Promise<number>{
 const root=await mkdtemp(path.join(tmpdir(),"discovery-current-access-"));let checks=0;
 try{const repository=createProductArtifactBodyRepository({root});const at="2026-08-10T12:00:00.000Z",organizationId="org-test",questionId="question-1",subjectId="subject-1",scope={organizationId,type:"organization"as const,id:organizationId};
 const grant:ScopedAuthorityGrant={authorityRef:"authority:v1",policyRef:"policy:v1",organizationId,subjectId,scope,operations:["product-artifact:read"],sensitivity:["standard"],relationship:"direct",status:"active",validFrom:"2026-01-01T00:00:00.000Z"};let active=false,reads=0;const candidates=[];
 for(const artifactType of ["prepared-work","frozen-snapshot","what-changed","product-decision-draft"]as const){const before=reads,artifactId=`${artifactType}:1`,artifactRevision=`${artifactType}:revision:1`;const staged=await repository.stage({contractVersion:"1",organizationId,semanticOwner:artifactType==="product-decision-draft"?"product-decision-draft":"leadership-conversation",artifactType,artifactId,artifactRevision,schemaRef:`${artifactType}:v1`,bytes:serializeProductArtifactBodyV1({contractVersion:"1",title:`${artifactType} title`,summary:"safe"})});
 const seed={contractVersion:"1"as const,organizationId,semanticOwner:artifactType==="product-decision-draft"?"product-decision-draft"as const:"leadership-conversation"as const,productQuestionId:questionId,creationOperationId:"operation:1",lineagePolicyVersion:"conservative-material-ancestor.v1",sourceBindings:[{sourceBindingId:"binding:1",bindingRevisionId:"binding-revision:1"}],sourceContentVersions:[{sourceBindingId:"binding:1",sourceContentVersionId:"content:1",normalizedContentDigest:"a".repeat(64)}],canonicalMaterial:[{canonicalObjectId:"evidence:1",revisionRef:"admission:1",owner:"canonical-evidence-admission"as const}],canonicalUnderstandingRevision:"understanding:1",projectionSourceRef:"projection-source:1",seedDigest:"b".repeat(64),artifactType,artifactId,artifactRevision,envelopeDigest:""};
 const metadata=completeProductArtifactInspectionMetadataV1({organizationId,semanticOwner:seed.semanticOwner,artifactType,artifactId,artifactRevision,productQuestionId:questionId,productWorkflowId:"workflow:1",creationEnvelopeDigest:"creation",materialReferencesDigest:"material",protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,materialLineage:seed});
 const invalidLineages=[{...seed,sourceContentVersions:[{...seed.sourceContentVersions[0]!,sourceBindingId:""}]},{...seed,sourceContentVersions:[{...seed.sourceContentVersions[0]!,sourceBindingId:"binding:unknown"}]},{...seed,sourceContentVersions:[seed.sourceContentVersions[0]!,{...seed.sourceContentVersions[0]!,sourceBindingId:"binding:other"}],sourceBindings:[...seed.sourceBindings,{sourceBindingId:"binding:other",bindingRevisionId:"binding-revision:other"}]}];const{contractVersion:_contractVersion,headerDigest:_headerDigest,...metadataInput}=metadata;for(const materialLineage of invalidLineages){const invalid=completeProductArtifactInspectionMetadataV1({...metadataInput,materialLineage});assert.throws(()=>validateProductArtifactInspectionMetadataV1(invalid),/material lineage/);assert.equal(reads,before);checks+=2;}
 const counted={...repository,backend:repository.backend,stage:repository.stage.bind(repository),readStagedExact:async(ref:typeof staged.body)=>{reads++;return repository.readStagedExact(ref)}};const current:ProductArtifactCurrentOwnerStateV1={contractVersion:"1",organizationId,productQuestionId:questionId,sourceGovernanceDigest:"source-current",eligibilityDigest:"eligibility-current",eligibilityDisposition:"eligible",projectionRevision:"projection-1",projectionDigest:"projection-digest",canonicalUnderstandingRevision:"understanding-1",canonicalChangeResultDigest:"not-applicable",lineagePolicyVersion:"conservative-material-ancestor.v1"};
 const governance=()=>resolveScopedGovernanceContext({organizationId,subjectId,requestedScope:scope,operation:"product-artifact:read",purpose:"current-product-delivery",sensitivity:"standard",evaluatedAt:at,temporal:{mode:"current"},serverResolvedAuthority:active?[grant]:[]});const composition=new CanonicalProductArtifactCurrentAccessComposition({metadataOwners:[{inspect:async input=>input.artifactId===artifactId?metadata:null}],bodyRepository:counted,preauthorize:async()=>active,resolveGovernance:async()=>governance(),resolveCurrentOwnerState:async()=>current});const request={contractVersion:"1"as const,organizationId,subjectId,artifactType,artifactId,artifactRevision,operation:"product-artifact:read"as const,purpose:"current-product-delivery",scopeDigest:"scope-1",sensitivity:"standard"as const,evaluatedAt:at,project:()=>({contractVersion:"1"as const,artifactType,artifactId,artifactRevision,title:`${artifactType} title`,summary:"safe",accessResultDigest:"pending"})};
 assert.equal((await composition.readAuthorized(request)).disposition,"inaccessible");assert.equal(reads,before);active=true;const eligible=await composition.readAuthorized(request);assert.equal(eligible.disposition,"eligible");assert.equal(reads,before+1);assert.equal((await composition.readAuthorized({...request,artifactId:"wrong"})).disposition,"inaccessible");assert.equal(reads,before+1);checks+=6;
 const access=resolveProductArtifactCurrentAccessV1({contractVersion:"1",organizationId,subjectId,operation:"product-artifact:read",purpose:request.purpose,scopeDigest:"scope-1",sensitivity:"standard",evaluatedAt:at,metadata,governance:governance()},current);const value=(eligible as {disposition:"eligible";value:{contractVersion:"1";artifactType:typeof artifactType;artifactId:string;artifactRevision:string;title:string;summary:string;accessResultDigest:string}}).value;candidates.push({access,safeProjection:{...value,accessResultDigest:access.resultDigest},occurredAt:at,ownerState:artifactType==="what-changed"?"changed"as const:"unchanged"as const});active=false;}
 assert.equal(deriveCurrentAuthorizedLeadershipHistoryV1(candidates).entries.length,4);assert.equal(buildCurrentAuthorizedProductQuestionWorkspaceV1({organizationId,questionId,subjectId,purpose:"current-product-delivery",scopeDigest:"scope-1",sensitivity:"standard",evaluatedAt:at,candidates}).artifacts.length,4);assert.equal(classifyFuturePreparationItemsV1(candidates).every(x=>x.semanticInfluence),true);checks+=3;
 const denied=candidates.map(x=>{const unsigned={...x.access,disposition:"withheld"as const};const{resultDigest:_,...body}=unsigned;return{...x,access:{...body,resultDigest:productArtifactBodyDigest(body)},safeProjection:null}});assert.equal(deriveCurrentAuthorizedLeadershipHistoryV1(denied).entries.length,0);assert.equal(classifyFuturePreparationItemsV1(denied).every(x=>!x.semanticInfluence),true);checks+=2;console.log(`${label}: PASS (${checks} checks)`);return checks;
 }finally{await rm(root,{recursive:true,force:true})}}
if(process.argv[2]==="--seed-child")seedChild(process.argv[3]!,process.argv[4]!).catch(e=>{console.error(e);process.exitCode=1});else if(process.argv[1]?.endsWith("validateProductArtifactAuthorizationBeforeBodyRead.ts"))Promise.all([validateSeedRecordScenario(),validateCurrentAccessScenario()]).catch(e=>{console.error(e);process.exitCode=1});
