import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, open, readFile, readdir, realpath, rename, stat } from "node:fs/promises";
import path from "node:path";
import { createOpenAIExecutiveAnalysisTransport, extractCompletedSourceScopedResponse } from "../../lib/analysis/openAIExecutiveAnalysisTransport";
import { buildSourceScopedExecutiveAnalysisRequest, projectProviderSafeSourceScopedRequest, sourceScopedModelConfiguration, sourceScopedOutputSchema } from "../../lib/analysis/buildSourceScopedExecutiveAnalysisRequest";
import { sourceScopedDigest, sourceScopedStable, type SourceScopedCandidateV1 } from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import { runSourceScopedFrontierAnalysis } from "../../lib/analysis/runSourceScopedFrontierAnalysis";
import { SourceScopedExecutiveAnalysisOwner, SourceScopedFrontierAttemptLifecycleV1 } from "../../product/integration/sourceScopedExecutiveAnalysis";
import { ChiefMeetingPackOwner } from "../../product/integration/chiefMeetingPackOwner";
import { chiefMeetingPackInputSnapshotDigest, composeChiefMeetingPack } from "../../product/integration/chiefMeetingPackComposer";
import { createProductArtifactBodyRepository } from "../../product/persistence/productArtifactBodyRepository";
import { createProductWorkflowArtifactRepository } from "../../product/workflow/leadershipConversation/productWorkflowArtifactRepository";

const root = process.argv[2];
const phase = process.argv[3] ?? "freeze";
if (!root || !path.isAbsolute(root) || !["freeze", "technical", "replay", "publish", "cold"].includes(phase)) throw new Error("Isolated proof invocation is unavailable.");
const sourceRoot = "/Users/garyepper/Library/Application Support/Discovery/founder-local-alpha-epoch2/source-content/organizations/founder-13fee396696fb5ac8b301fd15b0c3408/blobs";
const question = "Should Asterline keep the October 15 launch date, delay it, or limit the release to a controlled pilot—and what must be resolved before leadership can decide?";
const identity = { userId: "isolated-proof-user", organizationId: "isolated-proof-organization", questionId: "isolated-proof-question", seriesId: "isolated-proof-series", conversationId: "isolated-proof-occurrence" };
const dirs = ["frozen-request", "raw-response", "validated-candidate", "isolated-product", "cold-reconstruction", "execution-ledger"] as const;
const sha = (value: Uint8Array | string) => createHash("sha256").update(value).digest("hex");
const now = () => "2026-09-11T00:00:00.000Z";
const file = (...parts: string[]) => path.join(root, ...parts);
async function privateDirectory(directory: string) { await mkdir(directory, { recursive: true, mode: 0o700 }); const value = await stat(directory); assert.equal(value.isDirectory(), true); assert.equal(value.isSymbolicLink(), false); assert.equal(value.mode & 0o777, 0o700); }
async function atomic(target: string, bytes: Uint8Array | string) { const directory = path.dirname(target); await privateDirectory(directory); const temp = path.join(directory, `.${path.basename(target)}.${process.pid}.tmp`); const handle = await open(temp, "wx", 0o600); try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); } const staged = await stat(temp); assert.equal(staged.isFile(), true); assert.equal(staged.isSymbolicLink(), false); assert.equal(staged.mode & 0o777, 0o600); await rename(temp, target); const parent = await open(directory, "r"); try { await parent.sync(); } finally { await parent.close(); } const final = await stat(target); assert.equal(final.isFile(), true); assert.equal(final.mode & 0o777, 0o600); }
async function json(target: string, value: unknown) { await atomic(target, `${sourceScopedStable(value)}\n`); }
async function readJson<T>(target: string): Promise<T> { return JSON.parse(await readFile(target, "utf8")) as T; }
function emptySections(): SourceScopedCandidateV1["sections"] { return { whatMattersNow: [], whyItMatters: [], competingExplanations: [], whatChanged: [], decisions: [], notDecided: [], commitments: [], openQuestions: [], contradictions: [], evidenceUncertainty: [], modelUncertainty: [], organizationalDisagreement: [], attention: [], whatWouldChangeAssessment: [] }; }
function mockCandidate(sources: Array<{ sourceId: string; sourceVersion: string; normalizedBodyDigest: string }>): SourceScopedCandidateV1 { const sections = emptySections(); const citation = { sourceId: sources[0]!.sourceId, sourceVersion: sources[0]!.sourceVersion, bodyDigest: sources[0]!.normalizedBodyDigest, sourcePacketDigest: "setup", startLine: 1, endLine: 1 }; sections.whatMattersNow.push({ statement: "Historical isolated draft for setup only.", citations: [citation], factCheck: "HUMAN REVIEW REQUIRED" }); sections.openQuestions.push({ statement: "What evidence would change the assessment?", citations: [citation], factCheck: "HUMAN REVIEW REQUIRED" }); return { candidateDigest: sourceScopedDigest(sections), model: "setup", usage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 }, sections }; }
function responseEnvelope(model: string, candidate: unknown) { return { id: "isolated-capture-canary", object: "response", created_at: 0, status: "completed", model, output: [{ id: "message", type: "message", status: "completed", role: "assistant", content: [{ type: "output_text", text: JSON.stringify(candidate) }] }], usage: { input_tokens: 1, output_tokens: 1, total_tokens: 2 } }; }
async function inputs(copy = true) {
  const names = (await readdir(sourceRoot, { withFileTypes: true })).filter(value => value.isFile()).map(value => value.name).sort();
  assert.equal(names.length, 5, "Expected exactly five regular live source bodies.");
  const copied: Array<{ organizationId: string; sourceId: string; sourceVersion: string; normalizedBodyDigest: string; body: string; effectiveAt: string; title: string; authority: "authoritative" }> = [];
  for (let index = 0; index < names.length; index++) { const bytes = await readFile(path.join(sourceRoot, names[index]!)); const body = new TextDecoder().decode(bytes).normalize("NFC"); assert.ok(body.trim()); const sourceId = `isolated-source-${index + 1}`; const sourceVersion = `isolated-version-${index + 1}`; const normalizedBodyDigest = sourceScopedDigest(body); const copyTarget=file("isolated-product", "source-content", `${String.fromCharCode(65 + index)}.txt`); if(copy) await atomic(copyTarget, body); else assert.equal(sha(await readFile(copyTarget)), sha(body), "Frozen isolated body changed."); copied.push({ organizationId: identity.organizationId, sourceId, sourceVersion, normalizedBodyDigest, body, effectiveAt: `2026-09-0${index + 1}T00:00:00.000Z`, title: "Isolated source", authority: "authoritative" }); }
  return copied;
}
function emitted(request: ReturnType<typeof buildSourceScopedExecutiveAnalysisRequest>["request"], model: string) { const projection = projectProviderSafeSourceScopedRequest(request); return JSON.stringify({ model, reasoning: { effort: "high" }, max_output_tokens: 25000, store: false, tools: [], input: [{ role: "developer", content: [{ type: "input_text", text: request.prompt }] }, { role: "user", content: [{ type: "input_text", text: JSON.stringify(projection.providerInput) }] }], text: { format: { type: "json_schema", name: "chief_v1_source_scoped_analysis", strict: true, schema: sourceScopedOutputSchema } } }); }
async function setupRevisions(sources: Awaited<ReturnType<typeof inputs>>) {
  const workflow = createProductWorkflowArtifactRepository({ root: file("isolated-product", "workflow"), environment: "test" });
  const bodies = createProductArtifactBodyRepository({ root: file("isolated-product", "artifact-bodies") });
  const owner = new ChiefMeetingPackOwner({ repository: workflow, bodyRepository: bodies, clock: { now }, authorize: async value => value.userId === identity.userId && value.organizationId === identity.organizationId });
  const privateState = await owner.noteIdentity(identity); const existing = await owner.read(identity); if (!existing) { const candidate = mockCandidate(sources); const base = (tag: string) => composeChiefMeetingPack({ ...identity, occurrenceId: identity.conversationId, userScopeDigest: privateState.userScopeDigest, prepare: { meeting: { purpose: `Generic ${tag} draft.` } } as never, workspace: {} as never, analysis: candidate, notes: [], inputSnapshotDigest: sourceScopedDigest({ tag, sources: sources.map(value => value.normalizedBodyDigest) }), sourceLineageDigest: sourceScopedDigest(sources.map(value => value.normalizedBodyDigest)), preparedWorkPublicationDigest: sourceScopedDigest({ prepared: true, tag }), priorCompletionDigest: null, createdAt: now() }); const first = await owner.publish({ ...identity, body: base("historical"), idempotencyKey: "isolated-seed-1" }); assert.equal(first?.revision, 1); const second = await owner.publish({ ...identity, body: base("current"), idempotencyKey: "isolated-seed-2" }); assert.equal(second?.revision, 2); } else assert.ok(existing.revision === 2 || existing.revision === 3, "Unexpected isolated revision state.");
  return { owner, privateState, workflow, bodies };
}
async function organizationConfinementControls(sources: Awaited<ReturnType<typeof inputs>>) {
  type Selected = Omit<(typeof sources)[number], "body">;
  const selected = sources.map(({ body: _body, ...source }) => source);
  async function exercise(selection: Selected[]) {
    let protectedReads = 0;
    let requestsBuilt = 0;
    let providerEntries = 0;
    const owner = new SourceScopedExecutiveAnalysisOwner({
      providerFamily: "isolated-control",
      model: "gpt-5.6-sol",
      transport: async () => { providerEntries++; throw new Error("Control transport must not execute."); },
      authorizeDesignatedPrincipal: async () => true,
      selectCurrentPrepareSources: async () => selection,
      resolveCurrentAccess: async () => ({ disposition: "eligible" as const, accessDigest: "isolated-control-access" }),
      readProtectedBody: async ({ source }) => {
        protectedReads++;
        const match = sources.find(value => value.sourceId === source.sourceId && value.sourceVersion === source.sourceVersion);
        assert.ok(match, "Control source was not selected from the isolated five-source Prepared Work.");
        return match.body;
      },
      onRequestBuilt: () => { requestsBuilt++; }
    });
    const result = await owner.analyze({ subjectId: identity.userId, organizationId: identity.organizationId, questionId: identity.questionId, seriesId: identity.seriesId, occurrenceId: identity.conversationId, question });
    return { result, protectedReads, requestsBuilt, providerEntries };
  }
  const positive = await exercise(selected);
  assert.equal(positive.result.status, "analysis-unavailable", "Control transport intentionally stops before provider dispatch.");
  assert.equal(positive.protectedReads, 5, "The exact organization must select all five sources before a request can be built.");
  assert.equal(positive.requestsBuilt, 1, "The exact organization must build one request after source closure.");
  assert.equal(positive.providerEntries, 1, "The control transport is reachable only after source closure.");
  const missing = selected.map((source, index) => index === 0 ? ({ ...source, organizationId: undefined } as unknown as Selected) : source);
  const foreign = selected.map(source => ({ ...source, organizationId: "foreign-isolated-organization" }));
  const mixed = selected.map((source, index) => index === 4 ? ({ ...source, organizationId: "foreign-isolated-organization" }) : source);
  for (const [name, selection] of [["missing-organization", missing], ["foreign-organization", foreign], ["mixed-organization", mixed]] as const) {
    const result = await exercise(selection);
    assert.equal(result.result.status, "analysis-unavailable", `${name} must fail closed.`);
    assert.equal(result.protectedReads, 0, `${name} must perform zero protected body reads.`);
    assert.equal(result.requestsBuilt, 0, `${name} must build zero provider requests.`);
    assert.equal(result.providerEntries, 0, `${name} must enter no provider transport.`);
  }
  await json(file("execution-ledger", "organization-confinement-controls.json"), { positive: { selected: 5, protectedReads: 5, foreignReads: 0, requestBuiltAfterClosure: true, providerEntryAfterClosure: true }, rejected: ["missing-organization", "foreign-organization", "mixed-organization"], rejectedReads: 0, rejectedRequests: 0, rejectedProviderEntries: 0, lifecycleWrites: 0 });
}
async function technical() {
  for (const directory of dirs) await privateDirectory(file(directory));
  assert.equal(process.env.DISCOVERY_ALPHA_ANALYSIS_MODEL, "gpt-5.6-sol", "Configured model is unavailable."); assert.ok(process.env.OPENAI_API_KEY, "Application credential is unavailable.");
  const sources = await inputs(phase === "freeze"); const setup = await setupRevisions(sources); if (phase === "freeze") await organizationConfinementControls(sources);
  const packetSources = sources.map(value => ({ organizationId: identity.organizationId, sourceId: value.sourceId, sourceVersion: value.sourceVersion, title: value.title, effectiveAt: value.effectiveAt, authority: value.authority, bodyDigest: value.normalizedBodyDigest, body: value.body })).map(value => ({ ...value, entryDigest: sourceScopedDigest(value) }));
  const packetBase = { contractVersion: "1" as const, organizationId: identity.organizationId, subjectId: identity.userId, questionId: identity.questionId, seriesId: identity.seriesId, occurrenceId: identity.conversationId, sources: packetSources };
  const packet = { ...packetBase, packetDigest: sourceScopedDigest(packetBase) }; const configuration = sourceScopedModelConfiguration({ providerFamily: "openai", model: "gpt-5.6-sol" }); const built = buildSourceScopedExecutiveAnalysisRequest({ packet, question, configuration }); const expectedBody = emitted(built.request, "gpt-5.6-sol");
  const transcript = projectProviderSafeSourceScopedRequest(built.request).providerInput; const transcriptText = JSON.stringify(transcript);
  for (const value of [identity.organizationId, identity.userId, identity.questionId, identity.seriesId, identity.conversationId, ...sources.flatMap(source => [source.sourceId, source.sourceVersion, source.normalizedBodyDigest, source.title])]) assert.equal(expectedBody.includes(value), false, "Provider-visible metadata is prohibited.");
  const freeze = { version: "1", createdAt: new Date().toISOString(), questionDigest: sha(question), sourceBodyHashes: sources.map(value => value.normalizedBodyDigest), preparedWorkFingerprint: sourceScopedDigest({ organizationId: identity.organizationId, question, sources: sources.map(value => value.normalizedBodyDigest) }), requestHash: sha(built.requestBytes), emittedBodyHash: sha(expectedBody), transcriptHash: sha(transcriptText), model: "gpt-5.6-sol", reasoning: "high", timeoutMs: configuration.timeoutMs, responseMemoryCeiling: 8 * 1024 * 1024, calls: 1, retries: 0, stoppingRule: "first failed gate", supersedesStoppedRun: "isolated-provider-durable-pack-v1-002" }; if(phase === "freeze"){ await json(file("frozen-request", "freeze-receipt.json"), freeze); await atomic(file("frozen-request", "request.json"), built.requestBytes); await atomic(file("frozen-request", "emitted-body.json"), expectedBody); await atomic(file("frozen-request", "transcript.json"), transcriptText); }else{ const prior=await readJson<typeof freeze>(file("frozen-request", "freeze-receipt.json")); assert.deepEqual({...prior,createdAt:""},{...freeze,createdAt:""},"Frozen request changed before dispatch."); assert.equal(await readFile(file("frozen-request", "request.json"),"utf8"),built.requestBytes); assert.equal(await readFile(file("frozen-request", "emitted-body.json"),"utf8"),expectedBody); assert.equal(await readFile(file("frozen-request", "transcript.json"),"utf8"),transcriptText); }
  const capture = async (target: string, response: Response) => { const clone = response.clone(); const bytes = new Uint8Array(await clone.arrayBuffer()); await atomic(target, bytes); assert.equal(sha(bytes), sha(await readFile(target))); return response; };
  const canaryResponse = responseEnvelope("gpt-5.6-sol", { sections: Object.fromEntries(Object.keys(emptySections()).map(key => [key, [{ statement: "Canary.", citations: [{ sourceAlias: "Source A", startLine: 1, endLine: 1 }], factCheck: "HUMAN REVIEW REQUIRED" }]])) }); let canaryCalls=0; const canaryTransport=createOpenAIExecutiveAnalysisTransport(async()=>{canaryCalls++;return capture(file("execution-ledger", "capture-canary.raw"),new Response(JSON.stringify(canaryResponse),{status:200}));}); assert.ok(canaryTransport); const canaryResult=await runSourceScopedFrontierAnalysis({request:built.request,requestBytes:built.requestBytes,transport:canaryTransport}); assert.equal(canaryCalls,1); assert.equal(canaryResult.status,"eligible"); const canaryBytes=await readFile(file("execution-ledger","capture-canary.raw")); assert.equal(extractCompletedSourceScopedResponse(JSON.parse(new TextDecoder().decode(canaryBytes))).model,"gpt-5.6-sol"); await json(file("execution-ledger","capture-canary-receipt.json"),{rawCapturedBeforeExtraction:true,originalResponseConsumable:true,canonicalAdapterConsumed:true,byteLimitEnforcedByCanonicalTransport:true,temporaryFsyncRename:true,postCloseHash:sha(canaryBytes),credentialsLogged:0,sourceBodiesLogged:0,responseBytes:canaryBytes.byteLength}); if(phase === "freeze"){ process.stdout.write(JSON.stringify({ status: "FROZEN_AND_CAPTURE_CANARY_PASS", requestHash: freeze.requestHash, emittedBodyHash: freeze.emittedBodyHash, transcriptHash: freeze.transcriptHash })); return; }
  if(phase === "replay"){ const raw=await readFile(file("raw-response","provider-response.json")); assert.equal(raw.byteLength,61007); assert.equal(sha(raw),"b0c62a80b1a8d03f3dc4cd69e615c4e5a706b97e836482b900ed3aed3c13c60b"); let replayFetches=0; const replayTransport=createOpenAIExecutiveAnalysisTransport(async()=>{replayFetches++;return new Response(raw);}); assert.ok(replayTransport); const replay=await runSourceScopedFrontierAnalysis({request:built.request,requestBytes:built.requestBytes,transport:replayTransport}); assert.equal(replayFetches,1,"Sealed response replay must have one local fetch invocation."); assert.equal(replay.status,"eligible","Sealed response must satisfy canonical validation."); await json(file("validated-candidate","candidate.json"),replay.candidate); await json(file("execution-ledger","sealed-response-replay.json"),{rawResponseHash:sha(raw),rawResponseBytes:raw.byteLength,providerRequests:0,localReplayFetches:replayFetches,model:"gpt-5.6-sol",candidateHash:sha(sourceScopedStable(replay.candidate)),status:"PASS"}); process.stdout.write(JSON.stringify({status:"SEALED_RESPONSE_REPLAY_PASS",candidateHash:sha(sourceScopedStable(replay.candidate))})); return; }
  const lifecycleRoot = file("execution-ledger", "lifecycle"); await privateDirectory(lifecycleRoot); const resolvedRoot = await realpath(root), resolvedLifecycleRoot = await realpath(lifecycleRoot); assert.ok(resolvedLifecycleRoot.startsWith(`${resolvedRoot}${path.sep}`), "Lifecycle root must remain beneath the protected proof root."); assert.equal((await stat(resolvedLifecycleRoot)).mode & 0o777, 0o700); assert.equal((await readdir(resolvedLifecycleRoot)).length, 0, "Lifecycle root must be empty before canonical initialization."); const lifecycleInspection = await SourceScopedFrontierAttemptLifecycleV1.inspect(resolvedLifecycleRoot); assert.equal(lifecycleInspection.active, path.join(resolvedLifecycleRoot, "active")); assert.equal(lifecycleInspection.attempts, path.join(resolvedLifecycleRoot, "attempts")); assert.equal((await readdir(lifecycleInspection.attempts)).length, 0, "No lifecycle receipt may predate analysis.");
  let fetches = 0; let dispatchAt = ""; let completionAt = ""; const captureFetch: typeof fetch = async (url, init) => { const attempts = await readdir(lifecycleInspection.attempts); assert.equal(attempts.length, 1, "Canonical lifecycle plan must be persisted before fetch."); const attempt = await readJson<{ history: Array<{ stage: string }> }>(path.join(lifecycleInspection.attempts, attempts[0]!)); assert.ok(attempt.history.some(value => value.stage === "transport-entry-persisted"), "Transport entry must be persisted before fetch."); assert.equal(fetches, 0, "Provider counter must be zero until lifecycle transport entry is persisted."); fetches++; assert.equal(fetches, 1, "Only one provider request is permitted."); assert.equal(String(url), "https://api.openai.com/v1/responses"); assert.equal(String(init?.body), expectedBody, "Frozen emitted request mismatch."); dispatchAt = new Date().toISOString(); const response = await fetch(url, init); completionAt = new Date().toISOString(); return capture(file("raw-response", "provider-response.json"), response); };
  const transport = createOpenAIExecutiveAnalysisTransport(captureFetch); assert.ok(transport, "Canonical transport is unavailable.");
  const owner = new SourceScopedExecutiveAnalysisOwner({ providerFamily: "openai", model: "gpt-5.6-sol", transport, lifecycleRoot: resolvedLifecycleRoot, authorizeDesignatedPrincipal: async () => true, selectCurrentPrepareSources: async () => sources.map(({ body: _body, ...source }) => source), resolveCurrentAccess: async () => ({ disposition: "eligible" as const, accessDigest: "isolated-access" }), readProtectedBody: async ({ source }) => sources.find(value => value.sourceId === source.sourceId)!.body }); owner.configureLifecycle({ root: resolvedLifecycleRoot, resolve: async () => ({ preparedWorkPublicationDigest: freeze.preparedWorkFingerprint, materialLineageDigest: sourceScopedDigest(sources.map(value => value.normalizedBodyDigest)) }) });
  const result = await owner.analyze({ subjectId: identity.userId, organizationId: identity.organizationId, questionId: identity.questionId, seriesId: identity.seriesId, occurrenceId: identity.conversationId, question }); assert.equal(fetches, 1, "Provider call count must equal one."); assert.equal(result.status, "eligible", "Technical provider path failed."); const raw = await readFile(file("raw-response", "provider-response.json")); assert.ok(raw.byteLength > 0); const candidate = result.candidate; await json(file("validated-candidate", "candidate.json"), candidate); const receipt = { dispatchAt, completionAt, durationMs: new Date(completionAt).getTime() - new Date(dispatchAt).getTime(), responseBytes: raw.byteLength, rawResponseHash: sha(raw), validatedCandidateHash: sha(sourceScopedStable(candidate)), envelope: "PASS", schema: "PASS", requestPacketBinding: "PASS", citations: "PASS", providerVisibleInternalMetadata: 0, providerRequests: 1, retries: 0, setupRevisions: 2, deterministicSetupConfigured: false }; await json(file("execution-ledger", "technical-receipt.json"), receipt); process.stdout.write(JSON.stringify({ status: "TECHNICAL_PASS_PENDING_INDEPENDENT_QUALITY", rawResponseHash: receipt.rawResponseHash, candidateHash: receipt.validatedCandidateHash, durationMs: receipt.durationMs, responseBytes: receipt.responseBytes }));
}
async function publish() {
  const sources = await inputs(false); const candidate = await readJson<SourceScopedCandidateV1>(file("validated-candidate", "candidate.json")); const setup = await setupRevisions(sources); const current = await setup.owner.read(identity); assert.equal(current?.revision, 2, "Only seed revisions 1 and 2 may exist before publication."); const body = composeChiefMeetingPack({ ...identity, occurrenceId: identity.conversationId, userScopeDigest: setup.privateState.userScopeDigest, prepare: { meeting: { purpose: "Isolated provider proof meeting." } } as never, workspace: {} as never, analysis: candidate, notes: [], inputSnapshotDigest: chiefMeetingPackInputSnapshotDigest({ organizationId: identity.organizationId, questionId: identity.questionId, seriesId: identity.seriesId, occurrenceId: identity.conversationId, userScopeDigest: setup.privateState.userScopeDigest, preparedWorkPublicationDigest: sourceScopedDigest({ isolated: "prepared-work" }), analysisDigest: candidate.candidateDigest, priorCompletionDigest: null, notes: [] }), sourceLineageDigest: sourceScopedDigest(sources.map(value => value.normalizedBodyDigest)), preparedWorkPublicationDigest: sourceScopedDigest({ isolated: "prepared-work" }), priorCompletionDigest: null, createdAt: now() }); const published = await setup.owner.publish({ ...identity, body, idempotencyKey: "isolated-provider-publication" }); assert.equal(published?.revision, 3); const replay = await setup.owner.publish({ ...identity, body, idempotencyKey: "isolated-provider-publication" }); assert.equal(replay?.revision, 3); process.stdout.write(JSON.stringify({ status: "PUBLICATION_PASS_PENDING_COLD_PROCESS", revision: published.revision }));
}
async function cold() { const candidate = await readJson<SourceScopedCandidateV1>(file("validated-candidate", "candidate.json")); const fresh = new ChiefMeetingPackOwner({ repository: createProductWorkflowArtifactRepository({ root: file("isolated-product", "workflow"), environment: "test" }), bodyRepository: createProductArtifactBodyRepository({ root: file("isolated-product", "artifact-bodies") }), clock: { now }, authorize: async value => value.userId === identity.userId && value.organizationId === identity.organizationId }); const reconstructed = await fresh.read(identity); assert.equal(reconstructed?.revision, 3, "Fresh process must reconstruct revision three."); await json(file("cold-reconstruction", "receipt.json"), { revision: reconstructed.revision, artifactRevision: reconstructed.artifactRevision, providerRequests: 0, workflowWrites: 0, runtimeWrites: 0, sourceWrites: 0, candidateHash: sha(sourceScopedStable(candidate)), processId: process.pid }); process.stdout.write(JSON.stringify({ status: "COLD_RECONSTRUCTION_PASS", revision: reconstructed.revision })); }
void (phase === "publish" ? publish() : phase === "cold" ? cold() : technical());
