import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { lstat, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createCanonicalScopeTopology, createCanonicalSourceScopeBinding, resolveCurrentSourceScopeBinding, type CanonicalSourceScopeBinding, type CanonicalSourceType } from "../../engine/v3/governance/canonicalScopeLineage";
import { resolveScopedGovernanceContext, type ScopedGovernanceOperation } from "../../engine/v3/governance/scopedGovernanceContext";
import { createFilesystemSourceContentRepository, decodeAndNormalizeSourceContent, GovernedSourceContentService, sourceContentDigest, sourceContentStableSerialize } from "../../engine/v3/sources";

const ORG="sandbox-governed-source-content-001",ACTOR="person:source-owner-validator",PURPOSE="leadership-conversation-capture",AT="2026-08-06T12:00:00.000Z";
const BODY=new TextEncoder().encode("\ufeff  Exact Notes  \r\nDecision remains open.\t\r\n");
const EQUIVALENT=new TextEncoder().encode("  Exact Notes\nDecision remains open.\n");
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value as object).sort().map(key=>`${JSON.stringify(key)}:${stable((value as Record<string,unknown>)[key])}`).join(",")}}`:JSON.stringify(value);
const normalized=decodeAndNormalizeSourceContent(BODY).normalizedText;
const topology=createCanonicalScopeTopology({organizationId:ORG,topologyVersion:1,effectiveAt:AT,nodes:[{organizationId:ORG,type:"organization",id:ORG}],relationships:[]});
function binding(input:Partial<{sourceId:string;availability:"available"|"revoked";version:number;predecessor:string|null;purpose:string;sourceType:CanonicalSourceType}>={}):CanonicalSourceScopeBinding{return createCanonicalSourceScopeBinding({organizationId:ORG,bindingVersion:input.version??1,source:{sourceId:input.sourceId??"local:notes:1",sourceVersion:"1",normalizedContentDigest:sha(new TextEncoder().encode(normalized))},topology,assertions:[{relationship:"applies-to",scope:{organizationId:ORG,type:"organization",id:ORG}}],basisRefs:[`purpose:${input.purpose??PURPOSE}`],effectiveAt:AT,sourceType:input.sourceType??"pasted-text",purposeRef:input.purpose??PURPOSE,availability:input.availability??"available",supersedesBindingId:input.predecessor??null});}
const first=binding();
function context(operation:ScopedGovernanceOperation,granted=true){return resolveScopedGovernanceContext({organizationId:ORG,subjectId:ACTOR,requestedScope:{organizationId:ORG,type:"organization",id:ORG},operation,purpose:PURPOSE,sensitivity:"standard",evaluatedAt:AT,temporal:{mode:"current"},serverResolvedAuthority:granted?[{authorityRef:"authority:source-content",policyRef:"policy:source-content:v1",organizationId:ORG,subjectId:ACTOR,scope:{organizationId:ORG,type:"organization",id:ORG},operations:[operation],sensitivity:["standard"],relationship:"direct",status:"active",validFrom:AT}]:[]});}
let checks=0;const check=(condition:unknown,message:string)=>{assert.ok(condition,message);checks+=1;};const rejects=async(fn:()=>Promise<unknown>|unknown,pattern?:RegExp)=>{if(pattern)await assert.rejects(async()=>fn(),pattern);else await assert.rejects(async()=>fn());checks+=1;};

async function main(){
  const root=await mkdtemp(path.join(tmpdir(),"discovery-governed-source-content-owner-"));const defaultRoot=path.join(process.cwd(),".discovery-runtime/source-content");
  let repositoryReads=0,repositoryWrites=0,bindingReads=0;const histories=new Map<string,readonly CanonicalSourceScopeBinding[]>([[first.bindingId,[first]]]);
  const mechanical=createFilesystemSourceContentRepository({root,environment:"test",defaultRoot});const repository={inspectRevision:(id:string)=>mechanical.inspectRevision(id),write:(input:Parameters<typeof mechanical.write>[0])=>{repositoryWrites+=1;return mechanical.write(input);},read:(org:string,id:string)=>{repositoryReads+=1;return mechanical.read(org,id);},resetDevelopmentFixture:(id:string)=>mechanical.resetDevelopmentFixture(id)};
  const service=new GovernedSourceContentService(repository,{loadRevisions:async({sourceBindingId})=>{bindingReads+=1;return histories.get(sourceBindingId)??[];}},{now:()=>AT});
  const request={contractVersion:"1" as const,organizationId:ORG,sourceBindingId:first.bindingId,purposeRef:PURPOSE,mediaType:"text/plain" as const,bytes:BODY,storedAt:AT,storedByActorRef:ACTOR,idempotencyKey:"write:001",expectedRepositoryRevision:null,authorization:context("source-content:write")};
  try{
    await rejects(()=>createFilesystemSourceContentRepository({root,environment:"production" as never}),/outside development/);
    const writesBefore=repositoryWrites,bindingsBefore=bindingReads;await rejects(()=>service.write({...request,authorization:context("source-content:write",false)}),/access denied/);check(repositoryWrites===writesBefore&&bindingReads===bindingsBefore,"denied write must not resolve binding or access persistence");
    const written=await service.write(request);check(written.disposition==="stored","initial write");check(written.exactContentDigest===sha(BODY),"independent exact digest");check(written.normalizedContentDigest===sha(new TextEncoder().encode("  Exact Notes\nDecision remains open.")),"independent normalized digest");
    const expectedId=`source-content-version:${sha(JSON.stringify(["1",ORG,first.bindingId,sha(BODY)]))}`;check(written.sourceContentVersionId===expectedId,"independent semantic ID");
    const receiptSafe={...written} as Record<string,unknown>;delete receiptSafe.receiptDigest;check(written.receiptDigest===sha(stable(receiptSafe)),"independent receipt digest");
    const organizationDirectory=path.join(root,"organizations",ORG),manifestPath=path.join(organizationDirectory,"manifest.json"),blobPath=path.join(organizationDirectory,"blobs",`${written.exactContentDigest}.blob`);
    check(((await stat(organizationDirectory)).mode&0o777)===0o700,"organization mode");check(((await stat(path.join(organizationDirectory,"blobs"))).mode&0o777)===0o700,"blob directory mode");check(((await stat(manifestPath)).mode&0o777)===0o600,"manifest mode");check(((await stat(blobPath)).mode&0o777)===0o600,"blob mode");
    const manifestBytes=await readFile(manifestPath),manifestText=manifestBytes.toString("utf8");check(!manifestText.includes(request.idempotencyKey)&&!manifestText.includes("authority:source-content")&&!manifestText.includes("ScopedGovernanceContext"),"safe manifest fields");check(written.repositoryRevision===sha(manifestBytes),"independent manifest revision");check(Buffer.from(await readFile(blobPath)).equals(Buffer.from(BODY)),"exact bytes preserved");
    const replay=await service.write(request);check(replay.disposition==="idempotent-replay"&&replay.sourceContentVersionId===written.sourceContentVersionId,"idempotent replay");await rejects(()=>service.write({...request,bytes:EQUIVALENT,expectedRepositoryRevision:replay.repositoryRevision}),/idempotency conflict/);
    const read=await service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:first.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal")});check(Buffer.from(read.bytes).equals(Buffer.from(BODY))&&read.text==="  Exact Notes  \r\nDecision remains open.\t\r\n","authorized exact read");
    const readsBefore=repositoryReads,bindingBeforeDenied=bindingReads;await rejects(()=>service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:first.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal",false)}),/access denied/);check(repositoryReads===readsBefore&&bindingReads===bindingBeforeDenied,"denied read performs zero binding and repository reads");
    const second=binding({sourceId:"local:notes:2"});histories.set(second.bindingId,[second]);const secondRequest={...request,sourceBindingId:second.bindingId,bytes:EQUIVALENT,idempotencyKey:"write:002",expectedRepositoryRevision:written.repositoryRevision};const equivalent=await service.write(secondRequest);check(equivalent.exactContentDigest!==written.exactContentDigest&&equivalent.sourceContentVersionId!==written.sourceContentVersionId,"byte-distinct exact identities");check(equivalent.normalizedContentDigest===written.normalizedContentDigest,"normalized equivalence retained");
    const revoked=binding({availability:"revoked",version:2,predecessor:first.bindingId});histories.set(first.bindingId,[first,revoked]);await rejects(()=>service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:first.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal")}),/access denied/);
    const reactivated=binding({availability:"available",version:3,predecessor:revoked.bindingId});histories.set(revoked.bindingId,[first,revoked,reactivated]);await rejects(()=>service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:revoked.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal")}),/access denied/);histories.set(reactivated.bindingId,[first,revoked,reactivated]);const reactivatedRead=await service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:reactivated.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal")}).catch(()=>null);check(reactivatedRead===null,"content remains bound to original binding after reactivation");
    await rejects(()=>Promise.resolve(resolveCurrentSourceScopeBinding([first,binding({version:2,predecessor:first.bindingId,purpose:"changed-purpose"})],AT)),/identity changed/);await rejects(()=>Promise.resolve(resolveCurrentSourceScopeBinding([first,binding({version:2,predecessor:first.bindingId,sourceType:"manual-takeaway"})],AT)),/identity changed/);
    const mutated=structuredClone(first);mutated.availability="revoked";await rejects(()=>Promise.resolve(resolveCurrentSourceScopeBinding([mutated],AT)),/integrity failed/);await rejects(()=>Promise.resolve(createCanonicalSourceScopeBinding({organizationId:ORG,bindingVersion:1,source:first.source,topology,assertions:first.assertions,basisRefs:first.basisRefs,effectiveAt:AT,sourceType:"pasted-text"})),/must be complete/);
    const legacy=createCanonicalSourceScopeBinding({organizationId:ORG,bindingVersion:1,source:{sourceId:"legacy",sourceVersion:"1",normalizedContentDigest:first.source.normalizedContentDigest},topology,assertions:first.assertions,basisRefs:first.basisRefs,effectiveAt:AT});check(resolveCurrentSourceScopeBinding([legacy],AT)?.bindingId===legacy.bindingId,"legacy binding remains valid");histories.set(legacy.bindingId,[legacy]);await rejects(()=>service.write({...request,sourceBindingId:legacy.bindingId,idempotencyKey:"legacy",expectedRepositoryRevision:equivalent.repositoryRevision}),/access denied/);
    await rejects(()=>service.write({...request,mediaType:"application/json" as never,idempotencyKey:"bad-media",expectedRepositoryRevision:equivalent.repositoryRevision}),/access denied/);await rejects(()=>service.write({...request,bytes:new Uint8Array(1024*1024+1),idempotencyKey:"large",expectedRepositoryRevision:equivalent.repositoryRevision}),/access denied/);histories.set(first.bindingId,[first]);await rejects(()=>service.write({...request,bytes:new Uint8Array([0xc3,0x28]),idempotencyKey:"utf8",expectedRepositoryRevision:equivalent.repositoryRevision}),/valid UTF-8/);await rejects(()=>mechanical.inspectRevision("../escape"));await rejects(()=>mechanical.inspectRevision("/absolute"));await rejects(()=>service.write({...request,idempotencyKey:"stale",expectedRepositoryRevision:null}),/revision changed/);
    await writeFile(blobPath,"tampered");await rejects(()=>service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:first.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal")}),/integrity failed/);await writeFile(blobPath,BODY,{mode:0o600});await rm(blobPath);await rejects(()=>service.read({contractVersion:"1",organizationId:ORG,sourceBindingId:first.bindingId,sourceContentVersionId:written.sourceContentVersionId,purposeRef:PURPOSE,authorization:context("source-content:read-for-proposal")}),/integrity failed/);await writeFile(blobPath,BODY,{mode:0o600});
    const originalManifest=await readFile(manifestPath);await writeFile(manifestPath,Buffer.concat([originalManifest,Buffer.from(" ")]));await rejects(()=>mechanical.inspectRevision(ORG),/integrity failed/);await writeFile(manifestPath,originalManifest,{mode:0o600});
    const defaultRepository=createFilesystemSourceContentRepository({root:defaultRoot,environment:"test",defaultRoot});const defaultService=new GovernedSourceContentService(defaultRepository,{loadRevisions:async()=>[first]},{now:()=>AT});await rejects(()=>defaultService.resetDevelopmentFixture({contractVersion:"1",environment:"test",organizationId:ORG,purposeRef:PURPOSE,actorRef:ACTOR,authorization:context("source-content:reset-development")}),/reset refused/);
    const reset=await service.resetDevelopmentFixture({contractVersion:"1",environment:"test",organizationId:ORG,purposeRef:PURPOSE,actorRef:ACTOR,authorization:context("source-content:reset-development")});check(reset.removed,"fixture reset");await rejects(()=>lstat(organizationDirectory));
    console.log(JSON.stringify({validation:"governed-source-content-owner-001",result:"PASS",checks,authorizationBeforeRepository:true,rawIdempotencyPersisted:false,retainedRuntimeWrites:0,networkCalls:0,connectorCalls:0,driveReads:0,driveWrites:0,productionAccess:0,deploymentOperations:0}));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}
void main();
