import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { readLeadershipConversationFixture } from "../../product/frontend/leadershipConversationFixtureAdapter";
import { createProductArtifactBodyRefV1, productArtifactBodyDigest, type ProductArtifactBodyRefV1, type ProductArtifactBodyStageRequestV1, type ProductArtifactBodyStageReceiptV1 } from "../../product/persistence/productArtifactBodyContracts";
import type { ProductArtifactBodyRepository } from "../../product/persistence/productArtifactBodyRepository";
import { provisionNorthstarPreparationLineageFixture } from "../../product/simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";
import { createProductWorkflowArtifactRepository, LeadershipConversationProductOperations, northstarLeadershipConversationFixture, NORTHSTAR_PREPARED_CONTENT, NORTHSTAR_PREPARED_LINEAGE } from "../../product/workflow/leadershipConversation";

class MemoryBodies implements ProductArtifactBodyRepository {
  readonly backend="filesystem" as const; readonly values=new Map<string,Uint8Array>(); reads=0;
  async stage(input:ProductArtifactBodyStageRequestV1):Promise<ProductArtifactBodyStageReceiptV1>{const body=createProductArtifactBodyRefV1({organizationId:input.organizationId,semanticOwner:input.semanticOwner,artifactType:input.artifactType,artifactId:input.artifactId,artifactRevision:input.artifactRevision,exactBodyDigest:productArtifactBodyDigest(input.bytes),byteLength:input.bytes.byteLength,mediaType:"application/json",schemaRef:input.schemaRef}),prior=this.values.get(body.bodyId),disposition=prior?"exact-replay" as const:"staged" as const;if(prior)assert.deepEqual(prior,input.bytes);else this.values.set(body.bodyId,input.bytes.slice());return{contractVersion:"1",body,disposition,receiptDigest:productArtifactBodyDigest({body,disposition})};}
  async readStagedExact(ref:ProductArtifactBodyRefV1){this.reads+=1;const value=this.values.get(ref.bodyId);if(!value)throw new Error("body unavailable");return value.slice();}
}
const check=(value:unknown,message:string)=>assert.ok(value,message);
async function main(){const workflowRoot=await mkdtemp(path.join(tmpdir(),"discovery-leadership-conversation-private-working-")),lineageRoot=await mkdtemp(path.join(tmpdir(),"discovery-northstar-preparation-lineage-private-working-"));try{const setup=await provisionNorthstarPreparationLineageFixture({environment:"test",fixtureRoot:lineageRoot}),fixture=northstarLeadershipConversationFixture(setup.seed.productQuestionId),repository=createProductWorkflowArtifactRepository({root:workflowRoot,environment:"test"}),bodyRepository=new MemoryBodies(),base=readLeadershipConversationFixture(fixture.questionId).base,lineageUnsigned={contractVersion:"1" as const,organizationId:fixture.organizationId,semanticOwner:"leadership-conversation" as const,productQuestionId:fixture.questionId,creationOperationId:"private-working:prepare",lineagePolicyVersion:"private-working:v1",sourceBindings:[{sourceBindingId:"binding:1",bindingRevisionId:"binding-revision:1"}],sourceContentVersions:[{sourceBindingId:"binding:1",sourceContentVersionId:"content:1",normalizedContentDigest:"a".repeat(64)}],canonicalMaterial:[{canonicalObjectId:"evidence:1",revisionRef:"admission:1",owner:"canonical-evidence-admission" as const}],canonicalUnderstandingRevision:"understanding:1",projectionSourceRef:"projection:1",scopeDigest:productArtifactBodyDigest({organizationId:fixture.organizationId}),purpose:fixture.purposeRef,sensitivity:"standard" as const},materialLineage={...lineageUnsigned,seedDigest:productArtifactBodyDigest(lineageUnsigned)},source={write:async()=>{throw new Error("capture excluded")},readForProposal:async()=>{throw new Error("proposal excluded")},readForEvidenceAdmission:async()=>{throw new Error("admission excluded")}},make=(authorized=true)=>new LeadershipConversationProductOperations({repository,bodyRepository,clock:{now:()=>fixture.at},authorize:async({userId,organizationId})=>authorized&&userId===fixture.actorId&&organizationId===fixture.organizationId,resolvePreparedWorkMaterialLineage:async()=>materialLineage,loadBase:async()=>base,source}),operations=make(),identity={userId:fixture.actorId,organizationId:fixture.organizationId,questionId:fixture.questionId,conversationId:fixture.conversationId};
  check((await repository.read(fixture.organizationId)).store.privateWorkingContributionPublications?.length===0,"zero persistence before Freeze");
  await operations.recordContext({...identity,idempotencyKey:"context",title:"Staff conversation",purpose:"Resolve constraint",intendedOutcome:"Agree action",timeframe:"Weekly",participants:[],leaderContext:null});let store=(await repository.read(fixture.organizationId)).store;await operations.recordPreparation({...identity,idempotencyKey:"prepare",contextVersionId:store.contexts[0]!.contextVersionId,content:NORTHSTAR_PREPARED_CONTENT,lineage:NORTHSTAR_PREPARED_LINEAGE,changeSummary:null});store=(await repository.read(fixture.organizationId)).store;const artifactVersionId=store.preparedWorkPublications![0]!.artifactRevision,selected=["Selected private item one.","Selected private item two."],unselected="Unselected private item.";
  await operations.freeze({...identity,idempotencyKey:"freeze",artifactVersionId,privateWorkingContribution:{seriesId:"series:1",occurrenceId:"occurrence:1",authorizationRevision:"authorization:1",provenanceDigest:"b".repeat(64),selectedContent:selected}});store=(await repository.read(fixture.organizationId)).store;const freeze=store.frozenSnapshotPublications![0]!,publications=store.privateWorkingContributionPublications!,receipts=store.privateWorkingContributionReceipts!,ids=publications.map(value=>value.artifactId),workflow=JSON.stringify(store);
  check(publications.length===2&&receipts.length===2&&freeze.privateWorkingContributionRefs?.length===2,"Freeze atomically binds exact contribution references");check(store.events.find(value=>value.eventType==="prepared-work-product-frozen")?.privateWorkingContributionRefs?.length===2,"Freeze event preserves exact body-free contribution references");check(!workflow.includes(selected[0]!)&&!workflow.includes(selected[1]!)&&!workflow.includes(unselected),"Workflow metadata is body-free");check([...bodyRepository.values.values()].some(bytes=>new TextDecoder().decode(bytes).includes(selected[0]!))&&!JSON.stringify([...bodyRepository.values.values()].map(bytes=>new TextDecoder().decode(bytes))).includes(unselected),"only selected protected content persists");check(new Set(ids).size===2&&ids.every(value=>value.startsWith("private-working-contribution:")),"owner issues deterministic identities");
  const loaded=await operations.readFrozenPrivateWorkingContribution({...identity,snapshotId:freeze.artifactId,artifactIds:ids});assert.deepEqual(loaded,selected);check(true,"hard reload reconstructs exact selected set");const reads=bodyRepository.reads;await assert.rejects(()=>make(false).readFrozenPrivateWorkingContribution({...identity,snapshotId:freeze.artifactId,artifactIds:ids}),/access denied/);check(bodyRepository.reads===reads,"authorization precedes protected body load");await assert.rejects(()=>operations.readFrozenPrivateWorkingContribution({...identity,snapshotId:freeze.artifactId,artifactIds:[...ids,"injected"]}),/unavailable/);check(true,"injected and mismatched identities fail closed");
  const captured=await operations.captureFrozenPrivateWorkingContribution({...identity,idempotencyKey:"capture-contribution",snapshotId:freeze.artifactId}),capture=captured.privateWorkingContributionCaptures![0]!,captureReceipt=captured.privateWorkingContributionCaptureReceipts![0]!,captureEvent=captured.events.find(value=>value.eventType==="private-working-contribution-captured")!;assert.deepEqual(capture.contributionRefs,freeze.privateWorkingContributionRefs);check(capture.reviewRequired&&capture.provenanceDigests[0]==="b".repeat(64)&&capture.authorizationRevisions[0]==="authorization:1","Capture preserves exact refs, provenance, authorization and Review requirement");check(captureReceipt.captureId===capture.captureId&&captureEvent.recordRef===capture.captureId&&captureEvent.privateWorkingContributionRefs?.length===2,"Capture owner emits bound receipt and event");const captureReplay=await operations.captureFrozenPrivateWorkingContribution({...identity,idempotencyKey:"capture-contribution",snapshotId:freeze.artifactId});check(captureReplay.privateWorkingContributionCaptures?.length===1&&captureReplay.privateWorkingContributionCaptureReceipts?.length===1,"Capture replay creates no duplicates");await assert.rejects(()=>operations.captureFrozenPrivateWorkingContribution({...identity,idempotencyKey:"capture-contribution-distinct",snapshotId:freeze.artifactId}),/already exists/);
  const replay=await operations.freeze({...identity,idempotencyKey:"freeze",artifactVersionId,privateWorkingContribution:{seriesId:"series:1",occurrenceId:"occurrence:1",authorizationRevision:"authorization:1",provenanceDigest:"b".repeat(64),selectedContent:selected}});check(replay.privateWorkingContributionPublications?.length===2&&replay.privateWorkingContributionReceipts?.length===2&&replay.frozenSnapshotPublications?.length===1,"replay creates no duplicate artifact, receipt, event, or Freeze");
  await assert.rejects(()=>operations.freeze({...identity,idempotencyKey:"concurrent-freeze",artifactVersionId,privateWorkingContribution:{seriesId:"series:1",occurrenceId:"occurrence:1",authorizationRevision:"authorization:1",provenanceDigest:"b".repeat(64),selectedContent:selected}}),/freeze mismatch/);check(true,"distinct concurrent Freeze cannot fork the checkpoint");
  const valid=await repository.read(fixture.organizationId),malformed=structuredClone(valid.store);malformed.privateWorkingContributionPublications![0]!.publicationDigest="malformed";const corrupted=await repository.replace(fixture.organizationId,malformed,valid.revision),readsBeforeMalformed=bodyRepository.reads;await assert.rejects(()=>operations.readFrozenPrivateWorkingContribution({...identity,snapshotId:freeze.artifactId,artifactIds:ids}),/unavailable/);check(bodyRepository.reads===readsBeforeMalformed,"malformed body-free metadata fails before protected load");await repository.replace(fixture.organizationId,valid.store,corrupted.revision);
  const concurrentRoot=await mkdtemp(path.join(tmpdir(),"discovery-leadership-conversation-private-working-concurrent-"));try{const concurrentRepository=createProductWorkflowArtifactRepository({root:concurrentRoot,environment:"test"}),concurrentBodies=new MemoryBodies(),concurrentOperations=new LeadershipConversationProductOperations({repository:concurrentRepository,bodyRepository:concurrentBodies,clock:{now:()=>fixture.at},authorize:async()=>true,resolvePreparedWorkMaterialLineage:async()=>materialLineage,loadBase:async()=>base,source});await concurrentOperations.recordContext({...identity,idempotencyKey:"context",title:"Staff conversation",purpose:"Resolve constraint",intendedOutcome:"Agree action",timeframe:"Weekly",participants:[],leaderContext:null});let concurrent=(await concurrentRepository.read(fixture.organizationId)).store;await concurrentOperations.recordPreparation({...identity,idempotencyKey:"prepare",contextVersionId:concurrent.contexts[0]!.contextVersionId,content:NORTHSTAR_PREPARED_CONTENT,lineage:NORTHSTAR_PREPARED_LINEAGE,changeSummary:null});concurrent=(await concurrentRepository.read(fixture.organizationId)).store;const concurrentVersion=concurrent.preparedWorkPublications![0]!.artifactRevision,first="Concurrent selection A",second="Concurrent selection B",results=await Promise.allSettled([concurrentOperations.freeze({...identity,idempotencyKey:"freeze-a",artifactVersionId:concurrentVersion,privateWorkingContribution:{seriesId:"series:1",occurrenceId:"occurrence:1",authorizationRevision:"authorization:1",provenanceDigest:"c".repeat(64),selectedContent:[first]}}),concurrentOperations.freeze({...identity,idempotencyKey:"freeze-b",artifactVersionId:concurrentVersion,privateWorkingContribution:{seriesId:"series:1",occurrenceId:"occurrence:1",authorizationRevision:"authorization:1",provenanceDigest:"c".repeat(64),selectedContent:[second]}})]),fulfilled=results.filter(value=>value.status==="fulfilled");check(fulfilled.length===1,"true concurrent distinct Freeze selections have exactly one owner winner");concurrent=(await concurrentRepository.read(fixture.organizationId)).store;const allBodies=JSON.stringify([...concurrentBodies.values.values()].map(bytes=>new TextDecoder().decode(bytes)));check(concurrent.privateWorkingContributionPublications?.length===1&&concurrent.frozenSnapshotPublications?.length===1&&allBodies.includes(first)!==allBodies.includes(second),"losing concurrent selection stages no protected body or reachable reference");}finally{await rm(concurrentRoot,{recursive:true,force:true});}
  const emptyRoot=await mkdtemp(path.join(tmpdir(),"discovery-leadership-conversation-private-working-empty-"));try{const emptyRepository=createProductWorkflowArtifactRepository({root:emptyRoot,environment:"test"}),emptyOperations=new LeadershipConversationProductOperations({repository:emptyRepository,bodyRepository,clock:{now:()=>fixture.at},authorize:async()=>true,resolvePreparedWorkMaterialLineage:async()=>materialLineage,loadBase:async()=>base,source});await emptyOperations.recordContext({...identity,idempotencyKey:"context",title:"Staff conversation",purpose:"Resolve constraint",intendedOutcome:"Agree action",timeframe:"Weekly",participants:[],leaderContext:null});let empty=(await emptyRepository.read(fixture.organizationId)).store;await emptyOperations.recordPreparation({...identity,idempotencyKey:"prepare",contextVersionId:empty.contexts[0]!.contextVersionId,content:NORTHSTAR_PREPARED_CONTENT,lineage:NORTHSTAR_PREPARED_LINEAGE,changeSummary:null});empty=(await emptyRepository.read(fixture.organizationId)).store;await emptyOperations.freeze({...identity,idempotencyKey:"freeze-empty",artifactVersionId:empty.preparedWorkPublications![0]!.artifactRevision,privateWorkingContribution:{seriesId:"series:1",occurrenceId:"occurrence:1",authorizationRevision:"authorization:1",provenanceDigest:"b".repeat(64),selectedContent:[]}});empty=(await emptyRepository.read(fixture.organizationId)).store;check(empty.privateWorkingContributionPublications?.length===0&&!empty.frozenSnapshotPublications![0]!.privateWorkingContributionRefs,"empty contribution remains truthful");}finally{await rm(emptyRoot,{recursive:true,force:true});}
  console.log(JSON.stringify({validation:"leadership-conversation-private-working-contribution",result:"PASS",checks:21,selectedArtifacts:2,workflowPlaintext:0,deniedBodyLoads:0,reviewRequired:true,capturePersistence:1,concurrentWinnerCount:1}));
}finally{await rm(workflowRoot,{recursive:true,force:true});await rm(lineageRoot,{recursive:true,force:true});}}
void main().catch(error=>{console.error(error);process.exitCode=1});
