import {createHash} from "node:crypto";
export const SOURCE_SCOPED_ANALYSIS_VERSION="chief-v1-source-scoped-analysis-v1" as const;
export const SOURCE_SCOPED_SCHEMA_ID="chief-v1-source-scoped-output-v1" as const;
export const SOURCE_SCOPED_PROMPT_ID="chief-v1-source-scoped-prompt-v1" as const;
export const DEFAULT_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS=180000;
export const MIN_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS=30000;
export const MAX_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS=900000;
export type SourceScopedCitationV1={sourceId:string;sourceVersion:string;bodyDigest:string;sourcePacketDigest:string};
export type SourceScopedItemV1={statement:string;citations:SourceScopedCitationV1[];factCheck:"PASS"|"HUMAN REVIEW REQUIRED"};
export type SourceScopedSectionsV1={whatMattersNow:SourceScopedItemV1[];whyItMatters:SourceScopedItemV1[];competingExplanations:SourceScopedItemV1[];whatChanged:SourceScopedItemV1[];decisions:SourceScopedItemV1[];notDecided:SourceScopedItemV1[];commitments:SourceScopedItemV1[];openQuestions:SourceScopedItemV1[];contradictions:SourceScopedItemV1[];evidenceUncertainty:SourceScopedItemV1[];modelUncertainty:SourceScopedItemV1[];organizationalDisagreement:SourceScopedItemV1[];attention:SourceScopedItemV1[];whatWouldChangeAssessment:SourceScopedItemV1[]};
export type SourceScopedSourceV1={organizationId:string;sourceId:string;sourceVersion:string;title:string;effectiveAt:string;authority:"authoritative"|"preliminary";bodyDigest:string;body:string;entryDigest:string};
export type SourceScopedPacketV1={contractVersion:"1";organizationId:string;subjectId:string;questionId:string;seriesId:string;occurrenceId:string;sources:SourceScopedSourceV1[];packetDigest:string};
export type SourceScopedModelConfigurationV1={contractVersion:"1";providerFamily:string;model:string;reasoning:"high";maxOutputTokens:25000;timeoutMs:number;store:false;tools:[];schemaId:typeof SOURCE_SCOPED_SCHEMA_ID;promptId:typeof SOURCE_SCOPED_PROMPT_ID;configurationDigest:string};
export type SourceScopedRequestV1={contractVersion:"1";packet:SourceScopedPacketV1;question:string;configuration:SourceScopedModelConfigurationV1;prompt:string;promptDigest:string;schemaDigest:string;requestDigest:string};
export type SourceScopedUsageV1={inputTokens:number;outputTokens:number;totalTokens:number;latencyMs:number;returnedModel:string};
export type SourceScopedCandidateV1={contractVersion:"1";status:"user-scoped-ai-generated-noncanonical-not-reviewed";organizationId:string;subjectId:string;questionId:string;seriesId:string;occurrenceId:string;requestDigest:string;sourcePacketDigest:string;configurationDigest:string;model:string;sections:SourceScopedSectionsV1;usage:SourceScopedUsageV1;candidateDigest:string};
export type SourceScopedResultV1={contractVersion:"1";status:"eligible";candidate:SourceScopedCandidateV1;dispatchCount:1;resultDigest:string}|{contractVersion:"1";status:"analysis-unavailable";dispatchCount:0|1;resultDigest:string};
export type SourceScopedTransportV1=(input:{request:SourceScopedRequestV1;requestBytes:string})=>Promise<unknown>;
export const sourceScopedStable=(value:unknown):string=>{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(sourceScopedStable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${sourceScopedStable(item)}`).join(",")}}`;};
export const sourceScopedDigest=(value:unknown)=>createHash("sha256").update(typeof value==="string"?value:sourceScopedStable(value)).digest("hex");
const exact=(value:unknown,keys:string[])=>Boolean(value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).sort().join("\0")===[...keys].sort().join("\0"));
export function assertSourceScopedModelConfiguration(value:SourceScopedModelConfigurationV1){if(!exact(value,["contractVersion","providerFamily","model","reasoning","maxOutputTokens","timeoutMs","store","tools","schemaId","promptId","configurationDigest"])||value.contractVersion!=="1"||!value.providerFamily||!value.model||value.reasoning!=="high"||value.maxOutputTokens!==25000||!Number.isSafeInteger(value.timeoutMs)||value.timeoutMs<MIN_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS||value.timeoutMs>MAX_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS||value.store!==false||!Array.isArray(value.tools)||value.tools.length!==0||value.schemaId!==SOURCE_SCOPED_SCHEMA_ID||value.promptId!==SOURCE_SCOPED_PROMPT_ID)throw new Error("Source-scoped model configuration is invalid.");const{configurationDigest,...base}=value;if(sourceScopedDigest(base)!==configurationDigest)throw new Error("Source-scoped model configuration integrity failed.");}
export function assertSourceScopedPacket(value:SourceScopedPacketV1){if(!exact(value,["contractVersion","organizationId","subjectId","questionId","seriesId","occurrenceId","sources","packetDigest"])||value.contractVersion!=="1"||!Array.isArray(value.sources)||!value.sources.length)throw new Error("Source-scoped packet is invalid.");const ids=new Set<string>();for(const source of value.sources){if(!exact(source,["organizationId","sourceId","sourceVersion","title","effectiveAt","authority","bodyDigest","body","entryDigest"])||source.organizationId!==value.organizationId||ids.has(source.sourceId))throw new Error("Source-scoped source is invalid.");const{entryDigest,...base}=source;if(!source.sourceId||!source.body||!/^[a-f0-9]{64}$/.test(source.bodyDigest)||sourceScopedDigest(source.body)!==source.bodyDigest||sourceScopedDigest(base)!==entryDigest)throw new Error("Source-scoped source is invalid.");ids.add(source.sourceId);}const{packetDigest,...base}=value;if(sourceScopedDigest(base)!==packetDigest)throw new Error("Source-scoped packet integrity failed.");}
export function assertSourceScopedCandidate(value:SourceScopedCandidateV1,request:SourceScopedRequestV1){if(!exact(value,["contractVersion","status","organizationId","subjectId","questionId","seriesId","occurrenceId","requestDigest","sourcePacketDigest","configurationDigest","model","sections","usage","candidateDigest"])||value.status!=="user-scoped-ai-generated-noncanonical-not-reviewed"||value.requestDigest!==request.requestDigest||value.sourcePacketDigest!==request.packet.packetDigest||value.configurationDigest!==request.configuration.configurationDigest||value.model!==request.configuration.model||!exact(value.sections,["whatMattersNow","whyItMatters","competingExplanations","whatChanged","decisions","notDecided","commitments","openQuestions","contradictions","evidenceUncertainty","modelUncertainty","organizationalDisagreement","attention","whatWouldChangeAssessment"])||!exact(value.usage,["inputTokens","outputTokens","totalTokens","latencyMs","returnedModel"])||value.usage.returnedModel!==value.model||![value.usage.inputTokens,value.usage.outputTokens,value.usage.totalTokens,value.usage.latencyMs].every(item=>Number.isSafeInteger(item)&&item>=0)||value.usage.totalTokens!==value.usage.inputTokens+value.usage.outputTokens)throw new Error("Source-scoped candidate is invalid.");const allowed=new Map(request.packet.sources.map(source=>[source.sourceId,source]));for(const items of Object.values(value.sections)){if(!Array.isArray(items))throw new Error("Source-scoped sections are invalid.");for(const item of items){if(!exact(item,["statement","citations","factCheck"])||!item.statement||!Array.isArray(item.citations)||!item.citations.length||!["PASS","HUMAN REVIEW REQUIRED"].includes(item.factCheck))throw new Error("Source-scoped claim is invalid.");for(const citation of item.citations){if(!exact(citation,["sourceId","sourceVersion","bodyDigest","sourcePacketDigest"]))throw new Error("Source-scoped citation is invalid.");const source=allowed.get(citation.sourceId);if(!source||citation.sourceVersion!==source.sourceVersion||citation.bodyDigest!==source.bodyDigest||citation.sourcePacketDigest!==request.packet.packetDigest)throw new Error("Source-scoped citation is invalid.");}}}const{candidateDigest,...base}=value;if(sourceScopedDigest(base)!==candidateDigest)throw new Error("Source-scoped candidate integrity failed.");}
export function unavailable(dispatchCount:0|1):SourceScopedResultV1{const base={contractVersion:"1" as const,status:"analysis-unavailable" as const,dispatchCount};return{...base,resultDigest:sourceScopedDigest(base)};}
