import "server-only";
import path from "node:path";
import { createHash } from "node:crypto";
import { resolvePersonaForSignedInUser, SANDBOX_ORGANIZATION_ID } from "../../lib/access/sandboxMultiUserAccess";
import { createProductWorkflowArtifactRepository } from "../workflow/leadershipConversation/productWorkflowArtifactRepository";
import { readNorthstarPreparationLineageSeed } from "../simulations/living-organization-sandbox/preparationLineageFixtureProvisioner";
export type AuthorizedMeetingCardV1={seriesAddress:string;title:string;timeframe:string;phase:"Prepare"|"Meet"|"Confirm outcomes"|"Continue";packStatus:"Pack ready"|"Needs preparation";nextAction:string;materialChangeCount:number|null};
export type AuthorizedMeetingResolutionV1=AuthorizedMeetingCardV1&{organizationId:string;questionId:string;seriesId:string;occurrenceId:string;predecessorOccurrenceId:string|null};
const address=(organizationId:string,seriesId:string)=>createHash("sha256").update(`meeting-series-address:v1:${organizationId}:${seriesId}`).digest("base64url").slice(0,24);
const userScope=(userId:string)=>createHash("sha256").update(JSON.stringify({owner:"leadership-conversation-private-working",userId})).digest("hex");
function canAddress(persona:ReturnType<typeof resolvePersonaForSignedInUser>,title:string){if(!persona)return false;if(persona.key==="sandbox-ceo")return true;if(persona.key==="sandbox-director")return title!=="Northstar Staff Conversation";if(persona.key==="sandbox-manager")return title==="Pipeline Review";return false;}
export async function authorizedMeetingDirectory(input:{userId:string;organizationId:string}):Promise<AuthorizedMeetingResolutionV1[]>{
 const persona=resolvePersonaForSignedInUser(input.userId);if(!persona||input.organizationId!==SANDBOX_ORGANIZATION_ID)return[];const fixtureRoot=process.env.DISCOVERY_NORTHSTAR_PREPARATION_LINEAGE_FIXTURE_ROOT;if(!fixtureRoot)return[];
 const seed=await readNorthstarPreparationLineageSeed({fixtureRoot,organizationId:SANDBOX_ORGANIZATION_ID,fixtureId:"northstar-preparation-lineage-fixture-v1",provisioningKey:"northstar-preparation-lineage:v1"});
 const repository=createProductWorkflowArtifactRepository({root:process.env.DISCOVERY_LEADERSHIP_CONVERSATION_WORKFLOW_ROOT??path.join(process.cwd(),".discovery-runtime/product-workflow"),environment:"development"}),{store}=await repository.read(input.organizationId),contexts=store.contexts.filter(value=>value.organizationId===input.organizationId&&value.questionId===seed.productQuestionId),scope=userScope(input.userId),result:AuthorizedMeetingResolutionV1[]=[];
 for(const initial of contexts.filter(context=>!store.futurePreparationLinks.some(link=>link.nextConversationId===context.conversationId))){if(!canAddress(persona,initial.title))continue;const closure=(store.cycle1ClosureCompletions??[]).find(value=>value.questionId===seed.productQuestionId&&value.conversationId===initial.conversationId),link=store.futurePreparationLinks.find(value=>value.questionId===seed.productQuestionId&&value.conversationId===initial.conversationId),current=link?contexts.find(value=>value.conversationId===link.nextConversationId):initial;if(!current)continue;const seriesId=closure?.seriesId??`leadership-conversation-series:${initial.conversationId}`,pack=(store.meetingPackPublications??[]).filter(value=>value.questionId===seed.productQuestionId&&value.seriesId===seriesId&&value.occurrenceId===current.conversationId&&value.userScopeDigest===scope).at(-1),phase=link?"Continue" as const:closure?"Confirm outcomes" as const:"Prepare" as const,changes=(store.whatChangedPublications??[]).filter(value=>value.productQuestionId===seed.productQuestionId&&value.productWorkflowId===`leadership-conversation:${initial.conversationId}`).length;result.push({organizationId:input.organizationId,questionId:seed.productQuestionId,seriesId,occurrenceId:current.conversationId,predecessorOccurrenceId:link?initial.conversationId:null,seriesAddress:address(input.organizationId,seriesId),title:initial.title,timeframe:current.timeframe,phase,packStatus:pack?"Pack ready":"Needs preparation",nextAction:pack?(phase==="Continue"?"Continue current lifecycle":"Review or start meeting"):"Build my meeting pack",materialChangeCount:changes||null});}
 return result.sort((a,b)=>a.title.localeCompare(b.title));
}
export async function resolveAuthorizedMeetingAddress(input:{userId:string;organizationId:string;seriesAddress:string}){if(!/^[A-Za-z0-9_-]{24}$/.test(input.seriesAddress))return null;const matches=(await authorizedMeetingDirectory(input)).filter(item=>item.seriesAddress===input.seriesAddress);return matches.length===1?matches[0]!:null;}
