import type { CanonicalSourceScopeBinding } from "../../engine/v3/governance/canonicalScopeLineage";
import type { CanonicalProductWorkspaceAdapter } from "./canonicalProductWorkspaceAdapter";
import type { ProductDecisionDraftService } from "./productDecisionDraftService";
import { deriveProductUnknownCandidate } from "../unknowns/unknownLifecycle";
import { canonicalRoutingCompatibilityReferences, type LeadershipConversationCanonicalChangeFactsV1, type LeadershipConversationCanonicalRoutingReceiptV1, type LeadershipConversationClock, type LeadershipConversationSourceGateway, type ProductWorkflowArtifactRepository } from "../workflow/leadershipConversation";
import { leadershipDigest, leadershipId, leadershipStableSerialize } from "../workflow/leadershipConversation/determinism";

export type RouteApprovedLeadershipConversationProposalInput={userId:string;organizationId:string;questionId:string;conversationId:string;proposalId:string;purposeRef:string;expectedWorkflowRevision:string|null;idempotencyKey:string};
export type CanonicalLeadershipConversationOwnerRouterDependencies={repository:ProductWorkflowArtifactRepository;source:LeadershipConversationSourceGateway;productAdapter:CanonicalProductWorkspaceAdapter;decisionDraftService:ProductDecisionDraftService;clock:LeadershipConversationClock;authorize(input:{userId:string;organizationId:string;questionId:string;operation:"canonical-owner:route"}):Promise<boolean>;resolveCurrentSourceBinding(input:{userId:string;organizationId:string;questionId:string;sourceBindingId:string;sourceType:"pasted-text"|"plain-text-upload"|"markdown-upload";normalizedContentDigest:string;purposeRef:string;evaluatedAt:string}):Promise<CanonicalSourceScopeBinding>};
const safe=<T>(v:T)=>JSON.parse(JSON.stringify(v)) as T;
const hash=(v:unknown)=>leadershipDigest(leadershipStableSerialize(v));
const meaning=(workspace:any)=>hash({answer:workspace.answer,modelState:workspace.modelState,latestChange:workspace.latestChange});
const answer=(workspace:any)=>hash(workspace.answer);

export class CanonicalLeadershipConversationOwnerRouter{
  constructor(private readonly d:CanonicalLeadershipConversationOwnerRouterDependencies){}
  async routeApproved(input:RouteApprovedLeadershipConversationProposalInput):Promise<LeadershipConversationCanonicalRoutingReceiptV1>{
    if(!await this.d.authorize({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,operation:"canonical-owner:route"}))throw new Error("Leadership Conversation routing denied.");
    const snapshot=await this.d.repository.read(input.organizationId);if(snapshot.revision!==input.expectedWorkflowRevision)throw new Error("Leadership Conversation workflow revision changed.");
    const proposal=snapshot.store.proposals.find(v=>v.proposalId===input.proposalId),disposition=snapshot.store.dispositions.filter(v=>v.proposalId===input.proposalId).at(-1);
    if(!proposal||proposal.organizationId!==input.organizationId||proposal.questionId!==input.questionId||proposal.conversationId!==input.conversationId||!disposition||!disposition.disposition.startsWith("approved"))throw new Error("Leadership Conversation routing denied.");
    if(hash(proposal.payload)!==proposal.payloadDigest||disposition.originalPayloadDigest!==proposal.payloadDigest||(disposition.effectivePayload&&hash(disposition.effectivePayload)!==disposition.effectivePayloadDigest))throw new Error("Leadership Conversation routing integrity failed.");
    const keyDigest=hash(input.idempotencyKey),requestFingerprint=hash({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,proposalId:proposal.proposalId,dispositionReceiptId:disposition.dispositionReceiptId,purposeRef:input.purposeRef}),prior=snapshot.store.idempotency.find(v=>v.keyDigest===keyDigest);
    if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new Error("Leadership Conversation idempotency conflict.");const replay=snapshot.store.canonicalRoutingReceipts.find(v=>v.integrationReceiptId===prior.recordRef);if(!replay)throw new Error("Leadership Conversation routing replay is unavailable.");return safe(replay);}
    const routedAt=this.d.clock.now(),operationId=leadershipId("canonical-owner-operation",proposal.proposalId,disposition.dispositionReceiptId),payload=disposition.effectivePayload??proposal.payload,before=await this.d.productAdapter.getQuestionWorkspace({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId});
    let owner:any;let changeFacts:LeadershipConversationCanonicalChangeFactsV1;
    if(proposal.kind==="evidence-candidate"){
      const upload=snapshot.store.uploadReceipts.find(v=>v.uploadReceiptId===proposal.uploadReceiptId);if(!upload)throw new Error("Leadership Conversation source integrity failed.");
      const binding=await this.d.resolveCurrentSourceBinding({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,sourceBindingId:proposal.sourceBindingId,sourceType:upload.mediaType==="text/markdown"?"markdown-upload":"plain-text-upload",normalizedContentDigest:upload.normalizedContentDigest,purposeRef:input.purposeRef,evaluatedAt:routedAt});if(binding.bindingId!==proposal.sourceBindingId||binding.organizationId!==input.organizationId||binding.purposeRef!==input.purposeRef||binding.availability!=="available")throw new Error("Leadership Conversation source binding is unavailable.");
      const source=await this.d.source.readForEvidenceAdmission({organizationId:input.organizationId,sourceBindingId:binding.bindingId,sourceContentVersionId:proposal.sourceContentVersionId,purposeRef:input.purposeRef,userId:input.userId,proposalId:proposal.proposalId,dispositionReceiptId:disposition.dispositionReceiptId});
      if(!upload||source.exactContentDigest!==upload.exactContentDigest||source.normalizedContentDigest!==upload.normalizedContentDigest||binding.source.normalizedContentDigest!==source.normalizedContentDigest)throw new Error("Leadership Conversation source integrity failed.");
      const result=await this.d.productAdapter.contributeEvidenceWithCanonicalResult({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,contribution:{sourceId:binding.source.sourceId,sourceType:"paste",content:source.text,contributedAt:routedAt,idempotencyKey:operationId},operation:{requestId:operationId,operatorId:input.userId}});
      changeFacts={proposalRouted:true,productArtifactRecorded:true,evidenceAdmitted:result.contributionResult.admissions.length>0,runtimeRepository:result.contributionResult.runtimeRevisionBefore===result.contributionResult.runtimeRevisionAfter?"unchanged":"changed",organizationalUnderstanding:meaning(before.workspace)===meaning(result.workspace)?"unchanged":"changed",answer:answer(before.workspace)===answer(result.workspace)?"unchanged":"changed",unknown:"unchanged",learning:"undetermined"};
      owner={ownerKind:"evidence",canonicalOperation:"canonical-evidence:contribute",sourceBindingId:binding.bindingId,sourceContentVersionId:proposal.sourceContentVersionId,contributionOperationId:result.contributionResult.contributionOperationId,operationDisposition:result.contributionResult.operationDisposition,admissions:safe(result.contributionResult.admissions),runtimeRevisionBefore:result.contributionResult.runtimeRevisionBefore,runtimeRevisionAfter:result.contributionResult.runtimeRevisionAfter,productQuestionRevisionBefore:result.contributionResult.productQuestionRevisionBefore,productQuestionRevisionAfter:result.contributionResult.productQuestionRevisionAfter};
    }else if(proposal.kind==="decision-draft"){
      const current=before.workspace.answer,sourceAnswerId=current&&"id" in current?current.id:before.workspace.question.currentAnswerId;if(!sourceAnswerId)throw new Error("Product Decision Draft requires an exact Product Answer.");const result=await this.d.decisionDraftService.create({userId:input.userId,request:{contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,sourceAnswerId,draftId:null,expectedQuestionRevision:before.workspace.question.revision,expectedCurrentRevision:null,predecessorRevisionId:null,originatingProposalRef:proposal.proposalId,content:{title:payload.summary,intervention:payload.summary,rationale:payload.summary,assumptions:[],risks:[],expectedOutcomes:[],measures:[],intendedDecisionMakerRef:payload.targetRef,intendedDecisionMakerLabel:null,proposedReviewDate:null},recordedAt:routedAt,idempotencyKey:operationId},storageOperation:{requestId:operationId,operatorId:input.userId}});
      changeFacts={proposalRouted:true,productArtifactRecorded:true,evidenceAdmitted:false,runtimeRepository:result.runtimeRevision===before.runtimeRevision?"unchanged":"changed",organizationalUnderstanding:"unchanged",answer:"unchanged",unknown:"unchanged",learning:"unchanged"};owner={ownerKind:"product-decision-draft",canonicalOperation:"product-decision-draft:create",draftId:result.revision.draftId,draftRevisionId:result.revision.revisionId,draftRevision:result.revision.revision,ownerReceiptId:result.receipt.receiptId,ownerReceiptDigest:result.receipt.receiptDigest,runtimeRevision:result.runtimeRevision,idempotent:result.idempotent};
    }else if(proposal.kind==="unknown"){
      const candidate=deriveProductUnknownCandidate({organizationId:input.organizationId,questionId:input.questionId,category:"missing-evidence",target:{kind:"assumption",assumptionRef:proposal.proposalId},summary:payload.summary,whyItMatters:payload.summary,sourceAncestry:[{kind:"governed-determination",id:disposition.dispositionReceiptId}]});const result=await this.d.productAdapter.mutateUnknown({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,operationId,occurredAt:routedAt,actorRef:input.userId,candidate,transition:{type:"open"},reason:"Approved Leadership Conversation proposal.",operation:{requestId:operationId,operatorId:input.userId}});
      changeFacts={proposalRouted:true,productArtifactRecorded:true,evidenceAdmitted:false,runtimeRepository:result.runtimeRevision===before.runtimeRevision?"unchanged":"changed",organizationalUnderstanding:"unchanged",answer:"unchanged",unknown:"changed",learning:"unchanged"};owner={ownerKind:"unknown",canonicalOperation:"product-unknown:open",unknownId:result.unknown.unknownId,ownerEventId:result.receipt.eventId,ownerResult:result.receipt.result,runtimeRevision:result.runtimeRevision};
    }else if(proposal.kind==="follow-up-question"){
      const result=await this.d.productAdapter.createQuestion({userId:input.userId,organizationId:input.organizationId,question:payload.summary,createdAt:routedAt,idempotencyKey:operationId,operation:{requestId:operationId,operatorId:input.userId}});changeFacts={proposalRouted:true,productArtifactRecorded:true,evidenceAdmitted:false,runtimeRepository:result.runtimeRevision===before.runtimeRevision?"unchanged":"changed",organizationalUnderstanding:"unchanged",answer:"unchanged",unknown:"unchanged",learning:"unchanged"};owner={ownerKind:"follow-up-product-question",canonicalOperation:"product-question:create",createdQuestionId:result.workspace.question.id,createdQuestionRevision:result.workspace.question.revision,runtimeRevision:result.runtimeRevision};
    }else if(proposal.kind==="commitment"||proposal.kind==="assumption-change"||proposal.kind==="correction"){
      if(proposal.kind==="correction"&&!payload.targetRef)throw new Error("Correction requires an explicit target.");changeFacts={proposalRouted:true,productArtifactRecorded:true,evidenceAdmitted:false,runtimeRepository:"unchanged",organizationalUnderstanding:"unchanged",answer:"unchanged",unknown:"unchanged",learning:"unchanged"};owner={ownerKind:proposal.kind,canonicalOperation:`leadership-conversation:${proposal.kind}:record`,workflowRecordId:leadershipId(`leadership-${proposal.kind}`,proposal.proposalId,disposition.dispositionReceiptId,hash(payload)),targetRef:payload.targetRef,nonAuthoritative:true};
    }else throw new Error("Leadership Conversation proposal kind is not executable.");
    const common={contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,proposalId:proposal.proposalId,dispositionReceiptId:disposition.dispositionReceiptId,integrationOperationId:operationId,routedAt,...owner},canonicalResultDigest=hash({common,changeFacts}),integrationReceiptId=leadershipId("leadership-canonical-routing-receipt",operationId,canonicalResultDigest),unsigned={...common,integrationReceiptId,canonicalResultDigest,changeFacts,idempotencyKeyDigest:keyDigest,requestFingerprint},receipt={...unsigned,receiptDigest:hash(unsigned)} as LeadershipConversationCanonicalRoutingReceiptV1;
    const store=safe(snapshot.store);store.canonicalRoutingReceipts.push(receipt);const routingLinkId=leadershipId("canonical-routing-link",operationId,receipt.integrationReceiptId),compatibilityReferences=canonicalRoutingCompatibilityReferences(receipt);store.routingLinks.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,routingLinkId,proposalId:proposal.proposalId,dispositionReceiptId:disposition.dispositionReceiptId,targetOwner:proposal.targetOwner,integrationReceiptId:receipt.integrationReceiptId,integrationReceiptDigest:receipt.receiptDigest,compatibilityReferences,routedAt,idempotencyKeyDigest:keyDigest,requestFingerprint});const classification=changeFacts.organizationalUnderstanding==="changed"?"changed":changeFacts.organizationalUnderstanding==="unchanged"?"unchanged":"undetermined",changeLinkId=leadershipId("leadership-change-link",routingLinkId,receipt.integrationReceiptId);store.changeLinks.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,changeLinkId,routingLinkIds:[routingLinkId],integrationReceiptId:receipt.integrationReceiptId,changeFacts,classification,linkedAt:routedAt,idempotencyKeyDigest:keyDigest,requestFingerprint});
    for(const [eventType,recordRef,recordDigest] of [["canonical-routing-receipt-recorded",receipt.integrationReceiptId,receipt.receiptDigest],["canonical-owner-routing-linked",routingLinkId,hash(store.routingLinks.at(-1))],["change-receipt-linked",changeLinkId,hash(store.changeLinks.at(-1))]] as const){const events=store.events.filter(v=>v.questionId===input.questionId),eventSequence=events.length+1;store.events.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,eventId:leadershipId("leadership-event",input.organizationId,input.questionId,eventSequence,eventType,recordRef),eventSequence,previousEventId:events.at(-1)?.eventId??null,eventType,recordRef,recordDigest,occurredAt:routedAt,actorType:"user",actorRef:input.userId,idempotencyKeyDigest:keyDigest,requestFingerprint});}store.idempotency.push({keyDigest,requestFingerprint,recordRef:receipt.integrationReceiptId});
    const persisted=await this.d.repository.replace(input.organizationId,store,snapshot.revision),retained=persisted.store.canonicalRoutingReceipts.find(v=>v.integrationReceiptId===receipt.integrationReceiptId);if(!retained||retained.receiptDigest!==receipt.receiptDigest)throw new Error("Leadership Conversation routing receipt was not persisted.");return safe(retained);
  }
}
