import "server-only";
import type { ProductWorkflowArtifactRepository } from "../workflow/leadershipConversation/productWorkflowArtifactRepository";
import {
  assertHistoricalCheckpointLifecycleLinkIntegrityV1,assertHistoricalCheckpointLifecycleReceiptIntegrityV1,
  createHistoricalCheckpointLifecycleIdentityV1,createHistoricalCheckpointLifecycleLinkDigestV1,
  createHistoricalCheckpointLifecycleProjectionDigestV1,createHistoricalCheckpointLifecycleReceiptDigestV1,
  historicalCheckpointLifecycleDigestV1,type HistoricalCheckpointLifecycleLinkKindV1,
  type HistoricalCheckpointLifecycleLinkProjectionV1,type HistoricalCheckpointLifecycleLinkReceiptV1,
  type HistoricalCheckpointLifecycleLinkV1,type HistoricalCheckpointLifecycleOwnerTypeV1,
  type HistoricalCheckpointLifecyclePersistenceV1,type HistoricalCheckpointLifecyclePublicationResultV1,
  type HistoricalCheckpointUnderstandingRevisionBindingV1,
} from "../workflow/leadershipConversation/historicalCheckpointLifecycleLinkContracts";

type Sensitivity="standard"|"restricted"|"private";
type Base={userId:string;organizationId:string;questionId:string;conversationId:string;checkpointId:string;checkpointRevision:string;purpose:string;scopeDigest:string;sensitivity:Sensitivity;evaluatedAt:string};
type Target=|{linkKind:"product-decision-draft";draftId:string;draftRevisionId:string}|{linkKind:"decision-review";reviewId:string}|{linkKind:"observed-outcome";reviewId:string;expectedOutcomeId:string}|{linkKind:"learning";learningId:string};
export type HistoricalCheckpointLifecyclePublicationRequestV1=Base&Target&{idempotencyKey:string;predecessorLinkId:string|null;expectedWorkflowRevision:string|null};
export type HistoricalCheckpointLifecycleReadRequestV1=Base&{linkId?:string};
type Operation="historical-checkpoint-lifecycle-link:publish"|"historical-checkpoint-lifecycle-link:list"|"historical-checkpoint-lifecycle-link:read";
type AccessInput={userId:string;organizationId:string;questionId:string;operation:Operation;purpose:string;scopeDigest:string;sensitivity:Sensitivity;evaluatedAt:string};
type EndpointIdentity={linkKind:HistoricalCheckpointLifecycleLinkKindV1;linkedRecordId:string;linkedRecordRevision:string|null;linkedSubrecordId:string|null};
type CheckpointProof={checkpointId:string;checkpointRevision:string;checkpointHeaderDigest:string;checkpointPackageDigest:string;productQuestionId:string;productWorkflowId:string;understanding:HistoricalCheckpointUnderstandingRevisionBindingV1;accessResultDigest:string;accessBindingRef:string};
type LinkedProof={canonicalOwnerType:HistoricalCheckpointLifecycleOwnerTypeV1;linkedRecordId:string;linkedRecordRevision:string;linkedOwnerEventId:string|null;linkedOwnerReceiptId:string|null;linkedOwnerIntegrityDigest:string;linkedOwnerPersistence:HistoricalCheckpointLifecyclePersistenceV1;linkedSubrecordId:string|null;accessResultDigest:string;accessBindingRef:string};
type ProofRequest=AccessInput&{checkpointId:string;checkpointRevision:string;endpoint:EndpointIdentity;loadProtected:boolean;expectedUnderstanding?:HistoricalCheckpointUnderstandingRevisionBindingV1};
const clone=<T>(value:T):T=>structuredClone(value);

export class CanonicalHistoricalCheckpointLifecycleLinkRouter{
  constructor(private readonly d:{repository:ProductWorkflowArtifactRepository;clock:{now():string};authorizeOperation(input:AccessInput):Promise<boolean>;resolveCheckpoint(input:ProofRequest):Promise<CheckpointProof|null>;resolveLinkedRecord(input:ProofRequest):Promise<LinkedProof|null>}){}
  private async operation(input:AccessInput){if(!await this.d.authorizeOperation(input))throw new Error("Historical checkpoint lifecycle access denied.");}
  private target(input:HistoricalCheckpointLifecyclePublicationRequestV1):EndpointIdentity{if(input.linkKind==="product-decision-draft")return{linkKind:input.linkKind,linkedRecordId:input.draftId,linkedRecordRevision:input.draftRevisionId,linkedSubrecordId:null};if(input.linkKind==="decision-review")return{linkKind:input.linkKind,linkedRecordId:input.reviewId,linkedRecordRevision:null,linkedSubrecordId:null};if(input.linkKind==="observed-outcome")return{linkKind:input.linkKind,linkedRecordId:input.reviewId,linkedRecordRevision:null,linkedSubrecordId:input.expectedOutcomeId};return{linkKind:input.linkKind,linkedRecordId:input.learningId,linkedRecordRevision:null,linkedSubrecordId:null};}
  private access(input:Base,operation:Operation):AccessInput{return{userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,operation,purpose:input.purpose,scopeDigest:input.scopeDigest,sensitivity:input.sensitivity,evaluatedAt:input.evaluatedAt};}
  private async proofs(input:Base,endpoint:EndpointIdentity,operation:Operation,loadProtected:boolean,expectedUnderstanding?:HistoricalCheckpointUnderstandingRevisionBindingV1){const request={...this.access(input,operation),checkpointId:input.checkpointId,checkpointRevision:input.checkpointRevision,endpoint,loadProtected,...(expectedUnderstanding?{expectedUnderstanding}:{})};const linked=await this.d.resolveLinkedRecord(request);if(!linked)return null;const checkpoint=await this.d.resolveCheckpoint(request);if(!checkpoint)return null;if(checkpoint.productQuestionId!==input.questionId||checkpoint.productWorkflowId!==`leadership-conversation:${input.conversationId}`)return null;if(linked.linkedRecordId!==endpoint.linkedRecordId||linked.linkedSubrecordId!==endpoint.linkedSubrecordId)return null;return{checkpoint,linked};}
  private projection(link:HistoricalCheckpointLifecycleLinkV1,proofs:{checkpoint:CheckpointProof;linked:LinkedProof}):HistoricalCheckpointLifecycleLinkProjectionV1{const unsigned={contractVersion:"1" as const,linkId:link.linkId,linkKind:link.linkKind,checkpointId:link.checkpointId,linkedRecordId:link.linkedRecordId,linkedRecordRevision:link.linkedRecordRevision,linkedSubrecordId:link.linkedSubrecordId,occurredAt:link.occurredAt,accessResultDigests:[proofs.checkpoint.accessResultDigest,proofs.linked.accessResultDigest] as [string,string]};return{...unsigned,projectionDigest:createHistoricalCheckpointLifecycleProjectionDigestV1(unsigned)};}
  async publish(input:HistoricalCheckpointLifecyclePublicationRequestV1):Promise<HistoricalCheckpointLifecyclePublicationResultV1>{const operation=this.access(input,"historical-checkpoint-lifecycle-link:publish");await this.operation(operation);const endpoint=this.target(input),proofs=await this.proofs(input,endpoint,operation.operation,true);if(!proofs)throw new Error("Historical checkpoint lifecycle endpoint is inaccessible.");return this.persist(input,proofs.checkpoint,proofs.linked);}
  private async persist(input:HistoricalCheckpointLifecyclePublicationRequestV1,checkpoint:CheckpointProof,linked:LinkedProof):Promise<HistoricalCheckpointLifecyclePublicationResultV1>{const current=await this.d.repository.read(input.organizationId);const store=clone(current.store);store.historicalCheckpointLifecycleLinks??=[];store.historicalCheckpointLifecycleLinkReceipts??=[];const header=(store.frozenSnapshotPublications??[]).find(value=>value.artifactId===input.checkpointId&&value.artifactRevision===input.checkpointRevision);if(!header||header.headerDigest!==checkpoint.checkpointHeaderDigest||header.protectedBody.refDigest!==checkpoint.checkpointPackageDigest)throw new Error("Historical checkpoint lifecycle checkpoint is unavailable.");const expectedOwner=input.linkKind==="product-decision-draft"?"product-decision-draft":input.linkKind==="learning"?"executive-learning":"executive-review",expectedPersistence=input.linkKind==="product-decision-draft"?"organization-runtime-event":input.linkKind==="learning"?"organization-runtime-learning":"organization-runtime-review";if(linked.canonicalOwnerType!==expectedOwner||linked.linkedOwnerPersistence!==expectedPersistence)throw new Error("Historical checkpoint lifecycle owner kind mismatch.");if((input.linkKind==="observed-outcome")!==Boolean(linked.linkedSubrecordId))throw new Error("Historical checkpoint lifecycle subrecord mismatch.");if(input.predecessorLinkId){const predecessor=store.historicalCheckpointLifecycleLinks.find(value=>value.linkId===input.predecessorLinkId&&value.checkpointId===input.checkpointId);if(!predecessor)throw new Error("Historical checkpoint lifecycle predecessor is unavailable.");if(store.historicalCheckpointLifecycleLinks.some(value=>value.predecessorLinkId===input.predecessorLinkId&&value.linkKind===input.linkKind))throw new Error("Historical checkpoint lifecycle successor fork denied.");}
    const keyDigest=historicalCheckpointLifecycleDigestV1(input.idempotencyKey),requestFingerprint=historicalCheckpointLifecycleDigestV1({organizationId:input.organizationId,productQuestionId:input.questionId,productWorkflowId:checkpoint.productWorkflowId,checkpointId:checkpoint.checkpointId,checkpointRevision:checkpoint.checkpointRevision,checkpointHeaderDigest:checkpoint.checkpointHeaderDigest,checkpointPackageDigest:checkpoint.checkpointPackageDigest,understanding:checkpoint.understanding,linkKind:input.linkKind,linked,predecessorLinkId:input.predecessorLinkId,actorRef:input.userId,operation:"historical-checkpoint-lifecycle-link:publish",purpose:input.purpose,scopeDigest:input.scopeDigest,sensitivity:input.sensitivity,checkpointAccessBindingRef:checkpoint.accessBindingRef,linkedAccessBindingRef:linked.accessBindingRef});
    const prior=store.idempotency.find(value=>value.keyDigest===keyDigest);if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new Error("Historical checkpoint lifecycle idempotency conflict.");const link=store.historicalCheckpointLifecycleLinks.find(value=>value.linkId===prior.recordRef),receipt=link&&store.historicalCheckpointLifecycleLinkReceipts.find(value=>value.linkId===link.linkId);if(!link||!receipt)throw new Error("Historical checkpoint lifecycle replay state is incomplete.");assertHistoricalCheckpointLifecycleLinkIntegrityV1(link);assertHistoricalCheckpointLifecycleReceiptIntegrityV1(receipt);return{link:clone(link),receipt:clone(receipt),idempotent:true,repository:{disposition:"replayed",committedWorkflowRepositoryRevision:null,currentWorkflowRepositoryRevision:current.revision}};}if(current.revision!==input.expectedWorkflowRevision)throw new Error("Product Workflow store revision changed.");
    const identity={organizationId:input.organizationId,productWorkflowId:checkpoint.productWorkflowId,checkpointId:checkpoint.checkpointId,checkpointRevision:checkpoint.checkpointRevision,linkKind:input.linkKind,linkedRecordId:linked.linkedRecordId,linkedRecordRevision:linked.linkedRecordRevision,linkedSubrecordId:linked.linkedSubrecordId,predecessorLinkId:input.predecessorLinkId,requestFingerprint},linkId=createHistoricalCheckpointLifecycleIdentityV1("link",identity),receiptId=createHistoricalCheckpointLifecycleIdentityV1("receipt",identity),eventId=createHistoricalCheckpointLifecycleIdentityV1("event",identity),occurredAt=this.d.clock.now();
    if(store.historicalCheckpointLifecycleLinks.some(value=>value.linkId===linkId)||store.historicalCheckpointLifecycleLinkReceipts.some(value=>value.receiptId===receiptId)||store.events.some(value=>value.eventId===eventId))throw new Error("Historical checkpoint lifecycle identity collision.");
    const unsignedLink={contractVersion:"1" as const,organizationId:input.organizationId,productQuestionId:input.questionId,productWorkflowId:checkpoint.productWorkflowId,checkpointId:checkpoint.checkpointId,checkpointRevision:checkpoint.checkpointRevision,checkpointHeaderDigest:checkpoint.checkpointHeaderDigest,checkpointPackageDigest:checkpoint.checkpointPackageDigest,understanding:checkpoint.understanding,linkKind:input.linkKind,linkId,predecessorLinkId:input.predecessorLinkId,canonicalOwnerType:linked.canonicalOwnerType,linkedRecordId:linked.linkedRecordId,linkedRecordRevision:linked.linkedRecordRevision,linkedOwnerEventId:linked.linkedOwnerEventId,linkedOwnerReceiptId:linked.linkedOwnerReceiptId,linkedOwnerIntegrityDigest:linked.linkedOwnerIntegrityDigest,linkedOwnerPersistence:linked.linkedOwnerPersistence,linkedSubrecordId:linked.linkedSubrecordId,actorRef:input.userId,operation:"historical-checkpoint-lifecycle-link:publish" as const,purpose:input.purpose,scopeDigest:input.scopeDigest,sensitivity:input.sensitivity,occurredAt,checkpointAccessBindingRef:checkpoint.accessBindingRef,linkedAccessBindingRef:linked.accessBindingRef,requestFingerprint,idempotencyKeyDigest:keyDigest,workflowEventId:eventId,workflowReceiptId:receiptId};const link:HistoricalCheckpointLifecycleLinkV1={...unsignedLink,linkDigest:createHistoricalCheckpointLifecycleLinkDigestV1(unsignedLink)};
    const unsignedReceipt={contractVersion:"1" as const,receiptId,organizationId:input.organizationId,productQuestionId:input.questionId,productWorkflowId:checkpoint.productWorkflowId,checkpointId:checkpoint.checkpointId,linkId,linkKind:input.linkKind,linkedRecordId:linked.linkedRecordId,linkedRecordRevision:linked.linkedRecordRevision,linkedSubrecordId:linked.linkedSubrecordId,workflowEventId:eventId,workflowCasBaseRevision:current.revision,requestFingerprint,idempotencyKeyDigest:keyDigest,occurredAt};const receipt:HistoricalCheckpointLifecycleLinkReceiptV1={...unsignedReceipt,receiptDigest:createHistoricalCheckpointLifecycleReceiptDigestV1(unsignedReceipt)};assertHistoricalCheckpointLifecycleLinkIntegrityV1(link);assertHistoricalCheckpointLifecycleReceiptIntegrityV1(receipt);
    const events=store.events.filter(value=>value.questionId===input.questionId),sequence=events.length+1,previousEventId=events.at(-1)?.eventId??null;store.historicalCheckpointLifecycleLinks.push(link);store.historicalCheckpointLifecycleLinkReceipts.push(receipt);store.events.push({contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,eventId,eventSequence:sequence,previousEventId,eventType:"historical-checkpoint-lifecycle-link-published",recordRef:linkId,recordDigest:link.linkDigest,occurredAt,actorType:"user",actorRef:input.userId,idempotencyKeyDigest:keyDigest,requestFingerprint});store.idempotency.push({keyDigest,requestFingerprint,recordRef:linkId});
    try{const committed=await this.d.repository.replace(input.organizationId,store,current.revision);return{link:clone(link),receipt:clone(receipt),idempotent:false,repository:{disposition:"committed",committedWorkflowRepositoryRevision:committed.revision,currentWorkflowRepositoryRevision:committed.revision}};}catch(error){const latest=await this.d.repository.read(input.organizationId),winner=latest.store.idempotency.find(value=>value.keyDigest===keyDigest);if(!winner||winner.requestFingerprint!==requestFingerprint)throw error;const replayLink=(latest.store.historicalCheckpointLifecycleLinks??[]).find(value=>value.linkId===winner.recordRef),replayReceipt=replayLink&&(latest.store.historicalCheckpointLifecycleLinkReceipts??[]).find(value=>value.linkId===replayLink.linkId);if(!replayLink||!replayReceipt)throw error;return{link:clone(replayLink),receipt:clone(replayReceipt),idempotent:true,repository:{disposition:"replayed",committedWorkflowRepositoryRevision:null,currentWorkflowRepositoryRevision:latest.revision}};}}
  async list(input:HistoricalCheckpointLifecycleReadRequestV1):Promise<HistoricalCheckpointLifecycleLinkProjectionV1[]>{await this.operation(this.access(input,"historical-checkpoint-lifecycle-link:list"));const store=(await this.d.repository.read(input.organizationId)).store,result:HistoricalCheckpointLifecycleLinkProjectionV1[]=[];for(const link of (store.historicalCheckpointLifecycleLinks??[]).filter(value=>value.checkpointId===input.checkpointId&&value.checkpointRevision===input.checkpointRevision)){try{assertHistoricalCheckpointLifecycleLinkIntegrityV1(link);const proofs=await this.proofs(input,{linkKind:link.linkKind,linkedRecordId:link.linkedRecordId,linkedRecordRevision:link.linkedRecordRevision,linkedSubrecordId:link.linkedSubrecordId},"historical-checkpoint-lifecycle-link:list",false,link.understanding);if(proofs&&historicalCheckpointLifecycleDigestV1(proofs.checkpoint.understanding)===historicalCheckpointLifecycleDigestV1(link.understanding))result.push(this.projection(link,proofs));}catch{/* indistinguishable omission */}}return result;}
  async read(input:HistoricalCheckpointLifecycleReadRequestV1&{linkId:string}):Promise<HistoricalCheckpointLifecycleLinkProjectionV1|null>{await this.operation(this.access(input,"historical-checkpoint-lifecycle-link:read"));const link=(await this.d.repository.read(input.organizationId)).store.historicalCheckpointLifecycleLinks?.find(value=>value.linkId===input.linkId&&value.checkpointId===input.checkpointId&&value.checkpointRevision===input.checkpointRevision);if(!link)return null;try{assertHistoricalCheckpointLifecycleLinkIntegrityV1(link);const proofs=await this.proofs(input,{linkKind:link.linkKind,linkedRecordId:link.linkedRecordId,linkedRecordRevision:link.linkedRecordRevision,linkedSubrecordId:link.linkedSubrecordId},"historical-checkpoint-lifecycle-link:read",true,link.understanding);return proofs&&historicalCheckpointLifecycleDigestV1(proofs.checkpoint.understanding)===historicalCheckpointLifecycleDigestV1(link.understanding)?this.projection(link,proofs):null;}catch{return null;}}
}
