import type{ChiefCommunicationPlanItemV1,ChiefCommunicationPlanV1,ChiefCommunicationRoleV1}from"../workflow/leadershipConversation/chiefCommunicationPlan";
import{leadershipDigest,leadershipStableSerialize}from"../workflow/leadershipConversation/determinism";
export type ChiefCommunicationSentenceV1={text:string;itemId:string;semanticSourceId:string;lineage:string[]};export type ChiefCommunicationRenderedV1={contractVersion:"1";planDigest:string;firstSurface:Partial<Record<ChiefCommunicationRoleV1,ChiefCommunicationSentenceV1[]>>;progressiveDisclosure:Partial<Record<ChiefCommunicationRoleV1,ChiefCommunicationSentenceV1[]>>;metrics:{wordCount:number;estimatedReadingSeconds:number;sectionCount:number;omittedSectionCount:number;ontologyTermCount:number;repeatedItemCount:number}};
const first=new Set<ChiefCommunicationRoleV1>(["bottom-line","material-change","current-priority","hidden-tension","possible-surprise","suggested-question","uncertainty"]),sentence=(item:ChiefCommunicationPlanItemV1)=>({text:item.renderedContent,itemId:item.itemId,semanticSourceId:item.semanticSourceId,lineage:item.lineage});
export function renderChiefCommunicationPlanV1(plan:ChiefCommunicationPlanV1):ChiefCommunicationRenderedV1{const firstSurface:ChiefCommunicationRenderedV1["firstSurface"]={},progressiveDisclosure:ChiefCommunicationRenderedV1["progressiveDisclosure"]={};let words=0;for(const item of plan.items){const itemWords=item.renderedContent.trim().split(/\s+/).filter(Boolean).length,wantsFirst=first.has(item.role),fits=words+itemWords<=180,target=wantsFirst&&fits?firstSurface:progressiveDisclosure;if(target===firstSurface)words+=itemWords;(target[item.role]??=[]).push(sentence(item))}return{contractVersion:"1",planDigest:leadershipDigest(leadershipStableSerialize(plan)),firstSurface,progressiveDisclosure,metrics:{wordCount:words,estimatedReadingSeconds:Math.ceil(words/200*60),sectionCount:Object.keys(firstSurface).length,omittedSectionCount:plan.omitted.filter(item=>item.reason==="unsupported-empty").length,ontologyTermCount:plan.metrics.untranslatedOntologyTerms,repeatedItemCount:0}}}

import type{ChiefCommunicationPlanB11V1,ChiefCommunicationPlanItemB11V1,ChiefCommunicationSectionB11V1}from"../workflow/leadershipConversation/chiefCommunicationPlan";
export type ChiefCommunicationSentenceB11V1=ChiefCommunicationSentenceV1&{sourceRole:ChiefCommunicationRoleV1};
export type ChiefCommunicationSectionRenderedB11V1={sectionId:ChiefCommunicationSectionB11V1;label:string;items:ChiefCommunicationSentenceB11V1[]};
export type ChiefCommunicationRenderedB11V1={contractVersion:"1.1";planDigest:string;firstSurface:ChiefCommunicationSectionRenderedB11V1[];progressiveDisclosure:ChiefCommunicationSectionRenderedB11V1[];metrics:{wordCount:number;estimatedReadingSeconds:number;sectionCount:number;topSectionSentenceCount:number;topSectionWordCount:number;maximumSentenceWords:number;emptySectionCount:number;repeatedItemCount:number;progressiveDisclosureDuplicateCount:number;internalRoleLabelCount:number;genericAuditLabelCount:number;ontologyTermCount:number;ambiguousTranslationCount:number}};
const B11_LABELS:Record<ChiefCommunicationSectionB11V1,string>={"what-stands-out":"What stands out","what-changed":"What changed","the-tension":"The tension","what-could-surprise-you":"What could surprise you","what-to-do-next":"What to do next","what-would-help-most":"What would help most","question-worth-asking":"Question worth asking","what-i-do-not-know-yet":"What I do not know yet","why-this-is-my-view":"Why this is my view","another-explanation":"Another explanation","evidence-behind-this":"Evidence behind this"};
const B11_SECTION_ORDER:ChiefCommunicationSectionB11V1[]=["what-stands-out","what-changed","the-tension","what-could-surprise-you","what-to-do-next","what-would-help-most","question-worth-asking","what-i-do-not-know-yet","why-this-is-my-view","another-explanation","evidence-behind-this"];
const countWords=(value:string)=>value.trim().split(/\s+/u).filter(Boolean).length;
const sentenceCount=(value:string)=>value.split(/(?<=[.!?])\s+/u).filter(Boolean).length;
const maxSentenceWords=(value:string)=>Math.max(0,...value.split(/(?<=[.!?])\s+/u).map(countWords));
function appendB11(target:ChiefCommunicationSectionRenderedB11V1[],item:ChiefCommunicationPlanItemB11V1){let section=target.find(value=>value.sectionId===item.section);if(!section){section={sectionId:item.section,label:B11_LABELS[item.section],items:[]};target.push(section)}section.items.push({...sentence(item),sourceRole:item.role})}
export function renderChiefCommunicationPlanB11V1(plan:ChiefCommunicationPlanB11V1):ChiefCommunicationRenderedB11V1{
  const firstSurface:ChiefCommunicationSectionRenderedB11V1[]=[],progressiveDisclosure:ChiefCommunicationSectionRenderedB11V1[]=[];let words=0;
  for(const item of plan.items){const itemWords=countWords(item.renderedContent),existing=firstSurface.find(section=>section.sectionId===item.section),sectionDelta=existing?0:1,top=firstSurface.length===0||firstSurface[0]?.sectionId===item.section,topSentences=top?(firstSurface[0]?.items.reduce((sum,value)=>sum+sentenceCount(value.text),0)??0)+sentenceCount(item.renderedContent):0,topWords=top?(firstSurface[0]?.items.reduce((sum,value)=>sum+countWords(value.text),0)??0)+itemWords:0,wantsFirst=item.surface==="first",fits=wantsFirst&&words+itemWords<=120&&firstSurface.length+sectionDelta<=4&&(!top||topSentences<=2&&topWords<=50);if(fits){appendB11(firstSurface,item);words+=itemWords}else appendB11(progressiveDisclosure,item)}
  firstSurface.sort((a,b)=>B11_SECTION_ORDER.indexOf(a.sectionId)-B11_SECTION_ORDER.indexOf(b.sectionId));progressiveDisclosure.sort((a,b)=>B11_SECTION_ORDER.indexOf(a.sectionId)-B11_SECTION_ORDER.indexOf(b.sectionId));const firstNormalized=new Set(firstSurface.flatMap(section=>section.items.map(item=>item.text.trim().toLowerCase()))),deepNormalized=progressiveDisclosure.flatMap(section=>section.items.map(item=>item.text.trim().toLowerCase())),duplicates=deepNormalized.filter(value=>firstNormalized.has(value)).length,all=[...firstSurface,...progressiveDisclosure].flatMap(section=>section.items);
  return{contractVersion:"1.1",planDigest:leadershipDigest(leadershipStableSerialize(plan)),firstSurface,progressiveDisclosure,metrics:{wordCount:words,estimatedReadingSeconds:Math.ceil(words/200*60),sectionCount:firstSurface.length,topSectionSentenceCount:firstSurface[0]?.items.reduce((sum,value)=>sum+sentenceCount(value.text),0)??0,topSectionWordCount:firstSurface[0]?.items.reduce((sum,value)=>sum+countWords(value.text),0)??0,maximumSentenceWords:Math.max(0,...all.map(item=>maxSentenceWords(item.text))),emptySectionCount:0,repeatedItemCount:0,progressiveDisclosureDuplicateCount:duplicates,internalRoleLabelCount:0,genericAuditLabelCount:all.filter(item=>item.text.trim().toLowerCase()==="current authorized cognition projection").length,ontologyTermCount:plan.metrics.untranslatedOntologyTerms,ambiguousTranslationCount:plan.metrics.ambiguousTranslations}};
}
