import type { ProductArtifactBodyRepository } from "../persistence/productArtifactBodyRepository";
import { productArtifactBodyDigest, serializeProductArtifactBodyV1 } from "../persistence/productArtifactBodyContracts";
import { sourceScopedDigest, type SourceScopedCandidateV1 } from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import type { ProductWorkflowArtifactRepository } from "../workflow/leadershipConversation/productWorkflowArtifactRepository";
import { ProductWorkflowIncompatibleIdempotencyReplayError, ProductWorkflowRevisionConflictError } from "../workflow/leadershipConversation/productWorkflowArtifactRepository";
import { leadershipDigest, leadershipId, leadershipStableSerialize } from "../workflow/leadershipConversation/determinism";
import { projectSavedTalkingPointAdditions } from "./meetingExecutiveContentProjection";
import { verifyServerMintedSourceScopedAnalysisPublication, type ValidatedSourceScopedAnalysisPublicationV1 } from "./sourceScopedExecutiveAnalysis";
import type { ChiefMeetingPackBodyV1, ChiefMeetingPackPublicationV1, ChiefMeetingPackViewV1, MeetingPackPrivateNoteBodyV1, MeetingPackPrivateNoteIntentV1, MeetingPackPrivateNotePublicationV1 } from "../workflow/leadershipConversation/meetingPackContracts";

type Identity = { userId: string; organizationId: string; questionId: string; conversationId: string; seriesId: string };
type SourceScopedAnalysisBinding = NonNullable<ChiefMeetingPackPublicationV1["sourceScopedAnalysisBinding"]>;
const safe = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
export class ChiefMeetingPackRevisionConflictError extends Error { constructor(){super("Meeting Pack changed before this save.");this.name="ChiefMeetingPackRevisionConflictError";} }

export class ChiefMeetingPackOwner {
  constructor(private readonly d:{repository:ProductWorkflowArtifactRepository;bodyRepository:ProductArtifactBodyRepository;clock:{now():string};authorize(input:Identity):Promise<boolean>}){}
  private digest(value:unknown){return leadershipDigest(leadershipStableSerialize(value));}
  private citationSetDigest(candidate:SourceScopedCandidateV1){const tuples=Object.values(candidate.sections).flatMap(items=>items.flatMap(item=>item.citations)).map(value=>({sourceId:value.sourceId,sourceVersion:value.sourceVersion,bodyDigest:value.bodyDigest,sourcePacketDigest:value.sourcePacketDigest,startLine:value.startLine??null,endLine:value.endLine??null}));return this.digest([...new Map(tuples.map(value=>[leadershipStableSerialize(value),value])).values()].sort((a,b)=>leadershipStableSerialize(a).localeCompare(leadershipStableSerialize(b))));}
  /** A refresh identifies the meaningful proposed Pack, not the clock. */
  private candidateSemanticDigest(body:ChiefMeetingPackBodyV1){const{createdAt:_createdAt,...semantic}=body;return this.digest(semantic);}
  private userScope(userId:string){return this.digest({owner:"leadership-conversation-private-working",userId});}
  private async stageSourceScopedAnalysis(input:Identity,userScopeDigest:string,body:ChiefMeetingPackBodyV1,publication:ValidatedSourceScopedAnalysisPublicationV1|undefined){
    if(!publication)return undefined;
    const validated=verifyServerMintedSourceScopedAnalysisPublication(publication),candidate=validated.candidate,request=validated.request;
    if(candidate.organizationId!==input.organizationId||candidate.subjectId!==input.userId||candidate.questionId!==input.questionId||candidate.seriesId!==input.seriesId||candidate.occurrenceId!==input.conversationId||candidate.status!=="user-scoped-ai-generated-noncanonical-not-reviewed"||validated.preparedWorkPublicationDigest!==body.preparedWorkPublicationDigest||validated.materialLineageDigest!==body.sourceLineageDigest)throw new Error("Meeting Pack analysis is unavailable.");
    const {candidateDigest,...unsigned}=candidate;
    if(sourceScopedDigest(unsigned)!==candidateDigest)throw new Error("Meeting Pack analysis is unavailable.");
    const artifactId=leadershipId("source-scoped-analysis",input.organizationId,input.questionId,input.seriesId,input.conversationId,userScopeDigest),artifactRevision=leadershipId("source-scoped-analysis-revision",artifactId,candidate.candidateDigest);
    const binding:SourceScopedAnalysisBinding={contractVersion:"1",candidateDigest,questionDigest:sourceScopedDigest(request.question),requestDigest:request.requestDigest,sourcePacketDigest:request.packet.packetDigest,configurationDigest:request.configuration.configurationDigest,model:candidate.model,preparedWorkPublicationDigest:validated.preparedWorkPublicationDigest,sourceLineageDigest:validated.materialLineageDigest,sourceVersions:request.packet.sources.map(value=>({sourceId:value.sourceId,sourceVersion:value.sourceVersion,bodyDigest:value.bodyDigest})),citationSetDigest:this.citationSetDigest(candidate),usageDigest:this.digest(candidate.usage),lifecycleAttemptId:validated.lifecycleAttempt.attemptId,lifecycleReceiptDigest:validated.lifecycleAttempt.receiptDigest,resultDigest:validated.resultDigest},staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"source-scoped-analysis",artifactId,artifactRevision,schemaRef:"discovery:product:source-scoped-analysis-body:v1",bytes:serializeProductArtifactBodyV1(candidate)});return{...staged,binding};
  }
  private async access(input:Identity){if(!await this.d.authorize(input))throw new Error("Meeting Pack is unavailable.");return this.userScope(input.userId);}
  private noteHeaders(store:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>["store"],input:Identity,userScopeDigest:string){return (store.meetingPackPrivateNotePublications??[]).filter(value=>value.organizationId===input.organizationId&&value.questionId===input.questionId&&value.conversationId===input.conversationId&&value.seriesId===input.seriesId&&value.occurrenceId===input.conversationId&&value.userScopeDigest===userScopeDigest);}
  private packHeaders(store:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>["store"],input:Identity,userScopeDigest:string){return (store.meetingPackPublications??[]).filter(value=>value.organizationId===input.organizationId&&value.questionId===input.questionId&&value.conversationId===input.conversationId&&value.seriesId===input.seriesId&&value.occurrenceId===input.conversationId&&value.userScopeDigest===userScopeDigest).sort((a,b)=>a.revision-b.revision);}
  async hasPublishedPack(input:Identity):Promise<boolean>{
    const userScopeDigest=await this.access(input),snapshot=await this.d.repository.read(input.organizationId);
    return this.packHeaders(snapshot.store,input,userScopeDigest).length>0;
  }
  private async readNotesFrom(input:Identity,userScopeDigest:string,store:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>["store"]){const values=[];for(const header of this.noteHeaders(store,input,userScopeDigest)){const bytes=await this.d.bodyRepository.readStagedExact(header.protectedBody),body=JSON.parse(new TextDecoder().decode(bytes)) as MeetingPackPrivateNoteBodyV1;if(body.organizationId!==input.organizationId||body.questionId!==input.questionId||body.seriesId!==input.seriesId||body.occurrenceId!==input.conversationId||body.userScopeDigest!==userScopeDigest||body.noteId!==header.noteId||body.intent!==header.intent||this.digest(body.text)!==body.textDigest)throw new Error("Meeting Pack is unavailable.");values.push({noteId:body.noteId,noteRevisionId:header.noteRevisionId,intent:body.intent,text:body.text});}return values;}
  async addPrivateNote(input:Identity&{intent:MeetingPackPrivateNoteIntentV1;text:string;idempotencyKey:string}){const userScopeDigest=await this.access(input),text=input.text.trim();if(!text||text.length>1000||!["keep-private","talking-points","agenda"].includes(input.intent))throw new Error("Private context note is invalid.");const keyDigest=this.digest(input.idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:add-private-note",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,seriesId:input.seriesId,userScopeDigest,intent:input.intent,textDigest:this.digest(text)}),before=await this.d.repository.read(input.organizationId),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input);}
    const createdAt=this.d.clock.now(),textDigest=this.digest(text),noteId=leadershipId("meeting-pack-private-note",input.organizationId,input.questionId,input.seriesId,input.conversationId,userScopeDigest,input.intent,textDigest),noteRevisionId=leadershipId("meeting-pack-private-note-revision",noteId,"1"),body:MeetingPackPrivateNoteBodyV1={contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest,noteId,intent:input.intent,text,textDigest,createdAt},staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"meeting-pack-private-note",artifactId:noteId,artifactRevision:noteRevisionId,schemaRef:"discovery:product:meeting-pack-private-note-body:v1",bytes:serializeProductArtifactBodyV1(body)}),headerBase={contractVersion:"1" as const,organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest,noteId,noteRevisionId,intent:input.intent,protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,createdAt,idempotencyKeyDigest:keyDigest,requestFingerprint},publicationDigest=this.digest(headerBase),header:MeetingPackPrivateNotePublicationV1={...headerBase,publicationDigest},store=safe(before.store);store.meetingPackPrivateNotePublications??=[];if(!store.meetingPackPrivateNotePublications.some(value=>value.noteId===noteId))store.meetingPackPrivateNotePublications.push(header);store.idempotency.push({keyDigest,requestFingerprint,recordRef:noteRevisionId});try{await this.d.repository.replace(input.organizationId,store,before.revision);}catch(error){if(error instanceof ProductWorkflowRevisionConflictError){const raced=await this.d.repository.read(input.organizationId),match=raced.store.idempotency.find(value=>value.keyDigest===keyDigest);if(match?.requestFingerprint===requestFingerprint)return this.read(input);}throw error;}return this.read(input);
  }
  async publish(input:Identity&{body:ChiefMeetingPackBodyV1;idempotencyKey:string;validatedAnalysis?:ValidatedSourceScopedAnalysisPublicationV1;publicationLockHeld?:true}):Promise<ChiefMeetingPackViewV1|null>{const bodyStore=this.d.bodyRepository,lock=bodyStore.withPublicationLock;if(lock&&!input.publicationLockHeld){const bodyRepository={backend:bodyStore.backend,stage:bodyStore.stage.bind(bodyStore),readStagedExact:bodyStore.readStagedExact.bind(bodyStore),discardUnreferenced:bodyStore.discardUnreferenced?.bind(bodyStore)} satisfies ProductArtifactBodyRepository;return bodyStore.withPublicationLock!(input.organizationId,"leadership-conversation",()=>new ChiefMeetingPackOwner({...this.d,bodyRepository}).publish({...input,publicationLockHeld:true}));}const userScopeDigest=await this.access(input);if(input.body.organizationId!==input.organizationId||input.body.questionId!==input.questionId||input.body.seriesId!==input.seriesId||input.body.occurrenceId!==input.conversationId||input.body.userScopeDigest!==userScopeDigest)throw new Error("Meeting Pack is unavailable.");const before=await this.d.repository.read(input.organizationId),headers=this.packHeaders(before.store,input,userScopeDigest),priorHeader=headers.at(-1),current={preparedWorkPublicationDigest:input.body.preparedWorkPublicationDigest,priorCompletionDigest:input.body.priorCompletionDigest,inputSnapshotDigest:input.body.inputSnapshotDigest,sourceLineageDigest:input.body.sourceLineageDigest},validated=input.validatedAnalysis?verifyServerMintedSourceScopedAnalysisPublication(input.validatedAnalysis):undefined;if(priorHeader?.inputSnapshotDigest===input.body.inputSnapshotDigest&&priorHeader.sourceLineageDigest===input.body.sourceLineageDigest&&(!validated||priorHeader.sourceScopedAnalysisBinding?.candidateDigest===validated.candidate.candidateDigest))return this.read(input,current);const keyDigest=this.digest(input.idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:build",body:input.body,...(validated?{sourceScopedAnalysisDigest:validated.candidate.candidateDigest}:{})}),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input,{preparedWorkPublicationDigest:input.body.preparedWorkPublicationDigest,priorCompletionDigest:input.body.priorCompletionDigest});}
    const analysis=await this.stageSourceScopedAnalysis(input,userScopeDigest,input.body,input.validatedAnalysis);try{return await this.persistPack(input,input.body,before,(priorHeader?.revision??0)+1,priorHeader?.artifactRevision??null,keyDigest,requestFingerprint,undefined,analysis?.body,analysis?.binding);}catch(error){if(analysis)await this.discardIfUnpublished(input,analysis.body);throw error;}
  }
  async refresh(input:Identity&{body:ChiefMeetingPackBodyV1;validatedAnalysis?:ValidatedSourceScopedAnalysisPublicationV1;publicationLockHeld?:true}):Promise<ChiefMeetingPackViewV1|null>{
    const bodyStore=this.d.bodyRepository,lock=bodyStore.withPublicationLock;if(lock&&!input.publicationLockHeld){const bodyRepository={backend:bodyStore.backend,stage:bodyStore.stage.bind(bodyStore),readStagedExact:bodyStore.readStagedExact.bind(bodyStore),discardUnreferenced:bodyStore.discardUnreferenced?.bind(bodyStore)} satisfies ProductArtifactBodyRepository;return bodyStore.withPublicationLock!(input.organizationId,"leadership-conversation",()=>new ChiefMeetingPackOwner({...this.d,bodyRepository}).refresh({...input,publicationLockHeld:true}));}
    const userScopeDigest=await this.access(input);
    if(input.body.organizationId!==input.organizationId||input.body.questionId!==input.questionId||input.body.seriesId!==input.seriesId||input.body.occurrenceId!==input.conversationId||input.body.userScopeDigest!==userScopeDigest)throw new Error("Meeting Pack is unavailable.");
    const before=await this.d.repository.read(input.organizationId),headers=this.packHeaders(before.store,input,userScopeDigest),priorHeader=headers.at(-1),analysis=await this.stageSourceScopedAnalysis(input,userScopeDigest,input.body,input.validatedAnalysis),packSemanticDigest=this.candidateSemanticDigest(input.body),candidateSemanticDigest=analysis?this.digest({pack:packSemanticDigest,analysis:analysis.body.refDigest,binding:analysis.binding}):packSemanticDigest;
    if(priorHeader){
      await this.read(input);
      const currentBytes=await this.d.bodyRepository.readStagedExact(priorHeader.protectedBody),currentBody=JSON.parse(new TextDecoder().decode(currentBytes)) as ChiefMeetingPackBodyV1;
      if((priorHeader.candidateSemanticDigest??this.candidateSemanticDigest(currentBody))===candidateSemanticDigest)return this.read(input,{preparedWorkPublicationDigest:input.body.preparedWorkPublicationDigest,priorCompletionDigest:input.body.priorCompletionDigest,inputSnapshotDigest:input.body.inputSnapshotDigest,sourceLineageDigest:input.body.sourceLineageDigest});
    }
    const logicalPackId=leadershipId("chief-meeting-pack",input.organizationId,input.questionId,input.seriesId,input.conversationId,userScopeDigest),idempotencyKey=`meeting-pack-refresh:${this.digest({logicalPackId,predecessorArtifactRevision:priorHeader?.artifactRevision??null,candidateSemanticDigest})}`,keyDigest=this.digest(idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:refresh",logicalPackId,predecessorArtifactRevision:priorHeader?.artifactRevision??null,candidateSemanticDigest}),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);
    if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input,{preparedWorkPublicationDigest:input.body.preparedWorkPublicationDigest,priorCompletionDigest:input.body.priorCompletionDigest});}
    // This timestamp describes the enduring meeting context, not a refresh attempt.
    // Keeping it stable makes concurrent copies of one semantic candidate stage the
    // same protected bytes and preserves the existing no-orphan publication rule.
    const body={...input.body,createdAt:priorHeader?.createdAt??input.body.createdAt};
    try{return await this.persistPack(input,body,before,(priorHeader?.revision??0)+1,priorHeader?.artifactRevision??null,keyDigest,requestFingerprint,candidateSemanticDigest,analysis?.body,analysis?.binding);}catch(error){if(analysis)await this.discardIfUnpublished(input,analysis.body);throw error;}
  }
  async revise(input:Identity&{agendaText:string;talkingPointsText:string;expectedArtifactRevision:string;idempotencyKey:string}){
    const userScopeDigest=await this.access(input),agendaText=input.agendaText.trim(),talkingPointsText=input.talkingPointsText.trim();
    if(!agendaText||!talkingPointsText||agendaText.length>12000||talkingPointsText.length>12000)throw new Error("Meeting Pack edit is invalid.");
    const before=await this.d.repository.read(input.organizationId),keyDigest=this.digest(input.idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:revise",artifactRevision:input.expectedArtifactRevision,agendaText,talkingPointsText}),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);
    if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input);}
    const headers=this.packHeaders(before.store,input,userScopeDigest),current=headers.at(-1);
    if(!current||current.artifactRevision!==input.expectedArtifactRevision)throw new ChiefMeetingPackRevisionConflictError();
    const bytes=await this.d.bodyRepository.readStagedExact(current.protectedBody),priorBody=JSON.parse(new TextDecoder().decode(bytes)) as ChiefMeetingPackBodyV1,savedAdditions=projectSavedTalkingPointAdditions(priorBody.generatedTalkingPointsText,talkingPointsText),body={...priorBody,agendaText,talkingPointsText,revisionKind:"user-edit" as const,citationProjection:priorBody.citationProjection?{...priorBody.citationProjection,talkingPoints:[...priorBody.citationProjection.talkingPoints,...savedAdditions.filter(statement=>!priorBody.citationProjection!.talkingPoints.some(item=>item.statement===statement)).map((statement,index)=>({itemId:leadershipId("meeting-pack-talking-point",current.artifactRevision,"user-edit",index+1),statement,classification:"non-source-derived" as const,citations:[]}))]}:priorBody.citationProjection,createdAt:this.d.clock.now()};
    return this.persistPack(input,body,before,current.revision+1,current.artifactRevision,keyDigest,requestFingerprint,current.candidateSemanticDigest,current.sourceScopedAnalysisBodyReference,current.sourceScopedAnalysisBinding);
  }
  private async discardIfUnpublished(input:Identity,body:import("../persistence/productArtifactBodyContracts").ProductArtifactBodyRefV1){const snapshot=await this.d.repository.read(input.organizationId);if((snapshot.store.meetingPackPublications??[]).some(header=>header.protectedBody.refDigest===body.refDigest||header.sourceScopedAnalysisBodyReference?.refDigest===body.refDigest))return;const discard=this.d.bodyRepository.discardUnreferenced;if(!discard)throw new Error("Meeting Pack cleanup is unavailable.");await discard.call(this.d.bodyRepository,body);}
  private async persistPack(input:Identity,body:ChiefMeetingPackBodyV1,before:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>,revision:number,predecessorArtifactRevision:string|null,keyDigest:string,requestFingerprint:string,candidateSemanticDigest?:string,sourceScopedAnalysisBodyReference?:import("../persistence/productArtifactBodyContracts").ProductArtifactBodyRefV1,sourceScopedAnalysisBinding?:SourceScopedAnalysisBinding){const artifactId=leadershipId("chief-meeting-pack",input.organizationId,input.questionId,input.seriesId,input.conversationId,body.userScopeDigest),bodyBytes=serializeProductArtifactBodyV1(body),artifactRevision=leadershipId("chief-meeting-pack-revision",artifactId,revision,productArtifactBodyDigest(bodyBytes)),staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"meeting-pack-draft",artifactId,artifactRevision,schemaRef:"discovery:product:chief-meeting-pack-body:v1",bytes:bodyBytes}),headerBase={contractVersion:"1" as const,organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest:body.userScopeDigest,artifactId,artifactRevision,revision,predecessorArtifactRevision,generatedAgendaId:body.generatedAgendaId,generatedTalkingPointsId:body.generatedTalkingPointsId,inputSnapshotDigest:body.inputSnapshotDigest,...(candidateSemanticDigest?{candidateSemanticDigest}:{}),...(sourceScopedAnalysisBodyReference?{sourceScopedAnalysisBodyReference}:{}),...(sourceScopedAnalysisBinding?{sourceScopedAnalysisBinding}:{}),sourceLineageDigest:body.sourceLineageDigest,protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,createdAt:body.createdAt,idempotencyKeyDigest:keyDigest,requestFingerprint},publicationDigest=this.digest(headerBase),header:ChiefMeetingPackPublicationV1={...headerBase,publicationDigest},store=safe(before.store);store.meetingPackPublications??=[];store.meetingPackPublications.push(header);store.idempotency.push({keyDigest,requestFingerprint,recordRef:artifactRevision});try{await this.d.repository.replace(input.organizationId,store,before.revision);}catch(error){if(error instanceof ProductWorkflowRevisionConflictError){const raced=await this.d.repository.read(input.organizationId),match=raced.store.idempotency.find(value=>value.keyDigest===keyDigest);if(match?.requestFingerprint===requestFingerprint)return this.read(input,{preparedWorkPublicationDigest:body.preparedWorkPublicationDigest,priorCompletionDigest:body.priorCompletionDigest});}await this.discardIfUnpublished(input,staged.body);throw Object.assign(error instanceof Error?error:new Error("Meeting Pack save failed."),{stagedBodyRefDigest:staged.body.refDigest});}return this.read(input,{preparedWorkPublicationDigest:body.preparedWorkPublicationDigest,priorCompletionDigest:body.priorCompletionDigest});}
  async read(input:Identity,current?:{preparedWorkPublicationDigest:string;priorCompletionDigest:string|null;inputSnapshotDigest?:string;sourceLineageDigest?:string}):Promise<ChiefMeetingPackViewV1|null>{const userScopeDigest=await this.access(input),snapshot=await this.d.repository.read(input.organizationId),headers=this.packHeaders(snapshot.store,input,userScopeDigest),header=headers.at(-1);if(!header)return null;const bytes=await this.d.bodyRepository.readStagedExact(header.protectedBody),body=JSON.parse(new TextDecoder().decode(bytes)) as ChiefMeetingPackBodyV1;if(body.organizationId!==input.organizationId||body.questionId!==input.questionId||body.seriesId!==input.seriesId||body.occurrenceId!==input.conversationId||body.userScopeDigest!==userScopeDigest||body.inputSnapshotDigest!==header.inputSnapshotDigest)throw new Error("Meeting Pack is unavailable.");const notes=await this.readNotesFrom(input,userScopeDigest,snapshot.store),stale=notes.length!==body.inputBasis.privateNotes||Boolean(current&&(current.preparedWorkPublicationDigest!==body.preparedWorkPublicationDigest||current.priorCompletionDigest!==body.priorCompletionDigest||current.inputSnapshotDigest!==undefined&&current.inputSnapshotDigest!==body.inputSnapshotDigest||current.sourceLineageDigest!==undefined&&current.sourceLineageDigest!==header.sourceLineageDigest)),{organizationId:_o,questionId:_q,seriesId:_s,occurrenceId:_x,userScopeDigest:_u,personaTrace:_p,sourceLineageDigest:_l,...safeBody}=body;return{...safeBody,artifactRevision:header.artifactRevision,revision:header.revision,potentiallyOutOfDate:stale,privateNotes:notes.map(({noteRevisionId:_r,...note})=>note)};}
  async noteIdentity(input:Identity){const userScopeDigest=await this.access(input),snapshot=await this.d.repository.read(input.organizationId),notes=await this.readNotesFrom(input,userScopeDigest,snapshot.store);return{userScopeDigest,notes};}
  /** Server-only reconstruction for a future authorized admission boundary. */
  async readSourceScopedAnalysis(input:Identity):Promise<SourceScopedCandidateV1|null>{const userScopeDigest=await this.access(input),snapshot=await this.d.repository.read(input.organizationId),header=this.packHeaders(snapshot.store,input,userScopeDigest).at(-1),reference=header?.sourceScopedAnalysisBodyReference,binding=header?.sourceScopedAnalysisBinding;if(!reference&&!binding)return null;if(!reference||!binding)return null;const artifactId=leadershipId("source-scoped-analysis",input.organizationId,input.questionId,input.seriesId,input.conversationId,userScopeDigest);if(reference.organizationId!==input.organizationId||reference.semanticOwner!=="leadership-conversation"||reference.artifactType!=="source-scoped-analysis"||reference.artifactId!==artifactId)return null;const candidate=JSON.parse(new TextDecoder().decode(await this.d.bodyRepository.readStagedExact(reference))) as SourceScopedCandidateV1,pack=JSON.parse(new TextDecoder().decode(await this.d.bodyRepository.readStagedExact(header!.protectedBody))) as ChiefMeetingPackBodyV1,{candidateDigest,...unsigned}=candidate,allowed=new Set(binding.sourceVersions.map(value=>leadershipStableSerialize(value))),citations=Object.values(candidate.sections).flatMap(items=>items.flatMap(item=>item.citations));if(candidate.organizationId!==input.organizationId||candidate.subjectId!==input.userId||candidate.questionId!==input.questionId||candidate.seriesId!==input.seriesId||candidate.occurrenceId!==input.conversationId||candidate.status!=="user-scoped-ai-generated-noncanonical-not-reviewed"||sourceScopedDigest(unsigned)!==candidateDigest||binding.candidateDigest!==candidateDigest||binding.requestDigest!==candidate.requestDigest||binding.sourcePacketDigest!==candidate.sourcePacketDigest||binding.configurationDigest!==candidate.configurationDigest||binding.model!==candidate.model||binding.usageDigest!==this.digest(candidate.usage)||binding.citationSetDigest!==this.citationSetDigest(candidate)||binding.preparedWorkPublicationDigest!==pack.preparedWorkPublicationDigest||binding.sourceLineageDigest!==pack.sourceLineageDigest||citations.some(value=>value.sourcePacketDigest!==binding.sourcePacketDigest||!allowed.has(leadershipStableSerialize({sourceId:value.sourceId,sourceVersion:value.sourceVersion,bodyDigest:value.bodyDigest}))))return null;return safe(candidate);}
}
