import type { ProductArtifactBodyRepository } from "../persistence/productArtifactBodyRepository";
import { productArtifactBodyDigest, serializeProductArtifactBodyV1 } from "../persistence/productArtifactBodyContracts";
import type { ProductWorkflowArtifactRepository } from "../workflow/leadershipConversation/productWorkflowArtifactRepository";
import { ProductWorkflowIncompatibleIdempotencyReplayError, ProductWorkflowRevisionConflictError } from "../workflow/leadershipConversation/productWorkflowArtifactRepository";
import { leadershipDigest, leadershipId, leadershipStableSerialize } from "../workflow/leadershipConversation/determinism";
import type { ChiefMeetingPackBodyV1, ChiefMeetingPackPublicationV1, ChiefMeetingPackViewV1, MeetingPackPrivateNoteBodyV1, MeetingPackPrivateNoteIntentV1, MeetingPackPrivateNotePublicationV1 } from "../workflow/leadershipConversation/meetingPackContracts";

type Identity = { userId: string; organizationId: string; questionId: string; conversationId: string; seriesId: string };
const safe = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
export class ChiefMeetingPackRevisionConflictError extends Error { constructor(){super("Meeting Pack changed before this save.");this.name="ChiefMeetingPackRevisionConflictError";} }

export class ChiefMeetingPackOwner {
  constructor(private readonly d:{repository:ProductWorkflowArtifactRepository;bodyRepository:ProductArtifactBodyRepository;clock:{now():string};authorize(input:Identity):Promise<boolean>}){}
  private digest(value:unknown){return leadershipDigest(leadershipStableSerialize(value));}
  private userScope(userId:string){return this.digest({owner:"leadership-conversation-private-working",userId});}
  private async access(input:Identity){if(!await this.d.authorize(input))throw new Error("Meeting Pack is unavailable.");return this.userScope(input.userId);}
  private noteHeaders(store:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>["store"],input:Identity,userScopeDigest:string){return (store.meetingPackPrivateNotePublications??[]).filter(value=>value.organizationId===input.organizationId&&value.questionId===input.questionId&&value.conversationId===input.conversationId&&value.seriesId===input.seriesId&&value.occurrenceId===input.conversationId&&value.userScopeDigest===userScopeDigest);}
  private packHeaders(store:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>["store"],input:Identity,userScopeDigest:string){return (store.meetingPackPublications??[]).filter(value=>value.organizationId===input.organizationId&&value.questionId===input.questionId&&value.conversationId===input.conversationId&&value.seriesId===input.seriesId&&value.occurrenceId===input.conversationId&&value.userScopeDigest===userScopeDigest).sort((a,b)=>a.revision-b.revision);}
  private async readNotesFrom(input:Identity,userScopeDigest:string,store:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>["store"]){const values=[];for(const header of this.noteHeaders(store,input,userScopeDigest)){const bytes=await this.d.bodyRepository.readStagedExact(header.protectedBody),body=JSON.parse(new TextDecoder().decode(bytes)) as MeetingPackPrivateNoteBodyV1;if(body.organizationId!==input.organizationId||body.questionId!==input.questionId||body.seriesId!==input.seriesId||body.occurrenceId!==input.conversationId||body.userScopeDigest!==userScopeDigest||body.noteId!==header.noteId||body.intent!==header.intent||this.digest(body.text)!==body.textDigest)throw new Error("Meeting Pack is unavailable.");values.push({noteId:body.noteId,noteRevisionId:header.noteRevisionId,intent:body.intent,text:body.text});}return values;}
  async addPrivateNote(input:Identity&{intent:MeetingPackPrivateNoteIntentV1;text:string;idempotencyKey:string}){const userScopeDigest=await this.access(input),text=input.text.trim();if(!text||text.length>1000||!["keep-private","talking-points","agenda"].includes(input.intent))throw new Error("Private context note is invalid.");const keyDigest=this.digest(input.idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:add-private-note",organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,seriesId:input.seriesId,userScopeDigest,intent:input.intent,textDigest:this.digest(text)}),before=await this.d.repository.read(input.organizationId),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input);}
    const createdAt=this.d.clock.now(),textDigest=this.digest(text),noteId=leadershipId("meeting-pack-private-note",input.organizationId,input.questionId,input.seriesId,input.conversationId,userScopeDigest,input.intent,textDigest),noteRevisionId=leadershipId("meeting-pack-private-note-revision",noteId,"1"),body:MeetingPackPrivateNoteBodyV1={contractVersion:"1",organizationId:input.organizationId,questionId:input.questionId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest,noteId,intent:input.intent,text,textDigest,createdAt},staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"meeting-pack-private-note",artifactId:noteId,artifactRevision:noteRevisionId,schemaRef:"discovery:product:meeting-pack-private-note-body:v1",bytes:serializeProductArtifactBodyV1(body)}),headerBase={contractVersion:"1" as const,organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest,noteId,noteRevisionId,intent:input.intent,protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,createdAt,idempotencyKeyDigest:keyDigest,requestFingerprint},publicationDigest=this.digest(headerBase),header:MeetingPackPrivateNotePublicationV1={...headerBase,publicationDigest},store=safe(before.store);store.meetingPackPrivateNotePublications??=[];if(!store.meetingPackPrivateNotePublications.some(value=>value.noteId===noteId))store.meetingPackPrivateNotePublications.push(header);store.idempotency.push({keyDigest,requestFingerprint,recordRef:noteRevisionId});try{await this.d.repository.replace(input.organizationId,store,before.revision);}catch(error){if(error instanceof ProductWorkflowRevisionConflictError){const raced=await this.d.repository.read(input.organizationId),match=raced.store.idempotency.find(value=>value.keyDigest===keyDigest);if(match?.requestFingerprint===requestFingerprint)return this.read(input);}throw error;}return this.read(input);
  }
  async publish(input:Identity&{body:ChiefMeetingPackBodyV1;idempotencyKey:string}){const userScopeDigest=await this.access(input);if(input.body.organizationId!==input.organizationId||input.body.questionId!==input.questionId||input.body.seriesId!==input.seriesId||input.body.occurrenceId!==input.conversationId||input.body.userScopeDigest!==userScopeDigest)throw new Error("Meeting Pack is unavailable.");const before=await this.d.repository.read(input.organizationId),headers=this.packHeaders(before.store,input,userScopeDigest),priorHeader=headers.at(-1),current={preparedWorkPublicationDigest:input.body.preparedWorkPublicationDigest,priorCompletionDigest:input.body.priorCompletionDigest,inputSnapshotDigest:input.body.inputSnapshotDigest,sourceLineageDigest:input.body.sourceLineageDigest};if(priorHeader?.inputSnapshotDigest===input.body.inputSnapshotDigest&&priorHeader.sourceLineageDigest===input.body.sourceLineageDigest)return this.read(input,current);const keyDigest=this.digest(input.idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:build",body:input.body}),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input,{preparedWorkPublicationDigest:input.body.preparedWorkPublicationDigest,priorCompletionDigest:input.body.priorCompletionDigest});}
    return this.persistPack(input,input.body,before,(priorHeader?.revision??0)+1,priorHeader?.artifactRevision??null,keyDigest,requestFingerprint);
  }
  async revise(input:Identity&{agendaText:string;talkingPointsText:string;expectedArtifactRevision:string;idempotencyKey:string}){
    const userScopeDigest=await this.access(input),agendaText=input.agendaText.trim(),talkingPointsText=input.talkingPointsText.trim();
    if(!agendaText||!talkingPointsText||agendaText.length>12000||talkingPointsText.length>12000)throw new Error("Meeting Pack edit is invalid.");
    const before=await this.d.repository.read(input.organizationId),keyDigest=this.digest(input.idempotencyKey),requestFingerprint=this.digest({operation:"meeting-pack:revise",artifactRevision:input.expectedArtifactRevision,agendaText,talkingPointsText}),prior=before.store.idempotency.find(value=>value.keyDigest===keyDigest);
    if(prior){if(prior.requestFingerprint!==requestFingerprint)throw new ProductWorkflowIncompatibleIdempotencyReplayError();return this.read(input);}
    const headers=this.packHeaders(before.store,input,userScopeDigest),current=headers.at(-1);
    if(!current||current.artifactRevision!==input.expectedArtifactRevision)throw new ChiefMeetingPackRevisionConflictError();
    const bytes=await this.d.bodyRepository.readStagedExact(current.protectedBody),priorBody=JSON.parse(new TextDecoder().decode(bytes)) as ChiefMeetingPackBodyV1,body={...priorBody,agendaText,talkingPointsText,revisionKind:"user-edit" as const,createdAt:this.d.clock.now()};
    return this.persistPack(input,body,before,current.revision+1,current.artifactRevision,keyDigest,requestFingerprint);
  }
  private async persistPack(input:Identity,body:ChiefMeetingPackBodyV1,before:Awaited<ReturnType<ProductWorkflowArtifactRepository["read"]>>,revision:number,predecessorArtifactRevision:string|null,keyDigest:string,requestFingerprint:string){const artifactId=leadershipId("chief-meeting-pack",input.organizationId,input.questionId,input.seriesId,input.conversationId,body.userScopeDigest),bodyBytes=serializeProductArtifactBodyV1(body),artifactRevision=leadershipId("chief-meeting-pack-revision",artifactId,revision,productArtifactBodyDigest(bodyBytes)),staged=await this.d.bodyRepository.stage({contractVersion:"1",organizationId:input.organizationId,semanticOwner:"leadership-conversation",artifactType:"meeting-pack-draft",artifactId,artifactRevision,schemaRef:"discovery:product:chief-meeting-pack-body:v1",bytes:bodyBytes}),headerBase={contractVersion:"1" as const,organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,seriesId:input.seriesId,occurrenceId:input.conversationId,userScopeDigest:body.userScopeDigest,artifactId,artifactRevision,revision,predecessorArtifactRevision,generatedAgendaId:body.generatedAgendaId,generatedTalkingPointsId:body.generatedTalkingPointsId,inputSnapshotDigest:body.inputSnapshotDigest,sourceLineageDigest:body.sourceLineageDigest,protectedBody:staged.body,ownerStageReceiptDigest:staged.receiptDigest,createdAt:body.createdAt,idempotencyKeyDigest:keyDigest,requestFingerprint},publicationDigest=this.digest(headerBase),header:ChiefMeetingPackPublicationV1={...headerBase,publicationDigest},store=safe(before.store);store.meetingPackPublications??=[];store.meetingPackPublications.push(header);store.idempotency.push({keyDigest,requestFingerprint,recordRef:artifactRevision});try{await this.d.repository.replace(input.organizationId,store,before.revision);}catch(error){if(error instanceof ProductWorkflowRevisionConflictError){const raced=await this.d.repository.read(input.organizationId),match=raced.store.idempotency.find(value=>value.keyDigest===keyDigest);if(match?.requestFingerprint===requestFingerprint)return this.read(input,{preparedWorkPublicationDigest:body.preparedWorkPublicationDigest,priorCompletionDigest:body.priorCompletionDigest});}throw Object.assign(error instanceof Error?error:new Error("Meeting Pack save failed."),{stagedBodyRefDigest:staged.body.refDigest});}return this.read(input,{preparedWorkPublicationDigest:body.preparedWorkPublicationDigest,priorCompletionDigest:body.priorCompletionDigest});}
  async read(input:Identity,current?:{preparedWorkPublicationDigest:string;priorCompletionDigest:string|null;inputSnapshotDigest?:string;sourceLineageDigest?:string}):Promise<ChiefMeetingPackViewV1|null>{const userScopeDigest=await this.access(input),snapshot=await this.d.repository.read(input.organizationId),headers=this.packHeaders(snapshot.store,input,userScopeDigest),header=headers.at(-1);if(!header)return null;const bytes=await this.d.bodyRepository.readStagedExact(header.protectedBody),body=JSON.parse(new TextDecoder().decode(bytes)) as ChiefMeetingPackBodyV1;if(body.organizationId!==input.organizationId||body.questionId!==input.questionId||body.seriesId!==input.seriesId||body.occurrenceId!==input.conversationId||body.userScopeDigest!==userScopeDigest||body.inputSnapshotDigest!==header.inputSnapshotDigest)throw new Error("Meeting Pack is unavailable.");const notes=await this.readNotesFrom(input,userScopeDigest,snapshot.store),stale=notes.length!==body.inputBasis.privateNotes||Boolean(current&&(current.preparedWorkPublicationDigest!==body.preparedWorkPublicationDigest||current.priorCompletionDigest!==body.priorCompletionDigest||current.inputSnapshotDigest!==undefined&&current.inputSnapshotDigest!==body.inputSnapshotDigest||current.sourceLineageDigest!==undefined&&current.sourceLineageDigest!==header.sourceLineageDigest)),{organizationId:_o,questionId:_q,seriesId:_s,occurrenceId:_x,userScopeDigest:_u,personaTrace:_p,sourceLineageDigest:_l,...safeBody}=body;return{...safeBody,artifactRevision:header.artifactRevision,revision:header.revision,potentiallyOutOfDate:stale,privateNotes:notes.map(({noteRevisionId:_r,...note})=>note)};}
  async noteIdentity(input:Identity){const userScopeDigest=await this.access(input),snapshot=await this.d.repository.read(input.organizationId),notes=await this.readNotesFrom(input,userScopeDigest,snapshot.store);return{userScopeDigest,notes};}
}
