import type {ChiefFirstPrepareViewV1}from"../workflow/leadershipConversation";
import type{ChiefEvidenceSupportResolutionResultV1}from"./chiefLeadershipEvidenceSupportResolver";
import{applyChiefPreparationSemanticGates}from"./chiefLeadershipPreparationSemanticGates";
import{composeChiefAnalysisToActionV1,type ChiefAnalysisToActionInputV1}from"../workflow/leadershipConversation/chiefAnalysisToAction";
import{composeCandidateB11ChiefCommunication}from"./chiefLeadershipPreparationCommunicationComposer";
import type{ChiefPreparationSemanticGateReceiptV1}from"./chiefLeadershipPreparationSemanticGates";
import type{ChiefPreparationClaimSupportReceiptV1}from"./chiefLeadershipPreparationClaimSupport";
export function composeChiefLeadershipAnalysisToActionFromGrounded(input:{view:ChiefFirstPrepareViewV1;semantic:ChiefPreparationSemanticGateReceiptV1;claimSupport:ChiefPreparationClaimSupportReceiptV1;supportProjectionDigest:string;permissionScope:"organization"|"team";replayKey:string;context?:Partial<Pick<ChiefAnalysisToActionInputV1,"exactOwnerRef"|"exactDecisionRef"|"exactEvidenceAcquisitionRef"|"reviewCondition"|"explicitDeferral">>}){
 const analysis=composeChiefAnalysisToActionV1({organizationId:input.view.organizationId,questionId:input.view.questionId,conversationId:input.view.conversationId,meetingPurpose:input.view.meeting.purpose,intendedMeetingOutcome:null,view:input.view,semantic:input.semantic,claimSupport:input.claimSupport,supportProjectionDigest:input.supportProjectionDigest,permissionScope:input.permissionScope,idempotencyKey:`${input.replayKey}:analysis`,...input.context}),enriched=structuredClone(input.view);if(analysis.whyItMatters)enriched.reasoning=[analysis.whyItMatters,...enriched.reasoning];if(analysis.userFacingNextMove&&!enriched.questions.includes(analysis.userFacingNextMove))analysis.nextMoveDisposition==="ask"||analysis.nextMoveDisposition==="learn"?enriched.questions=[analysis.userFacingNextMove,...enriched.questions].slice(0,2):enriched.whatMattersNow=[...enriched.whatMattersNow.slice(0,1),analysis.userFacingNextMove];if(analysis.whatWouldChangeTheView)enriched.uncertainty=[analysis.whatWouldChangeTheView,...enriched.uncertainty];return{analysis,communication:composeCandidateB11ChiefCommunication(enriched),view:enriched};
}
export function composeChiefLeadershipAnalysisToAction(input:{view:ChiefFirstPrepareViewV1;productQuestion:string;meetingPurpose:string;support:ChiefEvidenceSupportResolutionResultV1;permissionScope:"organization"|"team";replayKey:string;context?:Partial<Pick<ChiefAnalysisToActionInputV1,"exactOwnerRef"|"exactDecisionRef"|"exactEvidenceAcquisitionRef"|"reviewCondition"|"explicitDeferral">>}){
 const evidence=input.support.serverOnly.items.map(item=>({sourceRef:item.sourceBindingId,observedAt:input.view.meeting.timeframe,summary:item.normalizedText})),trace={organizationId:input.view.organizationId,authorizedScope:input.permissionScope,authorization:"eligible" as const,evidence:input.support.serverOnly.items.map(item=>({evidenceId:item.evidenceId,sourceRef:item.sourceBindingId,text:item.normalizedText})),explanations:[]};
 const semantic=applyChiefPreparationSemanticGates({view:input.view,productQuestion:input.productQuestion,meetingPurpose:input.meetingPurpose,evidence,claimSupport:{organizationId:input.view.organizationId,authorizedScope:input.permissionScope,replayKey:`${input.replayKey}:support`,trace}});if(!semantic.claimSupport)throw new Error("Grounded claim support is unavailable.");
 return{semantic,...composeChiefLeadershipAnalysisToActionFromGrounded({view:semantic.view,semantic:semantic.receipt,claimSupport:semantic.claimSupport,supportProjectionDigest:input.support.projection.projectionDigest,permissionScope:input.permissionScope,replayKey:input.replayKey,context:input.context})};
}
