import type{SourceScopedCandidateV1,SourceScopedItemV1,SourceScopedSectionsV1}from"../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import type{ChiefMeetingPackViewV1}from"../workflow/leadershipConversation/meetingPackContracts";
export type MeetingAskStatusV1="Supported"|"Inferred"|"Disputed"|"Unknown";
export type MeetingAskAnswerV1={scope:string;answer:string;status:MeetingAskStatusV1;citations:Array<{sourceId:string;sourceVersion:string}>;uncertainty:string|null;usesPrivateContext:boolean};
export type AuthorizedAskReferentV1={referentId:string;kind:keyof SourceScopedSectionsV1;canonicalLabel:string;aliases:readonly string[];evidenceStatus:MeetingAskStatusV1;citationRefs:readonly string[];sourceRefs:readonly string[];item:SourceScopedItemV1};
const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9\s-]/g," ").replace(/-/g," ").replace(/\s+/g," ").trim();
const grammar=new Set("what why how which who when where changed change since last time agenda remains unresolved not decided unknown evidence supports support grounded would view assessment should ask questions question this that the a an is are was were does do did for from about current meeting claim discovery know we our now matter matters on of to in and or its it yet please tell me".split(" "));
const words=(value:string)=>normalize(value).split(" ").filter(Boolean),subjectWords=(question:string)=>words(question).filter(value=>value.length>1&&!grammar.has(value));
const statusFor=(kind:keyof SourceScopedSectionsV1,item:SourceScopedItemV1):MeetingAskStatusV1=>kind==="contradictions"||kind==="organizationalDisagreement"?"Disputed":item.factCheck==="HUMAN REVIEW REQUIRED"?"Inferred":"Supported";
export function projectAuthorizedAskReferents(candidate:SourceScopedCandidateV1):AuthorizedAskReferentV1[]{const grouped=new Map<string,AuthorizedAskReferentV1>();for(const[kind,items]of Object.entries(candidate.sections)as Array<[keyof SourceScopedSectionsV1,SourceScopedItemV1[]]>){items.forEach((item,index)=>{const citationRefs=item.citations.map(value=>`${value.sourceId}:${value.sourceVersion}`),key=JSON.stringify([normalize(item.statement),citationRefs]);if(grouped.has(key))return;grouped.set(key,{referentId:`${candidate.candidateDigest}:${kind}:${index}`,kind,canonicalLabel:item.statement,aliases:[],evidenceStatus:statusFor(kind,item),citationRefs,sourceRefs:[...new Set(item.citations.map(value=>value.sourceId))],item});});}return[...grouped.values()];}
function orderedCoverage(subject:string[],candidate:string[]){let index=0;for(const token of subject){index=candidate.indexOf(token,index);if(index<0)return false;index+=1;}return true;}
export function resolveAuthorizedAskReferent(question:string,catalog:readonly AuthorizedAskReferentV1[]):AuthorizedAskReferentV1|null|undefined{const subject=subjectWords(question);if(!subject.length)return undefined;const matches=catalog.filter(referent=>[referent.canonicalLabel,...referent.aliases].some(label=>orderedCoverage(subject,words(label))));return matches.length===1?matches[0]!:null;}
function meetingWideSection(question:string,candidate:SourceScopedCandidateV1):SourceScopedItemV1[]{const value=normalize(question);if(/changed|since last/.test(value))return candidate.sections.whatChanged;if(/why.+agenda|on the agenda|matter now/.test(value))return candidate.sections.decisions.length?candidate.sections.decisions:candidate.sections.attention;if(/unresolved|not decided|unknown/.test(value))return[...candidate.sections.openQuestions,...candidate.sections.notDecided];if(/what evidence|supports|grounded/.test(value))return candidate.sections.whatMattersNow;if(/change.+view|change.+assessment/.test(value))return candidate.sections.whatWouldChangeAssessment;if(/what should i ask|questions? should/.test(value))return candidate.sections.openQuestions;return[];}
const unknown=(scope:string):MeetingAskAnswerV1=>({scope,answer:"Discovery does not have enough authorized context to support that subject in this meeting.",status:"Unknown",citations:[],uncertainty:"The answer is not supported within this meeting’s current authorized context.",usesPrivateContext:false});
export function projectMeetingAskAnswer(input:{scope:string;question:string;candidate:SourceScopedCandidateV1|null;pack:ChiefMeetingPackViewV1|null}):MeetingAskAnswerV1{if(!input.candidate)return unknown(input.scope);const referent=resolveAuthorizedAskReferent(input.question,projectAuthorizedAskReferents(input.candidate));if(referent===null)return unknown(input.scope);const selected=referent?.item??meetingWideSection(input.question,input.candidate)[0];if(!selected)return unknown(input.scope);const status=referent?.evidenceStatus??(selected.factCheck==="HUMAN REVIEW REQUIRED"?"Inferred":"Supported"),citations=[...new Map(selected.citations.map(value=>[`${value.sourceId}:${value.sourceVersion}`,{sourceId:value.sourceId,sourceVersion:value.sourceVersion}])).values()],questionTerms=new Set(subjectWords(input.question)),privateNote=input.pack?.privateNotes.find(note=>note.intent==="keep-private"&&words(note.text).some(word=>questionTerms.has(word))),uncertainty=input.candidate.sections.evidenceUncertainty[0]?.statement??input.candidate.sections.modelUncertainty[0]?.statement??null;return{scope:input.scope,answer:privateNote?`${selected.statement} Your private context may also be relevant, but remains user-authored and unverified.`:selected.statement,status,citations,uncertainty,usesPrivateContext:Boolean(privateNote)};}
