import "server-only";
import { productArtifactBodyDigest } from "../persistence";
import { validateProductArtifactInspectionMetadataV1 } from "../workflow/productArtifactInspectionMetadataContracts";
import type { ProductArtifactCurrentAccessRequestV1,ProductArtifactCurrentAccessResultV1,ProductArtifactCurrentOwnerStateV1 } from "../workflow/productArtifactCurrentAccessContracts";
const requestBound=(r:ProductArtifactCurrentAccessRequestV1)=>r.governance.disposition==="authorized"&&r.governance.organizationId===r.organizationId&&r.governance.subjectId===r.subjectId&&r.governance.operation===r.operation&&r.governance.purpose===r.purpose&&r.governance.sensitivity===r.sensitivity&&r.governance.evaluatedAt===r.evaluatedAt;
export function resolveProductArtifactCurrentAccessV1(request:ProductArtifactCurrentAccessRequestV1,current:ProductArtifactCurrentOwnerStateV1):ProductArtifactCurrentAccessResultV1{
 validateProductArtifactInspectionMetadataV1(request.metadata);const metadataBound=request.metadata.organizationId===request.organizationId&&request.metadata.productQuestionId===current.productQuestionId&&Boolean(request.metadata.materialLineage);
 const complete=current.contractVersion==="1"&&current.organizationId===request.organizationId&&Boolean(current.sourceGovernanceDigest&&current.eligibilityDigest&&current.projectionRevision&&current.projectionDigest&&current.canonicalUnderstandingRevision&&current.canonicalChangeResultDigest&&current.lineagePolicyVersion);
 const disposition:ProductArtifactCurrentAccessResultV1["disposition"]=!requestBound(request)||current.eligibilityDisposition==="withheld"?"withheld":!metadataBound||!complete||current.eligibilityDisposition!=="eligible"?"unavailable":"eligible";
 const g=request.governance;const unsigned={contractVersion:"1" as const,organizationId:request.organizationId,subjectId:request.subjectId,artifactType:request.metadata.artifactType,artifactId:request.metadata.artifactId,artifactRevision:request.metadata.artifactRevision,operation:request.operation,purpose:request.purpose,scopeDigest:request.scopeDigest,sensitivity:request.sensitivity,evaluatedAt:request.evaluatedAt,disposition,metadataHeaderDigest:request.metadata.headerDigest,bodyRefDigest:request.metadata.protectedBody.refDigest,authorityRevisionRefs:g.disposition==="authorized"?[...g.authorityRefs]:[],policyRevisionRefs:g.disposition==="authorized"?[...g.policyRefs]:[],sourceGovernanceDigest:current.sourceGovernanceDigest,eligibilityDigest:current.eligibilityDigest,projectionRevision:current.projectionRevision,projectionDigest:current.projectionDigest,canonicalUnderstandingRevision:current.canonicalUnderstandingRevision,canonicalChangeResultDigest:current.canonicalChangeResultDigest,lineagePolicyVersion:current.lineagePolicyVersion};return{...unsigned,resultDigest:productArtifactBodyDigest(unsigned)};
}
export function assertProductArtifactCurrentAccessResultIntegrityV1(result:ProductArtifactCurrentAccessResultV1):void{const{resultDigest,...unsigned}=result;if(result.contractVersion!=="1"||resultDigest!==productArtifactBodyDigest(unsigned))throw new Error("Product artifact current-access result integrity failed.");}
