import "server-only";
import {sourceScopedDigest,type SourceScopedCandidateV1,type SourceScopedItemV1,type SourceScopedSectionsV1,type SourceScopedTransportV1} from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import {analyzeDeterministicDevelopmentCandidate,type SourceScopedExecutiveAnalysisOwner} from "./sourceScopedExecutiveAnalysis";
import type {GovernedConsequenceScopeBindingV1,ProposalKind,ReviewedCarryForwardProposalProvenanceV1} from "../workflow/leadershipConversation/contracts";
import type {LeadershipConversationProductOperations} from "../workflow/leadershipConversation/operations";

const empty:never[]=[];
const sectionsToCount=(sections:SourceScopedSectionsV1)=>Object.values(sections).reduce((total,items)=>total+items.reduce((sum,item)=>sum+item.statement.length,0),0);
export const reviewedCarryForwardDevelopmentTransport:SourceScopedTransportV1=async({request})=>{
  const cite=(index:number)=>{const source=request.packet.sources[index%request.packet.sources.length]!;return{sourceId:source.sourceId,sourceVersion:source.sourceVersion,bodyDigest:source.bodyDigest,sourcePacketDigest:request.packet.packetDigest};};
  const item=(statement:string,index:number,factCheck:SourceScopedItemV1["factCheck"]="HUMAN REVIEW REQUIRED"):SourceScopedItemV1=>({statement,citations:[cite(index)],factCheck});
  const bodies=request.packet.sources.map(source=>source.body.toLowerCase()),contains=(...phrases:string[])=>phrases.some(phrase=>bodies.some(body=>body.includes(phrase)));
  const titles=request.packet.sources.map(source=>source.title.toLowerCase());
  const sourceIndex=(pattern:RegExp,fallback:number)=>{const index=titles.findIndex(title=>pattern.test(title));return index<0?fallback:index;};
  const bodyFor=(pattern:RegExp)=>request.packet.sources.find(source=>pattern.test(source.title.toLowerCase()))?.body.toLowerCase()??"";
  const asterline=titles.length===5&&/October 15|launch/i.test(request.question)&&titles.some(title=>/sales and customer/.test(title))&&titles.some(title=>/strategy and launch/.test(title))&&titles.some(title=>/security, support, and financial/.test(title))&&titles.some(title=>/decisions, commitments, assumptions/.test(title))&&titles.some(title=>/product and engineering/.test(title))&&/atlas/.test(bodyFor(/sales and customer/))&&/october 15/.test(bodyFor(/strategy and launch/))&&/sec-31/.test(bodyFor(/security, support, and financial/))&&/c-01/.test(bodyFor(/decisions, commitments, assumptions/))&&/92%/.test(bodyFor(/product and engineering/));
  if(asterline){
    const sales=sourceIndex(/sales and customer/,0),strategy=sourceIndex(/strategy and launch/,1),security=sourceIndex(/security, support, and financial/,2),decisions=sourceIndex(/decisions, commitments, assumptions/,3),engineering=sourceIndex(/product and engineering/,4);
    const sections:SourceScopedSectionsV1={
      whatMattersNow:[item("Leadership must choose whether October 15 remains a general-release target, becomes a controlled pilot milestone, or moves until readiness and customer evidence are stronger.",strategy),item("Renewal protection is more consequential than the incremental revenue difference between an October general release and an October pilot.",security)],
      whyItMatters:[item("The evidence combines a proposed date, $730,000 of renewal exposure, a roughly $30,000 pilot-versus-general-release revenue difference, and readiness constraints that make the launch form consequential.",security)],
      competingExplanations:[item("Customer-driven pressure is plausible because Atlas is marked at risk, but the written evidence does not establish that general availability by October 15 is required.",sales),item("Readiness and unresolved technical defects are plausible because Engineering reports approximately 92% readiness, a 200-user performance miss, and remaining audit, export-alerting, and role-caching work.",engineering),item("Support-capacity constraints are independently plausible because broad launch demand is projected above current support capacity while a named-customer pilot is bounded.",security)],
      whatChanged:[item("The five-source review makes the launch choice, its conditions, and its evidence gaps explicit for human review.",strategy)],
      decisions:[item("Decision required: keep October 15 as a general-release target only if its stated security, performance, support, and commitment conditions are met; otherwise preserve the milestone as a controlled pilot or delay.",strategy),item("Option A — general availability on October 15: preserve renewal and revenue momentum, but only if the GA criteria, medium security findings, 200-user performance target, support readiness, and commitments are satisfied.",strategy),item("Option B — controlled pilot near October 15 or Option C — delay: protect renewals and operational reliability while accepting slower broad revenue or milestone movement; Atlas acceptance and dated remediation evidence are pivotal.",security)],
      notDecided:[item("October 15 remains proposed; no source records approval for general availability.",strategy),item("Whether Atlas will accept a controlled pilot with dated remediation instead of requiring general availability is unresolved.",sales)],
      commitments:[item("C-01: Engineering fix ENG-184 by September 26, owned by Priya Shah, high confidence; it addresses duplicate audit events on retry.",decisions),item("C-02: Engineering fix ENG-207 by October 7, owned by Mateo Ruiz, medium confidence; it addresses admin-role caching.",decisions),item("C-03: Security retest by October 10, dependent on C-02 and SEC-44, owned by the Security Lead.",decisions),item("C-04: Ask Atlas by September 12 whether a pilot plus dated remediation is sufficient, owned by the VP of Sales.",decisions),item("C-05: Complete support runbooks by September 30, owned by the Support Director.",decisions)],
      openQuestions:[item("Will Atlas accept a controlled pilot plus dated remediation, or does it require general availability by October 15?",sales),item("Are the scheduled export and access-review conditions mandatory for the pilot, and what evidence will Security accept by October 10?",security),item("Can Engineering meet the 200-user p95 target and close ENG-184, ENG-207, and export alerting before the GA decision?",engineering),item("Which smallest October milestone protects the $730,000 renewals without overstating readiness or committing beyond support capacity?",strategy)],
      contradictions:[item("Sales calls the Atlas and Beacon renewals committed while Customer Success marks Atlas at risk and Beacon likely to renew; the difference is a material evidence disagreement, not a settled fact.",sales),item("The launch deck says feature complete while Engineering reports approximately 92% readiness, unresolved defects, incomplete alerting/runbooks, and 3.8-second p95 at 200 users against a sub-two-second GA target.",engineering),item("Zero critical and high security findings does not itself approve GA: two medium findings and a documented access review remain conditions.",security)],
      evidenceUncertainty:[item("Atlas's pilot acceptance and the necessity of general availability by October 15 are not established in writing.",sales),item("The evidence does not yet establish that the 200-user target, export notification, or weekend on-call can be completed by the GA decision point.",engineering),item("Revenue urgency is real, but the sources do not justify treating the roughly $30,000 incremental October general-release revenue as worth unbounded renewal or operational risk.",security)],
      modelUncertainty:[],
      organizationalDisagreement:[item("Sales, Customer Success, Finance, Security, Support, and Engineering describe different risk thresholds; leadership must reconcile those accounts before treating the date as a decision.",sales)],
      attention:[item("Ask the VP of Sales to obtain Atlas's pilot answer before reaffirming October 15 as GA.",sales),item("Require dated evidence for security retests, Engineering defects and performance, export alerting, and support runbooks.",security),item("Do not repeat feature complete or committed renewals as settled approval without the underlying conditions and source distinctions.",engineering)],
      whatWouldChangeAssessment:[item("A written Atlas acceptance of a controlled pilot with dated remediation would favor the pilot option.",sales),item("Successful SEC-31/SEC-44 retests, closure of ENG-184 and ENG-207, export alerting, runbooks, and a 200-user result under two seconds would strengthen the GA option.",engineering),item("A written customer requirement for October 15 GA, or evidence that the pilot cannot protect the renewal, would change the balance toward GA if readiness conditions also hold.",sales)],
    };
    return{model:request.configuration.model,sections,usage:{inputTokens:request.packet.sources.reduce((n,s)=>n+s.body.length,0),outputTokens:sectionsToCount(sections),totalTokens:request.packet.sources.reduce((n,s)=>n+s.body.length,0)+sectionsToCount(sections)},latencyMs:0};
  }
  const product=contains("product roadmap sequencing","governed interface contract","stable review boundary"),pipeline=!product&&contains("implementation portfolio status","delivery capacity summary"),profile=product?"product":pipeline?"pipeline":"northstar";
  const sections:SourceScopedSectionsV1=profile==="product"?{
    whatMattersNow:[item("Interface sequencing remains the most material product delivery constraint.",1,"PASS"),item("Product leadership must choose whether to delay the milestone or narrow its scope.",2)],
    whyItMatters:[item("Customer commitments depend on a stable review boundary, explicit ownership, and the governed interface contract.",1,"PASS")],
    competingExplanations:[item("Migration sequencing and owner acceptance may each account for the current delivery risk.",1)],whatChanged:empty,
    decisions:[item("Choose whether to delay the product milestone or narrow its scope.",2)],notDecided:[item("The roadmap sequence and resource trade-off remain unresolved.",1)],
    commitments:[item("Complete the governed interface contract before confirming the customer commitment.",1)],openQuestions:[item("Which scope reduction preserves the customer commitment without bypassing the review boundary?",2)],contradictions:empty,
    evidenceUncertainty:[item("The current sources do not establish whether schedule or scope is the safer trade-off.",2)],modelUncertainty:[item("This working interpretation is limited to the authorized product source packet.",0)],organizationalDisagreement:empty,
    attention:[item("Resolve product and engineering sequencing before the next customer milestone.",1)],whatWouldChangeAssessment:[item("A validated migration plan and owner acceptance would change the delivery-risk assessment.",1)]
  }:profile==="pipeline"?{
    whatMattersNow:[item("Pipeline reliability is at risk where commitments precede feasibility and dependency review.",1,"PASS"),item("Conversion and delivery-capacity evidence must be separated before revising the forecast.",2)],
    whyItMatters:[item("Date changes and unresolved dependencies can make current coverage look more reliable than delivery evidence supports.",1,"PASS")],
    competingExplanations:[item("Lead mix, conversion lag, premature commitments, and delivery capacity remain competing explanations.",2)],whatChanged:empty,
    decisions:[item("Hold forecast changes until segment movement and delivery capacity are compared.",1)],notDecided:[item("No source establishes which segment accounts for the largest current gap.",2)],
    commitments:[item("Review enterprise conversion and delivery capacity at the next commercial checkpoint.",1)],openQuestions:[item("Which segment accounts for the largest share of the coverage and conversion gap?",2)],contradictions:empty,
    evidenceUncertainty:[item("The current packet does not isolate segment conversion from delivery feasibility.",2)],modelUncertainty:[item("This working interpretation is limited to the authorized commercial source packet.",0)],organizationalDisagreement:empty,
    attention:[item("Compare segment movement, conversion, and delivery dependencies before changing the forecast.",1)],whatWouldChangeAssessment:[item("A controlled segment comparison with current delivery capacity would change the forecast-risk assessment.",2)]
  }:{
    whatMattersNow:[item("Cross-functional sequencing and unclear decision ownership remain the primary organization-wide delivery constraint.",1,"PASS"),item("Leadership needs to resolve dependencies before adding or reaffirming commitments.",2)],
    whyItMatters:[item("Unresolved ownership and overloaded specialist capacity can propagate delay across product, sales, and delivery.",1,"PASS")],
    competingExplanations:[item("Capacity, governance, sequencing, and premature commitments remain plausible competing explanations.",2)],whatChanged:empty,
    decisions:[item("Set one cross-functional sequence and name the tie-breaker for feasibility exceptions.",1)],notDecided:[item("The current sources do not establish one primary cause of delay.",2)],
    commitments:[item("Leadership will assign owners to the highest-risk dependencies before the next staff conversation.",1)],openQuestions:[item("Which unresolved dependency requires the next leadership decision?",2)],contradictions:empty,
    evidenceUncertainty:[item("Similar utilization produced different outcomes, so staffing alone is not established as the cause.",2)],modelUncertainty:[item("This working interpretation is limited to the authorized leadership source packet.",0)],organizationalDisagreement:empty,
    attention:[item("Resolve the cross-functional dependency with the widest delivery impact.",1)],whatWouldChangeAssessment:[item("A dependency-level comparison of sequencing, ownership, and capacity would change the assessment.",2)]
  };
  return{model:request.configuration.model,sections,usage:{inputTokens:0,outputTokens:0,totalTokens:0},latencyMs:0};
};

type Definition={kind:Extract<ProposalKind,"decision-draft"|"commitment"|"unknown"|"follow-up-question"|"assumption-change">;summary:string;targetRef:string|null;item:SourceScopedItemV1;evidentiaryStatus:ReviewedCarryForwardProposalProvenanceV1["evidentiaryStatus"]};
function definitions(candidate:SourceScopedCandidateV1):Definition[]{const first=(items:SourceScopedItemV1[])=>{if(items.length!==1)throw new Error("Reviewed carry-forward development candidate is unavailable.");return items[0]!;};return[
  {kind:"decision-draft",summary:first(candidate.sections.decisions).statement,targetRef:null,item:first(candidate.sections.decisions),evidentiaryStatus:"inference"},
  {kind:"commitment",summary:first(candidate.sections.commitments).statement,targetRef:null,item:first(candidate.sections.commitments),evidentiaryStatus:"inference"},
  {kind:"unknown",summary:first(candidate.sections.openQuestions).statement,targetRef:null,item:first(candidate.sections.openQuestions),evidentiaryStatus:"uncertainty"},
  {kind:"assumption-change",summary:first(candidate.sections.competingExplanations).statement,targetRef:null,item:first(candidate.sections.competingExplanations),evidentiaryStatus:"inference"},
  {kind:"follow-up-question",summary:first(candidate.sections.attention).statement,targetRef:null,item:first(candidate.sections.attention),evidentiaryStatus:"inference"},
];}

export async function admitDeterministicReviewedCarryForward(input:{analysisOwner:SourceScopedExecutiveAnalysisOwner;operations:LeadershipConversationProductOperations;userId:string;organizationId:string;questionId:string;conversationId:string;uploadReceiptId:string;preparedWorkPublicationDigest:string;materialLineageDigest:string;governedScopeBinding:GovernedConsequenceScopeBindingV1;idempotencyKey:string}){
  const seriesId=`leadership-conversation-series:${input.conversationId}`,result=await analyzeDeterministicDevelopmentCandidate(input.analysisOwner,{subjectId:input.userId,organizationId:input.organizationId,questionId:input.questionId,seriesId,occurrenceId:input.conversationId,question:"What should this Leadership Conversation carry forward?"},reviewedCarryForwardDevelopmentTransport);
  if(result.status!=="eligible"||result.dispatchCount!==1)throw new Error("Reviewed carry-forward development candidate is unavailable.");
  const candidate=result.candidate,items=definitions(candidate),mapped=items.map((definition,index)=>{const claimId=sourceScopedDigest({candidateDigest:candidate.candidateDigest,ordinal:index+1,kind:definition.kind,summary:definition.summary}),base={contractVersion:"1" as const,generationCategory:"deterministic-development" as const,candidateDigest:candidate.candidateDigest,claimId,sourcePacketDigest:candidate.sourcePacketDigest,requestDigest:candidate.requestDigest,configurationDigest:candidate.configurationDigest,preparedWorkPublicationDigest:input.preparedWorkPublicationDigest,materialLineageDigest:input.materialLineageDigest,evidentiaryStatus:definition.evidentiaryStatus,citations:definition.item.citations},provenanceBase=base;return{kind:definition.kind,summary:definition.summary,targetRef:definition.targetRef,provenanceBase};});
  await input.operations.admitReviewedCarryForwardProposals({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,uploadReceiptId:input.uploadReceiptId,governedScopeBinding:input.governedScopeBinding,candidate:{organizationId:candidate.organizationId,subjectId:candidate.subjectId,questionId:candidate.questionId,seriesId:candidate.seriesId,occurrenceId:candidate.occurrenceId,candidateDigest:candidate.candidateDigest,sourcePacketDigest:candidate.sourcePacketDigest,requestDigest:candidate.requestDigest,configurationDigest:candidate.configurationDigest},preparedWorkPublicationDigest:input.preparedWorkPublicationDigest,materialLineageDigest:input.materialLineageDigest,definitions:mapped,idempotencyKey:input.idempotencyKey});
  return{candidate,proposalCount:mapped.length};
}
