import "server-only";
import {sourceScopedDigest,type SourceScopedCandidateV1,type SourceScopedItemV1,type SourceScopedSectionsV1,type SourceScopedTransportV1} from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
import {analyzeDeterministicDevelopmentCandidate,type SourceScopedExecutiveAnalysisOwner} from "./sourceScopedExecutiveAnalysis";
import type {GovernedConsequenceScopeBindingV1,ProposalKind,ReviewedCarryForwardProposalProvenanceV1} from "../workflow/leadershipConversation/contracts";
import type {LeadershipConversationProductOperations} from "../workflow/leadershipConversation/operations";

const empty:never[]=[];
export const reviewedCarryForwardDevelopmentTransport:SourceScopedTransportV1=async({request})=>{
  const cite=(index:number)=>{const source=request.packet.sources[index%request.packet.sources.length]!;return{sourceId:source.sourceId,sourceVersion:source.sourceVersion,bodyDigest:source.bodyDigest,sourcePacketDigest:request.packet.packetDigest};};
  const item=(statement:string,index:number,factCheck:SourceScopedItemV1["factCheck"]="HUMAN REVIEW REQUIRED"):SourceScopedItemV1[]=>[{statement,citations:[cite(index)],factCheck}];
  const sections:SourceScopedSectionsV1={whatMattersNow:item("Segment performance and delivery capacity need a bounded executive decision.",0),whyItMatters:item("A broad response could obscure materially different segment conditions.",0),competingExplanations:item("Lead mix, conversion lag, market conditions, and delivery capacity remain competing explanations.",2),whatChanged:empty,decisions:item("Keep the current broad hiring restraint while segment evidence is reviewed.",1),notDecided:empty,commitments:item("Review enterprise capacity and segment conversion at the next leadership checkpoint.",1),openQuestions:item("Which segment and constraint account for the largest share of the current gap?",0),contradictions:empty,evidenceUncertainty:item("The current evidence does not isolate one causal explanation.",2),modelUncertainty:item("This development synthesis may omit interpretations not explicit in the selected sources.",0),organizationalDisagreement:empty,attention:item("Compare segment conversion with delivery capacity before changing staffing or incentives.",1),whatWouldChangeAssessment:item("A controlled segment comparison or corrected authoritative source would change this assessment.",2)};
  return{model:request.configuration.model,sections,usage:{inputTokens:0,outputTokens:0,totalTokens:0},latencyMs:0};
};

type Definition={kind:Extract<ProposalKind,"decision-draft"|"commitment"|"unknown"|"follow-up-question"|"assumption-change">;summary:string;targetRef:string|null;item:SourceScopedItemV1;evidentiaryStatus:ReviewedCarryForwardProposalProvenanceV1["evidentiaryStatus"]};
function definitions(candidate:SourceScopedCandidateV1):Definition[]{const first=(items:SourceScopedItemV1[])=>{if(items.length!==1)throw new Error("Reviewed carry-forward development candidate is unavailable.");return items[0]!;};return[
  {kind:"decision-draft",summary:first(candidate.sections.decisions).statement,targetRef:null,item:first(candidate.sections.decisions),evidentiaryStatus:"inference"},
  {kind:"commitment",summary:first(candidate.sections.commitments).statement,targetRef:null,item:first(candidate.sections.commitments),evidentiaryStatus:"inference"},
  {kind:"unknown",summary:first(candidate.sections.openQuestions).statement,targetRef:null,item:first(candidate.sections.openQuestions),evidentiaryStatus:"uncertainty"},
  {kind:"assumption-change",summary:first(candidate.sections.competingExplanations).statement,targetRef:null,item:first(candidate.sections.competingExplanations),evidentiaryStatus:"inference"},
  {kind:"follow-up-question",summary:first(candidate.sections.attention).statement,targetRef:null,item:first(candidate.sections.attention),evidentiaryStatus:"inference"},
];}

export async function admitDeterministicReviewedCarryForward(input:{analysisOwner:SourceScopedExecutiveAnalysisOwner;operations:LeadershipConversationProductOperations;userId:string;organizationId:string;questionId:string;conversationId:string;uploadReceiptId:string;preparedWorkPublicationDigest:string;materialLineageDigest:string;governedScopeBinding:GovernedConsequenceScopeBindingV1;idempotencyKey:string}){
  const seriesId=`leadership-conversation-series:${input.conversationId}`,result=await analyzeDeterministicDevelopmentCandidate(input.analysisOwner,{subjectId:input.userId,organizationId:input.organizationId,questionId:input.questionId,seriesId,occurrenceId:input.conversationId,question:"What should this Leadership Conversation carry forward?"},reviewedCarryForwardDevelopmentTransport);
  if(result.status!=="eligible"||result.dispatchCount!==1)throw new Error("Reviewed carry-forward development candidate is unavailable.");
  const candidate=result.candidate,items=definitions(candidate),mapped=items.map((definition,index)=>{const claimId=sourceScopedDigest({candidateDigest:candidate.candidateDigest,ordinal:index+1,kind:definition.kind,summary:definition.summary}),base={contractVersion:"1" as const,generationCategory:"deterministic-development" as const,candidateDigest:candidate.candidateDigest,claimId,sourcePacketDigest:candidate.sourcePacketDigest,requestDigest:candidate.requestDigest,configurationDigest:candidate.configurationDigest,preparedWorkPublicationDigest:input.preparedWorkPublicationDigest,materialLineageDigest:input.materialLineageDigest,evidentiaryStatus:definition.evidentiaryStatus,citations:definition.item.citations},provenanceBase=base;return{kind:definition.kind,summary:definition.summary,targetRef:definition.targetRef,provenanceBase};});
  await input.operations.admitReviewedCarryForwardProposals({userId:input.userId,organizationId:input.organizationId,questionId:input.questionId,conversationId:input.conversationId,uploadReceiptId:input.uploadReceiptId,governedScopeBinding:input.governedScopeBinding,candidate:{organizationId:candidate.organizationId,subjectId:candidate.subjectId,questionId:candidate.questionId,seriesId:candidate.seriesId,occurrenceId:candidate.occurrenceId,candidateDigest:candidate.candidateDigest,sourcePacketDigest:candidate.sourcePacketDigest,requestDigest:candidate.requestDigest,configurationDigest:candidate.configurationDigest},preparedWorkPublicationDigest:input.preparedWorkPublicationDigest,materialLineageDigest:input.materialLineageDigest,definitions:mapped,idempotencyKey:input.idempotencyKey});
  return{candidate,proposalCount:mapped.length};
}
