import "server-only";
import {randomUUID} from "node:crypto";
import {mkdir,open,readFile,readdir,rename,stat,unlink} from "node:fs/promises";
import path from "node:path";
import type { Sql } from "postgres";
import {buildSourceScopedExecutiveAnalysisRequest,sourceScopedModelConfiguration} from "../../lib/analysis/buildSourceScopedExecutiveAnalysisRequest";
import {runSourceScopedFrontierAnalysis} from "../../lib/analysis/runSourceScopedFrontierAnalysis";
import {assertSourceScopedCandidate,DEFAULT_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS,sourceScopedDigest,sourceScopedStable,unavailable,type SourceScopedCandidateV1,type SourceScopedPacketV1,type SourceScopedRequestV1,type SourceScopedResultV1,type SourceScopedTransportV1} from "../../lib/analysis/sourceScopedExecutiveAnalysisContracts";
export type SelectedLeadershipSourceV1={organizationId:string;sourceId:string;sourceVersion:string;title:string;effectiveAt:string;authority:"authoritative"|"preliminary";normalizedBodyDigest:string};
export type SelectedSourceAccessV1={disposition:"eligible";accessDigest:string}|{disposition:"unavailable"};
export type SourceScopedUnavailableReasonV1="no-authorized-source-bodies"|"source-access-changed"|"analysis-construction-failure"|"request-failed";
export const SOURCE_SCOPED_LIFECYCLE_STAGES=["plan-frozen","request-digests-frozen","transport-entry-persisted","response-headers-received","response-body-received","candidate-parsed","candidate-validated","terminal-result-persisted"] as const;
export type SourceScopedLifecycleStageV1=typeof SOURCE_SCOPED_LIFECYCLE_STAGES[number];
export type SourceScopedTerminalV1="eligible"|"provider-rejected"|"transport-failed"|"response-too-large"|"malformed-response"|"model-mismatch"|"citation-failed"|"candidate-validation-failed"|"pre-dispatch-failed";
type MemoryV1={rss:number;heapUsed:number;heapTotal:number;external:number;arrayBuffers:number};
type StageV1={stage:SourceScopedLifecycleStageV1;at:string;memory:MemoryV1;responseByteCount:number|null;responseDigest:string|null;returnedModel:string|null;terminal:SourceScopedTerminalV1|null};
export type AttemptV1={lifecycleVersion:"1";attemptVersion:"1";attemptId:string;occurrenceDigest:string;preparedWorkPublicationDigest:string;materialLineageDigest:string;sourcePacketDigest:string;requestDigest:string;promptDigest:string;schemaDigest:string;configurationDigest:string;requestedModel:string;reasoning:"high";maxOutputTokens:25000;attemptNonce:string;createdAt:string;retryCount:0;history:StageV1[];receiptDigest:string};
type ClaimV1={lifecycleVersion:"1";attemptId:string;occurrenceDigest:string;requestDigest:string;claimDigest:string};
const validatedPublications=new WeakSet<object>();
export type ValidatedSourceScopedAnalysisPublicationV1={contractVersion:"1";candidate:SourceScopedCandidateV1;request:SourceScopedRequestV1;preparedWorkPublicationDigest:string;materialLineageDigest:string;lifecycleAttempt:AttemptV1;resultDigest:string;publicationDigest:string};
export function verifyServerMintedSourceScopedAnalysisPublication(value:ValidatedSourceScopedAnalysisPublicationV1){if(!validatedPublications.has(value))throw new Error("Validated source-scoped analysis publication is unavailable.");assertSourceScopedCandidate(value.candidate,value.request);assertAttempt(value.lifecycleAttempt);const terminal=value.lifecycleAttempt.history.at(-1),expectedResultDigest=sourceScopedDigest({contractVersion:"1",status:"eligible",candidate:value.candidate,dispatchCount:1});if(terminal?.stage!=="terminal-result-persisted"||terminal.terminal!=="eligible"||value.resultDigest!==expectedResultDigest||value.lifecycleAttempt.requestDigest!==value.request.requestDigest||value.lifecycleAttempt.sourcePacketDigest!==value.request.packet.packetDigest||value.lifecycleAttempt.configurationDigest!==value.request.configuration.configurationDigest||value.lifecycleAttempt.requestedModel!==value.candidate.model||value.lifecycleAttempt.preparedWorkPublicationDigest!==value.preparedWorkPublicationDigest||value.lifecycleAttempt.materialLineageDigest!==value.materialLineageDigest)throw new Error("Validated source-scoped analysis publication is unavailable.");const{publicationDigest,...unsigned}=value;if(sourceScopedDigest(unsigned)!==publicationDigest)throw new Error("Validated source-scoped analysis publication is unavailable.");return value;}
const exact=(value:unknown,keys:string[])=>Boolean(value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).sort().join("\0")===[...keys].sort().join("\0"));
const allowedTransitions:Record<SourceScopedLifecycleStageV1,readonly SourceScopedLifecycleStageV1[]>={"plan-frozen":["request-digests-frozen"],"request-digests-frozen":["transport-entry-persisted","terminal-result-persisted"],"transport-entry-persisted":["response-headers-received","terminal-result-persisted"],"response-headers-received":["response-body-received","terminal-result-persisted"],"response-body-received":["candidate-parsed","terminal-result-persisted"],"candidate-parsed":["candidate-validated","terminal-result-persisted"],"candidate-validated":["terminal-result-persisted"],"terminal-result-persisted":[]};
const snapshot=():MemoryV1=>{const value=process.memoryUsage();return{rss:value.rss,heapUsed:value.heapUsed,heapTotal:value.heapTotal,external:value.external,arrayBuffers:value.arrayBuffers??0};};
const digestReceipt=(value:Omit<AttemptV1,"receiptDigest">)=>sourceScopedDigest(value);
function assertAttempt(value:AttemptV1){if(!exact(value,["lifecycleVersion","attemptVersion","attemptId","occurrenceDigest","preparedWorkPublicationDigest","materialLineageDigest","sourcePacketDigest","requestDigest","promptDigest","schemaDigest","configurationDigest","requestedModel","reasoning","maxOutputTokens","attemptNonce","createdAt","retryCount","history","receiptDigest"])||value.lifecycleVersion!=="1"||value.attemptVersion!=="1"||value.reasoning!=="high"||value.maxOutputTokens!==25000||value.retryCount!==0||!Array.isArray(value.history)||!value.history.length||value.history[0]?.stage!=="plan-frozen")throw new Error("Frontier lifecycle receipt is invalid.");let prior:SourceScopedLifecycleStageV1|undefined;for(const item of value.history){if(!exact(item,["stage","at","memory","responseByteCount","responseDigest","returnedModel","terminal"])||!exact(item.memory,["rss","heapUsed","heapTotal","external","arrayBuffers"])||!Object.values(item.memory).every(number=>Number.isSafeInteger(number)&&number>=0))throw new Error("Frontier lifecycle receipt is invalid.");if(prior&&!allowedTransitions[prior].includes(item.stage))throw new Error("Frontier lifecycle stages are invalid.");prior=item.stage;}const{receiptDigest,...unsigned}=value;if(receiptDigest!==digestReceipt(unsigned))throw new Error("Frontier lifecycle receipt integrity failed.");}
async function safeDirectory(root:string){if(!path.isAbsolute(root))throw new Error("Frontier lifecycle root is unavailable.");const value=await stat(root);if(!value.isDirectory()||value.isSymbolicLink()||(value.mode&0o777)!==0o700||value.uid!==process.getuid?.())throw new Error("Frontier lifecycle root is unavailable.");for(const child of ["attempts","active"]){const target=path.join(root,child);await mkdir(target,{mode:0o700,recursive:true});const state=await stat(target);if(!state.isDirectory()||state.isSymbolicLink()||(state.mode&0o777)!==0o700||state.uid!==process.getuid?.())throw new Error("Frontier lifecycle root is unavailable.");}return root;}
async function atomicJson(file:string,value:unknown,exclusive=false){const directory=path.dirname(file),temporary=path.join(directory,`.${path.basename(file)}.${randomUUID()}.tmp`),handle=await open(temporary,"wx",0o600);try{await handle.writeFile(`${sourceScopedStable(value)}\n`,"utf8");await handle.sync();}finally{await handle.close();}const state=await stat(temporary);if(!state.isFile()||state.isSymbolicLink()||(state.mode&0o777)!==0o600||state.uid!==process.getuid?.()){await unlink(temporary).catch(()=>{});throw new Error("Frontier lifecycle file is unsafe.");}if(exclusive){try{const target=await open(file,"wx",0o600);try{await target.writeFile(await readFile(temporary));await target.sync();}finally{await target.close();}}finally{await unlink(temporary).catch(()=>{});}}else await rename(temporary,file);const directoryHandle=await open(directory,"r");try{await directoryHandle.sync();}finally{await directoryHandle.close();}}
async function readSafe<T>(file:string):Promise<T>{const state=await stat(file);if(!state.isFile()||state.isSymbolicLink()||(state.mode&0o777)!==0o600||state.uid!==process.getuid?.())throw new Error("Frontier lifecycle file is unsafe.");return JSON.parse(await readFile(file,"utf8")) as T;}
export type SourceScopedLifecycleHooksV1={transportEntry():Promise<void>;responseHeaders(returnedModel:string|null):Promise<void>;responseBody(input:{responseByteCount:number;responseDigest:string}):Promise<void>;candidateParsed(returnedModel:string):Promise<void>;terminal(value:SourceScopedTerminalV1):Promise<void>};
export type LifecycleAwareSourceScopedTransportV1=SourceScopedTransportV1&{withLifecycle?(hooks:SourceScopedLifecycleHooksV1):SourceScopedTransportV1};
export type DurableLifecycleV1={hooks():SourceScopedLifecycleHooksV1;validated():Promise<void>;finish(value:SourceScopedTerminalV1):Promise<void>;classification():ReturnType<SourceScopedFrontierAttemptLifecycleV1["classification"]>;receipt():AttemptV1};
export type SourceScopedLifecycleStoreV1={begin(input:{occurrenceDigest:string;preparedWorkPublicationDigest:string;materialLineageDigest:string;sourcePacketDigest:string;requestDigest:string;promptDigest:string;schemaDigest:string;configurationDigest:string;requestedModel:string}):Promise<DurableLifecycleV1>};
export class SourceScopedFrontierAttemptLifecycleV1{
 private constructor(private attempt:AttemptV1,private readonly attemptFile:string,private readonly claimFile:string){}
 static async inspect(root:string){await safeDirectory(root);return{active:path.join(root,"active"),attempts:path.join(root,"attempts")};}
 static async reconcile(root:string,occurrenceDigest:string){await safeDirectory(root);const claimFile=path.join(root,"active",`${occurrenceDigest}.json`),claim=await readSafe<ClaimV1>(claimFile);if(!exact(claim,["lifecycleVersion","attemptId","occurrenceDigest","requestDigest","claimDigest"])||claim.lifecycleVersion!=="1"||claim.occurrenceDigest!==occurrenceDigest){throw new Error("Frontier lifecycle claim is invalid.");}const{claimDigest,...unsigned}=claim;if(claimDigest!==sourceScopedDigest(unsigned))throw new Error("Frontier lifecycle claim integrity failed.");const attempt=await this.readAttempt(path.join(root,"attempts",`${claim.attemptId}.json`));if(attempt.attemptId!==claim.attemptId||attempt.occurrenceDigest!==claim.occurrenceDigest||attempt.requestDigest!==claim.requestDigest)throw new Error("Frontier lifecycle claim binding failed.");const last=attempt.history.at(-1)!;if(last.stage==="terminal-result-persisted")throw new Error("Frontier lifecycle terminal claim is invalid.");return{attemptId:attempt.attemptId,receiptDigest:attempt.receiptDigest,lastStage:last.stage,classification:last.stage==="plan-frozen"||last.stage==="request-digests-frozen"?"CONCLUSIVELY NOT DISPATCHED" as const:"TRANSPORT ENTERED — ATTEMPT CONSUMED" as const};}
 static async begin(root:string,input:{occurrenceDigest:string;preparedWorkPublicationDigest:string;materialLineageDigest:string;sourcePacketDigest:string;requestDigest:string;promptDigest:string;schemaDigest:string;configurationDigest:string;requestedModel:string}){await safeDirectory(root);const attemptNonce=randomUUID(),createdAt=new Date().toISOString(),attemptId=sourceScopedDigest({contractVersion:"1",...input,attemptNonce,createdAt}),claimFile=path.join(root,"active",`${input.occurrenceDigest}.json`),attemptFile=path.join(root,"attempts",`${attemptId}.json`),claimBase={lifecycleVersion:"1" as const,attemptId,occurrenceDigest:input.occurrenceDigest,requestDigest:input.requestDigest},claim:ClaimV1={...claimBase,claimDigest:sourceScopedDigest(claimBase)};await atomicJson(claimFile,claim,true);const unsigned={lifecycleVersion:"1" as const,attemptVersion:"1" as const,attemptId,...input,reasoning:"high" as const,maxOutputTokens:25000 as const,attemptNonce,createdAt,retryCount:0 as const,history:[{stage:"plan-frozen" as const,at:createdAt,memory:snapshot(),responseByteCount:null,responseDigest:null,returnedModel:null,terminal:null}]};let attempt:AttemptV1={...unsigned,receiptDigest:digestReceipt(unsigned)};try{await atomicJson(attemptFile,attempt,true);attempt=await this.append(attemptFile,attempt,"request-digests-frozen",{});}catch(error){await unlink(claimFile).catch(()=>{});throw error;}return new this(attempt,attemptFile,claimFile);}
 static async readAttempt(file:string){const value=await readSafe<AttemptV1>(file);assertAttempt(value);return value;}
 static async append(file:string,attempt:AttemptV1,stage:SourceScopedLifecycleStageV1,fields:{responseByteCount?:number;responseDigest?:string;returnedModel?:string;terminal?:SourceScopedTerminalV1}){assertAttempt(attempt);const priorStage=attempt.history.at(-1)!.stage;if(!allowedTransitions[priorStage].includes(stage))throw new Error("Frontier lifecycle transition is incompatible.");const entry:StageV1={stage,at:new Date().toISOString(),memory:snapshot(),responseByteCount:fields.responseByteCount??null,responseDigest:fields.responseDigest??null,returnedModel:fields.returnedModel??null,terminal:fields.terminal??null},{receiptDigest:_,...prior}=attempt,unsigned={...prior,history:[...attempt.history,entry]},next:AttemptV1={...unsigned,receiptDigest:digestReceipt(unsigned)};await atomicJson(file,next);return next;}
 hooks():SourceScopedLifecycleHooksV1{return{transportEntry:()=>this.transition("transport-entry-persisted",{}),responseHeaders:returnedModel=>this.transition("response-headers-received",returnedModel?{returnedModel}:{}),responseBody:value=>this.transition("response-body-received",value),candidateParsed:returnedModel=>this.transition("candidate-parsed",{returnedModel}),terminal:value=>this.finish(value)};}
 async transition(stage:SourceScopedLifecycleStageV1,fields:{responseByteCount?:number;responseDigest?:string;returnedModel?:string}){this.attempt=await SourceScopedFrontierAttemptLifecycleV1.append(this.attemptFile,this.attempt,stage,fields);}
 async finish(terminal:SourceScopedTerminalV1){if(this.attempt.history.at(-1)?.stage==="terminal-result-persisted")return;this.attempt=await SourceScopedFrontierAttemptLifecycleV1.append(this.attemptFile,this.attempt,"terminal-result-persisted",{terminal});await unlink(this.claimFile);const directory=await open(path.dirname(this.claimFile),"r");try{await directory.sync();}finally{await directory.close();}}
 async validated(){await this.transition("candidate-validated",{});await this.finish("eligible");}
 classification(){const last=this.attempt.history.at(-1)!;return last.stage==="terminal-result-persisted"?last.terminal:last.stage==="plan-frozen"||last.stage==="request-digests-frozen"?"CONCLUSIVELY NOT DISPATCHED":"TRANSPORT ENTERED — ATTEMPT CONSUMED";}
 receipt(){return this.attempt;}
}

/** Durable serverless lifecycle implementation. It persists the same bounded
 * receipt payload as the filesystem owner and never stores source bodies. */
export class PostgresSourceScopedFrontierAttemptLifecycleV1 {
 private constructor(private readonly sql:Sql<Record<string,unknown>>,private attempt:AttemptV1){}
 static async begin(sql:Sql<Record<string,unknown>>,input:{occurrenceDigest:string;preparedWorkPublicationDigest:string;materialLineageDigest:string;sourcePacketDigest:string;requestDigest:string;promptDigest:string;schemaDigest:string;configurationDigest:string;requestedModel:string}){const attemptNonce=randomUUID(),createdAt=new Date().toISOString(),attemptId=sourceScopedDigest({contractVersion:"1",...input,attemptNonce,createdAt}),unsigned={lifecycleVersion:"1" as const,attemptVersion:"1" as const,attemptId,...input,reasoning:"high" as const,maxOutputTokens:25000 as const,attemptNonce,createdAt,retryCount:0 as const,history:[{stage:"plan-frozen" as const,at:createdAt,memory:snapshot(),responseByteCount:null,responseDigest:null,returnedModel:null,terminal:null}]},attempt:AttemptV1={...unsigned,receiptDigest:digestReceipt(unsigned)};await sql.begin("isolation level serializable",async tx=>{const claim=await tx<{attempt_id:string}[]>`SELECT attempt_id FROM chief_analysis_active_claims WHERE occurrence_digest=${input.occurrenceDigest} FOR UPDATE`;if(claim.length)throw new Error("Frontier lifecycle occurrence is already active.");await tx`INSERT INTO chief_analysis_attempts (attempt_id,occurrence_digest,request_digest,receipt_digest,last_stage,terminal,payload_text) VALUES (${attemptId},${input.occurrenceDigest},${input.requestDigest},${attempt.receiptDigest},'plan-frozen',NULL,${JSON.stringify(attempt)})`;const claimBase={lifecycleVersion:"1" as const,attemptId,occurrenceDigest:input.occurrenceDigest,requestDigest:input.requestDigest},claimPayload={...claimBase,claimDigest:sourceScopedDigest(claimBase)};await tx`INSERT INTO chief_analysis_active_claims (occurrence_digest,attempt_id,request_digest,claim_payload_text) VALUES (${input.occurrenceDigest},${attemptId},${input.requestDigest},${JSON.stringify(claimPayload)})`;});const lifecycle=new this(sql,attempt);await lifecycle.transition("request-digests-frozen",{});return lifecycle;}
 hooks():SourceScopedLifecycleHooksV1{return{transportEntry:()=>this.transition("transport-entry-persisted",{}),responseHeaders:returnedModel=>this.transition("response-headers-received",returnedModel?{returnedModel}:{}),responseBody:value=>this.transition("response-body-received",value),candidateParsed:returnedModel=>this.transition("candidate-parsed",{returnedModel}),terminal:value=>this.finish(value)};}
 async transition(stage:SourceScopedLifecycleStageV1,fields:{responseByteCount?:number;responseDigest?:string;returnedModel?:string}){const prior=this.attempt.history.at(-1)!.stage;if(!allowedTransitions[prior].includes(stage))throw new Error("Frontier lifecycle transition is incompatible.");const entry:StageV1={stage,at:new Date().toISOString(),memory:snapshot(),responseByteCount:fields.responseByteCount??null,responseDigest:fields.responseDigest??null,returnedModel:fields.returnedModel??null,terminal:null},{receiptDigest:_,...base}=this.attempt,next:AttemptV1={...base,history:[...this.attempt.history,entry],receiptDigest:""};const{receiptDigest,...stable}=next;next.receiptDigest=digestReceipt(stable);assertAttempt(next);const updated=await this.sql<{attempt_id:string}[]>`UPDATE chief_analysis_attempts SET receipt_digest=${next.receiptDigest},last_stage=${stage},payload_text=${JSON.stringify(next)} WHERE attempt_id=${next.attemptId} AND receipt_digest=${this.attempt.receiptDigest} RETURNING attempt_id`;if(updated.length!==1)throw new Error("Frontier lifecycle transition conflict.");this.attempt=next;}
 async finish(terminal:SourceScopedTerminalV1){if(this.attempt.history.at(-1)?.stage==="terminal-result-persisted")return;const entry:StageV1={stage:"terminal-result-persisted",at:new Date().toISOString(),memory:snapshot(),responseByteCount:null,responseDigest:null,returnedModel:null,terminal},{receiptDigest:_,...base}=this.attempt,next:AttemptV1={...base,history:[...this.attempt.history,entry],receiptDigest:""};const{receiptDigest,...stable}=next;next.receiptDigest=digestReceipt(stable);assertAttempt(next);await this.sql.begin("isolation level serializable",async tx=>{const updated=await tx<{attempt_id:string}[]>`UPDATE chief_analysis_attempts SET receipt_digest=${next.receiptDigest},last_stage='terminal-result-persisted',terminal=${terminal},payload_text=${JSON.stringify(next)} WHERE attempt_id=${next.attemptId} AND receipt_digest=${this.attempt.receiptDigest} RETURNING attempt_id`;if(updated.length!==1)throw new Error("Frontier lifecycle transition conflict.");const removed=await tx<{attempt_id:string}[]>`DELETE FROM chief_analysis_active_claims WHERE occurrence_digest=${next.occurrenceDigest} AND attempt_id=${next.attemptId} RETURNING attempt_id`;if(removed.length!==1)throw new Error("Frontier lifecycle claim conflict.");});this.attempt=next;}
 async validated(){await this.transition("candidate-validated",{});await this.finish("eligible");}
 classification(){const last=this.attempt.history.at(-1)!;return last.stage==="terminal-result-persisted"?last.terminal:last.stage==="plan-frozen"||last.stage==="request-digests-frozen"?"CONCLUSIVELY NOT DISPATCHED":"TRANSPORT ENTERED — ATTEMPT CONSUMED";}
 receipt(){return this.attempt;}
}
/** The request identity remains intact at every source/body boundary.  This
 * prevents an implementation from authorizing the overall analysis and then
 * accidentally reading a cached or protected source under a weaker scope. */
export type SourceScopedExecutiveAnalysisDependencies={authorizeDesignatedPrincipal(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string}):Promise<boolean>;selectCurrentPrepareSources(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string}):Promise<SelectedLeadershipSourceV1[]>;resolveLifecycleBinding?(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string}):Promise<{preparedWorkPublicationDigest:string;materialLineageDigest:string}>;lifecycleStore?:SourceScopedLifecycleStoreV1;resolveCurrentAccess(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string;source:SelectedLeadershipSourceV1}):Promise<SelectedSourceAccessV1>;readProtectedBody(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string;source:SelectedLeadershipSourceV1;access:Extract<SelectedSourceAccessV1,{disposition:"eligible"}>}):Promise<string>;transport?:LifecycleAwareSourceScopedTransportV1;model:string;providerFamily:string;timeoutMs?:number|null;lifecycleRoot?:string;onRequestBuilt?():void;onUnavailable?(reason:SourceScopedUnavailableReasonV1):void};
export class SourceScopedExecutiveAnalysisOwner {
  private lifecycleConfiguration:{root:string;resolve(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string}):Promise<{preparedWorkPublicationDigest:string;materialLineageDigest:string}>}|undefined;
  private lastUnavailableReason:SourceScopedUnavailableReasonV1|undefined;
  constructor(private readonly dependencies:SourceScopedExecutiveAnalysisDependencies) {}
  configureLifecycle(value:NonNullable<SourceScopedExecutiveAnalysisOwner["lifecycleConfiguration"]>){this.lifecycleConfiguration=value;}
  unavailableReason(){return this.lastUnavailableReason;}
  async analyze(input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string;question:string}):Promise<SourceScopedResultV1&{validatedPublication?:ValidatedSourceScopedAnalysisPublicationV1}>{
    let lifecycle:DurableLifecycleV1|undefined,lifecycleBinding:{preparedWorkPublicationDigest:string;materialLineageDigest:string}|undefined,stage:SourceScopedUnavailableReasonV1="analysis-construction-failure";
    const unavailableResult=(reason:SourceScopedUnavailableReasonV1,dispatchCount:0|1)=>{this.lastUnavailableReason=reason;this.dependencies.onUnavailable?.(reason);return unavailable(dispatchCount);};
    try {
      if(this.dependencies.timeoutMs===null||!await this.dependencies.authorizeDesignatedPrincipal(input))return unavailableResult("source-access-changed",0);
      stage="no-authorized-source-bodies";
      const selected=await this.dependencies.selectCurrentPrepareSources(input);
      if(!selected.length||selected.some(source=>source.organizationId!==input.organizationId)||new Set(selected.map(source=>source.sourceId)).size!==selected.length)return unavailableResult(stage,0);
      const sources=[];
      for(const source of [...selected].sort((a,b)=>a.effectiveAt.localeCompare(b.effectiveAt)||a.sourceId.localeCompare(b.sourceId))){
        stage="source-access-changed";
        const access=await this.dependencies.resolveCurrentAccess({...input,source});
        if(access.disposition!=="eligible")return unavailableResult(stage,0);
        stage="no-authorized-source-bodies";
        const body=await this.dependencies.readProtectedBody({...input,source,access}),bodyDigest=sourceScopedDigest(body);
        if(!body.trim()||bodyDigest!==source.normalizedBodyDigest)return unavailableResult(stage,0);
        const base={organizationId:source.organizationId,sourceId:source.sourceId,sourceVersion:source.sourceVersion,title:source.title,effectiveAt:source.effectiveAt,authority:source.authority,bodyDigest,body};
        sources.push({...base,entryDigest:sourceScopedDigest(base)});
      }
      stage="analysis-construction-failure";
      const packetBase={contractVersion:"1" as const,organizationId:input.organizationId,subjectId:input.subjectId,questionId:input.questionId,seriesId:input.seriesId,occurrenceId:input.occurrenceId,sources},packet:SourceScopedPacketV1={...packetBase,packetDigest:sourceScopedDigest(packetBase)},configuration=sourceScopedModelConfiguration({providerFamily:this.dependencies.providerFamily,model:this.dependencies.model,timeoutMs:this.dependencies.timeoutMs??undefined}),built=buildSourceScopedExecutiveAnalysisRequest({packet,question:input.question,configuration});
      this.dependencies.onRequestBuilt?.();
      let transport:SourceScopedTransportV1|undefined=this.dependencies.transport;
      const lifecycleConfiguration=this.lifecycleConfiguration??(this.dependencies.lifecycleRoot&&this.dependencies.resolveLifecycleBinding?{root:this.dependencies.lifecycleRoot,resolve:this.dependencies.resolveLifecycleBinding}:undefined);
      if(this.dependencies.transport&&(lifecycleConfiguration||this.dependencies.lifecycleStore)){lifecycleBinding=await (lifecycleConfiguration?.resolve(input)??this.dependencies.resolveLifecycleBinding!(input));const lifecycleInput={occurrenceDigest:sourceScopedDigest({organizationId:input.organizationId,questionId:input.questionId,seriesId:input.seriesId,occurrenceId:input.occurrenceId}),...lifecycleBinding,sourcePacketDigest:packet.packetDigest,requestDigest:built.request.requestDigest,promptDigest:built.request.promptDigest,schemaDigest:built.request.schemaDigest,configurationDigest:configuration.configurationDigest,requestedModel:configuration.model};lifecycle=this.dependencies.lifecycleStore?await this.dependencies.lifecycleStore.begin(lifecycleInput):await SourceScopedFrontierAttemptLifecycleV1.begin(lifecycleConfiguration!.root,lifecycleInput);const hooks=lifecycle.hooks(),aware=this.dependencies.transport;transport=aware.withLifecycle?aware.withLifecycle(hooks):async value=>{await hooks.transportEntry();return aware(value);};}
      const result=await runSourceScopedFrontierAnalysis({...built,transport});
      if(lifecycle){if(result.status==="eligible")await lifecycle.validated();else await lifecycle.finish("candidate-validation-failed");}
      if(result.status!=="eligible")this.lastUnavailableReason=result.dispatchCount===1?"request-failed":"analysis-construction-failure";
      if(result.status!=="eligible"||!lifecycle||!lifecycleBinding)return result;
      const lifecycleAttempt=lifecycle.receipt(),unsigned={contractVersion:"1" as const,candidate:result.candidate,request:built.request,preparedWorkPublicationDigest:lifecycleBinding.preparedWorkPublicationDigest,materialLineageDigest:lifecycleBinding.materialLineageDigest,lifecycleAttempt,resultDigest:result.resultDigest},validatedPublication:ValidatedSourceScopedAnalysisPublicationV1={...unsigned,publicationDigest:sourceScopedDigest(unsigned)};validatedPublications.add(validatedPublication);return{...result,validatedPublication};
    } catch {
      const classification=lifecycle?.classification();
      if(lifecycle&&classification==="CONCLUSIVELY NOT DISPATCHED")await lifecycle.finish("pre-dispatch-failed").catch(()=>{});
      const dispatchCount=classification&&classification!=="CONCLUSIVELY NOT DISPATCHED"?1:0;
      return unavailableResult(dispatchCount===1?"request-failed":stage,dispatchCount);
    }
  }
}

export async function analyzeDeterministicDevelopmentCandidate(owner:SourceScopedExecutiveAnalysisOwner,input:{subjectId:string;organizationId:string;questionId:string;seriesId:string;occurrenceId:string;question:string},transport:SourceScopedTransportV1,onUnavailable?:(reason:SourceScopedUnavailableReasonV1)=>void):Promise<SourceScopedResultV1>{
  if(process.env.NODE_ENV==="production")return unavailable(0);
  const dependencies=(owner as unknown as {dependencies:SourceScopedExecutiveAnalysisDependencies}).dependencies;
  const deterministicOwner=new SourceScopedExecutiveAnalysisOwner({...dependencies,timeoutMs:DEFAULT_SOURCE_SCOPED_ANALYSIS_TIMEOUT_MS,providerFamily:"deterministic-development",transport,lifecycleRoot:undefined,resolveLifecycleBinding:undefined});
  const result=await deterministicOwner.analyze(input);
  if(result.status!=="eligible")onUnavailable?.(deterministicOwner.unavailableReason()??(result.dispatchCount===1?"request-failed":"analysis-construction-failure"));
  return result;
}
