import type{ChiefCommunicationPlanV1}from"../workflow/leadershipConversation/chiefCommunicationPlan";import{normalizeChiefCommunication}from"../workflow/leadershipConversation/chiefCommunicationPlan";import type{ChiefCommunicationRenderedV1}from"./chiefLeadershipCommunicationRenderer";
export type ChiefCommunicationFidelityResultV1={result:"PASS";sentenceCount:number;sentenceLineageCoverage:100;unsupportedStatements:0;confidenceMovements:0;inventedClaims:0;inventedQuestions:0;inventedRecommendations:0;repeatedClaims:0;repeatedQuestions:0;progressiveDisclosureDuplicates:0;candidateB2Behaviors:0};
export function validateChiefLeadershipCommunicationFidelityV1(plan:ChiefCommunicationPlanV1,rendered:ChiefCommunicationRenderedV1):ChiefCommunicationFidelityResultV1{const approved=new Map(plan.items.map(item=>[item.itemId,item])),first=Object.values(rendered.firstSurface).flatMap(value=>value??[]),deeper=Object.values(rendered.progressiveDisclosure).flatMap(value=>value??[]),all=[...first,...deeper],seen=new Set<string>(),firstText=new Set(first.map(item=>normalizeChiefCommunication(item.text)));let claims=0,questions=0,disclosure=0;for(const value of all){const item=approved.get(value.itemId);if(!item||item.semanticSourceId!==value.semanticSourceId||!value.lineage.length||value.text!==item.renderedContent||!item.confidencePreserved)throw new Error("Chief communication sentence is not faithful to its plan.")}for(const value of first){const normalized=normalizeChiefCommunication(value.text);if(seen.has(normalized))value.text.trim().endsWith("?")?questions++:claims++;seen.add(normalized)}for(const value of deeper)if(firstText.has(normalizeChiefCommunication(value.text)))disclosure++;if(claims||questions||disclosure||rendered.metrics.wordCount>180)throw new Error("Chief communication fidelity invariant failed.");return{result:"PASS",sentenceCount:all.length,sentenceLineageCoverage:100,unsupportedStatements:0,confidenceMovements:0,inventedClaims:0,inventedQuestions:0,inventedRecommendations:0,repeatedClaims:0,repeatedQuestions:0,progressiveDisclosureDuplicates:0,candidateB2Behaviors:0}}

import type{ChiefCommunicationPlanB11V1}from"../workflow/leadershipConversation/chiefCommunicationPlan";
import type{ChiefCommunicationRenderedB11V1}from"./chiefLeadershipCommunicationRenderer";
export type ChiefCommunicationFidelityResultB11V1={result:"PASS";sentenceCount:number;sentenceLineageCoverage:100;unsupportedStatements:0;confidenceMovements:0;inventedClaims:0;inventedQuestions:0;inventedRecommendations:0;repeatedClaims:0;repeatedQuestions:0;progressiveDisclosureDuplicates:0;candidateB2Behaviors:0;internalRoleLabels:0;genericAuditLabels:0;emptySections:0};
export function validateChiefLeadershipCommunicationFidelityB11V1(plan:ChiefCommunicationPlanB11V1,rendered:ChiefCommunicationRenderedB11V1):ChiefCommunicationFidelityResultB11V1{
  const approved=new Map(plan.items.map(item=>[item.itemId,item])),first=rendered.firstSurface.flatMap(section=>section.items),deeper=rendered.progressiveDisclosure.flatMap(section=>section.items),all=[...first,...deeper],seen=new Set<string>(),firstText=new Set(first.map(item=>normalizeChiefCommunication(item.text)));let repeatedClaims=0,repeatedQuestions=0,disclosure=0;
  for(const value of all){const item=approved.get(value.itemId);if(!item||item.semanticSourceId!==value.semanticSourceId||value.sourceRole!==item.role||!value.lineage.length||value.text!==item.renderedContent||!item.confidencePreserved)throw new Error("B1.1 sentence is not faithful to the accepted semantic item.");const normalized=normalizeChiefCommunication(value.text);if(seen.has(normalized))value.text.trim().endsWith("?")?repeatedQuestions++:repeatedClaims++;seen.add(normalized)}
  for(const value of deeper)if(firstText.has(normalizeChiefCommunication(value.text)))disclosure++;
  if(repeatedClaims||repeatedQuestions||disclosure||rendered.metrics.wordCount>120||rendered.metrics.sectionCount>4||rendered.metrics.topSectionSentenceCount>2||rendered.metrics.topSectionWordCount>50||rendered.metrics.maximumSentenceWords>32||rendered.metrics.internalRoleLabelCount||rendered.metrics.genericAuditLabelCount||rendered.metrics.emptySectionCount||rendered.metrics.ontologyTermCount||rendered.metrics.ambiguousTranslationCount)throw new Error("B1.1 communication fidelity invariant failed.");
  return{result:"PASS",sentenceCount:all.length,sentenceLineageCoverage:100,unsupportedStatements:0,confidenceMovements:0,inventedClaims:0,inventedQuestions:0,inventedRecommendations:0,repeatedClaims:0,repeatedQuestions:0,progressiveDisclosureDuplicates:0,candidateB2Behaviors:0,internalRoleLabels:0,genericAuditLabels:0,emptySections:0};
}
