import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { readFile } from "node:fs/promises";
import { DiscoveryStudio } from "../../../components/dev/discovery-studio/DiscoveryStudio";
import { listComparisons,listFrontierBenchmarkHardGateResults,listFrontierBenchmarkHardGateReviews,listLegacyRuns,listRuns,listScenarioValues,listTwoWayBlindReviews,loadScorecard } from "../../../lib/discovery-studio/scenarioStore";
import type { StudioScenarioV1,StudioScorecardV1 } from "../../../lib/discovery-studio/contracts";
import { listBlindReviews,listFrontierClaims,listFrontierRuns,openAIFrontierConfigurationStatus } from "../../../lib/discovery-studio/runOpenAIFrontierBaseline";
import { openDiscoveryQualityIterationReviewAction,openTwoWayBlindReviewAction,reconcileFrontierExecutionStateAction } from "./actions";

export const dynamic="force-dynamic";

export default async function DiscoveryStudioPage(){
 const host=(await headers()).get("host")??"";
 if(process.env.NODE_ENV==="production"||process.env.DISCOVERY_STUDIO_ENABLED!=="1"||!/^((127\.0\.0\.1)|(localhost))(\:\d+)?$/.test(host))notFound();
 await reconcileFrontierExecutionStateAction();
 const scenario=JSON.parse(await readFile("fixtures/discovery-studio/northstar-delivery-recovery-v1.json","utf8")) as StudioScenarioV1,runs=await listRuns(),entries=await Promise.all(runs.map(async run=>[run.runId,await loadScorecard(run)] as const)),scorecards=Object.fromEntries(entries.filter((entry):entry is readonly[string,StudioScorecardV1]=>entry[1]!==null)),twoWay=await listTwoWayBlindReviews(),hardGate=await listFrontierBenchmarkHardGateReviews(),blindReviews=await listBlindReviews(),order=["Northstar Evidence Sensitivity — Discovery vs Frontier","Northstar Temporal Update — Discovery vs Frontier","Northstar Staffing Contradiction — Discovery vs Frontier"],ordered=[...twoWay].sort((a,b)=>order.indexOf(a.reviewName)-order.indexOf(b.reviewName)),m1=blindReviews.find(review=>review.blindReviewId==="blind-c86d9b75ff699de5374a4a21"),evidence=ordered.find(review=>review.reviewName===order[0]),evidenceBlind=evidence?blindReviews.find(review=>review.blindReviewId===evidence.blindReviewId):undefined,temporal=hardGate.find(review=>review.order===2),staffing=hardGate.find(review=>review.order===3);
 if(!m1?.revealed||m1.labels.find(label=>label.label===m1.preferredLabel)?.runId!=="studio-874813b9-d079-4323-910a-f21312b05f94"||!evidenceBlind?.revealed||evidenceBlind.labels.find(label=>label.label===evidenceBlind.preferredLabel)?.runId!=="frontier-a019176d-f10c-4b95-bb72-de4742045654"||!temporal||!staffing)throw new Error("The complete four-case Founder Review result is unavailable.");
 let founderReview=null,founderReviewError:string|null=null;
 try{founderReview=evidence?await openTwoWayBlindReviewAction(evidence.twoWayReviewId):await openDiscoveryQualityIterationReviewAction()}catch(error){founderReviewError=error instanceof Error?error.message:"The persisted review is unavailable."}
 const caseReviews=[...ordered.map(review=>({kind:"blind" as const,id:review.twoWayReviewId,reviewName:review.reviewName,order:order.indexOf(review.reviewName)+1})),...hardGate.map(review=>({kind:"hard-gate" as const,id:review.reviewId,reviewName:review.reviewName,order:review.order}))].sort((a,b)=>a.order-b.order);
 return <DiscoveryStudio initialScenario={scenario} initialScenarioLibrary={await listScenarioValues()} initialRuns={runs} initialComparisons={await listComparisons()} initialLegacyRuns={await listLegacyRuns()} initialScorecards={scorecards} initialFrontierRuns={await listFrontierRuns()} initialFrontierClaims={await listFrontierClaims()} frontierConfigurationStatus={openAIFrontierConfigurationStatus()} initialFounderReview={founderReview} initialFounderReviewError={founderReviewError} initialTwoWayReviews={ordered.map(review=>({twoWayReviewId:review.twoWayReviewId,reviewName:review.reviewName}))} initialHardGateResults={await listFrontierBenchmarkHardGateResults()} initialHardGateReviews={hardGate} initialCaseReviews={caseReviews} initialGeneralizationSummary={[{caseName:"M1",discoveryHardGates:"PASS",frontierHardGates:"PASS",humanResult:"Discovery preferred",finalStatus:"Discovery human win"},{caseName:"Evidence removal",discoveryHardGates:"PASS",frontierHardGates:"PASS",humanResult:"Frontier preferred",finalStatus:"Frontier human win"},{caseName:"Temporal update",discoveryHardGates:"PASS",frontierHardGates:"FAIL",humanResult:"Not applicable",finalStatus:"Discovery hard-gate win"},{caseName:"Staffing contradiction",discoveryHardGates:"PASS",frontierHardGates:"FAIL",humanResult:"Not applicable",finalStatus:"Discovery hard-gate win"}]}/>;
}
