import { createHash } from "node:crypto";
import { ALPHA_PRODUCT_TELEMETRY_SCHEMA_VERSION, ALPHA_TELEMETRY_PURPOSE, alphaProgressiveDisclosureCategories, assertClosedFeedback, type AlphaFeedbackDimension, type AlphaFeedbackRating, type AlphaLifecycleTelemetry, type AlphaTelemetryRecord } from "./alphaProductTelemetryContracts";
import { assertAlphaContentSafeObservabilityEventV1, type AlphaContentSafeObservabilityEventV1 } from "../observability/alphaContentSafeObservabilityContracts";
import { deriveAlphaTelemetryPseudonym, signAlphaTelemetryValue, type AlphaTelemetryKeyRing } from "./alphaTelemetryPseudonymization";
import type { AlphaTelemetryRepository } from "./alphaTelemetryRepository";
import type { AlphaTelemetryConsentOwner } from "./alphaTelemetryConsentOwner";
const DAY=86_400_000,digest=(v:string)=>createHash("sha256").update(v).digest("hex");
export class AlphaProductTelemetryOwner{
 constructor(private consent:AlphaTelemetryConsentOwner,private repository:AlphaTelemetryRepository,private ring:AlphaTelemetryKeyRing,private now:()=>string){}
 async observe(organizationId:string,event:AlphaContentSafeObservabilityEventV1){try{assertAlphaContentSafeObservabilityEventV1(event);const{schemaVersion:_,sequence:__,correlation:___,...safe}=event;return await this.persist(organizationId,"lifecycle",{...safe,progressiveDisclosureCategory:"not-applicable"} satisfies AlphaLifecycleTelemetry);}catch{return"disabled" as const;}}
 async progressiveDisclosure(organizationId:string,category:Exclude<typeof alphaProgressiveDisclosureCategories[number],"not-applicable">){try{if(!alphaProgressiveDisclosureCategories.includes(category))return"disabled" as const;const payload:AlphaLifecycleTelemetry={eventCategory:"browser",workflowStage:"prepare",transitionCategory:"completed",outcomeCategory:"success",roleCategory:"not-applicable",occurrenceCategory:"occurrence-1",viewportCategory:"not-applicable",latencyBucket:"not-measured",replayRecoveryCategory:"none",failureCategory:"none",buildCategory:process.env.NODE_ENV==="production"?"production":process.env.NODE_ENV==="test"?"test":"development",protectedLoadCategory:"not-applicable",progressiveDisclosureCategory:category};return await this.persist(organizationId,"lifecycle",payload);}catch{return"disabled" as const;}}
 async feedback(organizationId:string,input:{dimension:AlphaFeedbackDimension;rating:AlphaFeedbackRating}){try{assertClosedFeedback(input);return await this.persist(organizationId,"feedback",input);}catch{return"disabled" as const;}}
 private async persist(organizationId:string,kind:"lifecycle"|"feedback",payload:unknown){const consent=await this.consent.current(organizationId);if(!consent)return"disabled" as const;const eventTime=this.now(),organizationPseudonym=deriveAlphaTelemetryPseudonym(this.ring,"organization",organizationId),authorizedOrganizationPseudonyms=Object.keys(this.ring.keys).map(version=>deriveAlphaTelemetryPseudonym(this.ring,"organization",organizationId,version)),keyVersion=this.ring.activeVersion,content=JSON.stringify({kind,payload,eventTime,organizationPseudonym,keyVersion}),base={schemaVersion:ALPHA_PRODUCT_TELEMETRY_SCHEMA_VERSION,recordId:`record_${digest(content)}`,organizationPseudonym,organizationPseudonyms:authorizedOrganizationPseudonyms,keyVersion,purpose:ALPHA_TELEMETRY_PURPOSE,kind,eventTime,expiresAt:new Date(Date.parse(eventTime)+90*DAY).toISOString(),...(kind==="lifecycle"?{lifecycle:payload as AlphaLifecycleTelemetry}:{feedback:payload as {dimension:AlphaFeedbackDimension;rating:AlphaFeedbackRating}})};const record={...base,integrityMac:signAlphaTelemetryValue(this.ring,keyVersion,JSON.stringify(base))} as AlphaTelemetryRecord;try{await this.repository.append(record,eventTime,consent.receiptId,authorizedOrganizationPseudonyms);return"persisted" as const;}catch{return"repository-unavailable" as const;}}
}
