import path from "node:path";
import postgres, { type Sql } from "postgres";
import { requireDiscoveryDatabaseUrl } from "../../db/config";
import { AlphaTelemetryConsentOwner } from "./alphaTelemetryConsentOwner";
import { AlphaTelemetryOperatorAccess } from "./alphaTelemetryOperatorAccess";
import { AlphaProductTelemetryOwner } from "./alphaProductTelemetryOwner";
import { type AlphaTelemetryKeyRing } from "./alphaTelemetryPseudonymization";
import { FilesystemAlphaTelemetryRepository, PostgresAlphaTelemetryRepository, type AlphaTelemetryRepository } from "./alphaTelemetryRepository";
function ringFromEnvironment():AlphaTelemetryKeyRing|null{const version=process.env.DISCOVERY_ALPHA_TELEMETRY_ACTIVE_KEY_VERSION,encoded=process.env.DISCOVERY_ALPHA_TELEMETRY_KEY_RING_JSON,environment=process.env.DISCOVERY_ENV??process.env.NODE_ENV??"development";if(!version||!encoded)return null;try{const keys=JSON.parse(encoded) as Record<string,string>;return{environment,activeVersion:version,keys};}catch{return null;}}
export function createAlphaTelemetryComposition(input?:{root?:string;ring?:AlphaTelemetryKeyRing;now?:()=>string;startupMaintenance?:"global"|"none";repository?:AlphaTelemetryRepository}){const ring=input?.ring??ringFromEnvironment();if(!ring)return null;const configuredRoot=input?.root??process.env.DISCOVERY_ALPHA_TELEMETRY_ROOT,hosted=process.env.DISCOVERY_CHIEF_COMPOSITION==="production";if(process.env.NODE_ENV==="production"&&!input?.repository&&!hosted&&!input?.root)return null;const now=input?.now??(()=>new Date().toISOString()),repository=input?.repository??(hosted?new PostgresAlphaTelemetryRepository(postgres(requireDiscoveryDatabaseUrl("application"),{max:1})):new FilesystemAlphaTelemetryRepository(configuredRoot??path.join(process.cwd(),".discovery-runtime","alpha-telemetry"))),consent=new AlphaTelemetryConsentOwner(repository,ring,now),operators=new AlphaTelemetryOperatorAccess(repository,ring,now,consent),telemetry=new AlphaProductTelemetryOwner(consent,repository,ring,now),ready=input?.startupMaintenance==="none"?Promise.resolve():(async()=>{await consent.expireCompliance();await operators.expireCompliance();await repository.sweep(now());})();return{ring,repository,consent,operators,telemetry,now,ready};}

export function createHostedAlphaTelemetryComposition(input:{sql:Sql<Record<string,unknown>>;ring?:AlphaTelemetryKeyRing;now?:()=>string}){return createAlphaTelemetryComposition({repository:new PostgresAlphaTelemetryRepository(input.sql),ring:input.ring,now:input.now,startupMaintenance:"none"});}
