import { createHash,createHmac,randomBytes } from "node:crypto";
import { constants } from "node:fs";
import { link,lstat,mkdir,open,readFile,rename,unlink } from "node:fs/promises";
import path from "node:path";

export const resourceKinds=["user","session","membership","organization","server","browser-profile","browser-binary","task-root","protected-file"] as const;
export type AcceptanceResourceKind=typeof resourceKinds[number];
export type PlannedResource={kind:AcceptanceResourceKind;ordinal:number};
export type AcceptanceTaskManifest={schemaVersion:"1";environment:"development";sourceDigest:string;taskDigest:string;ownershipMarker:string;resources:readonly PlannedResource[];organizationPlan:"enabled"|"not-applicable-capability-disabled";integrityMac:string};
export type CleanupProgress={schemaVersion:"1";taskDigest:string;attempt:number;remainingDigests:readonly string[];completedDigests:readonly string[];predecessorMac:string|null;integrityMac:string};
export type ClerkIdentityInventoryReceipt={schemaVersion:"1";taskDigest:string;ownershipMarker:string;userIds:readonly string[];sessionIds:readonly string[];integrityMac:string};
export const acceptanceResourceLifecycleStates=["not-dispatched","dispatch-started","acknowledged","acknowledgement-lost","rediscovered","never-created","cleanup-attempted","removed","zero-verified","cleanup-blocked"] as const;
export type AcceptanceResourceLifecycleState=typeof acceptanceResourceLifecycleStates[number];
export type PartialResourceInventory={kind:"user"|"session"|"membership"|"organization";plannedMaximum:number;identityRefs:readonly string[];dispatchState:AcceptanceResourceLifecycleState;acknowledgedCount:number;acknowledgementLostCount:number;rediscoveredCount:number;cleanupAttemptedCount:number;removedCount:number;zeroVerifiedCount:number;cleanupBlockedCount:number;absenceVerified:boolean};
export type PartialClerkIdentityInventoryReceipt={schemaVersion:"2";taskDigest:string;ownershipMarker:string;taskManifestDigest:string;resourcePlanDigest:string;resources:readonly PartialResourceInventory[];integrityMac:string};
export type AnyClerkIdentityInventoryReceipt=ClerkIdentityInventoryReceipt|PartialClerkIdentityInventoryReceipt;
const exact=(v:Record<string,unknown>,keys:string[])=>{if(Object.keys(v).sort().join("\0")!==keys.sort().join("\0"))throw new Error("Acceptance ownership schema is invalid");};
const digest=(v:string)=>createHash("sha256").update(v).digest("hex");
const mac=(secret:Buffer,value:unknown)=>createHmac("sha256",secret).update(JSON.stringify(value)).digest("hex");
export const acceptanceTaskManifestDigest=(manifest:AcceptanceTaskManifest)=>digest(JSON.stringify(manifest));
export const acceptanceResourcePlanDigest=(manifest:AcceptanceTaskManifest)=>digest(JSON.stringify(manifest.resources));
export const createTaskSecret=()=>randomBytes(32);
export function createAcceptanceTaskManifest(input:{sourceDigest:string;secret:Buffer;organizationPlan:AcceptanceTaskManifest["organizationPlan"]}):AcceptanceTaskManifest{
 if(!/^[a-f0-9]{64}$/.test(input.sourceDigest)||input.secret.length!==32)throw new Error("Acceptance ownership input is invalid");
 const resources:PlannedResource[]=[...(["user","user","user","user","session","session","session","session","session","session","server","browser-profile","browser-profile","browser-profile","browser-profile","browser-profile","browser-profile","browser-binary","task-root","protected-file"] as AcceptanceResourceKind[])].map((kind,ordinal)=>({kind,ordinal}));
 const taskDigest=digest(`ar2-pre-001b\0${input.sourceDigest}\0${randomBytes(32).toString("hex")}`),ownershipMarker=digest(`ownership\0${taskDigest}`),unsigned={schemaVersion:"1" as const,environment:"development" as const,sourceDigest:input.sourceDigest,taskDigest,ownershipMarker,resources,organizationPlan:input.organizationPlan};
 return{...unsigned,integrityMac:mac(input.secret,unsigned)};
}
export function assertAcceptanceTaskManifest(value:unknown,secret:Buffer):asserts value is AcceptanceTaskManifest{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Acceptance ownership schema is invalid");const r=value as Record<string,unknown>;exact(r,["schemaVersion","environment","sourceDigest","taskDigest","ownershipMarker","resources","organizationPlan","integrityMac"]);const{integrityMac,...unsigned}=r;if(r.schemaVersion!=="1"||r.environment!=="development"||!Array.isArray(r.resources)||!r.resources.length||!/^[a-f0-9]{64}$/.test(String(r.sourceDigest))||!/^[a-f0-9]{64}$/.test(String(r.taskDigest))||!/^[a-f0-9]{64}$/.test(String(r.ownershipMarker))||!['enabled','not-applicable-capability-disabled'].includes(String(r.organizationPlan))||!/^[a-f0-9]{64}$/.test(String(integrityMac))||integrityMac!==mac(secret,unsigned))throw new Error("Acceptance ownership integrity is invalid");const seen=new Set<string>();for(const item of r.resources){if(!item||typeof item!=="object"||Array.isArray(item))throw new Error("Acceptance resource plan is invalid");const p=item as Record<string,unknown>;exact(p,["kind","ordinal"]);if(!resourceKinds.includes(p.kind as AcceptanceResourceKind)||!Number.isSafeInteger(p.ordinal)||Number(p.ordinal)<0||seen.has(`${p.kind}:${p.ordinal}`))throw new Error("Acceptance resource plan is invalid");seen.add(`${p.kind}:${p.ordinal}`);}}
export async function writeProtectedManifest(file:string,value:AcceptanceTaskManifest){await mkdir(path.dirname(file),{recursive:true,mode:0o700});const candidate=`${file}.${randomBytes(8).toString("hex")}.candidate`,handle=await open(candidate,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY|constants.O_NOFOLLOW,0o600);try{await handle.writeFile(`${JSON.stringify(value)}\n`);await handle.sync();}finally{await handle.close();}await link(candidate,file);await unlink(candidate);const directory=await open(path.dirname(file),"r");try{await directory.sync();}finally{await directory.close();}}
export async function readProtectedManifest(file:string,secret:Buffer){const handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{const stat=await handle.stat();if(!stat.isFile()||(stat.mode&0o777)!==0o600)throw new Error("Acceptance manifest protection is invalid");const value=JSON.parse(await handle.readFile("utf8"));assertAcceptanceTaskManifest(value,secret);return value;}finally{await handle.close();}}
export function createClerkIdentityInventoryReceipt(input:{manifest:AcceptanceTaskManifest;secret:Buffer;userIds:string[];sessionIds:string[]}):ClerkIdentityInventoryReceipt{const unsigned={schemaVersion:"1" as const,taskDigest:input.manifest.taskDigest,ownershipMarker:input.manifest.ownershipMarker,userIds:[...input.userIds].sort(),sessionIds:[...input.sessionIds].sort()};return{...unsigned,integrityMac:mac(input.secret,unsigned)};}
export function assertClerkIdentityInventoryReceipt(value:unknown,manifest:AcceptanceTaskManifest,secret:Buffer):asserts value is ClerkIdentityInventoryReceipt{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Acceptance identity inventory is invalid");const r=value as Record<string,unknown>;exact(r,["schemaVersion","taskDigest","ownershipMarker","userIds","sessionIds","integrityMac"]);const{integrityMac,...unsigned}=r;if(r.schemaVersion!=="1"||r.taskDigest!==manifest.taskDigest||r.ownershipMarker!==manifest.ownershipMarker||!Array.isArray(r.userIds)||!Array.isArray(r.sessionIds)||new Set(r.userIds).size!==r.userIds.length||new Set(r.sessionIds).size!==r.sessionIds.length||r.userIds.length!==4||r.sessionIds.length!==6||integrityMac!==mac(secret,unsigned))throw new Error("Acceptance identity inventory is invalid");}
const partialKinds=["user","session","membership","organization"] as const;
function plannedMaximum(manifest:AcceptanceTaskManifest,kind:PartialResourceInventory["kind"]){return manifest.resources.filter(value=>value.kind===kind).length;}
export function createPartialClerkIdentityInventoryReceipt(input:{manifest:AcceptanceTaskManifest;secret:Buffer;resources:readonly PartialResourceInventory[]}):PartialClerkIdentityInventoryReceipt{const unsigned={schemaVersion:"2" as const,taskDigest:input.manifest.taskDigest,ownershipMarker:input.manifest.ownershipMarker,taskManifestDigest:acceptanceTaskManifestDigest(input.manifest),resourcePlanDigest:acceptanceResourcePlanDigest(input.manifest),resources:input.resources.map(value=>({...value,identityRefs:[...value.identityRefs].sort()}))};const value={...unsigned,integrityMac:mac(input.secret,unsigned)};assertPartialClerkIdentityInventoryReceipt(value,input.manifest,input.secret);return value;}
export function assertPartialClerkIdentityInventoryReceipt(value:unknown,manifest:AcceptanceTaskManifest,secret:Buffer):asserts value is PartialClerkIdentityInventoryReceipt{
 if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Acceptance partial identity inventory is invalid");
 const r=value as Record<string,unknown>;exact(r,["schemaVersion","taskDigest","ownershipMarker","taskManifestDigest","resourcePlanDigest","resources","integrityMac"]);const{integrityMac,...unsigned}=r;
 if(r.schemaVersion!=="2"||r.taskDigest!==manifest.taskDigest||r.ownershipMarker!==manifest.ownershipMarker||r.taskManifestDigest!==acceptanceTaskManifestDigest(manifest)||r.resourcePlanDigest!==acceptanceResourcePlanDigest(manifest)||!Array.isArray(r.resources)||r.resources.length!==partialKinds.length||integrityMac!==mac(secret,unsigned))throw new Error("Acceptance partial identity inventory is invalid");
 const seen=new Set<string>();
 for(const item of r.resources){
  if(!item||typeof item!=="object"||Array.isArray(item))throw new Error("Acceptance partial identity inventory is invalid");const p=item as Record<string,unknown>;exact(p,["kind","plannedMaximum","identityRefs","dispatchState","acknowledgedCount","acknowledgementLostCount","rediscoveredCount","cleanupAttemptedCount","removedCount","zeroVerifiedCount","cleanupBlockedCount","absenceVerified"]);
  if(!partialKinds.includes(p.kind as typeof partialKinds[number])||seen.has(String(p.kind))||!acceptanceResourceLifecycleStates.includes(p.dispatchState as AcceptanceResourceLifecycleState)||typeof p.absenceVerified!=="boolean"||!Array.isArray(p.identityRefs)||new Set(p.identityRefs).size!==p.identityRefs.length||p.identityRefs.some(value=>typeof value!=="string"||!value))throw new Error("Acceptance partial identity inventory is invalid");seen.add(String(p.kind));
  const maximum=plannedMaximum(manifest,p.kind as PartialResourceInventory["kind"]),counts=[p.plannedMaximum,p.acknowledgedCount,p.acknowledgementLostCount,p.rediscoveredCount,p.cleanupAttemptedCount,p.removedCount,p.zeroVerifiedCount,p.cleanupBlockedCount];
  if(counts.some(value=>!Number.isSafeInteger(value)||Number(value)<0)||p.plannedMaximum!==maximum||p.identityRefs.length>maximum||counts.slice(1).some(value=>Number(value)>maximum))throw new Error("Acceptance partial identity inventory is invalid");
  const actual=p.identityRefs.length,state=p.dispatchState as AcceptanceResourceLifecycleState;
  if((state==="not-dispatched"||state==="never-created")&&(actual!==0||Number(p.acknowledgedCount)+Number(p.acknowledgementLostCount)+Number(p.rediscoveredCount)+Number(p.cleanupAttemptedCount)+Number(p.removedCount)+Number(p.zeroVerifiedCount)+Number(p.cleanupBlockedCount)!==0))throw new Error("Acceptance partial identity inventory is invalid");
  const acknowledged=Number(p.acknowledgedCount),rediscovered=Number(p.rediscoveredCount),attempted=Number(p.cleanupAttemptedCount),removed=Number(p.removedCount),zero=Number(p.zeroVerifiedCount),blocked=Number(p.cleanupBlockedCount),provenance=acknowledged+rediscovered;
  const lost=Number(p.acknowledgementLostCount);
  if(state==="dispatch-started"&&(actual!==0||acknowledged!==0||rediscovered!==0||lost!==0||attempted!==0||removed!==0||zero!==0||blocked!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="acknowledgement-lost"&&(actual!==0||acknowledged!==0||rediscovered!==0||lost===0||attempted!==0||removed!==0||zero!==0||blocked!==lost))throw new Error("Acceptance partial identity inventory is invalid");
  if((state==="acknowledged"||state==="rediscovered")&&(provenance!==actual||attempted!==0||removed!==0||zero!==0||blocked!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="acknowledged"&&(actual===0||rediscovered!==0||lost!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="rediscovered"&&(rediscovered===0||lost!==rediscovered))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="cleanup-blocked"&&(provenance!==actual||lost!==rediscovered||attempted!==actual||removed+blocked!==actual||zero!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="cleanup-attempted"&&(actual===0||provenance!==actual||lost!==rediscovered||attempted!==actual||removed!==0||blocked!==actual||zero!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="removed"&&(provenance!==actual||lost!==rediscovered||attempted!==actual||removed!==actual||zero!==0||blocked!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state==="zero-verified"&&(!p.absenceVerified||provenance!==actual||lost!==rediscovered||attempted!==actual||removed!==actual||zero!==actual||blocked!==0))throw new Error("Acceptance partial identity inventory is invalid");
  if(state!=="zero-verified"&&p.absenceVerified)throw new Error("Acceptance partial identity inventory is invalid");
  if(provenance>actual)throw new Error("Acceptance partial identity inventory is invalid");
 }
 if(seen.size!==partialKinds.length)throw new Error("Acceptance partial identity inventory is invalid");
}
export async function writeClerkIdentityInventoryReceipt(file:string,value:AnyClerkIdentityInventoryReceipt){await writeCleanupProgress(file,value as unknown as CleanupProgress);}
export async function readClerkIdentityInventoryReceipt(file:string,manifest:AcceptanceTaskManifest,secret:Buffer):Promise<AnyClerkIdentityInventoryReceipt>{const handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{const stat=await handle.stat();if(!stat.isFile()||(stat.mode&0o777)!==0o600)throw new Error("Acceptance identity inventory protection is invalid");const value=JSON.parse(await handle.readFile("utf8"));if(value?.schemaVersion==="1")assertClerkIdentityInventoryReceipt(value,manifest,secret);else assertPartialClerkIdentityInventoryReceipt(value,manifest,secret);return value;}finally{await handle.close();}}
export function createCleanupProgress(input:{manifest:AcceptanceTaskManifest;secret:Buffer;attempt:number;remainingDigests:string[];completedDigests:string[];predecessorMac:string|null}):CleanupProgress{const unsigned={schemaVersion:"1" as const,taskDigest:input.manifest.taskDigest,attempt:input.attempt,remainingDigests:[...input.remainingDigests].sort(),completedDigests:[...input.completedDigests].sort(),predecessorMac:input.predecessorMac};return{...unsigned,integrityMac:mac(input.secret,unsigned)};}
export async function writeCleanupProgress(file:string,value:CleanupProgress){const candidate=`${file}.${randomBytes(8).toString("hex")}.candidate`;await mkdir(path.dirname(file),{recursive:true,mode:0o700});const h=await open(candidate,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY|constants.O_NOFOLLOW,0o600);try{await h.writeFile(`${JSON.stringify(value)}\n`);await h.sync();}finally{await h.close();}await rename(candidate,file);const d=await open(path.dirname(file),"r");try{await d.sync();}finally{await d.close();}}
export const resourceDigest=(manifest:AcceptanceTaskManifest,kind:AcceptanceResourceKind,opaqueRef:string)=>digest(`${manifest.taskDigest}\0${kind}\0${opaqueRef}`);
