import { chromium,type Browser,type BrowserContext,type Page } from "@playwright/test";
import { clerk,clerkSetup } from "@clerk/testing/playwright";
import { access,mkdir,rm } from "node:fs/promises";
import path from "node:path";

export type AcceptanceBrowser={browser:Browser;context:BrowserContext;page:Page;profileRoot:string;consoleErrors:string[];pageErrors:string[]};
const exactTemporaryRoot=(root:string,prefix:string)=>path.isAbsolute(root)&&path.dirname(root)==="/private/tmp"&&path.basename(root).startsWith(prefix)&&!path.basename(root).includes("..")&&path.basename(root).length>prefix.length+5;
export async function prepareClerkTesting(){await clerkSetup({dotenv:false});}
export async function openAcceptanceBrowser(input:{profileRoot:string;viewport:{width:number;height:number}}):Promise<AcceptanceBrowser>{if(!exactTemporaryRoot(input.profileRoot,"discovery-ar2-pre-001b-profile-"))throw new Error("Acceptance browser root is invalid");await prepareClerkTesting();await mkdir(input.profileRoot,{recursive:false,mode:0o700});const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:input.viewport,acceptDownloads:false}),page=await context.newPage(),value={browser,context,page,profileRoot:input.profileRoot,consoleErrors:[] as string[],pageErrors:[] as string[]};page.on("console",message=>{if(message.type()!=="error")return;const content=message.text();if(content.startsWith("Failed to load resource: the server responded with a status of 404"))return;value.consoleErrors.push(content.includes("Hydration")?"hydration":content.startsWith("Failed to load resource:")?"resource":content.startsWith("Clerk")?"clerk":"generic");});page.on("pageerror",()=>value.pageErrors.push("pageerror"));return value;}
export async function signInAcceptanceRole(browser:AcceptanceBrowser,input:{email:string;userId:string;baseUrl:string}){if(!/^http:\/\/localhost:\d{4,5}$/.test(input.baseUrl))throw new Error("Acceptance browser URL is invalid");await browser.page.goto(`${input.baseUrl}/alpha-access`,{waitUntil:"domcontentloaded"});await clerk.signOut({page:browser.page}).catch(()=>{});await clerk.signIn({page:browser.page,emailAddress:input.email});const active=await browser.page.evaluate(()=>window.Clerk?.user?.id??null);if(active!==input.userId)throw new Error("Acceptance browser identity is unavailable");}
export async function closeAcceptanceBrowser(value:AcceptanceBrowser){if(!exactTemporaryRoot(value.profileRoot,"discovery-ar2-pre-001b-profile-"))throw new Error("Acceptance browser cleanup target is invalid");await clerk.signOut({page:value.page}).catch(()=>{});await value.context.close();await value.browser.close();await rm(value.profileRoot,{recursive:true,force:true});if(await access(value.profileRoot).then(()=>true,()=>false))throw new Error("Acceptance browser profile remains");}
export async function removeAcceptanceBrowserProfileRoots(roots:string[]){for(const root of roots){if(!exactTemporaryRoot(root,"discovery-ar2-pre-001b-profile-"))throw new Error("Acceptance browser cleanup target is invalid");await rm(root,{recursive:true,force:true});if(await access(root).then(()=>true,()=>false))throw new Error("Acceptance browser profile remains");}}
export async function removeBrowserBinaryRoot(root:string){if(!exactTemporaryRoot(root,"discovery-ar2-pre-001b-browser-"))throw new Error("Acceptance browser binary root is not task-owned");await rm(root,{recursive:true,force:true});if(await access(root).then(()=>true,()=>false))throw new Error("Acceptance browser binary remains");}
