import { createHash } from "node:crypto";

export const ACCEPTANCE_FRAMEWORK_ID="authenticated-alpha-acceptance" as const;
export const ACCEPTANCE_FRAMEWORK_VERSION="1" as const;
export const producerCategories=["browser","replay-recovery","observability","lifecycle","scanner","cleanup","independent-zero"] as const;
export const phaseCategories=["browser-journey","replay-recovery","event-observation","resource-lifecycle","surface-scan","cleanup-attempts","zero-verification"] as const;
export const observationStates=["observed","not-observed","match","mismatch","executed","failed","unavailable","malformed"] as const;
export type ProducerCategory=typeof producerCategories[number];
export type PhaseCategory=typeof phaseCategories[number];
export type ObservationState=typeof observationStates[number];
export type FrameworkIdentity={id:typeof ACCEPTANCE_FRAMEWORK_ID;version:typeof ACCEPTANCE_FRAMEWORK_VERSION};
export type ProfileIdentity={id:string;version:string};
export type RequiredMeasurement={producer:ProducerCategory;phase:PhaseCategory;multiplicity:"exactly-one";factIds:readonly string[]};
export type OrderingConstraint={beforeFactId:string;afterFactId:string};
export type AcceptanceProfileRequirementsV1={schemaVersion:"1";kind:"acceptance-profile-requirements";framework:FrameworkIdentity;profile:ProfileIdentity;requiredMeasurements:readonly RequiredMeasurement[];orderingConstraints:readonly OrderingConstraint[];identityBindings:readonly ["framework","profile","source","task"]};
export type ObservedFact={factId:string;state:ObservationState};
export type AcceptanceMeasurementEnvelopeV1={schemaVersion:"1";kind:"acceptance-measurement";framework:FrameworkIdentity;profile:ProfileIdentity;producer:ProducerCategory;phase:PhaseCategory;sourceDigest:string;taskDigest:string;measurementId:string;producerRunDigest:string;sequence:number;observations:readonly ObservedFact[];measurementDigest:string};

const exactKeys=(value:Record<string,unknown>,expected:readonly string[],category:string)=>{if(Object.keys(value).sort().join("\0")!==[...expected].sort().join("\0"))throw new Error(`${category} schema is invalid`);};
const object=(value:unknown,category:string):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error(`${category} schema is invalid`);return value as Record<string,unknown>;};
const safeIdentity=(value:unknown,category:string)=>{if(typeof value!=="string"||!/^[a-z][a-z0-9-]{2,95}$/.test(value))throw new Error(`${category} identity is invalid`);return value;};
const digestValue=(value:unknown,category:string)=>{if(typeof value!=="string"||!/^[a-f0-9]{64}$/.test(value))throw new Error(`${category} digest is invalid`);return value;};
const factId=(value:unknown)=>{if(typeof value!=="string"||!/^[a-z][a-z0-9-]{2,95}$/.test(value))throw new Error("Fact identity is invalid");return value;};
const prohibitedString=/(?:https?:\/\/|\/Users\/|\/private\/|[A-Za-z]:\\|sk_(?:test|live)_|pk_(?:test|live)_|bearer\s|cookie|token|password|selector|script|command)/i;

export function canonicalAcceptanceSerialize(value:unknown):string{
  const visit=(item:unknown):string=>{if(item===null)return"null";if(typeof item==="string"){if(prohibitedString.test(item))throw new Error("Canonical value contains a prohibited string");return JSON.stringify(item);}if(typeof item==="boolean")return item?"true":"false";if(typeof item==="number"){if(!Number.isFinite(item))throw new Error("Canonical number is invalid");return JSON.stringify(item);}if(Array.isArray(item))return`[${item.map(visit).join(",")}]`;if(typeof item==="object"){if(Object.getPrototypeOf(item)!==Object.prototype)throw new Error("Canonical object is invalid");const record=item as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>{if(record[key]===undefined)throw new Error("Canonical value is undefined");return`${JSON.stringify(key)}:${visit(record[key])}`;}).join(",")}}`;}throw new Error("Canonical value type is unsupported");};return visit(value);
}
export const acceptanceDigest=(value:unknown)=>createHash("sha256").update(canonicalAcceptanceSerialize(value)).digest("hex");

function framework(value:unknown):FrameworkIdentity{const record=object(value,"Framework");exactKeys(record,["id","version"],"Framework");if(record.id!==ACCEPTANCE_FRAMEWORK_ID||record.version!==ACCEPTANCE_FRAMEWORK_VERSION)throw new Error("Framework identity is invalid");return record as FrameworkIdentity;}
function profileIdentity(value:unknown):ProfileIdentity{const record=object(value,"Profile");exactKeys(record,["id","version"],"Profile");return{id:safeIdentity(record.id,"Profile"),version:safeIdentity(record.version,"Profile version")};}

export function assertAcceptanceProfileRequirementsV1(value:unknown):asserts value is AcceptanceProfileRequirementsV1{
 const record=object(value,"Profile");exactKeys(record,["schemaVersion","kind","framework","profile","requiredMeasurements","orderingConstraints","identityBindings"],"Profile");if(record.schemaVersion!=="1"||record.kind!=="acceptance-profile-requirements")throw new Error("Profile version is invalid");framework(record.framework);profileIdentity(record.profile);if(!Array.isArray(record.requiredMeasurements)||record.requiredMeasurements.length===0)throw new Error("Profile measurement inventory is invalid");const measurementKeys=new Set<string>(),facts=new Set<string>();for(const item of record.requiredMeasurements){const requirement=object(item,"Profile measurement");exactKeys(requirement,["producer","phase","multiplicity","factIds"],"Profile measurement");if(!producerCategories.includes(requirement.producer as ProducerCategory)||!phaseCategories.includes(requirement.phase as PhaseCategory)||requirement.multiplicity!=="exactly-one"||!Array.isArray(requirement.factIds)||requirement.factIds.length===0)throw new Error("Profile measurement is invalid");const key=`${requirement.producer}:${requirement.phase}`;if(measurementKeys.has(key))throw new Error("Profile measurement is duplicated");measurementKeys.add(key);const local=new Set<string>();for(const itemFact of requirement.factIds){const id=factId(itemFact);if(local.has(id)||facts.has(id))throw new Error("Profile fact is duplicated");local.add(id);facts.add(id);}}
 if(!Array.isArray(record.orderingConstraints))throw new Error("Profile ordering is invalid");for(const item of record.orderingConstraints){const constraint=object(item,"Ordering constraint");exactKeys(constraint,["beforeFactId","afterFactId"],"Ordering constraint");const before=factId(constraint.beforeFactId),after=factId(constraint.afterFactId);if(before===after||!facts.has(before)||!facts.has(after))throw new Error("Ordering constraint is invalid");}
 if(!Array.isArray(record.identityBindings)||record.identityBindings.join("\0")!=="framework\0profile\0source\0task")throw new Error("Profile identity binding is invalid");canonicalAcceptanceSerialize(record);
}

export function createAcceptanceMeasurementEnvelopeV1(input:Omit<AcceptanceMeasurementEnvelopeV1,"schemaVersion"|"kind"|"measurementDigest">):AcceptanceMeasurementEnvelopeV1{const unsigned={schemaVersion:"1" as const,kind:"acceptance-measurement" as const,...input},measurementDigest=acceptanceDigest(unsigned),value={...unsigned,measurementDigest};assertAcceptanceMeasurementEnvelopeV1(value);return value;}
export function assertAcceptanceMeasurementEnvelopeV1(value:unknown):asserts value is AcceptanceMeasurementEnvelopeV1{
 const record=object(value,"Measurement");exactKeys(record,["schemaVersion","kind","framework","profile","producer","phase","sourceDigest","taskDigest","measurementId","producerRunDigest","sequence","observations","measurementDigest"],"Measurement");if(record.schemaVersion!=="1"||record.kind!=="acceptance-measurement")throw new Error("Measurement version is invalid");framework(record.framework);profileIdentity(record.profile);if(!producerCategories.includes(record.producer as ProducerCategory)||!phaseCategories.includes(record.phase as PhaseCategory))throw new Error("Measurement owner is invalid");digestValue(record.sourceDigest,"Source");digestValue(record.taskDigest,"Task");digestValue(record.measurementId,"Measurement");digestValue(record.producerRunDigest,"Producer run");if(!Number.isSafeInteger(record.sequence)||Number(record.sequence)<1)throw new Error("Measurement sequence is invalid");if(!Array.isArray(record.observations)||record.observations.length===0)throw new Error("Measurement observations are invalid");const facts=new Set<string>();for(const item of record.observations){const observation=object(item,"Observation");exactKeys(observation,["factId","state"],"Observation");const id=factId(observation.factId);if(facts.has(id)||!observationStates.includes(observation.state as ObservationState))throw new Error("Observation is invalid");facts.add(id);}digestValue(record.measurementDigest,"Measurement");const{measurementDigest,...unsigned}=record;if(measurementDigest!==acceptanceDigest(unsigned))throw new Error("Measurement digest is invalid");canonicalAcceptanceSerialize(record);
}
