import { ACCEPTANCE_FRAMEWORK_ID, ACCEPTANCE_FRAMEWORK_VERSION, acceptanceDigest, assertAcceptanceMeasurementEnvelopeV1, assertAcceptanceProfileRequirementsV1, type AcceptanceMeasurementEnvelopeV1, type AcceptanceProfileRequirementsV1, type ObservationState } from "./authenticatedAlphaAcceptanceContracts";

export const adjudicationResults=["PASS","FAIL","BLOCKED"] as const;
export type AcceptanceAdjudicationResultV1={schemaVersion:"1";framework:{id:typeof ACCEPTANCE_FRAMEWORK_ID;version:typeof ACCEPTANCE_FRAMEWORK_VERSION};profileId:string;sourceDigest:string;taskDigest:string;result:typeof adjudicationResults[number];reasonCategories:readonly string[];inventory:{requiredMeasurements:number;observedMeasurements:number;requiredFacts:number;observedFacts:number;failedFacts:number;blockedFacts:number};adjudicationDigest:string};
const digestPattern=/^[a-f0-9]{64}$/;
const satisfied=new Set<ObservationState>(["observed","match","executed"]),failed=new Set<ObservationState>(["not-observed","mismatch","failed"]),blocked=new Set<ObservationState>(["unavailable","malformed"]);
const result=(input:Omit<AcceptanceAdjudicationResultV1,"schemaVersion"|"framework"|"adjudicationDigest">):AcceptanceAdjudicationResultV1=>{const unsigned={schemaVersion:"1" as const,framework:{id:ACCEPTANCE_FRAMEWORK_ID,version:ACCEPTANCE_FRAMEWORK_VERSION},...input};return{...unsigned,adjudicationDigest:acceptanceDigest(unsigned)};};

export function adjudicateAuthenticatedAlphaAcceptance(input:{profile:unknown;measurements:readonly unknown[];sourceDigest:string;taskDigest:string}):AcceptanceAdjudicationResultV1{
 let profile:AcceptanceProfileRequirementsV1|undefined;const reasons=new Set<string>();if(!digestPattern.test(input.sourceDigest))reasons.add("source-identity-invalid");if(!digestPattern.test(input.taskDigest))reasons.add("task-identity-invalid");try{assertAcceptanceProfileRequirementsV1(input.profile);profile=input.profile;}catch{reasons.add("profile-invalid");}
 const safeProfileId=profile?.profile.id??"invalid-profile",requiredMeasurements=profile?.requiredMeasurements.length??0,requiredFacts=profile?.requiredMeasurements.reduce((sum,value)=>sum+value.factIds.length,0)??0,envelopes:AcceptanceMeasurementEnvelopeV1[]=[];
 for(const candidate of input.measurements){try{assertAcceptanceMeasurementEnvelopeV1(candidate);envelopes.push(candidate);}catch{reasons.add("measurement-invalid");}}
 if(!profile)return result({profileId:safeProfileId,sourceDigest:input.sourceDigest,taskDigest:input.taskDigest,result:"BLOCKED",reasonCategories:[...reasons].sort(),inventory:{requiredMeasurements,observedMeasurements:envelopes.length,requiredFacts,observedFacts:envelopes.reduce((sum,value)=>sum+value.observations.length,0),failedFacts:0,blockedFacts:0}});
 const measurementIds=new Set<string>(),ownerKeys=new Set<string>(),requiredByOwner=new Map(profile.requiredMeasurements.map(value=>[`${value.producer}:${value.phase}`,value])),observedFacts=new Map<string,{state:ObservationState;sequence:number;owner:string}>();let failedFacts=0,blockedFacts=0;
 for(const envelope of envelopes){if(envelope.framework.id!==profile.framework.id||envelope.framework.version!==profile.framework.version)reasons.add("framework-mismatch");if(envelope.profile.id!==profile.profile.id||envelope.profile.version!==profile.profile.version)reasons.add("profile-mismatch");if(envelope.sourceDigest!==input.sourceDigest)reasons.add("source-mismatch");if(envelope.taskDigest!==input.taskDigest)reasons.add("task-mismatch");if(measurementIds.has(envelope.measurementId))reasons.add("duplicate-measurement-identity");measurementIds.add(envelope.measurementId);const owner=`${envelope.producer}:${envelope.phase}`;if(ownerKeys.has(owner))reasons.add("duplicate-producer-phase");ownerKeys.add(owner);const requirement=requiredByOwner.get(owner);if(!requirement){reasons.add("unexpected-producer-phase");continue;}for(const observation of envelope.observations){if(!requirement.factIds.includes(observation.factId)){reasons.add("unknown-fact");continue;}if(observedFacts.has(observation.factId)){reasons.add("duplicate-fact");continue;}observedFacts.set(observation.factId,{state:observation.state,sequence:envelope.sequence,owner});if(failed.has(observation.state))failedFacts+=1;else if(blocked.has(observation.state))blockedFacts+=1;else if(!satisfied.has(observation.state))reasons.add("unsupported-observation");}}
 for(const [owner,requirement] of requiredByOwner){if(!ownerKeys.has(owner))reasons.add("missing-producer-phase");for(const id of requirement.factIds)if(!observedFacts.has(id))reasons.add("missing-fact");}
 for(const constraint of profile.orderingConstraints){const before=observedFacts.get(constraint.beforeFactId),after=observedFacts.get(constraint.afterFactId);if(before&&after&&before.sequence>=after.sequence)reasons.add("ordering-conflict");}
 if(blockedFacts)reasons.add("observation-unavailable");const finalResult=reasons.size?"BLOCKED":failedFacts?"FAIL":"PASS";return result({profileId:profile.profile.id,sourceDigest:input.sourceDigest,taskDigest:input.taskDigest,result:finalResult,reasonCategories:[...reasons].sort(),inventory:{requiredMeasurements,observedMeasurements:envelopes.length,requiredFacts,observedFacts:observedFacts.size,failedFacts,blockedFacts}});
}
