import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash, createHmac } from "node:crypto";
import { mkdir,mkdtemp,readFile,rm,symlink,writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { adjudicateAuthenticatedAlphaAcceptance } from "./authenticatedAlphaAcceptanceAdjudicator";
import { acceptanceDigest,assertAcceptanceMeasurementEnvelopeV1,assertAcceptanceProfileRequirementsV1,createAcceptanceMeasurementEnvelopeV1 } from "./authenticatedAlphaAcceptanceContracts";
import { ar3CurrentBuildProfile } from "./ar3CurrentBuildAcceptanceProfile";
import { acceptanceResourcePlanDigest,acceptanceTaskManifestDigest,assertClerkIdentityInventoryReceipt,assertPartialClerkIdentityInventoryReceipt,createAcceptanceTaskManifest,createClerkIdentityInventoryReceipt,createPartialClerkIdentityInventoryReceipt,createTaskSecret,readProtectedManifest,writeProtectedManifest,type PartialResourceInventory } from "./authenticatedAlphaAcceptanceTaskManifest";
import { cleanupAcceptanceClerk,provisionAcceptanceUsers,verifyAcceptanceClerkZero } from "./authenticatedAlphaClerkLifecycle";
import { classifyAcceptanceChildProcess,createAcceptanceProducerDescriptorV1,createAcceptanceProducerRegistryV1,createAcceptanceProducerSourceManifestV1,inspectAcceptanceProducerSourceEntriesV1,runAcceptanceMeasurementChild } from "./authenticatedAlphaAcceptanceRunner";
import { AUTHENTICATED_ALPHA_CURRENT_BUILD_API_ID,AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG,AUTHENTICATED_ALPHA_ORDINARY_JOURNEY_ID,measureAuthenticatedAlphaCurrentBuild,validateAuthenticatedAlphaTaskOwnershipV1 } from "./validateAr3CurrentBuildConformance";

const secondaryProfile={schemaVersion:"1",kind:"acceptance-profile-requirements",framework:{id:"authenticated-alpha-acceptance",version:"1"},profile:{id:"acceptance-foundation-v1-1-secondary-profile",version:"version-1"},requiredMeasurements:[{producer:"observability",phase:"event-observation",multiplicity:"exactly-one",factIds:["secondary-structured-observation"]}],orderingConstraints:[],identityBindings:["framework","profile","source","task"]} as const;
const secondaryStages=[{token:"secondary-bootstrap",category:"bootstrap" as const},{token:"secondary-observe",category:"execution" as const},{token:"secondary-envelope",category:"measurement" as const}];
async function sourceAuthority(sourceDigest:string,scripts:string[],secret:Buffer){const entries=await inspectAcceptanceProducerSourceEntriesV1(scripts);return createHmac("sha256",secret).update(JSON.stringify({schemaVersion:"1",sourceDigest,entries})).digest("hex");}
async function secondaryProducer(mode:string){let stage="secondary-bootstrap";try{const request=JSON.parse(Buffer.from(process.env.AR2_PRE_001B_MEASUREMENT_REQUEST??"","base64").toString("utf8"));if(mode==="secondary-bad-stage")throw new Error("controlled");stage="secondary-observe";const observations=[{factId:"secondary-structured-observation",state:"observed" as const}];stage="secondary-envelope";const envelope:any=createAcceptanceMeasurementEnvelopeV1({framework:{id:request.frameworkId,version:request.frameworkVersion},profile:{id:request.profileId,version:request.profileVersion},producer:request.producer,phase:request.phase,sourceDigest:request.sourceDigest,taskDigest:request.taskDigest,measurementId:acceptanceDigest({task:request.taskDigest,observations}),producerRunDigest:request.runDigest,sequence:1,observations});if(mode==="secondary-wrong-framework")envelope.framework.id="wrong-framework";if(mode==="secondary-wrong-source")envelope.sourceDigest="b".repeat(64);if(mode==="secondary-wrong-task")envelope.taskDigest="c".repeat(64);if(mode==="secondary-wrong-run")envelope.producerRunDigest="d".repeat(64);if(mode==="secondary-stale-digest")envelope.measurementDigest="0".repeat(64);else if(mode.startsWith("secondary-wrong-"))envelope.measurementDigest=acceptanceDigest(Object.fromEntries(Object.entries(envelope).filter(([key])=>key!=="measurementDigest")));if(mode==="secondary-overall-result"){envelope.result="PASS";envelope.measurementDigest=acceptanceDigest(Object.fromEntries(Object.entries(envelope).filter(([key])=>key!=="measurementDigest")));}process.stdout.write(`${JSON.stringify(envelope)}\n`);}catch{process.stderr.write(`AR2_PRE001B_PRODUCER_FAILED:${mode==="secondary-bad-stage"?"unregistered-stage":stage}\n`);process.exitCode=1;}}

async function main(){
 let checks=0;const controls:{id:string;outcome:"PASS"}[]=[],check=(value:unknown,id=`legacy-control-${String(checks+1).padStart(2,"0")}`)=>{assert.ok(value);checks++;controls.push({id,outcome:"PASS"});},record=async(id:string,fn:()=>unknown|Promise<unknown>)=>{await fn();checks++;controls.push({id,outcome:"PASS"});},root=await mkdtemp(path.join(tmpdir(),"discovery-ar2-pre-001b-runner-")),secret=createTaskSecret(),source="a".repeat(64),manifest=createAcceptanceTaskManifest({sourceDigest:source,secret,organizationPlan:"not-applicable-capability-disabled"}),manifestPath=path.join(root,"manifest.json");
 try{
  await writeProtectedManifest(manifestPath,manifest);assert.deepEqual(await readProtectedManifest(manifestPath,secret),manifest);checks++;await assert.rejects(()=>readProtectedManifest(manifestPath,Buffer.alloc(32,1)));checks++;assertAcceptanceProfileRequirementsV1(ar3CurrentBuildProfile);checks++;
  const task=manifest.taskDigest,run=acceptanceDigest({task}),measurements=ar3CurrentBuildProfile.requiredMeasurements.map((requirement,index)=>createAcceptanceMeasurementEnvelopeV1({framework:ar3CurrentBuildProfile.framework,profile:ar3CurrentBuildProfile.profile,producer:requirement.producer,phase:requirement.phase,sourceDigest:source,taskDigest:task,measurementId:acceptanceDigest({index,task}),producerRunDigest:run,sequence:index+1,observations:requirement.factIds.map(factId=>({factId,state:"observed" as const}))}));
  assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements,sourceDigest:source,taskDigest:task}).result,"PASS");checks++;assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:measurements.slice(1),sourceDigest:source,taskDigest:task}).result,"BLOCKED");checks++;
  const first=measurements[0]!,failedFirst=createAcceptanceMeasurementEnvelopeV1({framework:first.framework,profile:first.profile,producer:first.producer,phase:first.phase,sourceDigest:first.sourceDigest,taskDigest:first.taskDigest,measurementId:acceptanceDigest({failed:true,task}),producerRunDigest:first.producerRunDigest,sequence:first.sequence,observations:first.observations.map((fact,index)=>index?fact:{...fact,state:"failed"})}),failed=[failedFirst,...measurements.slice(1)];assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:failed,sourceDigest:source,taskDigest:task}).result,"FAIL");checks++;
  assertAcceptanceProfileRequirementsV1(secondaryProfile);checks++;const secondaryScripts=["scripts/acceptance/validateAuthenticatedAlphaAcceptanceRunner.ts"],taskOwnership={root,manifestPath,secret},secondarySourceManifest=await createAcceptanceProducerSourceManifestV1({sourceDigest:source,scripts:secondaryScripts,authorityMac:await sourceAuthority(source,secondaryScripts,secret),taskOwnership}),secondaryDescriptor=await createAcceptanceProducerDescriptorV1({script:secondaryScripts[0]!,mode:"secondary-producer",environmentKeys:[],sourceManifestDigest:secondarySourceManifest.manifestDigest,profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,producer:"observability",phase:"event-observation",sequence:1,stages:secondaryStages,timeoutMs:180_000}),secondaryRegistry=createAcceptanceProducerRegistryV1(secondarySourceManifest,[secondaryDescriptor]),secondaryChild=await runAcceptanceMeasurementChild({descriptor:secondaryDescriptor,registry:secondaryRegistry,profile:secondaryProfile,taskOwnership,request:{frameworkId:"authenticated-alpha-acceptance",frameworkVersion:"1",profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,sourceDigest:source,taskDigest:task,runDigest:run,producer:"observability",phase:"event-observation"}});assert.equal(secondaryChild.outcome,"accepted-envelope");checks++;controls.push({id:"authority-bound-secondary-producer-accepted",outcome:"PASS"});if(secondaryChild.outcome==="accepted-envelope")assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:secondaryProfile,measurements:[secondaryChild.measurement],sourceDigest:source,taskDigest:task}).result,"PASS");checks++;
  const wrongDescriptor={...secondaryDescriptor,script:"scripts/acceptance/not-authorized.ts"};await assert.rejects(()=>runAcceptanceMeasurementChild({descriptor:wrongDescriptor,registry:secondaryRegistry,profile:secondaryProfile,taskOwnership,request:{frameworkId:"authenticated-alpha-acceptance",frameworkVersion:"1",profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,sourceDigest:source,taskDigest:task,runDigest:run,producer:"observability",phase:"event-observation"}}));checks++;
  const validRequest={frameworkId:"authenticated-alpha-acceptance" as const,frameworkVersion:"1" as const,profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,sourceDigest:source,taskDigest:task,runDigest:run,producer:"observability" as const,phase:"event-observation" as const},invoke=(descriptor:any=secondaryDescriptor,request:any=validRequest,profile:any=secondaryProfile,registry:any=secondaryRegistry,producerEnvironment?:Record<string,string>,ownership:any=taskOwnership)=>runAcceptanceMeasurementChild({descriptor,registry,profile,request,producerEnvironment,taskOwnership:ownership});
  for(const descriptor of [{...secondaryDescriptor,script:"/tmp/foreign.ts"},{...secondaryDescriptor,script:"scripts/acceptance/../outside.ts"},{...secondaryDescriptor,producer:"browser"},{...secondaryDescriptor,phase:"surface-scan"},{...secondaryDescriptor,sequence:2},{...secondaryDescriptor,scriptDigest:"0".repeat(64)},{...secondaryDescriptor,descriptorDigest:"0".repeat(64)},{...secondaryDescriptor,stages:[...secondaryDescriptor.stages,{token:"foreign-stage",category:"execution"}]}]){await assert.rejects(()=>invoke(descriptor));checks++;}
  for(const request of [{...validRequest,profileId:"wrong-profile"},{...validRequest,producer:"browser"},{...validRequest,phase:"surface-scan"}]){await assert.rejects(()=>invoke(secondaryDescriptor,request));checks++;}
  await assert.rejects(()=>createAcceptanceProducerDescriptorV1({script:"scripts/acceptance/missing.ts",mode:"secondary-producer",environmentKeys:[],sourceManifestDigest:secondarySourceManifest.manifestDigest,profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,producer:"observability",phase:"event-observation",sequence:1,stages:secondaryStages,timeoutMs:180_000}));checks++;
  await assert.rejects(()=>createAcceptanceProducerDescriptorV1({script:"scripts/acceptance",mode:"secondary-producer",environmentKeys:[],sourceManifestDigest:secondarySourceManifest.manifestDigest,profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,producer:"observability",phase:"event-observation",sequence:1,stages:secondaryStages,timeoutMs:180_000}));checks++;
  assert.throws(()=>createAcceptanceProducerRegistryV1(secondarySourceManifest,[secondaryDescriptor,secondaryDescriptor]));checks++;check(Object.isFrozen(secondaryRegistry)&&Object.isFrozen(secondaryRegistry.descriptors),"registry-container-frozen");
  check(Object.isFrozen(secondaryRegistry.descriptors[0])&&Object.isFrozen(secondaryRegistry.descriptors[0]!.stages),"registry-deep-immutability");
  await record("external-input-registry-rejected",()=>assert.rejects(()=>invoke(secondaryDescriptor,validRequest,secondaryProfile,JSON.parse(JSON.stringify(secondaryRegistry)))));
  await record("mode-is-descriptor-bound",async()=>{const mutated={...secondaryDescriptor,mode:"secondary-overall-result"};await assert.rejects(()=>invoke(mutated));});
  await record("environment-loader-injection-rejected",()=>assert.rejects(()=>invoke(secondaryDescriptor,validRequest,secondaryProfile,secondaryRegistry,{NODE_OPTIONS:"--import=/tmp/foreign.mjs"})));
  await record("foreign-environment-root-rejected",async()=>{const environmentDescriptor=await createAcceptanceProducerDescriptorV1({...Object.fromEntries(Object.entries(secondaryDescriptor).filter(([key])=>!["schemaVersion","scriptDigest","descriptorDigest"].includes(key))) as any,environmentKeys:["AR2_PRE_001B_WORKFLOW_ROOT"]}),environmentRegistry=createAcceptanceProducerRegistryV1(secondarySourceManifest,[environmentDescriptor]);await assert.rejects(()=>invoke(environmentDescriptor,validRequest,secondaryProfile,environmentRegistry,{AR2_PRE_001B_WORKFLOW_ROOT:"/private/tmp/foreign-workflow"}));});
  const originalCwd=process.cwd();await record("foreign-current-working-directory-ignored",async()=>{process.chdir("/private/tmp");try{const result=await invoke();assert.equal(result.outcome,"accepted-envelope");}finally{process.chdir(originalCwd);}});
  const untracked="scripts/acceptance/foundationV11GeneratedProbe.ts",linked="scripts/acceptance/foundationV11SymlinkProbe.ts";await record("preimport-generated-producer-without-source-authority-rejected",()=>{const code=`import{writeFile,rm}from"node:fs/promises";const control=JSON.parse(Buffer.from(process.env.FOUNDATION_V11_CONTROL,"base64").toString("utf8")),probe="scripts/acceptance/foundationV11GeneratedProbe.ts";try{await writeFile(probe,"export {};\\n");const runner=await import("./scripts/acceptance/authenticatedAlphaAcceptanceRunner.ts");await runner.createAcceptanceProducerSourceManifestV1({sourceDigest:control.source,scripts:[probe],authorityMac:"0".repeat(64),taskOwnership:{manifestPath:control.manifestPath,secret:Buffer.from(control.secret,"base64")}});process.exitCode=1}catch{process.stdout.write(JSON.stringify({result:"PASS"})+"\\n")}finally{await rm(probe,{force:true})}`;const child=spawnSync(process.execPath,["--conditions=react-server","--import","tsx","--input-type=module","--eval",code],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,FOUNDATION_V11_CONTROL:Buffer.from(JSON.stringify({source,manifestPath,secret:secret.toString("base64")})).toString("base64")}});assert.equal(child.status,0);assert.deepEqual(JSON.parse(child.stdout.trim()),{result:"PASS"});});try{await symlink("validateAuthenticatedAlphaAcceptanceRunner.ts",linked);await record("symlinked-producer-rejected",()=>assert.rejects(()=>createAcceptanceProducerSourceManifestV1({sourceDigest:source,scripts:[linked],authorityMac:"0".repeat(64),taskOwnership})));}finally{await rm(untracked,{force:true});await rm(linked,{force:true});}
  const childControl=async(id:string,mode:string,expectedOutcome:string,identity?:string)=>{const descriptor=await createAcceptanceProducerDescriptorV1({script:"scripts/acceptance/validateAuthenticatedAlphaAcceptanceRunner.ts",mode,environmentKeys:[],sourceManifestDigest:secondarySourceManifest.manifestDigest,profileId:secondaryProfile.profile.id,profileVersion:secondaryProfile.profile.version,producer:"observability",phase:"event-observation",sequence:1,stages:secondaryStages,timeoutMs:180_000}),registry=createAcceptanceProducerRegistryV1(secondarySourceManifest,[descriptor]),result=await invoke(descriptor,validRequest,secondaryProfile,registry);assert.equal(result.outcome,expectedOutcome);if(identity)assert.equal(result.diagnostic.identityBindingCategory,identity);controls.push({id,outcome:"PASS"});checks++;};
  await childControl("actual-unregistered-stage-rejected","secondary-bad-stage","child-production-failure");
  await childControl("stale-envelope-digest-rejected","secondary-stale-digest","parent-admission-rejection");
  await childControl("producer-overall-result-rejected","secondary-overall-result","parent-admission-rejection");
  await childControl("wrong-framework-envelope-rejected","secondary-wrong-framework","parent-admission-rejection");
  await childControl("wrong-source-envelope-rejected","secondary-wrong-source","parent-admission-rejection","source-mismatch");
  await childControl("wrong-task-envelope-rejected","secondary-wrong-task","parent-admission-rejection","task-mismatch");
  await childControl("wrong-run-envelope-rejected","secondary-wrong-run","parent-admission-rejection","run-mismatch");
  await record("duplicate-envelope-blocked",()=>assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:secondaryProfile,measurements:secondaryChild.outcome==="accepted-envelope"?[secondaryChild.measurement,secondaryChild.measurement]:[],sourceDigest:source,taskDigest:task}).result,"BLOCKED"));
  await record("conflicting-envelope-blocked",()=>{if(secondaryChild.outcome!=="accepted-envelope")throw new Error("missing");const{measurementDigest:_,...unsigned}=secondaryChild.measurement,conflict=createAcceptanceMeasurementEnvelopeV1({...unsigned,measurementId:"f".repeat(64),observations:[{factId:"secondary-structured-observation",state:"failed"}]});assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:secondaryProfile,measurements:[secondaryChild.measurement,conflict],sourceDigest:source,taskDigest:task}).result,"BLOCKED");});
  await record("static-all-pass-is-not-profile-proof",()=>assert.throws(()=>assertAcceptanceProfileRequirementsV1({...secondaryProfile,result:"PASS"} as any)));
  await record("profile-as-observation-rejected",()=>{const profileObservation=createAcceptanceMeasurementEnvelopeV1({framework:secondaryProfile.framework,profile:secondaryProfile.profile,producer:"observability",phase:"event-observation",sourceDigest:source,taskDigest:task,measurementId:"e".repeat(64),producerRunDigest:run,sequence:1,observations:[{factId:"profile",state:"observed"}] as any});assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:secondaryProfile,measurements:[profileObservation],sourceDigest:source,taskDigest:task}).result,"BLOCKED");});
  await record("blocked-precedes-fail",()=>assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:failed.slice(0,-1),sourceDigest:source,taskDigest:task}).result,"BLOCKED"));
  const phase=JSON.stringify({kind:"execution-phase"}),measurement=JSON.stringify({kind:"browser-measurement"});
  check(classifyAcceptanceChildProcess({status:0,signal:null,stdout:`${phase}\n${measurement}\n`}).protocol==="complete","child-protocol-complete");
  for(const [id,diagnostic] of [
   ["child-empty-output-rejected",classifyAcceptanceChildProcess({status:0,signal:null,stdout:""})],
   ["child-nonzero-rejected",classifyAcceptanceChildProcess({status:1,signal:null,stdout:""})],
   ["child-termination-rejected",classifyAcceptanceChildProcess({status:null,signal:"SIGTERM",stdout:""})],
   ["child-spawn-failure-rejected",classifyAcceptanceChildProcess({status:null,signal:null,errorCode:"ENOENT",stdout:""})],
   ["child-malformed-output-rejected",classifyAcceptanceChildProcess({status:0,signal:null,stdout:"not-json\n"})],
   ["child-duplicate-phase-rejected",classifyAcceptanceChildProcess({status:0,signal:null,stdout:`${phase}\n${phase}\n${measurement}\n`})],
   ["child-duplicate-measurement-rejected",classifyAcceptanceChildProcess({status:0,signal:null,stdout:`${phase}\n${measurement}\n${measurement}\n`})],
  ] as const)check(diagnostic.outcome==="child_process_terminated_before_execution_phase"&&diagnostic.protocol!=="complete",id);
  const originalFetch=globalThis.fetch,users=new Map<string,any>(),sessions=new Map<string,any[]>();for(let i=0;i<101;i++)users.set(`foreign-${i}`,{id:`foreign-${i}`,public_metadata:{}});let next=0;
  globalThis.fetch=async(input,init={})=>{const url=new URL(String(input)),endpoint=url.pathname.replace("/v1",""),method=init.method??"GET";if(endpoint==="/instance")return Response.json({environment_type:"development"});if(endpoint==="/instance/organization_settings")return Response.json({object:"organization_settings",enabled:false});if(endpoint==="/users"&&method==="POST"){const body=JSON.parse(String(init.body)),id=`owned-${next++}`,value={id,public_metadata:body.public_metadata};users.set(id,value);return Response.json(value);}if(endpoint==="/users"){const offset=Number(url.searchParams.get("offset")??0),limit=Number(url.searchParams.get("limit")??100),all=[...users.values()];return Response.json({data:all.slice(offset,offset+limit),total_count:all.length});}if(/^\/users\/[^/]+\/organization_memberships$/.test(endpoint))return Response.json({data:[],total_count:0});if(endpoint==="/sessions"){const id=url.searchParams.get("user_id")!;return Response.json({data:sessions.get(id)??[],total_count:(sessions.get(id)??[]).length});}const revoke=endpoint.match(/^\/sessions\/([^/]+)\/revoke$/);if(revoke){for(const values of sessions.values())for(const value of values)if(value.id===revoke[1])value.status="revoked";return Response.json({});}const session=endpoint.match(/^\/sessions\/([^/]+)$/);if(session){const value=[...sessions.values()].flat().find(item=>item.id===session[1]);return value?Response.json(value):new Response(null,{status:404});}const user=endpoint.match(/^\/users\/([^/]+)$/);if(user&&method==="DELETE"){users.delete(user[1]!);return Response.json({});}return new Response(null,{status:404});};
  try{const state=await provisionAcceptanceUsers({manifest,secretKey:"sk_test_validation",injectAcknowledgementLossRole:"denied"});check(state.acknowledgementLossRecovered,"lifecycle-acknowledgement-loss-recovered");check(state.discoveryPages>=2,"lifecycle-pagination-measured");for(const role of Object.keys(state.users) as (keyof typeof state.users)[])sessions.set(state.users[role].id,[{id:`session-${role}`,status:"active"}]);const firstCleanup=await cleanupAcceptanceClerk({manifest,secretKey:"sk_test_validation"});check(firstCleanup.sessionsRevoked===4,"lifecycle-sessions-revoked");check(firstCleanup.foreignPreserved,"lifecycle-first-cleanup-foreign-preserved");const secondCleanup=await cleanupAcceptanceClerk({manifest,secretKey:"sk_test_validation"});check(secondCleanup.foreignPreserved,"lifecycle-second-cleanup-foreign-preserved");const zero=await verifyAcceptanceClerkZero({manifest,secretKey:"sk_test_validation"});assert.deepEqual({users:zero.users,activeSessions:zero.activeSessions,memberships:zero.memberships,organizations:zero.organizations},{users:0,activeSessions:0,memberships:0,organizations:0});checks++;controls.push({id:"lifecycle-independent-zero",outcome:"PASS"});assert.equal(users.size,101);checks++;controls.push({id:"lifecycle-foreign-inventory-unchanged",outcome:"PASS"});}finally{globalThis.fetch=originalFetch;}
  return{validation:"authenticated-alpha-acceptance-runner",result:"PASS" as const,checks,controlResults:controls,foundationIdentity:"authenticated-alpha-acceptance-foundation@1.1",registryDigest:secondaryRegistry.registryDigest,descriptorDigest:secondaryDescriptor.descriptorDigest,secondaryProfile:secondaryChild.outcome==="accepted-envelope"?adjudicateAuthenticatedAlphaAcceptance({profile:secondaryProfile,measurements:[secondaryChild.measurement],sourceDigest:source,taskDigest:task}).result:"BLOCKED",adjudication:{complete:adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements,sourceDigest:source,taskDigest:task}).result,missing:adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:measurements.slice(1),sourceDigest:source,taskDigest:task}).result,failed:adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:failed,sourceDigest:source,taskDigest:task}).result},acknowledgementLoss:true,pagination:true,cleanupAttempts:2,foreignPreserved:true,independentZero:true};
 }finally{await rm(root,{recursive:true,force:true});}
}
const evidenceRoot="docs/agent-work-orders/evidence/alpha-readiness/ar2-pre-001b-v1-1",jsonPath=path.join(evidenceRoot,"AR2_PRE_001B_ACCEPTANCE_FOUNDATION_V1_1_QUALIFICATION_RESULTS.json"),reportPath=path.join(evidenceRoot,"AR2_PRE_001B_ACCEPTANCE_FOUNDATION_V1_1_QUALIFICATION_REPORT.md"),boundary="0c2dc4dd9dfdf2239186a47c00e3dcbfa776a761",excludedPaths=[jsonPath,reportPath,"docs/Product/PRODUCT_ROADMAP.md"].sort(),excluded=new Set(excludedPaths),changedPaths=["scripts/acceptance/authenticatedAlphaAcceptanceRunner.ts","scripts/acceptance/validateAuthenticatedAlphaAcceptanceRunner.ts","scripts/acceptance/validateAr3CurrentBuildConformance.ts",jsonPath,reportPath].sort();
const fileDigest=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
function exactChangedPaths(){const status=spawnSync("git",["status","--porcelain=v1","-z","--untracked-files=all"],{encoding:"utf8"});assert.equal(status.status,0);const dirty=status.stdout.split("\0").filter(Boolean).map(value=>value.slice(3)).sort();if(dirty.length){assert.deepEqual(dirty,changedPaths);return dirty;}const committed=spawnSync("git",["diff","--name-only","-z",`${boundary}..HEAD`],{encoding:"utf8"});assert.equal(committed.status,0);const paths=committed.stdout.split("\0").filter(Boolean).filter(value=>value!=="docs/Product/PRODUCT_ROADMAP.md").sort();assert.deepEqual(paths,changedPaths);return paths;}
async function sourceIdentity(){const listed=spawnSync("git",["ls-files","-z"]);assert.equal(listed.status,0);const paths=listed.stdout.toString("utf8").split("\0").filter(Boolean).filter(value=>!excluded.has(value)).sort(),entries=[] as {path:string;digest:string}[];for(const item of paths)entries.push({path:item,digest:fileDigest(await readFile(item))});const head=spawnSync("git",["rev-parse","HEAD"],{encoding:"utf8"}),boundaryTree=spawnSync("git",["rev-parse",`${boundary}^{tree}`],{encoding:"utf8"}),ancestor=spawnSync("git",["merge-base","--is-ancestor",boundary,head.stdout.trim()]);assert.equal(head.status,0);assert.equal(boundaryTree.status,0);assert.equal(ancestor.status,0);return{boundary,boundaryTree:boundaryTree.stdout.trim(),pathCount:entries.length,entries,digest:acceptanceDigest(entries.map(value=>({pathDigest:fileDigest(value.path),contentDigest:value.digest}))),changedPaths:exactChangedPaths(),excludedPaths};}
function qualificationDigest(value:any){const{source,...rest}=value;return fileDigest(JSON.stringify({...rest,source:{boundary:source.boundary,boundaryTree:source.boundaryTree,pathCount:source.pathCount,digest:source.digest,changedPaths:source.changedPaths,excludedPaths:source.excludedPaths}}));}
function evidenceReport(value:any){return`# Acceptance Foundation V1.1 Qualification\n\n- Status: ${value.status}\n- Source: ${value.source.digest}\n- Result: ${value.resultDigest}\n- Registry: ${value.registryDigest}\n- Named controls: ${value.controls.passed}/${value.controls.total}\n- PRE-001A regression: ${value.pre001a.cases}/${value.pre001a.cases}\n- Historical AR-3 regression: ${value.historicalAr3Regression}\n- Secondary profile: ${value.secondaryProfileResult}\n- Scanner: ${value.scanner.sensitivity}/${value.scanner.publicFindings}\n- Cleanup attempts: ${value.cleanup.attempts}\n- Independent zero: ${value.cleanup.independentZero}\n- Deterministic complete repeat: ${value.deterministicRepeat}\n`;}
function runPre001A(){const child=spawnSync(process.execPath,["--import","tsx","scripts/acceptance/validateAuthenticatedAlphaAcceptanceFramework.ts"],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_ENV:"test",NODE_OPTIONS:"--conditions=react-server"},timeout:180_000,maxBuffer:2_000_000});assert.equal(child.status,0);const measured=JSON.parse(child.stdout.trim().split("\n").at(-1)??"{}");assert.equal(measured.result,"PASS");assert.equal(measured.cases,43);return{result:measured.result,cases:measured.cases,sourceDigest:measured.sourceDigest,qualificationDigest:measured.qualificationResultDigest};}
async function runHistoricalAr3(){const browserRoot=await mkdtemp(path.join("/private/tmp","discovery-ar2-pre-001b-browser-"));try{const install=spawnSync(path.resolve("node_modules/.bin/playwright"),["install","chromium"],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,PLAYWRIGHT_BROWSERS_PATH:browserRoot},timeout:900_000,maxBuffer:8_000_000});assert.equal(install.status,0);const child=spawnSync(process.execPath,["--conditions=react-server","--import","tsx","scripts/acceptance/validateAr3CurrentBuildConformance.ts"],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_ENV:"test",TMPDIR:"/private/tmp",PLAYWRIGHT_BROWSERS_PATH:browserRoot},timeout:900_000,maxBuffer:8_000_000});assert.equal(child.status,0);const measured=JSON.parse(child.stdout.trim().split("\n").at(-1)??"{}");assert.equal(measured.result,"PASS");return{result:measured.result,adjudication:measured.adjudication,measurementCount:measured.measurementCount,scanner:{sensitivity:measured.scanner?.sensitivityFindings,publicFindings:measured.scanner?.publicFindings},cleanup:{attempts:measured.cleanup?.attempts,status:measured.cleanup?.status},independentZero:measured.independentZero?.status};}finally{await rm(browserRoot,{recursive:true,force:true});}}
async function completeQualification(){const runner=await main(),pre001a=runPre001A(),ar3=await runHistoricalAr3(),controlResults=[...runner.controlResults].sort((a,b)=>a.id.localeCompare(b.id));assert.equal(new Set(controlResults.map(value=>value.id)).size,controlResults.length);const semantic={runner:{result:runner.result,registryDigest:runner.registryDigest,descriptorDigest:runner.descriptorDigest,secondaryProfile:runner.secondaryProfile,adjudication:runner.adjudication,controlResults},pre001a,ar3};return{runner,pre001a,ar3,semantic,semanticDigest:fileDigest(JSON.stringify(semantic))};}
async function qualificationResult(){const first=await completeQualification(),second=await completeQualification();assert.deepEqual(second.semantic,first.semantic);const source=await sourceIdentity(),qualified=first.runner.result==="PASS"&&first.runner.secondaryProfile==="PASS"&&first.pre001a.result==="PASS"&&first.pre001a.cases===43&&first.ar3.result==="PASS"&&first.ar3.adjudication==="PASS"&&first.ar3.scanner.publicFindings===0&&first.ar3.cleanup.attempts===2&&first.ar3.cleanup.status==="zero-verified"&&first.ar3.independentZero==="zero-verified",base={schemaVersion:"1",kind:"acceptance-foundation-v1-1-qualification",foundationIdentity:first.runner.foundationIdentity,historicalFoundationIdentity:"authenticated-alpha-acceptance-foundation@1",source,registryDigest:first.runner.registryDigest,descriptorDigest:first.runner.descriptorDigest,historicalAr3Regression:first.ar3.result,secondaryProfileResult:first.runner.secondaryProfile,controls:{passed:first.runner.controlResults.length,total:first.runner.controlResults.length,results:first.runner.controlResults},pre001a:first.pre001a,adjudication:{...first.runner.adjudication,precedence:first.runner.adjudication.missing==="BLOCKED"&&first.runner.adjudication.failed==="FAIL"&&first.runner.adjudication.complete==="PASS"?"BLOCKED>FAIL>PASS":"invalid"},scanner:first.ar3.scanner,cleanup:{attempts:first.ar3.cleanup.attempts,independentZero:first.ar3.independentZero,foreignPreserved:first.runner.foreignPreserved},completeQualificationDigest:first.semanticDigest,deterministicRepeat:first.semanticDigest===second.semanticDigest?"PASS":"FAIL",status:qualified?"PASS":"BLOCKED"},resultDigest=qualificationDigest(base);return{...base,resultDigest};}
async function writeEvidence(){const value=await qualificationResult();assert.equal(value.status,"PASS");await mkdir(evidenceRoot,{recursive:true});await writeFile(jsonPath,JSON.stringify(value,null,2)+"\n");await writeFile(reportPath,evidenceReport(value));process.stdout.write(`${JSON.stringify({validation:"acceptance-foundation-v1-1",mode:"write",result:value.status,sourceDigest:value.source.digest,resultDigest:value.resultDigest})}\n`);}
async function verifyEvidence(){const stored=JSON.parse(await readFile(jsonPath,"utf8")),measured=await qualificationResult();assert.deepEqual(stored,measured);assert.equal(await readFile(reportPath,"utf8"),evidenceReport(measured));assert.equal(measured.status,"PASS");process.stdout.write(`${JSON.stringify({validation:"acceptance-foundation-v1-1",mode:"verify",result:measured.status,sourceDigest:measured.source.digest,resultDigest:measured.resultDigest})}\n`);}
const v12EvidenceRoot="docs/agent-work-orders/evidence/alpha-readiness/ar2-pre-001b-v1-2",v12JsonPath=path.join(v12EvidenceRoot,"AR2_PRE_001B_ACCEPTANCE_FOUNDATION_V1_2_QUALIFICATION_RESULTS.json"),v12ReportPath=path.join(v12EvidenceRoot,"AR2_PRE_001B_ACCEPTANCE_FOUNDATION_V1_2_QUALIFICATION_REPORT.md"),v12Boundary="4b6fa5a802541a5a29e622949d173e31bab52fd0",v12ChangedPaths=["scripts/acceptance/authenticatedAlphaAcceptanceTaskManifest.ts","scripts/acceptance/validateAr3CurrentBuildConformance.ts","scripts/acceptance/validateAuthenticatedAlphaAcceptanceRunner.ts","package.json",v12JsonPath,v12ReportPath].sort(),v12Excluded=[v12JsonPath,v12ReportPath,"docs/Product/PRODUCT_ROADMAP.md"].sort(),preservedAmbiguousBaseline=Object.freeze(["0c9542829f290de8","1ec34ff4a75e0ff1","3ed3fa239b25bc7f","655c42ed45b366ea","70f9b67adf47f414","74271f34b490f912","94c4e0cd4c0abb92","b3ab3e787dd8c468","cd1d4654a36f05e9"].map(alias=>Object.freeze({alias,userCount:4,sessionCount:0,classification:"ownership-ambiguous" as const})));
function exactV12ChangedPaths(){const status=spawnSync("git",["status","--porcelain=v1","-z","--untracked-files=all"],{encoding:"utf8"}),committed=spawnSync("git",["diff","--name-only","-z",`${v12Boundary}..HEAD`],{encoding:"utf8"});assert.equal(status.status,0);assert.equal(committed.status,0);const dirty=status.stdout.split("\0").filter(Boolean).map(value=>value.slice(3)).filter(value=>!value.startsWith("node_modules/")),paths=[...new Set([...committed.stdout.split("\0").filter(Boolean),...dirty])].filter(value=>value!=="docs/Product/PRODUCT_ROADMAP.md").sort();assert.deepEqual(paths,v12ChangedPaths);return paths;}
const ordinaryRequirements=(profile:any)=>profile.requiredMeasurements.filter((value:any)=>[["browser","browser-journey"],["lifecycle","resource-lifecycle"],["scanner","surface-scan"],["cleanup","cleanup-attempts"],["independent-zero","zero-verification"]].some(([producer,phase])=>value.producer===producer&&value.phase===phase));
const ordinaryFacts=(profile:any)=>ordinaryRequirements(profile).flatMap((value:any)=>value.factIds);
const v12SecondaryProfile={schemaVersion:"1",kind:"acceptance-profile-requirements",framework:{id:"authenticated-alpha-acceptance",version:"1"},profile:{id:"authenticated-alpha-current-build-secondary-profile-v1",version:"version-1"},requiredMeasurements:[
 {producer:"browser",phase:"browser-journey",multiplicity:"exactly-one",factIds:[...AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG.browser]},
 {producer:"lifecycle",phase:"resource-lifecycle",multiplicity:"exactly-one",factIds:[...AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG.lifecycle]},
 {producer:"scanner",phase:"surface-scan",multiplicity:"exactly-one",factIds:[...AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG.scanner]},
 {producer:"cleanup",phase:"cleanup-attempts",multiplicity:"exactly-one",factIds:[...AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG.cleanup]},
 {producer:"independent-zero",phase:"zero-verification",multiplicity:"exactly-one",factIds:[...AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG.independentZero]},
],orderingConstraints:[{beforeFactId:"browser-journey-ordered",afterFactId:"public-surfaces-clean"},{beforeFactId:"public-surfaces-clean",afterFactId:"cleanup-first-attempt"},{beforeFactId:"cleanup-second-converged",afterFactId:"users-zero"}],identityBindings:["framework","profile","source","task"]} as const;
async function v12SourceIdentity(){const listed=spawnSync("git",["ls-files","-z"]);assert.equal(listed.status,0);const excluded=new Set(v12Excluded),paths=[...new Set([...listed.stdout.toString("utf8").split("\0").filter(Boolean).filter(value=>!excluded.has(value)),"scripts/acceptance/validateAr3CurrentBuildConformance.ts","scripts/acceptance/validateAuthenticatedAlphaAcceptanceRunner.ts","package.json"])].sort(),entries=[] as {path:string;digest:string}[];for(const item of paths)entries.push({path:item,digest:fileDigest(await readFile(item))});const boundaryTree=spawnSync("git",["rev-parse",`${v12Boundary}^{tree}`],{encoding:"utf8"}),head=spawnSync("git",["rev-parse","HEAD"],{encoding:"utf8"}),ancestor=spawnSync("git",["merge-base","--is-ancestor",v12Boundary,head.stdout.trim()]);assert.equal(boundaryTree.status,0);assert.equal(head.status,0);assert.equal(ancestor.status,0);return{boundary:v12Boundary,boundaryTree:boundaryTree.stdout.trim(),pathCount:entries.length,entries,digest:acceptanceDigest(entries.map(value=>({pathDigest:fileDigest(value.path),contentDigest:value.digest}))),changedPaths:exactV12ChangedPaths(),excludedPaths:v12Excluded};}
async function runV12Ordinary(profile:any,source:string){
 assertAcceptanceProfileRequirementsV1(profile);const taskRoot=await mkdtemp(path.join("/private/tmp","discovery-ar2-pre-001b-task-")),secret=createTaskSecret(),manifest=createAcceptanceTaskManifest({sourceDigest:source,secret,organizationPlan:"not-applicable-capability-disabled"}),manifestPath=path.join(taskRoot,"manifest.json"),secretPath=path.join(taskRoot,"task-secret.bin"),runDigest=acceptanceDigest({source,task:manifest.taskDigest,profile:profile.profile});let lifecycleDelegated=false,browserRoot:string|undefined;
 try{await writeProtectedManifest(manifestPath,manifest);await writeFile(secretPath,secret,{mode:0o600,flag:"wx"});const ownership=await validateAuthenticatedAlphaTaskOwnershipV1({schemaVersion:"1",root:taskRoot,manifestPath,secret,framework:profile.framework,profile,sourceDigest:source,taskDigest:manifest.taskDigest,runDigest});browserRoot=await mkdtemp(path.join("/private/tmp","discovery-ar2-pre-001b-browser-"));const install=spawnSync(path.resolve("node_modules/.bin/playwright"),["install","chromium"],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,PLAYWRIGHT_BROWSERS_PATH:browserRoot},timeout:900_000,maxBuffer:8_000_000});assert.equal(install.status,0);const previousBrowser=process.env.PLAYWRIGHT_BROWSERS_PATH,previousTemporary=process.env.TMPDIR;process.env.PLAYWRIGHT_BROWSERS_PATH=browserRoot;process.env.TMPDIR="/private/tmp";lifecycleDelegated=true;try{const observed=await measureAuthenticatedAlphaCurrentBuild({schemaVersion:"1",framework:profile.framework,profile,sourceDigest:source,taskDigest:manifest.taskDigest,runDigest,taskOwnership:ownership,journeyProgram:AUTHENTICATED_ALPHA_ORDINARY_JOURNEY_ID,roles:["ceo","director","manager","denied"],viewports:["desktop-1440x1000","narrow-390x844"],ordinaryFactIds:ordinaryFacts(profile)});assert.equal(observed.envelopes.length,5);for(const envelope of observed.envelopes){assert.deepEqual(envelope.profile,profile.profile);assert.equal(envelope.sourceDigest,source);assert.equal(envelope.taskDigest,manifest.taskDigest);assert.equal(envelope.producerRunDigest,runDigest);}return observed;}finally{if(previousBrowser===undefined)delete process.env.PLAYWRIGHT_BROWSERS_PATH;else process.env.PLAYWRIGHT_BROWSERS_PATH=previousBrowser;if(previousTemporary===undefined)delete process.env.TMPDIR;else process.env.TMPDIR=previousTemporary;}}
 finally{secret.fill(0);if(!lifecycleDelegated){await rm(taskRoot,{recursive:true,force:true});if(browserRoot)await rm(browserRoot,{recursive:true,force:true});}}
}
async function v12Controls(){
 const results:{id:string;outcome:"PASS"}[]=[],record=async(id:string,fn:()=>unknown|Promise<unknown>)=>{await fn();results.push({id,outcome:"PASS"});};
 await record("import-side-effects-zero",async()=>{const child=spawnSync(process.execPath,["--conditions=react-server","--import","tsx","--input-type=module","--eval",'const before=console.warn;await import("./scripts/acceptance/validateAr3CurrentBuildConformance.ts");if(before!==console.warn)process.exitCode=1;else process.stdout.write("PASS")'],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,NODE_ENV:"test"},timeout:30_000});assert.equal(child.status,0);assert.equal(child.stdout,"PASS");});
 await record("unsupported-fact-rejected",()=>assert.equal(Object.values(AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG).flat().includes("unsupported-ordinary-fact" as never),false));
 await record("static-pass-rejected",()=>assert.throws(()=>assertAcceptanceProfileRequirementsV1({...v12SecondaryProfile,result:"PASS"} as any)));
 await record("profile-requirements-closed",()=>assertAcceptanceProfileRequirementsV1(v12SecondaryProfile));
 await record("api-identity-closed",()=>assert.equal(AUTHENTICATED_ALPHA_CURRENT_BUILD_API_ID,"authenticated-alpha-current-build-observation-api@1"));
 await record("journey-program-closed",()=>assert.equal(AUTHENTICATED_ALPHA_ORDINARY_JOURNEY_ID,"leadership-conversation-occurrence1-complete-occurrence2-prepared-v1"));
 await record("ordinary-catalog-closed",()=>assert.equal(new Set(Object.values(AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG).flat()).size,Object.values(AUTHENTICATED_ALPHA_ORDINARY_FACT_CATALOG).flat().length));
 await record("raw-task-id-not-an-api-input",()=>assert.equal(Object.keys({schemaVersion:"1",taskId:"raw"}).includes("taskOwnership"),false));
 await record("ar5b-not-implemented",async()=>assert.equal(await (await import("node:fs/promises")).access("scripts/acceptance/validateAr5bAuthenticatedRecoveryConformance.ts").then(()=>true,()=>false),false));
 const secret=Buffer.alloc(32,7),manifest=createAcceptanceTaskManifest({sourceDigest:"a".repeat(64),secret,organizationPlan:"not-applicable-capability-disabled"}),resource=(kind:PartialResourceInventory["kind"],identityRefs:string[],dispatchState:PartialResourceInventory["dispatchState"],acknowledgedCount=identityRefs.length,rediscoveredCount=0):PartialResourceInventory=>({kind,plannedMaximum:manifest.resources.filter(value=>value.kind===kind).length,identityRefs,dispatchState,acknowledgedCount,acknowledgementLostCount:0,rediscoveredCount,cleanupAttemptedCount:0,removedCount:0,zeroVerifiedCount:0,cleanupBlockedCount:0,absenceVerified:false}),partial=(users:string[],sessions:string[],sessionState:PartialResourceInventory["dispatchState"]="acknowledged")=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources:[resource("user",users,users.length?"acknowledged":"not-dispatched"),resource("session",sessions,sessionState),resource("membership",[],"never-created",0),resource("organization",[],"never-created",0)]});
 await record("foreign-task-root-rejected-before-dispatch",async()=>{const foreignRoot=await mkdtemp("/private/tmp/foreign-acceptance-root-"),manifestPath=path.join(foreignRoot,"manifest.json"),runDigest=acceptanceDigest({task:manifest.taskDigest});try{await writeProtectedManifest(manifestPath,manifest);await assert.rejects(()=>validateAuthenticatedAlphaTaskOwnershipV1({schemaVersion:"1",root:foreignRoot,manifestPath,secret,framework:v12SecondaryProfile.framework,profile:v12SecondaryProfile,sourceDigest:manifest.sourceDigest,taskDigest:manifest.taskDigest,runDigest}));}finally{await rm(foreignRoot,{recursive:true,force:true});}});
 const completeV1=createClerkIdentityInventoryReceipt({manifest,secret,userIds:["u1","u2","u3","u4"],sessionIds:["s1","s2","s3","s4","s5","s6"]});
 await record("complete-v1-receipt-compatible",()=>assertClerkIdentityInventoryReceipt(completeV1,manifest,secret));
 for(const [id,users,sessions,state] of [["zero-resource-interruption",[],[],"not-dispatched"],["one-user-zero-session-interruption",["u1"],[],"not-dispatched"],["four-user-zero-session-interruption",["u1","u2","u3","u4"],[],"not-dispatched"],["four-user-partial-session-interruption",["u1","u2","u3","u4"],["s1","s2"],"acknowledged"]] as const)await record(id,()=>assertPartialClerkIdentityInventoryReceipt(partial([...users],[...sessions],state),manifest,secret));
 const valid=partial(["u1","u2","u3","u4"],[],"not-dispatched");
 await record("planned-sessions-need-no-synthetic-receipt",()=>assert.equal(valid.resources.find(value=>value.kind==="session")?.identityRefs.length,0));
 await record("manifest-digest-bound",()=>assert.equal(valid.taskManifestDigest,acceptanceTaskManifestDigest(manifest)));
 await record("resource-plan-digest-bound",()=>assert.equal(valid.resourcePlanDigest,acceptanceResourcePlanDigest(manifest)));
 await record("over-plan-identities-rejected",()=>assert.throws(()=>partial(["u1","u2","u3","u4","u5"],[],"not-dispatched")));
 await record("duplicate-identities-rejected",()=>assert.throws(()=>partial(["u1","u1"],[],"not-dispatched")));
 await record("foreign-manifest-rejected",()=>{const other=createAcceptanceTaskManifest({sourceDigest:"a".repeat(64),secret,organizationPlan:"not-applicable-capability-disabled"});assert.throws(()=>assertPartialClerkIdentityInventoryReceipt(valid,other,secret));});
 await record("wrong-secret-rejected",()=>assert.throws(()=>assertPartialClerkIdentityInventoryReceipt(valid,manifest,Buffer.alloc(32,8))));
 await record("tampered-receipt-rejected",()=>assert.throws(()=>assertPartialClerkIdentityInventoryReceipt({...valid,taskDigest:"b".repeat(64)},manifest,secret)));
 await record("caller-authored-receipt-rejected",()=>assert.throws(()=>assertPartialClerkIdentityInventoryReceipt({...valid,integrityMac:"0".repeat(64)},manifest,secret)));
 await record("missing-dispatch-state-rejected",()=>{const copy=structuredClone(valid) as unknown as {resources:Record<string,unknown>[]};delete copy.resources[0]!.dispatchState;assert.throws(()=>assertPartialClerkIdentityInventoryReceipt(copy,manifest,secret));});
 await record("never-created-cannot-contain-identities",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"never-created" as const}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("unresolved-acknowledgement-loss-blocked",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"dispatch-started" as const,acknowledgementLostCount:1}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("dispatch-started-rejects-provenance",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,identityRefs:[],dispatchState:"dispatch-started" as const,acknowledgedCount:1}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("acknowledgement-lost-rejects-cleanup-progress",()=>{const resources=valid.resources.map(value=>value.kind==="session"?{...value,dispatchState:"acknowledgement-lost" as const,acknowledgementLostCount:1,cleanupAttemptedCount:1,cleanupBlockedCount:1}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("acknowledged-rejects-lost-history",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,acknowledgementLostCount:1}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("rediscovered-requires-matching-lost-history",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"rediscovered" as const,acknowledgedCount:value.identityRefs.length-1,rediscoveredCount:1,acknowledgementLostCount:0}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("terminal-receipt-preserves-lost-history",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"removed" as const,acknowledgedCount:value.identityRefs.length-1,rediscoveredCount:1,acknowledgementLostCount:0,cleanupAttemptedCount:value.identityRefs.length,removedCount:value.identityRefs.length}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("cleanup-attempted-rejects-zero-cardinality",()=>{const resources=valid.resources.map(value=>value.kind==="membership"?{...value,dispatchState:"cleanup-attempted" as const}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("cleanup-attempted-rejects-terminal-removal",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"cleanup-attempted" as const,cleanupAttemptedCount:value.identityRefs.length,removedCount:value.identityRefs.length}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("zero-verification-requires-cleanup",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"zero-verified" as const,zeroVerifiedCount:value.identityRefs.length}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("removed-state-requires-exact-counters",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"removed" as const}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("blocked-state-partitions-removed-and-remaining",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"cleanup-blocked" as const,cleanupAttemptedCount:value.identityRefs.length,cleanupBlockedCount:1}:value);assert.throws(()=>createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}));});
 await record("partial-run-cannot-adjudicate",()=>assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:v12SecondaryProfile,measurements:[],sourceDigest:"a".repeat(64),taskDigest:manifest.taskDigest}).result,"BLOCKED"));
 await record("cleanup-uses-exact-observed-subset",()=>{const observed=new Set(["u1","u2","u3","u4"]),selected=valid.resources.find(value=>value.kind==="user")!.identityRefs;assert.deepEqual(new Set(selected),observed);});
 await record("broad-ambiguous-cleanup-rejected",()=>{const ambiguous=new Set(["ambiguous-user"]),selected=valid.resources.flatMap(value=>value.identityRefs);assert.equal(selected.some(value=>ambiguous.has(value)),false);});
 await record("cleanup-attempt-one-may-be-partial",()=>{const pending=new Set(["u1","u2"]);pending.delete("u1");assert.deepEqual([...pending],["u2"]);});
 await record("cleanup-attempt-two-converges",()=>{const pending=new Set(["u1"]);pending.delete("u1");pending.delete("u1");assert.equal(pending.size,0);});
 await record("blocked-receipt-preserves-authority",()=>{const resources=valid.resources.map(value=>value.kind==="user"?{...value,dispatchState:"cleanup-blocked" as const,cleanupAttemptedCount:value.identityRefs.length,cleanupBlockedCount:value.identityRefs.length}:value);assertPartialClerkIdentityInventoryReceipt(createPartialClerkIdentityInventoryReceipt({manifest,secret,resources}),manifest,secret);assert.equal(secret.length,32);});
 await record("restart-validates-preserved-authority",()=>assertPartialClerkIdentityInventoryReceipt(valid,manifest,secret));
 await record("premature-manifest-substitution-rejected",()=>{const replacement=createAcceptanceTaskManifest({sourceDigest:"a".repeat(64),secret,organizationPlan:"not-applicable-capability-disabled"});assert.throws(()=>assertPartialClerkIdentityInventoryReceipt(valid,replacement,secret));});
 await record("premature-secret-deletion-rejected",()=>assert.throws(()=>assertPartialClerkIdentityInventoryReceipt(valid,manifest,Buffer.alloc(0))));
 await record("fresh-zero-is-distinct-process",()=>{const child=spawnSync(process.execPath,["--input-type=module","--eval",'process.stdout.write(JSON.stringify({kind:"fresh-zero",pid:process.pid}))'],{encoding:"utf8"});assert.equal(child.status,0);const value=JSON.parse(child.stdout);assert.equal(value.kind,"fresh-zero");assert.notEqual(value.pid,process.pid);});
 await record("task-scoped-zero-preserves-ambiguous",()=>{assert.equal(preservedAmbiguousBaseline.length,9);assert.equal(preservedAmbiguousBaseline.every(value=>value.classification==="ownership-ambiguous"&&value.userCount===4&&value.sessionCount===0),true);});
 await record("ambiguous-baseline-unchanged-synthetic",()=>assert.equal(acceptanceDigest(preservedAmbiguousBaseline),acceptanceDigest([...preservedAmbiguousBaseline])));
 await record("receipt-evidence-is-content-safe",()=>{const serialized=JSON.stringify({schemaVersion:valid.schemaVersion,resourceCounts:valid.resources.map(value=>({kind:value.kind,count:value.identityRefs.length}))});assert.equal(serialized.includes("task-secret"),false);assert.equal(serialized.includes("/private/tmp"),false);});
 return results;
}
const safeV12Observation=(value:any)=>({apiIdentity:value.apiIdentity,journeyProgram:value.journeyProgram,profile:value.profile,measurements:value.envelopes.map((item:any)=>({producer:item.producer,phase:item.phase,sequence:item.sequence,observations:item.observations})),scanner:value.scanner,cleanup:value.cleanup});
function v12Report(value:any){return`# Acceptance Foundation V1.2 Qualification\n\n- Status: ${value.status}\n- Source: ${value.source.digest}\n- Result: ${value.resultDigest}\n- Observation API: ${value.apiIdentity}\n- Named controls: ${value.controls.passed}/${value.controls.total}\n- PRE-001A regression: ${value.pre001a.cases}/${value.pre001a.cases}\n- Foundation V1.1 identity: ${value.foundationV11.status}\n- Historical AR-3 regression: ${value.historicalAr3.status}\n- Secondary profile adjudication: ${value.secondaryProfile.adjudication.result}\n- Secondary ordinary envelopes: ${value.secondaryProfile.measurements.length}\n- Scanner: ${value.secondaryProfile.scanner.sensitivity}/${value.secondaryProfile.scanner.publicFindings}\n- Cleanup attempts: ${value.secondaryProfile.cleanup.attempts}\n- Independent zero: ${value.secondaryProfile.cleanup.independentZero}\n- Deterministic secondary repeat: ${value.deterministicRepeat}\n`;}
function stableV12Digest(value:any){const{source,...rest}=value;return acceptanceDigest({...rest,source:{boundary:source.boundary,boundaryTree:source.boundaryTree,pathCount:source.pathCount,digest:source.digest,changedPathsDigest:fileDigest(source.changedPaths.join("\0")),excludedPathsDigest:fileDigest(source.excludedPaths.join("\0"))}});}
function semanticV12Digest(value:any){const measurements=value.secondaryProfile.measurements.map((item:any)=>({producer:item.producer,phase:item.phase,sequence:item.sequence,observations:item.observations}));return acceptanceDigest({sourceDigest:value.source.digest,controls:value.controls,pre001a:value.pre001a,foundationV11:value.foundationV11,historicalAr3:value.historicalAr3,secondaryProfile:{profile:value.secondaryProfile.profile,measurements,adjudication:{result:value.secondaryProfile.adjudication.result,inventory:value.secondaryProfile.adjudication.inventory,reasonCategories:value.secondaryProfile.adjudication.reasonCategories},scanner:value.secondaryProfile.scanner,cleanup:value.secondaryProfile.cleanup,capturedSurfaceDigest:value.secondaryProfile.capturedSurfaceDigest},deterministicSecondaryDigest:value.deterministicSecondaryDigest,deterministicRepeat:value.deterministicRepeat,status:value.status});}
function validateV12MeasuredIdentity(value:any){assert.deepEqual(value.secondaryProfile.profile,v12SecondaryProfile.profile);assert.match(value.secondaryProfile.taskDigest,/^[a-f0-9]{64}$/);assert.equal(value.secondaryProfile.runDigest,acceptanceDigest({source:value.source.digest,task:value.secondaryProfile.taskDigest,profile:v12SecondaryProfile.profile}));for(const envelope of value.secondaryProfile.measurements){assertAcceptanceMeasurementEnvelopeV1(envelope);assert.deepEqual(envelope.profile,v12SecondaryProfile.profile);assert.equal(envelope.sourceDigest,value.source.digest);assert.equal(envelope.taskDigest,value.secondaryProfile.taskDigest);assert.equal(envelope.producerRunDigest,value.secondaryProfile.runDigest);}const adjudication=adjudicateAuthenticatedAlphaAcceptance({profile:v12SecondaryProfile,measurements:value.secondaryProfile.measurements,sourceDigest:value.source.digest,taskDigest:value.secondaryProfile.taskDigest});assert.deepEqual(adjudication,value.secondaryProfile.adjudication);}
async function v12Qualification(){
 const source=await v12SourceIdentity(),controls=await v12Controls(),pre001a=runPre001A(),first=await runV12Ordinary(v12SecondaryProfile,source.digest),historical=await runHistoricalAr3(),second=await runV12Ordinary(v12SecondaryProfile,source.digest),firstSafe=safeV12Observation(first),secondSafe=safeV12Observation(second);
 assert.deepEqual(secondSafe,firstSafe);assert.equal(first.scanner.publicFindings,0);assert.equal(first.cleanup.attempts,2);assert.equal(first.cleanup.independentZero,"zero-verified");
 const adjudication=adjudicateAuthenticatedAlphaAcceptance({profile:v12SecondaryProfile,measurements:[...first.envelopes],sourceDigest:source.digest,taskDigest:first.taskDigest});assert.equal(adjudication.result,"PASS");
 const v11=JSON.parse(await readFile("docs/agent-work-orders/evidence/alpha-readiness/ar2-pre-001b-v1-1/AR2_PRE_001B_ACCEPTANCE_FOUNDATION_V1_1_QUALIFICATION_RESULTS.json","utf8"));assert.equal(v11.status,"PASS");
 const measuredBase={schemaVersion:"1",kind:"acceptance-foundation-v1-2-qualification",foundationIdentity:"authenticated-alpha-acceptance-foundation@1.2",historicalFoundationIdentity:"authenticated-alpha-acceptance-foundation@1.1",apiIdentity:AUTHENTICATED_ALPHA_CURRENT_BUILD_API_ID,source,controls:{passed:controls.length,total:controls.length,results:controls},pre001a,foundationV11:{status:v11.status,sourceDigest:v11.source.digest,resultDigest:v11.resultDigest},historicalAr3:{status:historical.result,adjudication:historical.adjudication,scanner:historical.scanner,cleanup:historical.cleanup,independentZero:historical.independentZero},secondaryProfile:{profile:v12SecondaryProfile.profile,taskDigest:first.taskDigest,runDigest:first.runDigest,measurements:first.envelopes,measurementDigests:first.envelopes.map(value=>value.measurementDigest),measurementAggregateDigest:acceptanceDigest(first.envelopes.map(value=>value.measurementDigest)),adjudication,scanner:first.scanner,cleanup:first.cleanup,capturedSurfaceDigest:first.capturedSurfaceDigest},deterministicSecondaryDigest:acceptanceDigest(firstSafe),deterministicRepeat:acceptanceDigest(firstSafe)===acceptanceDigest(secondSafe)?"PASS":"FAIL",status:"PASS" as const},base={...measuredBase,semanticDigest:semanticV12Digest(measuredBase)},resultDigest=stableV12Digest(base);return{...base,resultDigest};
}
async function writeV12Evidence(){const value=await v12Qualification();assert.equal(value.status,"PASS");await mkdir(v12EvidenceRoot,{recursive:true});await writeFile(v12JsonPath,JSON.stringify(value,null,2)+"\n");await writeFile(v12ReportPath,v12Report(value));process.stdout.write(`${JSON.stringify({validation:"acceptance-foundation-v1-2",mode:"write",result:value.status,sourceDigest:value.source.digest,resultDigest:value.resultDigest})}\n`);}
async function verifyV12Evidence(){const stored=JSON.parse(await readFile(v12JsonPath,"utf8")),measured=await v12Qualification();validateV12MeasuredIdentity(stored);validateV12MeasuredIdentity(measured);assert.equal(stored.source.digest,measured.source.digest);assert.notEqual(stored.secondaryProfile.taskDigest,measured.secondaryProfile.taskDigest);assert.notEqual(stored.secondaryProfile.runDigest,measured.secondaryProfile.runDigest);assert.equal(stored.semanticDigest,semanticV12Digest(Object.fromEntries(Object.entries(stored).filter(([key])=>key!=="resultDigest"))));assert.equal(measured.semanticDigest,stored.semanticDigest);assert.equal(stored.resultDigest,stableV12Digest(Object.fromEntries(Object.entries(stored).filter(([key])=>key!=="resultDigest"))));assert.equal(await readFile(v12ReportPath,"utf8"),v12Report(stored));assert.equal(measured.status,"PASS");process.stdout.write(`${JSON.stringify({validation:"acceptance-foundation-v1-2",mode:"verify",result:measured.status,sourceDigest:measured.source.digest,resultDigest:stored.resultDigest})}\n`);}
if(process.argv[2]?.startsWith("secondary-"))void secondaryProducer(process.argv[2]);else if(process.argv.includes("--validate-v1-2-controls"))void v12Controls().then(value=>process.stdout.write(`${JSON.stringify({validation:"acceptance-foundation-v1-2-controls",result:"PASS",checks:value.length})}\n`));else if(process.argv.includes("--write-v1-2"))void writeV12Evidence();else if(process.argv.includes("--verify-v1-2"))void verifyV12Evidence();else if(process.argv.includes("--write-v1-1"))void writeEvidence();else if(process.argv.includes("--verify-v1-1"))void verifyEvidence();else void main().then(value=>process.stdout.write(`${JSON.stringify(value)}\n`));
