import assert from "node:assert/strict";
import { mkdtemp,rm } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { adjudicateAuthenticatedAlphaAcceptance } from "./authenticatedAlphaAcceptanceAdjudicator";
import { acceptanceDigest,assertAcceptanceProfileRequirementsV1,createAcceptanceMeasurementEnvelopeV1 } from "./authenticatedAlphaAcceptanceContracts";
import { ar3CurrentBuildProfile } from "./ar3CurrentBuildAcceptanceProfile";
import { createAcceptanceTaskManifest,createTaskSecret,readProtectedManifest,writeProtectedManifest } from "./authenticatedAlphaAcceptanceTaskManifest";
import { cleanupAcceptanceClerk,provisionAcceptanceUsers,verifyAcceptanceClerkZero } from "./authenticatedAlphaClerkLifecycle";
import { classifyAcceptanceChildProcess,runAcceptanceMeasurementChild } from "./authenticatedAlphaAcceptanceRunner";

async function main(){
 let checks=0;const check=(value:unknown)=>{assert.ok(value);checks++;},root=await mkdtemp(path.join(tmpdir(),"discovery-ar2-pre-001b-runner-")),secret=createTaskSecret(),source="a".repeat(64),manifest=createAcceptanceTaskManifest({sourceDigest:source,secret,organizationPlan:"not-applicable-capability-disabled"}),manifestPath=path.join(root,"manifest.json");
 try{
  await writeProtectedManifest(manifestPath,manifest);assert.deepEqual(await readProtectedManifest(manifestPath,secret),manifest);checks++;await assert.rejects(()=>readProtectedManifest(manifestPath,Buffer.alloc(32,1)));checks++;assertAcceptanceProfileRequirementsV1(ar3CurrentBuildProfile);checks++;
  const task=manifest.taskDigest,run=acceptanceDigest({task}),measurements=ar3CurrentBuildProfile.requiredMeasurements.map((requirement,index)=>createAcceptanceMeasurementEnvelopeV1({framework:ar3CurrentBuildProfile.framework,profile:ar3CurrentBuildProfile.profile,producer:requirement.producer,phase:requirement.phase,sourceDigest:source,taskDigest:task,measurementId:acceptanceDigest({index,task}),producerRunDigest:run,sequence:index+1,observations:requirement.factIds.map(factId=>({factId,state:"observed" as const}))}));
  assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements,sourceDigest:source,taskDigest:task}).result,"PASS");checks++;assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:measurements.slice(1),sourceDigest:source,taskDigest:task}).result,"BLOCKED");checks++;
  const first=measurements[0]!,failedFirst=createAcceptanceMeasurementEnvelopeV1({framework:first.framework,profile:first.profile,producer:first.producer,phase:first.phase,sourceDigest:first.sourceDigest,taskDigest:first.taskDigest,measurementId:acceptanceDigest({failed:true,task}),producerRunDigest:first.producerRunDigest,sequence:first.sequence,observations:first.observations.map((fact,index)=>index?fact:{...fact,state:"failed"})}),failed=[failedFirst,...measurements.slice(1)];assert.equal(adjudicateAuthenticatedAlphaAcceptance({profile:ar3CurrentBuildProfile,measurements:failed,sourceDigest:source,taskDigest:task}).result,"FAIL");checks++;
  await assert.rejects(()=>runAcceptanceMeasurementChild({script:"scripts/acceptance/not-authorized.ts",mode:"test",request:{frameworkId:"authenticated-alpha-acceptance",frameworkVersion:"1",profileId:ar3CurrentBuildProfile.profile.id,profileVersion:ar3CurrentBuildProfile.profile.version,sourceDigest:source,taskDigest:task,runDigest:run,producer:"browser",phase:"browser-journey"}}));checks++;
  const phase=JSON.stringify({kind:"execution-phase"}),measurement=JSON.stringify({kind:"browser-measurement"});
  check(classifyAcceptanceChildProcess({status:0,signal:null,stdout:`${phase}\n${measurement}\n`}).protocol==="complete");
  for(const diagnostic of [
   classifyAcceptanceChildProcess({status:0,signal:null,stdout:""}),
   classifyAcceptanceChildProcess({status:1,signal:null,stdout:""}),
   classifyAcceptanceChildProcess({status:null,signal:"SIGTERM",stdout:""}),
   classifyAcceptanceChildProcess({status:null,signal:null,errorCode:"ENOENT",stdout:""}),
   classifyAcceptanceChildProcess({status:0,signal:null,stdout:"not-json\n"}),
   classifyAcceptanceChildProcess({status:0,signal:null,stdout:`${phase}\n${phase}\n${measurement}\n`}),
   classifyAcceptanceChildProcess({status:0,signal:null,stdout:`${phase}\n${measurement}\n${measurement}\n`}),
  ])check(diagnostic.outcome==="child_process_terminated_before_execution_phase"&&diagnostic.protocol!=="complete");
  const originalFetch=globalThis.fetch,users=new Map<string,any>(),sessions=new Map<string,any[]>();for(let i=0;i<101;i++)users.set(`foreign-${i}`,{id:`foreign-${i}`,public_metadata:{}});let next=0;
  globalThis.fetch=async(input,init={})=>{const url=new URL(String(input)),endpoint=url.pathname.replace("/v1",""),method=init.method??"GET";if(endpoint==="/instance")return Response.json({environment_type:"development"});if(endpoint==="/instance/organization_settings")return Response.json({object:"organization_settings",enabled:false});if(endpoint==="/users"&&method==="POST"){const body=JSON.parse(String(init.body)),id=`owned-${next++}`,value={id,public_metadata:body.public_metadata};users.set(id,value);return Response.json(value);}if(endpoint==="/users"){const offset=Number(url.searchParams.get("offset")??0),limit=Number(url.searchParams.get("limit")??100),all=[...users.values()];return Response.json({data:all.slice(offset,offset+limit),total_count:all.length});}if(/^\/users\/[^/]+\/organization_memberships$/.test(endpoint))return Response.json({data:[],total_count:0});if(endpoint==="/sessions"){const id=url.searchParams.get("user_id")!;return Response.json({data:sessions.get(id)??[],total_count:(sessions.get(id)??[]).length});}const revoke=endpoint.match(/^\/sessions\/([^/]+)\/revoke$/);if(revoke){for(const values of sessions.values())for(const value of values)if(value.id===revoke[1])value.status="revoked";return Response.json({});}const session=endpoint.match(/^\/sessions\/([^/]+)$/);if(session){const value=[...sessions.values()].flat().find(item=>item.id===session[1]);return value?Response.json(value):new Response(null,{status:404});}const user=endpoint.match(/^\/users\/([^/]+)$/);if(user&&method==="DELETE"){users.delete(user[1]!);return Response.json({});}return new Response(null,{status:404});};
  try{const state=await provisionAcceptanceUsers({manifest,secretKey:"sk_test_validation",injectAcknowledgementLossRole:"denied"});check(state.acknowledgementLossRecovered);check(state.discoveryPages>=2);for(const role of Object.keys(state.users) as (keyof typeof state.users)[])sessions.set(state.users[role].id,[{id:`session-${role}`,status:"active"}]);const firstCleanup=await cleanupAcceptanceClerk({manifest,secretKey:"sk_test_validation"});check(firstCleanup.sessionsRevoked===4);check(firstCleanup.foreignPreserved);const secondCleanup=await cleanupAcceptanceClerk({manifest,secretKey:"sk_test_validation"});check(secondCleanup.foreignPreserved);const zero=await verifyAcceptanceClerkZero({manifest,secretKey:"sk_test_validation"});assert.deepEqual({users:zero.users,activeSessions:zero.activeSessions,memberships:zero.memberships,organizations:zero.organizations},{users:0,activeSessions:0,memberships:0,organizations:0});checks++;assert.equal(users.size,101);checks++;}finally{globalThis.fetch=originalFetch;}
  process.stdout.write(`${JSON.stringify({validation:"authenticated-alpha-acceptance-runner",result:"PASS",checks,acknowledgementLoss:true,pagination:true,cleanupAttempts:2,foreignPreserved:true,independentZero:true})}\n`);
 }finally{await rm(root,{recursive:true,force:true});}
}
void main();
