import { chmod,lstat,mkdir,open,readFile,readdir,rename,rm } from "node:fs/promises";
import { dirname,join,resolve } from "node:path";
import { assertStudioComparison,assertStudioId,assertStudioRun,assertStudioScenarioIntegrity,assertStudioScorecard,studioDigest,type LegacyStudioRunV1,type StudioComparisonV1,type StudioEvaluationPlanV1,type StudioRunV1,type StudioScenarioV1,type StudioScorecardV1 } from "./contracts";
import { assertFrontierBenchmarkHardGateResult,assertFrontierBenchmarkHardGateReview,assertFrontierLocalAdjudication,assertFrontierRunPlan,assertTwoWayBlindReview,type DiscoveryStudioFrontierRunPlanV1,type DiscoveryStudioTwoWayBlindReviewV1,type FrontierBenchmarkHardGateResultV1,type FrontierBenchmarkHardGateReviewV1,type FrontierLocalAdjudicationV1 } from "./frontierModelContracts";

export const studioRoot=()=>resolve(process.env.DISCOVERY_STUDIO_ROOT||"/private/tmp/discovery-studio");
const safe=/^[a-z0-9][a-z0-9-]{0,127}$/;
const id=(value:string)=>assertStudioId(value);
async function ensureDir(path:string){await mkdir(path,{recursive:true,mode:0o700});await chmod(path,0o700);const stat=await lstat(path);if(!stat.isDirectory()||stat.isSymbolicLink()||(stat.mode&0o777)!==0o700)throw new Error("Studio directory is unsafe.")}
async function root(){const value=studioRoot();if(!/^\/private\/tmp\/discovery-studio(?:\/|$)/.test(value))throw new Error("Studio root is not task-owned.");await ensureDir(value);return value}
async function validateFile(path:string){const stat=await lstat(path);if(!stat.isFile()||stat.isSymbolicLink()||(stat.mode&0o777)!==0o600)throw new Error("Studio artifact is unsafe.")}
async function atomicJson(path:string,value:unknown,validate:(value:unknown)=>void){const dir=dirname(path);await ensureDir(dir);const temp=join(dir,`.${path.split("/").pop()}.${process.pid}.${Date.now()}.tmp`),bytes=`${JSON.stringify(value,null,2)}\n`,handle=await open(temp,"wx",0o600);try{await handle.writeFile(bytes);await handle.sync()}finally{await handle.close()}try{await validateFile(temp);const reread=await readFile(temp,"utf8");if(reread!==bytes)throw new Error("Studio artifact reread mismatch.");validate(JSON.parse(reread));await rename(temp,path);const directory=await open(dir,"r");try{await directory.sync()}finally{await directory.close()}await validateFile(path);validate(JSON.parse(await readFile(path,"utf8")))}catch(error){await rm(temp,{force:true});throw error}}
async function files(kind:string){const dir=join(await root(),kind);await ensureDir(dir);return(await readdir(dir)).filter(x=>safe.test(x.replace(/\.json$/,""))&&x.endsWith(".json")).sort()}
async function readJson(path:string){await validateFile(path);return JSON.parse(await readFile(path,"utf8"))}

export async function saveScenario(value:StudioScenarioV1){assertStudioScenarioIntegrity(value);await atomicJson(join(await root(),"scenarios",`${id(value.scenarioId)}.json`),value,assertStudioScenarioIntegrity);return value}
export async function loadScenario(value:string){const scenario=await readJson(join(await root(),"scenarios",`${id(value)}.json`));assertStudioScenarioIntegrity(scenario);return scenario}
export async function listScenarios(){return files("scenarios")}

export async function saveRun(value:StudioRunV1){assertStudioRun(value);for(const name of await files("runs")){const existing=await readJson(join(await root(),"runs",name));if(existing.contractVersion==="3"){assertStudioRun(existing);if(existing.experimentId===value.experimentId&&existing.runName===value.runName&&existing.runId!==value.runId)throw new Error("Duplicate run name within experiment.")}}await atomicJson(join(await root(),"runs",`${id(value.runId)}.json`),value,assertStudioRun);return value}
export async function loadRun(value:string){const run=await readJson(join(await root(),"runs",`${id(value)}.json`));if(run.contractVersion!=="3")throw new Error("Legacy Studio run is not eligible for controlled comparison.");assertStudioRun(run);return run}
export async function listRuns(){const values:StudioRunV1[]=[];for(const name of await files("runs")){const raw=await readJson(join(await root(),"runs",name));if(raw.contractVersion==="3"){assertStudioRun(raw);values.push(raw)}}return values.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
export async function listLegacyRuns():Promise<LegacyStudioRunV1[]>{const values:LegacyStudioRunV1[]=[];for(const name of await files("runs")){const raw=await readJson(join(await root(),"runs",name));if(raw.contractVersion!=="3")values.push({contractVersion:"legacy-studio-run",legacyRunId:String(raw.runId??name.replace(/\.json$/,"")),originalContractVersion:String(raw.contractVersion??"unknown"),reason:"missing-controlled-evaluation-metadata",rawDigest:studioDigest(raw)})}return values}

export async function saveComparison(value:StudioComparisonV1){assertStudioComparison(value);await atomicJson(join(await root(),"comparisons",`${id(value.comparisonId)}.json`),value,assertStudioComparison);return value}
export async function loadComparison(value:string){const comparison=await readJson(join(await root(),"comparisons",`${id(value)}.json`));assertStudioComparison(comparison);return comparison}
export async function listComparisons(){const values:StudioComparisonV1[]=[];for(const name of await files("comparisons")){const value=await readJson(join(await root(),"comparisons",name));assertStudioComparison(value);values.push(value)}return values.sort((a,b)=>a.comparisonName.localeCompare(b.comparisonName))}

function assertPlan(value:unknown):asserts value is StudioEvaluationPlanV1{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Evaluation plan is invalid.");const v=value as StudioEvaluationPlanV1;if(v.contractVersion!=="1"||!safe.test(v.experimentId)||!Array.isArray(v.runPlans)||v.runPlans.length!==7||!Array.isArray(v.comparisonPlans)||v.comparisonPlans.length!==5||studioDigest(Object.fromEntries(Object.entries(v).filter(([key])=>key!=="planDigest")))!==v.planDigest)throw new Error("Evaluation plan integrity is invalid.");if(new Set(v.runPlans.map(x=>x.runName)).size!==v.runPlans.length)throw new Error("Evaluation plan run names are not unique.")}
export async function saveEvaluationPlan(value:StudioEvaluationPlanV1){assertPlan(value);await atomicJson(join(await root(),"experiments",`${id(value.experimentId)}.json`),value,assertPlan);return value}
export async function loadEvaluationPlan(value:string){const plan=await readJson(join(await root(),"experiments",`${id(value)}.json`));assertPlan(plan);return plan}

export async function saveFrontierRunPlan(value:DiscoveryStudioFrontierRunPlanV1){assertFrontierRunPlan(value);for(const name of await files("frontier-plans")){const existing=await readJson(join(await root(),"frontier-plans",name));assertFrontierRunPlan(existing);if(existing.experimentId===value.experimentId&&existing.runName===value.runName&&existing.planId!==value.planId)throw new Error("Duplicate frontier display name within experiment.")}await atomicJson(join(await root(),"frontier-plans",`${id(value.planId)}.json`),value,assertFrontierRunPlan);return value}
export async function loadFrontierRunPlan(value:string){const plan=await readJson(join(await root(),"frontier-plans",`${id(value)}.json`));assertFrontierRunPlan(plan);return plan}
export async function listFrontierRunPlans(){const values:DiscoveryStudioFrontierRunPlanV1[]=[];for(const name of await files("frontier-plans")){const value=await readJson(join(await root(),"frontier-plans",name));assertFrontierRunPlan(value);values.push(value)}return values.sort((a,b)=>a.runName.localeCompare(b.runName))}
export async function saveFrontierLocalAdjudication(value:FrontierLocalAdjudicationV1){assertFrontierLocalAdjudication(value);await atomicJson(join(await root(),"frontier-adjudications",`${id(value.adjudicationId)}.json`),value,assertFrontierLocalAdjudication);return value}
export async function loadFrontierLocalAdjudicationForRun(runId:string){for(const name of await files("frontier-adjudications")){const value=await readJson(join(await root(),"frontier-adjudications",name));assertFrontierLocalAdjudication(value);if(value.runId===runId)return value}return null}
export async function saveFrontierBenchmarkHardGateResult(value:FrontierBenchmarkHardGateResultV1){assertFrontierBenchmarkHardGateResult(value);await atomicJson(join(await root(),"frontier-hard-gates",`${id(value.hardGateResultId)}.json`),value,assertFrontierBenchmarkHardGateResult);return value}
export async function listFrontierBenchmarkHardGateResults(){const values:FrontierBenchmarkHardGateResultV1[]=[];for(const name of await files("frontier-hard-gates")){const value=await readJson(join(await root(),"frontier-hard-gates",name));assertFrontierBenchmarkHardGateResult(value);values.push(value)}return values}
export async function saveFrontierBenchmarkHardGateReview(value:FrontierBenchmarkHardGateReviewV1){assertFrontierBenchmarkHardGateReview(value);await atomicJson(join(await root(),"frontier-hard-gate-reviews",`${id(value.reviewId)}.json`),value,assertFrontierBenchmarkHardGateReview);return value}
export async function loadFrontierBenchmarkHardGateReview(value:string){const review=await readJson(join(await root(),"frontier-hard-gate-reviews",`${id(value)}.json`));assertFrontierBenchmarkHardGateReview(review);return review}
export async function listFrontierBenchmarkHardGateReviews(){const values:FrontierBenchmarkHardGateReviewV1[]=[];for(const name of await files("frontier-hard-gate-reviews")){const value=await readJson(join(await root(),"frontier-hard-gate-reviews",name));assertFrontierBenchmarkHardGateReview(value);values.push(value)}return values.sort((a,b)=>a.order-b.order)}
export async function quarantineFrontierBenchmarkHardGateReview(reviewId:string){const value=id(reviewId),source=join(await root(),"frontier-hard-gate-reviews",`${value}.json`),targetDir=join(await root(),"frontier-invalid-hard-gate-reviews"),target=join(targetDir,`INVALID-${value}.json`);await ensureDir(targetDir);const review=await readJson(source);assertFrontierBenchmarkHardGateReview(review);await rename(source,target);return review}
export async function saveTwoWayBlindReview(value:DiscoveryStudioTwoWayBlindReviewV1){assertTwoWayBlindReview(value);await atomicJson(join(await root(),"two-way-reviews",`${id(value.twoWayReviewId)}.json`),value,assertTwoWayBlindReview);return value}
export async function loadTwoWayBlindReview(value:string){const review=await readJson(join(await root(),"two-way-reviews",`${id(value)}.json`));assertTwoWayBlindReview(review);return review}
export async function listTwoWayBlindReviews(){const values:DiscoveryStudioTwoWayBlindReviewV1[]=[];for(const name of await files("two-way-reviews")){const value=await readJson(join(await root(),"two-way-reviews",name));assertTwoWayBlindReview(value);values.push(value)}return values.sort((a,b)=>a.reviewName.localeCompare(b.reviewName))}

export async function saveScorecard(value:StudioScorecardV1,run:StudioRunV1){assertStudioScorecard(value,run);await atomicJson(join(await root(),"scorecards",`${id(value.runId)}.json`),value,candidate=>assertStudioScorecard(candidate,run));return value}
export async function loadScorecard(run:StudioRunV1){const path=join(await root(),"scorecards",`${id(run.runId)}.json`);try{const value=await readJson(path);assertStudioScorecard(value,run);return value}catch(error:any){if(error?.code==="ENOENT")return null;throw error}}
export async function deleteRun(value:string){const runId=id(value);await rm(join(await root(),"runs",`${runId}.json`),{force:true});await rm(join(await root(),"scorecards",`${runId}.json`),{force:true})}
export async function clearRunHistory(){const value=await root();for(const name of ["runs","scorecards","comparisons","exports","experiments"])await rm(join(value,name),{recursive:true,force:true})}
export async function resetStudio(){const value=await root();for(const name of ["runs","scorecards","comparisons","exports","experiments","scenarios"])await rm(join(value,name),{recursive:true,force:true})}
