import type { CanonicalSourceScopeBinding } from "../governance/canonicalScopeLineage";
import { resolveCurrentSourceScopeBinding } from "../governance/canonicalScopeLineage";
import type { GovernedScopeRef, ScopedGovernanceContext, ScopedGovernanceOperation } from "../governance/scopedGovernanceContext";
import type { SourceContentClock, SourceContentDevelopmentResetRequestV1, SourceContentDevelopmentResetReceiptV1, SourceContentReadRequestV1, SourceContentReadResultV1, SourceContentRepository, SourceContentWriteRequestV1, SourceContentWriteReceiptV1 } from "./sourceContentContracts";
import { SOURCE_CONTENT_CONTRACT_VERSION } from "./sourceContentContracts";
import { decodeAndNormalizeSourceContent, sourceContentDigest, sourceContentStableSerialize } from "./sourceContentDeterminism";

export interface SourceBindingResolver {
  loadRevisions(input:{organizationId:string;sourceBindingId:string}):Promise<readonly CanonicalSourceScopeBinding[]>;
}
const localTypes=new Set(["pasted-text","plain-text-upload","markdown-upload","manual-takeaway"]);
function sameScope(left:GovernedScopeRef,right:GovernedScopeRef){return left.organizationId===right.organizationId&&left.type===right.type&&left.id===right.id;}
function deny():never{throw new Error("Governed source content access denied.");}

export class GovernedSourceContentService {
  constructor(private readonly repository:SourceContentRepository,private readonly bindings:SourceBindingResolver,private readonly clock:SourceContentClock){}
  private authorize(context:ScopedGovernanceContext,input:{organizationId:string;actorRef:string;purposeRef:string;operation:ScopedGovernanceOperation}){if(context.disposition!=="authorized"||context.organizationId!==input.organizationId||context.subjectId!==input.actorRef||context.operation!==input.operation||context.purpose!==input.purposeRef||context.temporal.mode!=="current")deny();}
  private async binding(input:{organizationId:string;sourceBindingId:string;purposeRef:string;at:string;context:ScopedGovernanceContext}){let current:CanonicalSourceScopeBinding|undefined;try{const revisions=await this.bindings.loadRevisions({organizationId:input.organizationId,sourceBindingId:input.sourceBindingId});current=resolveCurrentSourceScopeBinding(revisions,input.at);}catch{deny();}if(!current||current.bindingId!==input.sourceBindingId||current.organizationId!==input.organizationId||current.purposeRef!==input.purposeRef||current.availability!=="available"||!current.sourceType||!localTypes.has(current.sourceType)||!current.assertions.some(item=>sameScope(item.scope,input.context.requestedScope)))deny();return current;}
  async write(request:SourceContentWriteRequestV1):Promise<SourceContentWriteReceiptV1>{if(request.contractVersion!=="1"||!(["text/plain","text/markdown"] as unknown[]).includes(request.mediaType)||request.bytes.byteLength>1024*1024||!request.idempotencyKey.trim()||request.storedAt!==this.clock.now())deny();this.authorize(request.authorization,{organizationId:request.organizationId,actorRef:request.storedByActorRef,purposeRef:request.purposeRef,operation:"source-content:write"});const binding=await this.binding({organizationId:request.organizationId,sourceBindingId:request.sourceBindingId,purposeRef:request.purposeRef,at:request.storedAt,context:request.authorization});const {normalizedText}=decodeAndNormalizeSourceContent(request.bytes);const exactContentDigest=sourceContentDigest(request.bytes),normalizedContentDigest=sourceContentDigest(new TextEncoder().encode(normalizedText));if(binding.source.normalizedContentDigest!==normalizedContentDigest||(request.mediaType==="text/markdown")!==(binding.sourceType==="markdown-upload"))deny();const idempotencyKeyDigest=sourceContentDigest(request.idempotencyKey);const requestFingerprint=sourceContentDigest(sourceContentStableSerialize({organizationId:request.organizationId,sourceBindingId:request.sourceBindingId,purposeRef:request.purposeRef,mediaType:request.mediaType,exactContentDigest,normalizedContentDigest,storedAt:request.storedAt,storedByActorRef:request.storedByActorRef}));return this.repository.write({contractVersion:"1",organizationId:request.organizationId,sourceBindingId:request.sourceBindingId,purposeRef:request.purposeRef,mediaType:request.mediaType,bytes:request.bytes,storedAt:request.storedAt,storedByActorRef:request.storedByActorRef,expectedRepositoryRevision:request.expectedRepositoryRevision,exactContentDigest,normalizedContentDigest,idempotencyKeyDigest,requestFingerprint});}
  async read(request:SourceContentReadRequestV1):Promise<SourceContentReadResultV1>{const operation=request.authorization.operation;if(operation!=="source-content:read-for-proposal"&&operation!=="source-content:read-for-evidence-admission"&&operation!=="source-content:read-for-claim-support")deny();this.authorize(request.authorization,{organizationId:request.organizationId,actorRef:request.authorization.subjectId,purposeRef:request.purposeRef,operation});await this.binding({organizationId:request.organizationId,sourceBindingId:request.sourceBindingId,purposeRef:request.purposeRef,at:this.clock.now(),context:request.authorization});const stored=await this.repository.read(request.organizationId,request.sourceContentVersionId);if(!stored||stored.version.sourceBindingId!==request.sourceBindingId)deny();const {text}=decodeAndNormalizeSourceContent(stored.bytes);return{contractVersion:SOURCE_CONTENT_CONTRACT_VERSION,version:stored.version,bytes:stored.bytes,text};}
  async resetDevelopmentFixture(request:SourceContentDevelopmentResetRequestV1):Promise<SourceContentDevelopmentResetReceiptV1>{if(!["development","sandbox","test"].includes(request.environment)||this.clock.now()!==request.authorization.evaluatedAt)deny();this.authorize(request.authorization,{organizationId:request.organizationId,actorRef:request.actorRef,purposeRef:request.purposeRef,operation:"source-content:reset-development"});const removed=await this.repository.resetDevelopmentFixture(request.organizationId);const safe={contractVersion:SOURCE_CONTENT_CONTRACT_VERSION,organizationId:request.organizationId,removed,resetAt:this.clock.now()};return{...safe,receiptDigest:sourceContentDigest(sourceContentStableSerialize(safe))};}
}
