import { constants } from "node:fs";
import { chmod, lstat, mkdir, open, readFile, realpath, rename, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import type { ResolvedSourceContentWriteV1, SourceContentRepository, SourceContentRepositorySnapshotV1, SourceContentVersionV1, SourceContentWriteReceiptV1 } from "./sourceContentContracts";
import { SOURCE_CONTENT_CONTRACT_VERSION } from "./sourceContentContracts";
import { sourceContentDigest, sourceContentStableSerialize, sourceContentVersionId } from "./sourceContentDeterminism";

const SAFE_ID = /^[A-Za-z0-9_-]+$/;
const emptyRevision = null;
type Manifest = Omit<SourceContentRepositorySnapshotV1, "repositoryRevision">;

function safeId(value: string): string { if (!SAFE_ID.test(value)) throw new Error("Governed source content storage identifier is invalid."); return value; }
function unsignedManifest(organizationId: string, versions: SourceContentVersionV1[], idempotency: Manifest["idempotency"]) {
  return { contractVersion: SOURCE_CONTENT_CONTRACT_VERSION, organizationId, versions: [...versions].sort((a,b)=>a.sourceContentVersionId.localeCompare(b.sourceContentVersionId)), idempotency: [...idempotency].sort((a,b)=>a.idempotencyKeyDigest.localeCompare(b.idempotencyKeyDigest)) };
}
function manifest(organizationId: string, versions: SourceContentVersionV1[], idempotency: Manifest["idempotency"]): Manifest {
  const value=unsignedManifest(organizationId,versions,idempotency); return {...value,snapshotDigest:sourceContentDigest(sourceContentStableSerialize(value))};
}
function manifestBytes(value: Manifest): Uint8Array { return new TextEncoder().encode(`${sourceContentStableSerialize(value)}\n`); }
function receipt(version: SourceContentVersionV1, repositoryRevision: string, disposition: SourceContentWriteReceiptV1["disposition"]): SourceContentWriteReceiptV1 {
  const safe={contractVersion:SOURCE_CONTENT_CONTRACT_VERSION,organizationId:version.organizationId,sourceBindingId:version.sourceBindingId,sourceContentVersionId:version.sourceContentVersionId,mediaType:version.mediaType,byteLength:version.byteLength,exactContentDigest:version.exactContentDigest,normalizedContentDigest:version.normalizedContentDigest,repositoryRevision,disposition,storedAt:version.storedAt,storedByActorRef:version.storedByActorRef};
  return {...safe,receiptDigest:sourceContentDigest(sourceContentStableSerialize(safe))};
}

class FilesystemSourceContentRepository implements SourceContentRepository {
  constructor(private readonly root: string, private readonly defaultRoot: string) {
    if (!path.isAbsolute(root)) throw new Error("Governed source content root must be absolute.");
  }
  private organizationDirectory(id:string){return path.join(this.root,"organizations",safeId(id));}
  private manifestPath(id:string){return path.join(this.organizationDirectory(id),"manifest.json");}
  private blobPath(id:string,digest:string){if(!/^[a-f0-9]{64}$/.test(digest))throw new Error("Governed source content digest is invalid.");return path.join(this.organizationDirectory(id),"blobs",`${digest}.blob`);}
  private async rejectSymlink(target:string):Promise<void>{try{const status=await lstat(target);if(status.isSymbolicLink())throw new Error("Governed source content storage is unsafe.");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}}
  private async prepare(id:string):Promise<void>{await this.rejectSymlink(this.root);await mkdir(this.root,{recursive:true,mode:0o700});await this.rejectSymlink(this.root);const actualRoot=await realpath(this.root),actualParent=await realpath(path.dirname(this.root));if(actualRoot!==path.join(actualParent,path.basename(this.root)))throw new Error("Governed source content storage is aliased.");const organizations=path.join(this.root,"organizations");await this.rejectSymlink(organizations);await mkdir(organizations,{mode:0o700,recursive:true});const directory=this.organizationDirectory(id),blobs=path.join(directory,"blobs");await this.rejectSymlink(directory);await mkdir(blobs,{mode:0o700,recursive:true});for(const target of [this.root,organizations,directory,blobs]){await this.rejectSymlink(target);await chmod(target,0o700);}const actualDirectory=await realpath(directory),actualBlobs=await realpath(blobs);if(actualDirectory!==path.join(actualRoot,"organizations",safeId(id))||actualBlobs!==path.join(actualDirectory,"blobs"))throw new Error("Governed source content storage escaped its root.");}
  private async load(id:string):Promise<{value:Manifest;bytes:Uint8Array;revision:string}|null>{
    await this.prepare(id);const target=this.manifestPath(id);await this.rejectSymlink(target);
    try{const status=await lstat(target);if(!status.isFile()||(status.mode&0o777)!==0o600)throw new Error("Governed source content manifest integrity failed.");const bytes=new Uint8Array(await readFile(target));const parsed=JSON.parse(new TextDecoder().decode(bytes)) as Manifest;if(parsed.organizationId!==id||parsed.contractVersion!=="1")throw new Error("Governed source content manifest integrity failed.");const expected=manifest(id,parsed.versions,parsed.idempotency);if(sourceContentStableSerialize(expected)!==sourceContentStableSerialize(parsed)||sourceContentDigest(sourceContentStableSerialize(unsignedManifest(id,parsed.versions,parsed.idempotency)))!==parsed.snapshotDigest||!Buffer.from(bytes).equals(Buffer.from(manifestBytes(expected))))throw new Error("Governed source content manifest integrity failed.");return{value:parsed,bytes,revision:sourceContentDigest(bytes)};}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error;}
  }
  async inspectRevision(id:string){return (await this.load(id))?.revision??emptyRevision;}
  async write(input:ResolvedSourceContentWriteV1):Promise<SourceContentWriteReceiptV1>{
    const current=await this.load(input.organizationId);const entries=current?.value.idempotency??[];const prior=entries.find(item=>item.idempotencyKeyDigest===input.idempotencyKeyDigest);if(prior){if(prior.requestFingerprint!==input.requestFingerprint)throw new Error("Governed source content idempotency conflict.");const version=current!.value.versions.find(item=>item.sourceContentVersionId===prior.sourceContentVersionId);if(!version)throw new Error("Governed source content manifest integrity failed.");return receipt(version,current!.revision,"idempotent-replay");}
    if((current?.revision??null)!==input.expectedRepositoryRevision)throw new Error("Governed source content repository revision changed.");
    const versions=current?.value.versions??[];const duplicate=versions.find(item=>item.sourceBindingId===input.sourceBindingId&&item.exactContentDigest===input.exactContentDigest);
    let version=duplicate;
    if(!version){const id=sourceContentVersionId(input);const safe={contractVersion:SOURCE_CONTENT_CONTRACT_VERSION,organizationId:input.organizationId,sourceBindingId:input.sourceBindingId,sourceContentVersionId:id,mediaType:input.mediaType,byteLength:input.bytes.byteLength,exactContentDigest:input.exactContentDigest,normalizedContentDigest:input.normalizedContentDigest,storedAt:input.storedAt,storedByActorRef:input.storedByActorRef,idempotencyKeyDigest:input.idempotencyKeyDigest};version={...safe,storageIntegrityDigest:sourceContentDigest(sourceContentStableSerialize(safe))};
      const blob=this.blobPath(input.organizationId,input.exactContentDigest);await this.rejectSymlink(blob);try{await writeFile(blob,input.bytes,{flag:"wx",mode:0o600});}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;const status=await lstat(blob);if(!status.isFile()||(status.mode&0o777)!==0o600)throw new Error("Governed source content blob integrity failed.");const existing=new Uint8Array(await readFile(blob));if(sourceContentDigest(existing)!==input.exactContentDigest)throw new Error("Governed source content blob integrity failed.");}
    }
    const next=manifest(input.organizationId,duplicate?versions:[...versions,version], [...entries,{idempotencyKeyDigest:input.idempotencyKeyDigest,requestFingerprint:input.requestFingerprint,sourceContentVersionId:version.sourceContentVersionId}]);const bytes=manifestBytes(next);const temporary=`${this.manifestPath(input.organizationId)}.${input.idempotencyKeyDigest}.tmp`;await this.rejectSymlink(temporary);try{await unlink(temporary);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}const handle=await open(temporary,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);try{await handle.writeFile(bytes);await handle.sync();}finally{await handle.close();}await rename(temporary,this.manifestPath(input.organizationId));const revision=sourceContentDigest(bytes);return receipt(version,revision,duplicate?"exact-duplicate":"stored");
  }
  async read(organizationId:string,versionId:string){const current=await this.load(organizationId);if(!current)return null;const version=current.value.versions.find(item=>item.sourceContentVersionId===versionId);if(!version)return null;const blob=this.blobPath(organizationId,version.exactContentDigest);await this.rejectSymlink(blob);let bytes:Uint8Array;try{const status=await lstat(blob);if(!status.isFile()||(status.mode&0o777)!==0o600)throw new Error("Governed source content blob integrity failed.");bytes=new Uint8Array(await readFile(blob));}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")throw new Error("Governed source content blob integrity failed.");throw error;}if(bytes.byteLength!==version.byteLength||sourceContentDigest(bytes)!==version.exactContentDigest)throw new Error("Governed source content blob integrity failed.");const {storageIntegrityDigest,...safe}=version;if(sourceContentDigest(sourceContentStableSerialize(safe))!==storageIntegrityDigest)throw new Error("Governed source content metadata integrity failed.");return{version,bytes};}
  async resolveExactMetadata(organizationId:string,sourceBindingId:string,normalizedContentDigest:string){if(!/^[a-f0-9]{64}$/.test(normalizedContentDigest))throw new Error("Governed source content metadata resolution failed.");const current=await this.load(organizationId);if(!current)return null;const matches=current.value.versions.filter(item=>item.organizationId===organizationId&&item.sourceBindingId===sourceBindingId&&item.normalizedContentDigest===normalizedContentDigest);if(matches.length>1)throw new Error("Governed source content metadata resolution failed.");if(matches.length===0)return null;const version=matches[0]!,{storageIntegrityDigest,...safe}=version;if(sourceContentDigest(sourceContentStableSerialize(safe))!==storageIntegrityDigest)throw new Error("Governed source content metadata integrity failed.");return structuredClone(version);}
  async resetDevelopmentFixture(organizationId:string){if(path.resolve(this.defaultRoot)===path.resolve(this.root))throw new Error("Governed source content reset refused.");await this.rejectSymlink(this.root);const resolved=await realpath(this.root),temp=await realpath(tmpdir());if(!resolved.startsWith(`${temp}${path.sep}`)||!path.basename(resolved).startsWith("discovery-governed-source-content-"))throw new Error("Governed source content reset refused.");const directory=this.organizationDirectory(organizationId);await this.rejectSymlink(directory);try{await rm(directory,{recursive:true});return true;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return false;throw error;}}
}

export function createFilesystemSourceContentRepository(input:{root:string;environment:"development"|"sandbox"|"test";defaultRoot?:string}):SourceContentRepository{if(!["development","sandbox","test"].includes(input.environment))throw new Error("Governed source content filesystem storage is unavailable outside development.");return new FilesystemSourceContentRepository(path.resolve(input.root),path.resolve(input.defaultRoot??path.join(process.cwd(),".discovery-runtime/source-content")));}
