"use client";
import {useActionState,useState} from "react";
import {addFounderGovernedContextAction,type FounderAddContextActionState} from "../../../app/product-alpha/meetings/[seriesAddress]/actions";

const initial:FounderAddContextActionState={status:"idle",sourceCount:null,destination:null,message:null};
export function FounderAddGovernedContextForm({seriesAddress,currentSourceCount,question}:{seriesAddress:string;currentSourceCount:number;question:string}){
 const[files,setFiles]=useState<File[]>([]),[state,action,pending]=useActionState(addFounderGovernedContextAction.bind(null,seriesAddress),initial);
 if(state.status==="success")return <section aria-labelledby="context-added-heading" style={{marginTop:32,padding:20,border:"1px solid #c9b26b",borderRadius:12}}><h2 id="context-added-heading">Context added.</h2><p>Discovery preserved the original preparation and created an updated preparation using {state.sourceCount} governed sources.</p><p>The organization, question, meeting, occurrence, and access grants remain unchanged.</p><a href={state.destination??`/product-alpha/meetings/${seriesAddress}`}>Return to Meeting Home</a></section>;
 return <section aria-labelledby="add-context-heading" style={{marginTop:32,padding:20,border:"1px solid #d5cfbf",borderRadius:12}}><h2 id="add-context-heading">Add more context</h2><p>Add information that bears on this meeting’s existing question. Discovery will preserve the prior source scope and create an updated preparation with the new governed context.</p><p><strong>{currentSourceCount} governed source{currentSourceCount===1?" is":"s are"} currently connected.</strong></p><p>{question}</p><p>This does not create another question or meeting.</p><form action={action} style={{display:"grid",gap:14}}><input type="hidden" name="intent" value="add-governed-context"/><label>Choose 1–4 .txt or .md files<input type="file" name="files" multiple required accept=".txt,.md,text/plain,text/markdown" onChange={event=>setFiles(Array.from(event.target.files??[]).slice(0,4))}/></label>{files.map((file,index)=><label key={`${file.name}:${index}`}>Why should Discovery use {file.name}?<input name="sourcePurpose" required maxLength={500}/></label>)}<button type="submit" disabled={pending||files.length<1||files.length>4}>{pending?"Adding context…":"Add context and refresh preparation"}</button>{state.status==="error"&&<p role="alert">{state.message}</p>}</form></section>;
}
